### ISSUE TITLE
Regression: PT route 'Show on map' crashes

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#10255]
In latest nighly, not sure when it started: Calculate a PT route which finds at least one route, tap on its 'Show on map' button:

`Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke interface method 'void net.osmand.plus.measurementtool.graph.GraphAdapterHelper$RefreshMapCallback.refreshMap(boolean)' on a null object reference
	at net.osmand.plus.routepreparationmenu.RouteDetailsFragment.calculateLayout(RouteDetailsFragment.java:374)
	at net.osmand.plus.base.ContextMenuFragment$4.onGlobalLayout(ContextMenuFragment.java:965)
	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1070)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3185)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2200)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8999)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:996)
	at android.view.Choreographer.doCallbacks(Choreographer.java:794)
	at android.view.Choreographer.doFrame(Choreographer.java:729)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7860)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)`

**Comment by sonora** [comment]
Tapping 'Details' produces the same NPE. I guess we need to revisit this refactoring: https://github.com/osmandapp/OsmAnd/commit/38ebaccc288f3ee08bc84ef809b4740fe0ed2153
