### ISSUE TITLE
StrictMode violation when clicking position button

### ISSUE THREAD

**Issue by Phyks** [osmandapp/OsmAnd#10296]
Hi,

### Description

I get the following traceback in `adb logcat` when pressing the "get position" button in OSMAnd. Thought it might be worth reporting.

### How to reproduce?

Click the "get position" button, I get:

```
11-29 13:14:42.754  3889  3889 D StrictMode: StrictMode policy violation; ~duration=53 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65599 violation=2
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1440)
11-29 13:14:42.754  3889  3889 D StrictMode:    at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:251)
11-29 13:14:42.754  3889  3889 D StrictMode:    at java.io.File.exists(File.java:807)
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.app.SharedPreferencesImpl.writeToFile(SharedPreferencesImpl.java:665)
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.app.SharedPreferencesImpl.-wrap2(Unknown Source:0)
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.app.SharedPreferencesImpl$2.run(SharedPreferencesImpl.java:599)
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.app.SharedPreferencesImpl.enqueueDiskWrite(SharedPreferencesImpl.java:618)
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.app.SharedPreferencesImpl.-wrap0(Unknown Source:0)
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.app.SharedPreferencesImpl$EditorImpl.commit(SharedPreferencesImpl.java:534)
11-29 13:14:42.754  3889  3889 D StrictMode:    at net.osmand.plus.api.SettingsAPIImpl$1.commit(SettingsAPIImpl.java:70)
11-29 13:14:42.754  3889  3889 D StrictMode:    at net.osmand.plus.settings.backend.OsmandSettings.setLastKnownMapZoom(OsmandSettings.java:2954)
11-29 13:14:42.754  3889  3889 D StrictMode:    at net.osmand.plus.activities.MapActivity.onPauseActivity(MapActivity.java:1387)
11-29 13:14:42.754  3889  3889 D StrictMode:    at net.osmand.plus.activities.MapActivity.onPause(MapActivity.java:1353)
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.app.Activity.performPause(Activity.java:7153)
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1408)
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3901)
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3878)
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3852)
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3826)
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.app.ActivityThread.-wrap15(Unknown Source:0)
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1601)
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.os.Handler.dispatchMessage(Handler.java:106)
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.os.Looper.loop(Looper.java:164)
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.app.ActivityThread.main(ActivityThread.java:6494)
11-29 13:14:42.754  3889  3889 D StrictMode:    at java.lang.reflect.Method.invoke(Native Method)
11-29 13:14:42.754  3889  3889 D StrictMode:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
11-29 13:14:42.754  3889  3889 D StrictMode:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
11-29 13:14:42.754  3889  3889 D StrictMode: StrictMode policy violation; ~duration=52 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65599 violation=2
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1440)
11-29 13:14:42.754  3889  3889 D StrictMode:    at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:251)
11-29 13:14:42.754  3889  3889 D StrictMode:    at java.io.File.exists(File.java:807)
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.app.SharedPreferencesImpl.writeToFile(SharedPreferencesImpl.java:665)
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.app.SharedPreferencesImpl.-wrap2(Unknown Source:0)
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.app.SharedPreferencesImpl$2.run(SharedPreferencesImpl.java:599)
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.app.SharedPreferencesImpl.enqueueDiskWrite(SharedPreferencesImpl.java:618)
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.app.SharedPreferencesImpl.-wrap0(Unknown Source:0)
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.app.SharedPreferencesImpl$EditorImpl.commit(SharedPreferencesImpl.java:534)
11-29 13:14:42.754  3889  3889 D StrictMode:    at net.osmand.plus.api.SettingsAPIImpl$1.commit(SettingsAPIImpl.java:70)
11-29 13:14:42.754  3889  3889 D StrictMode:    at net.osmand.plus.settings.backend.OsmandSettings.setLastKnownMapElevation(OsmandSettings.java:2962)
11-29 13:14:42.754  3889  3889 D StrictMode:    at net.osmand.plus.activities.MapActivity.onPauseActivity(MapActivity.java:1388)
11-29 13:14:42.754  3889  3889 D StrictMode:    at net.osmand.plus.activities.MapActivity.onPause(MapActivity.java:1353)
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.app.Activity.performPause(Activity.java:7153)
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1408)
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3901)
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3878)
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3852)
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3826)
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.app.ActivityThread.-wrap15(Unknown Source:0)
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1601)
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.os.Handler.dispatchMessage(Handler.java:106)
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.os.Looper.loop(Looper.java:164)
11-29 13:14:42.754  3889  3889 D StrictMode:    at android.app.ActivityThread.main(ActivityThread.java:6494)
11-29 13:14:42.754  3889  3889 D StrictMode:    at java.lang.reflect.Method.invoke(Native Method)
11-29 13:14:42.754  3889  3889 D StrictMode:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
11-29 13:14:42.754  3889  3889 D StrictMode:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

### Your Environment
OsmAnd Version: 3.8.5 (from F-Droid)
Android/iOS version: Lineage OS 15.1 (Android 8.1) with microg
Device model: LG H870

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

Thanks!

**Comment by vcschapp** [comment]
I am observing the same logged stack trace today on a similar setup:

OsmAnd Version: 3.9.10
Android/iOS version: Lineage OS 18.1 (Android 11) with microg
Device model: Motorola Moto G5 "cedric " model XT1671

The issue seems to go away once my device has a GPS fix.

**Comment by derMart** [comment]
slightly different stacktrace on similar setup here, but not related to clicking the position button. It just happens when I open osmand:

OsmAnd Version: 4.0.9
Android Version: Lineage OS 17.1 (Android 10) wioth microg
Device: Sony Xperia XZ1 compact

This seems to come up whenever the osmand map activity is resumed or suspended

```
01-09 20:40:42.327  2334  2334 D StrictMode: StrictMode policy violation; ~duration=1 ms: android.os.strictmode.DiskReadViolation
01-09 20:40:42.327  2334  2334 D StrictMode: 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1556)
01-09 20:40:42.327  2334  2334 D StrictMode: 	at libcore.io.BlockGuardOs.access(BlockGuardOs.java:69)
01-09 20:40:42.327  2334  2334 D StrictMode: 	at libcore.io.ForwardingOs.access(ForwardingOs.java:73)
01-09 20:40:42.327  2334  2334 D StrictMode: 	at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7246)
01-09 20:40:42.327  2334  2334 D StrictMode: 	at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
01-09 20:40:42.327  2334  2334 D StrictMode: 	at java.io.File.exists(File.java:815)
01-09 20:40:42.327  2334  2334 D StrictMode: 	at android.app.SharedPreferencesImpl.writeToFile(SharedPreferencesImpl.java:713)
01-09 20:40:42.327  2334  2334 D StrictMode: 	at android.app.SharedPreferencesImpl.access$900(SharedPreferencesImpl.java:55)
01-09 20:40:42.327  2334  2334 D StrictMode: 	at android.app.SharedPreferencesImpl$2.run(SharedPreferencesImpl.java:647)
01-09 20:40:42.327  2334  2334 D StrictMode: 	at android.app.SharedPreferencesImpl.enqueueDiskWrite(SharedPreferencesImpl.java:666)
01-09 20:40:42.327  2334  2334 D StrictMode: 	at android.app.SharedPreferencesImpl.access$100(SharedPreferencesImpl.java:55)
01-09 20:40:42.327  2334  2334 D StrictMode: 	at android.app.SharedPreferencesImpl$EditorImpl.commit(SharedPreferencesImpl.java:585)
01-09 20:40:42.327  2334  2334 D StrictMode: 	at net.osmand.plus.api.SettingsAPIImpl$1.commit(SettingsAPIImpl.java:70)
01-09 20:40:42.327  2334  2334 D StrictMode: 	at net.osmand.plus.settings.backend.OsmandSettings.setLastStartPoint(OsmandSettings.java:964)
01-09 20:40:42.327  2334  2334 D StrictMode: 	at net.osmand.plus.settings.backend.OsmandSettings.setLastStartPoint(OsmandSettings.java:958)
01-09 20:40:42.327  2334  2334 D StrictMode: 	at net.osmand.plus.routing.RoutingHelperUtils.checkAndUpdateStartLocation(RoutingHelperUtils.java:169)
01-09 20:40:42.327  2334  2334 D StrictMode: 	at net.osmand.plus.routing.RoutingHelperUtils.checkAndUpdateStartLocation(RoutingHelperUtils.java:177)
01-09 20:40:42.327  2334  2334 D StrictMode: 	at net.osmand.plus.base.MapViewTrackingUtilities.updateLocation(MapViewTrackingUtilities.java:188)
01-09 20:40:42.327  2334  2334 D StrictMode: 	at net.osmand.plus.OsmAndLocationProvider.updateLocation(OsmAndLocationProvider.java:593)
01-09 20:40:42.327  2334  2334 D StrictMode: 	at net.osmand.plus.OsmAndLocationProvider.setLocation(OsmAndLocationProvider.java:804)
01-09 20:40:42.327  2334  2334 D StrictMode: 	at net.osmand.plus.OsmAndLocationProvider.access$200(OsmAndLocationProvider.java:56)
01-09 20:40:42.327  2334  2334 D StrictMode: 	at net.osmand.plus.OsmAndLocationProvider$2.onLocationResult(OsmAndLocationProvider.java:272)
01-09 20:40:42.327  2334  2334 D StrictMode: 	at net.osmand.plus.LocationServiceHelperImpl$NetworkListener.onLocationChanged(LocationServiceHelperImpl.java:43)
01-09 20:40:42.327  2334  2334 D StrictMode: 	at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:352)
01-09 20:40:42.327  2334  2334 D StrictMode: 	at android.location.LocationManager$ListenerTransport.access$000(LocationManager.java:275)
01-09 20:40:42.327  2334  2334 D StrictMode: 	at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:291)
01-09 20:40:42.327  2334  2334 D StrictMode: 	at android.os.Handler.dispatchMessage(Handler.java:107)
01-09 20:40:42.327  2334  2334 D StrictMode: 	at android.os.Looper.loop(Looper.java:214)
01-09 20:40:42.327  2334  2334 D StrictMode: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
01-09 20:40:42.327  2334  2334 D StrictMode: 	at java.lang.reflect.Method.invoke(Native Method)
01-09 20:40:42.327  2334  2334 D StrictMode: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
01-09 20:40:42.327  2334  2334 D StrictMode: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

**Comment by derMart** [comment]
have a look at
https://github.com/LineageOS/android_frameworks_base/blob/632a233028812dd2a69f58312b0563b68e233412/core/java/android/app/SharedPreferencesImpl.java#L639
or
https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/app/SharedPreferencesImpl.java#655
(so this is not Lineage specific, just regular AOSP code)

which states:
```
* @param postWriteRunnable if non-null, we're being called
*  from apply() and this is the runnable to run after
*   the write proceeds.  if null (from a regular commit()),
*   then we're allowed to do this disk write on the main
*   thread (which in addition to reducing allocations and
*   creating a background thread, this has the advantage that
*   we catch them in userdebug StrictMode reports to convert
*   them where possible to apply() ...)
```

So it seems android StrictMode does not like these regular commit() calls in https://github.com/osmandapp/OsmAnd/blob/f7153115769166cb387cf51b101beea611d94f9f/OsmAnd/src/net/osmand/plus/api/SettingsAPIImpl.java#L70
