### ISSUE TITLE
App crashes when sharing/exporting favorite bookmarks (GPX)

### ISSUE THREAD

**Issue by JamesDean829** [osmandapp/OsmAnd#10540]
Hello, 

I imported a gpx file to the bookmarks in OSMAnd Android.
when I try to share/export my group of bookmarks from OSMAnd (saved favourite locations), the app crashes.
There are about 850 locations.

When I remove all comments in the gpx-file, import it to OSMAnd and export it from there it works. The comments are about three english sentences without special signs, for every waypoint the comment is the same. 

Could it be that the app crashes, because the gpx is too big (280kb)? Because without the comments the export works. I tried many scenarios (removing waypoints with special characters, removing comments,...). And it only crashes if the file gets to big.

PS: Albeit from exporting, OSMand is quite good at working with the bookmarks. As a workaround it is possible to export the bookmarks by copying the file from android/data/net.osmand.plus/files/favourites.gpx.

**Device Info:**
Device : OnePlus2
Brand : OnePlus
Model : ONE A2001
Product : lineage_oneplus2
Build : lineage_oneplus2-userdebug 10 QQ3A.200805.001 eng.root.20201205.235139 dev-keys
Version : 10
App Version : OsmAnd~
Apk Version : 3.8.5 385

**Error Log:** 
Version  OsmAnd~ 3.8.5
07.01.2021 6:33:40
Apk Version : 3.8.5 385
Exception occured in thread Thread[main,5,main] : 
java.lang.RuntimeException: Failure from system
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1718)
	at android.app.Activity.startActivityForResult(Activity.java:5210)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:234)
	at androidx.fragment.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:791)
	at androidx.fragment.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:933)
	at androidx.fragment.app.Fragment.startActivity(Fragment.java:1185)
	at androidx.fragment.app.Fragment.startActivity(Fragment.java:1173)
	at net.osmand.plus.activities.FavoritesTreeFragment$13.onPostExecute(FavoritesTreeFragment.java:695)
	at net.osmand.plus.activities.FavoritesTreeFragment$13.onPostExecute(FavoritesTreeFragment.java:644)
	at android.os.AsyncTask.finish(AsyncTask.java:755)
	at android.os.AsyncTask.access$900(AsyncTask.java:192)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
Caused by: android.os.TransactionTooLargeException: data parcel size 1177024 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:511)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3847)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1712)
	... 18 more

**Comment by vshcherb** [comment]
Yes it's definitely related to the file cause it too big. Though we will check if there are other ways to share it. 

Workaround could be to find it location.
