### ISSUE TITLE
NPE handling track display

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#10749]
Not sure how to reproduce, but latest release produces this sometimes (with a number of tracks being visible on the map):

```
Version  OsmAnd~ 3.9.0#4142des
03.02.2021 12:26:05
Apk Version : 3.9.0#4142des 390
Exception occured in thread Thread[main,5,main] : 
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.osmand.plus/net.osmand.plus.activities.MapActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean net.osmand.plus.GpxSelectionHelper$SelectedGpxFile.isShowCurrentTrack()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3488)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3635)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2175)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7860)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean net.osmand.plus.GpxSelectionHelper$SelectedGpxFile.isShowCurrentTrack()' on a null object reference
	at net.osmand.plus.track.TrackMenuFragment.onCreate(TrackMenuFragment.java:222)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2586)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:838)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
	at androidx.fragment.app.FragmentManagerImpl.dispatchCreate(FragmentManagerImpl.java:2607)
	at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:235)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:316)
	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
	at net.osmand.plus.activities.MapActivity.onCreate(MapActivity.java:280)
	at android.app.Activity.performCreate(Activity.java:7955)
	at android.app.Activity.performCreate(Activity.java:7944)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3463)
	... 11 more
```

**Comment by alex-osm** [comment]
Fixed
