### ISSUE TITLE
NPE at SelectedGpxFile.isShowCurrentTrack

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#10820]
```
Version  OsmAnd+ 3.9.5
Apk Version : 3.9.5 395
Exception occured in thread Thread[main,5,main] : 
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.osmand.plus/net.osmand.plus.activities.MapActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean net.osmand.plus.GpxSelectionHelper$SelectedGpxFile.isShowCurrentTrack()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean net.osmand.plus.GpxSelectionHelper$SelectedGpxFile.isShowCurrentTrack()' on a null object reference
	at net.osmand.plus.track.TrackMenuFragment.onCreate(TrackMenuFragment.java:222)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2586)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:838)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
	at androidx.fragment.app.FragmentManagerImpl.dispatchCreate(FragmentManagerImpl.java:2607)
	at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:235)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:316)
	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
	at net.osmand.plus.activities.MapActivity.onCreate(MapActivity.java:280)
	at android.app.Activity.performCreate(Activity.java:7824)
	at android.app.Activity.performCreate(Activity.java:7813)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
	... 11 more
```

Unsure how to reproduce.

**Comment by Chumva** [comment]
This should be fixed here - https://github.com/osmandapp/OsmAnd/pull/10944
