### ISSUE TITLE
3.9 OsmAnd(Plan a route) is crashing

### ISSUE THREAD

**Issue by pawlosck** [osmandapp/OsmAnd#10854]
I am using non english OsmAnd, so my translation of options can be wrong.

### Description
I am using Broute as navigation backend

### How to reproduce?
1. Menu on the left side
2. Plan a route
3. Create new trace
4. Touch a map and select first point
5. Touch a map and select second point
6. Select "option" (bottom of screen)
7. Change "Road beetwen points" from "straight line" to "pedestrian"
8. Touch "gearwheel" (options) -> crash (reproducible 100%)

### Your Environment
OsmAnd Version: 3.9.4
Android/iOS version: 9 (original, not rooted)
Device model: Samsung Galaxy S8

**Maps used (online or offline):**   
Offline

**Comment by vshcherb** [comment]
Not reproducible and it's already 3.9.6 available. please send the crash log or exception.log from device.

**Comment by pawlosck** [comment]
Version  OsmAnd~ 3.9.4
12.02.2021 4:23:53
Apk Version : 3.9.4 394
Exception occured in thread Thread[main,5,main] :
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Map net.osmand.router.GeneralRouter.getParameters()' on a null object reference
    at net.osmand.plus.routepreparationmenu.RouteOptionsBottomSheet.getReliefParameters(RouteOptionsBottomSheet.java:628)
    at net.osmand.plus.routepreparationmenu.RouteOptionsBottomSheet.onCreate(RouteOptionsBottomSheet.java:166)
    at androidx.fragment.app.Fragment.performCreate(Fragment.java:2586)
    at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:838)
    at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
    at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
    at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
    at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
    at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
    at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
    at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
    at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7050)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by pawlosck** [comment]
Problem is connected with brouter, becuase when I change navigation from brouter to osmand, then is ok.

**Comment by vshcherb** [comment]
3.9.6

**Comment by Chumva** [comment]
This should be fixed here - https://github.com/osmandapp/OsmAnd/commit/0083b7d0e14b64d4fa908ead656ae2815783b8f3
