### ISSUE TITLE
No map is displayed if `default.render.xml` is empty

### ISSUE THREAD

**Issue by Massedil** [osmandapp/OsmAnd#10935]
### Description

After updating OsmAnd, I faced an empty map.

I tried to change the location of OsmAnd map file from external SD card to internal storage and downloading again the world map. The world map was well displayed.

So I tried to find what was the differences between the SD folder and the internal folder.

I found that my `default.render.xml` file was here but empty (0 byte) (`offroad.render.xml` and `topo.render.xml` was also 0 bytes).

I replaced `default.render.xml` with the one from the internal folder and it solved my problem.

### How to reproduce?

Just put an empty `default.render.xml` file.

(I don't know how I have done to have this file empty inside the OsmAnd app. Is it possible it was during the update process ?)

### Expected

The user interface leave me without any help message like if everything was correct.

I think at least a message saying that the data folder is corrupted can be helpful.

The best would be to have an option to restore the `default.render.xml` state.

### Your Environment
OsmAnd Version: 3.9.5
Android/iOS version: LineageOS 17.1 / Android 10
Device model: Samsung Galaxy S5

**Maps used (online or offline):**  

All offline maps, so for example : the world base map.

---

Don't know if this can helps :

```
Version  OsmAnd~ 3.5.5
01.01.2020 5:25:45
Exception occured in thread Thread[main,5,main] : 
java.lang.RuntimeException: android.os.DeadSystemException
	at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:390)
	at android.location.LocationManager$ListenerTransport.access$000(LocationManager.java:300)
	at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:316)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: android.os.DeadSystemException
	... 9 more
Version  OsmAnd~ 3.7.3
15.06.2020 7:21:16
Apk Version : 3.7.3 373
Exception occured in thread Thread[main,5,main] : 
java.lang.RuntimeException: Unable to resume activity {net.osmand.plus/net.osmand.plus.activities.MapActivity}: java.util.ConcurrentModificationException
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3822)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3854)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:860)
	at net.osmand.plus.poi.PoiUIFilter.fillPoiAdditionals(PoiUIFilter.java:640)
	at net.osmand.plus.poi.PoiUIFilter.updateTypesToAccept(PoiUIFilter.java:626)
	at net.osmand.plus.poi.PoiUIFilter.<init>(PoiUIFilter.java:94)
	at net.osmand.plus.poi.PoiFiltersHelper.getTopDefinedPoiFilters(PoiFiltersHelper.java:292)
	at net.osmand.plus.poi.PoiFiltersHelper.getFilterById(PoiFiltersHelper.java:214)
	at net.osmand.plus.poi.PoiFiltersHelper.getFilterById(PoiFiltersHelper.java:207)
	at net.osmand.plus.poi.PoiFiltersHelper.loadSelectedPoiFilters(PoiFiltersHelper.java:596)
	at net.osmand.plus.activities.MapActivity.updateApplicationModeSettings(MapActivity.java:1453)
	at net.osmand.plus.activities.MapActivity.onResume(MapActivity.java:827)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1412)
	at android.app.Activity.performResume(Activity.java:7300)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3814)
	... 11 more
Version  OsmAnd~ 3.7.4
12.07.2020 3:54:25
Exception occured in thread Thread[main,5,main] : 
java.lang.RuntimeException: Unable to resume activity {net.osmand.plus/net.osmand.plus.activities.MapActivity}: java.lang.RuntimeException: android.os.DeadSystemException
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3822)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3854)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.RuntimeException: android.os.DeadSystemException
	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1009)
	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:561)
	at net.osmand.plus.OsmAndLocationProvider.resumeAllUpdates(OsmAndLocationProvider.java:247)
	at net.osmand.plus.activities.MapActivity.onResume(MapActivity.java:838)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1412)
	at android.app.Activity.performResume(Activity.java:7300)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3814)
	... 11 more
Caused by: android.os.DeadSystemException
	... 18 more
Version  OsmAnd~ 3.8.3
13.11.2020 12:08:19
Exception occured in thread Thread[main,5,main] : 
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.osmand.plus/net.osmand.plus.activities.MapActivity}: java.lang.RuntimeException: android.os.DeadSystemException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.RuntimeException: android.os.DeadSystemException
	at android.location.LocationManager.getProviders(LocationManager.java:455)
	at net.osmand.plus.OsmAndLocationProvider.getFirstTimeRunDefaultLocation(OsmAndLocationProvider.java:391)
	at net.osmand.plus.activities.DayNightHelper.getSunriseSunset(DayNightHelper.java:113)
	at net.osmand.plus.activities.DayNightHelper.isNightModeForProfile(DayNightHelper.java:91)
	at net.osmand.plus.activities.DayNightHelper.isNightModeForMapControlsForProfile(DayNightHelper.java:64)
	at net.osmand.plus.activities.DayNightHelper.isNightModeForMapControls(DayNightHelper.java:59)
	at net.osmand.plus.mapcontextmenu.BaseMenuController.updateNightMode(BaseMenuController.java:53)
	at net.osmand.plus.mapcontextmenu.BaseMenuController.init(BaseMenuController.java:31)
	at net.osmand.plus.mapcontextmenu.BaseMenuController.<init>(BaseMenuController.java:24)
	at net.osmand.plus.mapcontextmenu.other.MapMultiSelectionMenu.<init>(MapMultiSelectionMenu.java:96)
	at net.osmand.plus.mapcontextmenu.MapContextMenu.setMapActivity(MapContextMenu.java:165)
	at net.osmand.plus.activities.MapActivity.onCreate(MapActivity.java:273)
	at android.app.Activity.performCreate(Activity.java:7144)
	at android.app.Activity.performCreate(Activity.java:7135)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
	... 11 more
Caused by: android.os.DeadSystemException
	... 27 more
```

**Comment by vshcherb** [comment]
That's correct behavior, there are valid examples in osmand-resources repo
