### ISSUE TITLE
3.9.6 (Google Play beta) crash on sharing GPX file

### ISSUE THREAD

**Issue by mandree** [osmandapp/OsmAnd#10970]
### Description
OsmAnd+ crashed while trying to share a recorded .gpx track. This track MAY be incomplete, sharing to SyncThing or Total Commander did not come up with a complete XML file, as confirmed both by GPXSee as well as a text editor.

### How to reproduce?
unknown

### Your Environment
OsmAnd Version: 3.9.6
Android/iOS version: 11 w/ 2021-01-01 Google Play and Security Patch levels
Device model: Samsung Galaxy S10 SM-G973F/DS (Germany)

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

exception.log contents that might be related:
```
Version  OsmAnd+ 3.9.6
21.02.2021 6:58:42
Apk Version : 3.9.6 396
Exception occured in thread Thread[main,5,main] : 
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.get(ArrayList.java:437)
	at net.osmand.plus.myplaces.AvailableGPXFragment$GpxIndexesAdapter.getChild(AvailableGPXFragment.java:1070)
	at net.osmand.plus.myplaces.AvailableGPXFragment$GpxIndexesAdapter.getChildView(AvailableGPXFragment.java:1086)
	at android.widget.ExpandableListConnector.getView(ExpandableListConnector.java:451)
	at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:234)
	at android.widget.AbsListView.obtainView(AbsListView.java:2629)
	at android.widget.ListView.makeAndAddView(ListView.java:2224)
	at android.widget.ListView.fillDown(ListView.java:826)
	at android.widget.ListView.fillSpecific(ListView.java:1539)
	at android.widget.ListView.layoutChildren(ListView.java:1923)
	at android.widget.AbsListView.onLayout(AbsListView.java:2405)
	at android.view.View.layout(View.java:24489)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:24489)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
	at android.view.View.layout(View.java:24489)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24489)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:24489)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24489)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at androidx.appcompat.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:530)
	at android.view.View.layout(View.java:24489)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24489)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:24489)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1211)
	at android.view.View.layout(View.java:24489)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4148)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3583)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2519)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9775)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
	at android.view.Choreographer.doCallbacks(Choreographer.java:809)
	at android.view.Choreographer.doFrame(Choreographer.java:744)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8425)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```

**Comment by cepprice** [comment]
@mandree Please try latest Google Play version and check whether Osmand craches or not on your "incomplete" GPX-file and another GPX-files. If you will get error, please provide log file right after crash (logs that you provided are related to another problem). I was trying to reproduce your problem, but got no error.

**Comment by mandree** [comment]
Sorry for providing a useless exception.log. Downloading the same recorded track (recorded by 3.9.6) through ADB (Android debug bridge) got me the complete file, so something about sharing wasn't right.

I have updated the Android in the meanwhile, it's now at the 2021-02-01 security patch level from Samsung.

With osmand+ 3.9.9 google-play, I don't see crashes, but still all sorts of applications fail with sharing (older 3.9.x versions also failed). 

Signal claims that more than one file were only supported for images (but I am trying to share one single .gpx track), Syncthing and KDE-connect error out and claim to be unable to share or 0 files saved; Bluetooth 2.1 sharing to a Fedora 33 Linux PC however appears to work.

Feel free to rename the summary accordingly.

**Comment by mandree** [comment]
So... this appears to be a wider issue, not specific to GPX: for instance, I cannot share the logcat.log either, same symptoms; when sharing, K9 mail doesn't have an attachment at all, FairEmail has it but claims it has not been downloaded.

This is with OsmAnd+ (paid) 3.9.10 from the Google Play Store. I think I can grab the files via ADB if needed, anything specific that would still be useful at this point without a crash?
