### ISSUE TITLE
OsmAnd crashes when too many files are in the settings export

### ISSUE THREAD

**Issue by jensMF** [osmandapp/OsmAnd#10976]
### Description
When I try to export settings and include my tracks OsmAnd crashes with a FileNotFoundException: ... (Too many open files).
Here is the logcat:
```
02-22 13:03:48.277 E/net.osmand(28241): SettingsHelper Failed to set input stream from file: Sat.gpx
02-22 13:03:48.277 E/net.osmand(28241): java.io.FileNotFoundException: /storage/emulated/0/osmand/tracks/rec/Sat.gpx (Too many open files)
02-22 13:03:48.277 E/net.osmand(28241): 	at java.io.FileInputStream.open0(Native Method)
02-22 13:03:48.277 E/net.osmand(28241): 	at java.io.FileInputStream.open(FileInputStream.java:200)
02-22 13:03:48.277 E/net.osmand(28241): 	at java.io.FileInputStream.<init>(FileInputStream.java:150)
02-22 13:03:48.277 E/net.osmand(28241): 	at net.osmand.plus.settings.backend.backup.FileSettingsItem.getWriter(FileSettingsItem.java:318)
02-22 13:03:48.277 E/net.osmand(28241): 	at net.osmand.plus.settings.backend.backup.SettingsItem.writeToJson(SettingsItem.java:147)
02-22 13:03:48.277 E/net.osmand(28241): 	at net.osmand.plus.settings.backend.backup.FileSettingsItem.writeToJson(FileSettingsItem.java:209)
02-22 13:03:48.277 E/net.osmand(28241): 	at net.osmand.plus.settings.backend.backup.GpxSettingsItem.writeToJson(GpxSettingsItem.java:51)
02-22 13:03:48.277 E/net.osmand(28241): 	at net.osmand.plus.settings.backend.backup.SettingsItem.toJson(SettingsItem.java:158)
02-22 13:03:48.277 E/net.osmand(28241): 	at net.osmand.plus.settings.backend.backup.SettingsExporter.createItemsJson(SettingsExporter.java:104)
02-22 13:03:48.277 E/net.osmand(28241): 	at net.osmand.plus.settings.backend.backup.SettingsExporter.exportSettings(SettingsExporter.java:53)
02-22 13:03:48.277 E/net.osmand(28241): 	at net.osmand.plus.settings.backend.backup.SettingsHelper$ExportAsyncTask.doInBackground(SettingsHelper.java:250)
02-22 13:03:48.277 E/net.osmand(28241): 	at net.osmand.plus.settings.backend.backup.SettingsHelper$ExportAsyncTask.doInBackground(SettingsHelper.java:229)
```

here is the exception.log:
```
Version  OsmAnd+ 3.9.6
22.02.2021 13:04:00
Apk Version : 3.9.6 396
Exception occured in thread Thread[main,5,main] : 
java.lang.RuntimeException: Could not read input channel file descriptors from parcel.
	at android.view.InputChannel.nativeReadFromParcel(Native Method)
	at android.view.InputChannel.readFromParcel(InputChannel.java:148)
	at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:804)
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:744)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
	at android.widget.Toast$TN.handleShow(Toast.java:496)
	at android.widget.Toast$TN$1.handleMessage(Toast.java:400)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6499)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

### How to reproduce?
Go to settings -> export and choose My Places -> Tracks. (You need to have enough tracks I guess. I think more than 1024 should suffice but may be more is necessary. May be try to have 2k. I have about 1925 tracks.) 

### Your Environment
OsmAnd Version: OsmAnd+ 3.9.6
Android/iOS version: Android 8.1
Device model: Moto G5 plus

**Comment by androiddevkotlin** [comment]
Not reproduced with 3000 tracks on AVD and physical device: API 30 and API 27.

**Comment by vshcherb** [comment]
On Average file limit is but it's quite unclear problem cause the files being closed properly according to the code.
