### ISSUE TITLE
OsmAnd crashes on reading downloaded WikiVoyage files

### ISSUE THREAD

**Issue by aceman444** [osmandapp/OsmAnd#11328]
When I download the Europe Wikivoyage file (400MB after download) and then visit the Wikivoyage menuitem in the menu, OsmAnd seems to read or index the downloaded files. It takes a few seconds and then it crashes. This happens everytime when visiting the WikiVoyage section. When not visiting it, OsmAnd works fine.

The crash log (below) mentions out of memory condition, but the phone has 3GB of RAM and OsmAnd works fine with it (even on lower RAM devices). If 3GB or more of RAM are needed for a Wikivoyage file, that should be handled gracefully without crashing and reported to the user.

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: 10 (1st of Mar 2021 security patches)
Phone: 3GB RAM

Here is the crash log:
Apk Version : 3.9.10 400
Exception occured in thread Thread[AsyncTask #4,5,main] :
java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:399)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 44168 byte allocation with 38824 free bytes and 37KB until OOM, target footprint 536870912, growth limit 536870912
        at java.util.Arrays.copyOf(Arrays.java:3257)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
        at java.lang.StringBuilder.append(StringBuilder.java:137)
        at net.osmand.data.MapObject.unzipContent(MapObject.java:368)
        at net.osmand.data.Amenity.getAdditionalInfo(Amenity.java:100)
        at net.osmand.data.Amenity.getTagContent(Amenity.java:283)
        at net.osmand.data.Amenity.getDescription(Amenity.java:305)
        at net.osmand.plus.wikivoyage.data.TravelObfHelper.readArticle(TravelObfHelper.java:267)
        at net.osmand.plus.wikivoyage.data.TravelObfHelper.readArticles(TravelObfHelper.java:256)
        at net.osmand.plus.wikivoyage.data.TravelObfHelper.cacheTravelArticles(TravelObfHelper.java:193)
        at net.osmand.plus.wikivoyage.data.TravelObfHelper.loadPopularArticles(TravelObfHelper.java:152)
        at net.osmand.plus.wikivoyage.data.TravelObfHelper.initializeDataToDisplay(TravelObfHelper.java:113)
        at net.osmand.plus.wikivoyage.explore.WikivoyageExploreActivity$LoadWikivoyageData.doInBackground(WikivoyageExploreActivity.java:393)
        at net.osmand.plus.wikivoyage.explore.WikivoyageExploreActivity$LoadWikivoyageData.doInBackground(WikivoyageExploreActivity.java:379)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        ... 4 more

**Comment by Dima-1** [comment]
Is it crash only with Europe Wikivoyage file? Can you see default travel articles?

**Comment by vshcherb** [comment]
How many popular articles do you see / load ? and which are of them are displayed, please share screenshot.

**Comment by aceman444** [comment]
I see no articles. Just the existence of downloaded Europe file and visiting the Travel guides (beta) menu item, makes OsmAnd crash (after a few seconds) without showing any data or articles.

The Default travel articles file is downloaded (visible in Downloads), but I do not know how to 'see' inside of it.

**Comment by aceman444** [comment]
OK, I have tried to download Wikivoyage file of Australia-oceania. That worked, OsmAnd didn't crash when visiting Travel guides (beta) menu item. BUT there was nothing useful in that section anymore, no way to download more of the files. I tried to input some Australian cities into the search field, but nothing was found. So I do not know if the wikivoyage file is working in any way.

**Comment by aceman444** [comment]
Thank you, I will test it in a stable release.
