### ISSUE TITLE
Problem with show POI along the route 

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#11608]
### Description
When you set up show POI on the map and after that on navigation option select show POI along the route and start navigation then appears two issues:
1. POI does not display on the map anymore
2. There is no information about POI in voice navigation
### How to reproduce?
In driving profile:
1. On Configure map turn on POI overlay
2. Set a destination
3. Option ->Show along the route->turn on POI (it would not offer you to set up a distance and type of POI) 
4. Start navigation (all POI along the route would not be displayed and during navigation, you would not get voice information about POI)

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: Android 
Device model: Nokia 2.4

![image](https://user-images.githubusercontent.com/80623554/117144120-3cc50800-adba-11eb-9927-7b0d31146d7c.png)
![image](https://user-images.githubusercontent.com/80623554/117144195-52d2c880-adba-11eb-82e4-1b372267692c.png)
![image](https://user-images.githubusercontent.com/80623554/117144298-7138c400-adba-11eb-8585-069665ce590f.png)
![image](https://user-images.githubusercontent.com/80623554/117144267-6847f280-adba-11eb-83e3-0e3b43bc9451.png)

**Comment by anastasiia936** [comment]
Also, the problem with disappearing POI on the map exists in the Cycling profile.
Please, watch the attached video.
https://c.gmx.net/@334293370690082996/DXIrPsVSQeuQQO5KV9Zucw

**Comment by josef54** [comment]
Ich habe mich nochmal mit der Problematik beschäftigt und herausgefunden, wenn die POIs im Profil Fahrrad angezeigt werden und ich dann auf Navigieren gehe sie noch ca. eine Sekunde angezeigt werden. Wenn ich dann die Navigation verwerfe werden die POIs auch nicht mehr angezeigt. Ich muß Osmand beenden und stoppen dann werden die POIs wieder angezeigt.Handy Samsung A 51 Android 11.Mit freundlichen GrüßenJosef Kemper
--

**Comment by scaidermern** [comment]
I can confirm that both the POI overlay and "Show along the route" are broken.

The POIs from the POI overlay disappear (almost) completely when starting a navigation. During routing, only very few POIs from the POI overlay are still visible. Stopping the navigation doesn't fix this, only restarting OsmAnd fixes it.

"Show along the route" is similar. Sometimes it is not possible to select additional options (e.g. the distance) because OsmAnd displays "Calculating route..." although the route already has been calculated (second screenshot in the first post). And the behavior is the same as with the POI overlay, only very few POIs get shown and most of them are missing.

Also I get crashes from time to time when trying to use the "Show along the route" option:
```
Version  OsmAnd+ 3.9.10
08.05.2021 6:30:56
Apk Version : 3.9.10 400
Exception occured in thread Thread[AsyncTask #10,5,main] : 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'double net.osmand.data.LatLon.getLatitude()' on a null object reference
	at net.osmand.binary.BinaryMapPoiReaderAdapter.readPoiPoint(BinaryMapPoiReaderAdapter.java:739)
	at net.osmand.binary.BinaryMapPoiReaderAdapter.readPoiData(BinaryMapPoiReaderAdapter.java:660)
	at net.osmand.binary.BinaryMapPoiReaderAdapter.searchPoiIndex(BinaryMapPoiReaderAdapter.java:551)
	at net.osmand.binary.BinaryMapIndexReader.searchPoi(BinaryMapIndexReader.java:1382)
	at net.osmand.plus.resources.AmenityIndexRepositoryBinary.searchAmenitiesOnThePath(AmenityIndexRepositoryBinary.java:193)
	at net.osmand.plus.resources.ResourceManager.searchAmenitiesOnThePath(ResourceManager.java:933)
	at net.osmand.plus.poi.PoiUIFilter.searchAmenitiesOnThePath(PoiUIFilter.java:336)
	at net.osmand.plus.helpers.WaypointHelper.calculatePoi(WaypointHelper.java:636)
	at net.osmand.plus.helpers.WaypointHelper.recalculatePoints(WaypointHelper.java:572)
	at net.osmand.plus.helpers.WaypointHelper.enableWaypointType(WaypointHelper.java:266)
	at net.osmand.plus.routepreparationmenu.ShowAlongTheRouteBottomSheet$EnableWaypointsTypeTask.doInBackground(ShowAlongTheRouteBottomSheet.java:595)
	at net.osmand.plus.routepreparationmenu.ShowAlongTheRouteBottomSheet$EnableWaypointsTypeTask.doInBackground(ShowAlongTheRouteBottomSheet.java:579)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
```

**Comment by sigiesec** [comment]
I have the same issue, in the cycling profile. I wonder why the issue was closed? No reason was provided for that.

**Comment by scaidermern** [comment]
Well, it was automatically closed by a pull request. Meaning, that there have been code changes that should fix this problem. They are contained in the next release (4.0).

**Comment by sigiesec** [comment]
Ah sorry that wasn't visible in my GH client. Is there a plan when 4.0 is going to be released?

**Comment by scaidermern** [comment]
4.0.1 is currently as beta available from the play store. Not sure if there is a fixed release data, I guess it depends on how fast the tickets that are assigned to the 4.0 milestone can be resolved.

**Comment by vshcherb** [comment]
tomorrow 4.0.2 beta is coming
