### ISSUE TITLE
Crash (NPE) when matching track to road

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#12215]
OsmAnd 4.0.1 crashes when matching the following track to the road, in bicycle mode.

[bicycle.gpx](https://github.com/osmandapp/OsmAnd/files/6867628/bicycle.gpx.txt)

```
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'net.osmand.binary.BinaryMapRouteReaderAdapter$RouteTypeRule net.osmand.binary.BinaryMapRouteReaderAdapter$RouteRegion.quickGetEncodingRule(int)' on a null object reference
	at net.osmand.binary.RouteDataObject.getValue(RouteDataObject.java:843)
	at net.osmand.binary.RouteDataObject.calculateHeightArray(RouteDataObject.java:175)
	at net.osmand.binary.RouteDataObject.calculateHeightArray(RouteDataObject.java:168)
	at net.osmand.plus.measurementtool.MeasurementEditingContextUtils.fillPointsArray(MeasurementEditingContextUtils.java:58)
	at net.osmand.plus.measurementtool.MeasurementEditingContext.setPoints(MeasurementEditingContext.java:877)
	at net.osmand.plus.measurementtool.command.ApplyGpxApproximationCommand.applyApproximation(ApplyGpxApproximationCommand.java:96)
	at net.osmand.plus.measurementtool.command.ApplyGpxApproximationCommand.execute(ApplyGpxApproximationCommand.java:55)
	at net.osmand.plus.measurementtool.command.MeasurementCommandManager.execute(MeasurementCommandManager.java:35)
	at net.osmand.plus.measurementtool.MeasurementToolFragment.onGpxApproximationDone(MeasurementToolFragment.java:2152)
	at net.osmand.plus.measurementtool.GpxApproximationFragment.onApproximationFinished(GpxApproximationFragment.java:489)
	at net.osmand.plus.measurementtool.GpxApproximationFragment.access$600(GpxApproximationFragment.java:47)
	at net.osmand.plus.measurementtool.GpxApproximationFragment$6$1.run(GpxApproximationFragment.java:456)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

The crash is reproducible.

**Comment by fridgeS3** [comment]
i can confirm this, here the same with bycycle

**Comment by vshcherb** [comment]
```
3.07.2021 1:22:28
Apk Version : 4.0.1 401
Exception occured in thread Thread[main,5,main] : 
java.lang.IndexOutOfBoundsException: Index: 94, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at net.osmand.binary.BinaryMapRouteReaderAdapter$RouteRegion.quickGetEncodingRule(BinaryMapRouteReaderAdapter.java:349)
	at net.osmand.binary.RouteDataObject.getValue(RouteDataObject.java:843)
	at net.osmand.binary.RouteDataObject.calculateHeightArray(RouteDataObject.java:175)
	at net.osmand.binary.RouteDataObject.calculateHeightArray(RouteDataObject.java:168)
	at net.osmand.plus.measurementtool.MeasurementEditingContextUtils.fillPointsArray(MeasurementEditingContextUtils.java:58)
	at net.osmand.plus.measurementtool.MeasurementEditingContext.setPoints(MeasurementEditingContext.java:877)
	at net.osmand.plus.measurementtool.command.ApplyGpxApproximationCommand.applyApproximation(ApplyGpxApproximationCommand.java:96)
	at net.osmand.plus.measurementtool.command.ApplyGpxApproximationCommand.execute(ApplyGpxApproximationCommand.java:55)
	at net.osmand.plus.measurementtool.command.MeasurementCommandManager.execute(MeasurementCommandManager.java:35)
	at net.osmand.plus.measurementtool.MeasurementToolFragment.onGpxApproximationDone(MeasurementToolFragment.java:2152)
	at net.osmand.plus.measurementtool.GpxApproximationFragment.onApproximationFinished(GpxApproximationFragment.java:489)
	at net.osmand.plus.measurementtool.GpxApproximationFragment.access$600(GpxApproximationFragment.java:47)
	at net.osmand.plus.measurementtool.GpxApproximationFragment$6$1.run(GpxApproximationFragment.java:456)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8010)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
Version  OsmAnd+ 4.0.1
23.07.2021 6:12:39
Apk Version : 4.0.1 401
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'net.osmand.binary.BinaryMapRouteReaderAdapter$RouteTypeRule net.osmand.binary.BinaryMapRouteReaderAdapter$RouteRegion.quickGetEncodingRule(int)' on a null object reference
	at net.osmand.binary.RouteDataObject.getValue(RouteDataObject.java:843)
	at net.osmand.binary.RouteDataObject.calculateHeightArray(RouteDataObject.java:175)
	at net.osmand.binary.RouteDataObject.calculateHeightArray(RouteDataObject.java:168)
	at net.osmand.plus.measurementtool.MeasurementEditingContextUtils.fillPointsArray(MeasurementEditingContextUtils.java:58)
	at net.osmand.plus.measurementtool.MeasurementEditingContext.setPoints(MeasurementEditingContext.java:877)
	at net.osmand.plus.measurementtool.command.ApplyGpxApproximationCommand.applyApproximation(ApplyGpxApproximationCommand.java:96)
```

**Comment by vshcherb** [comment]
Crahs should be fixed in 4.0.2 and nightly.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/commit/ecd1beef7c0eb844e3a6d3dbf0a6a3b7b460ae84

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-core-legacy/commit/7df45adb3e41c3a75622b3e8cf3dffb32285d02c

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd/pull/12285
