### ISSUE TITLE
Crash on import of profile settings

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#12401]
When trying to import a backup from another device (containing profile settings) the following exception occurs:

```
Version  OsmAnd+ 4.0.3
06.08.2021 12:03:03
Apk Version : 4.0.3 403
Exception occured in thread Thread[main,5,main] : 
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:860)
	at net.osmand.plus.settings.backend.ApplicationMode$3.lambda$stateChanged$0(ApplicationMode.java:544)
	at net.osmand.plus.settings.backend.-$$Lambda$ApplicationMode$3$IfciOaZD_J0p5cLg7hDaK-TrBjY.run(Unknown Source:0)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by scaidermern** [comment]
Regarding the `ConcurrentModificationException`: Importing each profile one by one works.

**Comment by Chumva** [comment]
Try to update to 4.0.4, it should be fixed there.

**Comment by scaidermern** [comment]
Works with 4.0.4. 👍
