### ISSUE TITLE
NavigationService crash

### ISSUE THREAD

**Issue by HraD** [osmandapp/OsmAnd#12444]
### Description
Version  OsmAnd 4.0.0
11.08.2021 12:28:48
Apk Version : 4.0.0 400
Exception occured in thread Thread[main,5,main] : 
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{cb20a27 u0 net.osmand/.plus.}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2240)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8512)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

### How to reproduce?

Calculate route, then select "Simulate navigation", then start new navigation via AIDL command with force=true flag:
mAidlHelper.navigate("checkpoint1",latitude1, longitude1, 
"checkpoint2", latitude2, longitude, 
"car", force = true, needLocationPermission = true)

### Your Environment
OsmAnd Version: 4.0.0
Android/iOS version: Android 11, One UI 3.1
Device model: Samsung Galaxy Tab S6 Lite

**Maps used (online or offline):**   
Not related to maps

**Comment by vshcherb** [comment]
Probably this issue is related only to AIDL, so we need to deal with it somehow there.
Do you have more information about does it happen or not happen with/without simulation, with/without AIDL.

**Comment by eldk** [comment]
Hello,

I got this error using Osmand in real situation - the app crash while using it or after been restarted frequently on a few kilometers. It can be reproduced while simulating navigation too. This is a new device used since one day.

Device : L762
Brand : Crosscall
Model : Core-X4
Product : L762
Build : QKQ1.200407.002 release-keys
Version : 10
App Version : OsmAnd~
Apk Version : 4.4.7 440703

```
ersion  OsmAnd~ 4.3.12
04.08.2023 10:53:18
Apk Version : 4.3.12 431203
Exception occured in thread Thread[main,5,main] : 
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{e8f02a7 u0 net.osmand.plus/.NavigationService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1946)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7402)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
Version  OsmAnd~ 4.4.7
04.08.2023 11:21:50
Apk Version : 4.4.7 440703
Exception occured in thread Thread[main,5,main] : 
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{d3da211 u0 net.osmand.plus/.NavigationService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1946)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7402)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
Version  OsmAnd~ 4.4.7
04.08.2023 11:29:10
Apk Version : 4.4.7 440703
Exception occured in thread Thread[main,5,main] : 
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{a50b3fc u0 net.osmand.plus/.NavigationService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1946)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7402)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
````

Thanks,

Eric

**Comment by DmitryAlexei** [comment]
try updating the app to the latest version (4.5.9 from Google play)
you write you have 4.4.7 and in crash log there is 4.3.12, that is quite outdated
