### ISSUE TITLE
Unable to Update Android-Full

### ISSUE THREAD

**Issue by MAlfare** [osmandapp/OsmAnd#12634]
Hi!
Problem occurs on two Devices running Android 4.3 and 4.4
Does not occur on a device running Android 8.1

Trying to update via "Builds" ends in 
#
Parsing error
A problem occurred while parsing the packet
#
after download.
 Last time it worked: update to OsmAnd ~ 4.1.0 # 32615 m, from 2021-08-27
 Does not work at least since:  OsmAnd ~ 4.1.0 # 32624 m

Last entry in exeptionlog:
Version  OsmAnd~ 4.1.0#32613m
29.08.2021 4:50:52
Apk Version : 4.1.0#32613m 410
Exception occured in thread Thread[Timer-0,5,main] : 
java.lang.IllegalStateException: Must be called from main thread of fragment host
	at androidx.fragment.app.FragmentManagerImpl.ensureExecReady(FragmentManagerImpl.java:1668)
	at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1692)
	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:299)
	at net.osmand.plus.activities.MapActivity.removeFragment(MapActivity.java:428)
	at net.osmand.plus.activities.MapActivity.dismissSecondSplashScreen(MapActivity.java:1023)
	at net.osmand.plus.activities.MapActivity.access$900(MapActivity.java:177)
	at net.osmand.plus.activities.MapActivity$10.run(MapActivity.java:900)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

**Comment by vshcherb** [comment]
This issue won't be fixed cause starting from 4.1 minimum app version will be Android 7.0 (required for Android Auto) - API code 24

**Comment by MAlfare** [comment]
This is really really bad news :-(
