### ISSUE TITLE
crashes on Android 2.3.7

### ISSUE THREAD

**Issue by alexxtasi** [osmandapp/Osmand#1275]
hi all
I used to use OsmAnd on Android 2.3 with no problems.
Now I installed OsmAnd (the latest free version) on Android 2.3.7 (CyanogenMod 7.2.0) but crashes really often, making it unusable!

Before installing it, I deleted it's old settings folder (osmand) and also after installation I "Moved to SD" the app.
At first run I downloaded maps, but after that the app crashes almost whenever I open it and "click" somewhere...

any suggestions ?

**Comment by vshcherb** [comment]
The crash log is needed

**Comment by alexxtasi** [comment]
I filtered the catlog's log with ```osmand``` to reduce the lines.... don't know if it suits

```
05-27 00:50:37.160 I/ActivityManager(  199): Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=net.osmand/.plus.activities.MapActivity } from pid 298
05-27 00:50:37.390 I/ActivityManager(  199): Start proc net.osmand for activity net.osmand/.plus.activities.MapActivity: pid=3060 uid=10072 gids={3003, 1015, 1006}
05-27 00:50:41.320 I/dalvikvm( 3060): Could not find method net.osmand.plus.OsmandApplication.getNoBackupFilesDir, referenced from method net.osmand.plus.OsmandSettings.getNoBackupPath
05-27 00:50:41.320 W/dalvikvm( 3060): VFY: unable to resolve virtual method 49862: Lnet/osmand/plus/OsmandApplication;.getNoBackupFilesDir ()Ljava/io/File;
05-27 00:50:41.320 D/dalvikvm( 3060): VFY: dead code 0x0005-0006 in Lnet/osmand/plus/OsmandSettings;.getNoBackupPath ()Ljava/io/File;
05-27 00:50:41.330 I/dalvikvm( 3060): Could not find method net.osmand.plus.OsmandApplication.getExternalFilesDirs, referenced from method net.osmand.plus.OsmandSettings.getExternalStorageDirectoryV19
05-27 00:50:41.330 W/dalvikvm( 3060): VFY: unable to resolve virtual method 49854: Lnet/osmand/plus/OsmandApplication;.getExternalFilesDirs (Ljava/lang/String;)[Ljava/io/File;
05-27 00:50:41.330 D/dalvikvm( 3060): VFY: dead code 0x0037-004b in Lnet/osmand/plus/OsmandSettings;.getExternalStorageDirectoryV19 (Lnet/osmand/ValueHolder;)Ljava/io/File;
05-27 00:50:41.330 D/dalvikvm( 3060): VFY: dead code 0x004e-0076 in Lnet/osmand/plus/OsmandSettings;.getExternalStorageDirectoryV19 (Lnet/osmand/ValueHolder;)Ljava/io/File;
05-27 00:50:41.460 W/System.err( 3060): Startup service net.osmand.plus.routing.RoutingHelper took too long 14 ms
05-27 00:50:41.630 I/net.osmand( 3060): ResourceManager Tiles to load in memory : 45.0
05-27 00:50:41.630 W/System.err( 3060): Startup service net.osmand.plus.resources.ResourceManager took too long 171 ms
05-27 00:50:41.670 W/System.err( 3060): Startup service net.osmand.plus.helpers.WaypointHelper took too long 23 ms
05-27 00:50:41.820 E/net.osmand( 3060): GPXUtilities Error reading gpx
05-27 00:50:41.820 E/net.osmand( 3060): java.io.FileNotFoundException: /data/data/net.osmand/files/favourites_bak.gpx (No such file or directory)
05-27 00:50:41.820 E/net.osmand( 3060): 	at org.apache.harmony.luni.platform.OSFileSystem.open(Native Method)
05-27 00:50:41.820 E/net.osmand( 3060): 	at dalvik.system.BlockGuard$WrappedFileSystem.open(BlockGuard.java:232)
05-27 00:50:41.820 E/net.osmand( 3060): 	at java.io.FileInputStream.<init>(FileInputStream.java:80)
05-27 00:50:41.820 E/net.osmand( 3060): 	at net.osmand.plus.GPXUtilities.loadGPXFile(GPXUtilities.java:787)
05-27 00:50:41.820 E/net.osmand( 3060): 	at net.osmand.plus.FavouritesDbHelper.loadGPXFile(FavouritesDbHelper.java:421)
05-27 00:50:41.820 E/net.osmand( 3060): 	at net.osmand.plus.FavouritesDbHelper.loadFavorites(FavouritesDbHelper.java:68)
05-27 00:50:41.820 E/net.osmand( 3060): 	at net.osmand.plus.AppInitializer.startApplicationBackground(AppInitializer.java:348)
05-27 00:50:41.820 E/net.osmand( 3060): 	at net.osmand.plus.AppInitializer.access$200(AppInitializer.java:55)
05-27 00:50:41.820 E/net.osmand( 3060): 	at net.osmand.plus.AppInitializer$7.run(AppInitializer.java:558)
05-27 00:50:41.820 E/net.osmand( 3060): 	at java.lang.Thread.run(Thread.java:1019)
05-27 00:50:41.840 E/net.osmand( 3060): GPXUtilities Error reading gpx
05-27 00:50:41.840 E/net.osmand( 3060): java.io.FileNotFoundException: /mnt/sdcard/osmand/favourites.gpx (No such file or directory)
05-27 00:50:41.840 E/net.osmand( 3060): 	at org.apache.harmony.luni.platform.OSFileSystem.open(Native Method)
05-27 00:50:41.840 E/net.osmand( 3060): 	at dalvik.system.BlockGuard$WrappedFileSystem.open(BlockGuard.java:232)
05-27 00:50:41.840 E/net.osmand( 3060): 	at java.io.FileInputStream.<init>(FileInputStream.java:80)
05-27 00:50:41.840 E/net.osmand( 3060): 	at net.osmand.plus.GPXUtilities.loadGPXFile(GPXUtilities.java:787)
05-27 00:50:41.840 E/net.osmand( 3060): 	at net.osmand.plus.FavouritesDbHelper.loadGPXFile(FavouritesDbHelper.java:421)
05-27 00:50:41.840 E/net.osmand( 3060): 	at net.osmand.plus.FavouritesDbHelper.loadFavorites(FavouritesDbHelper.java:69)
05-27 00:50:41.840 E/net.osmand( 3060): 	at net.osmand.plus.AppInitializer.startApplicationBackground(AppInitializer.java:348)
05-27 00:50:41.840 E/net.osmand( 3060): 	at net.osmand.plus.AppInitializer.access$200(AppInitializer.java:55)
05-27 00:50:41.840 E/net.osmand( 3060): 	at net.osmand.plus.AppInitializer$7.run(AppInitializer.java:558)
05-27 00:50:41.840 E/net.osmand( 3060): 	at java.lang.Thread.run(Thread.java:1019)
05-27 00:50:41.930 I/dalvikvm( 3060): Could not find method android.view.View.setTranslationY, referenced from method net.osmand.plus.dashboard.DashboardOnMap.setTranslationY
05-27 00:50:43.090 I/net.osmand( 3060): MapRenderingTypes Time to init poi types 1239
05-27 00:50:46.180 I/net.osmand( 3060): CachedOsmandIndexes Initialize cache 118
05-27 00:50:46.250 I/dalvikvm( 3060): Could not find method android.widget.TextView.<init>, referenced from method net.osmand.plus.widgets.TextViewEx.<init>
05-27 00:50:46.250 D/dalvikvm( 3060): VFY: dead code 0x0003-0006 in Lnet/osmand/plus/widgets/TextViewEx;.<init> (Landroid/content/Context;Landroid/util/AttributeSet;II)V
05-27 00:50:46.250 I/dalvikvm( 3060): Could not find method android.widget.TextView.setAllCaps, referenced from method net.osmand.plus.widgets.TextViewEx.updateAllCapsNewAPI
05-27 00:50:46.250 D/dalvikvm( 3060): VFY: dead code 0x0003-0003 in Lnet/osmand/plus/widgets/TextViewEx;.updateAllCapsNewAPI (Landroid/widget/TextView;Z)V
05-27 00:50:46.260 D/net.osmand( 3060): ResourceManager All map files initialized 205 ms
05-27 00:50:46.340 I/dalvikvm( 3060): Could not find method android.widget.Button.<init>, referenced from method net.osmand.plus.widgets.ButtonEx.<init>
05-27 00:50:46.340 D/dalvikvm( 3060): VFY: dead code 0x0003-0006 in Lnet/osmand/plus/widgets/ButtonEx;.<init> (Landroid/content/Context;Landroid/util/AttributeSet;II)V
05-27 00:50:47.030 I/dalvikvm( 3060): Could not find method android.widget.ToggleButton.<init>, referenced from method net.osmand.plus.widgets.SwitchEx.<init>
05-27 00:50:47.050 D/dalvikvm( 3060): VFY: dead code 0x0003-0006 in Lnet/osmand/plus/widgets/SwitchEx;.<init> (Landroid/content/Context;Landroid/util/AttributeSet;II)V
05-27 00:50:47.590 W/ActivityManager(  199): Activity idle timeout for HistoryRecord{407f4810 net.osmand/.plus.activities.MapActivity}
05-27 00:50:48.790 I/ActivityManager(  199): Displayed net.osmand/.plus.activities.MapActivity: +11s401ms (total +20s995ms)
05-27 00:50:58.280 D/net.osmand( 3060): NativeOsmandLibrary Loading native gnustl_shared...
05-27 00:50:58.280 D/dalvikvm( 3060): Trying to load lib /mnt/asec/net.osmand-1/lib/libgnustl_shared.so 0x40516a50
05-27 00:50:58.570 D/dalvikvm( 3060): Added shared lib /mnt/asec/net.osmand-1/lib/libgnustl_shared.so 0x40516a50
05-27 00:50:58.570 D/dalvikvm( 3060): No JNI_OnLoad found in /mnt/asec/net.osmand-1/lib/libgnustl_shared.so 0x40516a50, skipping init
05-27 00:50:58.570 D/net.osmand( 3060): NativeOsmandLibrary Loading jnigraphics, since Android >= 2.2 ...
05-27 00:50:58.570 D/net.osmand( 3060): NativeOsmandLibrary Loading native libraries...
05-27 00:50:58.570 D/dalvikvm( 3060): Trying to load lib /mnt/asec/net.osmand-1/lib/libosmand.so 0x40516a50
05-27 00:50:58.620 D/dalvikvm( 3060): Added shared lib /mnt/asec/net.osmand-1/lib/libosmand.so 0x40516a50
05-27 00:50:58.620 I/net.osmand:native( 3060): JNI_OnLoad completed
05-27 00:50:58.620 D/net.osmand( 3060): NativeOsmandLibrary Creating NativeOsmandLibrary instance...
05-27 00:50:58.620 D/net.osmand( 3060): NativeOsmandLibrary Initializing rendering rules storage...
05-27 00:50:58.620 D/net.osmand:native( 3060): Init rendering storage net.osmand.render.RenderingRulesStorage@40b2e8b0 
05-27 00:51:02.160 I/net.osmand:native( 3060): Native Cache file initialized /mnt/sdcard/osmand/ind.cache
05-27 00:51:02.560 I/net.osmand( 3060): MapRenderRepositories RENDER MAP: update due to start
05-27 00:51:02.590 I/net.osmand( 3060): MapRenderRepositories RENDER MAP: Interrupt rendering map
05-27 00:51:02.810 I/net.osmand( 3060): MapRenderRepositories RENDER MAP: update due to start
05-27 00:51:02.820 I/net.osmand( 3060): MapRenderRepositories RENDER MAP: Interrupt rendering map
05-27 00:51:02.890 I/net.osmand( 3060): MapRenderRepositories RENDER MAP: new request RotatedTileBox [lat=37.67374801635742, lon=21.431529998779297, rotate=0.0, density=1.5, zoom=14, mapDensity=1.5, zoomAnimation=0.0, zoomFloatPart=0.0, cx=400, cy=571, pixWidth=800, pixHeight=1142]
05-27 00:51:02.890 D/net.osmand:native( 3060): Native file initialized from cache /mnt/sdcard/osmand/World_basemap.obf
05-27 00:51:02.920 D/net.osmand( 3060): MapRenderRepositories Native resource /mnt/sdcard/osmand/World_basemap.obf initialized 23 ms
05-27 00:51:02.920 D/net.osmand:native( 3060): Native file initialized from cache /mnt/sdcard/osmand/Greece_europe.obf
05-27 00:51:02.920 D/net.osmand( 3060): MapRenderRepositories Native resource /mnt/sdcard/osmand/Greece_europe.obf initialized 0 ms
05-27 00:51:03.950 I/net.osmand:native( 3060): Route objects 629
05-27 00:51:03.950 I/net.osmand:native( 3060): Ocean 0 fillCompleteArea 1
05-27 00:51:03.950 I/net.osmand:native( 3060): Search : tree - read( 416), accept( 58), objs - visit( 5083), accept(650), in result(629) 
05-27 00:51:03.990 I/net.osmand( 3060): MapRenderRepositories BLat=37.64529438018799, TLat=37.702190208435056, LLong=21.408641815185547, RLong=21.454410552978516, zoom=14
05-27 00:51:03.990 I/net.osmand( 3060): MapRenderRepositories Native search: 1095 ms 
05-27 00:51:04.360 W/net.osmand:native( 3060): jnigraphics was not found in loaded libraries
05-27 00:51:04.390 W/net.osmand:native( 3060): jnigraphics was not loaded in default location
05-27 00:51:04.390 I/net.osmand:native( 3060): Creating SkBitmap in native w:800 h:1142 s:3200 f:1!
05-27 00:51:04.390 I/net.osmand:native( 3060): Row bytes for RGBA_8888 is 3200
05-27 00:51:04.390 I/net.osmand:native( 3060): Locked 3654400 bytes at 0x47eb2008
05-27 00:51:04.390 I/net.osmand:native( 3060): Initializing rendering
05-27 00:51:04.390 I/net.osmand:native( 3060): Rendering image
05-27 00:51:05.380 I/net.osmand( 3060): RenderingIcons Icon data length is 341
05-27 00:51:24.490 I/dalvikvm( 3060):   at net.osmand.Reshaper.reshape(Reshaper.java:24)
05-27 00:51:24.490 I/dalvikvm( 3060):   at net.osmand.plus.render.NativeOsmandLibrary.generateRenderingDirect(Native Method)
05-27 00:51:24.490 I/dalvikvm( 3060):   at net.osmand.plus.render.NativeOsmandLibrary.generateRendering(NativeOsmandLibrary.java:93)
05-27 00:51:24.490 I/dalvikvm( 3060):   at net.osmand.plus.render.OsmandRenderer.generateNewBitmapNative(OsmandRenderer.java:197)
05-27 00:51:24.490 I/dalvikvm( 3060):   at net.osmand.plus.render.MapRenderRepositories.loadMap(MapRenderRepositories.java:743)
05-27 00:51:24.490 I/dalvikvm( 3060):   at net.osmand.plus.resources.AsyncLoadingThread.run(AsyncLoadingThread.java:109)
05-27 00:51:25.340 I/dalvikvm( 3060):   at net.osmand.Reshaper.reshape(Reshaper.java:24)
05-27 00:51:25.340 I/dalvikvm( 3060):   at net.osmand.plus.render.NativeOsmandLibrary.generateRenderingDirect(Native Method)
05-27 00:51:25.340 I/dalvikvm( 3060):   at net.osmand.plus.render.NativeOsmandLibrary.generateRendering(NativeOsmandLibrary.java:93)
05-27 00:51:25.340 I/dalvikvm( 3060):   at net.osmand.plus.render.OsmandRenderer.generateNewBitmapNative(OsmandRenderer.java:197)
05-27 00:51:25.340 I/dalvikvm( 3060):   at net.osmand.plus.render.MapRenderRepositories.loadMap(MapRenderRepositories.java:743)
05-27 00:51:25.340 I/dalvikvm( 3060):   at net.osmand.plus.resources.AsyncLoadingThread.run(AsyncLoadingThread.java:109)
05-27 00:51:25.970 I/DEBUG   ( 2632): pid: 3060, tid: 3072  >>> net.osmand <<<
05-27 00:51:26.950 I/DEBUG   ( 2632):          #02  pc 000e9152  /mnt/asec/net.osmand-1/lib/libosmand.so (_ZN7_JNIEnv17GetStringUTFCharsEP8_jstringPh)
05-27 00:51:26.960 I/DEBUG   ( 2632):     463f1764  808e9155  /mnt/asec/net.osmand-1/lib/libosmand.so
05-27 00:51:29.000 I/dalvikvm( 3060):   at net.osmand.plus.render.NativeOsmandLibrary.generateRenderingDirect(Native Method)
05-27 00:51:29.000 I/dalvikvm( 3060):   at net.osmand.plus.render.NativeOsmandLibrary.generateRendering(NativeOsmandLibrary.java:93)
05-27 00:51:29.000 I/dalvikvm( 3060):   at net.osmand.plus.render.OsmandRenderer.generateNewBitmapNative(OsmandRenderer.java:197)
05-27 00:51:29.000 I/dalvikvm( 3060):   at net.osmand.plus.render.MapRenderRepositories.loadMap(MapRenderRepositories.java:743)
05-27 00:51:29.000 I/dalvikvm( 3060):   at net.osmand.plus.resources.AsyncLoadingThread.run(AsyncLoadingThread.java:109)
05-27 00:51:29.760 I/dalvikvm( 3060):   at net.osmand.plus.render.NativeOsmandLibrary.generateRenderingDirect(Native Method)
05-27 00:51:29.760 I/dalvikvm( 3060):   at net.osmand.plus.render.NativeOsmandLibrary.generateRendering(NativeOsmandLibrary.java:93)
05-27 00:51:29.760 I/dalvikvm( 3060):   at net.osmand.plus.render.OsmandRenderer.generateNewBitmapNative(OsmandRenderer.java:197)
05-27 00:51:29.760 I/dalvikvm( 3060):   at net.osmand.plus.render.MapRenderRepositories.loadMap(MapRenderRepositories.java:743)
05-27 00:51:29.760 I/dalvikvm( 3060):   at net.osmand.plus.resources.AsyncLoadingThread.run(AsyncLoadingThread.java:109)
05-27 00:51:30.520 I/dalvikvm( 3060):   at net.osmand.plus.render.NativeOsmandLibrary.generateRenderingDirect(Native Method)
05-27 00:51:30.520 I/dalvikvm( 3060):   at net.osmand.plus.render.NativeOsmandLibrary.generateRendering(NativeOsmandLibrary.java:93)
05-27 00:51:30.520 I/dalvikvm( 3060):   at net.osmand.plus.render.OsmandRenderer.generateNewBitmapNative(OsmandRenderer.java:197)
05-27 00:51:30.520 I/dalvikvm( 3060):   at net.osmand.plus.render.MapRenderRepositories.loadMap(MapRenderRepositories.java:743)
05-27 00:51:30.520 I/dalvikvm( 3060):   at net.osmand.plus.resources.AsyncLoadingThread.run(AsyncLoadingThread.java:109)
05-27 00:51:30.910 I/ActivityManager(  199): Process net.osmand (pid 3060) has died.
05-27 00:51:30.930 I/WindowManager(  199): WIN DEATH: Window{408b3620 net.osmand/net.osmand.plus.activities.MapActivity paused=false}
```

**Comment by mirabilos** [comment]
I just installed OsmAnd on a relatively fresh CM 7.2.0.1 install on an HTC Desire (bravo), and it just crashes and reboots the entire phone (sometimes into Safe Mode) each time I attempt to start it, without fail.

This is the last CM version officially available for this device.

**Comment by vshcherb** [comment]
Please try to test older releases if possible. http://download.osmand.net/releases/

**Comment by alexxtasi** [comment]
well I installed [net.osmand-1.9.5-197.apk](http://download.osmand.net/releases/net.osmand-1.9.5-197.apk)
it seems to work fine (with no crashes !! )
Though, Android shows the indication "Phone storage space is getting low" which was also on the latest version of OsmAnd (maybe it's what @mirabilos was talking about)

should I provide a log ? or test a newer version ? (eg [net.osmand-2.0.0-200.apk](http://download.osmand.net/releases/net.osmand-2.0.0-200.apk) ) ?

**Comment by sonora** [comment]
I just notice this is for Android 2.3. Have you ever tested this version: http://download.osmand.net/latest-night-build/OsmAnd-nightly-2.3.apk

**Comment by vshcherb** [comment]
2.3 support is deprecated in many senses, we still have very basic support but it is very limited already.
