### ISSUE TITLE
Crash at startup when Network Permission is denied

### ISSUE THREAD

**Issue by realbiz21** [osmandapp/OsmAnd#12841]
### Description

OsmAnd+ crashes when using a GrapheneOS phone that has denied Network permission to the app. Since OsmAnd+ advertises functionality in offline mode, expectation is that the app will still work.

### How to reproduce?

1. Install OsmAnd+ from F-Droid on GrapheneOS device
2. Deny Network Permission for the app
3. Run OsmAnd+

Crashes with following stack trace:

```
09-23 20:22:45.560  4251  4300 E InAppPurchaseHelper: Error: sendRequest Error
09-23 20:22:45.560  4251  4300 E InAppPurchaseHelper: java.lang.SecurityException: Permission denied (missing INTERNET permission?)
09-23 20:22:45.560  4251  4300 E InAppPurchaseHelper:   at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:150)
09-23 20:22:45.560  4251  4300 E InAppPurchaseHelper:   at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
09-23 20:22:45.560  4251  4300 E InAppPurchaseHelper:   at java.net.InetAddress.getAllByName(InetAddress.java:1152)
09-23 20:22:45.560  4251  4300 E InAppPurchaseHelper:   at com.android.okhttp.Dns$1.lookup(Dns.java:41)
09-23 20:22:45.560  4251  4300 E InAppPurchaseHelper:   at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
09-23 20:22:45.560  4251  4300 E InAppPurchaseHelper:   at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
09-23 20:22:45.560  4251  4300 E InAppPurchaseHelper:   at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
09-23 20:22:45.560  4251  4300 E InAppPurchaseHelper:   at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:176)
09-23 20:22:45.560  4251  4300 E InAppPurchaseHelper:   at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
09-23 20:22:45.560  4251  4300 E InAppPurchaseHelper:   at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
09-23 20:22:45.560  4251  4300 E InAppPurchaseHelper:   at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
09-23 20:22:45.560  4251  4300 E InAppPurchaseHelper:   at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
09-23 20:22:45.560  4251  4300 E InAppPurchaseHelper:   at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
09-23 20:22:45.560  4251  4300 E InAppPurchaseHelper:   at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
09-23 20:22:45.560  4251  4300 E InAppPurchaseHelper:   at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
09-23 20:22:45.560  4251  4300 E InAppPurchaseHelper:   at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
09-23 20:22:45.560  4251  4300 E InAppPurchaseHelper:   at net.osmand.AndroidNetworkUtils.sendRequest(AndroidNetworkUtils.java:189)
09-23 20:22:45.560  4251  4300 E InAppPurchaseHelper:   at net.osmand.plus.inapp.InAppPurchaseHelper$RequestInventoryTask.doInBackground(InAppPurchaseHelper.java:391)
09-23 20:22:45.560  4251  4300 E InAppPurchaseHelper:   at net.osmand.plus.inapp.InAppPurchaseHelper$RequestInventoryTask.doInBackground(InAppPurchaseHelper.java:379)
09-23 20:22:45.560  4251  4300 E InAppPurchaseHelper:   at android.os.AsyncTask$3.call(AsyncTask.java:394)
09-23 20:22:45.560  4251  4300 E InAppPurchaseHelper:   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09-23 20:22:45.560  4251  4300 E InAppPurchaseHelper:   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-23 20:22:45.560  4251  4300 E InAppPurchaseHelper:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-23 20:22:45.560  4251  4300 E InAppPurchaseHelper:   at java.lang.Thread.run(Thread.java:923)
09-23 20:22:45.560  4251  4300 E InAppPurchaseHelper: Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
09-23 20:22:45.560  4251  4300 E InAppPurchaseHelper:   at libcore.io.Linux.android_getaddrinfo(Native Method)
09-23 20:22:45.560  4251  4300 E InAppPurchaseHelper:   at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:73)
09-23 20:22:45.560  4251  4300 E InAppPurchaseHelper:   at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:202)
09-23 20:22:45.560  4251  4300 E InAppPurchaseHelper:   at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:73)
09-23 20:22:45.560  4251  4300 E InAppPurchaseHelper:   at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
09-23 20:22:45.560  4251  4300 E InAppPurchaseHelper:   ... 23 more
09-23 20:22:45.560  4251  4300 E InAppPurchaseHelper: Caused by: android.system.ErrnoException: android_getaddrinfo failed: EPERM (Operation not permitted)
09-23 20:22:45.560  4251  4300 E InAppPurchaseHelper:   ... 28 more

09-23 20:22:46.446  4251  4251 D net.osmand: Enable sensor
09-23 20:22:46.510   430   451 I ActivityTaskManager: Displayed net.osmand.plus/.activities.MapActivity: +7s687ms
09-23 20:22:46.528  4251  4251 I Choreographer: Skipped 112 frames!  The application may be doing too much work on its main thread.
09-23 20:22:46.570  4251  4295 I System.out: FONT 05_NotoSans-Regular.ttf
09-23 20:22:46.780  4251  4295 I System.out: FONT 10_NotoSans-Bold.ttf
09-23 20:22:46.794  4251  4251 D AndroidRuntime: Shutting down VM
09-23 20:22:46.794  4251  4251 E AndroidRuntime: FATAL EXCEPTION: main
09-23 20:22:46.794  4251  4251 E AndroidRuntime: Process: net.osmand.plus, PID: 4251
09-23 20:22:46.794  4251  4251 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from null array
09-23 20:22:46.794  4251  4251 E AndroidRuntime:        at net.osmand.plus.inapp.InAppPurchaseHelper$RequestInventoryTask.onPostExecute(InAppPurchaseHelper.java:416)
09-23 20:22:46.794  4251  4251 E AndroidRuntime:        at net.osmand.plus.inapp.InAppPurchaseHelper$RequestInventoryTask.onPostExecute(InAppPurchaseHelper.java:379)
09-23 20:22:46.794  4251  4251 E AndroidRuntime:        at android.os.AsyncTask.finish(AsyncTask.java:771)
09-23 20:22:46.794  4251  4251 E AndroidRuntime:        at android.os.AsyncTask.access$900(AsyncTask.java:199)
09-23 20:22:46.794  4251  4251 E AndroidRuntime:        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
09-23 20:22:46.794  4251  4251 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
09-23 20:22:46.794  4251  4251 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
09-23 20:22:46.794  4251  4251 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7666)
09-23 20:22:46.794  4251  4251 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-23 20:22:46.794  4251  4251 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
09-23 20:22:46.794  4251  4251 E AndroidRuntime:        at com.android.internal.os.ExecInit.main(ExecInit.java:48)
09-23 20:22:46.794  4251  4251 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
09-23 20:22:46.794  4251  4251 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
09-23 20:22:46.842  4251  4251 E AndroidRuntime: Error reporting crash
09-23 20:22:46.842  4251  4251 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
09-23 20:22:46.842  4251  4251 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
09-23 20:22:46.842  4251  4251 E AndroidRuntime:        at android.os.BinderProxy.transact(BinderProxy.java:550)
09-23 20:22:46.842  4251  4251 E AndroidRuntime:        at android.app.IActivityManager$Stub$Proxy.handleApplicationCrash(IActivityManager.java:5208)
09-23 20:22:46.842  4251  4251 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:158)
09-23 20:22:46.842  4251  4251 E AndroidRuntime:        at net.osmand.plus.OsmandApplication$DefaultExceptionHandler.uncaughtException(OsmandApplication.java:672)
09-23 20:22:46.842  4251  4251 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
09-23 20:22:46.842  4251  4251 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
09-23 20:22:46.842  4251  4251 E AndroidRuntime:        at java.lang.Thread.dispatchUncaughtException(Thread.java:2203)
09-23 20:22:46.842  4251  4251 I Process : Sending signal. PID: 4251 SIG: 9
```

Note that GrapheneOS throws a SecurityException when Network Permission is denied which doesn't appear to be caught.

### Your Environment
OsmAnd Version: OsmAnd+ 3.9.10, F-Droid
Android/iOS version: GrapheneOS, Android 11
Device model: Pixel 4a

**Maps used (online or offline):**   N/A, but would be offline

**Comment by realbiz21** [comment]
This is no longer an issue in OsmAnd+.

GrapheneOS has implemented some fixes that avoid a crash.

I believe the resolution from GrapheneOS from the [2021121602 release notes](https://grapheneos.org/releases#2021121602) explains why:

> remove special case of throwing SecurityException for socket errors caused by EACCES/EPERM as a debugging aid since it causes compatibility issues when the Network (INTERNET) permission is revoked

This may have been from GrapheneOS/os-issue-tracker#560.

I request this issue to be closed since it a sufficient external resolution has been provided.

**Comment by realbiz21** [comment]
Closing since there has not been any objection to my request-to-close after 3 months.
