### ISSUE TITLE
Osmand 2.0.4 crashes on Android 2.3.6

### ISSUE THREAD

**Issue by OsmandUser** [osmandapp/Osmand#1285]
Osmand crashes on a Huawei Honor after some interaction in
menus or text-input.

Tried version from website and version from f-droid.

Deleted app before installing the new one.
Old version 1.9.5 was/is working fine.
```
Version  OsmAnd 2.0.4
Apk Version : 2.0.4 207
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException
	at android.view.View.buildDrawingCache(View.java:6599)
	at android.view.View.getDrawingCache(View.java:6449)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1715)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.widget.AbsListView.dispatchDraw(AbsListView.java:1485)
	at android.widget.ListView.dispatchDraw(ListView.java:3138)
	at android.view.View.draw(View.java:7023)
	at android.widget.AbsListView.draw(AbsListView.java:2593)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1790)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1788)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1788)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.View.draw(View.java:6904)
	at android.widget.FrameLayout.draw(FrameLayout.java:357)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1790)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1788)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.View.draw(View.java:6904)
	at android.widget.FrameLayout.draw(FrameLayout.java:357)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1790)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.View.draw(View.java:6904)
	at android.support.v7.internal.widget.ActionBarOverlayLayout.draw(ActionBarOverlayLayout.java:506)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1790)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1788)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.View.draw(View.java:6904)
	at android.widget.FrameLayout.draw(FrameLayout.java:357)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:1871)
	at android.view.ViewRoot.draw(ViewRoot.java:1528)
	at android.view.ViewRoot.performTraversals(ViewRoot.java:1264)
	at android.view.ViewRoot.handleMessage(ViewRoot.java:1868)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:130)
	at android.app.ActivityThread.main(ActivityThread.java:3683)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
	at dalvik.system.NativeStart.main(Native Method)
Version  OsmAnd 2.0.4
Apk Version : 2.0.4 207
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException
	at android.view.View.buildDrawingCache(View.java:6599)
	at android.view.View.getDrawingCache(View.java:6449)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1715)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.widget.AbsListView.dispatchDraw(AbsListView.java:1485)
	at android.widget.ListView.dispatchDraw(ListView.java:3138)
	at android.view.View.draw(View.java:7023)
	at android.widget.AbsListView.draw(AbsListView.java:2593)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1790)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1788)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1788)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.View.draw(View.java:6904)
	at android.widget.FrameLayout.draw(FrameLayout.java:357)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1790)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1788)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.View.draw(View.java:6904)
	at android.widget.FrameLayout.draw(FrameLayout.java:357)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1790)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.View.draw(View.java:6904)
	at android.support.v7.internal.widget.ActionBarOverlayLayout.draw(ActionBarOverlayLayout.java:506)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1790)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1788)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.View.draw(View.java:6904)
	at android.widget.FrameLayout.draw(FrameLayout.java:357)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:1871)
	at android.view.ViewRoot.draw(ViewRoot.java:1528)
	at android.view.ViewRoot.performTraversals(ViewRoot.java:1264)
	at android.view.ViewRoot.handleMessage(ViewRoot.java:1868)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:130)
	at android.app.ActivityThread.main(ActivityThread.java:3683)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
	at dalvik.system.NativeStart.main(Native Method)
Version  OsmAnd 2.0.4
Apk Version : 2.0.4 207
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException
	at android.view.View.buildDrawingCache(View.java:6599)
	at android.view.ViewGroup.onAnimationStart(ViewGroup.java:1403)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1649)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.View.draw(View.java:6904)
	at android.widget.FrameLayout.draw(FrameLayout.java:357)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1790)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1788)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.View.draw(View.java:6904)
	at android.widget.FrameLayout.draw(FrameLayout.java:357)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1790)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.View.draw(View.java:6904)
	at android.support.v7.internal.widget.ActionBarOverlayLayout.draw(ActionBarOverlayLayout.java:506)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1790)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1788)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.View.draw(View.java:6904)
	at android.widget.FrameLayout.draw(FrameLayout.java:357)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:1871)
	at android.view.ViewRoot.draw(ViewRoot.java:1528)
	at android.view.ViewRoot.performTraversals(ViewRoot.java:1264)
	at android.view.ViewRoot.handleMessage(ViewRoot.java:1868)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:130)
	at android.app.ActivityThread.main(ActivityThread.java:3683)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
	at dalvik.system.NativeStart.main(Native Method)
Version  OsmAnd 2.0.4
Apk Version : 2.0.4 207
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException
	at android.view.View.buildDrawingCache(View.java:6599)
	at android.view.ViewGroup.onAnimationStart(ViewGroup.java:1403)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1649)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.View.draw(View.java:6904)
	at android.widget.FrameLayout.draw(FrameLayout.java:357)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1790)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1788)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.View.draw(View.java:6904)
	at android.widget.FrameLayout.draw(FrameLayout.java:357)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1790)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.View.draw(View.java:6904)
	at android.support.v7.internal.widget.ActionBarOverlayLayout.draw(ActionBarOverlayLayout.java:506)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1790)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1788)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.View.draw(View.java:6904)
	at android.widget.FrameLayout.draw(FrameLayout.java:357)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:1871)
	at android.view.ViewRoot.draw(ViewRoot.java:1528)
	at android.view.ViewRoot.performTraversals(ViewRoot.java:1264)
	at android.view.ViewRoot.handleMessage(ViewRoot.java:1868)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:130)
	at android.app.ActivityThread.main(ActivityThread.java:3683)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
	at dalvik.system.NativeStart.main(Native Method)
Version  OsmAnd 2.0.4
Apk Version : 2.0.4 207
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException
	at android.view.View.buildDrawingCache(View.java:6599)
	at android.view.View.getDrawingCache(View.java:6449)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1715)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.widget.AbsListView.dispatchDraw(AbsListView.java:1485)
	at android.widget.ListView.dispatchDraw(ListView.java:3138)
	at android.view.View.draw(View.java:7023)
	at android.widget.AbsListView.draw(AbsListView.java:2593)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1790)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1788)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1788)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.View.draw(View.java:6904)
	at android.widget.FrameLayout.draw(FrameLayout.java:357)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1790)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1788)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.View.draw(View.java:6904)
	at android.widget.FrameLayout.draw(FrameLayout.java:357)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1790)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.View.draw(View.java:6904)
	at android.support.v7.internal.widget.ActionBarOverlayLayout.draw(ActionBarOverlayLayout.java:506)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1790)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1788)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.View.draw(View.java:6904)
	at android.widget.FrameLayout.draw(FrameLayout.java:357)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:1871)
	at android.view.ViewRoot.draw(ViewRoot.java:1528)
	at android.view.ViewRoot.performTraversals(ViewRoot.java:1264)
	at android.view.ViewRoot.handleMessage(ViewRoot.java:1868)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:130)
	at android.app.ActivityThread.main(ActivityThread.java:3683)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
	at dalvik.system.NativeStart.main(Native Method)
Version  OsmAnd 2.0.4
Apk Version : 2.0.4 207
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException
	at android.view.View.buildDrawingCache(View.java:6599)
	at android.view.View.getDrawingCache(View.java:6449)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1715)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.widget.AbsListView.dispatchDraw(AbsListView.java:1485)
	at android.widget.ListView.dispatchDraw(ListView.java:3138)
	at android.view.View.draw(View.java:7023)
	at android.widget.AbsListView.draw(AbsListView.java:2593)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1790)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1788)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1788)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.View.draw(View.java:6904)
	at android.widget.FrameLayout.draw(FrameLayout.java:357)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1790)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1788)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.View.draw(View.java:6904)
	at android.widget.FrameLayout.draw(FrameLayout.java:357)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1790)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.View.draw(View.java:6904)
	at android.support.v7.internal.widget.ActionBarOverlayLayout.draw(ActionBarOverlayLayout.java:506)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1790)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1788)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.View.draw(View.java:6904)
	at android.widget.FrameLayout.draw(FrameLayout.java:357)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:1871)
	at android.view.ViewRoot.draw(ViewRoot.java:1528)
	at android.view.ViewRoot.performTraversals(ViewRoot.java:1264)
	at android.view.ViewRoot.handleMessage(ViewRoot.java:1868)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:130)
	at android.app.ActivityThread.main(ActivityThread.java:3683)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
	at dalvik.system.NativeStart.main(Native Method)
Version  OsmAnd 2.0.4
Apk Version : 2.0.4 207
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException
	at android.view.View.buildDrawingCache(View.java:6599)
	at android.view.View.getDrawingCache(View.java:6449)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1715)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.widget.AbsListView.dispatchDraw(AbsListView.java:1485)
	at android.widget.ListView.dispatchDraw(ListView.java:3138)
	at android.view.View.draw(View.java:7023)
	at android.widget.AbsListView.draw(AbsListView.java:2593)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1790)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1788)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1788)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.View.draw(View.java:6904)
	at android.widget.FrameLayout.draw(FrameLayout.java:357)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1790)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.View.draw(View.java:6904)
	at android.widget.FrameLayout.draw(FrameLayout.java:357)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:1871)
	at android.view.ViewRoot.draw(ViewRoot.java:1528)
	at android.view.ViewRoot.performTraversals(ViewRoot.java:1264)
	at android.view.ViewRoot.handleMessage(ViewRoot.java:1868)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:130)
	at android.app.ActivityThread.main(ActivityThread.java:3683)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
	at dalvik.system.NativeStart.main(Native Method)
Version  OsmAnd 2.0.4
Apk Version : 2.0.4 207
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException
	at android.view.View.buildDrawingCache(View.java:6599)
	at android.view.View.getDrawingCache(View.java:6449)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1715)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.widget.AbsListView.dispatchDraw(AbsListView.java:1485)
	at android.widget.ListView.dispatchDraw(ListView.java:3138)
	at android.view.View.draw(View.java:7023)
	at android.widget.AbsListView.draw(AbsListView.java:2593)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1790)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1788)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1788)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.View.draw(View.java:6904)
	at android.widget.FrameLayout.draw(FrameLayout.java:357)
	at android.view.ViewGroup.drawChild(ViewGroup.java:1790)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
	at android.view.View.draw(View.java:6904)
	at android.widget.FrameLayout.draw(FrameLayout.java:357)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:1871)
	at android.view.ViewRoot.draw(ViewRoot.java:1528)
	at android.view.ViewRoot.performTraversals(ViewRoot.java:1264)
	at android.view.ViewRoot.handleMessage(ViewRoot.java:1868)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:130)
	at android.app.ActivityThread.main(ActivityThread.java:3683)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
	at dalvik.system.NativeStart.main(Native Method)

```

**Comment by vshcherb** [comment]
It is suggested to switch to 1.9.5 back, cause of system issue https://code.google.com/p/android/issues/detail?id=65538
