### ISSUE TITLE
Issue 4.0.8 with 4.4 Android

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#12864]
java.lang.NoSuchMethodError at net.osmand.plus.chooseplan.BasePurchaseDialogFragment.onCreateDialog(BasePurchaseDialogFragment.java:97)26.09.2021 12:13:24Exception occured in thread Thread[main 5 main] :  at net.osmand.plus.chooseplan.BasePurchaseDialogFragment.onCreateDialog(BasePurchaseDialogFragment.java:97)

java.lang.NoSuchMethodError: 
  at net.osmand.plus.chooseplan.BasePurchaseDialogFragment.onCreateDialog (BasePurchaseDialogFragment.java:97)
  at androidx.fragment.app.DialogFragment.onGetLayoutInflater (DialogFragment.java:380)
  at androidx.fragment.app.Fragment.performGetLayoutInflater (Fragment.java:1412)
  at androidx.fragment.app.FragmentManagerImpl.moveToState (FragmentManagerImpl.java:881)
  at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState (FragmentManagerImpl.java:1238)

**Comment by Chumva** [comment]
This should be fixed here - https://github.com/osmandapp/OsmAnd/pull/12865
