### ISSUE TITLE
Map rendering fails and crash

### ISSUE THREAD

**Issue by Zahnstocher** [osmandapp/Osmand#1299]
Latest nightly seems to have a problem with settings.
If I start OsmAnd the map is not displayed and if I push the layers icon (top left corner on the map) OsmAnd crashes:
```
Exception occured in thread Thread[main,5,main] : 
java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
	at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:224)
	at net.osmand.plus.api.SettingsAPIImpl.getString(SettingsAPIImpl.java:71)
	at net.osmand.plus.OsmandSettings$StringPreference.getValue(OsmandSettings.java:487)
	at net.osmand.plus.OsmandSettings$StringPreference.getValue(OsmandSettings.java:479)
	at net.osmand.plus.OsmandSettings$CommonPreference.get(OsmandSettings.java:351)
	at net.osmand.plus.dialogs.ConfigureMapMenu.createCustomRenderingProperties(ConfigureMapMenu.java:555)
	at net.osmand.plus.dialogs.ConfigureMapMenu.createRenderingAttributeItems(ConfigureMapMenu.java:394)
	at net.osmand.plus.dialogs.ConfigureMapMenu.createListAdapter(ConfigureMapMenu.java:64)
	at net.osmand.plus.dashboard.DashboardOnMap.updateListAdapter(DashboardOnMap.java:476)
	at net.osmand.plus.dashboard.DashboardOnMap.setDashboardVisibility(DashboardOnMap.java:431)
	at net.osmand.plus.dashboard.DashboardOnMap.setDashboardVisibility(DashboardOnMap.java:383)
	at net.osmand.plus.views.MapControlsLayer$1.onClick(MapControlsLayer.java:189)
	at android.view.View.performClick(View.java:4630)
	at android.view.View$PerformClick.run(View.java:19339)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:157)
	at android.app.ActivityThread.main(ActivityThread.java:5335)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Zahnstocher** [comment]
https://groups.google.com/forum/#!topic/osmand/c2WFQzrrBTE

**Comment by xmd5a2** [comment]
Please test current nightly version again

**Comment by Zahnstocher** [comment]
Not fixed.
Now it is not rendering and crashing also in bicycle mode, yesterday I had only problems in pedestrian mode.
I think I changed a setting in bicycle mode which also causes the problem in this mode now.
I will try to find out which setting causes the problem.
Car mode and map view mode are currently working.
I don't use custom styles.

**Comment by vshcherb** [comment]
It looks like the rendering style was not updated (may be delete osmand/rendering/default.render.xml)
String descr = SettingsActivity.getStringPropertyValue(activity, pref.get());
We try to get description for String but apparently the setting is Boolean, we changed already the setting id, so it shouldn't happen any more.

**Comment by vshcherb** [comment]
Deprecated, no feedback. Please clear rendering style in osmand folder (and especially in the build folder if you use), cause the issue should be fixed now.

**Comment by Zahnstocher** [comment]
Thanks, it is working now.
