### ISSUE TITLE
Crash at Live Updates with OsmAnd 4.0 on Android 4.3

### ISSUE THREAD

**Issue by CJTmmr** [osmandapp/OsmAnd#13113]
Maybe have one more for Issue #12705 Backport fixes from 4.1 to 4.0 release (Last Android 4.4)

I use OsmAnd on Android 4.3 (Samsung Galaxy Camera2 EK-GC200; no Andriod-updates...)

With all the backport fixes for OsmAnd 4.0 (compiled myself) I still have one issue:

From Drawer choose  "Download maps" - "UPDATES"
As soon as I tap on "Live Updates": immediate crash with exception.log (see below)

Could there be an easy fix?
Thanks

`
Version  OsmAnd Nightly 4.0.0
03.11.2021 7:43:47
Apk Version : 4.0.0 400
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalStateException: Cannot add header view to list -- setAdapter has already been called.
at android.widget.ListView.addHeaderView(ListView.java:267)
at android.widget.ListView.addHeaderView(ListView.java:296)
at net.osmand.plus.liveupdates.LiveUpdatesFragment.onCreateView(LiveUpdatesFragment.java:201)
at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
at android.os.Handler.handleCallback(Handler.java:730)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:177)
at android.app.ActivityThread.main(ActivityThread.java:5493)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1225)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1041)
at dalvik.system.NativeStart.main(Native Method)`

```

**Comment by Chumva** [comment]
This should be fixed here https://github.com/osmandapp/OsmAnd/pull/13156

**Comment by CJTmmr** [comment]
Thanks, I can confirm the fix
