### ISSUE TITLE
crash with overlay tile

### ISSUE THREAD

**Issue by HolgerJeromin** [osmandapp/Osmand#1316]
I tried to configure to use mapillary tiles as an overlay with osmand.
After activating osmand (a not so old full osmand from the homepage) crashes direct after using.
Recovering from this state is quite challenging, as the new layout loads the full view direct on startup. You can be quick enough to go into the settings to remove the online tile.

Perhaps i had a typo in the tile urls. But i am not able to view it (will open another issue for that).

Version  OsmAnd~ 2.1.0#11198M
05.06.2015 1:11:26
Apk Version : 2.1.0#11198M 211
Exception occured in thread Thread[pool-1-thread-2,5,main] : 
java.lang.NullPointerException
	at libcore.net.http.HttpConnection$Address.hashCode(HttpConnection.java)
	at java.util.HashMap.get(HashMap.java)
	at libcore.net.http.HttpConnectionPool.get(HttpConnectionPool.java)
	at libcore.net.http.HttpConnection.connect(HttpConnection.java)
	at libcore.net.http.HttpEngine.openSocketConnection(HttpEngine.java)
	at libcore.net.http.HttpEngine.connect(HttpEngine.java)
	at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java)
	at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java)
	at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java)
	at libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java)
	at net.osmand.map.MapTileDownloader$DownloadMapWorker.run(MapTileDownloader.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java)
	at java.lang.Thread.run(Thread.java)
Version  OsmAnd~ 2.1.0#11198M
05.06.2015 1:11:26
Apk Version : 2.1.0#11198M 211
Exception occured in thread Thread[pool-1-thread-1,5,main] : 
java.lang.NullPointerException
	at libcore.net.http.HttpConnection$Address.hashCode(HttpConnection.java)
	at java.util.HashMap.get(HashMap.java)
	at libcore.net.http.HttpConnectionPool.get(HttpConnectionPool.java)
	at libcore.net.http.HttpConnection.connect(HttpConnection.java)
	at libcore.net.http.HttpEngine.openSocketConnection(HttpEngine.java)
	at libcore.net.http.HttpEngine.connect(HttpEngine.java)
	at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java)
	at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java)
	at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java)
	at libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java)
	at net.osmand.map.MapTileDownloader$DownloadMapWorker.run(MapTileDownloader.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java)
	at java.lang.Thread.run(Thread.java)
Version  OsmAnd~ 2.1.0#11198M
05.06.2015 1:11:26
Apk Version : 2.1.0#11198M 211
Exception occured in thread Thread[pool-1-thread-1,5,main] : 
java.lang.NullPointerException
	at libcore.net.http.HttpConnection$Address.hashCode(HttpConnection.java)
	at java.util.HashMap.get(HashMap.java)
	at libcore.net.http.HttpConnectionPool.get(HttpConnectionPool.java)
	at libcore.net.http.HttpConnection.connect(HttpConnection.java)
	at libcore.net.http.HttpEngine.openSocketConnection(HttpEngine.java)
	at libcore.net.http.HttpEngine.connect(HttpEngine.java)
	at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java)
	at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java)
	at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java)
	at libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java)
	at net.osmand.map.MapTileDownloader$DownloadMapWorker.run(MapTileDownloader.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java)
	at java.lang.Thread.run(Thread.java)
Version  OsmAnd~ 2.1.0#11198M
05.06.2015 1:11:26
Apk Version : 2.1.0#11198M 211
Exception occured in thread Thread[pool-1-thread-2,5,main] : 
java.lang.NullPointerException
	at libcore.net.http.HttpConnection$Address.hashCode(HttpConnection.java)
	at java.util.HashMap.get(HashMap.java)
	at libcore.net.http.HttpConnectionPool.get(HttpConnectionPool.java)
	at libcore.net.http.HttpConnection.connect(HttpConnection.java)
	at libcore.net.http.HttpEngine.openSocketConnection(HttpEngine.java)
	at libcore.net.http.HttpEngine.connect(HttpEngine.java)
	at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java)
	at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java)
	at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java)
	at libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java)
	at net.osmand.map.MapTileDownloader$DownloadMapWorker.run(MapTileDownloader.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java)
	at java.lang.Thread.run(Thread.java)
Version  OsmAnd~ 2.1.0#11198M
05.06.2015 1:11:27
Apk Version : 2.1.0#11198M 211
Exception occured in thread Thread[pool-1-thread-5,5,main] : 
java.lang.NullPointerException
	at libcore.net.http.HttpConnection$Address.hashCode(HttpConnection.java)
	at java.util.HashMap.get(HashMap.java)
	at libcore.net.http.HttpConnectionPool.get(HttpConnectionPool.java)
	at libcore.net.http.HttpConnection.connect(HttpConnection.java)
	at libcore.net.http.HttpEngine.openSocketConnection(HttpEngine.java)
	at libcore.net.http.HttpEngine.connect(HttpEngine.java)
	at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java)
	at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java)
	at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java)
	at libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java)
	at net.osmand.map.MapTileDownloader$DownloadMapWorker.run(MapTileDownloader.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java)
	at java.lang.Thread.run(Thread.java)
Version  OsmAnd~ 2.1.0#11198M
05.06.2015 1:11:27
Apk Version : 2.1.0#11198M 211
Exception occured in thread Thread[pool-1-thread-6,5,main] : 
java.lang.NullPointerException
	at libcore.net.http.HttpConnection$Address.hashCode(HttpConnection.java)
	at java.util.HashMap.get(HashMap.java)
	at libcore.net.http.HttpConnectionPool.get(HttpConnectionPool.java)
	at libcore.net.http.HttpConnection.connect(HttpConnection.java)
	at libcore.net.http.HttpEngine.openSocketConnection(HttpEngine.java)
	at libcore.net.http.HttpEngine.connect(HttpEngine.java)
	at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java)
	at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java)
	at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java)
	at libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java)
	at net.osmand.map.MapTileDownloader$DownloadMapWorker.run(MapTileDownloader.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java)
	at java.lang.Thread.run(Thread.java)
Version  OsmAnd~ 2.1.0#11198M
05.06.2015 1:11:27
Apk Version : 2.1.0#11198M 211
Exception occured in thread Thread[pool-1-thread-5,5,main] : 
java.lang.NullPointerException
	at libcore.net.http.HttpConnection$Address.hashCode(HttpConnection.java)
	at java.util.HashMap.get(HashMap.java)
	at libcore.net.http.HttpConnectionPool.get(HttpConnectionPool.java)
	at libcore.net.http.HttpConnection.connect(HttpConnection.java)
	at libcore.net.http.HttpEngine.openSocketConnection(HttpEngine.java)
	at libcore.net.http.HttpEngine.connect(HttpEngine.java)
	at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java)
	at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java)
	at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java)
	at libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java)
	at net.osmand.map.MapTileDownloader$DownloadMapWorker.run(MapTileDownloader.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java)
	at java.lang.Thread.run(Thread.java)
Version  OsmAnd~ 2.1.0#11198M
05.06.2015 1:11:27
Apk Version : 2.1.0#11198M 211
Exception occured in thread Thread[pool-1-thread-6,5,main] : 
java.lang.NullPointerException
	at libcore.net.http.HttpConnection$Address.hashCode(HttpConnection.java)
	at java.util.HashMap.get(HashMap.java)
	at libcore.net.http.HttpConnectionPool.get(HttpConnectionPool.java)
	at libcore.net.http.HttpConnection.connect(HttpConnection.java)
	at libcore.net.http.HttpEngine.openSocketConnection(HttpEngine.java)
	at libcore.net.http.HttpEngine.connect(HttpEngine.java)
	at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java)
	at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java)
	at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java)
	at libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java)
	at net.osmand.map.MapTileDownloader$DownloadMapWorker.run(MapTileDownloader.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java)
	at java.lang.Thread.run(Thread.java)
Version  OsmAnd~ 2.1.0#11198M
05.06.2015 1:12:08
Apk Version : 2.1.0#11198M 211
Exception occured in thread Thread[pool-1-thread-1,5,main] : 
java.lang.NullPointerException
	at libcore.net.http.HttpConnection$Address.hashCode(HttpConnection.java)
	at java.util.HashMap.get(HashMap.java)
	at libcore.net.http.HttpConnectionPool.get(HttpConnectionPool.java)
	at libcore.net.http.HttpConnection.connect(HttpConnection.java)
	at libcore.net.http.HttpEngine.openSocketConnection(HttpEngine.java)
	at libcore.net.http.HttpEngine.connect(HttpEngine.java)
	at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java)
	at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java)
	at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java)
	at libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java)
	at net.osmand.map.MapTileDownloader$DownloadMapWorker.run(MapTileDownloader.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java)
	at java.lang.Thread.run(Thread.java)
Version  OsmAnd~ 2.1.0#11198M
05.06.2015 1:12:08
Apk Version : 2.1.0#11198M 211
Exception occured in thread Thread[pool-1-thread-2,5,main] : 
java.lang.NullPointerException
	at libcore.net.http.HttpConnection$Address.hashCode(HttpConnection.java)
	at java.util.HashMap.get(HashMap.java)
	at libcore.net.http.HttpConnectionPool.get(HttpConnectionPool.java)
	at libcore.net.http.HttpConnection.connect(HttpConnection.java)
	at libcore.net.http.HttpEngine.openSocketConnection(HttpEngine.java)
	at libcore.net.http.HttpEngine.connect(HttpEngine.java)
	at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java)
	at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java)
	at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java)
	at libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java)
	at net.osmand.map.MapTileDownloader$DownloadMapWorker.run(MapTileDownloader.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java)
	at java.lang.Thread.run(Thread.java)
Version  OsmAnd~ 2.1.0#11198M
05.06.2015 1:12:08
Apk Version : 2.1.0#11198M 211
Exception occured in thread Thread[pool-1-thread-1,5,main] : 
java.lang.NullPointerException
	at libcore.net.http.HttpConnection$Address.hashCode(HttpConnection.java)
	at java.util.HashMap.get(HashMap.java)
	at libcore.net.http.HttpConnectionPool.get(HttpConnectionPool.java)
	at libcore.net.http.HttpConnection.connect(HttpConnection.java)
	at libcore.net.http.HttpEngine.openSocketConnection(HttpEngine.java)
	at libcore.net.http.HttpEngine.connect(HttpEngine.java)
	at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java)
	at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java)
	at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java)
	at libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java)
	at net.osmand.map.MapTileDownloader$DownloadMapWorker.run(MapTileDownloader.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java)
	at java.lang.Thread.run(Thread.java)
Version  OsmAnd~ 2.1.0#11198M
05.06.2015 1:12:08
Apk Version : 2.1.0#11198M 211
Exception occured in thread Thread[pool-1-thread-2,5,main] : 
java.lang.NullPointerException
	at libcore.net.http.HttpConnection$Address.hashCode(HttpConnection.java)
	at java.util.HashMap.get(HashMap.java)
	at libcore.net.http.HttpConnectionPool.get(HttpConnectionPool.java)
	at libcore.net.http.HttpConnection.connect(HttpConnection.java)
	at libcore.net.http.HttpEngine.openSocketConnection(HttpEngine.java)
	at libcore.net.http.HttpEngine.connect(HttpEngine.java)
	at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java)
	at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java)
	at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java)
	at libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java)
	at net.osmand.map.MapTileDownloader$DownloadMapWorker.run(MapTileDownloader.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java)
	at java.lang.Thread.run(Thread.java)

**Comment by HolgerJeromin** [comment]
Deleting the tile configuration triggers the same bug. But deactivating (or probably  deletion) is possible while offline.

**Comment by HolgerJeromin** [comment]
Newest nightly has the same error:

Version  OsmAnd~ 2.1.0#11396M
05.06.2015 3:21:46
Apk Version : 2.1.0#11396M 211
Exception occured in thread Thread[pool-1-thread-3,5,main] : 
java.lang.NullPointerException
	at libcore.net.http.HttpConnection$Address.hashCode(HttpConnection.java)
	at java.util.HashMap.get(HashMap.java)
	at libcore.net.http.HttpConnectionPool.get(HttpConnectionPool.java)
	at libcore.net.http.HttpConnection.connect(HttpConnection.java)
	at libcore.net.http.HttpEngine.openSocketConnection(HttpEngine.java)
	at libcore.net.http.HttpEngine.connect(HttpEngine.java)
	at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java)
	at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java)
	at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java)
	at libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java)
	at net.osmand.map.MapTileDownloader$DownloadMapWorker.run(MapTileDownloader.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java)
	at java.lang.Thread.run(Thread.java)

**Comment by HolgerJeromin** [comment]
The faulty entry was:

    http://{s}.tiles.mapillary.com/{z}/{y}
    min zoom 5, max zoom 17

**Comment by vshcherb** [comment]
There is no {x} and {s} not supported. This is not a standard url , so the issue not related to osmand.

**Comment by HolgerJeromin** [comment]
If i am able to crash an app with bogus config it is an issue to fix imo. Denial of service like. 

Especially if the recovery is extremely difficult if you are online and do not realize the Internet connection is the problem. 

The x and s Syntax is from leaflet so not really unusual in the ecosystem.
