### ISSUE TITLE
Crash on going background

### ISSUE THREAD

**Issue by Dominik-K** [osmandapp/Osmand#1332]
I used the back button several times so that OsmAnd should go into background. But it crashed instead:

Version  OsmAnd~ 2.0.4
09.06.2015 9:12:48
Apk Version : 2.0.4 207
Exception occured in thread Thread[AsyncTask #1,5,main] : 
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:299)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
	at java.util.concurrent.FutureTask.run(FutureTask.java:239)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:838)
Caused by: java.lang.NullPointerException
	at net.osmand.plus.activities.search.SearchPoiFilterFragment.getApp(SearchPoiFilterFragment.java:149)
	at net.osmand.plus.activities.search.SearchPoiFilterFragment.getFilters(SearchPoiFilterFragment.java:125)
	at net.osmand.plus.activities.search.SearchPoiFilterFragment$SearchPoiByNameTask.doInBackground(SearchPoiFilterFragment.java:212)
	at net.osmand.plus.activities.search.SearchPoiFilterFragment$SearchPoiByNameTask.doInBackground(SearchPoiFilterFragment.java:207)
	at android.os.AsyncTask$2.call(AsyncTask.java:287)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	... 4 more

**Comment by vshcherb** [comment]
Not reproducible

**Comment by vshcherb** [comment]
Crash is fixed
