### ISSUE TITLE
InflateException: Binary XML file line #92 in net.osmand.plus:layout/first_usage_wizard_fragment: Error inflating class androidx.cardview.widget.CardView

### ISSUE THREAD

**Issue by miclill** [osmandapp/OsmAnd#13537]
### Description
A few seconds after starting the app it crashes

### How to reproduce?
start app -> crash

### Your Environment
OsmAnd Version: see below
Android/iOS version: /e/ OS
Device model: Fairphone 4

**Maps used (online or offline):**  
none. crashes at start

Version  OsmAnd~ 4.1.9
13.01.2022 9:57:32
Apk Version : 4.1.9 419
Exception occured in thread Thread[main,5,main] : 
android.view.InflateException: Binary XML file line #631 in net.osmand.plus:layout/first_usage_wizard_fragment: Binary XML file line #631 in net.osmand.plus:layout/first_usage_wizard_fragment: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #631 in net.osmand.plus:layout/first_usage_wizard_fragment: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:852)
	at android.view.LayoutInflater.createView(LayoutInflater.java:774)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:928)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:948)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1002)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at net.osmand.plus.firstusage.FirstUsageWizardFragment.onCreateView(FirstUsageWizardFragment.java:119)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
	at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw an exception; no stack trace available
Version  OsmAnd~ 4.1.9
13.01.2022 9:57:32
Apk Version : 4.1.9 419
Exception occured in thread Thread[Initializing app,5,main] : 
java.lang.OutOfMemoryError: Failed to allocate a 296 byte allocation with 184 free bytes and 184B until OOM, target footprint 37748736, growth limit 37748736
	at java.util.Arrays.copyOf(Arrays.java:3257)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuilder.append(StringBuilder.java:137)
	at net.osmand.map.OsmandRegions.getSearchIndex(OsmandRegions.java:520)
	at net.osmand.map.OsmandRegions.initRegionData(OsmandRegions.java:467)
	at net.osmand.map.OsmandRegions.access$100(OsmandRegions.java:40)
	at net.osmand.map.OsmandRegions$1.publish(OsmandRegions.java:133)
	at net.osmand.map.OsmandRegions$1.publish(OsmandRegions.java:121)
	at net.osmand.binary.BinaryMapIndexReader$SearchRequest.publish(BinaryMapIndexReader.java:1756)
	at net.osmand.binary.BinaryMapIndexReader.readMapDataBlocks(BinaryMapIndexReader.java:959)
	at net.osmand.binary.BinaryMapIndexReader.searchMapIndex(BinaryMapIndexReader.java:928)
	at net.osmand.binary.BinaryMapIndexReader.searchMapIndex(BinaryMapIndexReader.java:870)
	at net.osmand.map.OsmandRegions.iterateOverAllObjects(OsmandRegions.java:599)
	at net.osmand.map.OsmandRegions.prepareFile(OsmandRegions.java:149)
	at net.osmand.plus.AppInitializer.indexRegionsBoundaries(AppInitializer.java:250)
	at net.osmand.plus.AppInitializer.startApplicationBackground(AppInitializer.java:633)
	at net.osmand.plus.AppInitializer.access$300(AppInitializer.java:105)
	at net.osmand.plus.AppInitializer$8.run(AppInitializer.java:865)
	at java.lang.Thread.run(Thread.java:923)
Version  OsmAnd~ 4.1.9
13.01.2022 10:02:35
Apk Version : 4.1.9 419
Exception occured in thread Thread[Initializing app,5,main] : 
java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw an exception; no stack trace available
Version  OsmAnd~ 4.1.9
13.01.2022 10:02:35
Apk Version : 4.1.9 419
Exception occured in thread Thread[Loader map objects (synchronizer),5,main] : 
java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw an exception; no stack trace available
Version  OsmAnd~ 4.1.11
13.01.2022 10:05:39
Apk Version : 4.1.11 421
Exception occured in thread Thread[Initializing app,5,main] : 
java.lang.OutOfMemoryError: Failed to allocate a 40976 byte allocation with 7464 free bytes and 7464B until OOM, target footprint 37748736, growth limit 37748736
	at gnu.trove.list.array.TIntArrayList.ensureCapacity(TIntArrayList.java:186)
	at gnu.trove.list.array.TIntArrayList.add(TIntArrayList.java:221)
	at net.osmand.binary.BinaryMapIndexReader.readMapDataObject(BinaryMapIndexReader.java:1118)
	at net.osmand.binary.BinaryMapIndexReader.readMapDataBlocks(BinaryMapIndexReader.java:976)
	at net.osmand.binary.BinaryMapIndexReader.searchMapIndex(BinaryMapIndexReader.java:928)
	at net.osmand.binary.BinaryMapIndexReader.searchMapIndex(BinaryMapIndexReader.java:870)
	at net.osmand.map.OsmandRegions.iterateOverAllObjects(OsmandRegions.java:599)
	at net.osmand.map.OsmandRegions.prepareFile(OsmandRegions.java:149)
	at net.osmand.plus.AppInitializer.indexRegionsBoundaries(AppInitializer.java:250)
	at net.osmand.plus.AppInitializer.startApplicationBackground(AppInitializer.java:633)
	at net.osmand.plus.AppInitializer.access$300(AppInitializer.java:105)
	at net.osmand.plus.AppInitializer$8.run(AppInitializer.java:865)
	at java.lang.Thread.run(Thread.java:923)
Version  OsmAnd~ 4.1.11
13.01.2022 10:07:37
Apk Version : 4.1.11 421
Exception occured in thread Thread[main,5,main] : 
java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 0 free bytes and 0B until OOM, target footprint 37748736, growth limit 37748736
	at java.util.ArrayList.iterator(ArrayList.java:834)
	at net.osmand.plus.OsmAndLocationProvider.updateCompassVal(OsmAndLocationProvider.java:596)
	at net.osmand.plus.OsmAndLocationProvider.onSensorChanged(OsmAndLocationProvider.java:541)
	at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:837)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:183)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Version  OsmAnd~ 4.1.11
13.01.2022 10:16:40
Apk Version : 4.1.11 421
Exception occured in thread Thread[Initializing app,5,main] : 
java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available
Version  OsmAnd~ 4.1.11
13.01.2022 10:18:54
Apk Version : 4.1.11 421
Exception occured in thread Thread[Initializing app,5,main] : 
java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw an exception; no stack trace available
Version  OsmAnd~ 4.1.11
13.01.2022 10:19:36
Apk Version : 4.1.11 421
Exception occured in thread Thread[Initializing app,5,main] : 
java.lang.OutOfMemoryError: Failed to allocate a 2208 byte allocation with 1584 free bytes and 1584B until OOM, target footprint 37748736, growth limit 37748736
	at java.util.Arrays.copyOf(Arrays.java:3136)
	at java.util.Arrays.copyOf(Arrays.java:3106)
	at java.util.ArrayList.grow(ArrayList.java:275)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:249)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:241)
	at java.util.ArrayList.add(ArrayList.java:467)
	at net.osmand.map.OsmandRegions.findBoundaries(OsmandRegions.java:501)
	at net.osmand.map.OsmandRegions.initRegionData(OsmandRegions.java:446)
	at net.osmand.map.OsmandRegions.access$100(OsmandRegions.java:40)
	at net.osmand.map.OsmandRegions$1.publish(OsmandRegions.java:133)
	at net.osmand.map.OsmandRegions$1.publish(OsmandRegions.java:121)
	at net.osmand.binary.BinaryMapIndexReader$SearchRequest.publish(BinaryMapIndexReader.java:1756)
	at net.osmand.binary.BinaryMapIndexReader.readMapDataBlocks(BinaryMapIndexReader.java:959)
	at net.osmand.binary.BinaryMapIndexReader.searchMapIndex(BinaryMapIndexReader.java:928)
	at net.osmand.binary.BinaryMapIndexReader.searchMapIndex(BinaryMapIndexReader.java:870)
	at net.osmand.map.OsmandRegions.iterateOverAllObjects(OsmandRegions.java:599)
	at net.osmand.map.OsmandRegions.prepareFile(OsmandRegions.java:149)
	at net.osmand.plus.AppInitializer.indexRegionsBoundaries(AppInitializer.java:250)
	at net.osmand.plus.AppInitializer.startApplicationBackground(AppInitializer.java:633)
	at net.osmand.plus.AppInitializer.access$300(AppInitializer.java:105)
	at net.osmand.plus.AppInitializer$8.run(AppInitializer.java:865)
	at java.lang.Thread.run(Thread.java:923)
Version  OsmAnd~ 4.1.11
13.01.2022 10:19:50
Apk Version : 4.1.11 421
Exception occured in thread Thread[Initializing app,5,main] : 
java.lang.OutOfMemoryError: Failed to allocate a 9992 byte allocation with 5928 free bytes and 5928B until OOM, target footprint 37748736, growth limit 37748736
	at gnu.trove.list.array.TIntArrayList.toArray(TIntArrayList.java:689)
	at gnu.trove.list.array.TIntArrayList.toArray(TIntArrayList.java:683)
	at net.osmand.binary.BinaryMapIndexReader.readMapDataObject(BinaryMapIndexReader.java:1275)
	at net.osmand.binary.BinaryMapIndexReader.readMapDataBlocks(BinaryMapIndexReader.java:976)
	at net.osmand.binary.BinaryMapIndexReader.searchMapIndex(BinaryMapIndexReader.java:928)
	at net.osmand.binary.BinaryMapIndexReader.searchMapIndex(BinaryMapIndexReader.java:870)
	at net.osmand.map.OsmandRegions.iterateOverAllObjects(OsmandRegions.java:599)
	at net.osmand.map.OsmandRegions.prepareFile(OsmandRegions.java:149)
	at net.osmand.plus.AppInitializer.indexRegionsBoundaries(AppInitializer.java:250)
	at net.osmand.plus.AppInitializer.startApplicationBackground(AppInitializer.java:633)
	at net.osmand.plus.AppInitializer.access$300(AppInitializer.java:105)
	at net.osmand.plus.AppInitializer$8.run(AppInitializer.java:865)
	at java.lang.Thread.run(Thread.java:923)
Version  OsmAnd~ 4.1.11
13.01.2022 10:20:00
Apk Version : 4.1.11 421
Exception occured in thread Thread[Initializing app,5,main] : 
java.lang.OutOfMemoryError: Failed to allocate a 11648 byte allocation with 11280 free bytes and 11KB until OOM, target footprint 37748736, growth limit 37748736
	at gnu.trove.list.array.TIntArrayList.toArray(TIntArrayList.java:689)
	at gnu.trove.list.array.TIntArrayList.toArray(TIntArrayList.java:683)
	at net.osmand.binary.BinaryMapIndexReader.readMapDataObject(BinaryMapIndexReader.java:1275)
	at net.osmand.binary.BinaryMapIndexReader.readMapDataBlocks(BinaryMapIndexReader.java:976)
	at net.osmand.binary.BinaryMapIndexReader.searchMapIndex(BinaryMapIndexReader.java:928)
	at net.osmand.binary.BinaryMapIndexReader.searchMapIndex(BinaryMapIndexReader.java:870)
	at net.osmand.map.OsmandRegions.iterateOverAllObjects(OsmandRegions.java:599)
	at net.osmand.map.OsmandRegions.prepareFile(OsmandRegions.java:149)
	at net.osmand.plus.AppInitializer.indexRegionsBoundaries(AppInitializer.java:250)
	at net.osmand.plus.AppInitializer.startApplicationBackground(AppInitializer.java:633)
	at net.osmand.plus.AppInitializer.access$300(AppInitializer.java:105)
	at net.osmand.plus.AppInitializer$8.run(AppInitializer.java:865)
	at java.lang.Thread.run(Thread.java:923)
Version  OsmAnd~ 4.1.11
13.01.2022 10:22:27
Apk Version : 4.1.11 421
Exception occured in thread Thread[main,5,main] : 
android.view.InflateException: Binary XML file line #92 in net.osmand.plus:layout/first_usage_wizard_fragment: Binary XML file line #92 in net.osmand.plus:layout/first_usage_wizard_fragment: Error inflating class androidx.cardview.widget.CardView
Caused by: android.view.InflateException: Binary XML file line #92 in net.osmand.plus:layout/first_usage_wizard_fragment: Error inflating class androidx.cardview.widget.CardView
Caused by: java.lang.ClassNotFoundException: androidx.cardview.widget.CardView
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at android.view.LayoutInflater.createView(LayoutInflater.java:813)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at net.osmand.plus.firstusage.FirstUsageWizardFragment.onCreateView(FirstUsageWizardFragment.java:119)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
	at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available

**Comment by vshcherb** [comment]
Strange new phone and such a result. You could try to reinstall app and observe how memory grows to the limit (development settings) as you start without overlay/underlay and lots offline maps. But that's strange it says the app was using only 40 MB

**Comment by miclill** [comment]
I did reinstall the app, wipe all caches but I'm unsure where I can find those settings you mention?

**Comment by vshcherb** [comment]
Plugins -> Development -> Settings -> Scroll down

**Comment by miclill** [comment]
@vshcherb Thanks for your instructions. Problem is that the app crashes before I can get there. It basically crashes a few seconds after launching already.

**Comment by nagraskal** [comment]
Having the same problem, but with version 4.1.11, but also on Fairphone 4 with /e/ OS:

Exception occured in thread Thread[Initializing app,5,main] : 
java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available
Version  OsmAnd~ 4.1.11
15.01.2022 9:34:59
Apk Version : 4.1.11 421
[exception.log](https://github.com/osmandapp/OsmAnd/files/7879981/exception.log)

after wiping caches and app storage the app comes up briefly, showing "first steps", then "maps are beeing searched", then the app crashes. on next start it will only show the "first steps" screen, then  crashes about three seconds later, while still on the first steps screen.

**Comment by beoe** [comment]
I am pretty sure, that this is not connected to OsmAnd but to /e/ OS ROM for FP4. I have created a bug-report there: https://gitlab.e.foundation/e/backlog/-/issues/4649 . The developer already fixed it and it should be working in the next build of /e/ for FP4.

**Comment by miclill** [comment]
@beoe perfect, thanks! I briefly thought of increasing the heapsize of the java VM but didn't have the time researching how it's done on android.
