### ISSUE TITLE
Karten-Management hangs forever

### ISSUE THREAD

**Issue by flohoff** [osmandapp/Osmand#1391]
Hi,
i am preparing my own daily map of Northrhine-Westfalia for some time now which i typically just copy via scp to the device and delete the old one. This worked without problems. Today then i could not disable/enable maps anymore as going into "Karten-Management" (Map management?) the osmand hung. I waited like 2-3 minutes and nothing happened. I rebootet the device - updated the regions.ocbf removed the ind.cache. After every change i killed osmand and started it fresh. 

After playing around i now got a backtrace in the exceptions.log:

24.06.2015 4:35:29
Apk Version : 2.1.1 212
Exception occured in thread Thread[AsyncTask #2,5,main] : 
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Application android.support.v4.app.FragmentActivity.getApplication()' on a null object reference
	at net.osmand.plus.activities.OsmandExpandableListFragment.getMyApplication(OsmandExpandableListFragment.java:27)
	at net.osmand.plus.download.LocalIndexesFragment$LoadLocalIndexTask.doInBackground(LocalIndexesFragment.java:286)
	at net.osmand.plus.download.LocalIndexesFragment$LoadLocalIndexTask.doInBackground(LocalIndexesFragment.java:280)
	at android.os.AsyncTask$2.call(AsyncTask.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more

Then i started osmand again and after like 30 seconds i got to the point beeing able to enable/disable maps.

Flo

**Comment by vshcherb** [comment]
That screen was completely refactored and we don't observe that issue, if you can still reproduce feel free to leave feadback
