### ISSUE TITLE
Australia map update

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#1394]
Australia-oceania.osm.pbf
INFO: Done 10.008 %.
Jun 24, 2015 11:39:37 AM net.osmand.data.preparation.address.IndexAddressCreator indexAddressRelation
WARNING: building with empty location! id: 5246543
Jun 24, 2015 11:39:37 AM net.osmand.data.preparation.IndexCreator generateIndexes
SEVERE: Log exception
java.lang.NullPointerException
	at net.osmand.data.preparation.address.DBStreetDAO.writeBuilding(DBStreetDAO.java:116)
	at net.osmand.data.preparation.address.CachedDBStreetDAO.writeBuilding(CachedDBStreetDAO.java:50)
	at net.osmand.data.preparation.address.IndexAddressCreator.indexAddressRelation(IndexAddressCreator.java:504)

**Comment by vshcherb** [comment]
Fixed
