### ISSUE TITLE
Osmand crashes when detail button is clicked

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#14118]
### How to reproduce?
1. Enter walking profile.
2. Enter context menu and tap navigation
3. Expand the navigation screen and tap on the details button.
Osmand crashed.

### Your Environment
OsmAnd Version: OsmAnd~ 4.2.0#33907m, released: 2022-04-23
Android version: 12
Device model: poco x3 pro

Maps used (online or offline): Russia_leningradskaya_asia + live update

**Comment by Nine-Tailed** [comment]
```
Version  OsmAnd~ 4.2.0#33907m
24.04.2022 3:56:41
Apk Version : 4.2.0#33907m 421
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
	at net.osmand.plus.routepreparationmenu.ChooseRouteFragment.updateControlsVisibility(ChooseRouteFragment.java:798)
	at net.osmand.plus.routepreparationmenu.ChooseRouteFragment.onResume(ChooseRouteFragment.java:252)
	at androidx.fragment.app.Fragment.performResume(Fragment.java:2649)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:922)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
	at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8250)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

```
