### ISSUE TITLE
Osmand crashes when entering terrain menu

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#14117]
### How to reproduce?
1. Menu
2. Select configure map
3. Select terrain
Osmand crash.

### Your Environment
OsmAnd Version: OsmAnd~ 4.2.0#33907m, released: 2022-04-23
Android version: 12
Device model: poco x3 pro

**Comment by Nine-Tailed** [comment]
```
Version  OsmAnd~ 4.2.0#33907m
24.04.2022 3:27:37
Apk Version : 4.2.0#33907m 421
Exception occured in thread Thread[main,5,main] : 
java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
	at java.util.ArrayList.get(ArrayList.java:439)
	at net.osmand.plus.widgets.ctxmenu.CtxMenuUtils.hideExtraDividers(CtxMenuUtils.java:59)
	at net.osmand.plus.widgets.ctxmenu.ContextMenuAdapter.toListAdapter(ContextMenuAdapter.java:110)
	at net.osmand.plus.plugins.srtm.TerrainFragment.updateDownloadSection(TerrainFragment.java:470)
	at net.osmand.plus.plugins.srtm.TerrainFragment.onUpdatedIndexesList(TerrainFragment.java:483)
	at net.osmand.plus.activities.MapActivity.onUpdatedIndexesList(MapActivity.java:1623)
	at net.osmand.plus.download.DownloadIndexesThread.onUpdatedIndexesList(DownloadIndexesThread.java:154)
	at net.osmand.plus.download.DownloadIndexesThread$ReloadIndexesTask.onPostExecute(DownloadIndexesThread.java:375)
	at net.osmand.plus.download.DownloadIndexesThread$ReloadIndexesTask.onPostExecute(DownloadIndexesThread.java:334)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.access$900(AsyncTask.java:199)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8250)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

```

**Comment by Chumva** [comment]
https://github.com/osmandapp/OsmAnd/pull/14128
