### ISSUE TITLE
Osmand crashes when adding a group of favorites

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#14131]
### Description
Osmand does not show a list of favorite points groups and when trying to add a group, it crashes.

### How to reproduce?
1. Select a favorite point and tap edit
2. Tap on the list button
the list of favorite groups will be empty, only the add group button
![Screenshot_2022-04-26-02-13-12-026_net.osmand.plus.jpg](https://user-images.githubusercontent.com/12549744/165189697-faea88e6-1461-471f-9752-7afb722522cd.jpg)
3. After clicking the add group button osmand will crash

### Your Environment
OsmAnd Version:
Android version: 12
Device model: poco x3 pro

**Comment by Nine-Tailed** [comment]
```
Version  OsmAnd~ 4.2.0#33916m
26.04.2022 2:18:59
Apk Version : 4.2.0#33916m 421
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Map net.osmand.GPXUtilities$GPXFile.getPointsGroups()' on a null object reference
	at net.osmand.plus.mapcontextmenu.editors.GpxGroupEditorFragment.onCreate(GpxGroupEditorFragment.java:51)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2586)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:838)
	at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1197)
	at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1080)
	at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:119)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1866)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
	at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8250)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

```
