### ISSUE TITLE
Osmand crashes when zooming the map in the loading window

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#14132]
### How to reproduce?
1. Select online maps as a source
2. In the context menu select download map
3. At the top of the screen, sharply zoom in on the map
As a result osmand will crash.
![Screenshot_2022-04-26-04-34-43-722_net.osmand.plus.jpg](https://user-images.githubusercontent.com/12549744/165202336-2a2963f1-80ea-4a82-b565-934a42bf30a3.jpg)

### Your Environment
OsmAnd Version: OsmAnd~ 4.2.0#33916m, дата выпуска: 2022-04-25
Android version: 12
Device model:poco x3 pro

**Comment by Nine-Tailed** [comment]
```
Version  OsmAnd~ 4.2.0#33916m
26.04.2022 4:28:31
Apk Version : 4.2.0#33916m 421
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalStateException: Slider value(19.0) must be greater or equal to valueFrom(16.0), and lower or equal to valueTo(17.0)
	at com.google.android.material.slider.BaseSlider.validateValues(BaseSlider.java:545)
	at com.google.android.material.slider.BaseSlider.validateConfigurationIfDirty(BaseSlider.java:587)
	at com.google.android.material.slider.BaseSlider.onDraw(BaseSlider.java:1521)
	at android.view.View.draw(View.java:23012)
	at android.view.View.updateDisplayListIfDirty(View.java:21880)
	at android.view.View.draw(View.java:22738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.updateDisplayListIfDirty(View.java:21871)
	at android.view.View.draw(View.java:22738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.draw(View.java:23016)
	at android.view.View.updateDisplayListIfDirty(View.java:21880)
	at android.view.View.draw(View.java:22738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.draw(View.java:23016)
	at android.widget.ScrollView.draw(ScrollView.java:1868)
	at android.view.View.updateDisplayListIfDirty(View.java:21880)
	at android.view.View.draw(View.java:22738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.updateDisplayListIfDirty(View.java:21871)
	at android.view.View.draw(View.java:22738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.draw(View.java:23016)
	at android.view.View.updateDisplayListIfDirty(View.java:21880)
	at android.view.View.draw(View.java:22738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.updateDisplayListIfDirty(View.java:21871)
	at android.view.View.draw(View.java:22738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.updateDisplayListIfDirty(View.java:21871)
	at android.view.View.draw(View.java:22738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1426)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.draw(View.java:23016)
	at android.view.View.updateDisplayListIfDirty(View.java:21880)
	at android.view.View.draw(View.java:22738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.updateDisplayListIfDirty(View.java:21871)
	at android.view.View.draw(View.java:22738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.updateDisplayListIfDirty(View.java:21871)
	at android.view.View.draw(View.java:22738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.updateDisplayListIfDirty(View.java:21871)
	at android.view.View.draw(View.java:22738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.updateDisplayListIfDirty(View.java:21871)
	at android.view.View.draw(View.java:22738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.draw(View.java:23016)
	at com.android.internal.policy.DecorView.draw(DecorView.java:887)
	at android.view.View.updateDisplayListIfDirty(View.java:21880)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:542)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:625)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4645)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4363)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3474)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2265)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9009)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1142)
	at android.view.Choreographer.doCallbacks(Choreographer.java:946)
	at android.view.Choreographer.doFrame(Choreographer.java:875)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1127)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8250)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

```

**Comment by Nine-Tailed** [comment]
The bug is still possible to repeat, but less often.
```
Version  OsmAnd~ 4.2.0#34004m
10.05.2022 2:58:06
Apk Version : 4.2.0#34004m 4200
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalStateException: Slider value(15.0) must be greater or equal to valueFrom(16.0), and lower or equal to valueTo(17.0)
	at com.google.android.material.slider.BaseSlider.validateValues(BaseSlider.java:545)
	at com.google.android.material.slider.BaseSlider.validateConfigurationIfDirty(BaseSlider.java:587)
	at com.google.android.material.slider.BaseSlider.onDraw(BaseSlider.java:1521)
	at android.view.View.draw(View.java:23012)
	at android.view.View.updateDisplayListIfDirty(View.java:21880)
	at android.view.View.draw(View.java:22738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.updateDisplayListIfDirty(View.java:21871)
	at android.view.View.draw(View.java:22738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.draw(View.java:23016)
	at android.view.View.updateDisplayListIfDirty(View.java:21880)
	at android.view.View.draw(View.java:22738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.draw(View.java:23016)
	at android.widget.ScrollView.draw(ScrollView.java:1868)
	at android.view.View.updateDisplayListIfDirty(View.java:21880)
	at android.view.View.draw(View.java:22738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.updateDisplayListIfDirty(View.java:21871)
	at android.view.View.draw(View.java:22738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.draw(View.java:23016)
	at android.view.View.updateDisplayListIfDirty(View.java:21880)
	at android.view.View.draw(View.java:22738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.updateDisplayListIfDirty(View.java:21871)
	at android.view.View.draw(View.java:22738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.updateDisplayListIfDirty(View.java:21871)
	at android.view.View.draw(View.java:22738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1426)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.draw(View.java:23016)
	at android.view.View.updateDisplayListIfDirty(View.java:21880)
	at android.view.View.draw(View.java:22738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.updateDisplayListIfDirty(View.java:21871)
	at android.view.View.draw(View.java:22738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.updateDisplayListIfDirty(View.java:21871)
	at android.view.View.draw(View.java:22738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.updateDisplayListIfDirty(View.java:21871)
	at android.view.View.draw(View.java:22738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.updateDisplayListIfDirty(View.java:21871)
	at android.view.View.draw(View.java:22738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.draw(View.java:23016)
	at com.android.internal.policy.DecorView.draw(DecorView.java:887)
	at android.view.View.updateDisplayListIfDirty(View.java:21880)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:542)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:625)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4645)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4363)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3474)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2265)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9009)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1142)
	at android.view.Choreographer.doCallbacks(Choreographer.java:946)
	at android.view.Choreographer.doFrame(Choreographer.java:875)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1127)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8250)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

```

**Comment by Nine-Tailed** [comment]
And yet such a bug is proposed to be sent to the phone manufacturer.
```
java.lang.IllegalStateException: Fragment DownloadTilesFragment{1e2f203 (42f361cd-acf7-4434-879d-b8c8771694fb)} not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:774)
	at androidx.fragment.app.Fragment.getResources(Fragment.java:838)
	at androidx.fragment.app.Fragment.getString(Fragment.java:873)
	at net.osmand.plus.plugins.rastermaps.DownloadTilesFragment.setupTilesDownloadInfo(DownloadTilesFragment.java:273)
	at net.osmand.plus.plugins.rastermaps.DownloadTilesFragment.updateDownloadContent(DownloadTilesFragment.java:196)
	at net.osmand.plus.plugins.rastermaps.DownloadTilesFragment.lambda$locationChanged$9$DownloadTilesFragment(DownloadTilesFragment.java:393)
	at net.osmand.plus.plugins.rastermaps.-$$Lambda$DownloadTilesFragment$3vlGxLKuTr2tvqQxQPyR9kVpyhU.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8250)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

```
