### ISSUE TITLE
[crash] when tapping on intermediate destination flag

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#14233]
### Description
crash when tapping on intermediate destination flag after prepare of route.

### How to reproduce?
see log
[exception_log.zip](https://github.com/osmandapp/OsmAnd/files/8653475/exception_log.zip)

### Your Environment
OsmAnd Version: OsmAnd~ 4.2.0#33997m, veröffentlicht: 2022-05-09
Android version: 8
Device model: Samsung S7

**Comment by vshcherb** [comment]
````
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context net.osmand.plus.views.OsmandMapTileView.getContext()' on a null object reference
	at net.osmand.plus.views.layers.PointNavigationLayer.getObjectName(PointNavigationLayer.java:342)
	at net.osmand.plus.mapcontextmenu.other.MapMultiSelectionMenu.createCollection(MapMultiSelectionMenu.java:132)
	at net.osmand.plus.mapcontextmenu.other.MapMultiSelectionMenu.show(MapMultiSelectionMenu.java:175)
```

**Comment by scaidermern** [comment]
Can confirm. Although for me the exception looks slightly different:

```
java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
 at net.osmand.plus.mapcontextmenu.MenuBuilder.addImageCard(MenuBuilder.java:177)
 at net.osmand.plus.mapcontextmenu.MenuBuilder$5$1$1.run(MenuBuilder.java:555)
 ```
