### ISSUE TITLE
Crash to Desktop report - I have no other thoughts on this so I'll just post the exception log.

### ISSUE THREAD

**Issue by duiveldoder** [osmandapp/OsmAnd#14462]
Version  OsmAnd~ 4.3.0#34123m
05.06.2022 5:24:04
Apk Version : 4.3.0#34123m 4300
Exception occured in thread Thread[AsyncTask #6,5,main] : 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$AsyncFutureTask.done(AsyncTask.java:429)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
Caused by: com.github.scribejava.core.exceptions.OAuthException: The IP address of a host could not be determined.
	at net.osmand.osm.oauth.OsmAndJDKHttpClient.doExecute(OsmAndJDKHttpClient.java:141)
	at net.osmand.osm.oauth.OsmAndJDKHttpClient.execute(OsmAndJDKHttpClient.java:103)
	at com.github.scribejava.core.oauth.OAuthService.execute(OAuthService.java:108)
	at net.osmand.osm.oauth.OsmOAuthAuthorizationClient.performRequest(OsmOAuthAuthorizationClient.java:137)
	at net.osmand.plus.plugins.osmedit.helpers.OsmBugsRemoteUtil.performOAuthRequest(OsmBugsRemoteUtil.java:185)
	at net.osmand.plus.plugins.osmedit.helpers.OsmBugsRemoteUtil.editingPOI(OsmBugsRemoteUtil.java:122)
	at net.osmand.plus.plugins.osmedit.helpers.OsmBugsRemoteUtil.validateLoginDetails(OsmBugsRemoteUtil.java:114)
	at net.osmand.plus.plugins.osmedit.helpers.OsmBugsRemoteUtil.commit(OsmBugsRemoteUtil.java:105)
	at net.osmand.plus.plugins.osmedit.asynctasks.UploadOpenstreetmapPointAsyncTask.doInBackground(UploadOpenstreetmapPointAsyncTask.java:83)
	at net.osmand.plus.plugins.osmedit.asynctasks.UploadOpenstreetmapPointAsyncTask.doInBackground(UploadOpenstreetmapPointAsyncTask.java:23)
	at android.os.AsyncTask$3.call(AsyncTask.java:389)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: java.net.UnknownHostException: Unable to resolve host "api.openstreetmap.org": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at com.android.okhttp.Dns$1.lookup(Dns.java:41)
	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
	at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:176)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
	at net.osmand.osm.oauth.OsmAndJDKHttpClient.doExecute(OsmAndJDKHttpClient.java:135)
	... 14 more
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:74)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:200)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:74)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
	... 30 more

### How to reproduce?
I was uploading notes to OSM - being a mapper.. and then walked out of the office room - to living room.
Where the phone switches the access points within the same network, same IP, same subnet, same gateway..

### Your Environment
Device : HWLYA
Brand : HUAWEI
Model : LYA-L29
Product : LYA-L29
Build : LYA-L29 10.1.0.298(C636E7R2P4)
Version : 10
App Version : OsmAnd~
Apk Version : 4.3.0#34123m 4300

**Comment by vshcherb** [comment]
Really weird actually, did you manage to reupload?

**Comment by duiveldoder** [comment]
Yes - no data lost and once I simply did the reupload - it just continued where it left off..

I don't see this crash as a problem - but any crash might be worth reporting nonetheless.. Keep it in "archive" just in case in future someone reports it again - or if the devs accidentally hit on the part of the code that triggered this as a "oohhhh, that's why"

I wouldn't spend time on it to search for what exactly triggered this - as "no data loss" means to me personally "low priority"
