### ISSUE TITLE
Crash when trying to navigate along GPX track

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#14475]
OsmAnd 4.2.2 crashed while trying to navigate along a GPX track:

```
Version  OsmAnd+ 4.2.2
05.06.2022 10:34:20
Apk Version : 4.2.2 4202
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
	at net.osmand.plus.views.mapwidgets.widgets.ElevationProfileWidget.updateTextWidget(ElevationProfileWidget.java:428)
	at net.osmand.plus.views.mapwidgets.widgets.ElevationProfileWidget.updateWidgets(ElevationProfileWidget.java:410)
	at net.osmand.plus.views.mapwidgets.widgets.ElevationProfileWidget.updateInfoImpl(ElevationProfileWidget.java:157)
	at net.osmand.plus.views.mapwidgets.widgets.ElevationProfileWidget.updateInfo(ElevationProfileWidget.java:146)
	at net.osmand.plus.views.mapwidgets.MapWidgetRegistry.updateWidgetsInfo(MapWidgetRegistry.java:113)
	at net.osmand.plus.views.layers.MapInfoLayer.onDraw(MapInfoLayer.java:294)
	at net.osmand.plus.views.OsmandMapTileView.drawOverMap(OsmandMapTileView.java:902)
	at net.osmand.plus.views.OsmandMapTileView.refreshMapInternal(OsmandMapTileView.java:783)
	at net.osmand.plus.views.OsmandMapTileView.lambda$sendRefreshMapMsg$1$OsmandMapTileView(OsmandMapTileView.java:983)
	at net.osmand.plus.views.-$$Lambda$OsmandMapTileView$fLgzRs-tuqSFsZCk0tpsmkkm-3g.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

Track: [track.gpx.txt](https://github.com/osmandapp/OsmAnd/files/8846099/track.gpx.txt)

The crash happened immediately after starting the navigation. It happened repeatedly when trying again.

Today I can't reproduce this crash, though,

**Comment by scaidermern** [comment]
I guess this has been resolved with the fix for #14489.
