### ISSUE TITLE
Osmand crash when exiting the screen while downloading a raster map

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#14487]
### Description

If you press the back button while the map is being animated in the marked window, the application crashes.

![IMG_20220607_225641.jpg](https://user-images.githubusercontent.com/12549744/172471036-0ce04c54-89bd-494d-9344-c55f4d85f185.jpg)

### How to reproduce?

Click in the context menu download map and quickly click the back button.
See video:
https://user-images.githubusercontent.com/12549744/172471091-ce65d1af-e059-467c-9413-f1cf4b5b79fe.mp4

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#34163m, released: 2022-06-07
Android version: 12
Device model: poco x3 pro

**Comment by Nine-Tailed** [comment]
'''
Version  OsmAnd~ 4.3.0#34163m
07.06.2022 10:53:23
Apk Version : 4.3.0#34163m 4300
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalStateException: Fragment DownloadTilesFragment{5263803 (02ffae8c-183f-47ed-be31-5d50c34e0ff9)} not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:774)
	at androidx.fragment.app.Fragment.getResources(Fragment.java:838)
	at androidx.fragment.app.Fragment.getString(Fragment.java:873)
	at net.osmand.plus.plugins.rastermaps.DownloadTilesFragment.setupTilesDownloadInfo(DownloadTilesFragment.java:270)
	at net.osmand.plus.plugins.rastermaps.DownloadTilesFragment.updateDownloadContent(DownloadTilesFragment.java:193)
	at net.osmand.plus.plugins.rastermaps.DownloadTilesFragment.lambda$locationChanged$9$DownloadTilesFragment(DownloadTilesFragment.java:390)
	at net.osmand.plus.plugins.rastermaps.-$$Lambda$DownloadTilesFragment$3vlGxLKuTr2tvqQxQPyR9kVpyhU.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8250)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
'''
