### ISSUE TITLE
Crash when rotating device 

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#14489]
Osmand 4.2.2 crashes when rotating the device during navigation.

Exception 1:
```
Exception occured in thread Thread[main,5,main] : 
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.osmand.plus/net.osmand.plus.activities.MapActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5279)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5187)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
	at net.osmand.plus.views.mapwidgets.widgets.ElevationProfileWidget.updateTextWidget(ElevationProfileWidget.java:428)
	at net.osmand.plus.views.mapwidgets.widgets.ElevationProfileWidget.updateWidgets(ElevationProfileWidget.java:410)
	at net.osmand.plus.views.mapwidgets.widgets.ElevationProfileWidget.updateInfoImpl(ElevationProfileWidget.java:157)
	at net.osmand.plus.views.mapwidgets.widgets.ElevationProfileWidget.updateInfo(ElevationProfileWidget.java:146)
	at net.osmand.plus.views.mapwidgets.MapWidgetRegistry.updateWidgetsInfo(MapWidgetRegistry.java:113)
	at net.osmand.plus.views.layers.MapInfoLayer.recreateControls(MapInfoLayer.java:159)
	at net.osmand.plus.views.layers.MapInfoLayer.setMapActivity(MapInfoLayer.java:80)
	at net.osmand.plus.views.MapLayers.setMapActivity(MapLayers.java:220)
	at net.osmand.plus.activities.MapActivity.onCreate(MapActivity.java:292)
	at android.app.Activity.performCreate(Activity.java:7824)
	at android.app.Activity.performCreate(Activity.java:7813)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
	... 13 more
```

Exception 2:
```
Exception occured in thread Thread[main,5,main] : 
java.lang.RuntimeException: Unable to resume activity {net.osmand.plus/net.osmand.plus.activities.MapActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4205)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
	at net.osmand.plus.views.mapwidgets.widgets.ElevationProfileWidget.updateTextWidget(ElevationProfileWidget.java:428)
	at net.osmand.plus.views.mapwidgets.widgets.ElevationProfileWidget.updateWidgets(ElevationProfileWidget.java:410)
	at net.osmand.plus.views.mapwidgets.widgets.ElevationProfileWidget.updateInfoImpl(ElevationProfileWidget.java:157)
	at net.osmand.plus.views.mapwidgets.widgets.ElevationProfileWidget.updateInfo(ElevationProfileWidget.java:146)
	at net.osmand.plus.views.mapwidgets.MapWidgetRegistry.updateWidgetsInfo(MapWidgetRegistry.java:113)
	at net.osmand.plus.views.layers.MapInfoLayer.recreateControls(MapInfoLayer.java:159)
	at net.osmand.plus.views.layers.MapInfoLayer.recreateAllControls(MapInfoLayer.java:139)
	at net.osmand.plus.activities.MapActivity.updateApplicationModeSettings(MapActivity.java:1305)
	at net.osmand.plus.activities.MapActivity.onResume(MapActivity.java:758)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1453)
	at android.app.Activity.performResume(Activity.java:7958)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195)
	... 11 more
```

Seems to be related to the ElevationProfileWidget.

Probably related to #14475.

**Comment by scaidermern** [comment]
Any chance to get a new release with this fix (apart from the nightly)? I had to disable the elevation profile widget in all of my profiles because this crash triggers very often. Not just when rotation the device but also when switching the display off and on.

**Comment by vshcherb** [comment]
Release is already out with it.
