### ISSUE TITLE
Android Marshmallow 6.0 might crash with `android.content.res.Resources$NotFoundException: File res/drawable/ic_action_ufo.xml` -- `invalid color state list tag gradient`

### ISSUE THREAD

**Issue by TheSnoozer** [osmandapp/OsmAnd#14880]
### Description
Hello,
I'm observing more or less random crashes when navigating the menu dialoges in osmand+. In particular open the menu and click on configure display seems to reproduce a consistent crash. The following is the last message in `exception.log`:
```
Version  OsmAnd+ 4.2.6
17.07.2022 6:35:08
Apk Version : 4.2.6 4206
Exception occured in thread Thread[main,5,main] : 
android.content.res.Resources$NotFoundException: File res/drawable/ic_action_ufo.xml from drawable resource ID #0x7f080781
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2884)
	at android.content.res.Resources.loadDrawable(Resources.java:2768)
	at android.content.res.Resources.getDrawable(Resources.java:927)
	at android.content.Context.getDrawable(Context.java:463)
	at androidx.core.content.ContextCompat$Api21Impl.getDrawable(ContextCompat.java:864)
	at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:483)
	at net.osmand.plus.views.mapwidgets.configure.ConfigureScreenFragment.setupModesToggle(ConfigureScreenFragment.java:198)
	at net.osmand.plus.views.mapwidgets.configure.ConfigureScreenFragment.onCreateView(ConfigureScreenFragment.java:120)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
	at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5763)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/$ic_action_ufo__0.xml from color state list resource ID #0x7f08002c
	at android.content.res.Resources.loadColorStateListForCookie(Resources.java:2995)
	at android.content.res.Resources.loadColorStateList(Resources.java:2944)
	at android.content.res.TypedArray.getColor(TypedArray.java:439)
	at android.graphics.drawable.VectorDrawable$VFullPath.updateStateFromTypedArray(VectorDrawable.java:1605)
	at android.graphics.drawable.VectorDrawable$VFullPath.inflate(VectorDrawable.java:1584)
	at android.graphics.drawable.VectorDrawable.inflateInternal(VectorDrawable.java:666)
	at android.graphics.drawable.VectorDrawable.inflate(VectorDrawable.java:571)
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1220)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1129)
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2874)
	... 24 more
Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #15: invalid color state list tag gradient
	at android.content.res.ColorStateList.createFromXmlInner(ColorStateList.java:217)
	at android.content.res.ColorStateList.createFromXml(ColorStateList.java:201)
	at android.content.res.Resources.loadColorStateListForCookie(Resources.java:2991)
	... 33 more
```

Given the file is not found I'm not sure if I should cleanup some cache or so...

### How to reproduce?
Open osmand+, open the menu and click on configure display

### Your Environment
Device : F3311
Brand : Sony
Model : F3311
Product : F3311
Build : 37.0.A.2.252
Version : 6.0
App Version : OsmAnd+
Apk Version : 4.2.6 4206

**Comment by TheSnoozer** [comment]
Seems related to my potato android version: https://stackoverflow.com/a/53018428

**Comment by TheSnoozer** [comment]
While the issue is likely still there I think this is no longer relevant, or people should update their android version.
