### ISSUE TITLE
The app crashes when sending the OSM Note without internet connection 

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#14992]
### Description
Application crashes when sending OSM Note if there is no internet connection 
[exception (5).log.zip](https://github.com/osmandapp/OsmAnd/files/9241564/exception.5.log.zip)

### Steps to reproduce
Start navigation > Deactivate internet connection >  Press on the map > Action > Open OSM Note > Create note > UPLOAD 

### Actual result
The app crashes

https://user-images.githubusercontent.com/104760013/182359856-1b62aa38-2a09-49d9-8dfd-187240523d4f.mp4

### Expected result
The app continues to work

### Your Environment
OsmAnd Version: 4.2.7, released: 2022-07-13 
Android/iOS version: Android 11
Device model: POCO X3 NFC

**Comment by scaidermern** [comment]
Yep, I can reproduce this:

```
Version  OsmAnd+ 4.2.7
02.08.2022 1:37:21
Apk Version : 4.2.7 4207
Exception occured in thread Thread[AsyncTask #30,5,main] : 
java.lang.RuntimeException: An error occurred while executing doInBackground()
 at android.os.AsyncTask$4.done(AsyncTask.java:399)
 at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
 at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
 at java.util.concurrent.FutureTask.run(FutureTask.java:271)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:919)
Caused by: com.github.scribejava.core.exceptions.OAuthException: The IP address of a host could not be determined.
 at net.osmand.osm.oauth.OsmAndJDKHttpClient.doExecute(OsmAndJDKHttpClient.java:141)
 at net.osmand.osm.oauth.OsmAndJDKHttpClient.execute(OsmAndJDKHttpClient.java:103)
 at com.github.scribejava.core.oauth.OAuthService.execute(OAuthService.java:108)
 at net.osmand.osm.oauth.OsmOAuthAuthorizationClient.performRequest(OsmOAuthAuthorizationClient.java:137)
 at net.osmand.plus.plugins.osmedit.helpers.OsmBugsRemoteUtil.performOAuthRequest(OsmBugsRemoteUtil.java:185)
 at net.osmand.plus.plugins.osmedit.helpers.OsmBugsRemoteUtil.editingPOI(OsmBugsRemoteUtil.java:122)
 at net.osmand.plus.plugins.osmedit.helpers.OsmBugsRemoteUtil.validateLoginDetails(OsmBugsRemoteUtil.java:114)
 at net.osmand.plus.plugins.osmedit.helpers.OsmBugsRemoteUtil.commit(OsmBugsRemoteUtil.java:105)
 at net.osmand.plus.plugins.osmedit.asynctasks.UploadOpenstreetmapPointAsyncTask.doInBackground(UploadOpenstreetmapPointAsyncTask.java:83)
 at net.osmand.plus.plugins.osmedit.asynctasks.UploadOpenstreetmapPointAsyncTask.doInBackground(UploadOpenstreetmapPointAsyncTask.java:23)
 at android.os.AsyncTask$3.call(AsyncTask.java:378)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 ... 3 more
Caused by: java.net.UnknownHostException: Unable to resolve host "api.openstreetmap.org": No address associated with hostname
 at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
 at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
 at java.net.InetAddress.getAllByName(InetAddress.java:1152)
 at com.android.okhttp.Dns$1.lookup(Dns.java:41)
 at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
 at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
 at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
 at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:176)
 at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
 at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
 at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
 at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
 at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
 at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
 at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
 at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
 at net.osmand.osm.oauth.OsmAndJDKHttpClient.doExecute(OsmAndJDKHttpClient.java:135)
 ... 14 more
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
 at libcore.io.Linux.android_getaddrinfo(Native Method)
 at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:74)
 at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:200)
 at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:74)
 at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
 ... 30 more
```
