### ISSUE TITLE
Crash / out of memory when loading details for an 82km long trail

### ISSUE THREAD

**Issue by mdykierek** [osmandapp/OsmAnd#15131]
https://www.openstreetmap.org/relation/1633747#map=11/66.3336/29.3496

### Description
```
Version  OsmAnd+ 4.2.7
22.08.2022 3:03:27
Apk Version : 4.2.7 4207
Exception occured in thread Thread[AsyncTask #6,5,main] : 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 6392 byte allocation with 4920 free bytes and 4920B until OOM, target footprint 536870912, growth limit 536870912
	at gnu.trove.map.hash.TLongObjectHashMap.rehash(TLongObjectHashMap.java:168)
	at gnu.trove.impl.hash.THash.postInsertHook(THash.java:387)
	at gnu.trove.map.hash.TLongObjectHashMap.doPut(TLongObjectHashMap.java:269)
	at gnu.trove.map.hash.TLongObjectHashMap.put(TLongObjectHashMap.java:240)
	at net.osmand.router.network.NetworkRouteContext$NetworkRoutesTile.add(NetworkRouteContext.java:437)
	at net.osmand.router.network.NetworkRouteContext.loadRoutingDataTile(NetworkRouteContext.java:209)
	at net.osmand.router.network.NetworkRouteContext.loadTile(NetworkRouteContext.java:172)
	at net.osmand.router.network.NetworkRouteContext.getMapRouteTile(NetworkRouteContext.java:148)
	at net.osmand.router.network.NetworkRouteContext.loadRouteSegmentTile(NetworkRouteContext.java:82)
	at net.osmand.router.network.NetworkRouteSelector.loadData(NetworkRouteSelector.java:588)
	at net.osmand.router.network.NetworkRouteSelector.connectAlgorithm(NetworkRouteSelector.java:271)
	at net.osmand.router.network.NetworkRouteSelector.getRoutes(NetworkRouteSelector.java:171)
	at net.osmand.plus.track.helpers.NetworkRouteSelectionTask.doInBackground(NetworkRouteSelectionTask.java:65)
	at net.osmand.plus.track.helpers.NetworkRouteSelectionTask.doInBackground(NetworkRouteSelectionTask.java:28)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
```

### How to reproduce?
This is for the most popular hiking trail of Finland. It is said to be 82km long - Karhunkierros Trail (also know as The Bear's Trail or The Bear's Ring - https://www.nationalparks.fi/karhunkierros
The location can be found: https://www.nationalparks.fi/karhunkierros/directions
The length is not the main reason, there are trails in Poland e.g. Szlak Tysiąclecia that is 102 km, Mały Szlak Beskidzki 134km that load OK. But for example European long distance path E9 part Poland crashes after a very long wait (breaking the process with button would be nice). To my surprise Główny Szlak Beskidzki (500km) did load quite fast.

### Your Environment
OsmAnd Version: OsmAnd+ 4.2.7
Android/iOS version: Android 11
Device model: Mi 9T Pro

**Maps used (online or offline):**   
Offline maps for Finland, August 2022

**Comment by scaidermern** [comment]
Sounds like #14698.

**Comment by mdykierek** [comment]
Indeed it does. Tried both "crash" and "memory", but didn't find. Sorry for duplicate. At least 2 more test cases available.

**Comment by mdykierek** [comment]
I have a theory on this. I noticed that there is a possibility of making a loop on this trail. So I "went" to Bornholm and tried on 100km loop around the island - route 10 and guess what -> crash after a couple of minutes.

**Comment by mdykierek** [comment]
Another question that comes to my mind is - how do you present distance for 2 or more variants with different length? Is that something that has to be resolved in the maps or several variants can be presented?

**Comment by vshcherb** [comment]
Planning to switch to Native version so it won't be such an issue

**Comment by vshcherb** [comment]
On many devices it works, but we are going to make it work for low end devices with C++ implemmentation
![telegram-cloud-photo-size-4-5778305986673621583-y](https://user-images.githubusercontent.com/1042025/186449886-b0f1454b-b4d9-41eb-b00c-5ab7de443c96.jpg)

**Comment by mdykierek** [comment]
I know it is not the latest, but **6GB of RAM** doesn't exactly put Mi 9T Pro among the low end.
That is plenty of memory to eat :D.

**Comment by vshcherb** [comment]
> 6GB of RAM
That's very common mistake, only 1GB is available and only for Native implementation. In Java it's limited to 24MB - 150 MB (depends on device) and it's eaten very fast with map rendering itself

**Comment by mdykierek** [comment]
Thank you for pointing this out. I have supplemented my knowledge on limitations imposed by Android and device on an app.
However, it still is not so obvious to me that the memory limitation is the main factor here. A 500 km route works fine while 100km loop crashes. I refer to the 4.2.7. I presume with the current development it may be different now.
Thanks anyway. Looking forward to 4.3 where it is supposed to be fixed.
