### ISSUE TITLE
"Loading data exception" while calculating route

### ISSUE THREAD

**Issue by PJuniszewski** [osmandapp/OsmAnd#15261]
### Description
When trying to navigate there is no route displayed. 

```
CurrentPositionHelper Exception happened during runUpdateInThread
    java.lang.RuntimeException: Loading data exception
        at net.osmand.router.RoutingContext.loadTileHeaders(RoutingContext.java:413)
        at net.osmand.router.RoutingContext.getRoutingTile(RoutingContext.java:490)
        at net.osmand.router.RoutingContext.loadTileData(RoutingContext.java:440)
        at net.osmand.router.RoutePlannerFrontEnd.findRouteSegment(RoutePlannerFrontEnd.java:151)
        at net.osmand.binary.GeocodingUtilities.reverseGeocodingSearch(GeocodingUtilities.java:154)
        at net.osmand.plus.helpers.CurrentPositionHelper.runUpdateInThread(CurrentPositionHelper.java:235)
        at net.osmand.plus.helpers.CurrentPositionHelper.processGeocoding(CurrentPositionHelper.java:192)
        at net.osmand.plus.helpers.CurrentPositionHelper.access$000(CurrentPositionHelper.java:37)
        at net.osmand.plus.helpers.CurrentPositionHelper$1.run(CurrentPositionHelper.java:115)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.io.IOException: lseek failed: EBADF (Bad file descriptor)
        at java.io.RandomAccessFile.seek(RandomAccessFile.java:620)
        at com.google.protobuf.CodedInputStream.seek(CodedInputStream.java:978)
        at net.osmand.binary.BinaryMapRouteReaderAdapter.initRouteRegion(BinaryMapRouteReaderAdapter.java:1055)
        at net.osmand.binary.BinaryMapRouteReaderAdapter.initRouteTypesIfNeeded(BinaryMapRouteReaderAdapter.java:1048)
        at net.osmand.binary.BinaryMapIndexReader.searchRouteIndexTree(BinaryMapIndexReader.java:2695)
        at net.osmand.router.RoutingContext.loadTileHeaders(RoutingContext.java:391)
        at net.osmand.router.RoutingContext.getRoutingTile(RoutingContext.java:490) 
        at net.osmand.router.RoutingContext.loadTileData(RoutingContext.java:440) 
        at net.osmand.router.RoutePlannerFrontEnd.findRouteSegment(RoutePlannerFrontEnd.java:151) 
        at net.osmand.binary.GeocodingUtilities.reverseGeocodingSearch(GeocodingUtilities.java:154) 
        at net.osmand.plus.helpers.CurrentPositionHelper.runUpdateInThread(CurrentPositionHelper.java:235) 
        at net.osmand.plus.helpers.CurrentPositionHelper.processGeocoding(CurrentPositionHelper.java:192) 
        at net.osmand.plus.helpers.CurrentPositionHelper.access$000(CurrentPositionHelper.java:37) 
        at net.osmand.plus.helpers.CurrentPositionHelper$1.run(CurrentPositionHelper.java:115) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: android.system.ErrnoException: lseek failed: EBADF (Bad file descriptor)
        at libcore.io.Linux.lseek(Native Method)
        at libcore.io.ForwardingOs.lseek(ForwardingOs.java:152)
        at libcore.io.BlockGuardOs.lseek(BlockGuardOs.java:221)
        at libcore.io.ForwardingOs.lseek(ForwardingOs.java:152)
        at java.io.RandomAccessFile.seek(RandomAccessFile.java:617)
        at com.google.protobuf.CodedInputStream.seek(CodedInputStream.java:978) 
        at net.osmand.binary.BinaryMapRouteReaderAdapter.initRouteRegion(BinaryMapRouteReaderAdapter.java:1055) 
        at net.osmand.binary.BinaryMapRouteReaderAdapter.initRouteTypesIfNeeded(BinaryMapRouteReaderAdapter.java:1048) 
        at net.osmand.binary.BinaryMapIndexReader.searchRouteIndexTree(BinaryMapIndexReader.java:2695) 
        at net.osmand.router.RoutingContext.loadTileHeaders(RoutingContext.java:391) 
        at net.osmand.router.RoutingContext.getRoutingTile(RoutingContext.java:490) 
        at net.osmand.router.RoutingContext.loadTileData(RoutingContext.java:440) 
        at net.osmand.router.RoutePlannerFrontEnd.findRouteSegment(RoutePlannerFrontEnd.java:151) 
        at net.osmand.binary.GeocodingUtilities.reverseGeocodingSearch(GeocodingUtilities.java:154) 
        at net.osmand.plus.helpers.CurrentPositionHelper.runUpdateInThread(CurrentPositionHelper.java:235) 
        at net.osmand.plus.helpers.CurrentPositionHelper.processGeocoding(CurrentPositionHelper.java:192) 
        at net.osmand.plus.helpers.CurrentPositionHelper.access$000(CurrentPositionHelper.java:37) 
        at net.osmand.plus.helpers.CurrentPositionHelper$1.run(CurrentPositionHelper.java:115) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
```

### How to reproduce?
Try to navigate anywhere.

### Your Environment
OsmAnd Version: 4.3.0
Android/iOS version: 10
Device model: Xiaomi Redmi 6A

**Maps used (online or offline):**   
Poland / Lower Silesian / Standrad Map

**Comment by vshcherb** [comment]
Potentially it's a multithread access issue

**Comment by PJuniszewski** [comment]
what do u mean? How could it impact the routing ?

**Comment by PJuniszewski** [comment]
Checked and it does not seem to be multithread issue

**Comment by PJuniszewski** [comment]
When using only `World_basemap.obf` the navigation is not throwing any exceptions (probably because it does not reach the affected logic), but it has missing maps `Poland_lower-silesian_europe.obf`. So when map is downloaded and then navigation is fired again ,then the exception is thrown.

**Comment by PJuniszewski** [comment]
@vshcherb I can see there are changes from u regarding the mentioned part of the code, any clues what might be the problem expect for multithread access issue ? Thx
