### ISSUE TITLE
org.xmlpull.v1.XmlPullParserException: name expected

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1548]
https://dl.dropboxusercontent.com/u/4624786/osm/test_order1.osm
Map generation fails:
SEVERE: Log exception
org.xmlpull.v1.XmlPullParserException: name expected (position:START_TAG <null>@22:18 in java.io.InputStreamReader@768f310f) 
	at org.kxml2.io.KXmlParser.exception(Unknown Source)
	at org.kxml2.io.KXmlParser.error(Unknown Source)
	at org.kxml2.io.KXmlParser.readName(Unknown Source)
	at org.kxml2.io.KXmlParser.parseStartTag(Unknown Source)
	at org.kxml2.io.KXmlParser.nextImpl(Unknown Source)
	at org.kxml2.io.KXmlParser.next(Unknown Source)
	at net.osmand.osm.io.OsmBaseStorage.parseOSM(OsmBaseStorage.java:110)
	at net.osmand.data.preparation.IndexCreator.extractOsmToNodesDB(IndexCreator.java:319)
	at net.osmand.data.preparation.IndexCreator.initDbAccessor(IndexCreator.java:354)
	at net.osmand.data.preparation.IndexCreator.generateIndexes(IndexCreator.java:588)
	at net.osmand.data.preparation.IndexCreator.generateIndexes(IndexCreator.java:518)
	at net.osmand.MainUtilities.generateObf(MainUtilities.java:84)
	at net.osmand.MainUtilities.main(MainUtilities.java:49)

**Comment by vshcherb** [comment]
Can't reproduce.
