### ISSUE TITLE
Error while saving GPX. The distance calculator plugin can't save GPX route. +enabling this plugin causes crash.

### ISSUE THREAD

**Issue by enomat** [osmandapp/Osmand#1565]
Steps to reproduce:
- enable "Distance calculator & planning tool" plugin
- create some points on the map
- tap the ruler then choose "Save as GPX track"
- type something (for GPX file name) then tap "Save"

This error message will appear:
"Error while saving GPX"

<img src="https://cloud.githubusercontent.com/assets/12612250/9304259/7947d552-44e6-11e5-8c76-89c0b2187a19.png" height="500px">

Device: Samsung Galaxy S2 I9100, Android 4.1.2
Osmand:
- version: 2.2.0#12479M
- file name: OsmAnd-nightly.apk
- downloaded from here:
http://download.osmand.net/latest-night-build/

I've also tried it on the old Osmand 1.9.5 version, and I get the same error (so it has the same problem).

**Comment by stephan75** [comment]
Using a nightly version 2.2.0#12368 from 2015August04 I CANNOT confirm, sorry.

I can even see that saved track file in "my tracks" then.

What apk version do you use exactly?
On which android version?
what is the path for osmand to store its data as defined in Osmand's generall settings inside app?

**Comment by enomat** [comment]
There is also a crash bug. I noticed it with the "Distance calculator & planning tool" plugin.

For clean testing, I started everything from the beginning. Uninstalled Osmand, deleted it's folder, installed the latest nightly (2.2.0#12479M), now everything is on default settings.

-started Osmand
-opened the plugins menu (tap "show all" on dashboard)
-enabled "Distance calculator & planning tool"
-pressed back button

and then Osmand crashed. Crash report:


Version  OsmAnd~ 2.2.0#12479M
17.08.2015 7:04:00
Apk Version : 2.2.0#12479M 211
Exception occured in thread Thread[main,5,main] : 
java.lang.RuntimeException: Unable to resume activity {net.osmand.plus/net.osmand.plus.activities.MapActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2639)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2667)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1279)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4921)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at net.osmand.plus.views.OsmandMapTileView.addLayer(OsmandMapTileView.java:259)
	at net.osmand.plus.distancecalculator.DistanceCalculatorPlugin.updateLayers(DistanceCalculatorPlugin.java:103)
	at net.osmand.plus.OsmandPlugin.refreshLayers(OsmandPlugin.java:217)
	at net.osmand.plus.activities.MapActivityLayers.updateLayers(MapActivityLayers.java:181)
	at net.osmand.plus.activities.MapActivity.updateApplicationModeSettings(MapActivity.java:740)
	at net.osmand.plus.activities.MapActivity.onResume(MapActivity.java:382)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1199)
	at android.app.Activity.performResume(Activity.java:5280)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2629)
	... 10 more
Version  OsmAnd~ 2.2.0#12479M
17.08.2015 7:04:00
Apk Version : 2.2.0#12479M 211
Exception occured in thread Thread[main,5,main] : 
java.lang.RuntimeException: Unable to resume activity {net.osmand.plus/net.osmand.plus.activities.MapActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2639)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2667)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1279)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4921)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at net.osmand.plus.views.OsmandMapTileView.addLayer(OsmandMapTileView.java:259)
	at net.osmand.plus.distancecalculator.DistanceCalculatorPlugin.updateLayers(DistanceCalculatorPlugin.java:103)
	at net.osmand.plus.OsmandPlugin.refreshLayers(OsmandPlugin.java:217)
	at net.osmand.plus.activities.MapActivityLayers.updateLayers(MapActivityLayers.java:181)
	at net.osmand.plus.activities.MapActivity.updateApplicationModeSettings(MapActivity.java:740)
	at net.osmand.plus.activities.MapActivity.onResume(MapActivity.java:382)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1199)
	at android.app.Activity.performResume(Activity.java:5280)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2629)
	... 10 more

**Comment by enomat** [comment]
@vshcherb 

I've also tested the previously mentioned nightly Osmand apk on another phone, on a Sony Xperia L (C2105), Android 4.1.2 .
A clean, fresh install, and it has all the same problems with the distance calculator plugin (if the plugin has been enabled and back button is pressed, Osmand crashed, error when trying to save the GPX).

**Comment by vshcherb** [comment]
Crash has fixed. Please verify, in case it fails please provide another log.

**Comment by enomat** [comment]
@vshcherb 
I confirm that the crash is fixed. Thanks.

However, the other bug, "Error while saving GPX" is still not fixed.

This thread/issue contains 2 different bug reports. While the crash bug is fixed, the other isn't.
So I will edit this issue and move the report about the GPX saving error in a separate issue.
