### ISSUE TITLE
Exception at net.osmand.binary.BinaryMapRouteReaderAdapter.readRouteTree 

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#15708]
```
Version  OsmAnd+ 4.3.0
13.11.2022 9:39:44
Apk Version : 4.3.0 4300
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalStateException: InputStream#read(byte[]) returned invalid result: 5120
The InputStream implementation is buggy.
	at com.google.protobuf.CodedInputStream.refillBuffer(CodedInputStream.java:768)
	at com.google.protobuf.CodedInputStream.isAtEnd(CodedInputStream.java:718)
	at com.google.protobuf.CodedInputStream.readTag(CodedInputStream.java:105)
	at net.osmand.binary.BinaryMapRouteReaderAdapter.readRouteTree(BinaryMapRouteReaderAdapter.java:992)
	at net.osmand.binary.BinaryMapRouteReaderAdapter.searchRouteRegionTree(BinaryMapRouteReaderAdapter.java:1120)
	at net.osmand.binary.BinaryMapIndexReader.searchRouteIndexTree(BinaryMapIndexReader.java:2696)
	at net.osmand.router.network.NetworkRouteContext.loadRoutingDataTile(NetworkRouteContext.java:200)
	at net.osmand.router.network.NetworkRouteContext.loadTile(NetworkRouteContext.java:179)
	at net.osmand.router.network.NetworkRouteContext.getMapRouteTile(NetworkRouteContext.java:162)
	at net.osmand.router.network.NetworkRouteContext.loadRouteSegmentTile(NetworkRouteContext.java:84)
	at net.osmand.router.network.NetworkRouteContext.loadRouteSegmentsBbox(NetworkRouteContext.java:76)
	at net.osmand.router.network.NetworkRouteSelector.getRoutes(NetworkRouteSelector.java:110)
	at net.osmand.plus.views.layers.MapSelectionHelper.putRouteGpxToSelected(MapSelectionHelper.java:444)
	at net.osmand.plus.views.layers.MapSelectionHelper.addRoute(MapSelectionHelper.java:433)
	at net.osmand.plus.views.layers.MapSelectionHelper.selectObjectsFromOpenGl(MapSelectionHelper.java:320)
	at net.osmand.plus.views.layers.MapSelectionHelper.selectObjectsFromMap(MapSelectionHelper.java:133)
	at net.osmand.plus.views.layers.ContextMenuLayer.showContextMenu(ContextMenuLayer.java:717)
	at net.osmand.plus.views.layers.ContextMenuLayer.onSingleTap(ContextMenuLayer.java:863)
	at net.osmand.plus.views.OsmandMapTileView$MapTileViewOnGestureListener.onSingleTapConfirmed(OsmandMapTileView.java:1863)
	at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:323)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

No idea how to reproduce.

**Comment by vshcherb** [comment]
This could be everything, very likely multithreading issue

**Comment by vshcherb** [comment]
Probably we can switch to Thread of https://github.com/osmandapp/OsmAnd/blob/47c2ef5e4416a57efe462e77a00520dbe85d9a2b/OsmAnd/src/net/osmand/plus/resources/ResourceManager.java#L129
or REVERSE_GEOCODING....
