### ISSUE TITLE
When I use the navigation function, the software is terminated!

### ISSUE THREAD

**Issue by wanganwhu** [osmandapp/Osmand#1570]
When I use the navigation function, the software is terminated.The exception.log is as follows.

Version  OsmAnd~ 2.2.0
18.08.2015 10:24:45
Apk Version : 2.2.0 211
Exception occured in thread Thread[Calculating position,5,main] : 
java.lang.IllegalStateException: java.lang.IllegalArgumentException: is == null
	at net.osmand.router.RoutingConfiguration.getDefault(RoutingConfiguration.java:171)
	at net.osmand.plus.AppInitializer.getLazyDefaultRoutingConfig(AppInitializer.java:302)
	at net.osmand.plus.OsmandApplication.getDefaultRoutingConfig(OsmandApplication.java:649)
	at net.osmand.plus.CurrentPositionHelper.initCtx(CurrentPositionHelper.java:40)
	at net.osmand.plus.CurrentPositionHelper.runUpdateInThread(CurrentPositionHelper.java:48)
	at net.osmand.plus.CurrentPositionHelper.runUpdateInThreadCatch(CurrentPositionHelper.java:92)
	at net.osmand.plus.CurrentPositionHelper$1.run(CurrentPositionHelper.java:72)
	at net.osmand.plus.routing.RoutingHelper$4.run(RoutingHelper.java:894)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.IllegalArgumentException: is == null
	at org.kxml2.io.KXmlParser.setInput(KXmlParser.java:1625)
	at net.osmand.router.RoutingConfiguration.parseFromInputStream(RoutingConfiguration.java:184)
	at net.osmand.router.RoutingConfiguration.getDefault(RoutingConfiguration.java:169)
	... 8 more

**Comment by wanganwhu** [comment]
The software is downloaded from https://github.com/osmandapp/Osmand and compiled by myself.
If I use the software downloaded https://f-droid.org/repo/net.osmand.plus_212.apk,everything is OK.
I think the problem may  be caused by compiling.

**Comment by vshcherb** [comment]
The issue that routing.xml is not present, I think running gradle and having download all the packages will solve that issue https://github.com/osmandapp/OsmAnd-manifest/blob/master/android_build.xml

**Comment by wanganwhu** [comment]
Thank you very much for your guidance.I am a green hand for android development. Routing.xml is not a typical AndroidManifest.xml,I do not know how to deal with it.I use android studio and windows10.
I imported https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml into Osmand/res.But it did not work.
