### ISSUE TITLE
Exception when tapping on weather plugin 

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#15720]
```
Version  OsmAnd+ 4.3.0
14.11.2022 11:38:29
Apk Version : 4.3.0 4300
Exception occured in thread Thread[main,5,main] : 
java.lang.ClassCastException: com.dsi.ant.plugins.antplus.pcc.AntPlusBikePowerPcc$MeasurementDataType cannot be cast to net.osmand.plus.plugins.weather.WeatherInfoType
	at net.osmand.plus.plugins.weather.WeatherPlugin.getSelectedContoursType(WeatherPlugin.java:1196)
	at net.osmand.plus.plugins.weather.WeatherMainFragment.setupWeatherContours(WeatherMainFragment.java:113)
	at net.osmand.plus.plugins.weather.WeatherMainFragment.onCreateView(WeatherMainFragment.java:64)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
	at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

How to reproduce: tap on configure map / weather.

**Comment by scaidermern** [comment]
Also for some reason it is not possible anymore to enable/disable(?) the weather plugin. The plugin screen displays it as disabled (although the weather menu item exists at configure map). In the weather plugin settings there is just a grey button called "off". Pressing it does nothing.

I definitely used this plugin yesterday and added widgets like temperature to the screen. Afterwards I removed these widgets again.

**Comment by vshcherb** [comment]
Probably you have opengl disabled?

**Comment by scaidermern** [comment]
> Probably you have opengl disabled?

No, definitely not. 2.5D is available and also the new 3D elevation rendering.

**Comment by scaidermern** [comment]
> > Probably you have opengl disabled?
> 
> No, definitely not. 2.5D is available and also the new 3D elevation rendering.

I'm taking this back. OpenGL was disabled. However, I don't know why. I'm pretty sure I didn't disable it. After enabling it the crash doesn't occur anymore.

Still, would be a good idea to prevent this crash in the first way. That's why I keep this ticket open.

**Comment by cepprice** [comment]
Already [fixed](https://github.com/osmandapp/OsmAnd/commit/c2541fa55df30726da17d9ec2c48c0113e22429e). This fix is included in nighly and will be included in next beta update
