### ISSUE TITLE
2.1 crashes when coordinates are not on a road (requires reproducing steps)

### ISSUE THREAD

**Issue by hvdwolf** [osmandapp/Osmand#1574]
Osmand 2.1.1 has become extremely sensible for startpoints/destinations not on a road. In previous versions when a coordinate (start/destination/waypoint) was too far of a road it simply could not calculate a route and gave an error message.
Now, with favorites which have always worked and are sometimes 3-5 meters of a road, also due to small map changes over the months/years, OsmAnd crashes all the time. It doesn't even give a warning//error message.
I really have to put the starting point and destination on a road to be able to do a calculation.

Osmand+ 2.1.1 from google Play. Samsung S4 mini Android 4.4.2

**Comment by hvdwolf** [comment]
I did more tests last night.

1. It does not always crash, but when it crashes you really need to reboot the phone as obviously "something" remains in memory or on disk which causes OsmAnd to crash a full 100% afterwards.

2. It crashes more, in my tests, when a starting point is not on a road then with a destination not on a road.

3. It's really unpredicatable. I continued to do every test on a "cleanly" rebooted phone (takes quite some time). Some startpoint/destination point calculation combis crash in one attempt and not in the other.

Please note that this is always when doing calculations "on the sofa" without a GPS lock, so with a startpoint/destination combi.

**Comment by rejdi** [comment]
Yesterday I had 2 crashes that made me angry, since we had to abort our trip. I think, It could be related to this issue.

First crash occured when we had to turn back due to road accident ahead of us (route was correctly calculated so I think osmand tried to recalculate it.).
Second crash occured when I was trying to add "via" point after phone restart.

Here is the stack-trace.

Version  OsmAnd 2.1.1
21.08.2015 6:09:50
Apk Version : 2.1.1 212
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException
	at android.widget.ArrayAdapter.init(ArrayAdapter.java:310)
	at android.widget.ArrayAdapter.<init>(ArrayAdapter.java:153)
	at net.osmand.plus.myplaces.SelectedGPXFragment$SelectedGPXAdapter.<init>(SelectedGPXFragment.java:423)
	at net.osmand.plus.myplaces.SelectedGPXFragment.setContent(SelectedGPXFragment.java:152)
	at net.osmand.plus.activities.TrackActivity$1.onPostExecute(TrackActivity.java:96)
	at net.osmand.plus.activities.TrackActivity$1.onPostExecute(TrackActivity.java:76)
	at android.os.AsyncTask.finish(AsyncTask.java:631)
	at android.os.AsyncTask.access$600(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:155)
	at android.app.ActivityThread.main(ActivityThread.java:5520)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
	at dalvik.system.NativeStart.main(Native Method)
Version  OsmAnd 2.1.1
21.08.2015 6:15:06
Apk Version : 2.1.1 212
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalArgumentException: View not attached to window manager
	at android.view.WindowManagerImpl.findViewLocked(WindowManagerImpl.java:784)
	at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:476)
	at android.view.WindowManagerImpl$CompatModeWrapper.removeView(WindowManagerImpl.java:182)
	at android.app.Dialog.dismissDialog(Dialog.java:328)
	at android.app.Dialog.dismiss(Dialog.java:311)
	at android.app.Dialog.cancel(Dialog.java:1117)
	at android.app.Dialog.onTouchEvent(Dialog.java:630)
	at android.app.Dialog.dispatchTouchEvent(Dialog.java:752)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1955)
	at android.view.View.dispatchPointerEvent(View.java:7392)
	at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3577)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3506)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4620)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4599)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4695)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:200)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:131)
	at android.os.Looper.loop(Looper.java:132)
	at android.app.ActivityThread.main(ActivityThread.java:5520)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
	at dalvik.system.NativeStart.main(Native Method)
Version  OsmAnd 2.1.1
21.08.2015 6:15:06
Apk Version : 2.1.1 212
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalArgumentException: View not attached to window manager
	at android.view.WindowManagerImpl.findViewLocked(WindowManagerImpl.java:784)
	at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:476)
	at android.view.WindowManagerImpl$CompatModeWrapper.removeView(WindowManagerImpl.java:182)
	at android.app.Dialog.dismissDialog(Dialog.java:328)
	at android.app.Dialog.dismiss(Dialog.java:311)
	at android.app.Dialog.cancel(Dialog.java:1117)
	at android.app.Dialog.onTouchEvent(Dialog.java:630)
	at android.app.Dialog.dispatchTouchEvent(Dialog.java:752)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1955)
	at android.view.View.dispatchPointerEvent(View.java:7392)
	at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3577)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3506)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4620)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4599)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4695)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:200)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:131)
	at android.os.Looper.loop(Looper.java:132)
	at android.app.ActivityThread.main(ActivityThread.java:5520)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
	at dalvik.system.NativeStart.main(Native Method)
Version  OsmAnd 2.1.1
21.08.2015 6:15:06
Apk Version : 2.1.1 212
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalArgumentException: View not attached to window manager
	at android.view.WindowManagerImpl.findViewLocked(WindowManagerImpl.java:784)
	at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:476)
	at android.view.WindowManagerImpl$CompatModeWrapper.removeView(WindowManagerImpl.java:182)
	at android.app.Dialog.dismissDialog(Dialog.java:328)
	at android.app.Dialog.dismiss(Dialog.java:311)
	at android.app.Dialog.cancel(Dialog.java:1117)
	at android.app.Dialog.onTouchEvent(Dialog.java:630)
	at android.app.Dialog.dispatchTouchEvent(Dialog.java:752)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1955)
	at android.view.View.dispatchPointerEvent(View.java:7392)
	at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3577)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3506)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4620)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4599)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4695)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:200)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:131)
	at android.os.Looper.loop(Looper.java:132)
	at android.app.ActivityThread.main(ActivityThread.java:5520)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
	at dalvik.system.NativeStart.main(Native Method)
Version  OsmAnd 2.1.1
21.08.2015 6:36:30
Apk Version : 2.1.1 212
Exception occured in thread Thread[Calculating position,5,main] : 
java.lang.RuntimeException: Loading data exception
	at net.osmand.router.RoutingContext.loadTileHeaders(RoutingContext.java:429)
	at net.osmand.router.RoutingContext.loadTileHeaders(RoutingContext.java:361)
	at net.osmand.router.RoutingContext.getRoutingTile(RoutingContext.java:498)
	at net.osmand.router.RoutingContext.loadTileData(RoutingContext.java:449)
	at net.osmand.router.RoutePlannerFrontEnd.findRouteSegment(RoutePlannerFrontEnd.java:61)
	at net.osmand.plus.CurrentPositionHelper.runUpdateInThread(CurrentPositionHelper.java:53)
	at net.osmand.plus.CurrentPositionHelper.runUpdateInThreadCatch(CurrentPositionHelper.java:92)
	at net.osmand.plus.CurrentPositionHelper$1.run(CurrentPositionHelper.java:72)
	at net.osmand.plus.routing.RoutingHelper$4.run(RoutingHelper.java:867)
	at java.lang.Thread.run(Thread.java:864)
Caused by: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either than the input has been truncated or that an embedded message misreported its own length.
	at com.google.protobuf.CodedInputStream.pushLimit(CodedInputStream.java:614)
	at net.osmand.binary.BinaryMapRouteReaderAdapter.searchRouteRegionTree(BinaryMapRouteReaderAdapter.java:753)
	at net.osmand.binary.BinaryMapIndexReader.searchRouteIndexTree(BinaryMapIndexReader.java:2387)
	at net.osmand.router.RoutingContext.loadTileHeaders(RoutingContext.java:408)
	... 9 more

**Comment by vshcherb** [comment]
From the crash log, map seems to be corrupted. Can you please try to redownload the map?  (It looks the map you driving on). Can you please also say which layers do you use. 

The workaround of the crash could be to disable address name on the header, but it doesn't seem to be an issue for other users, so I strongly suspect env issue.

**Comment by rejdi** [comment]
I reinstalled Osmand with yeasterday nightly and redownloaded all maps. Unfortunatelly I don't remember exactly which layers I was using, but I think Osmand rendering for map and the rest was default. Today, everything with new version went smooth.

**Comment by hvdwolf** [comment]
I was using the Contour line plugin. Without contour lines but with hillshades.
App crashed immediately. Upon restart I disabled the contour line plugin and the calculation went fine. Until now that did never work after simply restarting OsmAnd.
I did some more tests but it seems to keep on working without the contour lines plugin with hillshades.

Other plugins active: Trip recording, Parking position, OSM editing, OsmAnd development

**Comment by vshcherb** [comment]
If hillshade plugin affects behavior most likely there is an issue with memory, i'm not sure which device is used, using any additional layer grows the memory and Android limits that memory (depends on OS) from 16 to 50 MB. Certainly 16 MB devices have that issue and the crash could happen in any place actually, please take a look Development -> Settings (memory usage information)

**Comment by hvdwolf** [comment]
The mentioned S5 mini I now have has 1.5GB memory, so that shouldn't be a problem.

Fresh start with immediate check of memory via the development plugin
Without Controur lines (hill shades):
Allocated memory 37 MB (android limit 49 MB, Dalvik 10MB)
Total native memory allocated to app 0MB (Dalvik 40 MB, other 14MB. Proportional memeory 0MB (Android limit 40 MB, Dalvik 23MB)

After restart with Contour lines (hill shades):
Allocated memory 37 MB (android limit 43 MB, Dalvik 10MB)
Total native memory allocated to app 0MB, Dalvik 34 MB, other 14MB. Proportional memory 0MB (Android limit 34 MB, Dalvik 23MB)

**Comment by vshcherb** [comment]
First exception is not an issue any more.
I suspect second exception could be an issue if the contour lines contain routing section. 

I just tested on Netherlands,  download and enable contour lines, select start point from 300 m and it still doesn't crash.

**Comment by vshcherb** [comment]
Unless you are running in safe mode, I have no clue what could be an issue and I'm trying and not able to reproduce.

**Comment by hvdwolf** [comment]
With the last few nightly builds, OsmAnd always crashes when having selected a favorite, displaying it on the map and then tapping it on the map.

**Comment by vshcherb** [comment]
>> With the last few nightly builds, OsmAnd always crashes when having selected a favorite, displaying it on the map and then tapping it on the map.
Today were couple of fixes, could you please try or create another issue.

**Comment by hvdwolf** [comment]
I downloaded the nightly from today 05:28 and the one fron 12:47 today 29 Spet, but they still crash: always.
I also created new favorites, to see whether that made a difference. but upon selecting, displaying and tap on them OsmAnd still always crashes.

**Comment by vshcherb** [comment]
Could you please attach log file for that crash.

**Comment by hvdwolf** [comment]
Even though github mentions it, it is not possible to attach a log file,
not even when renaming the extension.
So please find a "fresh" log file attached to this mail.

I also sent it a couple of times via gmail out of OsmAnd after startup.

Harry

2015-09-29 14:52 GMT+02:00 vshcherb <notifications@github.com>:

**Comment by vshcherb** [comment]
Sorry, attached to which email? It is possible to do like this https://github.com/osmandapp/Osmand/issues/1574#issuecomment-133675100 or rename it to text file

**Comment by hvdwolf** [comment]
I did rename it to .txt, but I can't attach it. Neither by selecting them or drag&drop them.
Ok. directly in the post.


Version  OsmAnd~ 2.2.0#13289M
29.09.2015 6:18:57
Apk Version : 2.2.0#13289M 211
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException
	at net.osmand.plus.views.ContextMenuLayer.showMapContextMenu(ContextMenuLayer.java:534)
	at net.osmand.plus.views.ContextMenuLayer.showMapContextMenu(ContextMenuLayer.java:526)
	at net.osmand.plus.views.ContextMenuLayer.showContextMenuForSelectedObjects(ContextMenuLayer.java:509)
	at net.osmand.plus.views.ContextMenuLayer.onSingleTap(ContextMenuLayer.java:468)
	at net.osmand.plus.views.OsmandMapTileView$MapTileViewOnGestureListener.onSingleTapConfirmed(OsmandMapTileView.java:975)
	at net.osmand.access.MapExplorer.onSingleTapConfirmed(MapExplorer.java:133)
	at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:341)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5694)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
	at dalvik.system.NativeStart.main(Native Method)
Version  OsmAnd~ 2.2.0#13289M
29.09.2015 6:18:57
Apk Version : 2.2.0#13289M 211
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException
	at net.osmand.plus.views.ContextMenuLayer.showMapContextMenu(ContextMenuLayer.java:534)
	at net.osmand.plus.views.ContextMenuLayer.showMapContextMenu(ContextMenuLayer.java:526)
	at net.osmand.plus.views.ContextMenuLayer.showContextMenuForSelectedObjects(ContextMenuLayer.java:509)
	at net.osmand.plus.views.ContextMenuLayer.onSingleTap(ContextMenuLayer.java:468)
	at net.osmand.plus.views.OsmandMapTileView$MapTileViewOnGestureListener.onSingleTapConfirmed(OsmandMapTileView.java:975)
	at net.osmand.access.MapExplorer.onSingleTapConfirmed(MapExplorer.java:133)
	at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:341)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5694)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by Barrocas** [comment]
@ hvdwolf - "OsmAnd always crashes when having selected a favorite, displaying it on the map and then tapping it on the map." - I can confirm this behavior on today night build, using a Bq Aquaris E6.

**Comment by sonora** [comment]
Deprecated.
