### ISSUE TITLE
Exception at DownloadedRegionsLayer.queryData

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#15771]
```
Version  OsmAnd+ 4.3.0
18.11.2022 7:19:53
Apk Version : 4.3.0 4300
Exception occured in thread Thread[AsyncTask #16,5,main] : 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NullPointerException: Attempt to read from field 'double net.osmand.data.QuadRect.left' on a null object reference
	at net.osmand.plus.views.layers.DownloadedRegionsLayer.queryData(DownloadedRegionsLayer.java:407)
	at net.osmand.plus.views.layers.DownloadedRegionsLayer.access$000(DownloadedRegionsLayer.java:69)
	at net.osmand.plus.views.layers.DownloadedRegionsLayer$1.calculateResult(DownloadedRegionsLayer.java:203)
	at net.osmand.plus.views.layers.DownloadedRegionsLayer$1.calculateResult(DownloadedRegionsLayer.java:179)
	at net.osmand.plus.views.layers.base.OsmandMapLayer$MapLayerData$Task.doInBackground(OsmandMapLayer.java:786)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
```

Occured while panning the map.

**Comment by vshcherb** [comment]
Looks weird and probably bug in Android VM. Let's see if it happens often
