### ISSUE TITLE
AIDL : OsmandAidlApi null

### ISSUE THREAD

**Issue by MyAlpDroid** [osmandapp/OsmAnd#15781]
### Description & how to reproduce :
Hi, after registring for update (registerForNavigationUpdates) , each update cause android.os.DeadObjectException  exception :

OsmandAidlService AIDL V2 e.getMessage()
android.os.DeadObjectException
                                                                                                    	at android.os.BinderProxy.transactNative(Native Method)
                                                                                                    	at android.os.BinderProxy.transact(BinderProxy.java:575)
                                                                                                    	at net.osmand.aidlapi.IOsmAndAidlCallback$Stub$Proxy.onUpdate(IOsmAndAidlCallback.java:277)
at net.osmand.aidl.OsmandAidlServiceV2$1$2.run(OsmandAidlServiceV2.java:924)
..
and next

OsmandAidlApi null
                                                                                                    android.os.DeadObjectException
                                                                                                    	at android.os.BinderProxy.transactNative(Native Method)
                                                                                                    	at android.os.BinderProxy.transact(BinderProxy.java:575)
                                                                                                    	at net.osmand.aidlapi.IOsmAndAidlCallback$Stub$Proxy.updateNavigationInfo(IOsmAndAidlCallback.java:358)
at net.osmand.aidl.OsmandAidlApi.lambda$registerForNavigationUpdates$0$OsmandAidlApi(OsmandAidlApi.java:2122)

### Your Environment
OsmAnd Version: 4.2.7
Android/iOS version:10
Device model: Samsung Galaxy tab S4
Maps France Online

Same problem is happening with osmand api demo.

**Comment by MyAlpDroid** [comment]
Rewriting code, issue disappear.
