### ISSUE TITLE
V4.3.1 crashing when searching for "home" 

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#15870]
### Description
Since the update to 4.3.1 I can´t search for "Home". Typing the letters until "Hom" is ok, but as soon as entering the fourth letter "e" Osmand crashes immediately. Afer a few tries/crashes Osmand tells me to clear the cache, but that does not help.

There are several favourites which names contain "Home". Like "Home xyz" or "xyz Home". Searching for "xyz" displays all the favourites with "home" in their name and also displaying and routing does work. It´s just typing the letters "Home".

### How to reproduce?
Have sent some crash reports to crash@osmand.net

### Your Environment
OsmAnd Version: 4.3.1
Android/iOS version: 13
Device model: S20+

**Comment by scaidermern** [comment]
Same for me:

```
Version  OsmAnd+ 4.3.1
30.11.2022 3:02:19
Apk Version : 4.3.1 4301
Exception occured in thread Thread[main,5,main] : 
java.lang.ClassCastException: net.osmand.search.core.SearchCoreFactory$PoiAdditionalCustomFilter cannot be cast to net.osmand.osm.PoiType
	at net.osmand.plus.search.listitems.QuickSearchListItem.getIcon(QuickSearchListItem.java:332)
	at net.osmand.plus.search.listitems.QuickSearchListItem.getIcon(QuickSearchListItem.java:298)
	at net.osmand.plus.search.QuickSearchListAdapter.bindSearchResult(QuickSearchListAdapter.java:523)
	at net.osmand.plus.search.QuickSearchListAdapter.bindSearchResultItem(QuickSearchListAdapter.java:455)
	at net.osmand.plus.search.QuickSearchListAdapter.getView(QuickSearchListAdapter.java:242)
	at android.widget.AbsListView.obtainView(AbsListView.java:2405)
	at android.widget.ListView.makeAndAddView(ListView.java:2067)
	at android.widget.ListView.fillDown(ListView.java:793)
	at android.widget.ListView.fillFromTop(ListView.java:855)
	at android.widget.ListView.layoutChildren(ListView.java:1838)
	at android.widget.AbsListView.onLayout(AbsListView.java:2202)
	at android.view.View.layout(View.java:22466)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22466)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22466)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22466)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22466)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22466)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22466)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:779)
	at android.view.View.layout(View.java:22466)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3157)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2614)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1745)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7768)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
	at android.view.Choreographer.doCallbacks(Choreographer.java:791)
	at android.view.Choreographer.doFrame(Choreographer.java:726)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

**Comment by scaidermern** [comment]
Same crash when searching for "tree".

**Comment by pebogufi** [comment]
https://download.osmand.net/releases/

**Comment by Rowin63** [comment]
> https://download.osmand.net/releases/

Did not find any "plus"-Version there...? 
Installing the 3.4.0 from there does not include my existing data, because it installs in a different folder (not the existing "plus"-folder)
