### ISSUE TITLE
ArrayIndexOutOfBoundsException at gnu.trove.map.hash.TLongObjectHashMap.rehash / net.osmand.plus.utils.UiUtilities.getDrawable

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#15888]
```
Version  OsmAnd+ 4.3.1
03.12.2022 10:40:23
Apk Version : 4.3.1 4301
Exception occured in thread Thread[main,5,main] : 
java.lang.ArrayIndexOutOfBoundsException: length=197; index=396
	at gnu.trove.map.hash.TLongObjectHashMap.rehash(TLongObjectHashMap.java:173)
	at gnu.trove.impl.hash.THash.postInsertHook(THash.java:387)
	at gnu.trove.map.hash.TLongObjectHashMap.doPut(TLongObjectHashMap.java:269)
	at gnu.trove.map.hash.TLongObjectHashMap.put(TLongObjectHashMap.java:240)
	at net.osmand.plus.utils.UiUtilities.getDrawable(UiUtilities.java:111)
	at net.osmand.plus.utils.UiUtilities.getIcon(UiUtilities.java:140)
	at net.osmand.plus.widgets.ctxmenu.ViewCreator.setupIcon(ViewCreator.java:324)
	at net.osmand.plus.widgets.ctxmenu.ViewCreator.getView(ViewCreator.java:117)
	at net.osmand.plus.configmap.ConfigureMapFragment.bindItemView(ConfigureMapFragment.java:197)
	at net.osmand.plus.configmap.ConfigureMapFragment.bindCategoryView(ConfigureMapFragment.java:190)
	at net.osmand.plus.configmap.ConfigureMapFragment.updateItemsView(ConfigureMapFragment.java:149)
	at net.osmand.plus.configmap.ConfigureMapFragment.recreateView(ConfigureMapFragment.java:130)
	at net.osmand.plus.configmap.ConfigureMapFragment.onDataSetInvalidated(ConfigureMapFragment.java:92)
	at net.osmand.plus.configmap.ConfigureMapFragment.onCreateView(ConfigureMapFragment.java:81)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
	at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

Occurred while zooming, If I remember correctly.

**Comment by vshcherb** [comment]
Let's see how often it's reproduced (we didn't manage yet) cause the  reason is unknown and it's hard to trace any possibility

**Comment by scaidermern** [comment]
And another one:

```
Version  OsmAnd+ 4.3.7
10.02.2023 7:09:15
Apk Version : 4.3.7 4307
Exception occured in thread Thread[main,5,main] : 
java.lang.ArrayIndexOutOfBoundsException: length=397; index=-173
	at gnu.trove.map.hash.TLongObjectHashMap.rehash(TLongObjectHashMap.java:176)
	at gnu.trove.impl.hash.THash.postInsertHook(THash.java:387)
	at gnu.trove.map.hash.TLongObjectHashMap.doPut(TLongObjectHashMap.java:269)
	at gnu.trove.map.hash.TLongObjectHashMap.put(TLongObjectHashMap.java:240)
	at net.osmand.plus.utils.UiUtilities.getDrawable(UiUtilities.java:111)
	at net.osmand.plus.utils.UiUtilities.getIcon(UiUtilities.java:140)
	at net.osmand.plus.mapcontextmenu.MapContextMenuFragment.updateImageButton(MapContextMenuFragment.java:722)
	at net.osmand.plus.mapcontextmenu.MapContextMenuFragment.onCreateView(MapContextMenuFragment.java:537)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
	at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

**Comment by sonora** [comment]
Is "31l" correct here?
https://github.com/osmandapp/OsmAnd/blob/d0b3e0be3c016431bec7c68b6fd1be2fb5b196bd/OsmAnd/src/net/osmand/plus/utils/UiUtilities.java#L102

**Comment by vshcherb** [comment]
> .TLongObjectHashMap.rehash

is probably hash is not consistent doesn't matter 31 or 32 it just changes somewhere over time.

**Comment by Chumva** [comment]
It is possible that this issue appeared due to access from different threads, but I cannot find where we get icons in non-ui threads

**Comment by sonora** [comment]
How about also changing `<<31L` to `<<32L`? Couldn't otherwise two completely different drawables receive the same hash code and this may cause issues?

**Comment by vshcherb** [comment]
@sonora same hash is not a problem for hashmap! it only could slightly slow down - hashes are ints and not longs so you can't << 31. 
So the worst slow down if all hashes will to same bucket. If > 50% has 1 value per hash and others 2-4 - it's almost perfect hash. Please keep in mind that hashmap first stores all values in 16, 32 size array so only 4-5 bits from hash are used and only if it grows then more hashes are used, so in the end most important that last bits are randomly even distributed and not important if higher are the same .

**Comment by sonora** [comment]
Quite possibly I misunderstand something here, and if so, please forgive me.

I am not talking about the hash map or hash functionality per se, but the variable `long hash`, which in `private Drawable getPaintedDrawable(@DrawableRes int resId, @ColorInt int color)` we use as the **index** to retrieve a drawable:: `drawable = drawableCache.get(hash)`.

It seems to me that via `long hash = ((long) resId << 31L) + color;` two different drawables could actually receive the same index `hash`, so that when calling `drawable = drawableCache.get(hash)` we may receive the wrong result?

Here's an example:
**drawable 1 has**

- `resId`=1, <<31L=2,147,483,648
- `color`=0xFFFFFFFF=4,294,967,295
- `hash`=**6,442,450,943**

**drawable 2:**

- `resId`=2, <<31L=4,294,967,296
- `color`=0x7FFFFFFF==2,147,483,647
- `hash`=**6,442,450,943**

**Comment by vshcherb** [comment]
>> yes the could receive same hash.

What is the chance we have so many same icons? Cause this color is quite rare.

Further more **hash** is **int**, so all upper bits will be discarded. And we get horrible hash cause all bits are the same. I will fix it by having proper version. resId * 7 + color

**Comment by vshcherb** [comment]
I just realized it's not a hash, it's a key - https://github.com/osmandapp/OsmAnd/commit/d4fbb3a954d6c9a461116953398b57466a78e5a8. So indeed we need to avoid duplicates.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14194mqta, Released: 2023-02-22
There are no crashes when zoom changing
