### ISSUE TITLE
Route line not rendered anymore after switching to OpenGL

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#16069]
The route line disappears when switching from v1 rendering engine to v2 *while having an active routing*. 

![IMG_20221226_122733](https://user-images.githubusercontent.com/1040784/209544146-7bf43ab9-279b-49ed-95ad-cc152fc0e64d.jpg)

After stopping and restarting routing everything is displayed correctly again.

**Comment by Zirochkabila** [comment]
Merge to https://github.com/osmandapp/OsmAnd/issues/15928#issuecomment-1361131929

**Comment by scaidermern** [comment]
> Merge to [#15928 (comment)](https://github.com/osmandapp/OsmAnd/issues/15928#issuecomment-1361131929)

I fail to see how these two are related 🤔

**Comment by Zirochkabila** [comment]
@scaidermern The comment on the link states that - Observation (pending): if you change the rendering to Legacy and then back to OpenGL, **the route disappears from the map** and the blue dot is no longer displayed. Only turn lanes are displayed.

**Comment by scaidermern** [comment]
> @scaidermern The comment on the link states that - Observation (pending): if you change the rendering to Legacy and then back to OpenGL, **the route disappears from the map** and the blue dot is no longer displayed. Only turn lanes are displayed.

Oh, thanks, I missed that!

**Comment by vshcherb** [comment]
This bug is not going to be fixed cause Switch Rendering engine is likely to require app restart in future, so there is no much sense yet. However I didn't reproduce and instead I've got a crash when switched from  OpenGL to Legacy
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Canvas.rotate(float, float, float)' on a null object reference
	at net.osmand.plus.views.layers.geometry.GeometryWay.drawRouteSegment(GeometryWay.java:598)
	at net.osmand.plus.views.layers.geometry.GeometryWay.drawSegments(GeometryWay.java:318)
	at net.osmand.plus.views.layers.RouteLayer.drawLocations(RouteLayer.java:503)
	at net.osmand.plus.views.layers.RouteLayer.drawLocations(RouteLayer.java:206)
	at net.osmand.plus.views.layers.RouteLayer.lambda$onUpdateFrame$0$net-osmand-plus-views-layers-RouteLayer(RouteLayer.java:161)
	at net.osmand.plus.views.layers.RouteLayer$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
```
