### ISSUE TITLE
Unidentified Crash Report [UCR]

### ISSUE THREAD

**Issue by d4f5409d** [osmandapp/OsmAnd#16147]
### Description
-

### How to reproduce?
-

### Your Environment
OsmAnd Version: 4.3.5
Android/iOS version: 12
Device model: 1+ 8

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

```Version  OsmAnd~ 4.2.7
09.12.2022 2:35:07
Apk Version : 4.2.7 4207
Exception occured in thread Thread[pool-7-thread-8,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
 at net.osmand.map.MapTileDownloader.fireLoadCallback(MapTileDownloader.java:279)
 at net.osmand.map.MapTileDownloader$DownloadMapWorker.run(MapTileDownloader.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
 at java.lang.Thread.run(Thread.java:1012)```

**Comment by vshcherb** [comment]
should be fixed in 4.5
