### ISSUE TITLE
Osmand crashes again...

### ISSUE THREAD

**Issue by MAlfare** [osmandapp/OsmAnd#16447]
...immediately after start

Android 8.1.0
Moto G4 Plus

Exception log:
Version  OsmAnd~ 4.4.0#35421m
11.02.2023 5:16:55
Apk Version : 4.4.0#35421m 4400
Exception occured in thread Thread[pool-13-thread-1,5,main] : 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:353)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalStateException: Rendering constant or attribute 'contourLineDepthColor100m' was not specified.
	at net.osmand.render.RenderingRulesStorage$RenderingRulesHandler.parseAttributes(RenderingRulesStorage.java:438)
	at net.osmand.render.RenderingRulesStorage$RenderingRulesHandler.parse(RenderingRulesStorage.java:278)
	at net.osmand.render.RenderingRulesStorage.parseRulesFromXmlInputStream(RenderingRulesStorage.java:134)
	at net.osmand.plus.render.RendererRegistry.loadRenderer(RendererRegistry.java:170)
	at net.osmand.plus.render.RendererRegistry.getRenderer(RendererRegistry.java:111)
	at net.osmand.plus.render.UpdateVectorRendererAsyncTask.doInBackground(UpdateVectorRendererAsyncTask.java:32)
	at net.osmand.plus.render.UpdateVectorRendererAsyncTask.doInBackground(UpdateVectorRendererAsyncTask.java:15)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Version  OsmAnd~ 4.4.0#35421m
11.02.2023 5:16:56
Apk Version : 4.4.0#35421m 4400
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalStateException: Rendering constant or attribute 'contourLineDepthColor100m' was not specified.
	at net.osmand.render.RenderingRulesStorage$RenderingRulesHandler.parseAttributes(RenderingRulesStorage.java:438)
	at net.osmand.render.RenderingRulesStorage$RenderingRulesHandler.parse(RenderingRulesStorage.java:278)
	at net.osmand.render.RenderingRulesStorage.parseRulesFromXmlInputStream(RenderingRulesStorage.java:134)
	at net.osmand.plus.render.RendererRegistry.loadRenderer(RendererRegistry.java:170)
	at net.osmand.plus.render.RendererRegistry.getRenderer(RendererRegistry.java:111)
	at net.osmand.plus.render.RendererRegistry.defaultRender(RendererRegistry.java:91)
	at net.osmand.plus.render.RendererRegistry.getCurrentSelectedRenderer(RendererRegistry.java:409)
	at net.osmand.plus.plugins.PluginsHelper.registerRenderingPreferences(PluginsHelper.java:600)
	at net.osmand.plus.plugins.PluginsHelper$1.onFinish(PluginsHelper.java:311)
	at net.osmand.plus.AppInitializer.lambda$notifyFinish$2$net-osmand-plus-AppInitializer(AppInitializer.java:710)
	at net.osmand.plus.AppInitializer$$ExternalSyntheticLambda3.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6647)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

**Comment by Zirochkabila** [comment]
@MAlfare duplicate https://github.com/osmandapp/OsmAnd/issues/16443 ?

**Comment by MAlfare** [comment]
Seems to be duplicate of #16443 indeed
