### ISSUE TITLE
Failed requests in download for srtm

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#16481]
Crash in HEAD method cause files are not present on main server (indexes.xml should be used)
```
java.io.FileNotFoundException: File: Russia_khabarovsk_vyazemsky_asia_2.srtm.obf.zip not found
	at net.osmand.server.controllers.pub.DownloadIndexController.getFileAsResource(DownloadIndexController.java:64)
	at net.osmand.server.controllers.pub.DownloadIndexController.findFileResource(DownloadIndexController.java:206)
	at net.osmand.server.controllers.pub.DownloadIndexController.checkRangeRequests(DownloadIndexController.java:286)
	at jdk.internal.reflect.GeneratedMethodAccessor89.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
```

**Comment by ivanPyrohivskyi** [comment]
In access.log file present rows like that:
37.201.4.79 - - [16/Feb/2023:12:17:56 +0100] "HEAD /download?standard=yes&file=**Heightmap_Argentina_san-juan_southamerica.tif** HTTP/1.1" 404 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0"

Fix accept for rows:
62.224.203.224 - - [18/Feb/2023:13:40:51 +0100] "HEAD /download.php?slope=yes&file=Slope_Germany_europe.sqlitedb HTTP/1.1" 404 0 "-" "Wget/1.21.2"
62.224.203.224 - - [18/Feb/2023:13:40:51 +0100] "HEAD /download.php?hillshade=yes&file=Hillshade_Germany_europe.sqlitedb HTTP/1.1" 404 0 "-" "Wget/1.21.2"

**Comment by ivanPyrohivskyi** [comment]
In access.log file present rows like that:
37.201.4.79 - - [16/Feb/2023:12:17:56 +0100] "HEAD /download?standard=yes&file=**Heightmap_Argentina_san-juan_southamerica.tif** HTTP/1.1" **404** 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0"
