### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16483]
### Description
Crash at startup
[exception (30).log](https://github.com/osmandapp/OsmAnd/files/10765798/exception.30.log)
```
Caused by: java.lang.IllegalStateException: Layer net.osmand.plus.views.layers.MapControlsLayer@d1891c9 not attached to MapActivity.
	at net.osmand.plus.views.layers.base.OsmandMapLayer.requireMapActivity(OsmandMapLayer.java:161)
	at net.osmand.plus.views.layers.MapControlsLayer.isMapControlsVisible(MapControlsLayer.java:527)
	at net.osmand.plus.views.layers.MapControlsLayer.showMapControlsIfHidden(MapControlsLayer.java:457)
	at net.osmand.plus.base.ContextMenuFragment.onResume(ContextMenuFragment.java:607)
	at net.osmand.plus.routepreparationmenu.MapRouteInfoMenuFragment.onResume(MapRouteInfoMenuFragment.java:136)
```

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14181mqta, Released: 2023-02-16
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14214mqta, Released: 2023-03-03
[exception (33).log](https://github.com/osmandapp/OsmAnd/files/10881054/exception.33.log)
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/222699819-0f5305b6-fff9-4a86-a102-24a3577cfa5f.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14222mqta, Released: 2023-03-07
Still present
[exception (34).log](https://github.com/osmandapp/OsmAnd/files/10911420/exception.34.log)

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/223477576-f5ce9fad-1415-4a52-b53b-c783deedd37c.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>
