### ISSUE TITLE
Sorting tracks causes the application to crash

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#16662]
### Description
When specifying in sorting item nearest osmand crashes
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/12549744/224476155-46adaa89-cffb-41f9-87e5-8b0fe7becd87.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

```
Version  OsmAnd~ 4.4.0#14230mqta
11.03.2023 12:12:11
Apk Version : 4.4.0#14230mqta 4400
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeLo(TimSort.java:781)
	at java.util.TimSort.mergeAt(TimSort.java:518)
	at java.util.TimSort.mergeCollapse(TimSort.java:448)
	at java.util.TimSort.sort(TimSort.java:245)
	at java.util.Arrays.sort(Arrays.java:1495)
	at java.util.ArrayList.sort(ArrayList.java:1470)
	at java.util.Collections.sort(Collections.java:206)
	at net.osmand.plus.configmap.tracks.SelectedTracksHelper.sortTrackTab(SelectedTracksHelper.java:197)
	at net.osmand.plus.configmap.tracks.TracksFragment.setTracksSortMode(TracksFragment.java:369)
	at net.osmand.plus.configmap.tracks.SortByBottomSheet$SortModesAdapter.lambda$onBindViewHolder$0$net-osmand-plus-configmap-tracks-SortByBottomSheet$SortModesAdapter(SortByBottomSheet.java:107)
	at net.osmand.plus.configmap.tracks.SortByBottomSheet$SortModesAdapter$$ExternalSyntheticLambda0.onClick(Unknown Source:6)
	at android.view.View.performClick(View.java:7753)
	at android.view.View.performClickInternal(View.java:7730)
	at android.view.View.access$3700(View.java:861)
	at android.view.View$PerformClick.run(View.java:29136)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8105)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

```

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14230mqta, Дата выпуска: 2023-03-11
Android version: 12
Device model: poco f3

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14230mqta, Released: 2023-03-11
I managed to reproduce it only at a cold start from the 7th attempt
[exception (36).log](https://github.com/osmandapp/OsmAnd/files/10948302/exception.36.log)

https://user-images.githubusercontent.com/104760013/224480384-379af865-f756-484b-8b8a-6d02378143b5.mp4

**Comment by Nine-Tailed** [comment]
most likely it's in a specific set of tracks

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14239mqta, Released: 2023-03-15
0/10 Looks done
