### ISSUE TITLE
Crash when trying to edit POI

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#16772]
### Description 
I selected poi and clicked the edit button in the context menu, after which the application crashed.

```
Version  OsmAnd~ 4.4.0#14259mqta
22.03.2023 11:45:02
Apk Version : 4.4.0#14259mqta 4400
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'net.osmand.osm.MapPoiTypes net.osmand.plus.OsmandApplication.getPoiTypes()' on a null object reference
	at net.osmand.plus.plugins.osmedit.data.EditPoiData.<init>(EditPoiData.java:39)
	at net.osmand.plus.plugins.osmedit.dialogs.EditPoiDialogFragment.onAttach(EditPoiDialogFragment.java:150)
	at androidx.fragment.app.Fragment.performAttach(Fragment.java:2574)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:828)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
	at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8105)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

```

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14261mqta, Released: 2023-03-23
[exception (42).log](https://github.com/osmandapp/OsmAnd/files/11048266/exception.42.log)

Chose POI > Actions > Modify POI


https://user-images.githubusercontent.com/104760013/227139345-df32a15a-bebe-4198-89b2-fd73224d2958.mp4

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#14270mqta, Released: 2023-03-25
Done
