### ISSUE TITLE
Crash in GpxTrackAdapter

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#16776]
Crash occurred during the following steps: Navigate / Settings / Follow track / Choose track

The crash occurred just once, no idea how to reproduce it.

```
Version  OsmAnd+ 4.4.3
22.03.2023 9:31:20
Apk Version : 4.4.3 4403
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalArgumentException: Called attach on a child which is not detached: TrackCategoriesViewHolder{cf772a position=0 id=-1, oldPos=-1, pLpos:-1} androidx.recyclerview.widget.RecyclerView{3373ab8 VFED..... ......ID 0,4-1440,934 #7f090919 app:id/track_list}, adapter:net.osmand.plus.track.GpxTrackAdapter@4b84091, layout:androidx.recyclerview.widget.LinearLayoutManager@745dbf6, context:androidx.appcompat.view.ContextThemeWrapper@807cbf7
	at androidx.recyclerview.widget.RecyclerView$5.attachViewToParent(RecyclerView.java:920)
	at androidx.recyclerview.widget.ChildHelper.attachViewToParent(ChildHelper.java:239)
	at androidx.recyclerview.widget.RecyclerView.addAnimatingView(RecyclerView.java:1436)
	at androidx.recyclerview.widget.RecyclerView.animateChange(RecyclerView.java:4391)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:4194)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3862)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
	at android.view.View.layout(View.java:22466)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22466)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22466)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22466)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22466)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22466)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22466)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22466)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
	at android.view.View.layout(View.java:22466)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22466)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22466)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22466)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22466)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:779)
	at android.view.View.layout(View.java:22466)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3157)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2614)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1745)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7768)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
	at android.view.Choreographer.doCallbacks(Choreographer.java:791)
	at android.view.Choreographer.doFrame(Choreographer.java:726)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14261mqta, Released: 2023-03-23
Behavior could not be reproduced
We will be watching
