### ISSUE TITLE
Osmand crash when entering in menu download maps - other maps

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#16797]
application crash when entering in menu download maps - other maps or travel guides or nautical maps

```
Version  OsmAnd~ 4.5.0#14269mqta
25.03.2023 12:12:45
Apk Version : 4.5.0#14269mqta 4500
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'net.osmand.map.WorldRegion net.osmand.map.WorldRegion.getSuperregion()' on a null object reference
	at net.osmand.plus.download.ui.DownloadResourceGroupFragment.shouldDisplayFreeMapsMessage(DownloadResourceGroupFragment.java:267)
	at net.osmand.plus.download.ui.DownloadResourceGroupFragment.updateFreeMapsView(DownloadResourceGroupFragment.java:251)
	at net.osmand.plus.download.ui.DownloadResourceGroupFragment.reloadData(DownloadResourceGroupFragment.java:461)
	at net.osmand.plus.download.ui.DownloadResourceGroupFragment.onResume(DownloadResourceGroupFragment.java:420)
	at androidx.fragment.app.Fragment.performResume(Fragment.java:2649)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:922)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
	at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8105)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

```

**Comment by Chumva** [comment]
This should be fixed [here](https://github.com/osmandapp/OsmAnd/commit/306cacef0fb30ce83743a826839045aa05e97e13)
