### ISSUE TITLE
using in app editor crash OsmAnd

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/OsmAnd#16801]
In the latest version from Playstore, OsmAnd is crashing allways if I will edit a POI.
Happens in OsmAnd+ and also in the clean installed OsmAnd free version from PlayStore.

Here my crash report:
```
Version  OsmAnd+ 4.4.4
25.03.2023 11:15:20
Apk Version : 4.4.4 4404
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'net.osmand.osm.MapPoiTypes net.osmand.plus.OsmandApplication.getPoiTypes()' on a null object reference
	at net.osmand.plus.plugins.osmedit.data.EditPoiData.<init>(EditPoiData.java:39)
	at net.osmand.plus.plugins.osmedit.dialogs.EditPoiDialogFragment.onAttach(EditPoiDialogFragment.java:150)
	at androidx.fragment.app.Fragment.performAttach(Fragment.java:2574)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:828)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
	at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:7604)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
``` 
Report from OsmAnd free is the same.

My phone is the Moto G7 with Android 10

**Comment by Nine-Tailed** [comment]
Duplicate https://github.com/osmandapp/OsmAnd/issues/16772

**Comment by Zirochkabila** [comment]
@hakuchi Duplicate
Try to update https://osmand.net/docs/versions/nightly_versions

**Comment by hakuchi** [comment]
@Zirochkabila if this is fixed in the nightly version, also the PlayStore app should be updatet!

**Comment by Zirochkabila** [comment]
@hakuchi The update is planned in the near future
