### ISSUE TITLE
Crash in net.osmand.core.jni.WeatherTileResourcesManager.calculateDbCacheSize 

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#16862]
This crash occurred after upgrading from 4.4.5 to 4.4.6 and starting OsmAnd after the first time:

```
Version  OsmAnd+ 4.4.6
01.04.2023 9:44:36
Apk Version : 4.4.6 4406
Exception occured in thread Thread[AsyncTask #7,5,main] : 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.math.BigInteger net.osmand.core.jni.WeatherTileResourcesManager.calculateDbCacheSize(net.osmand.core.jni.TileIdList, net.osmand.core.jni.TileIdList, net.osmand.core.jni.ZoomLevel)' on a null object reference
	at net.osmand.plus.plugins.weather.OfflineForecastHelper.lambda$calculateCacheSize$2$net-osmand-plus-plugins-weather-OfflineForecastHelper(OfflineForecastHelper.java:301)
	at net.osmand.plus.plugins.weather.OfflineForecastHelper$$ExternalSyntheticLambda7.run(Unknown Source:8)
	at net.osmand.plus.plugins.weather.OfflineForecastHelper$3.doInBackground(OfflineForecastHelper.java:988)
	at net.osmand.plus.plugins.weather.OfflineForecastHelper$3.doInBackground(OfflineForecastHelper.java:985)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

```

No idea how to reproduce.

**Comment by nazar-kutz** [comment]
**Quick Fix**
* https://github.com/osmandapp/OsmAnd/pull/16890
