### ISSUE TITLE
My Places - Favorites  support Multiselection and all actions

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#16917]
<details>
    <summary>Related issue</summary>

**Move** 
* https://github.com/osmandapp/OsmAnd/issues/16828 
* https://github.com/osmandapp/OsmAnd/issues/15405
* https://github.com/osmandapp/OsmAnd/issues/20813

**Search** 
* https://github.com/osmandapp/OsmAnd/issues/16320
* https://github.com/osmandapp/OsmAnd/issues/8461

**Subgroups** 
* https://github.com/osmandapp/OsmAnd/issues/9967

**Delete all** 
* https://github.com/osmandapp/OsmAnd/issues/8377

**Sort** 
* https://github.com/osmandapp/OsmAnd/issues/6059
* https://github.com/osmandapp/OsmAnd/issues/2801

**Other**
* https://github.com/osmandapp/OsmAnd/issues/19018
* Home / Work https://github.com/osmandapp/OsmAnd/issues/8611
* https://github.com/osmandapp/OsmAnd/issues/15807

**Should be closed after redesign***
* https://github.com/osmandapp/OsmAnd/issues/7672

**Navigation**
* https://github.com/osmandapp/OsmAnd/issues/5468

</details>  

# Favorite, main folder
<table style="width:100%">
  <tr>
    <th>Main screen</th>
    <th>Sort menu</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/74db58d3-d132-403c-bc50-612f8df5034e"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/8e5a8ae9-346d-4308-9fac-e6ce57179f7b"  width="150" height="auto"/> </td>
  </tr>
</table>   

- [ ] Show list of folders
- [ ] Tap on the folder, should open new screen with the list of favorite points
- [ ] Display Folder menu after tap on menu icon

### Sorting menu
The Main Favorites folder can consist only of folders, so it has a reduced list of sorting options:

- [ ] **Last modified**
- [ ] **Name A – Z**
- [ ] **Name Z – A**
- [ ] **Newest date first**
- [ ] **Oldest date first** 
- [ ] By default by **Name A - Z**

# Folders
<table style="width:100%">
  <tr>
    <th>Visible</th>
    <th>Visible and shared</th>
    <th>Hidden</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/f48f676d-0ccc-43b0-a9f1-7a2b5d9097fb"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/1cedab13-13b0-46b5-9d28-6047fdf30b6b"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/930555b9-1630-49cf-978f-b70879bb8359"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] First line: display the folder name.
- - [ ] Use _italic_ text style for hidden folders.
- - [ ] Max two lines
- [ ] Second line: dsplay the date and points quantity, separated by a comma, in the format: `23 Apr, 13 points`.
- - [ ] Add `Hidden` for hidden folders
- [ ] Default icon – `ic_action_folder`.
- - [ ] Color works as currently implemented.
- - [ ] Use – `ic_action_folder_hidden` for hidden folders.
- [ ] Show menu button on the right side
- - [ ] Icon – `ic_overflow_menu_white`
- - [ ] Open Folder menu on the tap

### Folder menu
<table style="width:100%">
  <tr>
    <th>Folder menu</th>
    <th>Confirmation alert</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/1da67497-dfe2-4722-beb8-4868802e1aae"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/f8b4b582-096d-4429-bcd7-505f4c7e07fb"  width="150" height="auto"/> </td>
  </tr>
</table>   

- [ ] Header: show the same information as on folder item (name, date, icon...)
- [ ] Add new option **Add to a track**, should allow to add favorites folder to the track
- - [ ] Icon – `ic_action_track_add` 
- - [ ] show **Open track**  screen on tap
- [ ] Change items order:
- - [ ] Show on map
- - [ ] Rename, Appearance
- - [ ] Share, Move
- - [ ] Add to map markers, Add to a track, Add to Navigation
- - [ ] Delet folder

## Empty states
<table style="width:100%">
  <tr>
    <th>Main folder</th>
    <th>Open folder</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/4328d2f7-856c-4d1f-a35d-39f0cbc09463"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/5b6420fd-cf03-458f-94d5-eed0746a9808"  width="150" height="auto"/> </td>
  </tr>
</table>   

### Main folder
Use the same title and description as now
- [ ] Title – `empty_state_favourites`
- [ ] Description – `empty_state_favourites_desc`
- [ ] Button – **Import**, open system file picker

### Open folder
- [ ] Title –  `Empty folder`
- [ ] Description – `This fodler doesn’t have any points yet.`
- [ ] Button – **Import**, open system file picker

# Search
<table style="width:100%">
  <tr>
    <th>Search</th>
    <th>Search phrase</th>
    <th>Empty state</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/f3beb741-e9b7-4a33-bf3a-19a6e3feca93"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/dc072269-28ab-4d06-914a-4576a12e5b27"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/722cf2b1-7eaa-46ad-8c98-7d501193c5ae"  width="150" height="auto"/> </td>
  </tr>
</table>  

- [ ] Show list of favorites points

**Empty state:**
- [ ] Title – `No results`
- [ ] Description – `Adjust your search or filters to see if that helps`
- [ ] Action – `Clear all`, clear search phrase and filters.

# Favorite point item

<table style="width:100%">
  <tr>
    <th>Default</th>
    <th>Sort by date</th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/e5f07fbc-0e74-4f4f-a6ba-a1d6a31e6657"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/54c6e815-d6c9-48e2-9f3e-81ce6754fbed"  width="300" height="auto"/> </td>
    <td><img src=""  width="300" height="auto"/> </td>
  </tr>
</table>  

- [ ] Icon - without changes, same size.
- [ ] First line: show favorite name, max 2 lines

**Second line**
Order depend on applied sorting

- [ ] Default:
- - [ ] ↖︎ Distance • Address | Date. Example `↖︎ 1,56 km • Berlin, Street name |  14.03.2025`
- [ ] Sorting by date:
- - [ ] Date | ↖︎ Distance • Address. Example `14.03.2025  | ↖︎ 1,56 km • Berlin, Street name`
- [ ] Second line should take only one line.

**Iteraction**
- [ ] Tap open items opens favorite context menu
- [ ] Tap on menu button > shows action menu for the point

## Action menu, [Figma](https://www.figma.com/design/e2RHNzqCgUhcfAaQafHmQ8/My-places?node-id=4515-37262&m=dev)

<details>
    <summary>Screenshot</summary>

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/13d29d1a-1df7-459d-8628-8b34a81214d6"  width="150" height="auto"/> </td>
  </tr>
</table>   

</details>  

- [ ] **Edit**
- - [ ] Icon - `ic_action_edit_dark`
- [ ] **Move**
- - [ ] Icon - `ic_action_folder_move_outlined`
- [ ] **Share**
- - [ ] Icon - `ic_action_gshare_dark`
- [ ] **Add to map markers**
- - [ ] Icon - `ic_action_add_to_markers`
- [ ] **Add to track**
- - [ ] Icon - `ic_action_track_add`
- [ ] **Add to Navigation**
- - [ ] Icon - `ic_action_navigation_outlined`
- [ ] **Delete**
- - [ ] Icon - `ic_action_delete_outlined`

# Selection mode. [Figma](https://www.figma.com/design/e2RHNzqCgUhcfAaQafHmQ8/My-places?node-id=4424-161813&m=dev)
<table style="width:100%">
  <tr>
    <th>Selection mode</th>
    <th>Actions menu</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/ced4c41e-8615-4b82-b6ae-7069e13e7ee2"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/d0b9b8ff-0fdd-443f-bc32-fa169d943fee"  width="150" height="auto"/> </td>
  </tr>
</table>   

- [ ] Show after
- - [ ] Long tap on **Folder** or **Favorite point**
- - [ ] Tapping **Select** in **AppBar** context menu
- [ ] Show content (points and folders) from the opened folder.

### Actions menu

<details>
    <summary>Icons and actions</summary>

- [ ] **Change appearance**
- - [ ] Icon - `ic_action_appearance_outlined`
- [ ] **Move**
- - [ ] Icon - `ic_action_folder_move_outlined`
- [ ] **Share**
- - [ ] Icon - `ic_action_gshare_dark`
- [ ] **Add to map markers**
- - [ ] Icon - `ic_action_add_to_markers`
- [ ] **Add to track**
- - [ ] Icon - `ic_action_track_add`
- [ ] **Add to Navigation**
- - [ ] Icon - `ic_action_navigation_outlined`
- [ ] **Delete**
- - [ ] Icon - `ic_action_delete_outlined`

</details>

**Comment by readonly24** [comment]
Hi.

I want to import hunderts of well grouped POI from Locus Maps into OsmAnd. Please let me decide in which folder I can import my POI/favourites. Thanks.

**Comment by vshcherb** [comment]
> Hi.
> 
> I want to import hunderts of well grouped POI from Locus Maps into OsmAnd. Please let me decide in which folder I can import my POI/favourites. Thanks.

You can create favorites.gpx where all points are grouped by categories (tag ```category``` inside gpx)

**Comment by dpuschek** [comment]
> You can create favorites.gpx where all points are grouped by categories (tag `category` inside gpx)

I'm using android and I tried to modify it that way. But, how can I remove all old favorites from osmand before importing the new favorites.gpx? If I import the modified favorites.gpx the old are not overwritten. So I got many duplicated POIs with little changes. In My places -> Favorites I can only click the delete icon (recycle bin icon). Then I cannot select all groups at once. I have more than 100 groups there! It is impossible to select one by one every time I like to import a modified favorites.gpx :(

**Comment by scaidermern** [comment]
> Hi.
> 
> I want to import hunderts of well grouped POI from Locus Maps into OsmAnd. Please let me decide in which folder I can import my POI/favourites. Thanks.

Try to manage them using a track instead oft favorites. Simply keep your POIs as waypoints in this track. They will work almost similar to favorites and sharing them becomes even more easy.

**Comment by dmpr0** [comment]
## Pin Folder

<table style="width:100%">
  <tr>
    <th>Favorites</th>
    <th>Folder menu</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/731a9665-02c8-4a6c-b1c3-ef340fdf16bc"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/025fd833-249d-4265-b5f9-7eaa1b28fc43"  width="200" height="auto"/> </td>
  </tr>
</table>   

The **Android** team needs to add support for pinned folders, mirroring functionality already implemented by the **Web** team: https://github.com/osmandapp/web/issues/1193

### Folder Appearance and Behavior
- [ ] Use `ic_action_folder_pin` for pinned folders.
- [x] Display a full-width divider below pinned folders to separate them from the rest of the list.
- [x] The **Personal** and **Favorites** folders should be pinned by default.

### Folder Menu
- [x] Add the **Pin Folder** action using the icon `ic_action_drawing_pin`.
- [x] Add the **Unpin Folder** action for currently pinned folders using the icon `ic_action_drawing_pin_disable`.
- [x] Move pinned folders to the top

### Sorting
- [x] Apply selected sorting for each section separately.

### Backend:
- [x] Read and store the pin state in `<extensions>`.

```
<extensions>
    <osmand:points_groups>
        <group name="personal" icon="special_building" background="circle" pinned="true"/>
    </osmand:points_groups>
</extensions>
```

**Comment by Zirochkabila** [comment]
# Testing 1

> OsmAnd~ 5.3.0#7152m (Released: 2026-02-12)

### **Severity**: 🔴 Critical / **Priority**: 🔴 High

* [x] 1. Go to the folder → Three dots → **Delete** = **Crash**. Perhaps it would be better to remove the Delete button altogether until a specific item is selected.

[exception (1) (4).log](https://github.com/user-attachments/files/25265906/exception.1.4.log)

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/78f0ed96-7e00-4f2a-b8e5-a200ddb0bf09"></video>
</details>


### **Severity**: 🟠 Major / **Priority**: 🟠 Normal

* [x] 1. Not all folders can be selected
* [x] 2. Folders remain with the checkbox displayed for selection even after the selection is complete

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/996fb258-2d2a-4b04-8a47-7cd644b93eb1"></video>
</details>

* [ ] 3. Opening the context menu of a point in the search results is accompanied by **keyboard flickering**
* [ ] 4. The context menu is not displayed completely

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/778247dd-da94-46c8-861f-3adef0ff7713"></video>
</details>

* [x] 5. The system back button does not work for the edit menu

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/4a6a0964-d033-4001-994f-251ea3103975"></video>
</details>

* [ ] 6. Search results take a long time to show results

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/d2ea64a0-2147-4814-a9cf-25b3c2c5b705"></video>
</details>

* [x] 7. When adding as a **Map marker**, the map is expected to open with the marker set at the point

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/5e070291-e6fc-43fa-922b-334463c16475"></video>
</details>

* [ ] 8. Hidden folder reappears after reopening OsmAnd

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/8107c154-a55a-4175-9160-529903fbb513"></video>
</details>


### **Severity**: 🟡 Minor / **Priority**: 🟠 Normal

* [x] 1. The date format for the folder differs from the format used in Tracks

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <th><img src="https://github.com/user-attachments/assets/ebc30aea-381e-4ce1-a007-b98dfba4759c" width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/6c953de9-a1ca-4f17-8587-ca42af16ac84" width="300" height="auto"/></th>
  </tr>
</table>
</details>

* [x] 2. The action menu is displayed across almost the entire width of the screen — perhaps it could be adapted to the point name (or a fixed size)

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/073b466f-c72d-4374-bc1a-e4eb451b743c"></video>
</details>

* [x] 3. Different sizes of the Action menu depending on where the point (location) is opened

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/fd0e82f3-a56f-4348-a189-99017d701a5e"></video>
</details>


### **Severity**: 🔵 Trivial / **Priority**: 🔵 Low

* [x] 1. The names **Share location** and **POI name** are used — **Share favorite** expected

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/04290277-9e35-46d1-959a-75fecd08b0a4"></video>
</details>

**Comment by dmpr0** [comment]
## UI Review

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/67447aeb-cc62-4483-a726-2e5b7be523d9"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [x] Hide tabs in Selection mode

- - - - - -
 
<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/a1141cfa-59b9-4ba7-8fe4-55fa6feda74f"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [x] Trim point name in context menu to 24 symbols. Why it so wide?
- - [ ] Use Medium font style if possible for the name

- - - - - -

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/cc70b1d0-9fde-47c0-8d71-8a8dd2e9ffa9"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  
 

- [x] Divider Top/Bottom padding - 8dp
- [x] Apply new item specs for paddings

- - - - - -
 
- [x] Use `ic_action_folder_move_outlined` for Move action

- - - - - -

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Favorites</th>
        <th>Tracks</th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/4bfa0224-6cd2-4563-bb7d-56d445870725"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/c4eb966f-f416-4020-9c45-f9263948b1c2"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [x] Use System date format for the Date of creation that is shown on the second line; it works for tracks that way.

- - - - - -

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/bd2f1b52-2323-4ad6-852e-a72d8e65e974"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  
 
- [x] Decrease padding between icon and point name for 6 dp

- - - - - -
 
<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/0b16712a-8ac1-4d45-b2b5-16a5daf08707"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/15e9867e-ec99-4be6-8123-6238a49910f5"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   


- [x] The direction arrow doesn’t align vertically. Do we use a different component for this arrow and direction component?


### Search screen


<table style="width:100%">
  <tr>
    <th>Sort by name</th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/e54aac71-d0a6-4751-ac15-0c6082c067b1"  width="200" height="auto"/> </td>
    <td><img src=""  width="300" height="auto"/> </td>
  </tr>
</table>   


**Sort by name / Nearest first**
- [x] Remove date
- [x] Show **Folder** name
- - [x] Max 12 characters
- - [x] Prioritise folder name over address

### Refactor Share Sheet UX

Proposition to separate File sharing and Points list sharing. Currently, sending both the file (e.g., .gpx) and the long text list in a single intent causes unpredictable behavior in receiving apps (messengers often drop the file or split the message awkwardly).
Since Android 14 (API 34+), we can add custom actions directly to the native system Share Sheet. 


**For Android 14+ (API 34+):**

- [x] Default Share action must send only the file.
- [x] Add custom action "Copy list" to the system Share Sheet.
- - [x] "Copy list" copies text to the clipboard (rely on native system UI for the copied popup, no custom toasts).
- - [x] Use icon `ic_action_copy`

**For Android 13 and below:**
No changes. Keep legacy behavior (send file + text together).

**Comment by Zirochkabila** [comment]
# Testing 2

> OsmAnd~ 5.3.0#7281m, Released: 2026-03-02

### **Severity**: 🔴 Critical / **Priority**: 🔴 High

* [x] 1. Crash when adding a new folder [exception (1) (6).log.zip](https://github.com/user-attachments/files/25689011/exception.1.6.log.zip)

  <details><summary>Details</summary>
  <video src="https://github.com/user-attachments/assets/c761d457-b1a6-4dd1-9af5-8fa8b6f10dda"></video>
  </details>

**Comment by Zirochkabila** [comment]
> OsmAnd~ 5.3.0#7289m, Released: 2026-03-03

Crash - **Fixed**

**Comment by dmpr0** [comment]
## UI Review

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><video src="https://github.com/user-attachments/assets/156d0a17-9c77-4b5d-9a78-b771ce810fea"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [x] Crash on Search screen

<details>
    <summary>Log</summary>

```
Version  OsmAnd~ 5.3.0#7292m
04.03.2026 10:50:31
Apk Version : 5.3.0#7292m 5399
Exception occurred in thread Thread[main,5,main] : 
java.lang.IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.
 ViewHolder 1:FavoriteViewHolder{15d5465 position=10 id=-1181260089, oldPos=-1, pLpos:-1} 
 View Holder 2:FavoriteViewHolder{97448e0 position=17 id=-1181260089, oldPos=-1, pLpos:-1} androidx.recyclerview.widget.RecyclerView{2b289f6 VFED.V... ......ID 0,279-1080,2397 #7f090824 app:id/recycler_view aid=1073742026}, adapter:net.osmand.plus.myplaces.favorites.dialogs.FavoriteFoldersAdapter@651e1f7, layout:androidx.recyclerview.widget.LinearLayoutManager@fc0a864, context:androidx.appcompat.view.ContextThemeWrapper@4e80648
	at androidx.recyclerview.widget.RecyclerView.handleMissingPreInfoForChangeError(RecyclerView.java:4442)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:4366)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4031)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
	at android.view.View.layout(View.java:25981)
	at android.view.ViewGroup.layout(ViewGroup.java:6468)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:25981)
	at android.view.ViewGroup.layout(ViewGroup.java:6468)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25981)
	at android.view.ViewGroup.layout(ViewGroup.java:6468)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:25981)
	at android.view.ViewGroup.layout(ViewGroup.java:6468)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:778)
	at android.view.View.layout(View.java:25981)
	at android.view.ViewGroup.layout(ViewGroup.java:6468)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:5341)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4438)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3257)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11177)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1666)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1675)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1271)
	at android.view.Choreographer.doFrame(Choreographer.java:1200)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1649)
	at android.os.Handler.handleCallback(Handler.java:1095)
	at android.os.Handler.dispatchMessageImpl(Handler.java:135)
	at android.os.Handler.dispatchMessage(Handler.java:125)
	at android.os.Looper.loopOnce(Looper.java:297)
	at android.os.Looper.loop(Looper.java:400)
	at android.app.ActivityThread.main(ActivityThread.java:9449)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:566)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:931)


```
</details>  



- - - - - - 

- [x] Folder name on the second line should be visible only on Search screen

- - - - - -

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/c887c084-cbab-440a-8317-f02c0b11c361"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [x] Folder name should go right after Address if it present

Probably solution:

<details>
    <summary>Screenshot</summary>

```
<androidx.constraintlayout.widget.ConstraintLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <TextView
        android:id="@+id/tvAddress"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Belgrade"
        android:ellipsize="end"
        android:maxLines="1"
        app:layout_constrainedWidth="true" 
        app:layout_constraintHorizontal_bias="0.0"
        app:layout_constraintHorizontal_chainStyle="packed"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintEnd_toStartOf="@+id/tvFolder" />

    <TextView
        android:id="@+id/tvFolder"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text=" | Capitals"
        android:maxLines="1"
        app:layout_constraintStart_toEndOf="@id/tvAddress"
        app:layout_constraintEnd_toEndOf="parent" />

</androidx.constraintlayout.widget.ConstraintLayout>
```

</details>

**Comment by Zirochkabila** [comment]
# Testing 3

> OsmAnd~ 5.4.0#7533m, released: 2026-04-08

### **Severity**: 🟡 Minor / **Priority**: 🔵 Low

* [ ] 1. The keyboard reopens when opening Point Options

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/e4fdda36-a9c9-4334-ae45-7e1ada0d556a"></video>
</details>

* [ ] 2. Folder names are not displayed in full in search mode even though there is enough free space

<details><summary>Details</summary>
<img width="400" alt="Folder names are not displayed in full in search mode" src="https://github.com/user-attachments/assets/81e7cfba-79fa-4964-89d3-bdc022f1cda8">
</details>

**Comment by dmpr0** [comment]
## UI Review

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/caca809c-92d6-44ab-8588-59d8145c6e84"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [x] Use pined folder icon for Personal folder if it pinned?

- - - - - -
 
<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Favorites</th>
        <th>Tracks</th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/ace8bbe9-44c3-4902-a69c-1b5a37a9a914"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/6dd21da6-18e4-45b8-b3a3-7adc0a00fcb7"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details> 

- [x] Use Rename dialog similar to Tracks with "new" Text Field

**Comment by Zirochkabila** [comment]
# Testing 4

> OsmAnd~ 5.4.0#7547m, released: 2026-04-10

The use of the pinned folder icon for the personal folder when pinning it, and the rename dialog with the “new” text field (similar to Tracks), has been tested  - **Fixed**

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/15217030-f4c5-4de5-aebd-40efe480a34b"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/947b3a4c-acbb-4266-9da5-a35c70fc2ca4"  width="300" height="auto"/> </th>
  </tr>
</table>  
</details>
