### ISSUE TITLE
crashes when clearing waypoints

### ISSUE THREAD

**Issue by RicoZ-OSM** [osmandapp/Osmand#1694]
happens both with the nightlies as well as current f-droid version.

How to trigger:
1 select destination, wait for route to appear, add a waypoint
2 finish navigation
3 clear destination point (which should supposedly clear all intermediate waypoints) but the waypoints are still displayed
4 tap waypoint and (try to) remove it

Apparently in step 3  the waypoints are cleared from one array but left displayed?

An easier (more intuitive way) to clear all waypoints would be nice to have anyway. For example when hitting the "x" to finish navigation it could ask me whether I want to have all points cleared.

Version  OsmAnd~ 2.1.1
09.09.2015 1:34:00
Apk Version : 2.1.1 212
Exception occured in thread Thread[main,5,main] :
java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
        at java.util.ArrayList.remove(ArrayList.java:403)
        at net.osmand.plus.OsmandSettings.deleteIntermediatePoint(OsmandSettings.java:1487)
        at net.osmand.plus.TargetPointsHelper.removeWayPoint(TargetPointsHelper.java:189)
        at net.osmand.plus.views.PointNavigationLayer$1.onContextMenuClick(PointNavigationLayer.java:231)
        at net.osmand.plus.activities.MapActivityActions$6.onClick(MapActivityActions.java:301)
        at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1017)
        at android.widget.AdapterView.performItemClick(AdapterView.java:300)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1143)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3044)
        at android.widget.AbsListView.onTouchUp(AbsListView.java:3845)
        at android.widget.AbsListView.onTouchEvent(AbsListView.java:3617)
        at android.view.View.dispatchTouchEvent(View.java:8393)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2426)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2158)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)

**Comment by vshcherb** [comment]
Crash has fixed
