### ISSUE TITLE
Crash when trying to connect segments of a track

### ISSUE THREAD

**Issue by lintux** [osmandapp/OsmAnd#16983]
I see the following behavior with the latest Osmand Version on Android:

- Download the Track related to [this Hiking Trail](https://hiking.waymarkedtrails.org/?lang=de#route?id=13187847&type=relation&map=14.0/51.1681/6.2797) 
- Open the Track with Osmand
- Select the Track, then tap on "Segmente vebinden/Connect segments" --> Crash
- Trying instead to execute the Function "auf der Karte auswerten/evaluate on map" all Menus disappear.

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/11172254/232529079-7f2d8178-c01f-4f61-a51c-8ae0cd65b78b.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

`Version  OsmAnd+ 4.3.2
13.12.2022 10:44:15
Apk Version : 4.3.2 4302
Exception occured in thread Thread[main,5,main] : 
android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service net.osmand.plus/.download.DownloadService
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
	at android.os.Parcel.readParcelable(Parcel.java:3334)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2421)
	at android.os.Parcel.createException(Parcel.java:2410)
	at android.os.Parcel.readException(Parcel.java:2393)
	at android.os.Parcel.readException(Parcel.java:2335)
	at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:6320)
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1855)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1831)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:781)
	at net.osmand.plus.OsmandApplication.startDownloadService(OsmandApplication.java:949)
	at net.osmand.plus.download.DownloadIndexesThread.downloadHasStarted(DownloadIndexesThread.java:101)
	at net.osmand.plus.download.DownloadIndexesThread$DownloadIndexesAsyncTask.onPreExecute(DownloadIndexesThread.java:455)
	at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:724)
	at net.osmand.plus.download.DownloadIndexesThread.execute(DownloadIndexesThread.java:330)
	at net.osmand.plus.download.DownloadIndexesThread.runDownloadFiles(DownloadIndexesThread.java:237)
	at net.osmand.plus.liveupdates.PerformLiveUpdateAsyncTask.onPostExecute(PerformLiveUpdateAsyncTask.java:139)
	at net.osmand.plus.liveupdates.PerformLiveUpdateAsyncTask.onPostExecute(PerformLiveUpdateAsyncTask.java:39)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.access$900(AsyncTask.java:199)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:329)
	at android.app.ActivityThread.main(ActivityThread.java:8063)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActiveServices.startServiceLocked(ActiveServices.java:694)
	at com.android.server.am.ActiveServices.startServiceLocked(ActiveServices.java:619)
	at com.android.server.am.ActivityManagerService.startService(ActivityManagerService.java:12195)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2703)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2595)

Version  OsmAnd+ 4.4.7
14.04.2023 11:05:10
Apk Version : 4.4.7 4407
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.appcompat.widget.SwitchCompat.setChecked(boolean)' on a null object reference
	at net.osmand.plus.myplaces.ui.GPXItemPagerAdapter.updateJoinGapsInfo(GPXItemPagerAdapter.java:721)
	at net.osmand.plus.myplaces.ui.GPXItemPagerAdapter.access$200(GPXItemPagerAdapter.java:77)
	at net.osmand.plus.myplaces.ui.GPXItemPagerAdapter$3.onClick(GPXItemPagerAdapter.java:450)
	at android.view.View.performClick(View.java:7467)
	at android.view.View.performClickInternal(View.java:7444)
	at android.view.View.access$3700(View.java:840)
	at android.view.View$PerformClick.run(View.java:28830)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:329)
	at android.app.ActivityThread.main(ActivityThread.java:8063)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
Version  OsmAnd+ 4.4.7
14.04.2023 11:23:20
Apk Version : 4.4.7 4407
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.appcompat.widget.SwitchCompat.setChecked(boolean)' on a null object reference
	at net.osmand.plus.myplaces.ui.GPXItemPagerAdapter.updateJoinGapsInfo(GPXItemPagerAdapter.java:721)
	at net.osmand.plus.myplaces.ui.GPXItemPagerAdapter.access$200(GPXItemPagerAdapter.java:77)
	at net.osmand.plus.myplaces.ui.GPXItemPagerAdapter$3.onClick(GPXItemPagerAdapter.java:450)
	at android.view.View.performClick(View.java:7467)
	at android.view.View.performClickInternal(View.java:7444)
	at android.view.View.access$3700(View.java:840)
	at android.view.View$PerformClick.run(View.java:28830)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:329)
	at android.app.ActivityThread.main(ActivityThread.java:8063)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
Version  OsmAnd+ 4.4.7
14.04.2023 12:33:16
Apk Version : 4.4.7 4407
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.appcompat.widget.SwitchCompat.setChecked(boolean)' on a null object reference
	at net.osmand.plus.myplaces.ui.GPXItemPagerAdapter.updateJoinGapsInfo(GPXItemPagerAdapter.java:721)
	at net.osmand.plus.myplaces.ui.GPXItemPagerAdapter.access$200(GPXItemPagerAdapter.java:77)
	at net.osmand.plus.myplaces.ui.GPXItemPagerAdapter$3.onClick(GPXItemPagerAdapter.java:450)
	at android.view.View.performClick(View.java:7467)
	at android.view.View.performClickInternal(View.java:7444)
	at android.view.View.access$3700(View.java:840)
	at android.view.View$PerformClick.run(View.java:28830)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:329)
	at android.app.ActivityThread.main(ActivityThread.java:8063)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
Version  OsmAnd+ 4.4.7
17.04.2023 5:05:12
Apk Version : 4.4.7 4407
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.appcompat.widget.SwitchCompat.setChecked(boolean)' on a null object reference
	at net.osmand.plus.myplaces.ui.GPXItemPagerAdapter.updateJoinGapsInfo(GPXItemPagerAdapter.java:721)
	at net.osmand.plus.myplaces.ui.GPXItemPagerAdapter.access$200(GPXItemPagerAdapter.java:77)
	at net.osmand.plus.myplaces.ui.GPXItemPagerAdapter$3.onClick(GPXItemPagerAdapter.java:450)
	at android.view.View.performClick(View.java:7467)
	at android.view.View.performClickInternal(View.java:7444)
	at android.view.View.access$3700(View.java:840)
	at android.view.View$PerformClick.run(View.java:28830)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:329)
	at android.app.ActivityThread.main(ActivityThread.java:8063)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
`

**Comment by Zirochkabila** [comment]
@lintux Your result cannot be reproduced because the "Segmente vebinden/Connect segments" button is missing

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/232560072-b4ca01f0-ae5c-409c-b9de-818685bcfeaf.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by martinstingl** [comment]
I can see the "Join Segments" button and also reproduce the crash.
![Screenshot_20230419-110340_OsmAnd~](https://user-images.githubusercontent.com/1312947/233026209-84b9173d-461a-4fe8-98aa-ec6621b55fdd.png)

**Comment by Zirochkabila** [comment]
@lintux Please attach a video with playback steps - it looks like we have different tracks


https://user-images.githubusercontent.com/104760013/234606480-72fb4ab7-f942-4442-8ebf-8aae7db20396.mp4

**Comment by Zirochkabila** [comment]
@lintux A check was added to prevent the process from crashing.
Please check the latest nightly version https://osmand.net/docs/versions/nightly_versions

**Comment by Zirochkabila** [comment]
There is no response from the user, so we can assume that the issue is resolved. Can't check on my device

**Comment by lintux** [comment]
Sorry - just discovered all Github mails ended up in the spam folder. I guess the Nightly Versions can not be installed in parallel to the "normal" Osmand installation?

**Comment by vshcherb** [comment]
There is 4.5.1 beta out this week please try it
