### ISSUE TITLE
Crash, NullPointerException at Location.distanceTo

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#17033]
Crash while starting navigation right after startup.

```
Version  OsmAnd+ 4.4.7
Apk Version : 4.4.7 4407
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to read from field 'double net.osmand.Location.mLatitude' on a null object reference
	at net.osmand.Location.distanceTo(Location.java:260)
	at net.osmand.plus.views.layers.RouteLayer.addPreviousToActionPoints(RouteLayer.java:689)
	at net.osmand.plus.views.layers.RouteLayer.calculateActionPoints(RouteLayer.java:665)
	at net.osmand.plus.views.layers.RouteLayer.calculateActionPoints(RouteLayer.java:599)
	at net.osmand.plus.views.layers.RouteLayer.drawLocations(RouteLayer.java:531)
	at net.osmand.plus.views.layers.RouteLayer.drawLocations(RouteLayer.java:218)
	at net.osmand.plus.views.layers.RouteLayer.lambda$onUpdateFrame$1$net-osmand-plus-views-layers-RouteLayer(RouteLayer.java:168)
	at net.osmand.plus.views.layers.RouteLayer$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

**Comment by vshcherb** [comment]
Only 4.4.7 - fix is in place and we are waiting for release 4.4.8 or 4.5
