### ISSUE TITLE
Crash when trying to download online map

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#17079]
### To Do

- [ ] Displaying the map loading window

### Description
When opening the online map download window, OsmAnd crashes
[exception (51).log](https://github.com/osmandapp/OsmAnd/files/11355706/exception.51.log)

### Steps to reproduce

- **Configure screen** > **Overlay** > **Select any map**
- **Long tap on the map** > **Actions** > **Download map**

### Actual result
Crash

### Expected result
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/235207939-5c088c28-280f-4f66-b4bc-5f3f6a561a1d.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#35861m, Released: 2023-04-28
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by sonora** [comment]
From the log @Zirochkabila attaches, the "noSuchMethodError" seems to be the issue here:
```
Version  OsmAnd~ 4.5.0#35861m
28.04.2023 7:49:43
Apk Version : 4.5.0#35861m 4500
Exception occured in thread Thread[main,5,main] : 
java.lang.NoSuchMethodError: No virtual method getSerializable(Ljava/lang/String;Ljava/lang/Class;)Ljava/io/Serializable; in class Landroid/os/Bundle; or its super classes (declaration of 'android.os.Bundle' appears in /system/framework/framework.jar!classes2.dex)
	at net.osmand.plus.plugins.rastermaps.DownloadTilesFragment.onCreate(DownloadTilesFragment.java:117)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2586)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:838)
	at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1197)
	at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1080)
	at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:119)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1866)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
	at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8319)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
```
