### ISSUE TITLE
Cannot attach track to road when using a user profile

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#17083]
### Description
When attaching track to road and using a user profile (threshold distance 25, 30, 60) - the track cannot be attached.
When using a standard profile and meeting the same conditions - track is attached to the road
`52.25405° N, 6.19416° E` place on the video
[User's profile & GPX.zip](https://github.com/osmandapp/OsmAnd/files/11358736/User.s.profile.GPX.zip)

### Steps to reproduce

- Select track
- Navigation
- Set start (at the track starting)
- Attach to the roads
- Bicycle profile
- Chose threshold distance 25 and 30
- Compare default and user's profile result

### Expected and Actual results

https://user-images.githubusercontent.com/104760013/235294218-91aa9ea8-68ce-412a-a1bb-c3881c0c9b41.mp4

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#35864m, Released: 2023-04-29
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by Zirochkabila** [comment]
When using a standard profile, a straight line is formed at a threshold distance of 0, 5, 10 and 30 m


https://github.com/osmandapp/OsmAnd/assets/104760013/f0c3e6ee-2efb-4c7a-9ad7-7b7ca553cdff

**Comment by vshcherb** [comment]
```
endPointIndex	10	
startPointIndex	11	
Road (23997059), name ('Duistervoordseweg')

java.lang.ArrayIndexOutOfBoundsException: Index 11 out of bounds for length 11
	at net.osmand.binary.RouteDataObject.getPoint31YTile(RouteDataObject.java:395)
	at net.osmand.router.RouteSegmentResult.convertPoint(RouteSegmentResult.java:562)
	at net.osmand.router.RouteSegmentResult.getPoint(RouteSegmentResult.java:544)
	at net.osmand.router.RoutePlannerFrontEnd.isRouteCloseToGpxPoints(RoutePlannerFrontEnd.java:352)
	at net.osmand.router.RoutePlannerFrontEnd.searchGpxRoute(RoutePlannerFrontEnd.java:268)
	at net.osmand.swing.MapRouterLayer.getGpxAproximation(MapRouterLayer.java:1057)
	at net.osmand.swing.MapRouterLayer.selfRoute(MapRouterLayer.java:1022)
	at net.osmand.swing.MapRouterLayer$26.run(MapRouterLayer.java:752)
```
