### ISSUE TITLE
Application crash on the tiles loading screen

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#17112]
### Description
Application crash on the tile loading screen when zooming the map.
```
Version  OsmAnd~ 4.5.0#35884m
04.05.2023 2:55:06
Apk Version : 4.5.0#35884m 4500
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalStateException: Slider value(17.0) must be greater or equal to valueFrom(18.0), and lower or equal to valueTo(19.0)
	at com.google.android.material.slider.BaseSlider.validateValues(BaseSlider.java:545)
	at com.google.android.material.slider.BaseSlider.validateConfigurationIfDirty(BaseSlider.java:587)
	at com.google.android.material.slider.BaseSlider.onDraw(BaseSlider.java:1521)
	at android.view.View.draw(View.java:23342)
	at android.view.View.updateDisplayListIfDirty(View.java:22201)
	at android.view.View.draw(View.java:23067)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4543)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4301)
	at android.view.View.updateDisplayListIfDirty(View.java:22190)
	at android.view.View.draw(View.java:23067)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4543)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4301)
	at android.view.View.draw(View.java:23347)
	at android.view.View.updateDisplayListIfDirty(View.java:22201)
	at android.view.View.draw(View.java:23067)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4543)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4301)
	at android.view.View.draw(View.java:23347)
	at android.widget.ScrollView.draw(ScrollView.java:1869)
	at android.view.View.updateDisplayListIfDirty(View.java:22201)
	at android.view.View.draw(View.java:23067)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4543)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4301)
	at android.view.View.updateDisplayListIfDirty(View.java:22190)
	at android.view.View.draw(View.java:23067)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4543)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4301)
	at android.view.View.draw(View.java:23347)
	at android.view.View.updateDisplayListIfDirty(View.java:22201)
	at android.view.View.draw(View.java:23067)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4543)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4301)
	at android.view.View.updateDisplayListIfDirty(View.java:22190)
	at android.view.View.draw(View.java:23067)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4543)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4301)
	at android.view.View.updateDisplayListIfDirty(View.java:22190)
	at android.view.View.draw(View.java:23067)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4543)
	at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1426)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4301)
	at android.view.View.draw(View.java:23347)
	at android.view.View.updateDisplayListIfDirty(View.java:22201)
	at android.view.View.draw(View.java:23067)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4543)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4301)
	at android.view.View.updateDisplayListIfDirty(View.java:22190)
	at android.view.View.draw(View.java:23067)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4543)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4301)
	at android.view.View.updateDisplayListIfDirty(View.java:22190)
	at android.view.View.draw(View.java:23067)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4543)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4301)
	at android.view.View.updateDisplayListIfDirty(View.java:22190)
	at android.view.View.draw(View.java:23067)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4543)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4301)
	at android.view.View.updateDisplayListIfDirty(View.java:22190)
	at android.view.View.draw(View.java:23067)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4543)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4301)
	at android.view.View.draw(View.java:23347)
	at com.android.internal.policy.DecorView.draw(DecorView.java:896)
	at android.view.View.updateDisplayListIfDirty(View.java:22201)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:682)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:690)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:795)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4875)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4576)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3780)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2518)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9389)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1451)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1459)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1089)
	at android.view.Choreographer.doFrame(Choreographer.java:1003)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1431)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8252)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#35887m, Дата выпуска: 2023-05-03
Android version: 13
Device model: poco f3

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#35889m, Released: 2023-05-04

### Step to reproduce

- **Configure map** > **Map source** > **Microsoft Earth**
- **Long tap on the map** > **Actions** > **Download map** > **Set two values to the min** > **Zoom in map**



https://user-images.githubusercontent.com/104760013/236183420-abbc3e3e-1008-4ec6-b47c-3594fe4802f2.mp4
