### ISSUE TITLE
Crash (unknown step before)

### ISSUE THREAD

**Issue by Dominik-K** [osmandapp/Osmand#1715]
Unfortunately, I don't know what I did before. However, here's the exception.log:

Version  OsmAnd~ 2.1.1
19.09.2015 12:46:41
Apk Version : 2.1.1 212
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException
	at net.osmand.plus.myplaces.AvailableGPXFragment.updateCurrentTrack(AvailableGPXFragment.java:188)
	at net.osmand.plus.monitoring.DashTrackFragment$6.run(DashTrackFragment.java:215)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:153)
	at android.app.ActivityThread.main(ActivityThread.java:5299)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by vshcherb** [comment]
Fixed
