### ISSUE TITLE
Osmand stopped showing the vector map

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#17218]
### Description
After updating and restarting, the osmand does not show an offline map.  Reports an error on startup

```
Version  OsmAnd~ 4.5.0#44m
18.05.2023 6:15:42
Apk Version : 4.5.0#44m 4500
Exception occured in thread Thread[Initializing app,5,main] : 
java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
	at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:302)
	at net.osmand.plus.api.SettingsAPIImpl.getString(SettingsAPIImpl.java:77)
	at net.osmand.plus.settings.backend.preferences.StringPreference.getValue(StringPreference.java:13)
	at net.osmand.plus.settings.backend.preferences.StringPreference.getValue(StringPreference.java:5)
	at net.osmand.plus.settings.backend.preferences.CommonPreference.get(CommonPreference.java:208)
	at net.osmand.plus.settings.backend.OsmandSettings.getRenderPropertyValue(OsmandSettings.java:2888)
	at net.osmand.core.android.MapRendererContext.getMapStyleSettings(MapRendererContext.java:275)
	at net.osmand.core.android.MapRendererContext.updateMapPresentationEnvironment(MapRendererContext.java:205)
	at net.osmand.core.android.MapRendererContext.setupObfMap(MapRendererContext.java:148)
	at net.osmand.plus.views.corenative.NativeCoreContext.init(NativeCoreContext.java:81)
	at net.osmand.plus.AppInitializer.initOpenGl(AppInitializer.java:656)
	at net.osmand.plus.AppInitializer.startApplicationBackground(AppInitializer.java:527)
	at net.osmand.plus.AppInitializer.lambda$startApplication$4$net-osmand-plus-AppInitializer(AppInitializer.java:773)
	at net.osmand.plus.AppInitializer$$ExternalSyntheticLambda4.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:1012)
```

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#44m, Дата выпуска: 2023-05-18
Android version: 13
Device model: poco f3

**Comment by Nine-Tailed** [comment]
![Screenshot_2023-05-18-13-57-39-870_net.osmand.plus.jpg](https://github.com/osmandapp/OsmAnd/assets/12549744/b0d72b64-b34d-4faa-a10b-32c7830d8864)

**Comment by albansuser** [comment]
Same here. Blank map.

OsmAnd~ 4.5.0#44m, released: 2023-05-18

Message: "Could not draw vector area"

**Comment by MAlfare** [comment]
Me too!
OsmAnd~ 4.5.0#44m, released: 2023-05-18
In German:
"Ausgewählter Bereich konnte nicht gezeichnet werden"

OsmAnd~ 4.5.0#45m, released: 2023-05-18
OsmAnd~ 4.5.0#41m, released: 2023-05-18

Where can I find an earlier Version?

**Comment by albansuser** [comment]
I reverted (app only) to a late April compilation and everything worked as expected. 

I then updated to OsmAnd~ 4.5.0#45m, released: 2023-05-18 and everthing continues to work. Maybe #44 corrupted something?

**Comment by albansuser** [comment]
Unfortunately clicking on "My Places" causes the error again.

**Comment by albansuser** [comment]
FYI: I reverted to #37 (OsmAnd~ 4.5.0#37m, released: 2023-05-17) and it doesn't show the error at startup, nor upon clicking "My Places"

**Comment by Rowin63** [comment]
Could someone please answer the question, where to find earlier (+) versions? I often want to go back too... Thanks 👍

**Comment by albansuser** [comment]
My apologies for not responding. To answer your question: I make regular backups of the app on my mobile. 

Unfortunately I don't know an online source. Hopefully someone does.

**Comment by vshcherb** [comment]
Fixed, but restart is needed

**Comment by albansuser** [comment]
Great.  Thanks
