### ISSUE TITLE
NPE on startup

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#17253]
### Description
```
Version  OsmAnd~ 4.5.0#79m
23.05.2023 8:23:03
Apk Version : 4.5.0#79m 4500
Exception occured in thread Thread[main,5,main] : 
java.lang.RuntimeException: Unable to resume activity {net.osmand.plus/net.osmand.plus.activities.MapActivity}: java.lang.NullPointerException: Attempt to read from field 'net.osmand.plus.views.mapwidgets.WidgetsPanel net.osmand.plus.views.mapwidgets.WidgetType.defaultPanel' on a null object reference in method 'net.osmand.plus.views.mapwidgets.WidgetsPanel net.osmand.plus.views.mapwidgets.SideWidgetInfo.getUpdatedPanel()'
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4978)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5011)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2389)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8261)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.NullPointerException: Attempt to read from field 'net.osmand.plus.views.mapwidgets.WidgetsPanel net.osmand.plus.views.mapwidgets.WidgetType.defaultPanel' on a null object reference in method 'net.osmand.plus.views.mapwidgets.WidgetsPanel net.osmand.plus.views.mapwidgets.SideWidgetInfo.getUpdatedPanel()'
	at net.osmand.plus.views.mapwidgets.SideWidgetInfo.getUpdatedPanel(SideWidgetInfo.java:50)
	at net.osmand.plus.views.mapwidgets.MapWidgetRegistry.reorderWidgets(MapWidgetRegistry.java:187)
	at net.osmand.plus.views.mapwidgets.MapWidgetRegistry.registerAllControls(MapWidgetRegistry.java:333)
	at net.osmand.plus.views.layers.MapInfoLayer.registerAllControls(MapInfoLayer.java:165)
	at net.osmand.plus.views.layers.MapInfoLayer.recreateAllControls(MapInfoLayer.java:149)
	at net.osmand.plus.activities.MapActivity.updateApplicationModeSettings(MapActivity.java:1263)
	at net.osmand.plus.activities.MapActivity.onResume(MapActivity.java:716)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1565)
	at android.app.Activity.performResume(Activity.java:8668)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4968)
	... 13 more
```

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#79m, Дата выпуска: 2023-05-23
Android version: 13
Device model: poco f3

**Comment by Nine-Tailed** [comment]
In my case it happens after any back button click.
