### ISSUE TITLE
Iran: View map error

### ISSUE THREAD

**Issue by saeedafshari8** [osmandapp/Osmand#1755]
Dear developers,
I installed Osmand latest Apk in my handset that its Android version is 4.1.2. Unfortunately when I start application, application encounter with an error.
Error Description:
Invalid float:"20"

Note: I downloaded the following obf file:
http://download.osmand.net/download.php?standard=yes&file=Iran_asia_2.obf.zip

**Comment by GaidamakUA** [comment]
[exception(2).txt](https://github.com/osmandapp/Osmand/files/4230/exception.2.txt)

**Comment by vshcherb** [comment]
Caused by: java.lang.NumberFormatException: Invalid float: "۲۰"
	at java.lang.StringToReal.invalidReal(StringToReal.java:63)
	at java.lang.StringToReal.parseFloat(StringToReal.java:310)
	at java.lang.Float.parseFloat(Float.java:300)
	at net.osmand.binary.RouteDataObject.parseSpeed(RouteDataObject.java:212)
	at net.osmand.binary.BinaryMapRouteReaderAdapter$RouteTypeRule.analyze(BinaryMapRouteReaderAdapter.java:176)
	at net.osmand.binary.BinaryMapRouteReaderAdapter$RouteTypeRule.<init>(BinaryMapRouteReaderAdapter.java:71)
	at net.osmand.binary.BinaryMapRouteReaderAdapter$RouteRegion.initRouteEncodingRule(BinaryMapRouteReaderAdapter.java:213)
	at net.osmand.binary.BinaryMapRouteReaderAdapter$RouteRegion.access$100(BinaryMapRouteReaderAdapter.java:194)
	at net.osmand.binary.BinaryMapRouteReaderAdapter.readRouteEncodingRule(BinaryMapRouteReaderAdapter.java:600)
	at net.osmand.binary.BinaryMapRouteReaderAdapter.readRouteIndex(BinaryMapRouteReaderAdapter.java:355)
	at net.osmand.binary.BinaryMapIndexReader.init(BinaryMapIndexReader.java:216)

**Comment by saeedafshari8** [comment]
Thanks, Yeah exactly, you find the exception.

**Comment by vshcherb** [comment]
New map just generated doesn't have that value any more.
