### ISSUE TITLE
If Ruler widget is on track recording app crashes 

### ISSUE THREAD

**Issue by Gubayura** [osmandapp/OsmAnd#17603]
### track should be recorded
Device : fleur
Brand : Redmi
Model : 2201117SY
Product : fleur_eea
Build : TP1A.220624.014
Version : 13
App Version : OsmAnd
Apk Version : 4.4.7 4407

**Environment**
OsmAnd Version:
Android/iOS version:
Device model:

**Comment by vshcherb** [comment]
Unfortunately there is no crash log attached to fix, please attach it and try 4.5.5 beta probably it's already fixed

**Comment by mnalis** [comment]
The user orignally reported that on telegram: https://t.me/OsmAndMaps/41322 but had problems attaching a log to github issue. So I'll attach it for them here: [exception.log](https://github.com/osmandapp/OsmAnd/files/12042860/exception.log)

**Comment by vshcherb** [comment]
```
java.lang.IllegalArgumentException
	at android.graphics.LinearGradient.nativeCreate(Native Method)
	at android.graphics.LinearGradient.createNativeInstance(LinearGradient.java:158)
	at android.graphics.Shader.getNativeInstance(Shader.java:191)
	at android.graphics.Paint.getNativeInstance(Paint.java:734)
	at android.graphics.BaseRecordingCanvas.drawPath(BaseRecordingCanvas.java:571)
	at net.osmand.plus.views.layers.RadiusRulerControlLayer.drawLightingHeadingArc(RadiusRulerControlLayer.java:550)
	at net.osmand.plus.views.layers.RadiusRulerControlLayer.drawCompassCircle(RadiusRulerControlLayer.java:460)
	at net.osmand.plus.views.layers.RadiusRulerControlLayer.onDraw(RadiusRulerControlLayer.java:195)
	at net.osmand.plus.views.OsmandMapTileView.drawOverMap(OsmandMapTileView.java:1036)
	at net.osmand.plus.views.OsmAndMapLayersView.onDraw(OsmAndMapLayersView.java:84)
	at android.view.View.draw(View.java:23545)
	at android.view.View.updateDisplayListIfDirty(View.java:22341)
	at android.view.View.draw(View.java:23244)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4640)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4398)
	at android.view.View.updateDisplayListIfDirty(View.java:22330)
	at android.view.View.draw(View.java:23244)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4640)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4398)
	at android.view.View.updateDisplayListIfDirty(View.java:22330)
	at android.view.View.draw(View.java:23244)
	at android.view.ViewGroup.drawChild
```

**Comment by vshcherb** [comment]
Unfortunately didn't reproduce and we couldn't fix by crash
