### ISSUE TITLE
"Import from file" doesn't work 

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#17672]
## Description

* File [Export_2023-06-29.osf.zip](https://github.com/osmandapp/OsmAnd/files/11904250/Export_2023-06-29.osf.zip)
* Tested on today latest builds

### How to reproduce
* Save file to device
* Open OsmAnd – Settings – Scroll down
* Tap on Import from file
* Select file in file manager

### Actual result
* Nothing happens
* Log file – [logcat (1) (1).log](https://github.com/osmandapp/OsmAnd/files/12105207/logcat.1.1.log)

```
net.osmand: SettingsHelper Failed to collect items from: Export_2023-06-29.osf
 java.lang.IllegalArgumentException: No items
 	at net.osmand.plus.settings.backend.backup.SettingsImporter.processItems(SettingsImporter.java:109)
 	at net.osmand.plus.settings.backend.backup.SettingsImporter.collectItems(SettingsImporter.java:37)
 	at net.osmand.plus.settings.backend.backup.ImportFileTask.doInBackground(ImportFileTask.java:102)
 	at net.osmand.plus.settings.backend.backup.ImportFileTask.doInBackground(ImportFileTask.java:23)
 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
 	at java.lang.Thread.run(Thread.java:1012)
```
### Expected result

**Environment**
OsmAnd~ 4.5.0#436m 4500
Android version: 14
Device model: Pixel 6A

**Comment by vshcherb** [comment]
File backup is empty, it's a bug but not critical

**Comment by Chumva** [comment]
There are two osf files in Export_2023-06-29.osf.zip, first one (4kb) works fine, another one (178 bytes) is empty or broken.

**Comment by Nine-Tailed** [comment]
Import through the favorites screen does not work.
1. Go to the favorites screen.
2. Press the plus button and selecte the file.
Nothing happens.
