### ISSUE TITLE
night builds - poi_types.xml causes crash?

### ISSUE THREAD

**Issue by Barrocas** [osmandapp/Osmand#1779]
I already had reported it here:
https://groups.google.com/forum/#!topic/osmand/is9ODfi7kYo
Copy from the link:
On the various night build versions (just installed today morning), I'm experiencing several repeated crashes on Osmand startup, mainly after a forced close (app crash, or app swipe / force close).

I also noticed and tested that if I delete the file 'poi_types.xml' then Osmand starts up as expected (but with a crash report warning).

This is happening through several versions, but I have no track from where it started.

**Comment by Barrocas** [comment]
Testing today night build.
It crashed once, but then I deleted the 'poi_types.xml' file (from previous versions), and it appears that this file is no longer created again, so I had no more crashing after force close/swipe from app list.

**Comment by vshcherb** [comment]
Can you please attach logs, so it will be easier.

**Comment by Barrocas** [comment]
Fom today night build, installed and it crashed imediatly on startup.
It also created the 'poi_types.xml' file, after that file was deleted,
Osmand started as expected:

Version  OsmAnd~ 2.2.0#13461M
08.10.2015 8:44:57
Apk Version : 2.2.0#13461M 211
Exception occured in thread Thread[main,5,main] :
java.lang.RuntimeException: Unable to resume activity
{net.osmand.plus/net.osmand.plus.activities.MapActivity}:
java.util.ConcurrentModificationException
at
android.app.ActivityThread.performResumeActivity(ActivityThread.java:2997)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3026)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2428)
at android.app.ActivityThread.access$800(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342)
at android.os.Handler.dispatchMessage(Handler.java:110)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:5327)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.util.ConcurrentModificationException
at
java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:347)
at java.util.LinkedHashMap$ValueIterator.next(LinkedHashMap.java:371)
at java.util.AbstractCollection.toArrayList(AbstractCollection.java:349)
at java.util.AbstractCollection.toArray(AbstractCollection.java:339)
at java.util.ArrayList.<init>(ArrayList.java:97)
at
net.osmand.plus.audionotes.DashAudioVideoNotesFragment.setupNotes(DashAudioVideoNotesFragment.java:63)
at
net.osmand.plus.audionotes.DashAudioVideoNotesFragment.onOpenDash(DashAudioVideoNotesFragment.java:53)
at
net.osmand.plus.dashboard.DashBaseFragment.onResume(DashBaseFragment.java:123)
at android.support.v4.app.Fragment.performResume(Fragment.java:1832)
at
android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:995)
at
android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
at
android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
at
android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:437)
at
android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:138)
at android.app.Activity.performResume(Activity.java:5435)
at
android.app.ActivityThread.performResumeActivity(ActivityThread.java:2983)
... 12 more
Version  OsmAnd~ 2.2.0#13461M
08.10.2015 8:44:57
Apk Version : 2.2.0#13461M 211
Exception occured in thread Thread[main,5,main] :
java.lang.RuntimeException: Unable to resume activity
{net.osmand.plus/net.osmand.plus.activities.MapActivity}:
java.util.ConcurrentModificationException
at
android.app.ActivityThread.performResumeActivity(ActivityThread.java:2997)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3026)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2428)
at android.app.ActivityThread.access$800(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342)
at android.os.Handler.dispatchMessage(Handler.java:110)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:5327)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.util.ConcurrentModificationException
at
java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:347)
at java.util.LinkedHashMap$ValueIterator.next(LinkedHashMap.java:371)
at java.util.AbstractCollection.toArrayList(AbstractCollection.java:349)
at java.util.AbstractCollection.toArray(AbstractCollection.java:339)
at java.util.ArrayList.<init>(ArrayList.java:97)
at
net.osmand.plus.audionotes.DashAudioVideoNotesFragment.setupNotes(DashAudioVideoNotesFragment.java:63)
at
net.osmand.plus.audionotes.DashAudioVideoNotesFragment.onOpenDash(DashAudioVideoNotesFragment.java:53)
at
net.osmand.plus.dashboard.DashBaseFragment.onResume(DashBaseFragment.java:123)
at android.support.v4.app.Fragment.performResume(Fragment.java:1832)
at
android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:995)
at
android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
at
android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
at
android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:437)
at
android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:138)
at android.app.Activity.performResume(Activity.java:5435)
at
android.app.ActivityThread.performResumeActivity(ActivityThread.java:2983)
... 12 more



-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by GaidamakUA** [comment]
Can you tell us if the problem persists please?

**Comment by Barrocas** [comment]
Sure I can test it.
Just downloaded and installed
Version  OsmAnd~ 2.2.0#13464M
08.10.2015 14:12

It also created the 'poi_types.xml' file, but Osmand started without issues.
After swipe app to close, or even go to Android aplications and choose
Osmand to force close, it also starts without issues.

Thanks for the fast fix!
Great work :)


-- 
Cumprimentos,
D.er Hugo Barrocas
