### ISSUE TITLE
crash "can't deliver broadcast"

### ISSUE THREAD

**Issue by vinc17fr** [osmandapp/OsmAnd#17820]
## Description
When opening OsmAnd+ this afternoon, it crashed, leaving an `exception.log` file with contents:
```
Version  OsmAnd+ 4.5.9
05.08.2023 10:21:46
Apk Version : 4.5.9 4509
Exception occured in thread Thread[main,5,main] :
android.app.RemoteServiceException$CannotDeliverBroadcastException: can't deliver broadcast
        at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2219)
        at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2508)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8757)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

I don't know how to reproduce the crash.

**Environment**
OsmAnd Version: 4.5.9
Android/iOS version: Android 13
Device model: Samsung Galaxy S23 Ultra

**Comment by vshcherb** [comment]
We monitor other issues / crashes on Google Play and it's very rare crash, so we're not going to run deep investigation unless we find that's reproduced.
