### ISSUE TITLE
Crash when trying to send osm notes on unstable connection

### ISSUE THREAD

**Issue by deevroman** [osmandapp/OsmAnd#17880]
## Description
Crash when trying to send osm notes on unstable connection

### How to reproduce
Find yourself in a place with unstable 2G
Leave an OSM note
Send an OSM note
Crash after a while

**Environment**
Device : a52q
Brand : samsung
Model : SM-A525F
Product : a52qnsser
Build : TP1A.220624.014.A525FXXS6DWG1
Version : 13
App Version : OsmAnd
Apk Version : 4.5.9 4509

Logs:
[exception.log](https://github.com/osmandapp/OsmAnd/files/12307313/exception.log)

**Comment by vshcherb** [comment]
I hope data is preserved 
Crash
```
Caused by: java.net.UnknownHostException: Unable to resolve host "api.openstreetmap.org": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at com.android.okhttp.Dns$1.lookup(Dns.java:41)
```
