### ISSUE TITLE
Crash while tapping on black map marker

### ISSUE THREAD

**Issue by jf-simon** [osmandapp/Osmand#1792]
To reproduce
 tap on dashboard
Tap on an fav or last visit place
Map opens with black marker
Tap on this marker course an crash

Nightly 13486

Greetings Simon
![screenshot_2015-10-09-13-01-04](https://cloud.githubusercontent.com/assets/11144987/10392284/f7a2edce-6e85-11e5-845b-e2462626251c.png)

**Comment by Barrocas** [comment]
Yes, I can confirm this also.
Tapping a POI thas was selected in the Favorites list causes app crash.

This issue is also commented in another topic, but mixed with other
subjects.

Here is the 'exception.log' file content:

Version  OsmAnd~ 2.2.0#13484M
09.10.2015 12:36:30
Apk Version : 2.2.0#13484M 211
Exception occured in thread Thread[main,5,main] :
java.lang.NullPointerException
at
net.osmand.plus.views.ContextMenuLayer.showMapContextMenu(ContextMenuLayer.java:534)
at
net.osmand.plus.views.ContextMenuLayer.showMapContextMenu(ContextMenuLayer.java:526)
at
net.osmand.plus.views.ContextMenuLayer.showContextMenuForSelectedObjects(ContextMenuLayer.java:509)
at
net.osmand.plus.views.ContextMenuLayer.onSingleTap(ContextMenuLayer.java:468)
at
net.osmand.plus.views.OsmandMapTileView$MapTileViewOnGestureListener.onSingleTapConfirmed(OsmandMapTileView.java:975)
at net.osmand.access.MapExplorer.onSingleTapConfirmed(MapExplorer.java:133)
at
android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:273)
at android.os.Handler.dispatchMessage(Handler.java:110)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:5327)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
at dalvik.system.NativeStart.main(Native Method)
Version  OsmAnd~ 2.2.0#13484M
09.10.2015 12:36:30
Apk Version : 2.2.0#13484M 211
Exception occured in thread Thread[main,5,main] :
java.lang.NullPointerException
at
net.osmand.plus.views.ContextMenuLayer.showMapContextMenu(ContextMenuLayer.java:534)
at
net.osmand.plus.views.ContextMenuLayer.showMapContextMenu(ContextMenuLayer.java:526)
at
net.osmand.plus.views.ContextMenuLayer.showContextMenuForSelectedObjects(ContextMenuLayer.java:509)
at
net.osmand.plus.views.ContextMenuLayer.onSingleTap(ContextMenuLayer.java:468)
at
net.osmand.plus.views.OsmandMapTileView$MapTileViewOnGestureListener.onSingleTapConfirmed(OsmandMapTileView.java:975)
at net.osmand.access.MapExplorer.onSingleTapConfirmed(MapExplorer.java:133)
at
android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:273)
at android.os.Handler.dispatchMessage(Handler.java:110)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:5327)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
at dalvik.system.NativeStart.main(Native Method)



-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by vshcherb** [comment]
Fixed
