### ISSUE TITLE
Removing Map Marker Widget from Driving Profile Causes OsmAnd to Crash

### ISSUE THREAD

**Issue by Sonwon1** [osmandapp/OsmAnd#18021]
## Description

Removing Map Marker Widget from Driving Profile top panel Causes OsmAnd to Crash

### How to reproduce

1. Remove the Map Marker widget from Global profile top panel
2. Remove the Map Marker widget from Driving profile top panel

### Actual result

CRASH

### Expected result

Removal of the Map Marker widget from Driving profile top panel

**Environment**
OsmAnd Version: 4.5.10
Android/iOS version: 13
Device model: Samsung Galaxy Active Tab 3

**Comment by Sonwon1** [comment]
Also, multiple crash reports were sent via email! The last one sent was after a fresh install.

**Comment by vshcherb** [comment]
Could you please have crashlogs attached? you can copy it from email to here (just zip it)

**Comment by Sonwon1** [comment]
> Could you please have crashlogs attached? you can copy it from email to here (just zip it)

[exception.zip](https://github.com/osmandapp/OsmAnd/files/12461119/exception.zip)

**Comment by Sonwon1** [comment]
Let me know if you want me to upload all of the crash logs.

**Comment by vshcherb** [comment]
```
java.lang.IndexOutOfBoundsException: index=2 count=1
	at android.view.ViewGroup.addInArray(ViewGroup.java:5606)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5499)
	at android.view.ViewGroup.addView(ViewGroup.java:5296)
	at android.view.ViewGroup.addView(ViewGroup.java:5236)
	at net.osmand.plus.views.mapwidgets.widgets.LanesWidget.attachView(LanesWidget.java:174)
	at net.osmand.plus.views.mapwidgets.MapWidgetRegistry.populateControlsContainer(MapWidgetRegistry.java:78)
	at net.osmand.plus.views.layers.MapInfoLayer.recreateWidgetsPanel(MapInfoLayer.java:195)
	at net.osmand.plus.views.layers.MapInfoLayer.recreateTopWidgetsPanel(MapInfoLayer.java:189)
	at net.osmand.plus.views.mapwidgets.widgets.StreetNameWidget.updateVisibility(StreetNameWidget.java:357)
	at net.osmand.plus.views.mapwidgets.widgets.StreetNameWidget.updateInfo(StreetNameWidget.java:127)
	at net.osmand.plus.views.mapwidgets.MapWidgetRegistry.updateWidgetsInfo(MapWidgetRegistry.java:85)
	at net.osmand.plus.views.layers.MapInfoLayer.recreateControls(MapInfoLayer.java:178)
	at net.osmand.plus.utils.WidgetUtils.addSelectedWidgets(WidgetUtils.java:55)
	at net.osmand.plus.views.mapwidgets.configure.panel.ConfigureWidgetsFragment.onWidgetsSelectedToAdd(ConfigureWidgetsFragment.java:245)
	at net.osmand.plus.views.mapwidgets.configure.reorder.ReorderWidgetsFragment.applyWidgetsPanel(ReorderWidgetsFragment.java:428)
	at net.osmand.plus.views.mapwidgets.configure.reorder.ReorderWidgetsFragment.applyWidgetsConfiguration(ReorderWidgetsFragment.java:415)
	at net.osmand.plus.views.mapwidgets.configure.reorder.ReorderWidgetsFragment.onApplyChanges(ReorderWidgetsFragment.java:232)
	at net.osmand.plus.views.mapwidgets.configure.reorder.ReorderWidgetsFragment.lambda$setupApplyButton$3$net-osmand-plus-views-mapwidgets-configure-reorder-ReorderWidgetsFragment(ReorderWidgetsFragment.java:214)
	at net.osmand.plus.views.mapwidgets.configure.reorder.ReorderWidgetsFragment$$ExternalSyntheticLambda5.onClick(Unknown Source:2)

```

**Comment by Chumva** [comment]
This should be fixed [here](https://github.com/osmandapp/OsmAnd/commit/40bd9caeb4b713eb17d08f6807d066a5e962cc56)
