### ISSUE TITLE
Crash on "Manage map files"

### ISSUE THREAD

**Issue by quelbs** [osmandapp/Osmand#1820]
When I open "Manage map files" and select "Local" or "Updates" the app crashes.

**Comment by quelbs** [comment]
As I am not allowed to attach files, here is the exception log as text:


```
Version  OsmAnd~ 2.2.0#13659M
20.10.2015 3:03:04
Apk Version : 2.2.0#13659M 211
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException
	at net.osmand.plus.download.IndexItem.getBasename(IndexItem.java:126)
	at net.osmand.plus.download.ui.ItemViewHolder.getClickAction(ItemViewHolder.java:272)
	at net.osmand.plus.download.ui.ItemViewHolder.checkDisabledAndClickAction(ItemViewHolder.java:254)
	at net.osmand.plus.download.ui.ItemViewHolder.bindIndexItem(ItemViewHolder.java:127)
	at net.osmand.plus.download.ui.UpdatesIndexFragment$UpdateIndexAdapter.getView(UpdatesIndexFragment.java:183)
	at android.widget.AbsListView.obtainView(AbsListView.java:2207)
	at android.widget.ListView.makeAndAddView(ListView.java:1845)
	at android.widget.ListView.fillDown(ListView.java:678)
	at android.widget.ListView.fillFromTop(ListView.java:739)
	at android.widget.ListView.layoutChildren(ListView.java:1661)
	at android.widget.AbsListView.onLayout(AbsListView.java:2037)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1670)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1528)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1441)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1626)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1670)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1528)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1441)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.support.v7.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:493)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1670)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1528)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1441)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2183)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1947)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1139)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4879)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
	at android.view.Choreographer.doCallbacks(Choreographer.java:579)
	at android.view.Choreographer.doFrame(Choreographer.java:548)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:762)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:153)
	at android.app.ActivityThread.main(ActivityThread.java:5299)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(Native Method)
```
