### ISSUE TITLE
Create POI - Avanced tab - add more than one Tag -> app crash

### ISSUE THREAD

**Issue by Barrocas** [osmandapp/Osmand#1823]
Using v2.2.0#13676M on Android 4.4.2

Choose any place on the map (by long pressing),
on that spot menu, choose the 3dots, then 'Create POI'
go to the 'ADVANCED' tab
choose 'Add tag' twice, app crashes.

**Comment by Barrocas** [comment]
The exception log file:

Version  OsmAnd~ 2.2.0#13676M
21.10.2015 11:16:10
Apk Version : 2.2.0#13676M 211
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
	at android.view.ViewGroup.addViewInner(ViewGroup.java:3718)
	at android.view.ViewGroup.addView(ViewGroup.java:3564)
	at android.view.ViewGroup.addView(ViewGroup.java:3509)
	at android.view.ViewGroup.addView(ViewGroup.java:3485)
	at net.osmand.plus.osmedit.AdvancedDataFragment$TagAdapterLinearLayoutHack.addTagView(AdvancedDataFragment.java:194)
	at net.osmand.plus.osmedit.AdvancedDataFragment$1.onClick(AdvancedDataFragment.java:93)
	at android.view.View.performClick(View.java:4463)
	at android.view.View$PerformClick.run(View.java:18770)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5327)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
	at dalvik.system.NativeStart.main(Native Method)
Version  OsmAnd~ 2.2.0#13676M
21.10.2015 11:16:10
Apk Version : 2.2.0#13676M 211
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
	at android.view.ViewGroup.addViewInner(ViewGroup.java:3718)
	at android.view.ViewGroup.addView(ViewGroup.java:3564)
	at android.view.ViewGroup.addView(ViewGroup.java:3509)
	at android.view.ViewGroup.addView(ViewGroup.java:3485)
	at net.osmand.plus.osmedit.AdvancedDataFragment$TagAdapterLinearLayoutHack.addTagView(AdvancedDataFragment.java:194)
	at net.osmand.plus.osmedit.AdvancedDataFragment$1.onClick(AdvancedDataFragment.java:93)
	at android.view.View.performClick(View.java:4463)
	at android.view.View$PerformClick.run(View.java:18770)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5327)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by GaidamakUA** [comment]
Fixed.
