### ISSUE TITLE
Crash (OutOfMemory)

### ISSUE THREAD

**Issue by Dominik-K** [osmandapp/Osmand#1832]
Version  OsmAnd~ 2.1.1
18.10.2015 4:57:59
Apk Version : 2.1.1 212
Exception occured in thread Thread[RenderingBaseImage,5,main] : 
java.lang.OutOfMemoryError
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:689)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:666)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:633)
	at net.osmand.plus.views.OsmandMapTileView.refreshBaseMapInternal(OsmandMapTileView.java:446)
	at net.osmand.plus.views.OsmandMapTileView.access$700(OsmandMapTileView.java:60)
	at net.osmand.plus.views.OsmandMapTileView$2.run(OsmandMapTileView.java:600)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:153)
	at android.os.HandlerThread.run(HandlerThread.java:60)

**Comment by vshcherb** [comment]
This issue doesn't give any hint what could be fixed, it could be related to the Android < 4.0 versions
