### ISSUE TITLE
Crash in searchPoiByName

### ISSUE THREAD

**Issue by Dominik-K** [osmandapp/Osmand#1833]
I don't know what I searched for. Sorry.

Version  OsmAnd~ 2.1.1
16.10.2015 11:08:42
Apk Version : 2.1.1 212
Exception occured in thread Thread[AsyncTask #4,5,main] : 
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:299)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
	at java.util.concurrent.FutureTask.run(FutureTask.java:239)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:838)
Caused by: java.lang.IllegalArgumentException
	at net.osmand.binary.BinaryMapIndexReader.searchPoiByName(BinaryMapIndexReader.java:1289)
	at net.osmand.plus.resources.AmenityIndexRepositoryBinary.searchAmenitiesByName(AmenityIndexRepositoryBinary.java:67)
	at net.osmand.plus.resources.ResourceManager.searchAmenitiesByName(ResourceManager.java:805)
	at net.osmand.plus.poi.SearchByNameFilter.searchAmenitiesInternal(SearchByNameFilter.java:36)
	at net.osmand.plus.poi.PoiUIFilter.searchAmenities(PoiUIFilter.java:227)
	at net.osmand.plus.poi.PoiUIFilter.initializeNewSearch(PoiUIFilter.java:199)
	at net.osmand.plus.activities.search.SearchPOIActivity$SearchAmenityTask.doInBackground(SearchPOIActivity.java:661)
	at net.osmand.plus.activities.search.SearchPOIActivity$SearchAmenityTask.doInBackground(SearchPOIActivity.java:590)
	at android.os.AsyncTask$2.call(AsyncTask.java:287)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	... 4 more

**Comment by vshcherb** [comment]
Looks like it was empty string send to search (by exception), unfortunately can't reproduce it, may be a weird coincidence.
