### ISSUE TITLE
Illegal Argument Exception

### ISSUE THREAD

**Issue by bandishsapphire** [osmandapp/OsmAnd#18523]
I have integrated OsmAnd in my app. But as soon as I run the app, I am getting the below error.

Tag Manager is not found and thus will not be used
java.lang.IllegalArgumentException
at org.kxml2.io.KXmlParser.setInput(Unknown Source:294)
at net.osmand.router.RoutingConfiguration.parseFromInputStream(RoutingConfiguration.java:334)
at net.osmand.router.RoutingConfiguration.parseFromInputStream(RoutingConfiguration.java:325)
at net.osmand.router.RoutingConfiguration.getDefault(RoutingConfiguration.java:315)
at com.example.osmsapphire.net.osmand.plus.AppInitializer$2.getDefaultAttributes(AppInitializer.java:477)
at com.example.osmsapphire.net.osmand.plus.AppInitializer$2.doInBackground(AppInitializer.java:438)
at com.example.osmsapphire.net.osmand.plus.AppInitializer$2.doInBackground(AppInitializer.java:434)
at android.os.AsyncTask$3.call(AsyncTask.java:394)
at java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
at java.lang.Thread.run(Thread.java:1012)
Startup service com.example.osmsapphire.IBRouterService took too long 803 ms
Startup service com.example.osmsapphire.net.osmand.plus.routing.RoutingHelper took too long 13 ms

Unexpected error
    java.lang.IllegalArgumentException
    	at org.kxml2.io.KXmlParser.setInput(Unknown Source:294)
    	at net.osmand.osm.MapPoiTypes.initFromInputStream(MapPoiTypes.java:390)
    	at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:362)
    	at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:348)
    	at com.example.osmsapphire.net.osmand.plus.AppInitializer.initPoiTypes(AppInitializer.java:298)
    	at com.example.osmsapphire.net.osmand.plus.AppInitializer.startApplicationBackground(AppInitializer.java:535)
    	at com.example.osmsapphire.net.osmand.plus.AppInitializer.lambda$startApplication$4$com-example-osmsapphire-net-osmand-plus-AppInitializer(AppInitializer.java:783)
    	at com.example.osmsapphire.net.osmand.plus.AppInitializer$$ExternalSyntheticLambda0.run(Unknown Source:2)

After debugging the code I found that some files like poi_types.xml, regions.ocbf not found.

Can you please help me with this?

**Comment by groomkrunal** [comment]
@jrudolph @kadamski  @cbenz @xet7 Any one can help on this ? I am also getting same error.

**Comment by vshcherb** [comment]
Looks like you are missing some xml files probably like routing.xml or default.render.xml

**Comment by groomkrunal** [comment]
@vshcherb  boths files are there in my code. Still we are getting same error.

**Comment by vshcherb** [comment]
That's weird actually

**Comment by groomkrunal** [comment]
@vshcherb anything if we missed. Because we migrate from old version to lastest one..

**Comment by groomkrunal** [comment]
@vshcherb is it possible to check our code by your team ? because we have to deploy the project and only one thing is not working so we can't live the project. Can you please help us with that ?

**Comment by vshcherb** [comment]
Unfortunately I won't be able to help probably you are running under specific conditions and you need to debug what hapened with xml and while it's lost during build. It doesn't happen with latest default build, so you probably need to check configuration and see what's inside poi_types.xml

**Comment by groomkrunal** [comment]
Hello @vshcherb we checked the poi_types.xml file and its configure correctly.  still facing same error.

**Comment by groomkrunal** [comment]
Hello @vshcherb can you please guide us which configuration we have to take care so we check again all that ?

**Comment by groomkrunal** [comment]
Hello @vshcherb  any update on this ?

**Comment by vshcherb** [comment]
I don't have any update cause we simply don't reproduce this issue yet. All builds are fine
