### ISSUE TITLE
Failed to load 'Qt5Core' on 2.2.0 10106D nightly

### ISSUE THREAD

**Issue by bonanza123** [osmandapp/Osmand#1859]
Hey,

I'm running a nightly on my maguro with CM11 and noticed that starting car navigation crashes often with the following error. I also noticed these crashes on previous nightlies.
It seems to happen only when starting navigation from a high-detail map view (e.g. 'world map' view) and then switching to the car view mode (which happens automatically due to the start of the navigation) where many details are hidden.

```
11-01 15:15:34.092 D/dalvikvm(7623): Trying to load lib /data/app-lib/net.osmand-1/libgnustl_shared.so 0x42207f60
11-01 15:15:34.100 D/dalvikvm(7623): Added shared lib /data/app-lib/net.osmand-1/libgnustl_shared.so 0x42207f60
11-01 15:15:34.100 D/dalvikvm(7623): No JNI_OnLoad found in /data/app-lib/net.osmand-1/libgnustl_shared.so 0x42207f60, skipping init
11-01 15:15:34.123 E/OsmAndCore:Android/NativeCore(7623): Failed to load 'Qt5Core'
11-01 15:15:34.123 E/OsmAndCore:Android/NativeCore(7623): java.lang.UnsatisfiedLinkError: Couldn't load Qt5Core from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/net.osmand-1.apk"],nativeLibraryDirectories=[/data/app-lib/net.osmand-1, /vendor/lib, /system/lib]]]: findLibrary returned null
11-01 15:15:34.123 E/OsmAndCore:Android/NativeCore(7623): 	at java.lang.Runtime.loadLibrary(Runtime.java:358)
11-01 15:15:34.123 E/OsmAndCore:Android/NativeCore(7623): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
11-01 15:15:34.123 E/OsmAndCore:Android/NativeCore(7623): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
11-01 15:15:34.123 E/OsmAndCore:Android/NativeCore(7623): 	at java.lang.Runtime.loadLibrary(Native Method)
11-01 15:15:34.123 E/OsmAndCore:Android/NativeCore(7623): 	at java.lang.System.loadLibrary(System.java:526)
11-01 15:15:34.123 E/OsmAndCore:Android/NativeCore(7623): 	at net.osmand.core.android.NativeCore.loadNativeLibrary(NativeCore.java:25)
11-01 15:15:34.123 E/OsmAndCore:Android/NativeCore(7623): 	at net.osmand.core.android.NativeCore.<clinit>(NativeCore.java:43)
11-01 15:15:34.123 E/OsmAndCore:Android/NativeCore(7623): 	at net.osmand.plus.views.corenative.NativeCoreContext.init(NativeCoreContext.java:48)
11-01 15:15:34.123 E/OsmAndCore:Android/NativeCore(7623): 	at net.osmand.plus.views.corenative.NativeCoreContext.tryCatchInit(NativeCoreContext.java:37)
11-01 15:15:34.123 E/OsmAndCore:Android/NativeCore(7623): 	at net.osmand.plus.AppInitializer.initNativeCore(AppInitializer.java:514)
11-01 15:15:34.123 E/OsmAndCore:Android/NativeCore(7623): 	at net.osmand.plus.AppInitializer.startApplicationBackground(AppInitializer.java:444)
11-01 15:15:34.123 E/OsmAndCore:Android/NativeCore(7623): 	at net.osmand.plus.AppInitializer.access$200(AppInitializer.java:58)
11-01 15:15:34.123 E/OsmAndCore:Android/NativeCore(7623): 	at net.osmand.plus.AppInitializer$8.run(AppInitializer.java:652)
11-01 15:15:34.123 E/OsmAndCore:Android/NativeCore(7623): 	at java.lang.Thread.run(Thread.java:841)
11-01 15:15:34.162 D/net.osmand(7623): NativeOsmandLibrary Loading native gnustl_shared...
11-01 15:15:34.162 D/dalvikvm(7623): Trying to load lib /data/app-lib/net.osmand-1/libgnustl_shared.so 0x42207f60
11-01 15:15:34.162 D/dalvikvm(7623): Shared lib '/data/app-lib/net.osmand-1/libgnustl_shared.so' already loaded in same CL 0x42207f60
11-01 15:15:34.162 D/net.osmand(7623): NativeOsmandLibrary Loading jnigraphics, since Android >= 2.2 ...
11-01 15:15:34.162 D/dalvikvm(7623): No JNI_OnLoad found in /system/lib/libjnigraphics.so 0x42207f60, skipping init
11-01 15:15:34.162 D/net.osmand(7623): NativeOsmandLibrary Loading native libraries...
11-01 15:15:34.162 D/dalvikvm(7623): Trying to load lib /data/app-lib/net.osmand-1/libosmand.so 0x42207f60
11-01 15:15:34.170 D/dalvikvm(7623): Added shared lib /data/app-lib/net.osmand-1/libosmand.so 0x42207f60
11-01 15:15:34.170 I/net.osmand:native(7623): JNI_OnLoad completed
11-01 15:15:34.170 D/net.osmand(7623): NativeOsmandLibrary Creating NativeOsmandLibrary instance...
11-01 15:15:34.170 D/net.osmand(7623): NativeOsmandLibrary Initializing rendering rules storage...
11-01 15:15:34.170 D/net.osmand:native(7623): Init rendering storage net.osmand.render.RenderingRulesStorage@41da2330 
11-01 15:15:35.670 I/net.osmand:native(7623): Native Cache file initialized /storage/emulated/0/osmand/ind.cache```

**Comment by vshcherb** [comment]
The warning has fixed.
