### ISSUE TITLE
crash in the module OSM editing

### ISSUE THREAD

**Issue by kadlecf** [osmandapp/OsmAnd#18738]
### Description

I am using the OSM editing module. Sometimes, OsmAnd will crash upon an attempt of uploading edited POIs (when attempting to update tags).

### Steps to reproduce

Activate the OSM editing module. Choose an existing POI in the map (not necessarily _any_ point). Example: https://www.openstreetmap.org/node/10617944545
where I edited the tags to contain this information:

amenity=fast_food
cuisine=pizza
name=KM pizza
outdoor_seating=no
takeaway=yes
opening_hours=Mo-Fr 09:00-23:30; Sa, Su 10:00-23:30
indoor_seating=yes
toilets=no

(opening_hours were edited via the time selector tool)
Upload this POI, e.g., via My places | OSM edits, or directly using the lower-part-of-screen menu.

### Actual result

OsmAnd crashes, the edited POI remains in the list My places | OSM edits

### Expected result

updated POI is uploaded and removed from the list My places | OSM edits

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.5.10
Android/iOS version: Android 12, kernel 4.14.190-perf+
Device model: Nokia 5.3
Crash-Logs: sent to crash@osmand.net
```

**Comment by zipav** [comment]
OsmAnd Nightly 4.7.0#1254m, released: 2023-12-20

On the latest build of OsmAnd Nightly is not reproduced. POI uploads successfully, without crashing.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/e2fb5cf1-4c71-44c6-a86f-c85f4834971d"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by scaidermern** [comment]
Could this be caused by the same exception as #14992?

**Comment by kadlecf** [comment]
to this, I can only say firmly that it occurs even when the device is connected to internet. If I have a group of POIs, those who were created (not edited) are uploaded without problems.

**Comment by vshcherb** [comment]
If you have exception.log please attach related part of it, also there is 4.6 out already

**Comment by kadlecf** [comment]
Yes, indeed, my current version is 4.6.9. Sadly, the crash is still occurring without any change. The relevant part of exception.log is here:

```
05.01.2024 2:58:19
Apk Version : 4.6.9 4609
Exception occurred in thread Thread[AsyncTask #4,5,main] :
java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:415)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
        at java.util.concurrent.FutureTask.run(FutureTask.java:269)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1574)
        at java.util.HashMap$KeyIterator.next(HashMap.java:1597)
        at net.osmand.plus.plugins.osmedit.data.OpenstreetmapPoint.trimChangedTagNamesValues(OpenstreetmapPoint.java:102)
        at net.osmand.plus.plugins.osmedit.asynctasks.UploadOpenstreetmapPointAsyncTask.doInBackground(UploadOpenstreetmapPointAsyncTask.java:68)
        at net.osmand.plus.plugins.osmedit.asynctasks.UploadOpenstreetmapPointAsyncTask.doInBackground(UploadOpenstreetmapPointAsyncTask.java:23)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        ... 3 more
```
