### ISSUE TITLE
Crash when changing widget size

### ISSUE THREAD

**Issue by spaanse** [osmandapp/OsmAnd#18804]
### Description

When changing the size of top bar widgets in a row, the app crashes.
In the crash log it mentions an Index out of bounds
An interesting observation is that the rows are not correctly numbered in the reorganisation view.
Example:
```
Row 1
  Lanes
Row 3
  Sunrise
  Sunset
```

### Steps to reproduce

1. Go to Configure screen → Top panel
2. Add the lanes widget, the sunrise widget and the sunset widget
3. Reorganise (observe the rows are numbered 1,3,4)
4. Move sunset into row 3 and save
5. edit sunset and change size to small and save

Note: it may be relevant that the lanes widget is not rendered since I am not on a road with lanes.

### Actual result

The app crashes

### Expected result

it saves and the sunset widget is small

### Your Environment (required)

```
OsmAnd Version: 4.6.8.4608
Android/iOS version: 13
Device model: OnePlus Nord
Crash-Logs: ?

Version  OsmAnd 4.6.8
22.12.2023 7:00:48
Apk Version : 4.6.8 4608
Exception occurred in thread Thread[main,5,main] : 
java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:434)
	at net.osmand.plus.views.mapwidgets.configure.settings.BaseSimpleWidgetSettingsFragment.updateRowWidgets(BaseSimpleWidgetSettingsFragment.java:144)
	at net.osmand.plus.views.mapwidgets.configure.settings.BaseSimpleWidgetSettingsFragment.applySettings(BaseSimpleWidgetSettingsFragment.java:124)
	at net.osmand.plus.views.mapwidgets.configure.settings.SunriseSunsetSettingsFragment.applySettings(SunriseSunsetSettingsFragment.java:122)
	at net.osmand.plus.views.mapwidgets.configure.settings.WidgetSettingsBaseFragment.lambda$setupApplyButton$2$net-osmand-plus-views-mapwidgets-configure-settings-WidgetSettingsBaseFragment(WidgetSettingsBaseFragment.java:115)
	at net.osmand.plus.views.mapwidgets.configure.settings.WidgetSettingsBaseFragment$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7558)
	at android.view.View.performClickInternal(View.java:7534)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29661)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8377)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced, despite attempts in the newest release. 
- Notably, the rearrangement of rows can't be recreated due to the automatic sequential numbering. 
- Following the suggested steps, when adjusting the sunset widget, the app doesn't experience a crash.

Could you try updating to version 4.6.9? 
If that doesn't resolve it, please share a video demonstrating the steps leading to the crash and the profile settings where this occurs.

OsmAnd 4.6.9, released: 2023-12-20

https://github.com/osmandapp/OsmAnd/assets/127092082/1f8dfae0-8bda-41ff-86cf-1e99a398ca2f

**Comment by spaanse** [comment]
Tried in 4.6.9, issue seems resolved
