### ISSUE TITLE
Routing.xml file issue

### ISSUE THREAD

**Issue by groomkrunal** [osmandapp/OsmAnd#18838]
### Description

I have integrated OsmAnd in my app. But as soon as I run the app, I am getting the below error.

Tag Manager is not found and thus will not be used
java.lang.IllegalArgumentException
at org.kxml2.io.KXmlParser.setInput(Unknown Source:294)
at net.osmand.router.RoutingConfiguration.parseFromInputStream(RoutingConfiguration.java:334)
at net.osmand.router.RoutingConfiguration.parseFromInputStream(RoutingConfiguration.java:325)
at net.osmand.router.RoutingConfiguration.getDefault(RoutingConfiguration.java:315)
at com.example.osmsapphire.net.osmand.plus.AppInitializer$2.getDefaultAttributes(AppInitializer.java:477)
at com.example.osmsapphire.net.osmand.plus.AppInitializer$2.doInBackground(AppInitializer.java:438)
at com.example.osmsapphire.net.osmand.plus.AppInitializer$2.doInBackground(AppInitializer.java:434)
at android.os.AsyncTask$3.call(AsyncTask.java:394)
at java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
at java.lang.Thread.run(Thread.java:1012)
Startup service com.example.osmsapphire.IBRouterService took too long 803 ms
Startup service com.example.osmsapphire.net.osmand.plus.routing.RoutingHelper took too long 13 ms

Unexpected error
java.lang.IllegalArgumentException
at org.kxml2.io.KXmlParser.setInput(Unknown Source:294)
at net.osmand.osm.MapPoiTypes.initFromInputStream(MapPoiTypes.java:390)
at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:362)
at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:348)
at com.example.osmsapphire.net.osmand.plus.AppInitializer.initPoiTypes(AppInitializer.java:298)
at com.example.osmsapphire.net.osmand.plus.AppInitializer.startApplicationBackground(AppInitializer.java:535)
at com.example.osmsapphire.net.osmand.plus.AppInitializer.lambda$startApplication$4$com-example-osmsapphire-net-osmand-plus-AppInitializer(AppInitializer.java:783)
at com.example.osmsapphire.net.osmand.plus.AppInitializer$$ExternalSyntheticLambda0.run(Unknown Source:2)

After debugging the code I found that some files like poi_types.xml, regions.ocbf not found.

Can you please help me with this?

### Steps to reproduce

After build the project run the application first time

### Actual result

Application crash

### Expected result

Application will work

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by groomkrunal** [comment]
Hello @vshcherb  can you please check that because we download the latest code and same error occur

**Comment by groomkrunal** [comment]
Hello @vshcherb  any update on this ? It is very important for us to run the project

**Comment by vshcherb** [comment]
I understand it's important for you but we don't see any issue and we don't know which project needs to run

**Comment by groomkrunal** [comment]
Hello @vshcherb we are running the latest version of OSMAnd. And when launch the application it give us error that i describe in my issue.

**Comment by vshcherb** [comment]
I understand though we don't see any issue on our side with nightly builds

**Comment by groomkrunal** [comment]
@vshcherb  can you please provide me stable version of the SDK ? so we can run and check that..

**Comment by groomkrunal** [comment]
Hello @vshcherb  any update on this ?

**Comment by vshcherb** [comment]
No progress so far

**Comment by vshcherb** [comment]
You can reach our marketing department via support, probably they will find a developer that can help you to build. 

As issue not relevant for the project, it will be closed
