### ISSUE TITLE
NB: Add POI + navigation TTS voice => app crash

### ISSUE THREAD

**Issue by Barrocas** [osmandapp/Osmand#1888]
With today night build v2.3.0#14151M, I was adding POI along the way, and it was working fine, but when a TTS voice sounded while I was typing, osmand crashed and restarted.

Exception.log output:
Version  OsmAnd~ 2.3.0#14151M
09.11.2015 10:31:37
Apk Version : 2.3.0#14151M 231
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException
	at net.osmand.plus.osmedit.AdvancedEditPoiFragment$2.onTagsChanged(AdvancedEditPoiFragment.java:113)
	at net.osmand.plus.osmedit.EditPoiData.notifyDatasetChanged(EditPoiData.java:130)
	at net.osmand.plus.osmedit.EditPoiData.putTag(EditPoiData.java:82)
	at net.osmand.plus.osmedit.EditPoiDialogFragment$7.afterTextChanged(EditPoiDialogFragment.java:243)
	at android.widget.TextView.sendAfterTextChanged(TextView.java:7626)
	at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:9424)
	at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:973)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:499)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:437)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:30)
	at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:677)
	at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:199)
	at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:185)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:279)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:77)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5327)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by Barrocas** [comment]
On restart, the navigation resumed as usual, but without rendered map, only turn indications and grey map screen with ruler scale 100m, as when it happens in other bugs, like after a phone call.

Terminating the routing, it zoomed out to display the entire global map.

**Comment by vshcherb** [comment]
Seems to be fixed, if you get it reproduced please attach new crash.
