### ISSUE TITLE
crash when characters higher than \uFFFF are use in osf

### ISSUE THREAD

**Issue by mariush444** [osmandapp/OsmAnd#18936]
### Description

It is not possible to use characters like 🌲 or other where code is higher than \uFFFF 

### Steps to reproduce

create json file 

```
{
  "items": [
    {
      "sql": true,
      "name": "🌲 Database_of_tiles",
      "minZoom": 5,
      "maxZoom": 20,
      "url": "https:\/\/domain.com\/v2\/512\/{$z}\/{$x}\/{$y}\/1_1.png",
      "randoms": "",
      "ellipsoid": false,
      "inverted_y": false,
      "referer": "",
      "userAgent": "",
      "timesupported": true,
      "expire": 10,
      "inversiveZoom": false,
      "ext": ".png",
      "tileSize": 512,
      "bitDensity": 16,
      "avgSize": -1
    },
```

or

```
{
  "version": 1,
  "items": [
    {
      "type": "FILE",
      "file": "\/tiles\/🌲 Database_of_tiles.sqlitedb",
      "subtype": "tiles_map"
    },
```

### Actual result

crash

### Expected result

not crash

### Your Environment (required)

osmand 4.5.10
android 11

Apk Version : 4.5.10 451001
Exception occured in thread Thread[AsyncTask #1,5,main] : 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void net.osmand.plus.api.SQLiteAPI$SQLiteConnection.execSQL(java.lang.String)' on a null object reference
	at net.osmand.plus.resources.SQLiteTileSource.createDataBase(SQLiteTileSource.java:153)
	at net.osmand.plus.settings.backend.backup.items.MapSourcesSettingsItem.apply(MapSourcesSettingsItem.java:123)
	at net.osmand.plus.settings.backend.backup.ImportFileTask.doInBackground(ImportFileTask.java:113)
	at net.osmand.plus.settings.backend.backup.ImportFileTask.doInBackground(ImportFileTask.java:23)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

**Comment by yuriiurshuliak** [comment]
Kindly provide a detailed, step-by-step of the actions you take to reproduce this issue. Additionally, include screenshots or a video recording for better clarity.

**Comment by mariush444** [comment]
I try to prepare video but in mean time I tested the issue on other phone and there were no problem. So probably the problem is tricky.

Try to install attatched plugin.
Osmand crash on galaxy s4 LineageOS (ver. Android 11)
It just closes after click on button `continue`.
It works OK on realme 6 pro Android 11.
[austria.zip](https://github.com/osmandapp/OsmAnd/files/14043567/austria.zip)

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced on Android 12. I downloaded the above plugin and tried to import it into the app, the plugin import was successful. It's crucial to note that issues like this can be device's configurations and can depend on the software.

OsmAnd~ 4.7.0#1435m, released: 2024-01-26


https://github.com/osmandapp/OsmAnd/assets/127092082/a70508fc-b841-4a88-a819-ea9742a40d94

**Comment by mariush444** [comment]
it seems that problem exists bit is related to device or os soft.
