### ISSUE TITLE
Cannot open GPX trace on Moto G (Android 5.1)

### ISSUE THREAD

**Issue by bagage** [osmandapp/Osmand#1901]
While it is working fine on a Samsung S2 running Android 4.1.2, GPX import fails consistenly on Moto G and/or Android 5.1.

I tried, with several different GPX, to:
- put GPX file in `/storage/sdcard0/osmand/tracks/` and open the trace within OsmAnd using `Layer -> GPX track`
- select GPX file within `ES File Explorer` and open it with OsmAnd

Both situations failed similarly with a toast containing:

> 11-11 13:54:25.762  14398-14799/net.osmand E/net.osmand﹕ GPXUtilities Error reading gpx
    org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT
    Une erreur s'e...@3:55 in java.io.InputStreamReader@913857b)
            at org.kxml2.io.KXmlParser.next(KXmlParser.java:432)
            at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
            at net.osmand.plus.GPXUtilities.loadGPXFile(GPXUtilities.java:902)
            at net.osmand.plus.GPXUtilities.loadGPXFile(GPXUtilities.java:868)
            at net.osmand.plus.helpers.GpxUiHelper$8.run(GpxUiHelper.java:421)
            at java.lang.Thread.run(Thread.java:818)

**Comment by vshcherb** [comment]
Something is wrong at the line 3 (symbol 55), we will need more information to understand what to fix. Most likely we will be limited how to fix it, because it is using system provided xml reader.
