### ISSUE TITLE
Crash in Android Auto on ACTION_NAVIGATE intent

### ISSUE THREAD

**Issue by ntruchsess** [osmandapp/OsmAnd#19038]
### Description

When in Android-Auto starting the navigation from a third-party POI-app OSMAnd+ receives the intent and crashes. Using the same functionality with GMaps starts up navigation as expected.

### Steps to reproduce

1) in AA make sure OsmAnd is the most recently used navigation-app.
2) in AA open a third-party POI-app that allows to trigger naviation. E.g. EVMaps (https://github.com/ev-map/EVMap) or EnbW mobility+ (both available in Google Play store).
3) Open a POI in that app and click that navigation-button the app provides.

### Actual result

OsmAnd opens in AA but instead of starting the navigation to the coordinates of the POI being send via ACTION_NAVIGATE intent it crashes.

### Expected result

start OsmAnd and show the coordinates or address that were included in the ACTION_NAVIGATE intent in the search-result panel to start a navigation to that point.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.7.0
Android/iOS version: 12
Device model: Samsung Galaxy S10 (SG973F)
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
Please attach [Crash logs](https://osmand.net/docs/user/troubleshooting/crash-logs) files after application crash: Menu → Help → Send crash log (Send logcat log)

**Comment by ntruchsess** [comment]
crash log:
```
2024-02-07 17:40:09.220 19056-19056 AndroidRuntime          net.osmand.plus                      E  FATAL EXCEPTION: main
                                                                                                    Process: net.osmand.plus, PID: 19056
                                                                                                    java.lang.RuntimeException: java.lang.IllegalArgumentException: Template is in a loading state but a list is set, or vice versa
                                                                                                    	at androidx.car.app.utils.RemoteUtils.lambda$dispatchCallFromHost$0(RemoteUtils.java:155)
                                                                                                    	at androidx.car.app.utils.RemoteUtils$$ExternalSyntheticLambda1.run(Unknown Source:6)
                                                                                                    	at androidx.car.app.utils.ThreadUtils.runOnMain(ThreadUtils.java:39)
                                                                                                    	at androidx.car.app.utils.RemoteUtils.dispatchCallFromHost(RemoteUtils.java:147)
                                                                                                    	at androidx.car.app.utils.RemoteUtils.lambda$dispatchCallFromHost$1(RemoteUtils.java:186)
                                                                                                    	at androidx.car.app.utils.RemoteUtils$$ExternalSyntheticLambda2.run(Unknown Source:8)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8751)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
                                                                                                    Caused by: java.lang.IllegalArgumentException: Template is in a loading state but a list is set, or vice versa
                                                                                                    	at androidx.car.app.navigation.model.PlaceListNavigationTemplate$Builder.build(PlaceListNavigationTemplate.java:493)
                                                                                                    	at net.osmand.plus.auto.screens.SearchResultsScreen.onGetTemplate(SearchResultsScreen.java:73)
                                                                                                    	at androidx.car.app.Screen.getTemplateWrapper(Screen.java:361)
                                                                                                    	at androidx.car.app.ScreenManager.getTopTemplate(ScreenManager.java:279)
                                                                                                    	at androidx.car.app.AppManager$1$$ExternalSyntheticLambda1.dispatch(Unknown Source:2)
                                                                                                    	at androidx.car.app.utils.RemoteUtils.lambda$dispatchCallFromHost$0(RemoteUtils.java:150)
                                                                                                    	at androidx.car.app.utils.RemoteUtils$$ExternalSyntheticLambda1.run(Unknown Source:6) 
                                                                                                    	at androidx.car.app.utils.ThreadUtils.runOnMain(ThreadUtils.java:39) 
                                                                                                    	at androidx.car.app.utils.RemoteUtils.dispatchCallFromHost(RemoteUtils.java:147) 
                                                                                                    	at androidx.car.app.utils.RemoteUtils.lambda$dispatchCallFromHost$1(RemoteUtils.java:186) 
                                                                                                    	at androidx.car.app.utils.RemoteUtils$$ExternalSyntheticLambda2.run(Unknown Source:8) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226) 
                                                                                                    	at android.os.Looper.loop(Looper.java:313) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8751) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 
```

**Comment by ntruchsess** [comment]
my fix in #19039 addresses both issues:
- it accepts the formats that are documented by google: https://developer.android.com/reference/androidx/car/app/CarContext#startCarApp(android.content.Intent)
- if query is empty, coordinates are 0,0 or query just doesn't find any resuls so the itemList in SearchResultsScreen remains null it does provide a default empty itemList with appropriate (and internationalized) location-not-found as title.

**Comment by dmpr0** [comment]
# Review 

<details>
    <summary>Video</summary>
    <table style="width:100%">
      <tr>
        <td><video src="https://github.com/osmandapp/OsmAnd/assets/9365308/e25edb15-6645-403f-9f14-19d7dd76351e"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

<details>
    <summary>Crash</summary>

```
java.lang.RuntimeException: java.lang.UnsupportedOperationException: This isn't a hierarchical URI.
	at androidx.car.app.utils.RemoteUtils.lambda$dispatchCallFromHost$0(RemoteUtils.java:155)
	at androidx.car.app.utils.RemoteUtils$$ExternalSyntheticLambda1.run(Unknown Source:6)
	at androidx.car.app.utils.ThreadUtils.runOnMain(ThreadUtils.java:39)
	at androidx.car.app.utils.RemoteUtils.dispatchCallFromHost(RemoteUtils.java:147)
	at androidx.car.app.utils.RemoteUtils.lambda$dispatchCallFromHost$1(RemoteUtils.java:186)
	at androidx.car.app.utils.RemoteUtils$$ExternalSyntheticLambda2.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.lang.UnsupportedOperationException: This isn't a hierarchical URI.
	at android.net.Uri.getQueryParameter(Uri.java:1718)
	at net.osmand.plus.auto.NavigationSession.onNewIntent(NavigationSession.java:250)
	at androidx.car.app.CarAppService$CarAppBinder.onNewIntentInternal(CarAppService.java:610)
	at androidx.car.app.CarAppService$CarAppBinder.lambda$onNewIntent$5$androidx-car-app-CarAppService$CarAppBinder(CarAppService.java:505)
	at androidx.car.app.CarAppService$CarAppBinder$$ExternalSyntheticLambda3.dispatch(Unknown Source:6)
	at androidx.car.app.utils.RemoteUtils.lambda$dispatchCallFromHost$0(RemoteUtils.java:150)
	... 13 more
```


</details>  

- [ ] Crash [exception (1).log](https://github.com/osmandapp/OsmAnd/files/14330579/exception.1.log)

> Model : Pixel 6a
> Product : bluejay_beta
> Build : AP11.231215.009
> Version : 14
> App Version : OsmAnd~
> Apk Version : 4.7.0#1627m 4700

**Comment by ntruchsess** [comment]
fix is implemented in https://github.com/osmandapp/OsmAnd/pull/19126

**Comment by ntruchsess** [comment]
regression is fixed in https://github.com/osmandapp/OsmAnd/pull/19126

**Comment by Corwin-Kh** [comment]
fixed in https://github.com/osmandapp/OsmAnd/commit/95878b058a5f9b18ce77fcd6b78d45e50b185cbb
