### ISSUE TITLE
Unable to resolve host "osmand.net"

### ISSUE THREAD

**Issue by travnick** [osmandapp/OsmAnd#19388]
### Description

After some time the osmand is installed, I'm unable to see list of available regions, and online map updates are not working too.

I had this few times and reinstalling osmand fixes the issue (but not permanently)

### Steps to reproduce

Hard to say. Install osmand and after a week or two try to show available maps or update online maps.

### Actual result

There is a message (but only on online maps screen. No feedback on "download maps screen" :warning: )
```
Unable to resolve host "osmand.net": No address associated with hostname
```
It looks like some dns/network issues, but I see no issues with other apps.

### Expected result

Have the host resolved, see the available map list, properly update online tiles.

### Your Environment (required)

OsmAnd lives on adopted storage - since not enough main disk space for all my data.

```
OsmAnd Version: 4.6.14 (but seen this before in 4.5 and older)
Android/iOS version: LineageOS 20-20240213-NIGHTLY-Mi8937 (but as far as remember seen also on original Xiaomi OS)
Device model: Xiaomi Redmi 4X
Crash-Logs: logcat:
03-25 09:23:53.568  6367  6367 D net.osmand: PerformLiveUpdateAsyncTask onPreExecute {main}
03-25 09:23:53.569  6367  6530 D net.osmand: PerformLiveUpdateAsyncTask doInBackground {AsyncTask #2}
03-25 09:23:53.576  6367  6530 W System.err: java.net.UnknownHostException: Unable to resolve host "osmand.net": No address associated with hostname
03-25 09:23:53.576  6367  6530 W System.err:    at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
03-25 09:23:53.576  6367  6530 W System.err:    at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
03-25 09:23:53.576  6367  6530 W System.err:    at java.net.InetAddress.getAllByName(InetAddress.java:1152)
03-25 09:23:53.576  6367  6530 W System.err:    at com.android.okhttp.Dns$1.lookup(Dns.java:41)
03-25 09:23:53.576  6367  6530 W System.err:    at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
03-25 09:23:53.576  6367  6530 W System.err:    at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
03-25 09:23:53.577  6367  6530 W System.err:    at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
03-25 09:23:53.577  6367  6530 W System.err:    at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:176)
03-25 09:23:53.577  6367  6530 W System.err:    at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
03-25 09:23:53.577  6367  6530 W System.err:    at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
03-25 09:23:53.577  6367  6530 W System.err:    at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
03-25 09:23:53.577  6367  6530 W System.err:    at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
03-25 09:23:53.577  6367  6530 W System.err:    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
03-25 09:23:53.577  6367  6530 W System.err:    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
03-25 09:23:53.577  6367  6530 W System.err:    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
03-25 09:23:53.577  6367  6530 W System.err:    at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
03-25 09:23:53.577  6367  6530 W System.err:    at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
03-25 09:23:53.577  6367  6530 W System.err:    at net.osmand.plus.resources.IncrementalChangesManager.getIncrementalUpdates(IncrementalChangesManager.java:321)
03-25 09:23:53.577  6367  6530 W System.err:    at net.osmand.plus.resources.IncrementalChangesManager.getUpdatesByMonth(IncrementalChangesManager.java:356)
03-25 09:23:53.577  6367  6530 W System.err:    at net.osmand.plus.liveupdates.PerformLiveUpdateAsyncTask.doInBackground(PerformLiveUpdateAsyncTask.java:83)
03-25 09:23:53.577  6367  6530 W System.err:    at net.osmand.plus.liveupdates.PerformLiveUpdateAsyncTask.doInBackground(PerformLiveUpdateAsyncTask.java:42)
03-25 09:23:53.577  6367  6530 W System.err:    at android.os.AsyncTask$3.call(AsyncTask.java:394)
03-25 09:23:53.577  6367  6530 W System.err:    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
03-25 09:23:53.577  6367  6530 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
03-25 09:23:53.577  6367  6530 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
03-25 09:23:53.577  6367  6530 W System.err:    at java.lang.Thread.run(Thread.java:1012)
03-25 09:23:53.578  6367  6530 W System.err: Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
03-25 09:23:53.578  6367  6530 W System.err:    at libcore.io.Linux.android_getaddrinfo(Native Method)
03-25 09:23:53.578  6367  6530 W System.err:    at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
03-25 09:23:53.578  6367  6530 W System.err:    at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:222)
03-25 09:23:53.578  6367  6530 W System.err:    at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
03-25 09:23:53.578  6367  6530 W System.err:    at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
03-25 09:23:53.578  6367  6530 W System.err:    ... 25 more
03-25 09:23:53.578  6367  6530 E net.osmand: IncrementalChangesManager Unable to resolve host "osmand.net": No address associated with hostname {AsyncTask #2}
03-25 09:23:53.613  6367  6367 I net.osmand: PerformLiveUpdateAsyncTask Error message: Unable to resolve host "osmand.net": No address associated with hostname {main}
```

**Comment by vshcherb** [comment]
Looks like a firewall blocks, osmand.net works fine as I see

**Comment by travnick** [comment]
But `ping osmand.net` works fine on the phone, so I see no firewall here to block the traffic.
And strange thing is that reinstalling osmand fixes the issue for a short time, and then it's broken again.

**Comment by scaidermern** [comment]
Did you enable a proxy in the OsmAnd settings? Not sure if the error message would be the same one.
Are you using any VPN on your device?

**Comment by travnick** [comment]
no VPN, proxy also disabled. Do you mean to enable the proxy and check?

**Comment by scaidermern** [comment]
No, I didn't. Just wanted to make sure it wasn't enabled by accident.

**Comment by moon161** [comment]
I also don't load regions on all versions older than version 3.2.7. Android 7 device

**Comment by sonora** [comment]
I see you're running a LineageOS nightly... perhaps it foes something strange, like removing the network access permission for the OsmAnd app, activating the data saver, etc. Perhaps check in Settings/Apps/OsmAnd when it occurs.

**Comment by moon161** [comment]
> Я вижу, что вы используете LineageOS каждую ночь... возможно, он делает что-то странное, например, через некоторое время удаляет разрешение на доступ к сети для приложения OsmAnd, активирует функцию сохранения данных и т. д. Возможно, проверьте Настройки/Приложения/OsmAnd, когда это произойдет. .

Excuse me, how did you see that? I think it's a good idea, but not for someone to solve the osmand problem. Huawei mediapad m3 lite device, Android 7

**Comment by travnick** [comment]
@sonora 
It may be, since Lineage OS is quite restrictive and takes off permissions for unused apps, but I did check, and it had the network permission (as far as LineageOS GUI does not lie to me). Anyway, I'll try to be more focused on that.

Right now also have OEM Android One, so I'll see how both behave.
Are there any debugging things to do to have more details about the issue?

**Comment by sonora** [comment]
You can turn on the Development plugin and provide a logcat.log file here (via its Logcat buffer Settings item), perhaps it would reveal more details on what's going on.
