### ISSUE TITLE
Crash when disabling GPS

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#19429]
### Description

OsmAnd crashed shortly after disabling location services (GPS).

### Steps to reproduce

* Let OsmAnd determine the position
* Disable GPS
* Crash

I tried to reproduce it but didn't succeed.

### Actual result

Crash

### Expected result

No Crash

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.7.4
Android/iOS version: Android 10
Device model: Samsung S9
Crash-Logs:

Version  OsmAnd+ 4.7.4
30.03.2024 7:25:08
Apk Version : 4.7.4 4704
Exception occurred in thread Thread[main,5,main] : 
java.lang.AbstractMethodError: abstract method "void android.location.LocationListener.onProviderDisabled(java.lang.String)"
        at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:365)
        at android.location.LocationManager$ListenerTransport.access$000(LocationManager.java:275)
        at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:291)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

**Comment by DmitryAlexei** [comment]
may be related https://issuetracker.google.com/issues/190695723?pli=1
