### ISSUE TITLE
Crash NullPointerException: Attempt to invoke virtual method 'boolean com.google.protobuf.CodedInputStream.skipField(int)' on a null object reference

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#19473]
### Description

While downloading an update for a map and panning/zooming at the same time, a crash occurred.

### Steps to reproduce

:shr

### Actual result

Crash.

### Expected result

No crash.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.7.4
Android/iOS version: Android 10
Device model: Samsung S9
Crash-Logs:

Version  OsmAnd+ 4.7.4
04.04.2024 10:37:33
Apk Version : 4.7.4 4704
Exception occurred in thread Thread[AsyncTask #12,5,main] : 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.protobuf.CodedInputStream.skipField(int)' on a null object reference
	at net.osmand.binary.BinaryMapIndexReader.skipUnknownField(BinaryMapIndexReader.java:533)
	at net.osmand.binary.BinaryMapPoiReaderAdapter.skipUnknownField(BinaryMapPoiReaderAdapter.java:139)
	at net.osmand.binary.BinaryMapPoiReaderAdapter.checkCategories(BinaryMapPoiReaderAdapter.java:900)
	at net.osmand.binary.BinaryMapPoiReaderAdapter.readBoxField(BinaryMapPoiReaderAdapter.java:940)
	at net.osmand.binary.BinaryMapPoiReaderAdapter.readBoxField(BinaryMapPoiReaderAdapter.java:968)
	at net.osmand.binary.BinaryMapPoiReaderAdapter.readBoxField(BinaryMapPoiReaderAdapter.java:968)
	at net.osmand.binary.BinaryMapPoiReaderAdapter.readBoxField(BinaryMapPoiReaderAdapter.java:968)
	at net.osmand.binary.BinaryMapPoiReaderAdapter.readBoxField(BinaryMapPoiReaderAdapter.java:968)
	at net.osmand.binary.BinaryMapPoiReaderAdapter.readBoxField(BinaryMapPoiReaderAdapter.java:968)
	at net.osmand.binary.BinaryMapPoiReaderAdapter.readBoxField(BinaryMapPoiReaderAdapter.java:968)
	at net.osmand.binary.BinaryMapPoiReaderAdapter.readBoxField(BinaryMapPoiReaderAdapter.java:968)
	at net.osmand.binary.BinaryMapPoiReaderAdapter.readBoxField(BinaryMapPoiReaderAdapter.java:968)
	at net.osmand.binary.BinaryMapPoiReaderAdapter.searchPoiIndex(BinaryMapPoiReaderAdapter.java:525)
	at net.osmand.binary.BinaryMapIndexReader.searchPoi(BinaryMapIndexReader.java:1458)
	at net.osmand.plus.resources.AmenityIndexRepositoryBinary.searchAmenities(AmenityIndexRepositoryBinary.java:187)
	at net.osmand.plus.resources.ResourceManager.searchAmenities(ResourceManager.java:1195)
	at net.osmand.plus.resources.ResourceManager.searchAmenities(ResourceManager.java:1173)
	at net.osmand.plus.track.helpers.GpxReaderTask.searchNearestCity(GpxReaderTask.java:141)
	at net.osmand.plus.track.helpers.GpxReaderTask.checkAndSearchNearestCity(GpxReaderTask.java:131)
	at net.osmand.plus.track.helpers.GpxReaderTask.setupNearestCityName(GpxReaderTask.java:121)
	at net.osmand.plus.track.helpers.GpxReaderTask.doInBackground(GpxReaderTask.java:91)
	at net.osmand.plus.track.helpers.GpxReaderTask.doInBackground(GpxReaderTask.java:37)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
```

**Comment by Dima-1** [comment]
Can you clarify which map was downloading and the approximate coordinates of panning/zooming

**Comment by scaidermern** [comment]
> Can you clarify which map was downloading and the approximate coordinates of panning/zooming

I can only give a rough estimate. I think I downloaded an update of the Saxony map and panned around somewhere in North Rhine-Westphalia (where the area of Saxony is definitely _not_ visible).

**Comment by vshcherb** [comment]
Likely it's concurrency issue when map is being reindexed but hard to catch...
