### ISSUE TITLE
Crash NullPointerException: Attempt to invoke virtual method 'void com.google.protobuf.CodedInputStream.seek(long)' on a null object reference 

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#19487]
### Description

OsmAnd crashed while deactivating a map. 

### Steps to reproduce

🤷‍♂️

### Actual result

Crash 

### Expected result

No crash 

### Your Environment (required)

```
OsmAnd Version: 4.7.6
Android/iOS version: Android 10
Device model: Samsung S9
Crash-Logs:

Version  OsmAnd+ 4.7.6
06.04.2024 10:25:59
Apk Version : 4.7.6 4706
Exception occurred in thread Thread[AsyncTask #7,5,main] : 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.protobuf.CodedInputStream.seek(long)' on a null object reference
	at net.osmand.binary.BinaryMapIndexReader.searchPoi(BinaryMapIndexReader.java:1479)
	at net.osmand.plus.resources.AmenityIndexRepositoryBinary.searchAmenities(AmenityIndexRepositoryBinary.java:187)
	at net.osmand.plus.resources.ResourceManager.searchAmenities(ResourceManager.java:1198)
	at net.osmand.plus.resources.ResourceManager.searchAmenities(ResourceManager.java:1176)
	at net.osmand.plus.track.helpers.GpxReaderTask.searchNearestCity(GpxReaderTask.java:141)
	at net.osmand.plus.track.helpers.GpxReaderTask.checkAndSearchNearestCity(GpxReaderTask.java:131)
	at net.osmand.plus.track.helpers.GpxReaderTask.setupNearestCityName(GpxReaderTask.java:121)
	at net.osmand.plus.track.helpers.GpxReaderTask.doInBackground(GpxReaderTask.java:91)
	at net.osmand.plus.track.helpers.GpxReaderTask.doInBackground(GpxReaderTask.java:37)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
```

**Comment by vshcherb** [comment]
Same as previous, there is ongoing task of detecting city names for GPX and as it runs concurrently it crashes with map operations. I think once we figure out what causes GPX to reindex and fix it, that issue will be irrelevant

**Comment by scaidermern** [comment]
The same crash happened again while updating Wikipedia maps.

@vshcherb I never had these crashes with version <= 4.7.4. So I guess they must be caused by changes in 4.7.5 or 4.7.6.

**Comment by vshcherb** [comment]
That looks like a bug with GPX indexing we have a task to change it. Something like Force stop ... 

I just think it's a connected / duplicate to https://github.com/osmandapp/OsmAnd/issues/19151

**Comment by vshcherb** [comment]
Probably fixed by https://github.com/osmandapp/OsmAnd/issues/19151 needs to be tested
