### ISSUE TITLE
Search then crash

### ISSUE THREAD

**Issue by mariush444** [osmandapp/OsmAnd#19494]
### Description

I just search for string "BABYLONIAN THEATRE" then click for the 1st lime proposed by osmand then the apk crashed.
I tested twice.

### Steps to reproduce

above. I use current Iraq map 01.04.2024

### Actual result

Crash

### Expected result

not crash

### Your Environment (required)

Version  OsmAnd~ 4.5.10
07.04.2024 7:42:33
Apk Version : 4.5.10 451003
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalArgumentException: URLDecoder: Incomplete trailing escape (%) pattern
	at java.net.URLDecoder.decode(URLDecoder.java:196)
	at net.osmand.plus.mapcontextmenu.builders.AmenityMenuBuilder.getDecodedAdditionalInfo(AmenityMenuBuilder.java:234)
	at net.osmand.plus.mapcontextmenu.builders.AmenityMenuBuilder.getAdditionalCardParams(AmenityMenuBuilder.java:218)
	at net.osmand.plus.mapcontextmenu.MenuBuilder.startLoadingImagesTask(MenuBuilder.java:525)
	at net.osmand.plus.mapcontextmenu.MenuBuilder.startLoadingImages(MenuBuilder.java:519)
	at net.osmand.plus.mapcontextmenu.MenuBuilder.buildNearestPhotosRow(MenuBuilder.java:485)
	at net.osmand.plus.mapcontextmenu.MenuBuilder.build(MenuBuilder.java:306)
	at net.osmand.plus.mapcontextmenu.MenuController.build(MenuController.java:174)
	at net.osmand.plus.mapcontextmenu.MapContextMenu.build(MapContextMenu.java:1334)
	at net.osmand.plus.mapcontextmenu.MapContextMenuFragment.buildBottomView(MapContextMenuFragment.java:1320)
	at net.osmand.plus.mapcontextmenu.MapContextMenuFragment.onCreateView(MapContextMenuFragment.java:589)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
	at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:254)
	at android.app.ActivityThread.main(ActivityThread.java:8243)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. Attempt to download the map of Iraq and search for the Babylonian theater. Clicking on the search result will cause the application to crash.

[exception (8).log](https://github.com/osmandapp/OsmAnd/files/14907224/exception.8.log)
OsmAnd~ 4.7.0#2017m, released: 2024-04-08

https://github.com/osmandapp/OsmAnd/assets/127092082/7edf7839-7d66-4693-acad-87999ec94609

**Comment by Chumva** [comment]
Looks like the main reason for this crash was in broken link. 
Android got the link https://upload.wikimedia.org/wikipedia/commons/7/71/%D8%A7%D9%84%D9%85%D8%B3%D8%B1%D8%AD_%D8%A7%D9%84%D8%A8%D8%A7%D8%A8%D9%84%D9%8A_%D9%81%D9%8A_%D9%85%D8%AF%D9%8A%D9%86%D8%A9_%D8%A8%D8%A7%D8%A8%D9%84_%D8%A7%D9%84%D8%A7%D8%AB%D8%B1%D9%8A%D8%A9_%D9%81%D9%8 

instead of https://upload.wikimedia.org/wikipedia/commons/7/71/%D8%A7%D9%84%D9%85%D8%B3%D8%B1%D8%AD_%D8%A7%D9%84%D8%A8%D8%A7%D8%A8%D9%84%D9%8A_%D9%81%D9%8A_%D9%85%D8%AF%D9%8A%D9%86%D8%A9_%D8%A8%D8%A7%D8%A8%D9%84_%D8%A7%D9%84%D8%A7%D8%AB%D8%B1%D9%8A%D8%A9_%D9%81%D9%8A_%D9%85%D8%AD%D8%A7%D9%81%D8%B8%D8%A9_%D8%A8%D8%A7%D8%A8%D9%84_%D8%A7%D9%84%D8%B9%D8%B1%D8%A7%D9%82%D9%8A%D8%A9.jpg

**Comment by yuriiurshuliak** [comment]
The bug has been fixed. After trying to find Babylon Theater, clicking on the search result does not cause the app to crash.

OsmAnd~ 4.7.0#2031m, released: 2024-04-10

https://github.com/osmandapp/OsmAnd/assets/127092082/7b26ce40-815d-44df-b402-b566c749bc9f
