### ISSUE TITLE
4.7.8 keeps crashing

### ISSUE THREAD

**Issue by MarioSwitch** [osmandapp/OsmAnd#19535]
### Description

After updated OsmAnd from 4.7.7 to 4.7.8, the app keeps crashing.

### Steps to reproduce

Update the app to 4.7.8 and open it

### Actual result

The app crashes

### Expected result

The app works

### Your Environment (required)

OsmAnd Version: 4.7.8
Android/iOS version: Android 14
Device model: Google Pixel 7

# Crash-Logs
```
Version  OsmAnd 4.7.8
13.04.2024 8:55:08
Apk Version : 4.7.8 4708
Exception occurred in thread Thread[AsyncTask #2,5,main] : 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.database.sqlite.SQLiteException: no such column: totalDistance (code 1 SQLITE_ERROR): , while compiling: UPDATE gpxDirTable SET fileName = ?, fileDir = ?, totalDistance = ?, totalTracks = ?, startTime = ?, endTime = ?, timeSpan = ?, expectedRouteDuration = ?, timeMoving = ?, totalDistanceMoving = ?, diffElevationUp = ?, diffElevationDown = ?, avgElevation = ?, minElevation = ?, maxElevation = ?, minSpeed = ?, maxSpeed = ?, avgSpeed = ?, points = ?, wptPoints = ?, color = ?, fileLastModifiedTime = ?, fileLastUploadedTime = ?, fileCreationTime = ?, splitType = ?, splitInterval = ?, apiImported = ?, wptCategoryNames = ?, showAsMarkers = ?, joinSegments = ?, showArrows = ?, showStartFinish = ?, use3dTrackVisualization = ?, width = ?, gradientScaleType = ?, smoothingThreshold = ?, minFilterSpeed = ?, maxFilterSpeed = ?, minFilterAltitude = ?, maxFilterAltitude = ?, maxFilterHdop = ?, startLat = ?, startLon = ?, nearestCityName = ?, maxSensorTemperature = ?, avgSensorTemperature = ?, maxSensorSpeed = ?, avgSensorSpeed = ?, maxSensorPower = ?, avgSensorPower = ?, maxSensorCadence = ?, avgSensorCadence = ?, maxSensorHr = ?, avgSensorHr = ?, dataVersion = ? WHERE fileName = ? AND fileDir = ?
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.-$$Nest$smnativePrepareStatement(Unknown Source:0)
	at android.database.sqlite.SQLiteConnection$PreparedStatementCache.createStatement(SQLiteConnection.java:1552)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatementLI(SQLiteConnection.java:1095)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1123)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:683)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:614)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:62)
	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:34)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2201)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2178)
	at net.osmand.plus.api.SQLiteAPIImpl$SQLiteDatabaseWrapper.execSQL(SQLiteAPIImpl.java:133)
	at net.osmand.plus.track.helpers.GPXDatabase.updateGpxParameters(GPXDatabase.java:132)
	at net.osmand.plus.track.helpers.GPXDatabase.updateGpxParameters(GPXDatabase.java:118)
	at net.osmand.plus.track.helpers.GPXDatabase.updateDataItem(GPXDatabase.java:110)
	at net.osmand.plus.track.helpers.GpxDbHelper.updateDataItem(GpxDbHelper.java:142)
	at net.osmand.plus.track.helpers.GpxReaderTask.doInBackground(GpxReaderTask.java:94)
	at net.osmand.plus.track.helpers.GpxReaderTask.doInBackground(GpxReaderTask.java:38)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more
```

**Comment by vshcherb** [comment]
Fixed https://github.com/osmandapp/OsmAnd/commit/2ce1b9795ff6f5d53f2c0d56398ba9ebefed4f02

**Comment by vshcherb** [comment]
Please try with https://download.osmand.net/latest-night-build/ (they are signed as release version and should be updateable) as 4.7.8

**Comment by Nine-Tailed** [comment]
```
Version  OsmAnd~ 4.7.N#2069m
14.04.2024 1:18:24
Apk Version : 4.7.N#2069m 4708
Exception occurred in thread Thread[AsyncTask #3,5,main] : 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.database.sqlite.SQLiteException: table gpxDirTable has no column named totalDistance (code 1 SQLITE_ERROR): , while compiling: INSERT INTO gpxDirTable (fileName, fileDir, totalDistance, totalTracks, startTime, endTime, timeSpan, expectedRouteDuration, timeMoving, totalDistanceMoving, diffElevationUp, diffElevationDown, avgElevation, minElevation, maxElevation, minSpeed, maxSpeed, avgSpeed, points, wptPoints, color, fileLastModifiedTime, fileLastUploadedTime, fileCreationTime, splitType, splitInterval, apiImported, wptCategoryNames, showAsMarkers, joinSegments, showArrows, showStartFinish, use3dTrackVisualization, width, gradientScaleType, smoothingThreshold, minFilterSpeed, maxFilterSpeed, minFilterAltitude, maxFilterAltitude, maxFilterHdop, startLat, startLon, nearestCityName, maxSensorTemperature, avgSensorTemperature, maxSensorSpeed, avgSensorSpeed, maxSensorPower, avgSensorPower, maxSensorCadence, avgSensorCadence, maxSensorHr, avgSensorHr, dataVersion) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1068)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:673)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:62)
	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:34)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2086)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2064)
	at net.osmand.plus.api.SQLiteAPIImpl$SQLiteDatabaseWrapper.execSQL(SQLiteAPIImpl.java:133)
	at net.osmand.plus.track.helpers.GPXDatabase.insertItem(GPXDatabase.java:178)
	at net.osmand.plus.track.helpers.GpxReaderTask.doInBackground(GpxReaderTask.java:98)
	at net.osmand.plus.track.helpers.GpxReaderTask.doInBackground(GpxReaderTask.java:38)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more

```

**Comment by pebogufi** [comment]
@vshcherb 
Again Crash with

OsmAnd~ 4.7.N#2069m, veröffentlicht: 2024-04-13
[exception.log.zip](https://github.com/osmandapp/OsmAnd/files/14969814/exception.log.zip)

**Comment by alex-osm** [comment]
@pebogufi Please check last nightly version (2073)

**Comment by Nine-Tailed** [comment]
Now works without crashing.

**Comment by pebogufi** [comment]
Me too, confirm fixed. Thanks a lot.
