### ISSUE TITLE
Upload of OSM hints fails with no reason given

### ISSUE THREAD

**Issue by sjvudp** [osmandapp/OsmAnd#19557]
### Description

Today I collected some updates usin OsmAnd and StreetComplete (both have adavntages and disadvantages compared to each other). I was logged in to OSM via Web browser from my PC when I tried to upload the OSM changes (as I did before).
However this time it just brought a failure message after a few seconds saying 0 updates were uploaded.
I retried two or three times, but it still failed with no reason given.
Then I tried to upload the Street Complete updates, and they worked.
So I assume it's not the OSM service that has the problem.

### Steps to reproduce

Upload OSM changes (116)

### Actual result

Upload progress does not make any progress for a few seconds, then summarizes as "Uploaded 0/116" with no reason given

### Expected result

Upload should succeed, or a reason for the failure should be shown

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.7.7.4707
Android/iOS version: 13
Device model: CPH2371
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
Duplicate of #https://github.com/osmandapp/OsmAnd/issues/19148

**Comment by sjvudp** [comment]
> Duplicate of ##19148

I disagree, because the situation is different: I have WLAN/Internet, but the transfer does not even start.
In addition I realized that also the updates of OSM maps are no longer possible, so I suspect an authentication issue with OSM.
Finally Google Play says the app was updated 4 days ago, so I suspect that the current version introduced a bug (I had no issues with the previous version)!

Digging in the logcat, this might be helpful:
```
04-15 13:24:00.848 24174 24174 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
04-15 13:24:00.867 24174 24174 I Quality : Skipped: false 3 cost 52.200783 refreshRate 16666667 bit true processName net.osmand
04-15 13:24:00.868 24174 24174 E OplusBracketLog: [OplusViewMirrorManager] updateHostViewRootIfNeeded, not support android.view.ViewRootImpl@4515d4f
04-15 13:24:00.889 24174 24174 E IPCThreadState: attemptIncStrongHandle(102): Not supported
04-15 13:24:00.904 24174  2202 W Parcel  : Expecting binder but got null!
04-15 13:24:00.939 24174 24174 I Quality : Skipped: false 2 cost 39.622368 refreshRate 16752319 bit true processName net.osmand
04-15 13:24:01.099 24174  3097 I net.osmand: OsmBugsRemoteUtil Unauthorized {AsyncTask #4}
04-15 13:24:01.100 24174  3097 E net.osmand: OsmBugsRemoteUtil Validating login failed {AsyncTask #4}
04-15 13:24:01.100 24174  3097 E net.osmand: java.io.FileNotFoundException: https://api.openstreetmap.org/api/0.6/user/details
04-15 13:24:01.100 24174  3097 E net.osmand: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
04-15 13:24:01.100 24174  3097 E net.osmand: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
04-15 13:24:01.100 24174  3097 E net.osmand: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
04-15 13:24:01.100 24174  3097 E net.osmand: 	at net.osmand.plus.plugins.osmedit.helpers.OsmBugsRemoteUtil.performBasicRequest(OsmBugsRemoteUtil.java:162)
04-15 13:24:01.100 24174  3097 E net.osmand: 	at net.osmand.plus.plugins.osmedit.helpers.OsmBugsRemoteUtil.editingPOI(OsmBugsRemoteUtil.java:129)
04-15 13:24:01.100 24174  3097 E net.osmand: 	at net.osmand.plus.plugins.osmedit.helpers.OsmBugsRemoteUtil.validateLoginDetails(OsmBugsRemoteUtil.java:114)
04-15 13:24:01.100 24174  3097 E net
21:08
.osmand: 	at net.osmand.plus.plugins.osmedit.helpers.OsmBugsRemoteUtil.commit(OsmBugsRemoteUtil.java:105)
04-15 13:24:01.100 24174  3097 E net.osmand: 	at net.osmand.plus.plugins.osmedit.asynctasks.UploadOpenstreetmapPointAsyncTask.doInBackground(UploadOpenstreetmapPointAsyncTask.java:83)
04-15 13:24:01.100 24174  3097 E net.osmand: 	at net.osmand.plus.plugins.osmedit.asynctasks.UploadOpenstreetmapPointAsyncTask.doInBackground(UploadOpenstreetmapPointAsyncTask.java:23)
04-15 13:24:01.100 24174  3097 E net.osmand: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
04-15 13:24:01.100 24174  3097 E net.osmand: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
04-15 13:24:01.100 24174  3097 E net.osmand: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
04-15 13:24:01.100 24174  3097 E net.osmand: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
04-15 13:24:01.100 24174  3097 E net.osmand: 	at java.lang.Thread.run(Thread.java:1012)
04-15 13:24:01.176 24174 24174 W OnBackInvokedCallback: OnBackInvokedCallback is not enabled for the application.
04-15 13:24:01.176 24174 24174 W OnBackInvokedCallback: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
04-15 13:24:01.178 24174 24174 I Quality : Skipped: false 3 cost 60.944992 refreshRate 16748438 bit true processName net.osmand
```

**Comment by yuriiurshuliak** [comment]
Could you please confirm whether you attempted to log in using OAuth method instead of entering your username and password directly?

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/6eef97f9-fa73-434f-829a-bae400a61698"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by sjvudp** [comment]
> Could you please confirm whether you attempted to log in using OAuth method instead of entering your username and password directly?

Honestly I did never think about which authentication method had been used as long as it worked. AFAIR I had entered username and password once, thinking the app will remember it in some safe memory.

When it stopped to work I tried both options, realizing that "username and password" seemed not to remember what I had entered, so I entered the credentials again. Still it did not help. And most up-to-date: The recent version 4.7.9 also did not fix the problem.

Back to the question:
When I select "Sign in with OpenStreetMap", I'm prompted for username and password, so I guessed it's the same as "Use username and password".

When I repeated the procedure (first option), I was redirected to a web browser to perform OSM login, then some Google dialog would ask whether to store the credentials "in Google" which I denied. Then another confirmation dialog asking for site permissions, and eventually the browser asked whether to switch to another app (I agreed).

After that the difference was the the lower part of the dialog (Login to OpenStreetMap.org) is no longer displayed.
And it seems I'm connected to OSM again!
To me this also means the OsmAnd has lost my credentials somehow, but didn't really say so.
Glad to see my 1082 OSM contributions for the last two months again ;-)

**Comment by yuriiurshuliak** [comment]
It is likely that the issue is related to a change in the OpenStreetMap authentication method. You can refer to the following link for more details: [OpenStreetMap Authentication Change](https://community.openstreetmap.org/t/oauth-1-0a-and-http-basic-auth-shutdown/108490).

Could you please confirm if your problem has been resolved since then?

**Comment by sjvudp** [comment]
The problem, if seen as "unable to access OSM", can be considered as solved; however the problem that a "connection to OSM fails without a reason given" is still not considered to be solved. The discussion about OAuth _versions_, _access_ and _refresh tokens_ isn't really helpful at the user level, specifically as there is no display in OsmAnd that would display the actual authentication method being used (AFAIK).
