### ISSUE TITLE
Crash after updating to 4.7.8

### ISSUE THREAD

**Issue by pranatahouse** [osmandapp/OsmAnd#19550]
### Description

this is happening only after updating to 4.7.8.

### Steps to reproduce

1. update the app from play store
2. open the app 

### Actual result

crash 

### Expected result

the app open normally 

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.7.8
Android/iOS version: android 13
Device model: redmi note 11
Crash-Logs: ?
```
Version  OsmAnd 4.7.8
13.04.2024 8:22:09
Apk Version : 4.7.8 4708
Exception occurred in thread Thread[AsyncTask #4,5,main] : 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.database.sqlite.SQLiteException: no such column: totalDistance (code 1 SQLITE_ERROR[1]): , while compiling: UPDATE gpxDirTable SET fileName = ?, fileDir = ?, totalDistance = ?, totalTracks = ?, startTime = ?, endTime = ?, timeSpan = ?, expectedRouteDuration = ?, timeMoving = ?, totalDistanceMoving = ?, diffElevationUp = ?, diffElevationDown = ?, avgElevation = ?, minElevation = ?, maxElevation = ?, minSpeed = ?, maxSpeed = ?, avgSpeed = ?, points = ?, wptPoints = ?, color = ?, fileLastModifiedTime = ?, fileLastUploadedTime = ?, fileCreationTime = ?, splitType = ?, splitInterval = ?, apiImported = ?, wptCategoryNames = ?, showAsMarkers = ?, joinSegments = ?, showArrows = ?, showStartFinish = ?, use3dTrackVisualization = ?, width = ?, gradientScaleType = ?, smoothingThreshold = ?, minFilterSpeed = ?, maxFilterSpeed = ?, minFilterAltitude = ?, maxFilterAltitude = ?, maxFilterHdop = ?, startLat = ?, startLon = ?, nearestCityName = ?, maxSensorTemperature = ?, avgSensorTemperature = ?, maxSensorSpeed = ?, avgSensorSpeed = ?, maxSensorPower = ?, avgSensorPower = ?, maxSensorCadence = ?, avgSensorCadence = ?, maxSensorHr = ?, avgSensorHr = ?, dataVersion = ? WHERE fileName = ? AND fileDir = ?
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1540)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:975)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:63)
	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:34)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2652)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2630)
	at net.osmand.plus.api.SQLiteAPIImpl$SQLiteDatabaseWrapper.execSQL(SQLiteAPIImpl.java:133)
	at net.osmand.plus.track.helpers.GPXDatabase.updateGpxParameters(GPXDatabase.java:132)
	at net.osmand.plus.track.helpers.GPXDatabase.updateGpxParameters(GPXDatabase.java:118)
	at net.osmand.plus.track.helpers.GPXDatabase.updateDataItem(GPXDatabase.java:110)
	at net.osmand.plus.track.helpers.GpxDbHelper.updateDataItem(GpxDbHelper.java:142)
	at net.osmand.plus.track.helpers.GpxReaderTask.doInBackground(GpxReaderTask.java:94)
	at net.osmand.plus.track.helpers.GpxReaderTask.doInBackground(GpxReaderTask.java:38)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more
Version  OsmAnd 4.7.8
13.04.2024 8:22:37
Apk Version : 4.7.8 4708
Exception occurred in thread Thread[AsyncTask #3,5,main] : 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.database.sqlite.SQLiteException: no such column: totalDistance (code 1 SQLITE_ERROR[1]): , while compiling: UPDATE gpxDirTable SET fileName = ?, fileDir = ?, totalDistance = ?, totalTracks = ?, startTime = ?, endTime = ?, timeSpan = ?, expectedRouteDuration = ?, timeMoving = ?, totalDistanceMoving = ?, diffElevationUp = ?, diffElevationDown = ?, avgElevation = ?, minElevation = ?, maxElevation = ?, minSpeed = ?, maxSpeed = ?, avgSpeed = ?, points = ?, wptPoints = ?, color = ?, fileLastModifiedTime = ?, fileLastUploadedTime = ?, fileCreationTime = ?, splitType = ?, splitInterval = ?, apiImported = ?, wptCategoryNames = ?, showAsMarkers = ?, joinSegments = ?, showArrows = ?, showStartFinish = ?, use3dTrackVisualization = ?, width = ?, gradientScaleType = ?, smoothingThreshold = ?, minFilterSpeed = ?, maxFilterSpeed = ?, minFilterAltitude = ?, maxFilterAltitude = ?, maxFilterHdop = ?, startLat = ?, startLon = ?, nearestCityName = ?, maxSensorTemperature = ?, avgSensorTemperature = ?, maxSensorSpeed = ?, avgSensorSpeed = ?, maxSensorPower = ?, avgSensorPower = ?, maxSensorCadence = ?, avgSensorCadence = ?, maxSensorHr = ?, avgSensorHr = ?, dataVersion = ? WHERE fileName = ? AND fileDir = ?
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1540)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:975)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:63)
	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:34)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2652)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2630)
	at net.osmand.plus.api.SQLiteAPIImpl$SQLiteDatabaseWrapper.execSQL(SQLiteAPIImpl.java:133)
	at net.osmand.plus.track.helpers.GPXDatabase.updateGpxParameters(GPXDatabase.java:132)
	at net.osmand.plus.track.helpers.GPXDatabase.updateGpxParameters(GPXDatabase.java:118)
	at net.osmand.plus.track.helpers.GPXDatabase.updateDataItem(GPXDatabase.java:110)
	at net.osmand.plus.track.helpers.GpxDbHelper.updateDataItem(GpxDbHelper.java:142)
	at net.osmand.plus.track.helpers.GpxReaderTask.doInBackground(GpxReaderTask.java:94)
	at net.osmand.plus.track.helpers.GpxReaderTask.doInBackground(GpxReaderTask.java:38)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more

**Comment by gosgtan** [comment]
exact same problem!

**Comment by DmitryAlexei** [comment]
As a workaround. Please try Nigtly build https://download.osmand.net/latest-night-build/ (they are signed as release version and should be updatable) as 4.7.8

**Comment by DmitryAlexei** [comment]
Probably duplicate or related https://github.com/osmandapp/OsmAnd/issues/19535

**Comment by pranatahouse** [comment]
oh sorry, i was trying to search it but couldn't find the issue. thanks for the fix anyway.
