### ISSUE TITLE
Crash Attempt to invoke virtual method 'int net.osmand.plus.track.Gpx3DVisualizationType.ordinal()' on a null object reference 

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#19696]
### Description

A crash occured when trying to change the appearance of a track. 

### Steps to reproduce

Create a new track via plan a route. Save. Tap on it, tap on the appearance icon. Crash. 

### Actual result

Crash. 

### Expected result

No crash. 

### Your Environment (required)

```
OsmAnd Version: 4.7.12
Android/iOS version: Android 10
Device model:
Crash-Logs:
Version  OsmAnd+ 4.7.12
29.04.2024 12:30:31
Apk Version : 4.7.12 4712
Exception occurred in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'int net.osmand.plus.track.Gpx3DVisualizationType.ordinal()' on a null object reference
	at net.osmand.plus.track.cards.Track3DCard.updateContent(Track3DCard.java:125)
	at net.osmand.plus.routepreparationmenu.cards.BaseCard.update(BaseCard.java:86)
	at net.osmand.plus.track.cards.Track3DCard.build(Track3DCard.java:106)
	at net.osmand.plus.track.fragments.TrackAppearanceFragment.addCard(TrackAppearanceFragment.java:764)
	at net.osmand.plus.track.fragments.TrackAppearanceFragment.setupCards(TrackAppearanceFragment.java:740)
	at net.osmand.plus.track.fragments.TrackAppearanceFragment.initContent(TrackAppearanceFragment.java:247)
	at net.osmand.plus.track.fragments.TrackAppearanceFragment.onCreateView(TrackAppearanceFragment.java:240)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
 
```

**Comment by vshcherb** [comment]
Already fixed
