### ISSUE TITLE
Crash short time after startup (class not found exception for java.time.format.DateTimeFormatter while loading GPX track)

### ISSUE THREAD

**Issue by gjaekel** [osmandapp/OsmAnd#19844]
### Description

A about 30s till 1min after the start the application crashes. Until then, all seems to work as usual - I observed no glitches apparently.

This happens after upgrade to  4.7.15, but never before.

### Steps to reproduce

Start Application as usual.

### Actual result

Crash after about 30sec

### Expected result

Work als usual.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.7.15
Android/iOS version: 7.1.2
Device model: santoni (Redmi 4X)
Crash-Logs: exception log
```
[exception.log](https://github.com/osmandapp/OsmAnd/files/15285617/exception.log)

```
Version  OsmAnd 4.7.15
10.05.2024 6:46:32
Apk Version : 4.7.15 4715
Exception occurred in thread Thread[pool-11-thread-1,5,main] : 
java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:325)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/format/DateTimeFormatter;
        at net.osmand.gpx.GPXUtilities.getTimeFormatterMills(GPXUtilities.java:1480)
        at net.osmand.gpx.GPXUtilities.parseTime(GPXUtilities.java:1414)
        at net.osmand.gpx.GPXUtilities.loadGPXFile(GPXUtilities.java:1797)
        at net.osmand.gpx.GPXUtilities.loadGPXFile(GPXUtilities.java:1492)
        at net.osmand.gpx.GPXUtilities.loadGPXFile(GPXUtilities.java:1485)
        at net.osmand.plus.track.helpers.GpxFileLoaderTask.doInBackground(GpxFileLoaderTask.java:83)
        at net.osmand.plus.track.helpers.GpxFileLoaderTask.doInBackground(GpxFileLoaderTask.java:21)
        at android.os.AsyncTask$2.call(AsyncTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        ... 3 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "java.time.format.DateTimeFormatter" on path: DexPathList[[zip file "/data/app/net.osmand-2/base.apk", zip file "/data/app/net.osmand-2/split_config.arm64_v8a.apk", zip file "/data/app/net.osmand-2/split_config.xhdpi.apk"],nativeLibraryDirectories=[/data/app/net.osmand-2/lib/arm64, /data/app/net.osmand-2/base.apk!/lib/arm64-v8a, /data/app/net.osmand-2/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/net.osmand-2/split_config.xhdpi.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        ... 12 more
        Suppressed: java.io.IOException: No original dex files found for dex location /data/app/net.osmand-2/split_config.arm64_v8a.apk
                at dalvik.system.DexFile.openDexFileNative(Native Method)
                at dalvik.system.DexFile.openDexFile(DexFile.java:367)
                at dalvik.system.DexFile.<init>(DexFile.java:112)
                at dalvik.system.DexFile.<init>(DexFile.java:77)
                at dalvik.system.DexPathList.loadDexFile(DexPathList.java:359)
                at dalvik.system.DexPathList.makeElements(DexPathList.java:323)
                at dalvik.system.DexPathList.makeDexElements(DexPathList.java:263)
                at dalvik.system.DexPathList.<init>(DexPathList.java:126)
                at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
                at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
                at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
                at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:58)
                at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:522)
                at android.app.LoadedApk.getClassLoader(LoadedApk.java:555)
                at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:1924)
                at android.app.LoadedApk.getResources(LoadedApk.java:768)
                at android.app.ContextImpl.<init>(ContextImpl.java:2077)
                at android.app.ContextImpl.createAppContext(ContextImpl.java:2022)
                at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5394)
                at android.app.ActivityThread.-wrap2(ActivityThread.java)
                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                at android.os.Handler.dispatchMessage(Handler.java:102)
                at android.os.Looper.loop(Looper.java:163)
                at android.app.ActivityThread.main(ActivityThread.java:6238)
                at java.lang.reflect.Method.invoke(Native Method)
                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
        Suppressed: java.io.IOException: No original dex files found for dex location /data/app/net.osmand-2/split_config.xhdpi.apk
                at dalvik.system.DexFile.openDexFileNative(Native Method)
                at dalvik.system.DexFile.openDexFile(DexFile.java:367)
                at dalvik.system.DexFile.<init>(DexFile.java:112)
                at dalvik.system.DexFile.<init>(DexFile.java:77)
                at dalvik.system.DexPathList.loadDexFile(DexPathList.java:359)

```

**Comment by gjaekel** [comment]
* Is this already fixed in 4.7.17? 
* Is it possible to move away all existing GPX tracks or the complete `tracks` directory via `adb`?

**Comment by yuriiurshuliak** [comment]
Based on our analysis of the crash logs, it appears that the issue is identical to the java 8 formatting crash. To resolve this, please update to the latest version.

**Comment by gjaekel** [comment]
Thank you. What's the minimal version number you're referring to, please? It seems to me that I have to download an APK directly because it isn't available on the appstores at the moment.

**Comment by vshcherb** [comment]
4.7.17 is available in GPlay and on our site https://download.osmand.net/releases/

**Comment by gjaekel** [comment]
@vshcherb: Thank you. Indeed, now 4.7.17 was offered to me at GPlay. The App is already running for more than 3min without crashing. For this, I confirm that the issue is solved.
