### ISSUE TITLE
Crash immediatly after try to view favourite route.

### ISSUE THREAD

**Issue by Vucumpra** [osmandapp/OsmAnd#19875]
### Description

Crash immediatly after show favourite routes but no crash for favourites POI.

### Steps to reproduce

Just open Osmand and go to view favourites routes

### Actual result

Crash for favourites routes but no crash for favourites POI

### Expected result

No crash !

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.7.17 F-Droid
Android/iOS version: 11 & 13
Device model: One+ & Xiaomi MIUI 14
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
Kindly provide additional details regarding the term "favorite routes." It would be helpful if you could outline the specific sequence of actions that result in the crash. Additionally, please include a video demonstrating the cause of the crash as well as the crash logs following the occurrence.

**Comment by Vucumpra** [comment]
> Kindly provide additional details regarding the term "favorite routes." It would be helpful if you could outline the specific sequence of actions that result in the crash. Additionally, please include a video demonstrating the cause of the crash as well as the crash logs following the occurrence.


https://github.com/osmandapp/OsmAnd/assets/156325356/3e2ba790-6eb5-481d-a8bd-3349ef9572d4


LOG : 
`
Version  OsmAnd~ 4.7.17
26.05.2024 2:34:53
Apk Version : 4.7.17 471703
Exception occurred in thread Thread[pool-20-thread-1,5,main] : 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Long
	at java.lang.Long.compareTo(Long.java:55)
	at net.osmand.plus.myplaces.tracks.filters.RangeTrackFilter.isTrackAccepted(RangeTrackFilter.kt:112)
	at net.osmand.plus.myplaces.tracks.filters.SmartFolderHelper.addTracksToSmartFolders(SmartFolderHelper.kt:220)
	at net.osmand.plus.myplaces.tracks.filters.SmartFolderHelper.addTrackItemsToSmartFolder(SmartFolderHelper.kt:211)
	at net.osmand.plus.configmap.tracks.TrackFolderLoaderTask.loadGPXFolder(TrackFolderLoaderTask.java:123)
	at net.osmand.plus.configmap.tracks.TrackFolderLoaderTask.doInBackground(TrackFolderLoaderTask.java:71)
	at net.osmand.plus.configmap.tracks.TrackFolderLoaderTask.doInBackground(TrackFolderLoaderTask.java:28)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
`

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. To replicate it, go to My Places and try switching between the Favorites, Tracks, and OSM Edits tabs.

OsmAnd~ 4.8.0#2395m, released: 2024-05-27

https://github.com/osmandapp/OsmAnd/assets/127092082/e452a4ec-42c3-44f4-9c7e-38c10a9707b8

**Comment by Vucumpra** [comment]
I'm using 4.7.17 !

**Comment by sikjo** [comment]
I too experienced this problem in both 4.7.10 and 4.7.17 (unsure about earlier versions).

After finding this issue a few days ago, I did some expeimenting and found that any gpx-file in the Tracks folder will trigger the crash. But after removing my only smart folder the crashing stopped and hasn't returned even after recreating the smart folder.

**Comment by DmitryAlexei** [comment]
@sikjo To reproduce and fix that issue we need additional info:
- crash logs (see https://osmand.net/docs/user/troubleshooting/crash-logs#send-logs-from-osmand-app-android ) 
- what were your smart folder settings? Which filters were on?

**Comment by sikjo** [comment]
Yes, the last stack trace is included below.

The filter was created a couple of years ago and a very simple one showing "short" tracks I wish to delete (usually accidental saves) . I am uncertain if it used time or length as criteria. Both works today though.

```
Version  OsmAnd~ 4.7.17
16.06.2024 10:51:57
Apk Version : 4.7.17 471703
Exception occurred in thread Thread[main,5,main] : 
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Long
    at java.lang.Long.compareTo(Long.java:55)
    at net.osmand.plus.myplaces.tracks.filters.RangeTrackFilter.isValid(RangeTrackFilter.kt:245)
    at net.osmand.plus.myplaces.tracks.filters.viewholders.FilterRangeViewHolder._init_$lambda$1(FilterRangeViewHolder.kt:96)
    at net.osmand.plus.myplaces.tracks.filters.viewholders.FilterRangeViewHolder.$r8$lambda$HVe2KX1yIIYAKJNQlzpm7h9H_Dc(Unknown Source:0)
    at net.osmand.plus.myplaces.tracks.filters.viewholders.FilterRangeViewHolder$$ExternalSyntheticLambda1.onClick(Unknown Source:2)
    at android.view.View.performClick(View.java:6600)
    at android.view.View.performClickInternal(View.java:6577)
    at android.view.View.access$3100(View.java:781)
    at android.view.View$PerformClick.run(View.java:25966)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:210)
    at android.app.ActivityThread.main(ActivityThread.java:7124)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:898)
```

**Comment by DmitryAlexei** [comment]
@Vucumpra does the issue persist? Please provide your profile settings and latest crash logs.
We need this information to reproduce and fix that issue.

As a workaround (if you cannot send additional info), please try to recreate a smart folder filter.

**Comment by Vucumpra** [comment]
It's impossible for me to create a smart folder. I can enter in the "Track" section because Osmand crash !

**Comment by Vucumpra** [comment]
The logs was on third message on this html page

**Comment by DmitryAlexei** [comment]
@Vucumpra please attach your profile settings. We need them to reproduce and fix that issue. 
go to menu > settings > your profile > export profile
export file can be attached to github after adding .txt extension

**Comment by Vucumpra** [comment]
Hello, now it's too late.
I don't remember how, but I managed to get into the "track" tab on favourites page. From there, I deleted all smart folder.
Now, osmand 4.7.17 and 4.8 are OK :)
