### ISSUE TITLE
OSM note upload crashes the app if mobile Internet is not usable/unavailable/limited

### ISSUE THREAD

**Issue by HellMapGoesCoding** [osmandapp/OsmAnd#19985]
### Description

As per title.

About "usable/available/limited" - I don't exactly know what my phone or OsmAnd considers usable/connected for each of those network "code" values like "H+", but I believe the connection has to be "less" than 3G or some weird 3G variant that doesn't actually allow full Internet access. I have no way to debug this. It does not happen with 4G/5G/LTE. I am not sure if it happens with "pure" 3G, it tends to fluctuate quickly. I believe it happens with H+. (3G is locally being phased out, so it may be related and one of those 3.5G modes might be technically connecting but failing. But I'm deep into speculation now, I have no idea.) Reproduced several times in a couple different low-coverage locations.

### Steps to reproduce

Go to a place with no "usable" network coverage.

Try to upload OSM note.

### Actual result

OsmAnd crashes, offers bug report sending, then closes. OSM note position/data is lost on restart.

### Expected result

Ideally, schedule note upload for later.

At least, state that "couldn't upload" and allow to retry.

### Crash log

Pixel 7, Android 14 (5 May 2024, AP1A.240505.005)

```
Version  OsmAnd 4.7.17
28.05.2024 3:52:33
Apk Version : 4.7.17 4717
Exception occurred in thread Thread[AsyncTask #2,5,main] : 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: com.github.scribejava.core.exceptions.OAuthException: The IP address of a host could not be determined.
	at net.osmand.osm.oauth.OsmAndJDKHttpClient.doExecute(OsmAndJDKHttpClient.java:141)
	at net.osmand.osm.oauth.OsmAndJDKHttpClient.execute(OsmAndJDKHttpClient.java:103)
	at com.github.scribejava.core.oauth.OAuthService.execute(OAuthService.java:108)
	at net.osmand.osm.oauth.OsmOAuthAuthorizationClient.performRequest(OsmOAuthAuthorizationClient.java:114)
	at net.osmand.plus.plugins.osmedit.helpers.OsmBugsRemoteUtil.performOAuthRequest(OsmBugsRemoteUtil.java:185)
	at net.osmand.plus.plugins.osmedit.helpers.OsmBugsRemoteUtil.editingPOI(OsmBugsRemoteUtil.java:122)
	at net.osmand.plus.plugins.osmedit.helpers.OsmBugsRemoteUtil.validateLoginDetails(OsmBugsRemoteUtil.java:114)
	at net.osmand.plus.plugins.osmedit.helpers.OsmBugsRemoteUtil.commit(OsmBugsRemoteUtil.java:105)
	at net.osmand.plus.plugins.osmedit.asynctasks.UploadOpenstreetmapPointAsyncTask.doInBackground(UploadOpenstreetmapPointAsyncTask.java:83)
	at net.osmand.plus.plugins.osmedit.asynctasks.UploadOpenstreetmapPointAsyncTask.doInBackground(UploadOpenstreetmapPointAsyncTask.java:23)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more
Caused by: java.net.UnknownHostException: Unable to resolve host "api.openstreetmap.org": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:124)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at com.android.okhttp.Dns$1.lookup(Dns.java:41)
	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
	at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:176)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
	at net.osmand.osm.oauth.OsmAndJDKHttpClient.doExecute(OsmAndJDKHttpClient.java:135)
	... 14 more
```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To encounter this bug, first open OSM Note, then navigate to MyPlaces - OSM Edits - Upload edit to OSM. Before proceeding with the upload, disable your internet connection and attempt to download the edit. This will cause the app to crash.

[exception (10).zip](https://github.com/osmandapp/OsmAnd/files/15500502/exception.10.zip)


OsmAnd~ 4.8.0#2416m, released: 2024-05-30

https://github.com/osmandapp/OsmAnd/assets/127092082/0844c021-0759-4b53-bfe1-623c211bc347
