### ISSUE TITLE
My Places: OSM Edits: Upper Right Upload Button: Application Consistently Restarts

### ISSUE THREAD

**Issue by Zian** [osmandapp/OsmAnd#20109]
Steps to Reproduce the Problem:
1. Start OsmAnd.
2. Press the hamburger menu button in the lower left corner.
3. Press My Places.
4. Press "OSM EDITS" if the list of pending edits is not visible. On my device, 5 items are shown under "Your edits".
5. Press the upload button in the lower left corner.
6. Check all the check boxes by pressing the checkbox to the left of "Your edits".
7. Press the upload button in the upper right corner.

Expected Result:
The items should be uploaded.

Actual Result:
OsmAnd crashes. After the application restarts, it prompts me to e-mail a log file.

Most Recent Entry in exception.log:
```
Version  OsmAnd+ 4.7.17
15.06.2024 11:40:51
Apk Version : 4.7.17 4717
Exception occurred in thread Thread[AsyncTask #144,5,main] : 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:354)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.RuntimeException: Can't toast on a thread that has not called Looper.prepare()
	at android.widget.Toast$TN.<init>(Toast.java:393)
	at android.widget.Toast.<init>(Toast.java:117)
	at android.widget.Toast.makeText(Toast.java:280)
	at android.widget.Toast.makeText(Toast.java:270)
	at net.osmand.plus.plugins.osmedit.helpers.OpenstreetmapRemoteUtil.loadEntity(OpenstreetmapRemoteUtil.java:442)
	at net.osmand.plus.plugins.osmedit.asynctasks.UploadOpenstreetmapPointAsyncTask.doInBackground(UploadOpenstreetmapPointAsyncTask.java:71)
	at net.osmand.plus.plugins.osmedit.asynctasks.UploadOpenstreetmapPointAsyncTask.doInBackground(UploadOpenstreetmapPointAsyncTask.java:23)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
```

Environmental Information:
- OsmAnd Version: 4.7.17
- Full Name: net.osmand.plus
- OnePlus 5
- Android version 9

**Comment by vshcherb** [comment]
Toasts should be displayed in PostExecute (not in DoBackground as it's now)
```
			public void uploadEnded(Map<OsmPoint, String> loadErrorsMap) {
```

**Comment by DmitryAlexei** [comment]
todo:
- reproduce and fix that bug
