### ISSUE TITLE
Unnecessary detour in pedestrian navigation

### ISSUE THREAD

**Issue by gabortim** [osmandapp/OsmAnd#20278]
### Routing engine

- [X] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

pedestrian default profile

### Start and end points

Use these three points for route creation:
- start: https://www.openstreetmap.org/api/0.6/node/7041674499/4
- intermediate point: https://www.openstreetmap.org/api/0.6/way/513719876/9
- destination: https://www.openstreetmap.org/api/0.6/node/8955472807/1

### Actual route

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/23311361/d4f44e14-1165-4ccb-ab76-e85286f6b68b"  width="300" height="auto"/> </th>
  </tr>
</table>

### Expected route

Without the detour around the Vigadó tér to the north from the start position.

It works fine in the online version:
https://osmand.net/map/navigate/?start=46.812031%2C17.776504&end=46.809221%2C17.764721&via=46.810973%2C17.775397&profile=pedestrian#16/46.8113/17.7684

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/23311361/0bb268bb-ae18-4ae4-b51b-d628ce2a56dc"  width="300" height="auto"/> </th>
  </tr>
</table>

### Maps you used (online or offline)

- [x] Offline maps offered within the OsmAnd app for download. Hungary 2024-07-01 without live updates.
- [ ] Online (tile / raster) maps 

### Your Environment

```
OsmAnd Version: 4.7.17 from F-Droid
Android version: 13-14 (multiple test devices)
Device model: no impact, reproducible on multiple devices
```

**Comment by yuriiurshuliak** [comment]
The bug could not be reproduced. To test, choose the pedestrian profile and use these coordinates in the [Web version](https://test.osmand.net/map/navigate/?start=46.812030,17.776500&end=46.809220,17.764720&via=46.810970,17.775401&profile=pedestrian#15/46.8093/17.7663)
Attempt to build the navigation, and it will be correctly built in both the Web version and the app without any detours.
So, please try to update your map.

OsmAnd~ 4.8.0#2710m, released: 2024-07-09

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/b4a3b58e-f012-45c5-b3c2-06cf9f0eb025"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/501a16b5-8f1a-4b33-b3a8-565691829cb7"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by gabortim** [comment]
> OsmAnd~ 4.8.0#2710m, released: 2024-07-09

This is a newer version. Where can I get it? :)

**Comment by dmpr0** [comment]
> > OsmAnd~ 4.8.0#2710m, released: 2024-07-09
> 
> This is a newer version. Where can I get it? :)

On Google Play, Huawei, Amazon https://docs.osmand.net/docs/versions/free-versions

**Comment by gabortim** [comment]
I cannot find OsmAnd~ on any of the mentioned stores, only OsmAnd and only version 4.7.17 which is the latest.

But if you say it's fixed in 4.8.0, then fine, waiting for the release.

**Comment by dmpr0** [comment]
@gabortim 
4.8.0 is available as Beta version on Google Play:
* OsmAnd – https://play.google.com/apps/testing/net.osmand 
* OsmAnd +  – https://play.google.com/apps/testing/net.osmand.plus

**Comment by gabortim** [comment]
Thanks for the info!

Now I downloaded the nightly from [here](https://download.osmand.net/latest-night-build/OsmAnd-default.apk) and with these 3 coordinates from yuriiurshuliak OsmAnd just crashed:

```
07-10 13:09:09.889 22768 23086 E net.osmand: RouteProvider Runtime error: Attempt to invoke virtual method 'net.osmand.map.WorldRegion net.osmand.map.OsmandRegions.getRegionDataByDownloadName(java.lang.String)' on a null object reference {pool-5-thread-1}
07-10 13:09:09.889 22768 23086 E net.osmand: java.lang.NullPointerException: Attempt to invoke virtual method 'net.osmand.map.WorldRegion net.osmand.map.OsmandRegions.getRegionDataByDownloadName(java.lang.String)' on a null object reference
07-10 13:09:09.889 22768 23086 E net.osmand: 	at net.osmand.router.MissingMapsCalculator.checkIfThereAreMissingMaps(MissingMapsCalculator.java:75)
07-10 13:09:09.889 22768 23086 E net.osmand: 	at net.osmand.router.RoutePlannerFrontEnd.searchRoute(RoutePlannerFrontEnd.java:389)
07-10 13:09:09.889 22768 23086 E net.osmand: 	at net.osmand.router.RoutePlannerFrontEnd.searchRoute(RoutePlannerFrontEnd.java:218)
07-10 13:09:09.889 22768 23086 E net.osmand: 	at net.osmand.plus.routing.RouteProvider.calcOfflineRouteImpl(RouteProvider.java:878)
07-10 13:09:09.889 22768 23086 E net.osmand: 	at net.osmand.plus.routing.RouteProvider.findVectorMapsRoute(RouteProvider.java:801)
07-10 13:09:09.889 22768 23086 E net.osmand: 	at net.osmand.plus.routing.RouteProvider.calculateRouteImpl(RouteProvider.java:130)
07-10 13:09:09.889 22768 23086 E net.osmand: 	at net.osmand.plus.routing.RouteRecalculationHelper$RouteRecalculationTask.run(RouteRecalculationHelper.java:363)
07-10 13:09:09.889 22768 23086 E net.osmand: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
07-10 13:09:09.889 22768 23086 E net.osmand: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
07-10 13:09:09.889 22768 23086 E net.osmand: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
07-10 13:09:09.889 22768 23086 E net.osmand: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
07-10 13:09:09.889 22768 23086 E net.osmand: 	at java.lang.Thread.run(Thread.java:1012)
07-10 13:09:09.890 22768 23086 I net.osmand: RouteProvider Finding route contained 0 points for 19 ms {pool-5-thread-1}

...

07-10 13:09:37.125 22768 23086 I scudo   :   00 (    64): mapped:    256K popped:   65754 pushed:   65208 inuse:    546 total:   4004 rss:      0K releases:      0 last released:      0K region: 0x7a14e0d000 (0x7a14e02000)
07-10 13:09:37.125 22768 23086 I scudo   :   01 (    32): mapped:  43008K popped: 1494736 pushed:  123435 inuse: 1371301 total: 1371340 rss:      0K releases:      0 last released:      0K region: 0x7a24e03000 (0x7a24e02000)
07-10 13:09:37.125 22768 23086 I scudo   :   02 (    48): mapped:  39424K popped: 1550697 pushed:  710099 inuse: 840598 total: 840624 rss:      0K releases:      0 last released:      0K region: 0x7a34e11000 (0x7a34e02000)
07-10 13:09:37.125 22768 23086 I scudo   :   03 (    64): mapped: 261632K popped: 4304034 pushed:  121043 inuse: 4182991 total: 4183004 rss:      0K releases:      0 last released:      0K region: 0x7a44e0a000 (0x7a44e02000)
07-10 13:09:37.125 22768 23086 I scudo   :   04 (    80): mapped:  28672K popped:  432302 pushed:   67392 inuse: 364910 total: 364910 rss:      0K releases:      0 last released:      0K region: 0x7a54e0b000 (0x7a54e02000)
07-10 13:09:37.125 22768 23086 I scudo   :   05 (    96): mapped:   3584K popped:   42102 pushed:    4745 inuse:  37357 total:  37370 rss:      0K releases:      0 last released:      0K region: 0x7a64e03000 (0x7a64e02000)
07-10 13:09:37.125 22768 23086 I scudo   :   06 (   112): mapped:   3328K popped:   47294 pushed:   16978 inuse:  30316 total:  30316 rss:      0K releases:      0 last released:      0K region: 0x7a74e03000 (0x7a74e02000)
07-10 13:09:37.125 22768 23086 I scudo   :   07 (   144): mapped:   6656K popped:   84214 pushed:   36933 inuse:  47281 total:  47320 rss:      0K releases:      0 last released:      0K region: 0x7a84e03000 (0x7a84e02000)
07-10 13:09:37.125 22768 23086 I scudo   : F 08 (   176): mapped: 261888K popped: 1574321 pushed:   50609 inuse: 1523712 total: 1523712 rss:      0K releases:      3 last released:    352K region: 0x7a94e0c000 (0x7a94e02000)
07-10 13:09:37.125 22768 23086 I scudo   :   09 (   192): mapped:   2560K popped:   15707 pushed:    3133 inuse:  12574 total:  12600 rss:      0K releases:      0 last released:      0K region: 0x7aa4e10000 (0x7aa4e02000)
07-10 13:09:37.125 22768 23086 I scudo   :   10 (   224): mapped:   4352K popped:   24288 pushed:    5291 inuse:  18997 total:  19036 rss:      0K releases:      1 last released:    240K region: 0x7ab4e0f000 (0x7ab4e02000)
07-10 13:09:37.125 22768 23086 I scudo   :   11 (   288): mapped:   4864K popped:   22793 pushed:    5681 inuse:  17112 total:  17112 rss:      0K releases:    147 last released:      4K region: 0x7ac4e09000 (0x7ac4e02000)
07-10 13:09:37.125 22768 23086 I scudo   :   12 (   352): mapped:  30208K popped:  114836 pushed:   27378 inuse:  87458 total:  87497 rss:      0K releases:    206 last released:      8K region: 0x7ad4e0c000 (0x7ad4e02000)
07-10 13:09:37.125 22768 23086 I scudo   :   13 (   448): mapped:   6400K popped:   16526 pushed:    2327 inuse:  14199 total:  14199 rss:      0K releases:     27 last released:     20K region: 0x7ae4e03000 (0x7ae4e02000)
07-10 13:09:37.125 22768 23086 I scudo   :   14 (   592): mapped:   3840K popped:    8773 pushed:    2301 inuse:   6472 total:   6511 rss:      0K releases:     26 last released:      8K region: 0x7af4e05000 (0x7af4e02000)
07-10 13:09:37.125 22768 23086 I scudo   :   15 (   800): mapped:   4352K popped:    5532 pushed:     140 inuse:   5392 total:   5402 rss:      0K releases:      1 last released:      4K region: 0x7b04e0a000 (0x7b04e02000)
07-10 13:09:37.125 22768 23086 I scudo   :   16 (  1104): mapped:   3328K popped:    4347 pushed:    1379 inuse:   2968 total:   2989 rss:      0K releases:     16 last released:      8K region: 0x7b14e0a000 (0x7b14e02000)
07-10 13:09:37.125 22768 23086 I scudo   :   17 (  1648): mapped:   6144K popped:    6050 pushed:    2332 inuse:   3718 total:   3722 rss:      0K releases:    171 last released:    148K region: 0x7b24e0d000 (0x7b24e02000)
07-10 13:09:37.125 22768 23086 I scudo   :   18 (  2096): mapped:   1536K popped:    1237 pushed:     531 inuse:    706 total:    709 rss:      0K releases:    118 last released:     72K region: 0x7b34e06000 (0x7b34e02000)
07-10 13:09:37.125 22768 23086 I scudo   :   19 (  2576): mapped:   1024K popped:     428 pushed:      36 inuse:    392 total:    401 rss:      0K releases:     11 last released:      4K region: 0x7b44e08000 (0x7b44e02000)
07-10 13:09:37.125 22768 23086 I scudo   :   20 (  3120): mapped:   1792K popped:     618 pushed:     110 inuse:    508 total:    512 rss:      0K releases:     25 last released:     12K region: 0x7b54e0b000 (0x7b54e02000)
07-10 13:09:37.125 22768 23086 I scudo   :   21 (  4112): mapped:  10496K popped:    6021 pushed:    3647 inuse:   2374 total:   2610 rss:      0K releases:   1221 last released:    660K region: 0x7b64e0c000 (0x7b64e02000)
07-10 13:09:37.125 22768 23086 I scudo   :   22 (  4624): mapped:    512K popped:     420 pushed:     358 inuse:     62 total:     76 rss:      0K releases:    100 last released:     16K region: 0x7b74e09000 (0x7b74e02000)
07-10 13:09:37.125 22768 23086 I scudo   :   23 (  7120): mapped:   6912K popped:    2506 pushed:    1524 inuse:    982 total:    993 rss:      0K releases:    836 last released:      8K region: 0x7b84e0b000 (0x7b84e02000)
07-10 13:09:37.125 22768 23086 I scudo   :   24 (  8720): mapped:   1792K popped:     694 pushed:     495 inuse:    199 total:    200 rss:      0K releases:     66 last released:      8K region: 0x7b94e0e000 (0x7b94e02000)
07-10 13:09:37.125 22768 23086 I scudo   :   25 ( 11664): mapped:    768K popped:      60 pushed:      32 inuse:     28 total:     52 rss:      0K releases:     52 last released:    240K region: 0x7ba4e0a000 (0x7ba4e02000)
07-10 13:09:37.125 22768 23086 I scudo   :   26 ( 14224): mapped:  12032K popped:    1009 pushed:     157 inuse:    852 total:    855 rss:      0K releases:     93 last released:     16K region: 0x7bb4e04000 (0x7bb4e02000)
07-10 13:09:37.125 22768 23086 I scudo   :   27 ( 16400): mapped:   4096K popped:     365 pushed:     197 inuse:    168 total:    243 rss:      0K releases:    140 last released:    844K region: 0x7bc4e0d000 (0x7bc4e02000)
07-10 13:09:37.125 22768 23086 I scudo   :   28 ( 18448): mapped:   1280K popped:      85 pushed:      74 inuse:     11 total:     64 rss:      0K releases:     31 last released:    932K region: 0x7bd4e11000 (0x7bd4e02000)
07-10 13:09:37.125 22768 23086 I scudo   :   29 ( 23056): mapped:   2560K popped:     147 pushed:      71 inuse:     76 total:    113 rss:      0K releases:     80 last released:    784K region: 0x7be4e0b000 (0x7be4e02000)
07-10 13:09:37.125 22768 23086 I scudo   :   30 ( 29456): mapped:   9728K popped:     413 pushed:      83 inuse:    330 total:    333 rss:      0K releases:    106 last released:    132K region: 0x7bf4e09000 (0x7bf4e02000)
07-10 13:09:37.125 22768 23086 I scudo   :   31 ( 33296): mapped:   3840K popped:     835 pushed:     735 inuse:    100 total:    114 rss:      0K releases:    170 last released:    412K region: 0x7c04e04000 (0x7c04e02000)
07-10 13:09:37.125 22768 23086 I scudo   :   32 ( 65552): mapped:   7424K popped:     187 pushed:      76 inuse:    111 total:    115 rss:      0K releases:     83 last released:   4212K region: 0x7c14e12000 (0x7c14e02000)
07-10 13:09:37.125 22768 23086 I scudo   : Scudo OOM: The process has exhausted 256M for size class 176.
07-10 13:09:37.172 22768 23086 I scudo   : Stats: SizeClassAllocator64: 763M mapped (0M rss) in 9840308 allocations; remains 8585463
07-10 13:09:37.172 22768 23086 I scudo   :   00 (    64): mapped:    256K popped:   65754 pushed:   65208 inuse:    546 total:   4004 rss:      0K releases:      0 last released:      0K region: 0x7a14e0d000 (0x7a14e02000)
07-10 13:09:37.172 22768 23086 I scudo   :   01 (    32): mapped:  43008K popped: 1494762 pushed:  123448 inuse: 1371314 total: 1371340 rss:      0K releases:      0 last released:      0K region: 0x7a24e03000 (0x7a24e02000)
07-10 13:09:37.172 22768 23086 I scudo   :   02 (    48): mapped:  39680K popped: 1551477 pushed:  710385 inuse: 841092 total: 841092 rss:      0K releases:      0 last released:      0K region: 0x7a34e11000 (0x7a34e02000)
07-10 13:09:37.172 22768 23086 I scudo   : F 03 (    64): mapped: 261888K popped: 4311251 pushed:  121043 inuse: 4190208 total: 4190208 rss:      0K releases:      0 last released:      0K region: 0x7a44e0a000 (0x7a44e02000)
07-10 13:09:37.172 22768 23086 I scudo   :   04 (    80): mapped:  28672K popped:  432354 pushed:   67405 inuse: 364949 total: 364962 rss:      0K releases:      0 last released:      0K region: 0x7a54e0b000 (0x7a54e02000)
07-10 13:09:37.172 22768 23086 I scudo   :   05 (    96): mapped:   3584K popped:   42154 pushed:    4745 inuse:  37409 total:  37422 rss:      0K releases:      0 last released:      0K region: 0x7a64e03000 (0x7a64e02000)
07-10 13:09:37.172 22768 23086 I scudo   :   06 (   112): mapped:   3328K popped:   47307 pushed:   16978 inuse:  30329 total:  30368 rss:      0K releases:      0 last released:      0K region: 0x7a74e03000 (0x7a74e02000)
07-10 13:09:37.172 22768 23086 I scudo   :   07 (   144): mapped:   6656K popped:   84227 pushed:   36933 inuse:  47294 total:  47320 rss:      0K releases:      0 last released:      0K region: 0x7a84e03000 (0x7a84e02000)
07-10 13:09:37.172 22768 23086 I scudo   : F 08 (   176): mapped: 261888K popped: 1574321 pushed:   50609 inuse: 1523712 total: 1523712 rss:      0K releases:      3 last released:    352K region: 0x7a94e0c000 (0x7a94e02000)
07-10 13:09:37.172 22768 23086 I scudo   :   09 (   192): mapped:   3072K popped:   18489 pushed:    3133 inuse:  15356 total:  15382 rss:      0K releases:      0 last released:      0K region: 0x7aa4e10000 (0x7aa4e02000)
07-10 13:09:37.172 22768 23086 I scudo   :   10 (   224): mapped:   4352K popped:   24288 pushed:    5291 inuse:  18997 total:  19036 rss:      0K releases:      1 last released:    240K region: 0x7ab4e0f000 (0x7ab4e02000)
07-10 13:09:37.172 22768 23086 I scudo   :   11 (   288): mapped:   4864K popped:   22806 pushed:    5681 inuse:  17125 total:  17164 rss:      0K releases:    147 last released:      4K region: 0x7ac4e09000 (0x7ac4e02000)
07-10 13:09:37.172 22768 23086 I scudo   :   12 (   352): mapped:  30208K popped:  114836 pushed:   27378 inuse:  87458 total:  87497 rss:      0K releases:    206 last released:      8K region: 0x7ad4e0c000 (0x7ad4e02000)
07-10 13:09:37.172 22768 23086 I scudo   :   13 (   448): mapped:   6400K popped:   16539 pushed:    2327 inuse:  14212 total:  14251 rss:      0K releases:     27 last released:     20K region: 0x7ae4e03000 (0x7ae4e02000)
07-10 13:09:37.172 22768 23086 I scudo   :   14 (   592): mapped:   3840K popped:    8773 pushed:    2301 inuse:   6472 total:   6511 rss:      0K releases:     26 last released:      8K region: 0x7af4e05000 (0x7af4e02000)
07-10 13:09:37.172 22768 23086 I scudo   :   15 (   800): mapped:   4352K popped:    5532 pushed:     140 inuse:   5392 total:   5402 rss:      0K releases:      1 last released:      4K region: 0x7b04e0a000 (0x7b04e02000)
07-10 13:09:37.172 22768 23086 I scudo   :   16 (  1104): mapped:   3328K popped:    4347 pushed:    1379 inuse:   2968 total:   2989 rss:      0K releases:     16 last released:      8K region: 0x7b14e0a000 (0x7b14e02000)
07-10 13:09:37.172 22768 23086 I scudo   :   17 (  1648): mapped:   6144K popped:    6054 pushed:    2332 inuse:   3722 total:   3722 rss:      0K releases:    171 last released:    148K region: 0x7b24e0d000 (0x7b24e02000)
07-10 13:09:37.172 22768 23086 I scudo   :   18 (  2096): mapped:   1536K popped:    1237 pushed:     531 inuse:    706 total:    709 rss:      0K releases:    118 last released:     72K region: 0x7b34e06000 (0x7b34e02000)
07-10 13:09:37.172 22768 23086 I scudo   :   19 (  2576): mapped:   1024K popped:     428 pushed:      36 inuse:    392 total:    401 rss:      0K releases:     11 last released:      4K region: 0x7b44e08000 (0x7b44e02000)
07-10 13:09:37.173 22768 23086 I scudo   :   20 (  3120): mapped:   1792K popped:     618 pushed:     110 inuse:    508 total:    512 rss:      0K releases:     25 last released:     12K region: 0x7b54e0b000 (0x7b54e02000)
07-10 13:09:37.173 22768 23086 I scudo   :   21 (  4112): mapped:  10496K popped:    6032 pushed:    3647 inuse:   2385 total:   2610 rss:      0K releases:   1221 last released:    660K region: 0x7b64e0c000 (0x7b64e02000)
07-10 13:09:37.173 22768 23086 I scudo   :   22 (  4624): mapped:    512K popped:     420 pushed:     358 inuse:     62 total:     76 rss:      0K releases:    100 last released:     16K region: 0x7b74e09000 (0x7b74e02000)
07-10 13:09:37.173 22768 23086 I scudo   :   23 (  7120): mapped:   6912K popped:    2506 pushed:    1526 inuse:    980 total:    993 rss:      0K releases:    836 last released:      8K region: 0x7b84e0b000 (0x7b84e02000)
07-10 13:09:37.173 22768 23086 I scudo   :   24 (  8720): mapped:   1792K popped:     694 pushed:     496 inuse:    198 total:    200 rss:      0K releases:     68 last released:      8K region: 0x7b94e0e000 (0x7b94e02000)
07-10 13:09:37.173 22768 23086 I scudo   :   25 ( 11664): mapped:    768K popped:      60 pushed:      32 inuse:     28 total:     52 rss:      0K releases:     52 last released:    240K region: 0x7ba4e0a000 (0x7ba4e02000)
07-10 13:09:37.173 22768 23086 I scudo   :   26 ( 14224): mapped:  12032K popped:    1010 pushed:     157 inuse:    853 total:    855 rss:      0K releases:     93 last released:     16K region: 0x7bb4e04000 (0x7bb4e02000)
07-10 13:09:37.173 22768 23086 I scudo   :   27 ( 16400): mapped:   4096K popped:     365 pushed:     197 inuse:    168 total:    243 rss:      0K releases:    140 last released:    844K region: 0x7bc4e0d000 (0x7bc4e02000)
07-10 13:09:37.173 22768 23086 I scudo   :   28 ( 18448): mapped:   1280K popped:      85 pushed:      74 inuse:     11 total:     64 rss:      0K releases:     31 last released:    932K region: 0x7bd4e11000 (0x7bd4e02000)
07-10 13:09:37.173 22768 23086 I scudo   :   29 ( 23056): mapped:   2560K popped:     147 pushed:      71 inuse:     76 total:    113 rss:      0K releases:     80 last released:    784K region: 0x7be4e0b000 (0x7be4e02000)
07-10 13:09:37.173 22768 23086 I scudo   :   30 ( 29456): mapped:   9728K popped:     413 pushed:      83 inuse:    330 total:    333 rss:      0K releases:    106 last released:    132K region: 0x7bf4e09000 (0x7bf4e02000)
07-10 13:09:37.173 22768 23086 I scudo   :   31 ( 33296): mapped:   3840K popped:     835 pushed:     735 inuse:    100 total:    114 rss:      0K releases:    170 last released:    412K region: 0x7c04e04000 (0x7c04e02000)
07-10 13:09:37.173 22768 23086 I scudo   :   32 ( 65552): mapped:   7424K popped:     187 pushed:      76 inuse:    111 total:    115 rss:      0K releases:     83 last released:   4212K region: 0x7c14e12000 (0x7c14e02000)
07-10 13:09:37.173 22768 23086 I scudo   : Scudo OOM: The process has exhausted 256M for size class 64.
```

Which is one thing, but the worse part is that in freshly installed v4.8.0 there is still the same detour.

@yuriiurshuliak could you please zoom in? I see something suspicious in that screenshot.

**Comment by gabortim** [comment]
I can still reproduce the issue on OsmAnd 4.9.10.
