### ISSUE TITLE
crash after editing a track

### ISSUE THREAD

**Issue by seahorse41** [osmandapp/OsmAnd#20293]
### Description

After editing a track, osmand crashes. I managed to duplicate it and record the steps to reproduce. An exception log was generated.

### Steps to reproduce

(parenthesis are my comments) [brackets are copy of screen for key words, buttons]

Start OsmAnd~
(create the prerequisite track near another existing track)
Plan a route , Create new route , Add , Add , Points , drag 1 to 2 to swap order , Back , Add , Options , Save as new track , select folder, name , Save , Open saved track , Appearance , toggle Show start and finish icons , select color , Custom (1px) , Apply , Back (looks correct) 

(Bonus 2nd crash scenario for joan: still shows edit screen, press) back , back (to only showing map.)
Back (to Close app), Reopen app, [Unfortunately OsmAnd has crashed] 
(That's a different crash trigger then I was trying to reproduce, so the above "prerequisite" is included if it is part of a crash step of it's own.)
No crash log, so reopen app again, ok:
 (I see line width, color, icons have reverted to thick red with icons.)
Hold finger to select track , open track , appearance , icons,color,custom-1px , apply , back , back (should be back to before it crashed last, or before exiting last.)
(end bonus 2nd crash only for LG V30 running joan)

Hold to select (same track just created) , Open track , Options , Edit track , Points , 
(Key moment:) hold at node to select
  instead opens What's here: because 2 tracks close to each other, 
select same as was editing , open track , options , edit track , Points , delete #1 , (color changed) , slide to swap order , back , pan to choose new point location , add , options , save changes , (GPX file saved to ...) , back , (see the screen just before it crashed the first time:)
[ Move Point , Cancel , [Apply] ] , 
Press Apply, 
[Unfortunately OsmAnd~ has stopped. [Open app again] ]
   Crash Last OsmAnd run crashed. Please help us improve OsmAnd by sharing the error message. [Send]

### Actual result

Not supposed to crash, or get lost regarding which track in memory is being edited.

### Expected result

Either 1. select the node when I touch-hold at the node, instead of starting a second instance of editing the track
and/or 2. Remember the appearance changes (but that was only for LG V30 joan)
3. save the track in such a way it replaces the track being edited, instead of orphaning the first track being edited.

### Your Environment (required)

OsmAnd Version: OsmAnd~ 3.9.4 / 4.6.14 461403
Android/iOS version: 7.1.2
Device model: joan
Crash-Logs: attachment by email
```

2nd device, confirmed the primary crash being reported
Device : OnePlus6TSingle
Brand : OnePlus
Manufacturer : OnePlus
Model : ONEPLUS A6013
Product : OnePlus6TSingle
Build : ONEPLUS A6013_34_211123
Version : 11
App Version : OsmAnd~
Apk Version : 4.6.14 461403 

Version  OsmAnd~ 4.6.14
11.07.2024 10:06:42
Apk Version : 4.6.14 461403
Exception occurred in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to read from field 'double net.osmand.gpx.GPXUtilities$WptPt.lat' on a null object reference
	at net.osmand.gpx.GPXUtilities$WptPt.<init>(GPXUtilities.java:258)
	at net.osmand.plus.measurementtool.MeasurementToolLayer.getMovedPointToApply(MeasurementToolLayer.java:935)
	at net.osmand.plus.measurementtool.MeasurementToolFragment.applyMovePointMode(MeasurementToolFragment.java:1606)
	at net.osmand.plus.measurementtool.MeasurementToolFragment.lambda$onCreateView$4$net-osmand-plus-measurementtool-MeasurementToolFragment(MeasurementToolFragment.java:419)
	at net.osmand.plus.measurementtool.MeasurementToolFragment$$ExternalSyntheticLambda5.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7520)
	at android.view.View.performClickInternal(View.java:7489)
	at android.view.View.access$3600(View.java:826)
	at android.view.View$PerformClick.run(View.java:28555)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8068)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

**Comment by seahorse41** [comment]
After confirming the sequence to generate the crash, I tried again and skipped the key mistake that can be ascribed to an amateur at editing, or just an accidental long-touch..., and it did not crash after saving changes with only 1 instance of the track being edited.
Next I upgraded to 471703
and duplicated the crash still occurs when "accidentally" editing two instances of the same track.

A bit of good news, Joan on the LG V30 did not have the bonus crash this time, and did not get lost needing the back,back after saving changes. So... ignore the extra bonus fluff, I guess.
