### ISSUE TITLE
Android app crashes

### ISSUE THREAD

**Issue by daPhipz** [osmandapp/OsmAnd#20306]
### Description

Since two weeks ago, the app crashes whenever I open it. First, it gets unresponsive and laggy, then it crashes.

### Steps to reproduce

1. Open the app
2. Wait

### Actual result

App crashes, closes.
The entire Android launcher rebuilds, as if the device was restarted. Any app playing media in the background stops, the media isn't played anymore. Possible memory leak in OSMAnd?

### Expected result

The app is usable

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.7.17, released on 2024-05-07
Android/iOS version: 14
Device model:
Crash-Logs: 

Version  OsmAnd 4.7.17
27.06.2024 10:28:27
Apk Version : 4.7.17 4717
Exception occurred in thread Thread[main,5,main] : 
java.lang.OutOfMemoryError
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1217)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1174)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1122)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1081)
	at android.graphics.drawable.RippleDrawable.updateMaskShaderIfNeeded(RippleDrawable.java:1136)
	at android.graphics.drawable.RippleDrawable.updateRipplePaint(RippleDrawable.java:1258)
	at android.graphics.drawable.RippleForeground.startHardwareEnter(RippleForeground.java:255)
	at android.graphics.drawable.RippleForeground.enter(RippleForeground.java:304)
	at android.graphics.drawable.RippleDrawable.tryRippleEnter(RippleDrawable.java:734)
	at android.graphics.drawable.RippleDrawable.setRippleActive(RippleDrawable.java:369)
	at android.graphics.drawable.RippleDrawable.onStateChange(RippleDrawable.java:358)
	at android.graphics.drawable.Drawable.setState(Drawable.java:840)
	at android.view.View.drawableStateChanged(View.java:26220)
	at android.view.ViewGroup.drawableStateChanged(ViewGroup.java:8087)
	at android.view.View.refreshDrawableState(View.java:26302)
	at android.view.ViewGroup.drawableStateChanged(ViewGroup.java:8101)
	at android.view.View.refreshDrawableState(View.java:26302)
	at android.view.View.setPressed(View.java:13915)
	at android.view.ViewGroup.dispatchSetPressed(ViewGroup.java:4898)
	at android.view.View.setPressed(View.java:13917)
	at android.view.View.setPressed(View.java:13893)
	at android.view.View.onTouchEvent(View.java:18286)
	at android.view.View.dispatchTouchEvent(View.java:16225)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3322)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2982)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2939)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2939)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2939)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2939)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2939)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2939)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2939)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2939)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:776)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1967)
	at android.app.Dialog.dispatchTouchEvent(Dialog.java:1324)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:734)
	at android.view.View.dispatchPointerEvent(View.java:16489)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:8602)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:8353)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7682)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7739)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7705)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7908)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7713)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7965)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7686)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7739)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7705)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7713)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7686)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:11250)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:11119)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:11075)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:11384)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:337)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:187)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```

**Comment by yuriiurshuliak** [comment]
The crash you attached is due to an OutOfMemoryError, indicating insufficient RAM. Could you confirm if you have tracks with a large number of points or online maps enabled?

Additionally, the logs you provided are dated 06/27/2024, which means they might be from a previous crash. Please make sure that live updates are disabled and deleted, clear the cache, and then enable and redownload the updates.

Please provide detailed steps on how the app crashes, including the exact conditions. Also, share the exact coordinates where the crash occurs.

**Comment by sleepy-nols** [comment]
I had the same problem since about 2 or 3 weeks, after re-installing the app everything works normal again.

**Comment by vshcherb** [comment]
Memory leak is possible though we didn't identify it yet with out testing devices

**Comment by daPhipz** [comment]
> Could you confirm if you have tracks with a large number of points or online maps enabled?

I don't think I did.

I deleted all user data and reinstalled the app, that fixed my issue for now.

**Comment by sleepy-nols** [comment]
So after re-enabling the map live updates the app crashes again. Are live updates not supported?

**Comment by vshcherb** [comment]
Did you update to August maps before enabling live updates?

**Comment by sleepy-nols** [comment]
No I did not, still on Juli, I guess thats the issue?
