### ISSUE TITLE
Crash when deleting track from Smart folder

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#20661]
### Description

Osmand crashes when deleting a track from smart folder.

```
Version  OsmAnd~ 4.9.0#3047m
21.08.2024 10:05:41
Apk Version : 4.9.0#3047m 4900
Exception occurred in thread Thread[AsyncTask #4,5,main] : 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:10558)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:2237)
	at android.view.View.requestLayout(View.java:27049)
	at android.view.View.requestLayout(View.java:27049)
	at android.view.View.requestLayout(View.java:27049)
	at android.view.View.requestLayout(View.java:27049)
	at android.view.View.requestLayout(View.java:27049)
	at android.view.View.requestLayout(View.java:27049)
	at android.view.View.requestLayout(View.java:27049)
	at android.view.View.requestLayout(View.java:27049)
	at android.view.View.requestLayout(View.java:27049)
	at android.view.View.requestLayout(View.java:27049)
	at android.view.View.requestLayout(View.java:27049)
	at androidx.recyclerview.widget.RecyclerView.requestLayout(RecyclerView.java:4412)
	at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.onChanged(RecyclerView.java:5541)
	at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyChanged(RecyclerView.java:12253)
	at androidx.recyclerview.widget.RecyclerView$Adapter.notifyDataSetChanged(RecyclerView.java:7354)
	at net.osmand.plus.myplaces.tracks.dialogs.TrackFoldersAdapter.setItems(TrackFoldersAdapter.java:98)
	at net.osmand.plus.myplaces.tracks.dialogs.BaseTrackFolderFragment.updateContent(BaseTrackFolderFragment.java:277)
	at net.osmand.plus.myplaces.tracks.dialogs.TrackFolderFragment.updateContent(TrackFolderFragment.java:173)
	at net.osmand.plus.myplaces.tracks.dialogs.SmartFolderFragment.onSmartFolderUpdated(SmartFolderFragment.kt:122)
	at net.osmand.plus.myplaces.tracks.filters.SmartFolderHelper.notifyFolderUpdatedListeners(SmartFolderHelper.kt:132)
	at net.osmand.plus.myplaces.tracks.filters.SmartFolderHelper.updateSmartFolderItems(SmartFolderHelper.kt:264)
	at net.osmand.plus.myplaces.tracks.filters.SmartFolderHelper.updateAllSmartFoldersItems(SmartFolderHelper.kt:303)
	at net.osmand.plus.myplaces.tracks.filters.SmartFolderHelper.onGpxFileDeleted(SmartFolderHelper.kt:242)
	at net.osmand.plus.utils.FileUtils.removeGpxFile(FileUtils.java:182)
	at net.osmand.plus.myplaces.tracks.tasks.DeleteTracksTask.deleteTrackItems(DeleteTracksTask.java:59)
	at net.osmand.plus.myplaces.tracks.tasks.DeleteTracksTask.doInBackground(DeleteTracksTask.java:43)
	at net.osmand.plus.myplaces.tracks.tasks.DeleteTracksTask.doInBackground(DeleteTracksTask.java:21)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more
```

### Steps to reproduce

1. Menu
2. My places
3. Tracks
4. Go to smart folder
5. Click on the three dots and select delete
6. Confirm 
Crash

### Actual result

Crash

### Expected result

No crash

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
The bug could not be reproduced. To test, I created a smart folder and added tracks to it. Then, I attempted to delete these tracks from the folder.

The app performed smoothly, deleting all tracks correctly without any crashes.

OsmAnd~ 4.9.0#3049m, released: 2024-08-22

https://github.com/user-attachments/assets/76da9419-84fe-4b0b-afc0-e08739b3e4a3

**Comment by Nine-Tailed** [comment]
@yuriiurshuliak, try deleting the three dots from the track.
![Screenshot_2024-08-22-10-57-31-089_net.osmand.plus-edit.jpg](https://github.com/user-attachments/assets/3e72902a-bc30-466e-9c4e-560767349ca4)

**Comment by Nine-Tailed** [comment]
@yuriiurshuliak, try deleting using three dots from the track.
![Screenshot_2024-08-22-10-57-31-089_net.osmand.plus-edit.jpg](https://github.com/user-attachments/assets/3e72902a-bc30-466e-9c4e-560767349ca4)

**Comment by yuriiurshuliak** [comment]
Thank you for the clarification; you're correct. The bug has been reproduced. To reproduce it, create a smart folder and attempt to delete a track from the folder by using the three dots on the right side of the track.

As a result, the app crashes.

Here are my crash logs: [exception (19).zip](https://github.com/user-attachments/files/16707581/exception.19.zip)

OsmAnd~ 4.9.0#3049m, released: 2024-08-22

https://github.com/user-attachments/assets/d15de7f8-ab95-4cf0-abbb-75f692376e58
