### ISSUE TITLE
OsmAnd Crashes after loading render.xml with errors inside

### ISSUE THREAD

**Issue by hhornburg** [osmandapp/OsmAnd#20774]
### Description

I imported a `.render.xml` into OsmAnd which referenced a non-existing `renderingConstant`. Now I can't open OsmAnd again to load a fixed version of the `.render.xml` since osmand crashes on startup.

### Steps to reproduce

- Import a `.render.xml` where a `renderingConstant` is referenced which is not defined.
-  Close app
- Try to open app

### Actual result

- App crashes after it has been closed once

### Expected result

- `.render.xml` is parsed upon import and import is refused when there are errors in the file.
- In no case should the app crash

### Your Environment (required)

```
OsmAnd Version: 4.8.5
Android/iOS version: Android 11
Device model: SM-A520F
Crash-Logs: None
```

**Comment by vshcherb** [comment]
If you don't have access to the file storage of OsmAnd (Shared folder) indeed you're stuck and app need to be reinstalled. If you provide crash logs, probably we can fix it quickly

**Comment by hhornburg** [comment]
I managed to access the contents of `net.osmand.plus` via adb and edit the file to remove the error.

As for the crash logs there seems to be another bug. When I try to export them, no file is generated, no matter what app I try to send it with. (Some apps go into an infinite loop, some report an internal error and others just have no attached file).
Can I find the logs somewhere in `net.osmand.plus` so I can pull them over to my laptop manually?

**Comment by mariush444** [comment]
My log with this pub below ....
Version  OsmAnd~ 4.5.10
09.09.2024 9:21:26
Apk Version : 4.5.10 451003
Exception occured in thread Thread[pool-15-thread-1,5,main] : 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.IllegalStateException: Rendering constant or attribute 'color_red' was not specified.
	at net.osmand.render.RenderingRulesStorage$RenderingRulesHandler.parseAttributes(RenderingRulesStorage.java:438)
	at net.osmand.render.RenderingRulesStorage$RenderingRulesHandler.parse(RenderingRulesStorage.java:278)
	at net.osmand.render.RenderingRulesStorage.parseRulesFromXmlInputStream(RenderingRulesStorage.java:134)
	at net.osmand.plus.render.RendererRegistry.loadRenderer(RendererRegistry.java:176)
	at net.osmand.plus.render.RendererRegistry.lambda$loadRenderer$0$net-osmand-plus-render-RendererRegistry(RendererRegistry.java:183)
	at net.osmand.plus.render.RendererRegistry$$ExternalSyntheticLambda0.resolve(Unknown Source:6)
	at net.osmand.render.RenderingRulesStorage$RenderingRulesHandler.startElement(RenderingRulesStorage.java:397)
	at net.osmand.render.RenderingRulesStorage$RenderingRulesHandler.parse(RenderingRulesStorage.java:293)
	at net.osmand.render.RenderingRulesStorage.parseRulesFromXmlInputStream(RenderingRulesStorage.java:134)
	at net.osmand.plus.render.RendererRegistry.loadRenderer(RendererRegistry.java:176)
	at net.osmand.plus.render.RendererRegistry.getRenderer(RendererRegistry.java:114)
	at net.osmand.plus.render.UpdateVectorRendererAsyncTask.doInBackground(UpdateVectorRendererAsyncTask.java:32)
	at net.osmand.plus.render.UpdateVectorRendererAsyncTask.doInBackground(UpdateVectorRendererAsyncTask.java:15)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

**Comment by hhornburg** [comment]
Thanks @mariush444 !

**Comment by vshcherb** [comment]
Crash is fixed to prevent crash of the app
