### ISSUE TITLE
The app crashes when trying to apply a filter to a track

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#20794]
### Description

The app crashes when trying to apply a filter to a track.
```
Version  OsmAnd~ 4.9.0#3151m
09.09.2024 3:24:46
Apk Version : 4.9.0#3151m 4900
Exception occurred in thread Thread[main,5,main] : 
android.database.sqlite.SQLiteException: no such column: totalDistance (code 1 SQLITE_ERROR): , while compiling: UPDATE gpxDirTable SET fileName = ?, fileDir = ?, totalDistance = ?, totalTracks = ?, startTime = ?, endTime = ?, timeSpan = ?, timeMoving = ?, totalDistanceMoving = ?, diffElevationUp = ?, diffElevationDown = ?, avgElevation = ?, minElevation = ?, maxElevation = ?, minSpeed = ?, maxSpeed = ?, avgSpeed = ?, points = ?, wptPoints = ?, color = ?, fileLastModifiedTime = ?, fileLastUploadedTime = ?, fileCreationTime = ?, splitType = ?, splitInterval = ?, apiImported = ?, wptCategoryNames = ?, showAsMarkers = ?, joinSegments = ?, showArrows = ?, showStartFinish = ?, track_visualization_type = ?, track_3d_wall_coloring_type = ?, track_3d_line_position_type = ?, additional_exaggeration = ?, elevation_meters = ?, width = ?, gradientScaleType = ?, colorPalette = ?, smoothingThreshold = ?, minFilterSpeed = ?, maxFilterSpeed = ?, minFilterAltitude = ?, maxFilterAltitude = ?, maxFilterHdop = ?, startLat = ?, startLon = ?, nearestCityName = ?, maxSensorTemperature = ?, avgSensorTemperature = ?, maxSensorSpeed = ?, avgSensorSpeed = ?, maxSensorPower = ?, avgSensorPower = ?, maxSensorCadence = ?, avgSensorCadence = ?, maxSensorHr = ?, avgSensorHr = ?, dataVersion = ? WHERE fileName = ? AND fileDir = ?
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1068)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:673)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:62)
	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:34)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2086)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2064)
	at net.osmand.shared.api.SQLiteAPIImpl$SQLiteDatabaseWrapper.execSQL(SQLiteAPIImpl.kt:51)
	at net.osmand.shared.gpx.GpxDatabase.updateGpxParameters(GpxDatabase.kt:94)
	at net.osmand.shared.gpx.GpxDatabase.updateGpxParameters(GpxDatabase.kt:80)
	at net.osmand.shared.gpx.GpxDatabase.updateDataItem(GpxDatabase.kt:69)
	at net.osmand.plus.track.helpers.GpxDbHelper.updateDataItem(GpxDbHelper.java:139)
	at net.osmand.plus.track.cards.GpsFiltersCard.updateGpsFilters(GpsFiltersCard.java:212)
	at net.osmand.plus.track.cards.GpsFiltersCard.lambda$setupSlider$3(GpsFiltersCard.java:192)
	at net.osmand.plus.track.cards.GpsFiltersCard.$r8$lambda$j1loJrQY6ctyEdVesEEzlFxVGrU(Unknown Source:0)
	at net.osmand.plus.track.cards.GpsFiltersCard$$ExternalSyntheticLambda1.onValueChange(Unknown Source:11)
	at com.google.android.material.slider.Slider$OnChangeListener.onValueChange(Slider.java:45)
	at com.google.android.material.slider.BaseSlider.dispatchOnChangedFromUser(BaseSlider.java:2371)
	at com.google.android.material.slider.BaseSlider.snapThumbToValue(BaseSlider.java:2117)
	at com.google.android.material.slider.BaseSlider.snapActiveThumbToValue(BaseSlider.java:2102)
	at com.google.android.material.slider.BaseSlider.snapTouchPosition(BaseSlider.java:2098)
	at com.google.android.material.slider.BaseSlider.onTouchEvent(BaseSlider.java:1980)
	at com.google.android.material.slider.Slider.onTouchEvent(Slider.java:42)
	at android.view.View.dispatchTouchEvent(View.java:15160)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3152)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2820)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3152)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2820)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3152)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2820)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3152)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2820)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3152)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2820)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3152)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2820)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3152)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2820)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3152)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2820)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3152)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2820)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3152)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2820)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3188)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2820)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3152)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2820)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3152)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2820)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3152)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2820)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3152)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2820)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3152)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2820)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3152)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2820)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3152)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2820)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3152)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2820)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:579)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1903)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4456)
	at net.osmand.plus.activities.MapActivity.dispatchTouchEvent(MapActivity.java:1381)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:537)
	at android.view.View.dispatchPointerEvent(View.java:15435)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7316)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7086)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6505)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6562)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6528)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6693)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6536)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6750)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6509)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6562)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6528)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6536)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6509)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9714)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9665)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9633)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9870)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:298)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:270)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:9799)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:9968)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1505)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1513)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1128)
	at android.view.Choreographer.doFrame(Choreographer.java:1034)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1481)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8503)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

```

### Steps to reproduce

1. Select track on map
2. Press option 
3. Select item gps filter
Crash

### Actual result

Crash

### Expected result

No crash 

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:OsmAnd~ 4.9.0#3151m, Дата выпуска: 2024-09-09
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. To reproduce, select a track, open the context menu, choose options, and then select GPS Filter.

Everything displayed correctly without any crashes. Please try updating the app or using the latest nightly version for further testing.

OsmAnd~ 4.9.0#3157m, released: 2024-09-10

https://github.com/user-attachments/assets/6890aeb0-234d-42bd-a598-5f291f891e07

**Comment by Nine-Tailed** [comment]
osmand stopped crashing, now there is another problem - it stopped displaying tracks on the map until you change its appearance.

**Comment by mic140** [comment]
> The bug was not reproduced. To reproduce, select a track, open the context menu, choose options, and then select GPS Filter.
> 
> Everything displayed correctly without any crashes. Please try updating the app or using the latest nightly version for further testing.
> 
> OsmAnd~ 4.9.0#3157m, released: 2024-09-10
> 
>  video_2024-09-10_17-01-04.mp4

try changing the filter parameters

**Comment by Nine-Tailed** [comment]
After changing the appearance of the track so that it would be displayed on the map, I applied the filter again and the osmand crashed again.
OsmAnd~ 4.9.0#3162m, Дата выпуска: 2024-09-10

**Comment by Chumva** [comment]
@Nine-Tailed can you share new exception.log?

**Comment by Nine-Tailed** [comment]
@Chumva
![exception.zip](https://github.com/user-attachments/files/16963642/exception.zip)

**Comment by Nine-Tailed** [comment]
video in telegram chat with these bugs:
https://t.me/ruosmand/161171
https://t.me/ruosmand/161172

**Comment by yuriiurshuliak** [comment]
The bug has been successfully reproduced. To reproduce the crashes, follow these steps:

- For the first crash: Go to Menu → My Places → At the top, click "New track." The application will crash.

- For the second crash: Select any track, change its appearance, after that go to options, choose GPS Filter, scroll, and select any option. The application will crash again.

Here are the corresponding crash logs: [exception (21).zip](https://github.com/user-attachments/files/17011493/exception.21.zip)

OsmAnd~ 4.9.0#3193m, released: 2024-09-16

<table style="width:100%">
  </tr>
  <tr>
    <td> <video source src="https://github.com/user-attachments/assets/58fd22de-8133-46ab-8d33-593bbc626471"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/user-attachments/assets/1021f5ee-038b-4799-9903-edbd3670b0a7"  width="300" height="auto"/>   </td>
  </tr>
</table>
