### ISSUE TITLE
Osmand crashes when opening navigation's settings menu

### ISSUE THREAD

**Issue by enomat** [osmandapp/Osmand#2084]
-start a navigation
-press the settings icon in the navigation panel

Osmand crashes. Crash report:

<pre>
Version  OsmAnd~ 2.3.0#6402MQA
24.12.2015 9:18:17
Apk Version : 2.3.0#6402MQA 231
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException
	at com.android.internal.os.LoggingPrintStream.println(LoggingPrintStream.java:298)
	at net.osmand.plus.helpers.FileNameTranslationHelper.getVoiceName(FileNameTranslationHelper.java:90)
	at net.osmand.plus.mapcontextmenu.other.RoutePreferencesMenu$3.getView(RoutePreferencesMenu.java:333)
	at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)
	at android.widget.AbsListView.obtainView(AbsListView.java:2465)
	at android.widget.ListView.makeAndAddView(ListView.java:1775)
	at android.widget.ListView.fillDown(ListView.java:678)
	at android.widget.ListView.fillFromTop(ListView.java:739)
	at android.widget.ListView.layoutChildren(ListView.java:1628)
	at android.widget.AbsListView.onLayout(AbsListView.java:2300)
	at android.view.View.layout(View.java:14072)
	at android.view.ViewGroup.layout(ViewGroup.java:4607)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14072)
	at android.view.ViewGroup.layout(ViewGroup.java:4607)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14072)
	at android.view.ViewGroup.layout(ViewGroup.java:4607)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14072)
	at android.view.ViewGroup.layout(ViewGroup.java:4607)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14072)
	at android.view.ViewGroup.layout(ViewGroup.java:4607)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1043)
	at android.view.View.layout(View.java:14072)
	at android.view.ViewGroup.layout(ViewGroup.java:4607)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14072)
	at android.view.ViewGroup.layout(ViewGroup.java:4607)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1655)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1513)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1426)
	at android.view.View.layout(View.java:14072)
	at android.view.ViewGroup.layout(ViewGroup.java:4607)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14072)
	at android.view.ViewGroup.layout(ViewGroup.java:4607)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1655)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1513)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1426)
	at android.view.View.layout(View.java:14072)
	at android.view.ViewGroup.layout(ViewGroup.java:4607)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14072)
	at android.view.ViewGroup.layout(ViewGroup.java:4607)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1997)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1818)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4526)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
	at android.view.Choreographer.doCallbacks(Choreographer.java:555)
	at android.view.Choreographer.doFrame(Choreographer.java:525)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
	at android.os.Handler.handleCallback(Handler.java:615)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4921)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
	at dalvik.system.NativeStart.main(Native Method)
Version  OsmAnd~ 2.3.0#6402MQA
24.12.2015 9:18:17
Apk Version : 2.3.0#6402MQA 231
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException
	at com.android.internal.os.LoggingPrintStream.println(LoggingPrintStream.java:298)
	at net.osmand.plus.helpers.FileNameTranslationHelper.getVoiceName(FileNameTranslationHelper.java:90)
	at net.osmand.plus.mapcontextmenu.other.RoutePreferencesMenu$3.getView(RoutePreferencesMenu.java:333)
	at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)
	at android.widget.AbsListView.obtainView(AbsListView.java:2465)
	at android.widget.ListView.makeAndAddView(ListView.java:1775)
	at android.widget.ListView.fillDown(ListView.java:678)
	at android.widget.ListView.fillFromTop(ListView.java:739)
	at android.widget.ListView.layoutChildren(ListView.java:1628)
	at android.widget.AbsListView.onLayout(AbsListView.java:2300)
	at android.view.View.layout(View.java:14072)
	at android.view.ViewGroup.layout(ViewGroup.java:4607)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14072)
	at android.view.ViewGroup.layout(ViewGroup.java:4607)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14072)
	at android.view.ViewGroup.layout(ViewGroup.java:4607)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14072)
	at android.view.ViewGroup.layout(ViewGroup.java:4607)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14072)
	at android.view.ViewGroup.layout(ViewGroup.java:4607)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1043)
	at android.view.View.layout(View.java:14072)
	at android.view.ViewGroup.layout(ViewGroup.java:4607)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14072)
	at android.view.ViewGroup.layout(ViewGroup.java:4607)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1655)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1513)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1426)
	at android.view.View.layout(View.java:14072)
	at android.view.ViewGroup.layout(ViewGroup.java:4607)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14072)
	at android.view.ViewGroup.layout(ViewGroup.java:4607)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1655)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1513)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1426)
	at android.view.View.layout(View.java:14072)
	at android.view.ViewGroup.layout(ViewGroup.java:4607)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14072)
	at android.view.ViewGroup.layout(ViewGroup.java:4607)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1997)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1818)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4526)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
	at android.view.Choreographer.doCallbacks(Choreographer.java:555)
	at android.view.Choreographer.doFrame(Choreographer.java:525)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
	at android.os.Handler.handleCallback(Handler.java:615)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4921)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
	at dalvik.system.NativeStart.main(Native Method)

</pre>

**Comment by vshcherb** [comment]
Can't reproduce it in today's build. The exception looks weird and not related to OsmAnd code in the end of stack traced.

**Comment by enomat** [comment]
Today I couldn't reproduce it, but after some trying, I can.

1. Clear OsmAnd's data (or do a fresh install)
2. Launch OsmAnd (when it say "Enter country name" press SKIP)
3. Start navigation (touch the right arrow icon at the bottom)
4. Press CANCEL when "Select voice guidance" popup appear
5. Press the gear icon to open navigation settings

Osmand will crash.

6. Go back to step 4. At "Select voice guidance" popup, choose any TTS voice and press APPLY

Now Osmand will not crash.

So if you have selected a voice data, osmand will not crash. Otherwise it will.

(Tested on Samsung Galaxy S2 I9100 Android 4.1.2 with latest Osmand nightly.)

**Comment by crimean** [comment]
The issue has been fixed
