### ISSUE TITLE
Map Creation crashes when there is no coastline in rendering_types.xml

### ISSUE THREAD

**Issue by hhornburg** [osmandapp/OsmAnd#20897]
### Description

When trying to create a map using `utilities.sh` with a `rendering_types.xml` that lacks `<type tag="natural" value="coastline" minzoom="1" />` the creation of the map crashes

### Steps to reproduce

create a map with a `rendering_types.xml` that lacks `<type tag="natural" value="coastline" minzoom="1" />`

### Actual result

Crash after quite some time of computation

### Expected result

No Crash.
If not possible, exit with an error right at the beginning of the processing.
Alternatively provide an xsd so one can check whether the rendering_types is correct.

### Your Environment (required)

```
SEVERE: Log exception
java.lang.NullPointerException: Cannot invoke "net.osmand.osm.MapRenderingTypes$MapRulType.getInternalId()" because the return value of "net.osmand.osm.MapRenderingTypesEncoder.getCoastlineRuleType()" is null
	at net.osmand.obf.preparation.IndexVectorMapCreator.processingLowLevelWays(IndexVectorMapCreator.java:513)
	at net.osmand.obf.preparation.IndexCreator.generateIndexes(IndexCreator.java:587)
	at net.osmand.obf.preparation.IndexCreator.generateIndexes(IndexCreator.java:484)
	at net.osmand.MainUtilities.generateObf(MainUtilities.java:334)
	at net.osmand.MainUtilities.mainException(MainUtilities.java:162)
	at net.osmand.MainUtilities.main(MainUtilities.java:76)

java.lang.NullPointerException: Cannot invoke "net.osmand.osm.MapRenderingTypes$MapRulType.getInternalId()" because the return value of "net.osmand.osm.MapRenderingTypesEncoder.getCoastlineRuleType()" is null
	at net.osmand.obf.preparation.IndexVectorMapCreator.processingLowLevelWays(IndexVectorMapCreator.java:513)
	at net.osmand.obf.preparation.IndexCreator.generateIndexes(IndexCreator.java:587)
	at net.osmand.obf.preparation.IndexCreator.generateIndexes(IndexCreator.java:484)
	at net.osmand.MainUtilities.generateObf(MainUtilities.java:334)
	at net.osmand.MainUtilities.mainException(MainUtilities.java:162)
	at net.osmand.MainUtilities.main(MainUtilities.java:76)
```

**Comment by vshcherb** [comment]
We don't plan to support it. Yes you need ```<type tag="natural" value="coastline" minzoom="1" />```
