### ISSUE TITLE
Problem with creating smart folder

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#20918]
### Description

When creating a smart folder, not a single track is displayed.
There is an assumption that this is related to the average/max speed. in addition, when trying to increase the average speed or max speed values, the application crashes.
Video in telegram chat:
https://t.me/ruosmand/162474

exception.log:
![files.zip](https://github.com/user-attachments/files/17152006/files.zip)

### Steps to reproduce

.

### Actual result

.

### Expected result

.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:OsmAnd~ 4.9.0#3295m, Дата выпуска: 2024-09-26
Android/iOS version:13
Device model:poco f3
Crash-Logs: ?
```

**Comment by Nine-Tailed** [comment]
The problem is not solved in full. I attached a video and a log, where when changing the average or maximum speed the application crashes.
```
Version  OsmAnd~ 4.9.0#3321m
30.09.2024 6:47:10
Apk Version : 4.9.0#3321m 4900
Exception occurred in thread Thread[main,5,main] : 
java.lang.IllegalStateException: Slider value(250.0) must be greater or equal to valueFrom(0.0), and lower or equal to valueTo(4.0)
	at com.google.android.material.slider.BaseSlider.validateValues(BaseSlider.java:575)
	at com.google.android.material.slider.BaseSlider.validateConfigurationIfDirty(BaseSlider.java:628)
	at com.google.android.material.slider.BaseSlider.onDraw(BaseSlider.java:1771)
	at android.view.View.draw(View.java:23845)
	at android.view.View.updateDisplayListIfDirty(View.java:22682)
	at android.view.View.draw(View.java:23559)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4344)
	at android.view.View.updateDisplayListIfDirty(View.java:22671)
	at android.view.View.draw(View.java:23559)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4586)
	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5030)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4344)
	at android.view.View.draw(View.java:23850)
	at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4429)
	at android.view.View.updateDisplayListIfDirty(View.java:22682)
	at android.view.View.draw(View.java:23559)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4344)
	at android.view.View.updateDisplayListIfDirty(View.java:22671)
	at android.view.View.draw(View.java:23559)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4344)
	at android.view.View.draw(View.java:23850)
	at android.view.View.updateDisplayListIfDirty(View.java:22682)
	at android.view.View.draw(View.java:23559)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4344)
	at android.view.View.updateDisplayListIfDirty(View.java:22671)
	at android.view.View.draw(View.java:23559)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4344)
	at android.view.View.updateDisplayListIfDirty(View.java:22671)
	at android.view.View.draw(View.java:23559)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4344)
	at android.view.View.draw(View.java:23850)
	at com.android.internal.policy.DecorView.draw(DecorView.java:915)
	at android.view.View.updateDisplayListIfDirty(View.java:22682)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:685)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:693)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5198)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4899)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4047)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2725)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9812)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1505)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1513)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1128)
	at android.view.Choreographer.doFrame(Choreographer.java:1042)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1481)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8503)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

```

**Comment by alex-osm** [comment]
@Nine-Tailed There is no video attached. Could you please reattach it?

**Comment by Nine-Tailed** [comment]
@alex-osm, 
https://github.com/user-attachments/assets/22d50641-b528-4825-b2dd-3e9e68ca6e3c

**Comment by Nine-Tailed** [comment]
somehow my osmand keeps crashing with this error.
```
Version  OsmAnd~ 4.9.0#3339m
02.10.2024 11:36:23
Apk Version : 4.9.0#3339m 4900
Exception occurred in thread Thread[main,5,main] : 
java.lang.IllegalStateException: Slider value(250.0) must be greater or equal to valueFrom(0.0), and lower or equal to valueTo(5.0)
	at com.google.android.material.slider.BaseSlider.validateValues(BaseSlider.java:575)
	at com.google.android.material.slider.BaseSlider.validateConfigurationIfDirty(BaseSlider.java:628)
	at com.google.android.material.slider.BaseSlider.onDraw(BaseSlider.java:1771)
	at android.view.View.draw(View.java:23845)
	at android.view.View.updateDisplayListIfDirty(View.java:22682)
```

**Comment by Nine-Tailed** [comment]
It seems to me that the problem is in scanning the folder with tracks, after reinstalling osmand I copy it manually to the osmand folder. Then on the tracks tab the scanning progress spins endlessly, I have 685 tracks. 
At this point, to be honest, I would like to see clear progress with percentages, maybe even a modal window, otherwise this circle spins and it is not clear how much longer to wait and whether the process is going on at all.

**Comment by Nine-Tailed** [comment]
What's also interesting is that I deleted the tracks folder via the file manager, went into osmand and tried again to change the average speed in the smart folder and the application crashed again.
That's why I'm inclined to think that the problem is precisely in scanning the tracks folder and collecting statistics.

**Comment by Nine-Tailed** [comment]
After another deletion of osmand settings in android and subsequent copying of the tracks folder, osmand stopped crashing with this error. I don't know if it's luck or the problem is solved.
