### ISSUE TITLE
Run time error

### ISSUE THREAD

**Issue by FWaqidi** [osmandapp/Osmand#2099]
12-30 19:50:11.487 5809-6079/net.osmand E/AndroidRuntime: FATAL EXCEPTION: Calculating position
                                                          Process: net.osmand, PID: 5809
                                                          java.lang.IllegalStateException: java.lang.IllegalArgumentException: is == null
                                                              at net.osmand.router.RoutingConfiguration.getDefault(RoutingConfiguration.java:171)
                                                              at net.osmand.plus.AppInitializer.getLazyDefaultRoutingConfig(AppInitializer.java:386)
                                                              at net.osmand.plus.OsmandApplication.getDefaultRoutingConfig(OsmandApplication.java:664)
                                                              at net.osmand.plus.CurrentPositionHelper.initCtx(CurrentPositionHelper.java:49)
                                                              at net.osmand.plus.CurrentPositionHelper.runUpdateInThread(CurrentPositionHelper.java:203)
                                                              at net.osmand.plus.CurrentPositionHelper.access$000(CurrentPositionHelper.java:24)
                                                              at net.osmand.plus.CurrentPositionHelper$1.run(CurrentPositionHelper.java:66)
                                                              at net.osmand.plus.routing.RoutingHelper$4.run(RoutingHelper.java:900)
                                                              at java.lang.Thread.run(Thread.java:841)
                                                           Caused by: java.lang.IllegalArgumentException: is == null
                                                              at org.kxml2.io.KXmlParser.setInput(KXmlParser.java:1625)
                                                              at net.osmand.router.RoutingConfiguration.parseFromInputStream(RoutingConfiguration.java:184)
                                                              at net.osmand.router.RoutingConfiguration.getDefault(RoutingConfiguration.java:169)
                                                              at net.osmand.plus.AppInitializer.getLazyDefaultRoutingConfig(AppInitializer.java:386) 
                                                              at net.osmand.plus.OsmandApplication.getDefaultRoutingConfig(OsmandApplication.java:664) 
                                                              at net.osmand.plus.CurrentPositionHelper.initCtx(CurrentPositionHelper.java:49) 
                                                              at net.osmand.plus.CurrentPositionHelper.runUpdateInThread(CurrentPositionHelper.java:203) 
                                                              at net.osmand.plus.CurrentPositionHelper.access$000(CurrentPositionHelper.java:24) 
                                                              at net.osmand.plus.CurrentPositionHelper$1.run(CurrentPositionHelper.java:66) 
                                                              at net.osmand.plus.routing.RoutingHelper$4.run(RoutingHelper.java:900)   at java.lang.Thread.run(Thread.java:841)

**Comment by vshcherb** [comment]
Something wrong with compilation of the project. The routing file is missing.
