### ISSUE TITLE
Osmand crashes when clicking on installed widgets in panels in screen settings

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#21063]
### Description

Osmand crashes when clicking on installed widgets in panels in screen settings.
https://github.com/user-attachments/assets/c2a7f22b-ab42-4283-987d-56c23a5ea41e
```
Version  OsmAnd~ 4.9.0#3470m
17.10.2024 12:32:25
Apk Version : 4.9.0#3470m 4900
Exception occurred in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean net.osmand.plus.views.mapwidgets.WidgetsPanel.isPanelVertical()' on a null object reference
	at net.osmand.plus.views.mapwidgets.WidgetType.getGroup(WidgetType.java:230)
	at net.osmand.plus.views.mapwidgets.configure.dialogs.WidgetInfoFragment.initFromBundle(WidgetInfoFragment.java:117)
	at net.osmand.plus.views.mapwidgets.configure.dialogs.WidgetInfoFragment.onCreateView(WidgetInfoFragment.java:89)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8503)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

### Steps to reproduce

.

### Actual result

Crash.

### Expected result

No crash.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:OsmAnd~ 4.9.0#3470m, Дата выпуска: 2024-10-16
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by Nine-Tailed** [comment]
Fixed OsmAnd~ 4.9.0#3476m, Дата выпуска: 2024-10-17
