### ISSUE TITLE
tap POI then crash

### ISSUE THREAD

**Issue by mariush444** [osmandapp/OsmAnd#21094]
### Description

After tapping a POI app crashes

### Steps to reproduce

Download Iraq map, go to 32.43994 43.60309 and tap icon pointed in the screenshot.
![crash](https://github.com/user-attachments/assets/5480ef28-5d1d-46ae-abc7-42e2cad9c0a9)

### Actual result

Crash

### Expected result

Don't crash

### Your Environment (required)

log
[log.zip](https://github.com/user-attachments/files/17455257/log.zip)

**Comment by yuriiurshuliak** [comment]
The issue could not be reproduced. To test, I navigated to the coordinates 32.43994, 43.60309, and selected the POI shown in the video.

The app did not crash and successfully displayed the context menu for the chosen POI.

After reviewing your crash logs, it appears the last crash occurred with version 4.5.10, so it’s likely the issue has been resolved in the latest update. Please make sure to update your app.

OsmAnd~ 4.9.0#3507m, released: 2024-10-21

https://github.com/user-attachments/assets/94391f1d-4d71-49eb-94d5-c17076d466d5

**Comment by DmitryAlexei** [comment]
@mariush444 Could you please provide your profile settings: menu > settings > export to file > chose all items under settings

**Comment by vshcherb** [comment]
From log file
```
21.10.2024 8:05:52
Apk Version : 4.5.10 451003
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalArgumentException: URLDecoder: Incomplete trailing escape (%) pattern
	at java.net.URLDecoder.decode(URLDecoder.java:196)
	at net.osmand.plus.mapcontextmenu.builders.AmenityMenuBuilder.getDecodedAdditionalInfo(AmenityMenuBuilder.java:234)
	at net.osmand.plus.mapcontextmenu.builders.AmenityMenuBuilder.getAdditionalCardParams(AmenityMenuBuilder.java:218)
``

4.5 is very outdated version, needs to be updated to 4.8-4.9

We have very similar bug with symptoms in nightly version but it https://github.com/osmandapp/OsmAnd/pull/21115/commits/d47a6394c50577c0e27ffb64406c81109d150381

**Comment by Chumva** [comment]
Duplicate - https://github.com/osmandapp/OsmAnd/issues/19494

**Comment by mariush444** [comment]
Here you are
[Export_2024-10-23.zip](https://github.com/user-attachments/files/17488634/Export_2024-10-23.zip)

ps
Admin should add possibility to upload osf format.
for this moment you have to change extension zip to osf
