### ISSUE TITLE
OSMAnd crashes on reaching destination

### ISSUE THREAD

**Issue by Goodingn** [osmandapp/Osmand#2120]
I typically have it set to GPX log automatically when Navigating, set to 1 second intervals.

**Comment by Goodingn** [comment]
Sorry, not related to gpx logging- it's crashed without logging and also not crashed (once) with auto logging.

**Comment by sonora** [comment]
I cannot reproduce this. Can you give more details under what circumstances this occurs, and with what version, settings, etc?

**Comment by noci2012** [comment]
I have seen it once, didn;t take a note on circumstances though, too busy driving...

**Comment by Goodingn** [comment]
Well, I had it navigate to two locations fine, one after another, at the weekend.  I was careful not to hit 'Go' until the route had been fully calculated.

I usually select a destination from POIPocket, share it with OSMand, hit the 'new' Navigate to button, then most of the time hit the Go button and start driving as the route continues to be calculated.

**Comment by Goodingn** [comment]
I have previously emailed in the crash reports when prompted to by OSMand.

**Comment by Goodingn** [comment]
That wasn't it either- pressing Go before nav had calculated. It's been strangely behaving itself :-/

**Comment by sonora** [comment]
OK, if you mailed the exception log, we can likely pinpoint the issue, (it should have gone to our support mailbox, I cannot verify right now).

**Comment by vshcherb** [comment]
Is it possible to attach the message from exception here? At least some top lines

**Comment by Goodingn** [comment]
Version  OsmAnd+ 2.2.2
26.11.2015 5:05:42
Apk Version : 2.2.2 222
Exception occured in thread Thread[Calculating position,5,main] : 
java.lang.RuntimeException: Loading data exception
	at net.osmand.router.RoutingContext.loadSubregionTile(RoutingContext.java:330)
	at net.osmand.router.RoutingContext.getRoutingTile(RoutingContext.java:505)
	at net.osmand.router.RoutingContext.loadTileData(RoutingContext.java:449)
	at net.osmand.router.RoutePlannerFrontEnd.findRouteSegment(RoutePlannerFrontEnd.java:61)
	at net.osmand.plus.CurrentPositionHelper.runUpdateInThread(CurrentPositionHelper.java:54)
	at net.osmand.plus.CurrentPositionHelper.runUpdateInThreadCatch(CurrentPositionHelper.java:100)
	at net.osmand.plus.CurrentPositionHelper$2.run(CurrentPositionHelper.java:80)
	at net.osmand.plus.routing.RoutingHelper$4.run(RoutingHelper.java:901)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.IOException: lseek failed: EBADF (Bad file number)
	at java.io.RandomAccessFile.seek(RandomAccessFile.java:602)
	at com.google.protobuf.CodedInputStream.seek(CodedInputStream.java:919)
	at net.osmand.binary.BinaryMapRouteReaderAdapter.loadRouteRegionData(BinaryMapRouteReaderAdapter.java:767)
	at net.osmand.binary.BinaryMapIndexReader.loadRouteIndexData(BinaryMapIndexReader.java:2401)
	at net.osmand.router.RoutingContext.loadSubregionTile(RoutingContext.java:318)
	... 8 more
Caused by: android.system.ErrnoException: lseek failed: EBADF (Bad file number)
	at libcore.io.Posix.lseek(Native Method)
	at libcore.io.BlockGuardOs.lseek(BlockGuardOs.java:163)
	at java.io.RandomAccessFile.seek(RandomAccessFile.java:600)
	... 12 more
Version  OsmAnd+ 2.2.2
26.11.2015 5:05:42
Apk Version : 2.2.2 222
Exception occured in thread Thread[Calculating position,5,main] : 
java.lang.RuntimeException: Loading data exception
	at net.osmand.router.RoutingContext.loadSubregionTile(RoutingContext.java:330)
	at net.osmand.router.RoutingContext.getRoutingTile(RoutingContext.java:505)
	at net.osmand.router.RoutingContext.loadTileData(RoutingContext.java:449)
	at net.osmand.router.RoutePlannerFrontEnd.findRouteSegment(RoutePlannerFrontEnd.java:61)
	at net.osmand.plus.CurrentPositionHelper.runUpdateInThread(CurrentPositionHelper.java:54)
	at net.osmand.plus.CurrentPositionHelper.runUpdateInThreadCatch(CurrentPositionHelper.java:100)
	at net.osmand.plus.CurrentPositionHelper$2.run(CurrentPositionHelper.java:80)
	at net.osmand.plus.routing.RoutingHelper$4.run(RoutingHelper.java:901)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.IOException: lseek failed: EBADF (Bad file number)
	at java.io.RandomAccessFile.seek(RandomAccessFile.java:602)
	at com.google.protobuf.CodedInputStream.seek(CodedInputStream.java:919)
	at net.osmand.binary.BinaryMapRouteReaderAdapter.loadRouteRegionData(BinaryMapRouteReaderAdapter.java:767)
	at net.osmand.binary.BinaryMapIndexReader.loadRouteIndexData(BinaryMapIndexReader.java:2401)
	at net.osmand.router.RoutingContext.loadSubregionTile(RoutingContext.java:318)
	... 8 more
Caused by: android.system.ErrnoException: lseek failed: EBADF (Bad file number)
	at libcore.io.Posix.lseek(Native Method)
	at libcore.io.BlockGuardOs.lseek(BlockGuardOs.java:163)
	at java.io.RandomAccessFile.seek(RandomAccessFile.java:600)
	... 12 more
Version  OsmAnd+ 2.2.2
26.11.2015 5:05:42
Apk Version : 2.2.2 222
Exception occured in thread Thread[Calculating position,5,main] : 
java.lang.RuntimeException: Loading data exception
	at net.osmand.router.RoutingContext.loadSubregionTile(RoutingContext.java:330)
	at net.osmand.router.RoutingContext.getRoutingTile(RoutingContext.java:505)
	at net.osmand.router.RoutingContext.loadTileData(RoutingContext.java:449)
	at net.osmand.router.RoutePlannerFrontEnd.findRouteSegment(RoutePlannerFrontEnd.java:61)
	at net.osmand.plus.CurrentPositionHelper.runUpdateInThread(CurrentPositionHelper.java:54)
	at net.osmand.plus.CurrentPositionHelper.runUpdateInThreadCatch(CurrentPositionHelper.java:100)
	at net.osmand.plus.CurrentPositionHelper$2.run(CurrentPositionHelper.java:80)
	at net.osmand.plus.routing.RoutingHelper$4.run(RoutingHelper.java:901)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.IOException: lseek failed: EBADF (Bad file number)
	at java.io.RandomAccessFile.seek(RandomAccessFile.java:602)
	at com.google.protobuf.CodedInputStream.seek(CodedInputStream.java:919)
	at net.osmand.binary.BinaryMapRouteReaderAdapter.loadRouteRegionData(BinaryMapRouteReaderAdapter.java:767)
	at net.osmand.binary.BinaryMapIndexReader.loadRouteIndexData(BinaryMapIndexReader.java:2401)
	at net.osmand.router.RoutingContext.loadSubregionTile(RoutingContext.java:318)
	... 8 more
Caused by: android.system.ErrnoException: lseek failed: EBADF (Bad file number)
	at libcore.io.Posix.lseek(Native Method)
	at libcore.io.BlockGuardOs.lseek(BlockGuardOs.java:163)
	at java.io.RandomAccessFile.seek(RandomAccessFile.java:600)
	... 12 more
Version  OsmAnd+ 2.2.2
26.11.2015 5:05:42
Apk Version : 2.2.2 222
Exception occured in thread Thread[Calculating position,5,main] : 
java.lang.RuntimeException: Loading data exception
	at net.osmand.router.RoutingContext.loadSubregionTile(RoutingContext.java:330)
	at net.osmand.router.RoutingContext.getRoutingTile(RoutingContext.java:505)
	at net.osmand.router.RoutingContext.loadTileData(RoutingContext.java:449)
	at net.osmand.router.RoutePlannerFrontEnd.findRouteSegment(RoutePlannerFrontEnd.java:61)
	at net.osmand.plus.CurrentPositionHelper.runUpdateInThread(CurrentPositionHelper.java:54)
	at net.osmand.plus.CurrentPositionHelper.runUpdateInThreadCatch(CurrentPositionHelper.java:100)
	at net.osmand.plus.CurrentPositionHelper$2.run(CurrentPositionHelper.java:80)
	at net.osmand.plus.routing.RoutingHelper$4.run(RoutingHelper.java:901)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.IOException: lseek failed: EBADF (Bad file number)
	at java.io.RandomAccessFile.seek(RandomAccessFile.java:602)
	at com.google.protobuf.CodedInputStream.seek(CodedInputStream.java:919)
	at net.osmand.binary.BinaryMapRouteReaderAdapter.loadRouteRegionData(BinaryMapRouteReaderAdapter.java:767)
	at net.osmand.binary.BinaryMapIndexReader.loadRouteIndexData(BinaryMapIndexReader.java:2401)
	at net.osmand.router.RoutingContext.loadSubregionTile(RoutingContext.java:318)
	... 8 more
Caused by: android.system.ErrnoException: lseek failed: EBADF (Bad file number)
	at libcore.io.Posix.lseek(Native Method)
	at libcore.io.BlockGuardOs.lseek(BlockGuardOs.java:163)
	at java.io.RandomAccessFile.seek(RandomAccessFile.java:600)
	... 12 more
Version  OsmAnd+ 2.2.2
26.11.2015 5:05:42
Apk Version : 2.2.2 222
Exception occured in thread Thread[Calculating position,5,main] : 
java.lang.RuntimeException: Loading data exception
	at net.osmand.router.RoutingContext.loadSubregionTile(RoutingContext.java:330)
	at net.osmand.router.RoutingContext.getRoutingTile(RoutingContext.java:505)
	at net.osmand.router.RoutingContext.loadTileData(RoutingContext.java:449)
	at net.osmand.router.RoutePlannerFrontEnd.findRouteSegment(RoutePlannerFrontEnd.java:61)
	at net.osmand.plus.CurrentPositionHelper.runUpdateInThread(CurrentPositionHelper.java:54)
	at net.osmand.plus.CurrentPositionHelper.runUpdateInThreadCatch(CurrentPositionHelper.java:100)
	at net.osmand.plus.CurrentPositionHelper$2.run(CurrentPositionHelper.java:80)
	at net.osmand.plus.routing.RoutingHelper$4.run(RoutingHelper.java:901)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.IOException: lseek failed: EBADF (Bad file number)
	at java.io.RandomAccessFile.seek(RandomAccessFile.java:602)
	at com.google.protobuf.CodedInputStream.seek(CodedInputStream.java:919)
	at net.osmand.binary.BinaryMapRouteReaderAdapter.loadRouteRegionData(BinaryMapRouteReaderAdapter.java:767)
	at net.osmand.binary.BinaryMapIndexReader.loadRouteIndexData(BinaryMapIndexReader.java:2401)
	at net.osmand.router.RoutingContext.loadSubregionTile(RoutingContext.java:318)
	... 8 more
Caused by: android.system.ErrnoException: lseek failed: EBADF (Bad file number)
	at libcore.io.Posix.lseek(Native Method)
	at libcore.io.BlockGuardOs.lseek(BlockGuardOs.java:163)
	at java.io.RandomAccessFile.seek(RandomAccessFile.java:600)
	... 12 more

**Comment by Goodingn** [comment]
Version  OsmAnd+ 2.2.4
05.01.2016 4:18:34
Apk Version : 2.2.4 224
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{38be90c3 V.E..... R......D 0,0-513,242} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:396)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:322)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
	at android.app.Dialog.dismissDialog(Dialog.java:341)
	at android.app.Dialog.dismiss(Dialog.java:324)
	at net.osmand.plus.activities.search.GeoIntentActivity$GeoIntentTask.onPostExecute(GeoIntentActivity.java:127)
	at net.osmand.plus.activities.search.GeoIntentActivity$GeoIntentTask.onPostExecute(GeoIntentActivity.java:100)
	at android.os.AsyncTask.finish(AsyncTask.java:636)
	at android.os.AsyncTask.access$500(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5343)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
Version  OsmAnd+ 2.2.4
05.01.2016 4:18:34
Apk Version : 2.2.4 224
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{38be90c3 V.E..... R......D 0,0-513,242} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:396)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:322)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
	at android.app.Dialog.dismissDialog(Dialog.java:341)
	at android.app.Dialog.dismiss(Dialog.java:324)
	at net.osmand.plus.activities.search.GeoIntentActivity$GeoIntentTask.onPostExecute(GeoIntentActivity.java:127)
	at net.osmand.plus.activities.search.GeoIntentActivity$GeoIntentTask.onPostExecute(GeoIntentActivity.java:100)
	at android.os.AsyncTask.finish(AsyncTask.java:636)
	at android.os.AsyncTask.access$500(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5343)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
Version  OsmAnd+ 2.2.4
05.01.2016 4:18:34
Apk Version : 2.2.4 224
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{38be90c3 V.E..... R......D 0,0-513,242} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:396)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:322)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
	at android.app.Dialog.dismissDialog(Dialog.java:341)
	at android.app.Dialog.dismiss(Dialog.java:324)
	at net.osmand.plus.activities.search.GeoIntentActivity$GeoIntentTask.onPostExecute(GeoIntentActivity.java:127)
	at net.osmand.plus.activities.search.GeoIntentActivity$GeoIntentTask.onPostExecute(GeoIntentActivity.java:100)
	at android.os.AsyncTask.finish(AsyncTask.java:636)
	at android.os.AsyncTask.access$500(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5343)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
Version  OsmAnd+ 2.2.4
05.01.2016 4:18:34
Apk Version : 2.2.4 224
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{38be90c3 V.E..... R......D 0,0-513,242} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:396)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:322)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
	at android.app.Dialog.dismissDialog(Dialog.java:341)
	at android.app.Dialog.dismiss(Dialog.java:324)
	at net.osmand.plus.activities.search.GeoIntentActivity$GeoIntentTask.onPostExecute(GeoIntentActivity.java:127)
	at net.osmand.plus.activities.search.GeoIntentActivity$GeoIntentTask.onPostExecute(GeoIntentActivity.java:100)
	at android.os.AsyncTask.finish(AsyncTask.java:636)
	at android.os.AsyncTask.access$500(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5343)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
Version  OsmAnd+ 2.2.4
05.01.2016 4:46:32
Apk Version : 2.2.4 224
Exception occured in thread Thread[Calculating position,5,main] : 
java.lang.RuntimeException: Loading data exception
	at net.osmand.router.RoutingContext.loadSubregionTile(RoutingContext.java:330)
	at net.osmand.router.RoutingContext.getRoutingTile(RoutingContext.java:505)
	at net.osmand.router.RoutingContext.loadTileData(RoutingContext.java:449)
	at net.osmand.router.RoutePlannerFrontEnd.findRouteSegment(RoutePlannerFrontEnd.java:61)
	at net.osmand.plus.CurrentPositionHelper.runUpdateInThread(CurrentPositionHelper.java:54)
	at net.osmand.plus.CurrentPositionHelper.runUpdateInThreadCatch(CurrentPositionHelper.java:100)
	at net.osmand.plus.CurrentPositionHelper$2.run(CurrentPositionHelper.java:80)
	at net.osmand.plus.routing.RoutingHelper$4.run(RoutingHelper.java:901)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.IOException: lseek failed: EBADF (Bad file number)
	at java.io.RandomAccessFile.seek(RandomAccessFile.java:602)
	at com.google.protobuf.CodedInputStream.seek(CodedInputStream.java:919)
	at net.osmand.binary.BinaryMapRouteReaderAdapter.loadRouteRegionData(BinaryMapRouteReaderAdapter.java:767)
	at net.osmand.binary.BinaryMapIndexReader.loadRouteIndexData(BinaryMapIndexReader.java:2401)
	at net.osmand.router.RoutingContext.loadSubregionTile(RoutingContext.java:318)
	... 8 more
Caused by: android.system.ErrnoException: lseek failed: EBADF (Bad file number)
	at libcore.io.Posix.lseek(Native Method)
	at libcore.io.BlockGuardOs.lseek(BlockGuardOs.java:163)
	at java.io.RandomAccessFile.seek(RandomAccessFile.java:600)
	... 12 more
Version  OsmAnd+ 2.2.4
05.01.2016 4:46:32
Apk Version : 2.2.4 224
Exception occured in thread Thread[Calculating position,5,main] : 
java.lang.RuntimeException: Loading data exception
	at net.osmand.router.RoutingContext.loadSubregionTile(RoutingContext.java:330)
	at net.osmand.router.RoutingContext.getRoutingTile(RoutingContext.java:505)
	at net.osmand.router.RoutingContext.loadTileData(RoutingContext.java:449)
	at net.osmand.router.RoutePlannerFrontEnd.findRouteSegment(RoutePlannerFrontEnd.java:61)
	at net.osmand.plus.CurrentPositionHelper.runUpdateInThread(CurrentPositionHelper.java:54)
	at net.osmand.plus.CurrentPositionHelper.runUpdateInThreadCatch(CurrentPositionHelper.java:100)
	at net.osmand.plus.CurrentPositionHelper$2.run(CurrentPositionHelper.java:80)
	at net.osmand.plus.routing.RoutingHelper$4.run(RoutingHelper.java:901)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.IOException: lseek failed: EBADF (Bad file number)
	at java.io.RandomAccessFile.seek(RandomAccessFile.java:602)
	at com.google.protobuf.CodedInputStream.seek(CodedInputStream.java:919)
	at net.osmand.binary.BinaryMapRouteReaderAdapter.loadRouteRegionData(BinaryMapRouteReaderAdapter.java:767)
	at net.osmand.binary.BinaryMapIndexReader.loadRouteIndexData(BinaryMapIndexReader.java:2401)
	at net.osmand.router.RoutingContext.loadSubregionTile(RoutingContext.java:318)
	... 8 more
Caused by: android.system.ErrnoException: lseek failed: EBADF (Bad file number)
	at libcore.io.Posix.lseek(Native Method)
	at libcore.io.BlockGuardOs.lseek(BlockGuardOs.java:163)
	at java.io.RandomAccessFile.seek(RandomAccessFile.java:600)
	... 12 more
Version  OsmAnd+ 2.2.4
05.01.2016 4:46:32
Apk Version : 2.2.4 224
Exception occured in thread Thread[Calculating position,5,main] : 
java.lang.RuntimeException: Loading data exception
	at net.osmand.router.RoutingContext.loadSubregionTile(RoutingContext.java:330)
	at net.osmand.router.RoutingContext.getRoutingTile(RoutingContext.java:505)
	at net.osmand.router.RoutingContext.loadTileData(RoutingContext.java:449)
	at net.osmand.router.RoutePlannerFrontEnd.findRouteSegment(RoutePlannerFrontEnd.java:61)
	at net.osmand.plus.CurrentPositionHelper.runUpdateInThread(CurrentPositionHelper.java:54)
	at net.osmand.plus.CurrentPositionHelper.runUpdateInThreadCatch(CurrentPositionHelper.java:100)
	at net.osmand.plus.CurrentPositionHelper$2.run(CurrentPositionHelper.java:80)
	at net.osmand.plus.routing.RoutingHelper$4.run(RoutingHelper.java:901)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.IOException: lseek failed: EBADF (Bad file number)
	at java.io.RandomAccessFile.seek(RandomAccessFile.java:602)
	at com.google.protobuf.CodedInputStream.seek(CodedInputStream.java:919)
	at net.osmand.binary.BinaryMapRouteReaderAdapter.loadRouteRegionData(BinaryMapRouteReaderAdapter.java:767)
	at net.osmand.binary.BinaryMapIndexReader.loadRouteIndexData(BinaryMapIndexReader.java:2401)
	at net.osmand.router.RoutingContext.loadSubregionTile(RoutingContext.java:318)
	... 8 more
Caused by: android.system.ErrnoException: lseek failed: EBADF (Bad file number)
	at libcore.io.Posix.lseek(Native Method)
	at libcore.io.BlockGuardOs.lseek(BlockGuardOs.java:163)
	at java.io.RandomAccessFile.seek(RandomAccessFile.java:600)
	... 12 more
Version  OsmAnd+ 2.2.4
05.01.2016 4:46:32
Apk Version : 2.2.4 224
Exception occured in thread Thread[Calculating position,5,main] : 
java.lang.RuntimeException: Loading data exception
	at net.osmand.router.RoutingContext.loadSubregionTile(RoutingContext.java:330)
	at net.osmand.router.RoutingContext.getRoutingTile(RoutingContext.java:505)
	at net.osmand.router.RoutingContext.loadTileData(RoutingContext.java:449)
	at net.osmand.router.RoutePlannerFrontEnd.findRouteSegment(RoutePlannerFrontEnd.java:61)
	at net.osmand.plus.CurrentPositionHelper.runUpdateInThread(CurrentPositionHelper.java:54)
	at net.osmand.plus.CurrentPositionHelper.runUpdateInThreadCatch(CurrentPositionHelper.java:100)
	at net.osmand.plus.CurrentPositionHelper$2.run(CurrentPositionHelper.java:80)
	at net.osmand.plus.routing.RoutingHelper$4.run(RoutingHelper.java:901)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.IOException: lseek failed: EBADF (Bad file number)
	at java.io.RandomAccessFile.seek(RandomAccessFile.java:602)
	at com.google.protobuf.CodedInputStream.seek(CodedInputStream.java:919)
	at net.osmand.binary.BinaryMapRouteReaderAdapter.loadRouteRegionData(BinaryMapRouteReaderAdapter.java:767)
	at net.osmand.binary.BinaryMapIndexReader.loadRouteIndexData(BinaryMapIndexReader.java:2401)
	at net.osmand.router.RoutingContext.loadSubregionTile(RoutingContext.java:318)
	... 8 more
Caused by: android.system.ErrnoException: lseek failed: EBADF (Bad file number)
	at libcore.io.Posix.lseek(Native Method)
	at libcore.io.BlockGuardOs.lseek(BlockGuardOs.java:163)
	at java.io.RandomAccessFile.seek(RandomAccessFile.java:600)
	... 12 more
Version  OsmAnd+ 2.2.4
05.01.2016 4:46:32
Apk Version : 2.2.4 224
Exception occured in thread Thread[Calculating position,5,main] : 
java.lang.RuntimeException: Loading data exception
	at net.osmand.router.RoutingContext.loadSubregionTile(RoutingContext.java:330)
	at net.osmand.router.RoutingContext.getRoutingTile(RoutingContext.java:505)
	at net.osmand.router.RoutingContext.loadTileData(RoutingContext.java:449)
	at net.osmand.router.RoutePlannerFrontEnd.findRouteSegment(RoutePlannerFrontEnd.java:61)
	at net.osmand.plus.CurrentPositionHelper.runUpdateInThread(CurrentPositionHelper.java:54)
	at net.osmand.plus.CurrentPositionHelper.runUpdateInThreadCatch(CurrentPositionHelper.java:100)
	at net.osmand.plus.CurrentPositionHelper$2.run(CurrentPositionHelper.java:80)
	at net.osmand.plus.routing.RoutingHelper$4.run(RoutingHelper.java:901)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.IOException: lseek failed: EBADF (Bad file number)
	at java.io.RandomAccessFile.seek(RandomAccessFile.java:602)
	at com.google.protobuf.CodedInputStream.seek(CodedInputStream.java:919)
	at net.osmand.binary.BinaryMapRouteReaderAdapter.loadRouteRegionData(BinaryMapRouteReaderAdapter.java:767)
	at net.osmand.binary.BinaryMapIndexReader.loadRouteIndexData(BinaryMapIndexReader.java:2401)
	at net.osmand.router.RoutingContext.loadSubregionTile(RoutingContext.java:318)
	... 8 more
Caused by: android.system.ErrnoException: lseek failed: EBADF (Bad file number)
	at libcore.io.Posix.lseek(Native Method)
	at libcore.io.BlockGuardOs.lseek(BlockGuardOs.java:163)
	at java.io.RandomAccessFile.seek(RandomAccessFile.java:600)
	... 12 more
Version  OsmAnd+ 2.2.4
05.01.2016 4:46:32
Apk Version : 2.2.4 224
Exception occured in thread Thread[Calculating position,5,main] : 
java.lang.RuntimeException: Loading data exception
	at net.osmand.router.RoutingContext.loadSubregionTile(RoutingContext.java:330)
	at net.osmand.router.RoutingContext.getRoutingTile(RoutingContext.java:505)
	at net.osmand.router.RoutingContext.loadTileData(RoutingContext.java:449)
	at net.osmand.router.RoutePlannerFrontEnd.findRouteSegment(RoutePlannerFrontEnd.java:61)
	at net.osmand.plus.CurrentPositionHelper.runUpdateInThread(CurrentPositionHelper.java:54)
	at net.osmand.plus.CurrentPositionHelper.runUpdateInThreadCatch(CurrentPositionHelper.java:100)
	at net.osmand.plus.CurrentPositionHelper$2.run(CurrentPositionHelper.java:80)
	at net.osmand.plus.routing.RoutingHelper$4.run(RoutingHelper.java:901)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.IOException: lseek failed: EBADF (Bad file number)
	at java.io.RandomAccessFile.seek(RandomAccessFile.java:602)
	at com.google.protobuf.CodedInputStream.seek(CodedInputStream.java:919)
	at net.osmand.binary.BinaryMapRouteReaderAdapter.loadRouteRegionData(BinaryMapRouteReaderAdapter.java:767)
	at net.osmand.binary.BinaryMapIndexReader.loadRouteIndexData(BinaryMapIndexReader.java:2401)
	at net.osmand.router.RoutingContext.loadSubregionTile(RoutingContext.java:318)
	... 8 more
Caused by: android.system.ErrnoException: lseek failed: EBADF (Bad file number)
	at libcore.io.Posix.lseek(Native Method)
	at libcore.io.BlockGuardOs.lseek(BlockGuardOs.java:163)
	at java.io.RandomAccessFile.seek(RandomAccessFile.java:600)
	... 12 more

**Comment by vshcherb** [comment]
Thanks for report, I'm afraid we can't do much unless it will be reproducible on our development devices. According to the stacktrace it could be related to out of memory or some other system related issues, so the exact problem is not identified.

**Comment by Goodingn** [comment]
I see.  If you need to know with what version this started happening with, this started happening when the newest GUI was launched- when sharing a position with OSMAnd, there's a new location information slider at the bottom of the screen with Navigate To button and a few others at the bottom- fav, waypoint, share, etc.  Before this addition, I didn't have this issue.

**Comment by vshcherb** [comment]
But you don't press anything or you don't call context menu when you are finishing navigation that's why it is strange. It could be possible to explain if you use context menu while you are driving, but then it is hard to connect to reaching the destination

**Comment by Goodingn** [comment]
I think I was just trying to pin down a version where this started to see if there was anything introduced in those versions that needs checking out.

As an aside, though I'm not doing anything regarding menus, Osmand does a theme change- back from car to map browse.

On 18 January 2016 20:39:03 GMT+00:00, vshcherb <notifications@github.com> wrote:
>But you don't press anything or you don't call context menu when you
>are finishing navigation that's why it is strange. It could be possible
>to explain if you use context menu while you are driving, but then it
>is hard to connect to reaching the destination
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/osmandapp/Osmand/issues/2120#issuecomment-172647674

-- 
Neil Gooding

**Comment by Goodingn** [comment]
You may be pleased to know OSMAnd has been frustratingly well behaved over the past week or so of use.

**Comment by vshcherb** [comment]
Hm... May be not, because the issue is still there :) It is much better to have it obvious and fix it quickly otherwise it is just a moment it will pop up

**Comment by sonora** [comment]
Deprecated, I guess.
