### ISSUE TITLE
Zooming while creating a track on the map crash

### ISSUE THREAD

**Issue by 4sStylZ** [osmandapp/OsmAnd#21294]
### Description

While using Vivaldi or Firefox (not tested on others browser), zooming on the web map cause a crash.

https://github.com/user-attachments/assets/911584d1-2f85-4fdd-a676-7490e0ce2a60

### Steps to reproduce

1. Use https://osmand.net/map/plan#9/45.9302/4.7158 on Vivaldi or Firefox
2. Create a track
3. Zoom

### Actual result

It crash and display this in the console 

```javascript
react-dom.production.min.js:188 TypeError: Cannot read properties of undefined (reading 'options')
    at LocalClientTrackLayer.js:179:60
    at il (react-dom.production.min.js:243:332)
    at wc (react-dom.production.min.js:285:111)
    at lc (react-dom.production.min.js:272:185)
    at Vr (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:266:273
ds @ react-dom.production.min.js:188
n.callback @ react-dom.production.min.js:188
Go @ react-dom.production.min.js:156
bl @ react-dom.production.min.js:261
yl @ react-dom.production.min.js:259
vl @ react-dom.production.min.js:258
(anonyme) @ react-dom.production.min.js:282
xc @ react-dom.production.min.js:280
lc @ react-dom.production.min.js:272
Vr @ react-dom.production.min.js:127
(anonyme) @ react-dom.production.min.js:266
hashchange
onMapMove @ leaflet-hash.js:90
fire @ Events.js:195
_moveEnd @ Map.js:1254
_onZoomTransitionEnd @ Map.js:1735
_catchTransitionEnd @ Map.js:1651
o @ DomEvent.js:108
Afficher 17 autres frames
Afficher moins
LocalClientTrackLayer.js:179 Uncaught TypeError: Cannot read properties of undefined (reading 'options')
    at LocalClientTrackLayer.js:179:60
    at il (react-dom.production.min.js:243:332)
    at wc (react-dom.production.min.js:285:111)
    at lc (react-dom.production.min.js:272:185)
    at Vr (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:266:273
(anonyme) @ LocalClientTrackLayer.js:179
il @ react-dom.production.min.js:243
wc @ react-dom.production.min.js:285
lc @ react-dom.production.min.js:272
Vr @ react-dom.production.min.js:127
(anonyme) @ react-dom.production.min.js:266
hashchange
onMapMove @ leaflet-hash.js:90
fire @ Events.js:195
_moveEnd @ Map.js:1254
_onZoomTransitionEnd @ Map.js:1735
_catchTransitionEnd @ Map.js:1651
o @ DomEvent.js:108
Afficher 11 autres frames
Afficher moins
DomUtil.js:247 Uncaught TypeError: Cannot read properties of undefined (reading '_leaflet_pos')
    at At (DomUtil.js:247:12)
    at t._getMapPanePos (Map.js:1488:10)
    at t.containerPointToLayerPoint (Map.js:1039:39)
    at t.containerPointToLatLng (Map.js:1053:25)
    at t.setZoomAround (Map.js:247:24)
    at t._performZoom (Map.ScrollWheelZoom.js:83:8)
```

### Expected result

It does not crash

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: I am using the last version of the website
Android/iOS version: no
Device model: windows 11 / vivaldi etc
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. In the [web version](https://test.osmand.net/map/#5/50.000/5.000), go to the "Plan a route" tab in the menu, select "Create track," and attempt to zoom in or out on the map.

The web version crashes as a result, displaying only a white screen in the browser.

https://github.com/user-attachments/assets/a2bf1340-047a-4ece-a38c-4052f1f99869
