### ISSUE TITLE
Crash in AA (should restore correctly after restart)

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#21433]
- [ ] Fix crash
- [ ] After Crash in AA should restore navigation correctly

```
Exception occurred in thread Thread[pool-17-thread-1,5,main] : 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1111)
	at java.util.ArrayList$Itr.next(ArrayList.java:1064)
	at net.osmand.plus.shared.SharedUtil.jTrkSegment(SharedUtil.kt:252)
	at net.osmand.plus.shared.SharedUtil.jTrack(SharedUtil.kt:212)
	at net.osmand.plus.shared.SharedUtil.jGpxFile(SharedUtil.kt:187)
	at net.osmand.plus.routing.RouteProvider.parseOsmAndGPXRoute(RouteProvider.java:968)
	at net.osmand.plus.routing.RouteProvider.parseOsmAndGPXRoute(RouteProvider.java:961)
	at net.osmand.plus.track.helpers.ParseGpxRouteTask.doInBackground(ParseGpxRouteTask.java:46)
	at net.osmand.plus.track.helpers.ParseGpxRouteTask.doInBackground(ParseGpxRouteTask.java:17)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more
```

**Comment by Zirochkabila** [comment]
`OsmAnd~ 5.0.0#3813m, Released: 2024-11-26`
Not reproduce
