### ISSUE TITLE
images not loading reliably and app crash when requesting image details

### ISSUE THREAD

**Issue by uegert** [osmandapp/OsmAnd#21579]
### Description

Hi, Osmand+ 4.9.10 (android) of 2024-12-12 crashes when tapping on the "Details" of full-screen image display.

Btw: I've send crash reports via the app (email), but these don't seem to end up anywhere. It would be better remove this function from the app if it is a dead end.

### Steps to reproduce

There might be two bugs linked to each other:
Version 1
1) find "Silberberg-Schutzhütte", OSM way 436089692. There is an online image associated. Tap on the thumbnail. The image does not open. 
2) open the menu (top right), tap on "Details" 
Osmand crashes reliably.
The link to the image is ok if called from openstreetmap.org. The same happens for images linked from other servers. I also checked after restarting the phone, clearing the osmand cache, etc.

Version 2
1) find node #225987561 (Dorerbühl-Hütte). There are several thumbnails. Tapping on them will open the image. 
2a) If you tap on the **large** thumbnail, then step 2 from above can be reproduced and Osmand crashes.
2b) If you tap on the **small** thumbnail, then step 2 does not crash Osmand.

I could not find a pattern for when images will open and when not. 

### Actual result

Image does not open reliably, Osmand crashes when opening "Details"

### Expected result

Images should open, Details should be shown.

### Your Environment (required)

Android/iOS version: 12
Device model: SM-G970U
Crash-Logs: below

Version  OsmAnd+ 4.9.10
17.12.2024 9:52:41
Apk Version : 4.9.10 4910
Exception occurred in thread Thread[main,5,main] : 
android.content.res.Resources$NotFoundException: Resource ID #0x0
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:240)
	at android.content.res.Resources.getValue(Resources.java:1511)
	at androidx.appcompat.widget.ResourceManagerInternal.createDrawableIfNeeded(ResourceManagerInternal.java:181)
	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:146)
	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:137)
	at androidx.appcompat.content.res.AppCompatResources.getDrawable(AppCompatResources.java:66)
	at net.osmand.plus.utils.UiUtilities.getDrawable(UiUtilities.java:101)
	at net.osmand.plus.utils.UiUtilities.getIcon(UiUtilities.java:169)
	at net.osmand.plus.mapcontextmenu.gallery.GalleryDetailsFragment.buildItem(GalleryDetailsFragment.java:154)
	at net.osmand.plus.mapcontextmenu.gallery.GalleryDetailsFragment.updateContent(GalleryDetailsFragment.java:127)
	at net.osmand.plus.mapcontextmenu.gallery.GalleryDetailsFragment.onCreateView(GalleryDetailsFragment.java:82)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```

**Comment by yuriiurshuliak** [comment]
The bugs you mentioned **could not be reproduced** in either the **nightly** or the latest **release version** of OsmAnd. Specifically, I followed these steps:  
1. Open the coordinates [Silberberg-Schutzhütte](https://www.openstreetmap.org/way/436089692) and [Dorerbühl-Hütte](https://www.openstreetmap.org/way/225987561).   
2. Tap on the POI > "Details" > "Online photo" > Click on the photo.

**Result**:  
The photo screen opened successfully, and the app did not crash.  

However, I did observe that the photos take a long time to load before being displayed, which might be causing unexpected behavior on certain devices or network conditions.

Please share additional details, such as video of the issue, to help us investigate further.

OsmAnd~ 5.0.0#3944m, released: 2024-12-17
OsmAnd 4.9.10, released: 2024-12-12

<table style="width:100%">
  </tr>
  <tr>
    <td> <video source src="https://github.com/user-attachments/assets/c96b49a4-69ba-445d-8b95-e990b0800265"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/user-attachments/assets/4f1f201f-d0bd-4005-b50b-fabbce47ed6e"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by uegert** [comment]
Hi, after checking your videos: The crash does not happen when only tapping on the thumbnail, but when checking "Details" in the full screen menu. For my videos I used an external camera to show the different effects for tapping the big and the small thumbnail. 
Images of Dorerbühl-Hütte do open quickly after tapping either the small or the large thumbnails. The crash only occurs when tapping "Details" for the large thumbnail. Details of the small thumbnails are no problem. The photo linked to the image= tag is also part of the set of images in the category linked to the wikimedia_commons= tag and shown as a large as well as a small thumbnail. The crash happens only with the large thumbnail but I'm not sure this is the image= tag.
Silberberg-Schutzhütte does not open for me, even after waiting a long time. 

[Dorerbühl-Hütte large thumbnail](https://www.dropbox.com/scl/fi/jpolaexg32jg0dz9v49ez/WIN_20241217_17_29_14_Pro.mp4?rlkey=qbw8ohvw77zm3f1qq7kwgjph3&dl=0) - crash
[Dorerbühl-Hütte small thumbnail](https://www.dropbox.com/scl/fi/3znefitaskh8e031io8qi/WIN_20241217_17_29_52_Pro.mp4?rlkey=tmgl1nk662t4kigggrgjbyb7p&dl=0) - no crash
[Silberberg-Schutzhütte, large thumbnail, not loading ](https://www.dropbox.com/scl/fi/eb4y8z6o7000al50xzpdy/WIN_20241217_17_28_22_Pro.mp4?rlkey=ympugzcljvla4jct32etexwrz&dl=0) - crash

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To do so:

1. Open *Silberberg-Schutzhütte* and *Dorerbühl-Hütte*.
2. Tap on the POI, then "Details" > "Online photo" > click on the photo.
3. Tap the three dots in the top right, then select "Details."

This results in a crash at both locations.

However, if you select a smaller photo instead of the large one, the crash does not occur when tapping "Details."

Here are the crash logs:
[exception (29).zip](https://github.com/user-attachments/files/18229178/exception.29.zip)

OsmAnd~ 5.0.0#3985m, released: 2024-12-23

<table style="width:100%">
  </tr>
  <tr>
    <td> <video source src="https://github.com/user-attachments/assets/d36ce4af-d8f9-4b17-9f8c-00e8e33cfc45"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/user-attachments/assets/cc6bae46-46a8-4185-a162-8ae02327fc92"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
# Testing 1

`OsmAnd~ 5.0.0#4062m, Released: 2025-01-06` - Fixed

**Comment by dmpr0** [comment]
# Review 

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/8ac94417-7258-4fd5-bfa2-16d4e89adce9"  width="300" height="auto"/> </td>
  </tr>
</table>   


- [ ] No image for **Silberberg-Schutzhütte**

**Comment by Zirochkabila** [comment]
`OsmAnd~ 5.0.0#4093m, Released: 2025-01-09` - Image still present 
`4.9.3.4936`
But:
1. Can't open - dark screen only, looks like image has a long time for downloading (details work)
2. Can't open large photos in browser (both large photos from both locations) - work in iOS






<details><summary>Video</summary>
<table style="width:100%">
  <tr>
    <th>Dark screen</th>
    <th>Large photos</th>
    <th>iOS example</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/user-attachments/assets/7d0bc82f-3c6f-4f40-b9a2-41cc220173e4"  width="300" height="auto"/></td>
    <td><video source src="https://github.com/user-attachments/assets/891178c1-5d6b-4c72-8ec5-a3cef8af919d"  width="300" height="auto"/> </th>
    <td><video source src="https://github.com/user-attachments/assets/8f897572-235b-4831-b28c-1d40294c3731"  width="300" height="auto"/> </th>
  </tr>
</table> 
</details>

**Comment by dmpr0** [comment]
# Review 

<table style="width:100%">
  <tr>
    <th>Video</th>
    <th>Mapillary - ON</th>
    <th>Mapillary - OFF</th>
  </tr>
  <tr>
    <td><video src="https://github.com/user-attachments/assets/3381cfba-5373-4186-8278-d07e6310bb12"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/060ed096-5441-4b20-b799-df75c5b96add"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/76e6dd23-ff2a-4bef-9694-e1d83e36c376"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] Doesn't work for me if Mapillary plugin is Off

**Comment by Zirochkabila** [comment]
# Testing 3
`OsmAnd~ 5.0.0#4136m, Released: 2025-01-15`

Can confirm @dmpr0 behavior - if Mapillary plugin is Off [Silberberg-Schutzhütte photo](https://www.openstreetmap.org/way/436089692#map=19/47.778431/7.831053) doesn't show


<details><summary>Silberberg-Schutzhütte photo</summary>
<video src="https://github.com/user-attachments/assets/29288ffe-cc2d-4e99-8faa-3aa77be20614"></video>
</details>

**Comment by uegert** [comment]
I can also reproduce the Mapillary dependency with Silberberg-Schutzhütte - but strangely not for node #225987561 (Dorerbühl-Hütte). All its images show up as thumbnails whether the plugin is active or not. I used offline vectormaps in both cases. Osmand Apk Version : 4.9.10

**Comment by uegert** [comment]
@nazar-kutz : It would be useful to retrieve entries in "Usage on www.wikidata.org" to catch objects where images are already associated with the node but wikidata or wikipedia entries are created later by people not editing OSM.

**Comment by Zirochkabila** [comment]
# Testing 4
`OsmAnd~ 5.0.0#4175m, Released: 2025-01-20`

Open photo at location `47.778431/7.831154`

<details><summary>Photo don't opened</summary>
<video src="https://github.com/user-attachments/assets/3cef5131-9d17-4367-b173-d5d6c6cbac71"></video>
</details>

**Comment by uegert** [comment]
Hi again, it seems there might be another pattern in this image problem.

1) if the image= tag points to an image on commons.wikimedia then the thumbnails for wikimedia_commons=Category:*  will show up

[Stora Holmevatten vindskydd](https://www.openstreetmap.org/node/2501405264)
**image = a wikimedia_commons image**
wikimedia_commons=Category:* thumbnails **are** showing
Large thumbnail shows image=  but **does not** load when tapped

[Dorerbühl-Hütte](https://www.openstreetmap.org/way/225987561)
This is the one uploaded for the longest time among the examples.
**image = a wikimedia_commons image**
wikimedia_commons=Category:* thumbnails **are** showing
Large thumbnail shows image=  but **does** open when tapped - this is the only one example where the large thumbnail opens the full image.

---
2) if the image= tag points to an image elsewhere then the thumbnails for wikimedia_commons=Category:*  will **not** show up

[Rödhällmalen vindskydd](https://www.openstreetmap.org/node/7125241124)
**image = NOT a wikimedia_commons image**
wikimedia_commons=Category:* thumbnails **not** showing
Large thumbnail shows image= and **does not** load when tapped
 
[Silberberg-Schutzhütte](https://www.openstreetmap.org/way/436089692)
**image = NOT a wikimedia_commons image**
wikimedia_commons=Category:* thumbnails **not** showing
Large thumbnail shows image= but **does not** load when tapped

---
OsmAnd Nightly 5.0.0#4178m

**Comment by uegert** [comment]
Same here. Large thumbnails generally do not open and wikimedia_commons:Categories very often do not even load as thumbnails.
Dorerbühl-Hütte is somehow an exception: here tapping the big thumbnail will open the image.

Osmand Nightly 5.0.0#4178m

**Comment by nazar-kutz** [comment]
@uegert : yes, we plan to create a separate issue for WEB/Backend team and address the data issue on the server side. It has been identified that the problem lies in legacy server-side code that processes data requests for these specified points, and this code requires review and fixing.

**Comment by uegert** [comment]
As of 2026-02-06 (offline maps updated) and version Osmand+ 5.2.13 (on android 12, cache just cleared) the issue is still not fixed completely. Here are several examples that work correctly or not. I cannot find a consistent pattern. Except for the last example none has an image=* entry. Mapillary on/off makes not difference. Rendering of images is still not correct. 

**Fjärdbotten 7 w1349704366**
_OSMand_ : 
Wrong images shown (from several other wikimedia_commons categories), without date/author/license information (all present on commons)

_OSM_
wikidata=Q121541351 (with correct pictures)
wikimedia_commons=Category:Fjärdbotten hut 7

**Fjärdbotten 6 w1198939711**
_OSMand_ : 
No images showing

_OSM_
No wikidata entry 
wikimedia_commons=Category:Fjärdbotten hut 6

**Fjärdbotten 5 w1198939289**
_OSMand_ : 
Shows 4 of 4  images of Category:Fjärdbotten hut 5 correctly as ‘online photos’ but without date/author/license information (all present on commons)

_OSM_
No wikidata entry 
wikimedia_commons=Category:Fjärdbotten hut 5

**Fjärdbotten 4 w1198939290**
_OSMand_:
Shows 3 of 3 images of Category:Fjärdbotten hut 4 correctly as ‘online photos’ but without date/author/license information (all present on commons)

_OSM_
No wikidata entry 
wikimedia_commons=Category:Fjärdbotten hut 4

**Fjärdbotten 3 w1198939291**
_OSMand_:
Shows 3 of 3 images of Category:Fjärdbotten hut 3 correctly as ‘online photos’ with date/author/license information 

_OSM_
wikidata=Q121540723
wikimedia_commons=Category:Fjärdbotten hut 3

**Fjärdbotten 2 w1198939292**
_OSMand_:
Shows 4 of 4 images of Category:Fjärdbotten hut 2 correctly as ‘online photos’ without date/author/license information 

_OSM_
No wikidata entry 
wikimedia_commons=Category:Fjärdbotten hut 2


**Fjärdbotten 1 w1462578860**
_OSMand_:
Shows 4 of 4 images of Category:Fjärdbotten hut 1 correctly as ‘online photos’ without date/author/license information 

_OSM_
No wikidata entry 
wikimedia_commons=Category:Fjärdbotten hut 1


**Ibichhütte w225049593**
_OSMand_
1 of 4 images showing, corresponding to the one in image=*, which is stored on commons.wikimedia

_OSM_
No wikidata entry 
image=https://commons.wikimedia.org/wiki/File:Ibichh%C3%BCtte_20260207_04.jpg
wikimedia_commons=Category:Ibichhütte, Simonswald

**Comment by Zirochkabila** [comment]
> OsmAnd~ 5.3.0#7197m, Released: 2026-02-18
> Web - prod
> OsmAnd Maps 5337, released 17.02.26

Different pictures

[OsmAnd](https://osmand.net/map/poi/?type=Tourism&pin=62.815426,18.155144#20/62.81545/18.15505) [Wikidata](https://www.wikidata.org/wiki/Q121541351)

<details><summary>Details - 1349704366</summary>
<video src="https://github.com/user-attachments/assets/87019ecc-5a9f-4eb9-bb68-e4c632b422e9"></video>
</details> 


[OsmAnd](https://osmand.net/map/poi/?type=Tourism&osmId=1198939291&pin=62.81612,18.15539#20/62.81603/18.15524) [Wikidata](https://www.wikidata.org/wiki/Q121540723)


<details><summary>Details - 1198939291</summary>
<video src="https://github.com/user-attachments/assets/b509b620-71ea-467c-ac6f-4d60270baf04"></video>
</details> 


_________



Missed data on the photo

[OsmAnd](https://osmand.net/map/poi/?type=Tourism&osmId=1198939289&pin=62.815853,18.155176#18/62.81591/18.15551) [Сommons_wikimedia](https://commons.wikimedia.org/wiki/Category:Fj%C3%A4rdbotten_hut_5#/media/File:Fj%C3%A4rdbotten_hut_5,_20250820_01.jpg)

<details><summary>Details - 1198939289</summary>
<video src="https://github.com/user-attachments/assets/2b35481e-cd29-48ac-b463-97e3b61981dd"></video>
</details>

**Comment by vshcherb** [comment]
@uegert the issue is that wikidata id doesn't have a link to category and probably these photos are not processed. However you are right osm has links to category which could help us to process this data.

**Comment by uegert** [comment]
@vshcherb & @Zirochkabila: I've added the category links to existing wikidata entries, but I'm not convinced this is the problem:

- Correct Category images are shown (though w/o author etc.) for Fjärdbotten 1 (w1462578860), which has no wikidata entry. 
- Category images are not shown for Ibichhütte (w225049593) and Fjärdbotten 6 (w1198939711), which also have no wikidata entry.
So commons retrieval sometimes works without wikidata.

- Wrong category images are shown for Fjärdbotten 7 (w1349704366), which has a wikidata entry w/o category link (before adding it)
- Images are still wrong for Fjärdbotten 7 after adding commons category to wikidata (Osmand closed and cache cleared before checking). That said, it takes some time until the wiki bots make the connection between wikidata and commons categories. I'll check again once that has happened and I'll get the Osmand offline maps live update tonight. Maybe these two change something. 

 To test if there is an interaction between image=* and wikimedia_commons=Category:*, I've removed the image=* entry from Ibichhütte.

Unless something happens after the updates, adding the commons category to wikidata does not seem to make a consistent difference. I'll see tomorrow.

I could do an experiment and remove/change the commons category entry in wikidata (reverse it later, of course) to track down the bug - but in any case, as you say, the wikidata_commons retrieval should not depend on wikidata entries. So that would probably be useless information. Let me know if that is needed.

Besides that, do you have any idea why author & license are not showing sometimes? 
These two images have the same entry codes in commons, with the same license but different author and dates, 
yet:
Fjärdbotten 2 outside.jpg:  date/author/license information are shown correctly in Osmand
Fjärdbotten hut 7, 20250820 03.jpg: not showing

Since both are cc-by-sa-4.0 license images, this information would need to be shown the same way.

**Comment by uegert** [comment]
Maybe not relevant but for completeness: The wikidata entry of Fjärdbotten 7 (w1349704366) was linked to the wrong OSM way (same as Fjärdbotten hut 3). This is now corrected.

**Comment by uegert** [comment]
Commons has now linked Category:Fjärdbotten hut 7 and wikidata Fjärdbotten hut 7 (Q121541351). The offline map for Sweden was also updated last night (live update). The images in the category now show in Osmand but also 2 others that are not in the Category. Which confirms the undesired need for a link between wikimedia Category and wikidata commons_category entry. It is apparently not sufficient that there is a wikidata entry, it must be linked to commons for Osmand to show the images. This does, however, not explain the off-category images (I cleared the Osmand cache before testing). 

Image information that was previously not shown is now retrieved (author/date/license), also for other huts that do not have a wikidata entry and did not show the information yesterday. 

Ibichhütte (no wikidata entry and, now without images= tag, map updated) still only shows 1 image from commons but without detailed informaton.

**Comment by alisa911** [comment]
@uegert Thank you for the detailed testing and observations! 
App retrieves images from both Wikidata and Wikimedia Commons categories when available:
- Wikidata images: Retrieved via the wikidata tag in OSM
- Commons category images: Retrieved via the wikimedia_commons tag in OSM
- Deduplication: Images appearing in both sources are automatically deduplicated to avoid showing the same image twice

The system is designed to show all images we can find from both sources. You don't need a link between the Wikimedia Category and Wikidata commons_category property - app fetches from both independently when the respective tags are present in OSM.

For Fjärdbotten hut 7, you're seeing 10 unique images total:
- 8 images from the Commons category
- 4 images from Wikidata
- Minus 2 duplicates = 10 images displayed

**Comment by uegert** [comment]
@alisa911, thanks for the explanation. 
Using both sources+deduplication seems to create problems: all images on wikidata Fjärdbotten hut 7 are also in Category:Fjärdbotten hut 7, so there should be only 8 images. The files [Fjärdbotten_2_view.jpg](https://commons.wikimedia.org/wiki/File:Fj%C3%A4rdbotten_2_view.jpg) ([Category:Fjärdbotten campsite](https://commons.wikimedia.org/wiki/Category:Fj%C3%A4rdbotten_campsite)) and [Fjärdbotten_2_inside_2.jpg, renamed to Fjärdbotten hut 3 inside 2 2020-09-15.jpg](https://commons.wikimedia.org/wiki/File:Fj%C3%A4rdbotten_hut_3_inside_2_2020-09-15.jpg) ([Category:Fjärdbotten hut 3](https://commons.wikimedia.org/wiki/Category:Fj%C3%A4rdbotten_hut_3)) are not in [Category:Fjärdbotten hut 7](https://commons.wikimedia.org/wiki/Category:Fj%C3%A4rdbotten_hut_7) and not on wikidata. So they should not be shown. I overhauled the area and wikimedia category structure some time ago. It almost seems as if the wrong images are still stuck in some cache somewhere. 

The retrieval of category images doesn't always work for wikimedia_commons tags only, without wikidata as for (as for [Ibichhütte](https://commons.wikimedia.org/wiki/Category:Ibichh%C3%BCtte,_Simonswald), node [w225049593](https://www.openstreetmap.org/edit#map=20/48.1109061/8.1051142). 

Yet, for others it works, the Category images are shown in Osmand, for example 
Fjärdbotten hut 2 [w1198939292](https://www.openstreetmap.org/edit#map=20/62.8162066/18.1558956), [Category:Fjärdbotten hut 2](https://commons.wikimedia.org/wiki/Category:Fj%C3%A4rdbotten_hut_2). No wikidata entry here.

**Comment by alisa911** [comment]
@uegert 
The first image [https://commons.wikimedia.org/wiki/File:Fj%C3%A4rdbotten_hut_3_inside_2_2020-09-15.jpg](https://commons.wikimedia.org/wiki/File:Fj%C3%A4rdbotten_hut_3_inside_2_2020-09-15.jpg)
In structured data, depicts (P180) has a link to [wikidataId](https://www.wikidata.org/wiki/Q121541351). Similarly in https://commons.wikimedia.org/wiki/File:Fj%C3%A4rdbotten_2_view.jpg

We collect and store all images linked to a Wikidata ID, using only the official latest-mediainfo.json.bz2 dump

**Comment by uegert** [comment]
@alisa911 Thank you, that is interesting! Indeed, these p180 entries are wrong (now corrected). So Osmand not only uses the category and the images from wikidata but also takes the p180 link from a commons image, associates that with the wikidata item, without using the wikidata=* of the OSM object. 

Since commons images do not (should not) have OSM node/way entries, it seems like Osmand is taking another round here: 
1) find commons p180 entries that match some wikidata entry, irrespective of a wikidata=* tag on OSM.
2) take wikidata=* tag on OSM and find images there
3) take wikimedia_commons=tag on OSM and find images
4) deduplicate

... or something similar. 

However, p180 can be very general: For example "[picnic table](https://www.wikidata.org/wiki/Special:EntityPage/Q2466395)" is a valid entry since there is a picnic table in the image (it happens to not have an OSM node entry in wikidata). Here is an example showing the object class "[lean-to with wooden plank floor](https://www.wikidata.org/wiki/Q96357537)" with several examples. So, given that p180 is read, should Osmand show these images with every commons image that has p180=lean-to with wooden plank floor? That would not be correct. Testing that for node [9847335008](https://www.openstreetmap.org/edit#map=20/58.0206741/12.0293629) and [2501438527](https://www.openstreetmap.org/edit#map=20/58.9337487/11.4358389), Osmand does not show the other images of [Q96357537](https://www.wikidata.org/wiki/Q96357537), even though p180=Q96357537 for the images. So that does not seem to be consistent.
I could imagine a p180 pointing to a wikidata entry with a more general concept + images - which could lead to strange collections of images. 
While I understand the motivation for this approach (I think), it may not be very robust.  
In turn, how does Osmand treat the "has part(s)" field of wikidata entries?

**Comment by uegert** [comment]
What I would have expected is:

- If there is a valid wikimedia_commons=*  File/Category/Gallery tag, use those images
- If there is a valid wikidata=* tag, use those images (if permissible)
- If there is a valid image tag=* use that image (if permissible)
- deduplicate and show unique images only.

I would expect that these are independent, except for deduplication.
