### ISSUE TITLE
Crash when switching profile

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#21598]
### Description

Crash when switching profiles using the button in the upper left corner.
![Screenshot_2024-12-20-23-41-28-870_net osmand plus-edit](https://github.com/user-attachments/assets/0a878d4a-c944-47d1-8457-8210fcde998f)

```
Version  OsmAnd~ 5.0.0#3976m
20.12.2024 11:36:29
Apk Version : 5.0.0#3976m 5000
Exception occurred in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at net.osmand.plus.configmap.routes.RouteUtils.getIconIdForAttr(RouteUtils.java:110)
	at net.osmand.plus.configmap.ConfigureMapMenu.createRouteAttributeItems(ConfigureMapMenu.java:235)
	at net.osmand.plus.configmap.ConfigureMapMenu.createListAdapter(ConfigureMapMenu.java:111)
	at net.osmand.plus.configmap.ConfigureMapFragment.updateItemsData(ConfigureMapFragment.java:148)
	at net.osmand.plus.configmap.ConfigureMapFragment.recreateView(ConfigureMapFragment.java:141)
	at net.osmand.plus.configmap.ConfigureMapFragment.onDataSetInvalidated(ConfigureMapFragment.java:95)
	at net.osmand.plus.configmap.ConfigureMapFragment.onCreateView(ConfigureMapFragment.java:84)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8503)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

### Steps to reproduce

Described above.

### Actual result

Crash

### Expected result

No crash.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
We couldn’t reproduce the crash when switching profiles using the top-left icon; the profile changed successfully.

Please update to 3978m and try again.
Related to #21601

OsmAnd~ 5.0.0#3978m, released: 2024-12-20

https://github.com/user-attachments/assets/36d99ade-692d-4eb5-9df5-b676a5042b83

**Comment by Nine-Tailed** [comment]
in version OsmAnd~ 5.0.0#3978m it doesn't crash.
