### ISSUE TITLE
OSM Live crash (not reproducable, but happened twice for me)

### ISSUE THREAD

**Issue by quelbs** [osmandapp/Osmand#2175]
When pressing OSM Live it only worked the third time I tried. I previously tested the issue #2169 so maybe that could be a remains of this test, but anyhow, here is the exception log:

```
Version  OsmAnd~ 2.3.0#15339M
19.01.2016 7:51:48
Apk Version : 2.3.0#15339M 231
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException
	at net.osmand.plus.resources.IncrementalChangesManager.getTimestamp(IncrementalChangesManager.java:379)
	at net.osmand.plus.resources.IncrementalChangesManager.getTimestamp(IncrementalChangesManager.java:370)
	at net.osmand.plus.liveupdates.LiveUpdatesFragment$LocalFullMapsViewHolder.bindLocalIndexInfo(LiveUpdatesFragment.java:357)
	at net.osmand.plus.liveupdates.LiveUpdatesFragment$LocalIndexesAdapter.getChildView(LiveUpdatesFragment.java:188)
	at android.widget.ExpandableListConnector.getView(ExpandableListConnector.java:451)
	at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)
	at android.widget.AbsListView.obtainView(AbsListView.java:2207)
	at android.widget.ListView.makeAndAddView(ListView.java:1845)
	at android.widget.ListView.fillDown(ListView.java:678)
	at android.widget.ListView.fillSpecific(ListView.java:1336)
	at android.widget.ListView.layoutChildren(ListView.java:1639)
	at android.widget.AbsListView.onLayout(AbsListView.java:2037)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1627)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1670)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1528)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1441)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:435)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1670)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1528)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1441)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2183)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1947)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1139)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4879)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
	at android.view.Choreographer.doCallbacks(Choreographer.java:579)
	at android.view.Choreographer.doFrame(Choreographer.java:548)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:762)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:153)
	at android.app.ActivityThread.main(ActivityThread.java:5299)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(Native Method)
Version  OsmAnd~ 2.3.0#15339M
19.01.2016 7:51:48
Apk Version : 2.3.0#15339M 231
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException
	at net.osmand.plus.resources.IncrementalChangesManager.getTimestamp(IncrementalChangesManager.java:379)
	at net.osmand.plus.resources.IncrementalChangesManager.getTimestamp(IncrementalChangesManager.java:370)
	at net.osmand.plus.liveupdates.LiveUpdatesFragment$LocalFullMapsViewHolder.bindLocalIndexInfo(LiveUpdatesFragment.java:357)
	at net.osmand.plus.liveupdates.LiveUpdatesFragment$LocalIndexesAdapter.getChildView(LiveUpdatesFragment.java:188)
	at android.widget.ExpandableListConnector.getView(ExpandableListConnector.java:451)
	at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)
	at android.widget.AbsListView.obtainView(AbsListView.java:2207)
	at android.widget.ListView.makeAndAddView(ListView.java:1845)
	at android.widget.ListView.fillDown(ListView.java:678)
	at android.widget.ListView.fillSpecific(ListView.java:1336)
	at android.widget.ListView.layoutChildren(ListView.java:1639)
	at android.widget.AbsListView.onLayout(AbsListView.java:2037)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1627)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1670)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1528)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1441)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:435)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1670)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1528)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1441)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2183)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1947)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1139)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4879)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
	at android.view.Choreographer.doCallbacks(Choreographer.java:579)
	at android.view.Choreographer.doFrame(Choreographer.java:548)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:762)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:153)
	at android.app.ActivityThread.main(ActivityThread.java:5299)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by vshcherb** [comment]
Fixed
