### ISSUE TITLE
Some instabilities introduced lately

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2214]
See log attached.

Issue 1 has been around for several days now, is observed on devices not registered with a google account, when leaving the OSM Live screen (without making any changes).

Issue 2 was observed when adding an interim destination point to an existing route calculation.
[exception.log.txt](https://github.com/osmandapp/Osmand/files/115225/exception.log.txt)

**Comment by vshcherb** [comment]
ava.lang.RuntimeException: Unable to destroy activity {net.osmand.plus/net.osmand.plus.liveupdates.OsmLiveActivity}: java.lang.IllegalArgumentException: Service not registered: net.osmand.plus.inapp.util.IabHelper$1@448e2a28
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3812)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3830)
	at android.app.ActivityThread.access$1500(ActivityThread.java:174)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1360)
