### ISSUE TITLE
Crash on 2.3

### ISSUE THREAD

**Issue by crimean** [osmandapp/Osmand#2218]
Version  OsmAnd~ 2.3.0#2785M_2.3
05.02.2016 3:37:02
Apk Version : 2.3.0#2785M_2.3 231
Exception occured in thread Thread[main,5,main] : 
java.lang.NoSuchMethodError: android.view.Display.getSize
    at net.osmand.plus.views.DoubleTapScaleDetector.<init>(DoubleTapScaleDetector.java:39)
    at net.osmand.plus.views.OsmandMapTileView.init(OsmandMapTileView.java:224)
    at net.osmand.plus.views.OsmandMapTileView.<init>(OsmandMapTileView.java:183)
    at net.osmand.plus.activities.MapActivity.onCreate(MapActivity.java:197)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1623)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1675)
    at android.app.ActivityThread.access$1500(ActivityThread.java:121)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:943)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:130)
    at android.app.ActivityThread.main(ActivityThread.java:3701)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:507)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by crimean** [comment]
Version  OsmAnd~ 2.3.0#2876M_2.3
12.02.2016 7:22:16
Apk Version : 2.3.0#2876M_2.3 231
Exception occured in thread Thread[main,5,main] : 
java.lang.NoSuchMethodError: android.view.Display.getSize
    at net.osmand.plus.views.OsmandMapTileView.init(OsmandMapTileView.java:237)
    at net.osmand.plus.views.OsmandMapTileView.<init>(OsmandMapTileView.java:183)
    at net.osmand.plus.activities.MapActivity.onCreate(MapActivity.java:198)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1623)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1675)
    at android.app.ActivityThread.access$1500(ActivityThread.java:121)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:943)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:130)
    at android.app.ActivityThread.main(ActivityThread.java:3701)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:507)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)
