### ISSUE TITLE
AudioVideoNotesPlugin crashes

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#2240]
Version  OsmAnd~ 2.3.0#15606M
08.02.2016 12:52:23
Apk Version : 2.3.0#15606M 231
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.Camera.cancelAutoFocus()' on a null object reference
	at net.osmand.plus.audionotes.AudioVideoNotesPlugin.shootAgain(AudioVideoNotesPlugin.java:1916)
	at net.osmand.plus.audionotes.AudioVideoNoteRecordingMenuFullScreen$1.onClick(AudioVideoNoteRecordingMenuFullScreen.java:49)
	at android.view.View.performClick(View.java:4792)
	at android.view.View$PerformClick.run(View.java:19936)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5595)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by xmd5a2** [comment]
Version  OsmAnd~ 2.3.0#15732M
17.02.2016 10:28:19
Apk Version : 2.3.0#15732M 231
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v4.app.FragmentManager net.osmand.plus.activities.MapActivity.getSupportFragmentManager()' on a null object reference
	at net.osmand.plus.audionotes.AudioVideoNoteRecordingMenuFullScreen.findMenuFragment(AudioVideoNoteRecordingMenuFullScreen.java:76)
	at net.osmand.plus.audionotes.AudioVideoNoteRecordingMenuFullScreen.hide(AudioVideoNoteRecordingMenuFullScreen.java:38)
	at net.osmand.plus.audionotes.AudioVideoNotesPlugin$17.run(AudioVideoNotesPlugin.java:1758)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5595)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
