### ISSUE TITLE
Problems with Android 6.0

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#2244]
My phone updated to Android 6.0 and osmand stopped to work.
I guess this will hit a lot of users when they update too.

In logcat I saw this:
```
java.lang.RuntimeException: Unable to resume activity {net.osmand/net.osmand.plus.activities.MapActivity}: java.lang.NullPointerException: Attempt to get length of null array
	at net.osmand.map.TileSourceManager.findOneTile(TileSourceManager.java:376)
	at net.osmand.map.TileSourceManager.createTileSourceTemplate(TileSourceManager.java:348)
	at net.osmand.plus.OsmandSettings.getTileSourceByName(OsmandSettings.java:1142)
	at net.osmand.plus.OsmandSettings.getMapTileSource(OsmandSettings.java:1103)
	at net.osmand.plus.activities.MapActivityLayers.updateMapSource(MapActivityLayers.java:196)
	at net.osmand.plus.activities.MapActivityLayers.updateLayers(MapActivityLayers.java:176)
	at net.osmand.plus.activities.MapActivity.updateApplicationModeSettings(MapActivity.java:791)
	at net.osmand.plus.activities.MapActivity.onResume(MapActivity.java:463)
```
```
GPXUtilities Error reading gpx
java.io.FileNotFoundException: /storage/emulated/0/osmand/favourites.gpx: open failed: EACCES (Permission denied)
	at libcore.io.IoBridge.open(IoBridge.java:452)
	at java.io.FileInputStream.<init>(FileInputStream.java:76)
	at net.osmand.plus.GPXUtilities.loadGPXFile(GPXUtilities.java:937)
	at net.osmand.plus.FavouritesDbHelper.loadGPXFile(FavouritesDbHelper.java:537)
	at net.osmand.plus.FavouritesDbHelper.loadFavorites(FavouritesDbHelper.java:77)
	at net.osmand.plus.AppInitializer.startApplicationBackground(AppInitializer.java:461)
	at net.osmand.plus.AppInitializer.access$200(AppInitializer.java:70)
	at net.osmand.plus.AppInitializer$9.run(AppInitializer.java:709)
	at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
	at libcore.io.IoBridge.open(IoBridge.java:438)
	... 8 more
```
```
MapRenderingTypes Unexpected error
java.io.FileNotFoundException: /storage/emulated/0/osmand/poi_types.xml: open failed: EACCES (Permission denied)
	at libcore.io.IoBridge.open(IoBridge.java:452)
	at java.io.FileInputStream.<init>(FileInputStream.java:76)
	at java.io.FileInputStream.<init>(FileInputStream.java:103)
	at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:265)
	at net.osmand.plus.AppInitializer.initPoiTypes(AppInitializer.java:287)
	at net.osmand.plus.AppInitializer.startApplicationBackground(AppInitializer.java:464)
	at net.osmand.plus.AppInitializer.access$200(AppInitializer.java:70)
	at net.osmand.plus.AppInitializer$9.run(AppInitializer.java:709)
	at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
	at libcore.io.IoBridge.open(IoBridge.java:438)
	... 8 more
```
```
java.io.FileNotFoundException: /storage/emulated/0/osmand/poi_types.xml: open failed: EACCES (Permission denied)
        at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:265)
        at net.osmand.plus.AppInitializer.initPoiTypes(AppInitializer.java:287)
        at net.osmand.plus.AppInitializer.startApplicationBackground(AppInitializer.java:464)
        at net.osmand.plus.AppInitializer.access$200(AppInitializer.java:70)
        at net.osmand.plus.AppInitializer$9.run(AppInitializer.java:709)
java.lang.RuntimeException: java.io.FileNotFoundException: /storage/emulated/0/osmand/poi_types.xml: open failed: EACCES (Permission denied)
        at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:335)
        at net.osmand.plus.AppInitializer.initPoiTypes(AppInitializer.java:287)
        at net.osmand.plus.AppInitializer.startApplicationBackground(AppInitializer.java:464)
        at net.osmand.plus.AppInitializer.access$200(AppInitializer.java:70)
        at net.osmand.plus.AppInitializer$9.run(AppInitializer.java:709)
Caused by: java.io.FileNotFoundException: /storage/emulated/0/osmand/poi_types.xml: open failed: EACCES (Permission denied)
        at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:265)
TileSourceManager Error reading metainfo file /storage/emulated/0/osmand/tiles/OsmAnd (online tiles)
java.io.FileNotFoundException: /storage/emulated/0/osmand/tiles/OsmAnd (online tiles)/.metainfo: open failed: EACCES (Permission denied)
        at libcore.io.IoBridge.open(IoBridge.java:452)
        at java.io.FileInputStream.<init>(FileInputStream.java:76)
        at net.osmand.map.TileSourceManager.readMetaInfoFile(TileSourceManager.java:261)
        at net.osmand.map.TileSourceManager.createTileSourceTemplate(TileSourceManager.java:336)
        at net.osmand.plus.OsmandSettings.getTileSourceByName(OsmandSettings.java:1142)
        at net.osmand.plus.OsmandSettings.getMapTileSource(OsmandSettings.java:1103)
        at net.osmand.plus.activities.MapActivityLayers.updateMapSource(MapActivityLayers.java:196)
        at net.osmand.plus.activities.MapActivityLayers.updateLayers(MapActivityLayers.java:176)
        at net.osmand.plus.activities.MapActivity.updateApplicationModeSettings(MapActivity.java:791)
        at net.osmand.plus.activities.MapActivity.onResume(MapActivity.java:463)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1281)
        at android.app.Activity.performResume(Activity.java:6320)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3110)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3152)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5443)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
        at libcore.io.IoBridge.open(IoBridge.java:438)
```
```
RendererRegistry Error loading renderer
java.io.FileNotFoundException: /storage/emulated/0/osmand/rendering/default.render.xml: open failed: EACCES (Permission denied)
        at libcore.io.IoBridge.open(IoBridge.java:452)
        at java.io.FileInputStream.<init>(FileInputStream.java:76)
        at net.osmand.plus.render.RendererRegistry.getInputStream(RendererRegistry.java:172)
        at net.osmand.plus.render.RendererRegistry.loadRenderer(RendererRegistry.java:103)
        at net.osmand.plus.render.RendererRegistry.getRenderer(RendererRegistry.java:79)
        at net.osmand.plus.activities.MapActivity$7.doInBackground(MapActivity.java:814)
        at net.osmand.plus.activities.MapActivity$7.doInBackground(MapActivity.java:809)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
        at libcore.io.IoBridge.open(IoBridge.java:438)
```

I had to uninstall it and install again.
It seems that permissions in Android are a mess now (it asks to allow access to the storage, to read the maps, access to location, etc).

Maybe osmand could gracefully handle the access errors instead just crashing?

Phone:
```
build.brand: motorola
build.cpu_abi: armeabi-v7a
build.cpu_abi2: armeabi
build.device: titan_udstv
build.hardware: qcom
build.manufacturer: motorola
build.model: XT1069
build.product: titan_retbr_dstv
version.codename: REL
version.incremental: 31
version.release: 6.0
version.sdk_int: 23
```

**Comment by vshcherb** [comment]
If somebody is able to test the issue, please do it.
