### ISSUE TITLE
Crash on geo intent

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#2256]
Version  OsmAnd~ 2.3.0
20.02.2016 4:59:17
Apk Version : 2.3.0 231
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.content.Intent.mAction' on a null object reference
	at android.content.Intent.<init>(Intent.java:4349)
	at net.osmand.plus.activities.MapActivity.launchMapActivityMoveToTop(MapActivity.java:1040)
	at net.osmand.plus.activities.search.GeoIntentActivity.onItemClick(GeoIntentActivity.java:97)
	at net.osmand.plus.activities.search.GeoIntentActivity$GeoIntentTask.onPostExecute(GeoIntentActivity.java:140)
	at net.osmand.plus.activities.search.GeoIntentActivity$GeoIntentTask.onPostExecute(GeoIntentActivity.java:100)

**Comment by crimean** [comment]
Я пофиксил. Все равно не работает или старый билд?

**Comment by vshcherb** [comment]
I reported in order to not forget.
