### ISSUE TITLE
"java.sql.SQLException: UNIQUE constraint failed" with OsmAndMapCreator

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#2323]
While generating some maps I am seeing:

```
mar 10, 2016 9:07:36 AM net.osmand.data.preparation.IndexCreator generateIndexes
GRAVE: Log exception
java.sql.SQLException: UNIQUE constraint failed: binary_map_objects.id
	at org.sqlite.core.DB.throwex(DB.java:859)
	at org.sqlite.core.DB.executeBatch(DB.java:760)
	at org.sqlite.core.CorePreparedStatement.executeBatch(CorePreparedStatement.java:77)
	at net.osmand.data.preparation.AbstractIndexPartCreator.addBatch(AbstractIndexPartCreator.java:75)
	at net.osmand.data.preparation.AbstractIndexPartCreator.addBatch(AbstractIndexPartCreator.java:69)
	at net.osmand.data.preparation.IndexVectorMapCreator.insertBinaryMapRenderObjectIndex(IndexVectorMapCreator.java:1039)
	at net.osmand.data.preparation.IndexVectorMapCreator.createMultipolygonObject(IndexVectorMapCreator.java:319)
	at net.osmand.data.preparation.IndexVectorMapCreator.indexMultiPolygon(IndexVectorMapCreator.java:281)
	at net.osmand.data.preparation.IndexVectorMapCreator.indexMapRelationsAndMultiPolygons(IndexVectorMapCreator.java:141)
	at net.osmand.data.preparation.IndexCreator$9.iterateEntity(IndexCreator.java:785)
	at net.osmand.data.preparation.OsmDbAccessor.iterateOverEntities(OsmDbAccessor.java:252)
	at net.osmand.data.preparation.OsmDbAccessor.iterateOverEntities(OsmDbAccessor.java:206)
	at net.osmand.data.preparation.IndexCreator.indexRelations(IndexCreator.java:777)
	at net.osmand.data.preparation.IndexCreator.generateIndexes(IndexCreator.java:596)
	at net.osmand.data.preparation.IndexCreator.generateIndexes(IndexCreator.java:519)
	at net.osmand.data.index.IndexBatchCreator.generateIndex(IndexBatchCreator.java:548)
	at net.osmand.data.index.IndexBatchCreator.generatedIndexes(IndexBatchCreator.java:460)
	at net.osmand.data.index.IndexBatchCreator.runBatch(IndexBatchCreator.java:306)
	at net.osmand.data.index.IndexBatchCreator.main(IndexBatchCreator.java:164)
```

I am using the latest OsmAndMapCreator and it seems that this problem is present since 3 or 4 days ago.

One example file which is having this problem: http://naoliv.iq.unesp.br/osm/Brasil-SP.osm.pbf

**Comment by vshcherb** [comment]
Fixed
