### ISSUE TITLE
Geocoding related crash

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#2340]
Version  OsmAnd~ 2.3.0#16126M
15.03.2016 6:21:56
Apk Version : 2.3.0#16126M 231
Exception occured in thread Thread[Calculating position,5,main] : 
java.lang.ArrayIndexOutOfBoundsException: length=7; index=25
	at net.osmand.binary.BinaryMapAddressReaderAdapter.readCityHeader(BinaryMapAddressReaderAdapter.java:239)
	at net.osmand.binary.BinaryMapAddressReaderAdapter.searchAddressDataByName(BinaryMapAddressReaderAdapter.java:588)
	at net.osmand.binary.BinaryMapIndexReader.searchAddressDataByName(BinaryMapIndexReader.java:1275)
	at net.osmand.binary.GeocodingUtilities.justifyReverseGeocodingSearch(GeocodingUtilities.java:280)
	at net.osmand.plus.resources.RegionAddressRepositoryBinary.justifyReverseGeocodingSearch(RegionAddressRepositoryBinary.java:74)
	at net.osmand.plus.CurrentPositionHelper.justifyResult(CurrentPositionHelper.java:116)
	at net.osmand.plus.CurrentPositionHelper$1.run(CurrentPositionHelper.java:73)
	at net.osmand.plus.routing.RoutingHelper$5.run(RoutingHelper.java:925)
	at java.lang.Thread.run(Thread.java:831)

**Comment by vshcherb** [comment]
This crash could happen only during simultaneous address search & geocoding
