### ISSUE TITLE
NB - search by coordinates -> crash

### ISSUE THREAD

**Issue by Barrocas** [osmandapp/Osmand#2380]
BQ Aquaris E6, running Android 4.4.2

Version  OsmAnd~ 2.4.0#16246M
29.03.2016 10:37:43
Apk Version : 2.4.0#16246M 231
Exception occured in thread Thread[Calculating position,5,main] : 
java.lang.RuntimeException: Loading data exception
	at net.osmand.router.RoutingContext.loadTileHeaders(RoutingContext.java:435)
	at net.osmand.router.RoutingContext.loadTileHeaders(RoutingContext.java:367)
	at net.osmand.router.RoutingContext.getRoutingTile(RoutingContext.java:504)
	at net.osmand.router.RoutingContext.loadTileData(RoutingContext.java:455)
	at net.osmand.router.RoutePlannerFrontEnd.findRouteSegment(RoutePlannerFrontEnd.java:62)
	at net.osmand.binary.GeocodingUtilities.reverseGeocodingSearch(GeocodingUtilities.java:164)
	at net.osmand.plus.CurrentPositionHelper.runUpdateInThread(CurrentPositionHelper.java:208)
	at net.osmand.plus.CurrentPositionHelper.access$000(CurrentPositionHelper.java:24)
	at net.osmand.plus.CurrentPositionHelper$1.run(CurrentPositionHelper.java:67)
	at net.osmand.plus.routing.RoutingHelper$5.run(RoutingHelper.java:926)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.io.IOException: lseek failed: EBADF (Bad file number)
	at java.io.RandomAccessFile.seek(RandomAccessFile.java:603)
	at com.google.protobuf.CodedInputStream.seek(CodedInputStream.java:919)
	at net.osmand.binary.BinaryMapRouteReaderAdapter.searchRouteRegionTree(BinaryMapRouteReaderAdapter.java:813)
	at net.osmand.binary.BinaryMapIndexReader.searchRouteIndexTree(BinaryMapIndexReader.java:2459)
	at net.osmand.router.RoutingContext.loadTileHeaders(RoutingContext.java:414)
	... 10 more
Caused by: libcore.io.ErrnoException: lseek failed: EBADF (Bad file number)
	at libcore.io.Posix.lseek(Native Method)
	at libcore.io.ForwardingOs.lseek(ForwardingOs.java:89)
	at java.io.RandomAccessFile.seek(RandomAccessFile.java:601)
	... 14 more

**Comment by vshcherb** [comment]
Does it happen often? Do you have a regular path to reproduce it?

**Comment by Barrocas** [comment]
Cannot reproduce in today's build.

**Comment by vshcherb** [comment]
Today we fixed that issue I think...
