### ISSUE TITLE
Crash 2.3 - RouteInfoWidgetsFactory

### ISSUE THREAD

**Issue by crimean** [osmandapp/Osmand#2395]
Version  OsmAnd~ 2.4.0#3287M_2.3
28.03.2016 4:52:51
Apk Version : 2.4.0#3287M_2.3 231
Exception occured in thread Thread[main,5,main] : 
java.lang.NoClassDefFoundError: android.util.ArrayMap
	at net.osmand.plus.views.mapwidgets.RouteInfoWidgetsFactory$LanesDrawable.<init>(RouteInfoWidgetsFactory.java:633)
	at net.osmand.plus.views.mapwidgets.RouteInfoWidgetsFactory$LanesControl.<init>(RouteInfoWidgetsFactory.java:538)
	at net.osmand.plus.views.mapwidgets.RouteInfoWidgetsFactory.createLanesControl(RouteInfoWidgetsFactory.java:770)
	at net.osmand.plus.views.MapInfoLayer.registerAllControls(MapInfoLayer.java:99)
	at net.osmand.plus.views.MapInfoLayer.initLayer(MapInfoLayer.java:75)
	at net.osmand.plus.views.OsmandMapTileView.addLayer(OsmandMapTileView.java:279)
	at net.osmand.plus.activities.MapActivityLayers.createLayers(MapActivityLayers.java:159)
	at net.osmand.plus.activities.MapActivity.onCreate(MapActivity.java:260)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1623)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1675)
	at android.app.ActivityThread.access$1500(ActivityThread.java:121)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:943)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:130)
	at android.app.ActivityThread.main(ActivityThread.java:3701)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by vshcherb** [comment]
Fixed already
