### ISSUE TITLE
Crash after changing track color

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#2405]
When changing color of the path Osmand stops when activating tracking.

Device : E5303
Brand : Sony
Model : E5303
Product : E5303
Build : 27.1.A.1.106
Version : 5.0
App Version : OsmAnd+
Apk Version : 2.2.4 224

Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'net.osmand.plus.GPXUtilities$GPXFile net.osmand.plus.GpxSelectionHelper$SelectedGpxFile.getModifiableGpxFile()' on a null object reference
	at net.osmand.plus.myplaces.SelectedGPXFragment$4.onClick(SelectedGPXFragment.java:338)
	at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:153)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5636)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

**Comment by vshcherb** [comment]
2.3 fix if needed.

**Comment by GaidamakUA** [comment]
Can't reproduce. Please update to current version (2.3.3).
