### ISSUE TITLE
App crash when clicking on the "three dots" icon (development version)

### ISSUE THREAD

**Issue by jeckyhl** [osmandapp/Osmand#2406]
With OsmAnd~ 2.4.0, Android version 5.0, device Galaxy Note 3

To reproduce :
* Select a point on the map
* tap on the "three dots" icon on the bottom right corner 

--> this causes the app to crash (see screenshot below)

![tempfileforshare_2016-04-01-13-49-19](https://cloud.githubusercontent.com/assets/1909153/14206170/932fe7b4-f811-11e5-9370-df93f8a56be8.png)

code version infos : 
* OsmAnd Android App : repos `https://github.com/osmandapp/Osmand.git`, branch master, changeset 75d874136a573320193464b294bc3fd31147b49f, date Wed Mar 30 13:27:02 2016
* OsmAnd Resources : repos `https://github.com/osmandapp/OsmAnd-resources.git`, branch master, changeset e6e6b027db65df9c0793b2e1a506d38377e5f071, date Tue Mar 29 02:06:28 2016

here's the stacktrace 
```
Version  OsmAnd~ 2.4.0
01.04.2016 1:39:57
Apk Version : 2.4.0 231
Exception occured in thread Thread[main,5,main] : 
android.content.res.Resources$NotFoundException: Resource ID #0x0
	at android.content.res.Resources.getValue(Resources.java:2345)
	at android.content.res.Resources.getColor(Resources.java:1987)
	at android.support.v4.content.ContextCompat.getColor(ContextCompat.java:368)
	at net.osmand.plus.ContextMenuItem.getThemedColor(ContextMenuItem.java:93)
	at net.osmand.plus.ContextMenuAdapter$ContextMenuArrayAdapter.getView(ContextMenuAdapter.java:158)
	at android.widget.AbsListView.obtainView(AbsListView.java:2820)
	at android.widget.ListView.measureHeightOfChildren(ListView.java:1290)
	at android.widget.ListView.onMeasure(ListView.java:1202)
	at android.view.View.measure(View.java:18563)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
	at android.view.View.measure(View.java:18563)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:721)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:612)
	at android.view.View.measure(View.java:18563)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
	at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
	at android.view.View.measure(View.java:18563)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
	at android.view.View.measure(View.java:18563)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
	at android.view.View.measure(View.java:18563)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:721)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:612)
	at android.view.View.measure(View.java:18563)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2888)
	at android.view.View.measure(View.java:18563)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2248)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1281)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1548)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1191)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6642)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
	at android.view.Choreographer.doCallbacks(Choreographer.java:590)
	at android.view.Choreographer.doFrame(Choreographer.java:560)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5938)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
```

**Comment by vshcherb** [comment]
Fixed
