### ISSUE TITLE
Crash at net.osmand.plus.activities.MapActivity

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#2474]
OsmAnd crashed directly after startup:

> Device : thea
> Brand : motorola
> Model : Moto G 2014 LTE
> Product : cm_thea
> Build : cm_thea-userdebug 5.1.1 LMY48Y a9bb45598b test-keys
> Version : 5.1.1
> App Version : OsmAnd+
> Apk Version : 2.3.3 235

```
Version  OsmAnd+ 2.3.3
17.04.2016 9:21:39
Apk Version : 2.3.3 235
Exception occured in thread Thread[main,5,main] : 
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.osmand.plus/net.osmand.plus.activities.MapActivity}: java.lang.NullPointerException: name == null
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
	at android.app.ActivityThread.access$900(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5294)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
Caused by: java.lang.NullPointerException: name == null
	at java.lang.Enum.valueOf(Enum.java:189)
	at net.osmand.plus.osmedit.OsmPoint$Action.valueOf(OsmPoint.java:11)
	at net.osmand.plus.osmedit.OsmBugsLayer.prepareBugDialog(OsmBugsLayer.java:411)
	at net.osmand.plus.osmedit.OsmBugsLayer.onPrepareDialog(OsmBugsLayer.java:562)
	at net.osmand.plus.activities.MapActivity.onPrepareDialog(MapActivity.java:794)
	at android.app.Activity.onPrepareDialog(Activity.java:3357)
	at android.app.Activity.restoreManagedDialogs(Activity.java:1081)
	at android.app.Activity.performRestoreInstanceState(Activity.java:979)
	at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1162)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2331)
	... 10 more
```

**Comment by scaidermern** [comment]
Oh, this seems to be issue #2421 again.
