### ISSUE TITLE
Crash on 2.3

### ISSUE THREAD

**Issue by crimean** [osmandapp/Osmand#2483]
Проявляется когда активирован профайл отличный от обзорного.

Version  OsmAnd~ 2.4.0#3474M_2.3
21.04.2016 10:43:05
Apk Version : 2.4.0#3474M_2.3 231
Exception occured in thread Thread[main,5,main] : 
java.util.concurrent.RejectedExecutionException: pool=128/128, queue=10/10
    at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:1961)
    at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:794)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1315)
    at android.os.AsyncTask.execute(AsyncTask.java:394)
    at net.osmand.plus.CurrentPositionHelper.scheduleRouteSegmentFind(CurrentPositionHelper.java:67)
    at net.osmand.plus.CurrentPositionHelper.getLastKnownRouteSegment(CurrentPositionHelper.java:204)
    at net.osmand.plus.OsmAndLocationProvider.getLastKnownRouteSegment(OsmAndLocationProvider.java:855)
    at net.osmand.plus.views.mapwidgets.RouteInfoWidgetsFactory$8.updateInfo(RouteInfoWidgetsFactory.java:357)
    at net.osmand.plus.views.mapwidgets.MapWidgetRegistry.update(MapWidgetRegistry.java:108)
    at net.osmand.plus.views.mapwidgets.MapWidgetRegistry.updateInfo(MapWidgetRegistry.java:102)
    at net.osmand.plus.views.MapInfoLayer.onDraw(MapInfoLayer.java:275)
    at net.osmand.plus.views.OsmandMapTileView.drawOverMap(OsmandMapTileView.java:592)
    at net.osmand.plus.views.OsmandMapTileView.refreshMapInternal(OsmandMapTileView.java:527)
    at net.osmand.plus.views.OsmandMapTileView.access$900(OsmandMapTileView.java:62)
    at net.osmand.plus.views.OsmandMapTileView$3.run(OsmandMapTileView.java:665)
    at android.os.Handler.handleCallback(Handler.java:587)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:130)
    at android.app.ActivityThread.main(ActivityThread.java:3701)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:507)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by vshcherb** [comment]
Fixed
