### ISSUE TITLE
Search field not filled and then sent causes OsmAnd+ crash (Android KitKat)

### ISSUE THREAD

**Issue by JuliendeVillele** [osmandapp/Osmand#2495]
I've send the crash report.
This crash is reproductible on my device (Crosscall Trekker X1).
Don't know if it helps (?)
Sorry if any mistake, newbie on github.

**Comment by kompowiec** [comment]
1. give crashlog here
2. if this error is reproducible, give instruction how to do it.

**Comment by JuliendeVillele** [comment]
The instructions are :



Device : msm8226
Brand : Crosscall
Model : Trekker-X1
Product : T88CR
Build : KVT49L release-keys
Version : 4.4.2
App Version : OsmAnd+
Apk Version : 2.3.3 235


Version  OsmAnd+ 2.3.3
25.04.2016 5:20:10
Apk Version : 2.3.3 235
Exception occured in thread Thread[AsyncTask #5,5,main] : 
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:300)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.IllegalArgumentException
	at net.osmand.binary.BinaryMapIndexReader.searchPoiByName(BinaryMapIndexReader.java:1288)
	at net.osmand.plus.resources.AmenityIndexRepositoryBinary.searchAmenitiesByName(AmenityIndexRepositoryBinary.java:67)
	at net.osmand.plus.resources.ResourceManager.searchAmenitiesByName(ResourceManager.java:858)
	at net.osmand.plus.poi.SearchByNameFilter.searchAmenitiesInternal(SearchByNameFilter.java:36)
	at net.osmand.plus.poi.PoiUIFilter.searchAmenities(PoiUIFilter.java:231)
	at net.osmand.plus.poi.PoiUIFilter.initializeNewSearch(PoiUIFilter.java:203)
	at net.osmand.plus.activities.search.SearchPOIActivity$SearchAmenityTask.doInBackground(SearchPOIActivity.java:635)
	at net.osmand.plus.activities.search.SearchPOIActivity$SearchAmenityTask.doInBackground(SearchPOIActivity.java:564)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
Version  OsmAnd+ 2.3.3
25.04.2016 5:20:10
Apk Version : 2.3.3 235
Exception occured in thread Thread[AsyncTask #5,5,main] : 
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:300)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.IllegalArgumentException
	at net.osmand.binary.BinaryMapIndexReader.searchPoiByName(BinaryMapIndexReader.java:1288)
	at net.osmand.plus.resources.AmenityIndexRepositoryBinary.searchAmenitiesByName(AmenityIndexRepositoryBinary.java:67)
	at net.osmand.plus.resources.ResourceManager.searchAmenitiesByName(ResourceManager.java:858)
	at net.osmand.plus.poi.SearchByNameFilter.searchAmenitiesInternal(SearchByNameFilter.java:36)
	at net.osmand.plus.poi.PoiUIFilter.searchAmenities(PoiUIFilter.java:231)
	at net.osmand.plus.poi.PoiUIFilter.initializeNewSearch(PoiUIFilter.java:203)
	at net.osmand.plus.activities.search.SearchPOIActivity$SearchAmenityTask.doInBackground(SearchPOIActivity.java:635)
	at net.osmand.plus.activities.search.SearchPOIActivity$SearchAmenityTask.doInBackground(SearchPOIActivity.java:564)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
Version  OsmAnd+ 2.3.3
25.04.2016 5:20:43
Apk Version : 2.3.3 235
Exception occured in thread Thread[AsyncTask #3,5,main] : 
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:300)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.IllegalArgumentException
	at net.osmand.binary.BinaryMapIndexReader.searchPoiByName(BinaryMapIndexReader.java:1288)
	at net.osmand.plus.resources.AmenityIndexRepositoryBinary.searchAmenitiesByName(AmenityIndexRepositoryBinary.java:67)
	at net.osmand.plus.resources.ResourceManager.searchAmenitiesByName(ResourceManager.java:858)
	at net.osmand.plus.poi.SearchByNameFilter.searchAmenitiesInternal(SearchByNameFilter.java:36)
	at net.osmand.plus.poi.PoiUIFilter.searchAmenities(PoiUIFilter.java:231)
	at net.osmand.plus.poi.PoiUIFilter.initializeNewSearch(PoiUIFilter.java:203)
	at net.osmand.plus.activities.search.SearchPOIActivity$SearchAmenityTask.doInBackground(SearchPOIActivity.java:635)
	at net.osmand.plus.activities.search.SearchPOIActivity$SearchAmenityTask.doInBackground(SearchPOIActivity.java:564)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
Version  OsmAnd+ 2.3.3
25.04.2016 5:20:43
Apk Version : 2.3.3 235
Exception occured in thread Thread[AsyncTask #3,5,main] : 
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:300)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.IllegalArgumentException
	at net.osmand.binary.BinaryMapIndexReader.searchPoiByName(BinaryMapIndexReader.java:1288)
	at net.osmand.plus.resources.AmenityIndexRepositoryBinary.searchAmenitiesByName(AmenityIndexRepositoryBinary.java:67)
	at net.osmand.plus.resources.ResourceManager.searchAmenitiesByName(ResourceManager.java:858)
	at net.osmand.plus.poi.SearchByNameFilter.searchAmenitiesInternal(SearchByNameFilter.java:36)
	at net.osmand.plus.poi.PoiUIFilter.searchAmenities(PoiUIFilter.java:231)
	at net.osmand.plus.poi.PoiUIFilter.initializeNewSearch(PoiUIFilter.java:203)
	at net.osmand.plus.activities.search.SearchPOIActivity$SearchAmenityTask.doInBackground(SearchPOIActivity.java:635)
	at net.osmand.plus.activities.search.SearchPOIActivity$SearchAmenityTask.doInBackground(SearchPOIActivity.java:564)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
Version  OsmAnd+ 2.3.3
26.04.2016 7:01:26
Apk Version : 2.3.3 235
Exception occured in thread Thread[AsyncTask #4,5,main] : 
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:300)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.IllegalArgumentException
	at net.osmand.binary.BinaryMapIndexReader.searchPoiByName(BinaryMapIndexReader.java:1288)
	at net.osmand.plus.resources.AmenityIndexRepositoryBinary.searchAmenitiesByName(AmenityIndexRepositoryBinary.java:67)
	at net.osmand.plus.resources.ResourceManager.searchAmenitiesByName(ResourceManager.java:858)
	at net.osmand.plus.poi.SearchByNameFilter.searchAmenitiesInternal(SearchByNameFilter.java:36)
	at net.osmand.plus.poi.PoiUIFilter.searchAmenities(PoiUIFilter.java:231)
	at net.osmand.plus.poi.PoiUIFilter.initializeNewSearch(PoiUIFilter.java:203)
	at net.osmand.plus.activities.search.SearchPOIActivity$SearchAmenityTask.doInBackground(SearchPOIActivity.java:635)
	at net.osmand.plus.activities.search.SearchPOIActivity$SearchAmenityTask.doInBackground(SearchPOIActivity.java:564)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
Version  OsmAnd+ 2.3.3
26.04.2016 7:01:26
Apk Version : 2.3.3 235
Exception occured in thread Thread[AsyncTask #4,5,main] : 
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:300)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.IllegalArgumentException
	at net.osmand.binary.BinaryMapIndexReader.searchPoiByName(BinaryMapIndexReader.java:1288)
	at net.osmand.plus.resources.AmenityIndexRepositoryBinary.searchAmenitiesByName(AmenityIndexRepositoryBinary.java:67)
	at net.osmand.plus.resources.ResourceManager.searchAmenitiesByName(ResourceManager.java:858)
	at net.osmand.plus.poi.SearchByNameFilter.searchAmenitiesInternal(SearchByNameFilter.java:36)
	at net.osmand.plus.poi.PoiUIFilter.searchAmenities(PoiUIFilter.java:231)
	at net.osmand.plus.poi.PoiUIFilter.initializeNewSearch(PoiUIFilter.java:203)
	at net.osmand.plus.activities.search.SearchPOIActivity$SearchAmenityTask.doInBackground(SearchPOIActivity.java:635)
	at net.osmand.plus.activities.search.SearchPOIActivity$SearchAmenityTask.doInBackground(SearchPOIActivity.java:564)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more

**Comment by vshcherb** [comment]
The issue reproduced, so it should be just one space in the query ' '.

**Comment by scaidermern** [comment]
Reproducible with OsmAnd 2.3.5, same backtrace.

Accepting an empty query seems wrong, doesn't it?
