### ISSUE TITLE
Crash during map download at BaseOsmAndFragment.java:21

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#2513]
I started to download multiple maps. After a short time OsmAnd became very slow, then seemed to hang until it crashed.

```
Device : thea
Brand : motorola
Model : Moto G 2014 LTE
Product : cm_thea
Build : cm_thea-userdebug 5.1.1 LMY48Y a9bb45598b test-keys
Version : 5.1.1
App Version : OsmAnd+
Apk Version : 2.3.5 238
```

```
Version  OsmAnd+ 2.3.5
04.05.2016 7:16:59
Apk Version : 2.3.5 238
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Application android.support.v4.app.FragmentActivity.getApplication()' on a null object reference
	at net.osmand.plus.base.BaseOsmAndFragment.getMyApplication(BaseOsmAndFragment.java:21)
	at net.osmand.plus.download.ui.LocalIndexesFragment.access$900(LocalIndexesFragment.java:78)
	at net.osmand.plus.download.ui.LocalIndexesFragment$LocalIndexesAdapter.findCategory(LocalIndexesFragment.java:832)
	at net.osmand.plus.download.ui.LocalIndexesFragment$LocalIndexesAdapter.move(LocalIndexesFragment.java:855)
	at net.osmand.plus.download.ui.LocalIndexesFragment$LocalIndexOperationTask.onProgressUpdate(LocalIndexesFragment.java:490)
	at net.osmand.plus.download.ui.LocalIndexesFragment$LocalIndexOperationTask.onProgressUpdate(LocalIndexesFragment.java:378)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:656)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5294)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

Looks suspiciously like #1391.

**Comment by vshcherb** [comment]
Can you reproduce it? I see these crashes happen in < 0.1% cases, though it was always a mistery for me. I suspect application ran out of memory and that random place occurred.

**Comment by scaidermern** [comment]
No,  I can't reproduce it. Just happened once so far.
