### ISSUE TITLE
Crash while trying to route along GPX file at net.osmand.router.GeneralRouter$RouteAttributeEvalRule.checkAllTypesShouldBePresent

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#2521]
OsmAnd crashed while trying to route along a GPX file (can't remember if I selected a GPX track or route):

```
Device : thea
Brand : motorola
Model : Moto G 2014 LTE
Product : cm_thea
Build : cm_thea-userdebug 5.1.1 LMY48Y a9bb45598b test-keys
Version : 5.1.1
App Version : OsmAnd+
Apk Version : 2.3.5 238
```

```
Version  OsmAnd+ 2.3.5
06.05.2016 12:14:11
Apk Version : 2.3.5 238
Exception occured in thread Thread[AsyncTask #5,5,main] : 
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.IllegalArgumentException: start > end: 1 > 0
	at java.util.Arrays.checkStartAndEnd(Arrays.java:1736)
	at java.util.Arrays.fill(Arrays.java:840)
	at java.util.BitSet.and(BitSet.java:468)
	at net.osmand.router.GeneralRouter$RouteAttributeEvalRule.checkAllTypesShouldBePresent(GeneralRouter.java:860)
	at net.osmand.router.GeneralRouter$RouteAttributeEvalRule.matches(GeneralRouter.java:800)
	at net.osmand.router.GeneralRouter$RouteAttributeEvalRule.eval(GeneralRouter.java:771)
	at net.osmand.router.GeneralRouter$RouteAttributeContext.evaluate(GeneralRouter.java:495)
	at net.osmand.router.GeneralRouter$RouteAttributeContext.evaluate(GeneralRouter.java:472)
	at net.osmand.router.GeneralRouter$RouteAttributeContext.evaluateInt(GeneralRouter.java:523)
	at net.osmand.router.GeneralRouter.acceptLine(GeneralRouter.java:186)
	at net.osmand.router.RoutingContext.loadSubregionTile(RoutingContext.java:325)
	at net.osmand.router.RoutingContext.getRoutingTile(RoutingContext.java:523)
	at net.osmand.router.RoutingContext.loadTileData(RoutingContext.java:459)
	at net.osmand.router.RoutePlannerFrontEnd.findRouteSegment(RoutePlannerFrontEnd.java:62)
	at net.osmand.binary.GeocodingUtilities.reverseGeocodingSearch(GeocodingUtilities.java:164)
	at net.osmand.plus.CurrentPositionHelper.runUpdateInThread(CurrentPositionHelper.java:220)
	at net.osmand.plus.CurrentPositionHelper.processGeocoding(CurrentPositionHelper.java:87)
	at net.osmand.plus.CurrentPositionHelper.access$000(CurrentPositionHelper.java:26)
	at net.osmand.plus.CurrentPositionHelper$1.doInBackground(CurrentPositionHelper.java:72)
	at net.osmand.plus.CurrentPositionHelper$1.doInBackground(CurrentPositionHelper.java:67)
	at android.os.AsyncTask$2.call(AsyncTask.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
```

**Comment by vshcherb** [comment]
This is very interesting though crash is not related to GPX. It is related to context menu (long tap). The crash is very weird and we will need exact location to reproduce it. Unfortunately I never saw it before and the code behind it is > 1 year like that. So we need to get it reproduced otherwise it is hard to do something.

**Comment by scaidermern** [comment]
I'll try and see if it happens again.

**Comment by scaidermern** [comment]
Yep, I can reproduce it. However I still don't know exactly how. I went through multiple local GPX files (routes) and told OsmAnd to calculate a route along them. A few succeeded, then one produced a crash:

```
Version  OsmAnd+ 2.3.5
08.05.2016 5:47:42
Apk Version : 2.3.5 238
Exception occured in thread Thread[AsyncTask #1,5,main] : 
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.IllegalArgumentException: start > end: 1 > 0
	at java.util.Arrays.checkStartAndEnd(Arrays.java:1736)
	at java.util.Arrays.fill(Arrays.java:840)
	at java.util.BitSet.and(BitSet.java:468)
	at net.osmand.router.GeneralRouter$RouteAttributeEvalRule.checkAllTypesShouldBePresent(GeneralRouter.java:860)
	at net.osmand.router.GeneralRouter$RouteAttributeEvalRule.matches(GeneralRouter.java:800)
	at net.osmand.router.GeneralRouter$RouteAttributeEvalRule.eval(GeneralRouter.java:771)
	at net.osmand.router.GeneralRouter$RouteAttributeContext.evaluate(GeneralRouter.java:495)
	at net.osmand.router.GeneralRouter$RouteAttributeContext.evaluate(GeneralRouter.java:472)
	at net.osmand.router.GeneralRouter$RouteAttributeContext.evaluateInt(GeneralRouter.java:523)
	at net.osmand.router.GeneralRouter.acceptLine(GeneralRouter.java:186)
	at net.osmand.router.RoutingContext.loadSubregionTile(RoutingContext.java:325)
	at net.osmand.router.RoutingContext.getRoutingTile(RoutingContext.java:523)
	at net.osmand.router.RoutingContext.loadTileData(RoutingContext.java:459)
	at net.osmand.router.RoutePlannerFrontEnd.findRouteSegment(RoutePlannerFrontEnd.java:62)
	at net.osmand.binary.GeocodingUtilities.reverseGeocodingSearch(GeocodingUtilities.java:164)
	at net.osmand.plus.CurrentPositionHelper.runUpdateInThread(CurrentPositionHelper.java:220)
	at net.osmand.plus.CurrentPositionHelper.processGeocoding(CurrentPositionHelper.java:87)
	at net.osmand.plus.CurrentPositionHelper.access$000(CurrentPositionHelper.java:26)
	at net.osmand.plus.CurrentPositionHelper$1.doInBackground(CurrentPositionHelper.java:72)
	at net.osmand.plus.CurrentPositionHelper$1.doInBackground(CurrentPositionHelper.java:67)
	at android.os.AsyncTask$2.call(AsyncTask.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
```

After restarting OsmAnd, calculating a route with the very same file succeeded. Maybe this is just some race condition? The starting position must have been the same all the time since the location service is switched off. Please tell me how to provide more information.

Another thing that makes me wonder is: While OsmAnd is calculating a route along a GPX route the progress bar goes forward, then falls back to zero. This happens multiple times until the route is finally calculated. Is this a bug or a feature? I can imagine that OsmAnd displays a progress bar for each waypoint in the route, is this correct? Anyway, this is really confusing.

**Comment by vshcherb** [comment]
It looks like race condition. Though I didn't expect race condition in GeneralRouter class will need to check class member variables.
