### ISSUE TITLE
Crash while trying to route along GPX file at net.osmand.plus.routing.RoutingHelper.updateCurrentRouteStatus

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#2524]
OsmAnd crashed while trying to route along a GPX file:

```
Device : thea
Brand : motorola
Model : Moto G 2014 LTE
Product : cm_thea
Build : cm_thea-userdebug 5.1.1 LMY48Y a9bb45598b test-keys
Version : 5.1.1
App Version : OsmAnd+
Apk Version : 2.3.5 238
```

```
Version  OsmAnd+ 2.3.5
06.05.2016 2:14:26
Apk Version : 2.3.5 238
Exception occured in thread Thread[main,5,main] : 
java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
	at java.util.ArrayList.remove(ArrayList.java:403)
	at net.osmand.plus.routing.RoutingHelper.updateCurrentRouteStatus(RoutingHelper.java:487)
	at net.osmand.plus.routing.RoutingHelper.setCurrentLocation(RoutingHelper.java:307)
	at net.osmand.plus.routing.RoutingHelper.setCurrentLocation(RoutingHelper.java:276)
	at net.osmand.plus.OsmAndLocationProvider.setLocation(OsmAndLocationProvider.java:793)
	at net.osmand.plus.OsmAndLocationProvider.access$700(OsmAndLocationProvider.java:47)
	at net.osmand.plus.OsmAndLocationProvider$2.onLocationChanged(OsmAndLocationProvider.java:578)
	at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:281)
	at android.location.LocationManager$ListenerTransport.access$000(LocationManager.java:210)
	at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:226)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5294)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by vshcherb** [comment]
Thanks
