### ISSUE TITLE
Crash due to off-by-one in GeneralRouter.parseValueFromTag()

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#2543]
Nightly version crashed shortly after startup, seems to be an off-by-one-error:

```
Version  OsmAndF~ 2.4.0#12809D
13.05.2016 4:37:30
Apk Version : 2.4.0#12809D 231
Exception occured in thread Thread[AsyncTask #1,5,main] : 
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.IndexOutOfBoundsException: Invalid index 374, size is 374
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
	at java.util.ArrayList.get(ArrayList.java:308)
	at net.osmand.router.GeneralRouter.parseValueFromTag(GeneralRouter.java:244)
	at net.osmand.router.GeneralRouter.access$1300(GeneralRouter.java:24)
	at net.osmand.router.GeneralRouter$RouteAttributeExpression.calculateExprValue(GeneralRouter.java:630)
	at net.osmand.router.GeneralRouter$RouteAttributeExpression.matches(GeneralRouter.java:604)
	at net.osmand.router.GeneralRouter$RouteAttributeEvalRule.checkExpressions(GeneralRouter.java:820)
	at net.osmand.router.GeneralRouter$RouteAttributeEvalRule.matches(GeneralRouter.java:812)
	at net.osmand.router.GeneralRouter$RouteAttributeEvalRule.eval(GeneralRouter.java:771)
	at net.osmand.router.GeneralRouter$RouteAttributeContext.evaluate(GeneralRouter.java:495)
	at net.osmand.router.GeneralRouter$RouteAttributeContext.evaluate(GeneralRouter.java:472)
	at net.osmand.router.GeneralRouter$RouteAttributeContext.evaluateInt(GeneralRouter.java:523)
	at net.osmand.router.GeneralRouter.acceptLine(GeneralRouter.java:186)
	at net.osmand.router.RoutingContext.loadSubregionTile(RoutingContext.java:325)
	at net.osmand.router.RoutingContext.getRoutingTile(RoutingContext.java:523)
	at net.osmand.router.RoutingContext.loadTileData(RoutingContext.java:459)
	at net.osmand.router.RoutePlannerFrontEnd.findRouteSegment(RoutePlannerFrontEnd.java:62)
	at net.osmand.binary.GeocodingUtilities.reverseGeocodingSearch(GeocodingUtilities.java:164)
	at net.osmand.plus.CurrentPositionHelper.runUpdateInThread(CurrentPositionHelper.java:220)
	at net.osmand.plus.CurrentPositionHelper.processGeocoding(CurrentPositionHelper.java:87)
	at net.osmand.plus.CurrentPositionHelper.access$000(CurrentPositionHelper.java:26)
	at net.osmand.plus.CurrentPositionHelper$1.doInBackground(CurrentPositionHelper.java:72)
	at net.osmand.plus.CurrentPositionHelper$1.doInBackground(CurrentPositionHelper.java:67)
	at android.os.AsyncTask$2.call(AsyncTask.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
```

**Comment by crimean** [comment]
@scaidermern Please try latest nightly build

**Comment by scaidermern** [comment]
@crimean Thanks, I will. Not sure how to reproduce this crash, though (well, hopefully it can't be reproduced any more ;)).
