### ISSUE TITLE
Sometimes fails to load native library

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#2563]
I see a strange thing with osmand: sometimes I open it and everything perfectly works and sometimes I open it and it fails to load the native library (then I close and open again, and it works).

In logcat I can see:

```
05-18 08:41:12.996 26770 26801 E OsmAndCore:Android/NativeCore: Failed to load 'Qt5Core'
05-18 08:41:12.996 26770 26801 E OsmAndCore:Android/NativeCore: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/net.osmand.dev-1/base.apk"],nativeLibraryDirectories=[/data/app/net.osmand.dev-1/lib/arm, /data/app/net.osmand.dev-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libQt5Core.so"
05-18 08:41:12.996 26770 26801 E OsmAndCore:Android/NativeCore: 	at java.lang.Runtime.loadLibrary(Runtime.java:367)
05-18 08:41:12.996 26770 26801 E OsmAndCore:Android/NativeCore: 	at java.lang.System.loadLibrary(System.java:1076)
05-18 08:41:12.996 26770 26801 E OsmAndCore:Android/NativeCore: 	at net.osmand.core.android.NativeCore.loadNativeLibrary(NativeCore.java:25)
05-18 08:41:12.996 26770 26801 E OsmAndCore:Android/NativeCore: 	at net.osmand.core.android.NativeCore.<clinit>(NativeCore.java:43)
05-18 08:41:12.996 26770 26801 E OsmAndCore:Android/NativeCore: 	at net.osmand.plus.views.corenative.NativeCoreContext.init(NativeCoreContext.java:48)
05-18 08:41:12.996 26770 26801 E OsmAndCore:Android/NativeCore: 	at net.osmand.plus.views.corenative.NativeCoreContext.tryCatchInit(NativeCoreContext.java:37)
05-18 08:41:12.996 26770 26801 E OsmAndCore:Android/NativeCore: 	at net.osmand.plus.AppInitializer.initNativeCore(AppInitializer.java:591)
05-18 08:41:12.996 26770 26801 E OsmAndCore:Android/NativeCore: 	at net.osmand.plus.AppInitializer.startApplicationBackground(AppInitializer.java:488)
05-18 08:41:12.996 26770 26801 E OsmAndCore:Android/NativeCore: 	at net.osmand.plus.AppInitializer.access$200(AppInitializer.java:69)
05-18 08:41:12.996 26770 26801 E OsmAndCore:Android/NativeCore: 	at net.osmand.plus.AppInitializer$9.run(AppInitializer.java:729)
05-18 08:41:12.996 26770 26801 E OsmAndCore:Android/NativeCore: 	at java.lang.Thread.run(Thread.java:818)
```

Maybe there is a race condition somewhere, causing this problem randomly when starting it?
My current version is 2.4.0#12810D, but there is a good time that I see this problem happening.

**Comment by vshcherb** [comment]
This is expected failure for builds without qt5.
