### ISSUE TITLE
Sometimes fails to render the map

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#2564]
Sometimes I am scrolling the map and I see a message saying that it failed to render the map.
In logcat there is:

```
05-18 08:47:58.229 26770 26799 E net.osmand: MapRenderRepositories Runtime memory exception
05-18 08:47:58.229 26770 26799 E net.osmand: java.lang.NullPointerException: Attempt to read from field 'double net.osmand.data.QuadRect.left' on a null object reference
05-18 08:47:58.229 26770 26799 E net.osmand: 	at net.osmand.plus.render.MapRenderRepositories.loadMap(MapRenderRepositories.java:662)
05-18 08:47:58.229 26770 26799 E net.osmand: 	at net.osmand.plus.resources.AsyncLoadingThread.run(AsyncLoadingThread.java:109)
```

Version is 2.4.0#12810D

**Comment by vshcherb** [comment]
Thanks, interesting case.

**Comment by sonora** [comment]
Deprecated or not?

**Comment by naoliv** [comment]
Sometimes I still see a message that it failed to render the map, even with the latest version.

**Comment by sonora** [comment]
Any more details on that? Is this a device with little memory, when lots of POIs are displayed at the same time, etc.? Thx!

**Comment by naoliv** [comment]
It has 1GB of RAM
And it always happens when opening osmand (when it starts to render the map), even on areas with a few objects.
The problem is that when it happens I am usually at the car or walking.
I need to see if I can reproduce it when I am close to the computer, to see if the logcat error is still the same.
