### ISSUE TITLE
NPE while creating maps with map creator

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#2602]
It seems to be happening for around 4 days already:

```
java.lang.NullPointerException
        at net.osmand.data.preparation.OsmDbCreator.convertId(OsmDbCreator.java:132)
        at net.osmand.data.preparation.OsmDbCreator.acceptEntityToLoad(OsmDbCreator.java:348)
        at net.osmand.osm.io.OsmBaseStorage.acceptEntityToLoad(OsmBaseStorage.java:300)
        at net.osmand.osm.io.OsmBaseStoragePbf$1.registerEntity(OsmBaseStoragePbf.java:43)
        at net.osmand.osm.io.OsmBaseStoragePbf$1.parseRelations(OsmBaseStoragePbf.java:170)
        at crosby.binary.BinaryParser.parse(BinaryParser.java:105)
        at crosby.binary.BinaryParser.handleBlock(BinaryParser.java:51)
        at crosby.binary.file.FileBlock.process(FileBlock.java:120)
        at crosby.binary.file.BlockInputStream.process(BlockInputStream.java:15)
        at net.osmand.osm.io.OsmBaseStoragePbf.parseOSMPbf(OsmBaseStoragePbf.java:214)
        at net.osmand.data.preparation.IndexCreator.extractOsmToNodesDB(IndexCreator.java:337)
        at net.osmand.data.preparation.IndexCreator.initDbAccessor(IndexCreator.java:426)
        at net.osmand.data.preparation.IndexCreator.generateIndexes(IndexCreator.java:661)
        at net.osmand.data.preparation.IndexCreator.generateIndexes(IndexCreator.java:589)
        at net.osmand.data.index.IndexBatchCreator.generateIndex(IndexBatchCreator.java:552)
        at net.osmand.data.index.IndexBatchCreator.generatedIndexes(IndexBatchCreator.java:464)
        at net.osmand.data.index.IndexBatchCreator.runBatch(IndexBatchCreator.java:307)
        at net.osmand.data.index.IndexBatchCreator.main(IndexBatchCreator.java:165)
```

**Comment by xmd5a2** [comment]
I expect these NPE too. For example at this xml:
https://dl.dropboxusercontent.com/u/4624786/osm/spoil_heap_test.zip

**Comment by rominf** [comment]
I reproduced the bug with @xmd5a2's xml and fixed it in https://github.com/osmandapp/OsmAnd-tools/commit/6c9be9053cad930ccfa108cd1313e9a2c809b2c0
@naoliv, @xmd5a2, can you verify?

**Comment by vshcherb** [comment]
Which map is failing?
