### ISSUE TITLE
Crash at net.osmand.plus.base.BaseOsmAndFragment.getMyApplication()

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#2615]
Nightly crashed during startup:

```
Version  OsmAndF~ 2.4.0#13034D
29.05.2016 9:34:28
Apk Version : 2.4.0#13034D 231
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Application android.support.v4.app.FragmentActivity.getApplication()' on a null object reference
    at net.osmand.plus.base.BaseOsmAndFragment.getMyApplication(BaseOsmAndFragment.java:21)
    at net.osmand.plus.download.ui.LocalIndexesFragment.access$1000(LocalIndexesFragment.java:78)
    at net.osmand.plus.download.ui.LocalIndexesFragment$LocalIndexesAdapter.addLocalIndexInfo(LocalIndexesFragment.java:911)
    at net.osmand.plus.download.ui.LocalIndexesFragment$LoadLocalIndexTask.onProgressUpdate(LocalIndexesFragment.java:343)
    at net.osmand.plus.download.ui.LocalIndexesFragment$LoadLocalIndexTask.onProgressUpdate(LocalIndexesFragment.java:318)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:656)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5294)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by vshcherb** [comment]
Does it happen during startup? It might be during when you enter Manage Map files screen.

**Comment by scaidermern** [comment]
Yes, I think that's what I did while the map was still loading.

**Comment by postadelmaga** [comment]
+1 I have 5 / 6 exception like this in my exception.log file

```
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Application android.support.v4.app.FragmentActivity.getApplication()' on a null object reference
	at net.osmand.plus.base.BaseOsmAndFragment.getMyApplication(BaseOsmAndFragment.java:21)
	at net.osmand.plus.download.ui.LocalIndexesFragment.access$1000(LocalIndexesFragment.java:78)
	at net.osmand.plus.download.ui.LocalIndexesFragment$LocalIndexesAdapter.addLocalIndexInfo(LocalIndexesFragment.java:910)
	at net.osmand.plus.download.ui.LocalIndexesFragment$LoadLocalIndexTask.onProgressUpdate(LocalIndexesFragment.java:342)
	at net.osmand.plus.download.ui.LocalIndexesFragment$LoadLocalIndexTask.onProgressUpdate(LocalIndexesFragment.java:317)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:656)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5290)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
```

The download action is always been very slow and inconsistent on all my phones and in all the OsmAnd versions and I think this exception maybe related.

When I start to download a map, the speed is very slow and if I switch to another application and then come back to OsmAnd the download is not shown anymore in the "Manage map files" views ( but sometime it is still shown in the notifications of the phone but look frozen )
