### ISSUE TITLE
MapCreator: "IllegalArgumentException: Invalid number of points in LinearRing"

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#2685]
While generating some maps I am seeing this:

```
jun 12, 2016 2:12:04 AM net.osmand.data.preparation.IndexCreator generateIndexes
GRAVE: Log exception
java.lang.IllegalArgumentException: Invalid number of points in LinearRing (found 3 - must be 0 or >= 4)
        at com.vividsolutions.jts.geom.LinearRing.validateConstruction(LinearRing.java:114)
        at com.vividsolutions.jts.geom.LinearRing.<init>(LinearRing.java:106)
        at com.vividsolutions.jts.geom.GeometryFactory.createLinearRing(GeometryFactory.java:355)
        at com.vividsolutions.jts.geom.GeometryFactory.createLinearRing(GeometryFactory.java:342)
        at net.osmand.data.Ring.toLinearRing(Ring.java:219)
        at net.osmand.data.Multipolygon.toMultiPolygon(Multipolygon.java:57)
        at net.osmand.data.preparation.address.IndexAddressCreator.postcodesInCityBoundary(IndexAddressCreator.java:982)
        at net.osmand.data.preparation.address.IndexAddressCreator.writeCityBlockIndex(IndexAddressCreator.java:1221)
        at net.osmand.data.preparation.address.IndexAddressCreator.writeBinaryAddressIndex(IndexAddressCreator.java:1095)
        at net.osmand.data.preparation.IndexCreator.generateIndexes(IndexCreator.java:731)
        at net.osmand.data.preparation.IndexCreator.generateIndexes(IndexCreator.java:578)
        at net.osmand.data.index.IndexBatchCreator.generateIndex(IndexBatchCreator.java:552)
        at net.osmand.data.index.IndexBatchCreator.generatedIndexes(IndexBatchCreator.java:464)
        at net.osmand.data.index.IndexBatchCreator.runBatch(IndexBatchCreator.java:307)
        at net.osmand.data.index.IndexBatchCreator.main(IndexBatchCreator.java:165)
```

MapCreator is the latest version, but it seems to be happening for, at least, ~3 days.

**Comment by rominf** [comment]
@naoliv. Can you please provide `.osm` file of map, causing this exception?

**Comment by rominf** [comment]
@naoliv, never mind, I reproduced issue.

**Comment by naoliv** [comment]
All of these 4 maps are having this problem: http://naoliv.iq.unesp.br/osm/osmand-2685/

**Comment by naoliv** [comment]
Hum... taking a look at their size I guess the problem is not with osmand, but with the splitter. Their size is much smaller than they should be. I will verify this.

**Comment by naoliv** [comment]
Regenerated without any problem these extracts.
I am unsure if there is a silent problem with cutting the extracts or it they are indeed right (and thus the problem is in MapCreator).

**Comment by rominf** [comment]
It shows 403 error on file download attempts.

**Comment by naoliv** [comment]
Sorry for the wrong permissions.
They are fixed now.

**Comment by rominf** [comment]
Thank you. I confirm this exception with your files.
Can you please provide `.osm` files? My JOSM don't wont to open them. I tried to open them with pbf plugin, convert them via `osmconvert` — nothing helps.

**Comment by naoliv** [comment]
Plain `.osm` files are now available at the same place.
Thanks!

**Comment by rominf** [comment]
Fixed in https://github.com/osmandapp/OsmAnd-tools/commit/2c0ed115badb5d9e803d4fb4aef199ac06cc3f1a
BTW, bugs related to map generation is better to fill in Osmand-tools repository.
