### ISSUE TITLE
Crash on OSM notice opening

### ISSUE THREAD

**Issue by Dominik-K** [osmandapp/Osmand#2752]
Hi,

I wanted to open an OSM notice, but it didn't work. I touched the icon many times because it doesn't show up, but then the app crashed with the following exception.

OsmAnd~ 2.3.5, Android 4.2.2 (Fairphone 1), with offline map of Niedersachsen, Germany (01.05.2016).

Version  OsmAnd~ 2.3.5
28.06.2016 7:49:25
Apk Version : 2.3.5 238
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalStateException: Activity has been destroyed
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1511)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:634)
	at android.support.v4.app.BackStackRecord.commitAllowingStateLoss(BackStackRecord.java:617)
	at net.osmand.plus.mapcontextmenu.other.MapMultiSelectionMenuFragment.showInstance(MapMultiSelectionMenuFragment.java:109)
	at net.osmand.plus.mapcontextmenu.other.MapMultiSelectionMenu.show(MapMultiSelectionMenu.java:166)
	at net.osmand.plus.views.ContextMenuLayer.showContextMenuForSelectedObjects(ContextMenuLayer.java:323)
	at net.osmand.plus.views.ContextMenuLayer.showContextMenu(ContextMenuLayer.java:190)
	at net.osmand.plus.views.ContextMenuLayer.onSingleTap(ContextMenuLayer.java:305)
	at net.osmand.plus.views.OsmandMapTileView$MapTileViewOnGestureListener.onSingleTapConfirmed(OsmandMapTileView.java:1089)
	at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:271)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:153)
	at android.app.ActivityThread.main(ActivityThread.java:5299)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by DaMonk45** [comment]
I have the same issue. 
I get to the point where it says graph hopper then message the Locus has stoped working
I sent my logs. If you need more info let me know.

Dave

**Comment by crimean** [comment]
@Dominik-K can you repeat this bug?
