### ISSUE TITLE
Menu > My Places > Share doesn't do anything

### ISSUE THREAD

**Issue by bjohas** [osmandapp/Osmand#2799]
Unless I misunderstand the feature, selecting Menu > My Places and then tapping the share button doesn't do anything. (Latest nightly 8th July, though has been like that for at least a few nightlies.)

**Comment by sonora** [comment]
Confirmed, I think there is an issue here. From what I remember, you should see a popup dialog just like when you tap "Share" on an individual favorite (where it works), only here you would probably share your entire favourite.gpx file.

**Comment by homersimpsons** [comment]
There is no bug for me in Osmand~ 2.3.5

**Comment by bjohas** [comment]
Thanks for confirming, so it only affects the current nightlies, e.g. 2.4.0#4149M_2.3.

**Comment by sonora** [comment]
I found this in my error logs, looks like it may refer to this:
```
25.07.2016 1:55:07
Apk Version : 2.4.0#17634M 231
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException
	at net.osmand.plus.activities.FavoritesTreeFragment.hideProgressBar(FavoritesTreeFragment.java:291)
	at net.osmand.plus.activities.FavoritesTreeFragment$10.onPostExecute(FavoritesTreeFragment.java:489)
	at net.osmand.plus.activities.FavoritesTreeFragment$10.onPostExecute(FavoritesTreeFragment.java:476)
	at android.os.AsyncTask.finish(AsyncTask.java:632)
	at android.os.AsyncTask.access$600(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5593)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)

```

**Comment by vshcherb** [comment]
Didn't reproduce with latest but I put an additional check to avoid exception

**Comment by bjohas** [comment]
In v. 4802, the issue is still there (at least for me).
