### ISSUE TITLE
Sample Application crashes on android

### ISSUE THREAD

**Issue by DhavalsShah** [osmandapp/Osmand#2853]
After installing an app in to device sample android app crashes. and I got following error in logcat. How to fix this one? I have tested on 5.0,5.1 and 6.0. I am getting same result(i.e app crashes.)

MapRenderingTypes Unexpected error
java.io.FileNotFoundException: /storage/emulated/0/osmand/poi_types.xml: open failed: ENOENT (No such file or directory)
at libcore.io.IoBridge.open(IoBridge.java:452)
at java.io.FileInputStream.(FileInputStream.java:76)
at java.io.FileInputStream.(FileInputStream.java:103)
at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:267)
at net.osmand.core.samples.android.sample1.SampleApplication.initPoiTypes(SampleApplication.java:55)
at net.osmand.core.samples.android.sample1.SampleApplication.onCreate(SampleApplication.java:32)
at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:369)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4712)
at android.app.ActivityThread.-wrap1(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5422)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
at libcore.io.Posix.open(Native Method)
at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
at libcore.io.IoBridge.open(IoBridge.java:438)
at java.io.FileInputStream.(FileInputStream.java:76) 
at java.io.FileInputStream.(FileInputStream.java:103) 
at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:267) 
at net.osmand.core.samples.android.sample1.SampleApplication.initPoiTypes(SampleApplication.java:55) 
at net.osmand.core.samples.android.sample1.SampleApplication.onCreate(SampleApplication.java:32) 
at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:369) 
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013) 
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4712) 
at android.app.ActivityThread.-wrap1(ActivityThread.java) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:148) 
at android.app.ActivityThread.main(ActivityThread.java:5422) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by vshcherb** [comment]
Duplicate
