### ISSUE TITLE
Reproducable OsmAnd crashes on car head unit.

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#2876]
The apps both nightly and OsmAnd+ 2.3.5 work well on other devices but crash repeatedly on car head unit.
Crash info: 
Device : rk3188 
Brand : rockchip 
Model : CarPad-III-P 
Product : rk3188 
Build : rk3188-eng 4.4.2 KOT49H eng.gypeng.20160628.183203 test-keys 
Version : 4.4.2 
App Version : OsmAnd~ 
Apk Version : 2.4.0#17678M 240

Exception log:

Version  OsmAnd~ 2.4.0#17678M
26.07.2016 11:29:49
Apk Version : 2.4.0#17678M 240
Exception occured in thread Thread[Initializing app,5,main] : 
java.lang.NoSuchMethodError: com.google.protobuf.CodedInputStream.newInstance
	at net.osmand.binary.BinaryMapIndexReader.<init>(BinaryMapIndexReader.java:124)
	at net.osmand.map.OsmandRegions.prepareFile(OsmandRegions.java:96)
	at net.osmand.plus.AppInitializer.indexRegionsBoundaries(AppInitializer.java:291)
	at net.osmand.plus.AppInitializer.startApplicationBackground(AppInitializer.java:494)
	at net.osmand.plus.AppInitializer.access$200(AppInitializer.java:69)
	at net.osmand.plus.AppInitializer$9.run(AppInitializer.java:729)
	at java.lang.Thread.run(Thread.java:841)
Version  OsmAnd~ 2.4.0#17678M
26.07.2016 11:29:49
Apk Version : 2.4.0#17678M 240
Exception occured in thread Thread[Initializing app,5,main] : 
java.lang.NoSuchMethodError: com.google.protobuf.CodedInputStream.newInstance
	at net.osmand.binary.BinaryMapIndexReader.<init>(BinaryMapIndexReader.java:124)
	at net.osmand.map.OsmandRegions.prepareFile(OsmandRegions.java:96)
	at net.osmand.plus.AppInitializer.indexRegionsBoundaries(AppInitializer.java:291)
	at net.osmand.plus.AppInitializer.startApplicationBackground(AppInitializer.java:494)
	at net.osmand.plus.AppInitializer.access$200(AppInitializer.java:69)
	at net.osmand.plus.AppInitializer$9.run(AppInitializer.java:729)
	at java.lang.Thread.run(Thread.java:841)
Version  OsmAnd~ 2.4.0#17678M
26.07.2016 11:29:59
Apk Version : 2.4.0#17678M 240
Exception occured in thread Thread[Initializing app,5,main] : 
java.lang.NoSuchMethodError: com.google.protobuf.CodedInputStream.newInstance
	at net.osmand.binary.BinaryMapIndexReader.<init>(BinaryMapIndexReader.java:124)
	at net.osmand.map.OsmandRegions.prepareFile(OsmandRegions.java:96)
	at net.osmand.plus.AppInitializer.indexRegionsBoundaries(AppInitializer.java:291)
	at net.osmand.plus.AppInitializer.startApplicationBackground(AppInitializer.java:494)
	at net.osmand.plus.AppInitializer.access$200(AppInitializer.java:69)
	at net.osmand.plus.AppInitializer$9.run(AppInitializer.java:729)
	at java.lang.Thread.run(Thread.java:841)
Version  OsmAnd~ 2.4.0#17678M
26.07.2016 11:29:59
Apk Version : 2.4.0#17678M 240
Exception occured in thread Thread[Initializing app,5,main] : 
java.lang.NoSuchMethodError: com.google.protobuf.CodedInputStream.newInstance
	at net.osmand.binary.BinaryMapIndexReader.<init>(BinaryMapIndexReader.java:124)
	at net.osmand.map.OsmandRegions.prepareFile(OsmandRegions.java:96)
	at net.osmand.plus.AppInitializer.indexRegionsBoundaries(AppInitializer.java:291)
	at net.osmand.plus.AppInitializer.startApplicationBackground(AppInitializer.java:494)
	at net.osmand.plus.AppInitializer.access$200(AppInitializer.java:69)
	at net.osmand.plus.AppInitializer$9.run(AppInitializer.java:729)
	at java.lang.Thread.run(Thread.java:841)
Version  OsmAnd~ 2.4.0#17678M
26.07.2016 11:30:10
Apk Version : 2.4.0#17678M 240
Exception occured in thread Thread[Initializing app,5,main] : 
java.lang.NoSuchMethodError: com.google.protobuf.CodedInputStream.newInstance
	at net.osmand.binary.BinaryMapIndexReader.<init>(BinaryMapIndexReader.java:124)
	at net.osmand.map.OsmandRegions.prepareFile(OsmandRegions.java:96)
	at net.osmand.plus.AppInitializer.indexRegionsBoundaries(AppInitializer.java:291)
	at net.osmand.plus.AppInitializer.startApplicationBackground(AppInitializer.java:494)
	at net.osmand.plus.AppInitializer.access$200(AppInitializer.java:69)
	at net.osmand.plus.AppInitializer$9.run(AppInitializer.java:729)
	at java.lang.Thread.run(Thread.java:841)
Version  OsmAnd~ 2.4.0#17678M
26.07.2016 11:30:10
Apk Version : 2.4.0#17678M 240
Exception occured in thread Thread[Initializing app,5,main] : 
java.lang.NoSuchMethodError: com.google.protobuf.CodedInputStream.newInstance
	at net.osmand.binary.BinaryMapIndexReader.<init>(BinaryMapIndexReader.java:124)
	at net.osmand.map.OsmandRegions.prepareFile(OsmandRegions.java:96)
	at net.osmand.plus.AppInitializer.indexRegionsBoundaries(AppInitializer.java:291)
	at net.osmand.plus.AppInitializer.startApplicationBackground(AppInitializer.java:494)
	at net.osmand.plus.AppInitializer.access$200(AppInitializer.java:69)
	at net.osmand.plus.AppInitializer$9.run(AppInitializer.java:729)
	at java.lang.Thread.run(Thread.java:841)
Version  OsmAnd~ 2.4.0#17678M
26.07.2016 11:30:22
Apk Version : 2.4.0#17678M 240
Exception occured in thread Thread[Initializing app,5,main] : 
java.lang.NoSuchMethodError: com.google.protobuf.CodedInputStream.newInstance
	at net.osmand.binary.BinaryMapIndexReader.<init>(BinaryMapIndexReader.java:124)
	at net.osmand.map.OsmandRegions.prepareFile(OsmandRegions.java:96)
	at net.osmand.plus.AppInitializer.indexRegionsBoundaries(AppInitializer.java:291)
	at net.osmand.plus.AppInitializer.startApplicationBackground(AppInitializer.java:494)
	at net.osmand.plus.AppInitializer.access$200(AppInitializer.java:69)
	at net.osmand.plus.AppInitializer$9.run(AppInitializer.java:729)
	at java.lang.Thread.run(Thread.java:841)
Version  OsmAnd~ 2.4.0#17678M
26.07.2016 11:30:22
Apk Version : 2.4.0#17678M 240
Exception occured in thread Thread[Initializing app,5,main] : 
java.lang.NoSuchMethodError: com.google.protobuf.CodedInputStream.newInstance
	at net.osmand.binary.BinaryMapIndexReader.<init>(BinaryMapIndexReader.java:124)
	at net.osmand.map.OsmandRegions.prepareFile(OsmandRegions.java:96)
	at net.osmand.plus.AppInitializer.indexRegionsBoundaries(AppInitializer.java:291)
	at net.osmand.plus.AppInitializer.startApplicationBackground(AppInitializer.java:494)
	at net.osmand.plus.AppInitializer.access$200(AppInitializer.java:69)
	at net.osmand.plus.AppInitializer$9.run(AppInitializer.java:729)
	at java.lang.Thread.run(Thread.java:841)

**Comment by vshcherb** [comment]
Not sure how much we can help here
