### ISSUE TITLE
Sometimes dies during navigation

### ISSUE THREAD

**Issue by agilob** [osmandapp/OsmAnd#2899]
Hi guys, at the beginning I have to say this is the best issue template I've seen so far, good job on this.

My problem is that OsmAnd~ (from Fdroid) sometimes dies during navigation, when OsmAnd is in foreground.
Application just turns off, navigation is dead and I have to restart it, then I'm asked if I want to resume previous navigation. 
I didn't want to report it without log, so I was waiting for it to happen. Today it crashed again, and after restart it showed me popup `Send report`, which has never happened before.

Please give us the following information so that we can try to **reproduce** your issue:
Hard to say, I can't see any pattern when it crashes... Next time I use it I will turn on logging on logcat with filter for OsmAnd

What version of OsmAnd are you using, on what device and Android/iOS version?
- Android 4.1 branded from LG
- OsmAnd~ from Fdroid, version 2.3.5

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?
- Offline maps England and Wales
- Car navigation, non-default settings, don't think that matters, hide houses and borders, avoid motorways
- Enabled plugin: record GPS track automatically + continuous.

I tried to send report by email, but Fdroid crashes when doing it :D so I found exception.log in osmand folder (SD card), its content:

```
Version  OsmAnd~ 2.3.5
04.08.2016 7:59:26
Apk Version : 2.3.5 238
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalArgumentException: View not attached to window manager
    at android.view.WindowManagerImpl.findViewLocked(WindowManagerImpl.java:671)
    at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:364)
    at android.view.WindowManagerImpl$CompatModeWrapper.removeView(WindowManagerImpl.java:163)
    at android.app.Dialog.dismissDialog(Dialog.java:347)
    at android.app.Dialog.dismiss(Dialog.java:330)
    at android.app.Dialog.cancel(Dialog.java:1132)
    at android.app.Dialog.onTouchEvent(Dialog.java:645)
    at android.app.Dialog.dispatchTouchEvent(Dialog.java:767)
    at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2157)
    at android.view.View.dispatchPointerEvent(View.java:7331)
    at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3205)
    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3150)
    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4186)
    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4165)
    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4257)
    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:171)
    at android.os.MessageQueue.nativePollOnce(Native Method)
    at android.os.MessageQueue.next(MessageQueue.java:125)
    at android.os.Looper.loop(Looper.java:140)
    at android.app.ActivityThread.main(ActivityThread.java:5071)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)
```

Just to add a "proof" where the red line ends, OsmAnd crashes and stopped logging track:
![screenshot_2016-08-04-08-26-59](https://cloud.githubusercontent.com/assets/2544251/17393762/9643fbc0-5a1d-11e6-8488-c0710ade6e19.png)

Let me know if I can provide you any more info.

**Comment by bjohas** [comment]
I've had the same issue.

**Comment by agilob** [comment]
To add more info, it dies when using standard offline navigation service and with online YOURS.

**Comment by vshcherb** [comment]
We've seen that issue many times for years, though we never managed to trace information. With confidence of 90% it is related to out of memory issue. We've recently fixed memory leak in 2.4, so it will possibly help that issue.

**Comment by agilob** [comment]
Hmm I use Cracker from Xposed to catch Throwables that kill apps. One of my apps was vulnerable to out of memory and Cracker was catching those exceptions and provided me strack trace for them. I take take memory measures for you. Sometimes it dies after 5minutes, sometimes after over an hour.

**Comment by agilob** [comment]
I used OsmAnd 2.4.5 in last two days 4 times on ~20minutes trips and it didn't crash :)

**Comment by polarbearing** [comment]
see also #2870

**Comment by agilob** [comment]
I saw it, but for me it was crashing in Wales, on empty roads.
