### ISSUE TITLE
Crash when changing device orientation in "Screen orientation" menu

### ISSUE THREAD

**Issue by agilob** [osmandapp/Osmand#2900]
1. Select "Landscape" screen orientation
2. Go to General settings -> "Screen orientation"
3. When you see the menu with 3 options, rotate device

OsmAnd 2.3.5 from Fdroid, Android 4.1

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.osmand.plus/net.osmand.plus.activities.SettingsGeneralActivity}: java.lang.IllegalStateException: ListPreference requires an entries array and an entryValues array.
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2198)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2225)
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3735)
    at android.app.ActivityThread.access$700(ActivityThread.java:151)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1307)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:153)
    at android.app.ActivityThread.main(ActivityThread.java:5071)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalStateException: ListPreference requires an entries array and an entryValues array.
    at android.preference.ListPreference.onPrepareDialogBuilder(ListPreference.java:232)
    at android.preference.DialogPreference.showDialog(DialogPreference.java:295)
    at android.preference.DialogPreference.onRestoreInstanceState(DialogPreference.java:441)
    at android.preference.ListPreference.onRestoreInstanceState(ListPreference.java:298)
    at android.preference.Preference.dispatchRestoreInstanceState(Preference.java:1778)
    at android.preference.PreferenceGroup.dispatchRestoreInstanceState(PreferenceGroup.java:327)
    at android.preference.Preference.restoreHierarchyState(Preference.java:1760)
    at android.preference.PreferenceActivity.onRestoreInstanceState(PreferenceActivity.java:936)
    at android.app.Activity.performRestoreInstanceState(Activity.java:1063)
    at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1133)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2176)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2225)
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3735)
    at android.app.ActivityThread.access$700(ActivityThread.java:151)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1307)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:153)
    at android.app.ActivityThread.main(ActivityThread.java:5071)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)

```

**Comment by sonora** [comment]
Yes, I can reproduce this.

**Comment by Chumva** [comment]
This should be fixed in new settings screens.
