### ISSUE TITLE
OutOfMemory during map update

### ISSUE THREAD

**Issue by agilob** [osmandapp/Osmand#2965]
Happened when I was in Updates tab in Manage map files.

```
java.lang.OutOfMemoryError: java.util.HashMap$HashMapEntry[] of length 1073741824 exceeds the VM limit
    at java.util.HashMap.makeTable(HashMap.java:555)
    at java.util.HashMap.ensureCapacity(HashMap.java:534)
    at java.util.HashMap.putAll(HashMap.java:507)
    at android.os.Bundle.putAll(Bundle.java:304)
    at android.support.v4.app.NotificationCompatJellybean$Builder.build(NotificationCompatJellybean.java:143)
    at android.support.v7.app.NotificationCompat$JellybeanExtender.build(NotificationCompat.java:111)
    at android.support.v4.app.NotificationCompat$NotificationCompatImplJellybean.build(NotificationCompat.java:600)
    at android.support.v4.app.NotificationCompat$Builder.build(NotificationCompat.java:1561)
    at net.osmand.plus.download.DownloadIndexesThread.updateNotification(DownloadIndexesThread.java:132)
    at net.osmand.plus.download.DownloadIndexesThread.downloadInProgress(DownloadIndexesThread.java:102)
    at net.osmand.plus.download.DownloadIndexesThread$DownloadIndexesAsyncTask.updateProgress(DownloadIndexesThread.java:604)
    at net.osmand.plus.download.DownloadIndexesThread$DownloadIndexesAsyncTask.updateProgress(DownloadIndexesThread.java:367)
    at net.osmand.plus.base.BasicProgressAsyncTask$1.run(BasicProgressAsyncTask.java:80)
    at android.os.Handler.handleCallback(Handler.java:615)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:153)
    at android.app.ActivityThread.main(ActivityThread.java:5071)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by sonora** [comment]
Not reproducible any more?
