### ISSUE TITLE
House numbers are not found when they are marked with an 'associatedStreet' relation (role: 'house')

### ISSUE THREAD

**Issue by honggoff** [osmandapp/Osmand#3064]
In Zürich, a lot of house numbers are mapped as points and have an association of type 'associatedStreet'. The role in the association is 'house'. These are not found in OsmAnd.

From how I understand the OSM Wiki, these house numbers are mapped correctly, however OsmAnd does not show them in either the traditional or the quick search.

Example node that cannot be found: https://www.openstreetmap.org/node/1235083838#map=19/47.37952/8.52635
The node should create an entry for Zinistrasse 8, Zürich, Switzerland.
OsmAnd version: 2.4.6 on Android 6.0.1
Map source: Offline vector maps for Switzerland

**Comment by honggoff** [comment]
After some digging around, I realize the bug might be in OsmAndMapCreator. I'm still struggling with building that from source to work on a fix.

**Comment by vshcherb** [comment]
It should be pretty easy to build if you have Ant and proper folder structrure (ant -file build.xml -Dbuild.version=#16855MC clean compile build)

**Comment by vshcherb** [comment]
That was probably temporarily glitch with maps, just tested and all 6 houses are displayed with today generated map

**Comment by vshcherb** [comment]
i.e. Zinistrasse (Langstrasse) 8 and so on

**Comment by honggoff** [comment]
I used repo and the commit.xml manifest to check out the source, I hope this created the proper folder structure.
I now managed to build the jar file for OsmAndMapCreator. When runnig it however, I get the errors below. From what I can tell it is a GUI program, so it's not a matter of wrong command line parameters.

Is this the program that is used by OSM to create its map files or am I looking it the wrong place?

```
Sep 16, 2016 10:20:23 AM net.osmand.osm.MapPoiTypes init
INFO: Time to init poi types 613
Sep 16, 2016 10:20:26 AM net.osmand.binary.BinaryMapIndexReader searchMapIndex
INFO: Search is done. Visit 2234 objects. Read 2234 objects.
Sep 16, 2016 10:20:26 AM net.osmand.binary.BinaryMapIndexReader searchMapIndex
INFO: Read 59 subtrees. Go through 115 subtrees.
Sep 16, 2016 10:20:27 AM net.osmand.swing.ExceptionHandler handle
SEVERE: Error in thread main
com.google.protobuf.UninitializedMessageException: Message was missing required fields.  (Lite runtime could not determine which fields were missing).
        at com.google.protobuf.AbstractMessageLite$Builder.newUninitializedMessageException(AbstractMessageLite.java:306)
        at net.osmand.binary.OsmandIndex$OsmAndStoredIndex$Builder.build(OsmandIndex.java:215)
        at net.osmand.binary.CachedOsmandIndexes.readFromFile(CachedOsmandIndexes.java:311)
        at net.osmand.swing.OsmExtractionUI.createUI(OsmExtractionUI.java:213)
        at net.osmand.swing.OsmExtractionUI.<init>(OsmExtractionUI.java:167)
        at net.osmand.swing.OsmExtractionUI.main(OsmExtractionUI.java:129)

com.google.protobuf.UninitializedMessageException: Message was missing required fields.  (Lite runtime could not determine which fields were missing).
        at com.google.protobuf.AbstractMessageLite$Builder.newUninitializedMessageException(AbstractMessageLite.java:306)
        at net.osmand.binary.OsmandIndex$OsmAndStoredIndex$Builder.build(OsmandIndex.java:215)
        at net.osmand.binary.CachedOsmandIndexes.readFromFile(CachedOsmandIndexes.java:311)
        at net.osmand.swing.OsmExtractionUI.createUI(OsmExtractionUI.java:213)
        at net.osmand.swing.OsmExtractionUI.<init>(OsmExtractionUI.java:167)
        at net.osmand.swing.OsmExtractionUI.main(OsmExtractionUI.java:129)
```

**Comment by honggoff** [comment]
I only have the data from September 1st, so I cannot say if it has been fixed now.
However, the house numbers were always _displayed_, however they could not be _found in the search._

**Comment by vshcherb** [comment]
The maps were regenerated I just tested on Switzerland latest https://www.dropbox.com/s/uo7z7pio4y10s78/Screen%20Shot%202016-09-19%20at%2001.33.33.png?dl=0. The same search is used in text Android Search
