### ISSUE TITLE
OsmAnd crashes during search

### ISSUE THREAD

**Issue by verdulo** [osmandapp/Osmand#3211]
OsmAnd (on developer versions; 2.4.7 works fine) always crashes when I perform a search for 'Leisure' or 'Nearest POIs' nearby [this area](https://www.openstreetmap.org/#map=17/50.27659/19.01183).

Why the new search method searches around current location instead of around the map centre?

OsmAndF~ 2.5.0#15067D
28.10.2016 11:46:36
Apk Version : 2.5.0#15067D 240
Exception occured in thread Thread[main,5,main] : 
java.lang.ArrayIndexOutOfBoundsException: length=31; index=31
	at net.osmand.util.OpeningHoursParser.parseRuleV2(OpeningHoursParser.java:1090)
	at net.osmand.util.OpeningHoursParser.parseRule(OpeningHoursParser.java:1182)
	at net.osmand.util.OpeningHoursParser.parseOpenedHours(OpeningHoursParser.java:1428)
	at net.osmand.plus.search.QuickSearchListAdapter.getView(QuickSearchListAdapter.java:309)
	at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)
	at android.widget.AbsListView.obtainView(AbsListView.java:2045)
	at android.widget.ListView.makeAndAddView(ListView.java:1772)
	at android.widget.ListView.fillDown(ListView.java:672)
	at android.widget.ListView.fillSpecific(ListView.java:1330)
	at android.widget.ListView.layoutChildren(ListView.java:1603)
	at android.widget.AbsListView.onLayout(AbsListView.java:1875)
	at android.view.View.layout(View.java:11390)
	at android.view.ViewGroup.layout(ViewGroup.java:4332)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1653)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1511)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1416)
	at android.view.View.layout(View.java:11390)
	at android.view.ViewGroup.layout(ViewGroup.java:4332)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1653)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1511)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1416)
	at android.view.View.layout(View.java:11390)
	at android.view.ViewGroup.layout(ViewGroup.java:4332)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1653)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1511)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1416)
	at android.view.View.layout(View.java:11390)
	at android.view.ViewGroup.layout(ViewGroup.java:4332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:444)
	at android.view.View.layout(View.java:11390)
	at android.view.ViewGroup.layout(ViewGroup.java:4332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:444)
	at android.view.View.layout(View.java:11390)
	at android.view.ViewGroup.layout(ViewGroup.java:4332)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1653)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1511)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1416)
	at android.view.View.layout(View.java:11390)
	at android.view.ViewGroup.layout(ViewGroup.java:4332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:444)
	at android.view.View.layout(View.java:11390)
	at android.view.ViewGroup.layout(ViewGroup.java:4332)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1490)
	at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2455)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4424)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:817)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
	at dalvik.system.NativeStart.main(Native Method)
Version  OsmAndF~ 2.5.0#15067D
28.10.2016 11:46:36
Apk Version : 2.5.0#15067D 240
Exception occured in thread Thread[main,5,main] : 
java.lang.ArrayIndexOutOfBoundsException: length=31; index=31
	at net.osmand.util.OpeningHoursParser.parseRuleV2(OpeningHoursParser.java:1090)
	at net.osmand.util.OpeningHoursParser.parseRule(OpeningHoursParser.java:1182)
	at net.osmand.util.OpeningHoursParser.parseOpenedHours(OpeningHoursParser.java:1428)
	at net.osmand.plus.search.QuickSearchListAdapter.getView(QuickSearchListAdapter.java:309)
	at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)
	at android.widget.AbsListView.obtainView(AbsListView.java:2045)
	at android.widget.ListView.makeAndAddView(ListView.java:1772)
	at android.widget.ListView.fillDown(ListView.java:672)
	at android.widget.ListView.fillSpecific(ListView.java:1330)
	at android.widget.ListView.layoutChildren(ListView.java:1603)
	at android.widget.AbsListView.onLayout(AbsListView.java:1875)
	at android.view.View.layout(View.java:11390)
	at android.view.ViewGroup.layout(ViewGroup.java:4332)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1653)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1511)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1416)
	at android.view.View.layout(View.java:11390)
	at android.view.ViewGroup.layout(ViewGroup.java:4332)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1653)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1511)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1416)
	at android.view.View.layout(View.java:11390)
	at android.view.ViewGroup.layout(ViewGroup.java:4332)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1653)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1511)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1416)
	at android.view.View.layout(View.java:11390)
	at android.view.ViewGroup.layout(ViewGroup.java:4332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:444)
	at android.view.View.layout(View.java:11390)
	at android.view.ViewGroup.layout(ViewGroup.java:4332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:444)
	at android.view.View.layout(View.java:11390)
	at android.view.ViewGroup.layout(ViewGroup.java:4332)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1653)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1511)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1416)
	at android.view.View.layout(View.java:11390)
	at android.view.ViewGroup.layout(ViewGroup.java:4332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:444)
	at android.view.View.layout(View.java:11390)
	at android.view.ViewGroup.layout(ViewGroup.java:4332)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1490)
	at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2455)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4424)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:817)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by xmd5a2** [comment]
If you search far away from your location (~50km if I'm not wrong) it will search around map center

**Comment by vshcherb** [comment]
Fixed

**Comment by sonora** [comment]
Why would we have some arbitrary 50km trigger distance from your position and not always search from the map center?

**Comment by vshcherb** [comment]
For UX reasons, you can always search near map position if you use context menu -> search.
P.S. mostly we don't search around my location but we display distance from my location which is more clear.
