### ISSUE TITLE
OsmMapCreator crashes: java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by Carnildo** [osmandapp/Osmand#3212]
When trying to create a .obf file from a .osm, OsmMapCreator crashes with the following output:

```
java.lang.UnsatisfiedLinkError: /tmp/sqlite-3.8.7-5c15bb39-ae96-4cfc-822d-38598b2a23ea-libsqlitejdbc.so: /tmp/sqlite-3.8.7-5c15bb39-ae96-4cfc-822d-38598b2a23ea-libsqlitejdbc.so: failed to map segment from shared object
Oct 28, 2016 11:18:15 PM net.osmand.swing.ExceptionHandler handle
SEVERE: Error in thread Thread-3
java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open(Ljava/lang/String;I)V
    at org.sqlite.core.NativeDB._open(Native Method)
    at org.sqlite.core.DB.open(DB.java:161)
    at org.sqlite.core.CoreConnection.open(CoreConnection.java:145)
    at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:66)
    at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:21)
    at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
    at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
    at org.sqlite.JDBC.createConnection(JDBC.java:114)
    at org.sqlite.JDBC.connect(JDBC.java:88)
    at java.sql.DriverManager.getConnection(DriverManager.java:664)
    at java.sql.DriverManager.getConnection(DriverManager.java:270)
    at net.osmand.data.preparation.DBDialect.getDatabaseConnection(DBDialect.java:58)
    at net.osmand.data.preparation.IndexCreator.getDatabaseConnection(IndexCreator.java:167)
    at net.osmand.data.preparation.IndexCreator.createDatabaseIndexesStructure(IndexCreator.java:462)
    at net.osmand.data.preparation.IndexCreator.generateIndexes(IndexCreator.java:649)
    at net.osmand.data.preparation.IndexCreator.generateIndexes(IndexCreator.java:578)
    at net.osmand.swing.OsmExtractionUI$18.run(OsmExtractionUI.java:799)
    at net.osmand.swing.ProgressDialog$WorkerThread.run(ProgressDialog.java:87)

java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open(Ljava/lang/String;I)V
    at org.sqlite.core.NativeDB._open(Native Method)
    at org.sqlite.core.DB.open(DB.java:161)
    at org.sqlite.core.CoreConnection.open(CoreConnection.java:145)
    at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:66)
    at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:21)
    at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
    at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
    at org.sqlite.JDBC.createConnection(JDBC.java:114)
    at org.sqlite.JDBC.connect(JDBC.java:88)
    at java.sql.DriverManager.getConnection(DriverManager.java:664)
    at java.sql.DriverManager.getConnection(DriverManager.java:270)
    at net.osmand.data.preparation.DBDialect.getDatabaseConnection(DBDialect.java:58)
    at net.osmand.data.preparation.IndexCreator.getDatabaseConnection(IndexCreator.java:167)
    at net.osmand.data.preparation.IndexCreator.createDatabaseIndexesStructure(IndexCreator.java:462)
    at net.osmand.data.preparation.IndexCreator.generateIndexes(IndexCreator.java:649)
    at net.osmand.data.preparation.IndexCreator.generateIndexes(IndexCreator.java:578)
    at net.osmand.swing.OsmExtractionUI$18.run(OsmExtractionUI.java:799)
    at net.osmand.swing.ProgressDialog$WorkerThread.run(ProgressDialog.java:87)
```

I believe the problem is that it's assuming an executable `/tmp`, but letting code be executed from there hasn't been considered good security practice for years.

I'm running on Gentoo Linux.

**Comment by erik55** [comment]
Seems like this bug and bug #2632 are the same (duplicate). This occurs only on 32 bit systems. The solution is written here in this bug https://github.com/xerial/sqlite-jdbc/issues/34 , and is to update lib/sqlite-jdbc-3.8.7.jar to version sqlite-jdbc-3.8.10.1 or newer.

Please incorporate this newer version in osmMapCreator.

Thank you.

**Comment by Carnildo** [comment]
I'm running on a 64-bit multilib system, and as far as I can tell, Java is running in 64-bit mode.
