### ISSUE TITLE
Crash when searching for geo URI

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#3517]
Pasting a geo URI such as `geo:12.34,56.78` into the search field leads to a crash:

```
Version  OsmAnd+ 2.5.4
16.02.2017 8:18:41
Apk Version : 2.5.4 254
Exception occured in thread Thread[main,5,main] : 
java.lang.ClassCastException: net.osmand.util.GeoPointParserUtil$GeoParsedPoint cannot be cast to net.osmand.data.LatLon
	at net.osmand.plus.search.QuickSearchListItem.getTypeName(QuickSearchListItem.java:196)
	at net.osmand.plus.search.QuickSearchListItem.getTypeName(QuickSearchListItem.java:99)
	at net.osmand.plus.search.QuickSearchListAdapter.getView(QuickSearchListAdapter.java:286)
	at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)
	at android.widget.AbsListView.obtainView(AbsListView.java:2346)
	at android.widget.ListView.makeAndAddView(ListView.java:1876)
	at android.widget.ListView.fillDown(ListView.java:702)
	at android.widget.ListView.fillSpecific(ListView.java:1367)
	at android.widget.ListView.layoutChildren(ListView.java:1663)
	at android.widget.AbsListView.onLayout(AbsListView.java:2148)
	at android.view.View.layout(View.java:16639)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1735)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1579)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1488)
	at android.view.View.layout(View.java:16639)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1735)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1579)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1488)
	at android.view.View.layout(View.java:16639)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1735)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1579)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1488)
	at android.view.View.layout(View.java:16639)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16639)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16639)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1735)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1579)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1488)
	at android.view.View.layout(View.java:16639)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2934)
	at android.view.View.layout(View.java:16639)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2179)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1939)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6023)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
	at android.view.Choreographer.doFrame(Choreographer.java:606)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by scaidermern** [comment]
I know you are supposed to just enter the coordinates like `12.34,56.78` but stripping the `geo:` prefix from the start of the string should be easy.
