### ISSUE TITLE
Not displaying any maps

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#3531]
With the latest nightly version I am not seeing any map in osmand (it's only an empty map).

In logcat I can see a lot of this:

```
02-26 13:48:57.780  8908  8959 E net.osmand: OsmandMapTileView Attempt to invoke virtual method 'boolean java.io.File.equals(java.lang.Object)' on a null object reference
02-26 13:48:57.780  8908  8959 E net.osmand: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.equals(java.lang.Object)' on a null object reference
02-26 13:48:57.780  8908  8959 E net.osmand: 	at net.osmand.plus.GPXDatabase.getFileDir(GPXDatabase.java:213)
02-26 13:48:57.780  8908  8959 E net.osmand: 	at net.osmand.plus.GPXDatabase.getItem(GPXDatabase.java:313)
02-26 13:48:57.780  8908  8959 E net.osmand: 	at net.osmand.plus.views.GPXLayer.drawSelectedFilesSegments(GPXLayer.java:371)
02-26 13:48:57.780  8908  8959 E net.osmand: 	at net.osmand.plus.views.GPXLayer.onPrepareBufferImage(GPXLayer.java:173)
02-26 13:48:57.780  8908  8959 E net.osmand: 	at net.osmand.plus.views.OsmandMapTileView.refreshBaseMapInternal(OsmandMapTileView.java:495)
02-26 13:48:57.780  8908  8959 E net.osmand: 	at net.osmand.plus.views.OsmandMapTileView.access$700(OsmandMapTileView.java:59)
02-26 13:48:57.780  8908  8959 E net.osmand: 	at net.osmand.plus.views.OsmandMapTileView$2.run(OsmandMapTileView.java:638)
02-26 13:48:57.780  8908  8959 E net.osmand: 	at android.os.Handler.handleCallback(Handler.java:746)
02-26 13:48:57.780  8908  8959 E net.osmand: 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-26 13:48:57.780  8908  8959 E net.osmand: 	at android.os.Looper.loop(Looper.java:148)
02-26 13:48:57.780  8908  8959 E net.osmand: 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

osmand is `OsmAndF~ 2.6.0#16460D`

**Comment by utack** [comment]
Same here
Disabled Osmand Live, the online notes and gpx track overlay..then it came back
Maybe that helps for you too?

**Comment by AndreasTUHU** [comment]
Same here.
After starting Osmand displays the map once, but not updates the display until I turn off GPX overlay.

**Comment by AndreasTUHU** [comment]
2.6.0#20488 OK
2.6.0#20493 Not working

**Comment by mircozorzo** [comment]
Reappeared on 2.6.0#20564M

**Comment by littlehelper** [comment]
I observerd the same with latest nightly build 20566M too.
A temporary fix (only until restart of Osmand) is to either deactive 'Show current track' or to start (and stop) GPX track recording.
