### ISSUE TITLE
Crash when clicking search icon

### ISSUE THREAD

**Issue by sybrenstuvel** [osmandapp/Osmand#3539]
__Problem description__

Whenever I click on the "search" icon (the magnifying glass in the top left corner), OsmAnd crashes.
Re-downloading the map file for the currently shown region doesn't help.

__What version of OsmAnd are you using, on what device and Android/iOS version?__

Device : OnePlus3
Brand : OnePlus
Model : ONEPLUS A3003
Product : OnePlus3
Build : ONEPLUS A3003_16_161118
Version : 6.0.1
App Version : OsmAnd+
Apk Version : 2.5.4 254

__Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?__

Offline maps. The bug is reproducible with both OsmAnd Live enabled and disabled (I deleted the "live" files after disabling to ensure it would use the stock map).

This is the produced log:

```
Version  OsmAnd+ 2.5.4
13.02.2017 7:41:28
Apk Version : 2.5.4 254
Exception occured in thread Thread[main,5,main] : 
android.content.res.Resources$NotFoundException: Resource ID #0x1b
	at android.content.res.Resources.getValue(Resources.java:1365)
	at android.content.res.Resources.getDrawable(Resources.java:818)
	at android.content.Context.getDrawable(Context.java:459)
	at android.support.v4.content.ContextCompatApi21.getDrawable(ContextCompatApi21.java:26)
	at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:321)
	at net.osmand.plus.IconsCache.getDrawable(IconsCache.java:28)
	at net.osmand.plus.IconsCache.getIcon(IconsCache.java:58)
	at net.osmand.plus.search.QuickSearchListItem.getIcon(QuickSearchListItem.java:367)
	at net.osmand.plus.search.QuickSearchListItem.getIcon(QuickSearchListItem.java:258)
	at net.osmand.plus.search.QuickSearchListAdapter.getView(QuickSearchListAdapter.java:282)
	at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)
	at android.widget.AbsListView.obtainView(AbsListView.java:2358)
	at android.widget.ListView.makeAndAddView(ListView.java:1876)
	at android.widget.ListView.fillDown(ListView.java:702)
	at android.widget.ListView.fillSpecific(ListView.java:1367)
	at android.widget.ListView.layoutChildren(ListView.java:1675)
	at android.widget.AbsListView.onLayout(AbsListView.java:2160)
	at android.view.View.layout(View.java:16692)
	at android.view.ViewGroup.layout(ViewGroup.java:5449)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
	at android.view.View.layout(View.java:16692)
	at android.view.ViewGroup.layout(ViewGroup.java:5449)
	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1695)
	at android.view.View.layout(View.java:16692)
	at android.view.ViewGroup.layout(ViewGroup.java:5449)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
	at android.view.View.layout(View.java:16692)
	at android.view.ViewGroup.layout(ViewGroup.java:5449)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
	at android.view.View.layout(View.java:16692)
	at android.view.ViewGroup.layout(ViewGroup.java:5449)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16692)
	at android.view.ViewGroup.layout(ViewGroup.java:5449)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16692)
	at android.view.ViewGroup.layout(ViewGroup.java:5449)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
	at android.view.View.layout(View.java:16692)
	at android.view.ViewGroup.layout(ViewGroup.java:5449)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2707)
	at android.view.View.layout(View.java:16692)
	at android.view.ViewGroup.layout(ViewGroup.java:5449)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2173)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1933)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1109)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6046)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
	at android.view.Choreographer.doFrame(Choreographer.java:606)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:152)
	at android.app.ActivityThread.main(ActivityThread.java:5507)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by vshcherb** [comment]
Did you try to reinstall, looks like installation was incomplete

**Comment by vshcherb** [comment]
Not reproducible

**Comment by sybrenstuvel** [comment]
After reinstallation OsmAnd downloaded The Netherlands - Noord Holland and the world base map too. After that, the crash was gone. Thanks.
