### ISSUE TITLE
Crash when opening Dashboard

### ISSUE THREAD

**Issue by CJTmmr** [osmandapp/Osmand#3553]
Using Samsung Galaxy Camera 2 (EK-GC200), Android 4.3
Using Latest nightlies - OsmAndF~
Since at least 4 days I get a app-crash when I want to show Dashboard.
Through the "grid"-symbol on the map, as well as through the side-menu.

Thanks for investigating; related to new GPX-file-management?

This is exception.log:

`Version  OsmAndF~ 2.6.0#16651D
14.03.2017 6:52:37
Apk Version : 2.6.0#16651D 240
Exception occured in thread Thread[main,5,main] :
android.database.sqlite.SQLiteException: duplicate column name: color (code 1): , while compiling: ALTER TABLE gpxTable ADD color TEXT
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1120)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:693)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1794)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1725)
	at net.osmand.plus.api.SQLiteAPIImpl$SQLiteDatabaseWrapper.execSQL(SQLiteAPIImpl.java:103)
	at net.osmand.plus.GPXDatabase.onUpgrade(GPXDatabase.java:131)
	at net.osmand.plus.GPXDatabase.openConnection(GPXDatabase.java:117)
	at net.osmand.plus.GPXDatabase.getItem(GPXDatabase.java:310)
	at net.osmand.plus.myplaces.AvailableGPXFragment.udpateGpxInfoView(AvailableGPXFragment.java:1621)
	at net.osmand.plus.monitoring.DashTrackFragment.setupGpxFiles(DashTrackFragment.java:168)
	at net.osmand.plus.monitoring.DashTrackFragment.onOpenDash(DashTrackFragment.java:88)
	at net.osmand.plus.dashboard.DashBaseFragment.onResume(DashBaseFragment.java:123)
	at android.support.v4.app.Fragment.performResume(Fragment.java:2020)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1107)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
	at android.os.Handler.handleCallback(Handler.java:730)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:177)
	at android.app.ActivityThread.main(ActivityThread.java:5493)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1225)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1041)
	at dalvik.system.NativeStart.main(Native Method)`

**Comment by crimean** [comment]
I would suggest to reset data or reinstall app. Cannot explain how it could happen.

**Comment by CJTmmr** [comment]
Deleting Data with Android-App-management after re-install helped indeed...
No more crashes.
Thanks, just had to reconfigure my personal settings...

Kees-Jan
