### ISSUE TITLE
OsmAnd+ ClassCastException on startup, free version works

### ISSUE THREAD

**Issue by brdloush** [osmandapp/Osmand#3564]
Hi,

I've made fresh installation of OsmAnd+ on new Vernee Apollo Lite LTE (Android 6). It immediately crashed (and kept crashing) with following exception (logcat excerpt, see bellow). At the same time the free version of OsmAnd started without any problems. I've tried reinstalling, cleaning data etc., nothing helped. As a last attempt, I've restarted the device and the restart OsmAnd+ started without any issues. Not sure if this may be a bug in OsmAnd or it was some system issue.

```
03-19 11:54:54.800 15305 15305 D ActivityThread: BIND_APPLICATION handled : 0 / AppBindData{appInfo=ApplicationInfo{2766f7c net.osmand.plus}}
03-19 11:54:54.800 15305 15305 V ActivityThread: Handling launch of ActivityRecord{84d7005 token=android.os.BinderProxy@9f8685a {net.osmand.plus/net.osmand.plus.activities.MapActivity}} startsNotResumed=false
03-19 11:54:54.808 15305 15305 V ActivityThread: ActivityRecord{84d7005 token=android.os.BinderProxy@9f8685a {net.osmand.plus/net.osmand.plus.activities.MapActivity}}: app=android.app.Application@6790768, appName=net.osmand.plus, pkg=net.osmand.plus, comp={net.osmand.plus/net.osmand.plus.activities.MapActivity}, dir=/data/app/net.osmand.plus-1/base.apk
03-19 11:54:54.811 15305 15305 D AndroidRuntime: Shutting down VM
03-19 11:54:54.812 15305 15305 E AndroidRuntime: FATAL EXCEPTION: main
03-19 11:54:54.812 15305 15305 E AndroidRuntime: Process: net.osmand.plus, PID: 15305
03-19 11:54:54.812 15305 15305 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{net.osmand.plus/net.osmand.plus.activities.MapActivity}: java.lang.ClassCastException: android.app.Application cannot be cast to net.osmand.plus.OsmandApplication
03-19 11:54:54.812 15305 15305 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2547)
03-19 11:54:54.812 15305 15305 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2613)
03-19 11:54:54.812 15305 15305 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(ActivityThread.java)
03-19 11:54:54.812 15305 15305 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1469)
03-19 11:54:54.812 15305 15305 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:111)
03-19 11:54:54.812 15305 15305 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:207)
03-19 11:54:54.812 15305 15305 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5695)
03-19 11:54:54.812 15305 15305 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-19 11:54:54.812 15305 15305 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
03-19 11:54:54.812 15305 15305 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)
03-19 11:54:54.812 15305 15305 E AndroidRuntime: Caused by: java.lang.ClassCastException: android.app.Application cannot be cast to net.osmand.plus.OsmandApplication
03-19 11:54:54.812 15305 15305 E AndroidRuntime:        at net.osmand.plus.activities.MapActivity.getMyApplication(MapActivity.java:796)
03-19 11:54:54.812 15305 15305 E AndroidRuntime:        at net.osmand.plus.activities.MapActivity.onCreate(MapActivity.java:185)
03-19 11:54:54.812 15305 15305 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6270)
03-19 11:54:54.812 15305 15305 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
03-19 11:54:54.812 15305 15305 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2500)
03-19 11:54:54.812 15305 15305 E AndroidRuntime:        ... 9 more
03
```

**Comment by vshcherb** [comment]
It looks like corrupted installation unfortunately.

**Comment by vshcherb** [comment]
Good it was resolved
