### ISSUE TITLE
Can't save generated gpx files

### ISSUE THREAD

**Issue by kompowiec** [osmandapp/Osmand#3568]
Steps to reproduce:
1. Create new any route
2. Click on daahboard-->info

Log here:

Version  OsmAndF~ 2.6.0#16657D
21.03.2017 7:38:37
Apk Version : 2.6.0#16657D 240
Exception occured in thread Thread[main,5,main] : 
android.content.ActivityNotFoundException: Unable to find explicit activity class {net.osmand.dev/net.osmand.plus.activities.ShowRouteInfoDialogFragment}; have you declared this activity in your AndroidManifest.xml?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1805)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1523)
	at android.app.Activity.startActivityForResult(Activity.java:4032)
	at android.app.Activity.startActivityForResult(Activity.java:3986)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:843)
	at android.app.Activity.startActivity(Activity.java:4316)
	at android.app.Activity.startActivity(Activity.java:4284)
	at net.osmand.plus.activities.MapActivity.startActivity(MapActivity.java:431)
	at net.osmand.plus.dashboard.DashNavigationFragment$2.onClick(DashNavigationFragment.java:47)
	at android.view.View.performClick(View.java:5273)
	at android.view.View$PerformClick.run(View.java:21315)
	at android.os.Handler.handleCallback(Handler.java:743)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5665)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)

Other info:

Device : HNNEM-H
Brand : HONOR
Model : NEM-L21
Product : NEM-L21
Build : NEM-L21C432B132
Version : 6.0

**Comment by sonora** [comment]
Yes, confirmed, crash only occurs when opening Info via the Dashboard, saving a route via the route config dialog works ok.
