### ISSUE TITLE
Reset issue on the search screen

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#3660]
See screenshot attached: I cannot seem to update the button "Search street in Lucca". I had once searched something in Lucca with a previous build, but now the button function and button caption never seem to update again. I am not located in Lucca either. (Nightly of 4/14.)

![untitled](https://cloud.githubusercontent.com/assets/845735/25061841/5389aa40-21bf-11e7-8b33-c554e8ce4377.png)

**Comment by vshcherb** [comment]
Doesn't seem to be much critical. If you clear on any "Nearest cities" the city will be replaced.

**Comment by kmq** [comment]
I am currently stuck on this same problem: 

Selecting a city from "Nearest cities" just takes me there on the map. The "search street" field is not updated.

Using  "Select the city first" let's me search and find a city, but when selecting it, just takes me there on the map as well

This does not happen with *all* cities: It seems to *only* happen to the city that I am currently in. Trying to search any other city works as expected, but I can't select the city I am currently at.

Which is annoying, because chances are, things in this place are highly relevant for me.

This is a stracktrace I found via adb logcat which seems somewhat relevant.





```
01-11 10:22:23.545 28381 28381 W System.err: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either than the input has been truncated or that an embedded message misreported its own length. 
01-11 10:22:23.545 28381 28381 W System.err:    at com.google.protobuf.CodedInputStream.pushLimit(CodedInputStream.java:668)
01-11 10:22:23.546 28381 28381 W System.err:    at net.osmand.binary.BinaryMapIndexReader.preloadStreets(BinaryMapIndexReader.java:652)
01-11 10:22:23.546 28381 28381 W System.err:    at net.osmand.plus.search.QuickSearchListFragment.isCityEmpty(QuickSearchListFragment.java:138)
01-11 10:22:23.546 28381 28381 W System.err:    at net.osmand.plus.search.QuickSearchListFragment.onListItemClick(QuickSearchListFragment.java:106)
01-11 10:22:23.546 28381 28381 W System.err:    at android.support.v4.app.ListFragment$2.onItemClick(ListFragment.java:62)
01-11 10:22:23.546 28381 28381 W System.err:    at android.widget.AdapterView.performItemClick(AdapterView.java:310)
01-11 10:22:23.546 28381 28381 W System.err:    at android.widget.AbsListView.performItemClick(AbsListView.java:1164)
01-11 10:22:23.546 28381 28381 W System.err:    at android.widget.AbsListView$PerformClick.run(AbsListView.java:3139)
01-11 10:22:23.546 28381 28381 W System.err:    at android.widget.AbsListView.onTouchUp(AbsListView.java:4066)
01-11 10:22:23.546 28381 28381 W System.err:    at android.widget.AbsListView.onTouchEvent(AbsListView.java:3825)
01-11 10:22:23.546 28381 28381 W System.err:    at android.view.View.dispatchTouchEvent(View.java:10024)
01-11 10:22:23.546 28381 28381 W System.err:    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2626)
01-11 10:22:23.546 28381 28381 W System.err:    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2307)
01-11 10:22:23.546 28381 28381 W System.err:    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
01-11 10:22:23.546 28381 28381 W System.err:    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
01-11 10:22:23.547 28381 28381 W System.err:    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
01-11 10:22:23.547 28381 28381 W System.err:    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
01-11 10:22:23.547 28381 28381 W System.err:    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
01-11 10:22:23.547 28381 28381 W System.err:    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
01-11 10:22:23.547 28381 28381 W System.err:    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
01-11 10:22:23.547 28381 28381 W System.err:    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
01-11 10:22:23.547 28381 28381 W System.err:    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
01-11 10:22:23.547 28381 28381 W System.err:    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
01-11 10:22:23.547 28381 28381 W System.err:    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
01-11 10:22:23.547 28381 28381 W System.err:    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
01-11 10:22:23.547 28381 28381 W System.err:    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
01-11 10:22:23.547 28381 28381 W System.err:    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
01-11 10:22:23.547 28381 28381 W System.err:    at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:416)
01-11 10:22:23.547 28381 28381 W System.err:    at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
01-11 10:22:23.547 28381 28381 W System.err:    at android.app.Dialog.dispatchTouchEvent(Dialog.java:806)
01-11 10:22:23.547 28381 28381 W System.err:    at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:378)
01-11 10:22:23.547 28381 28381 W System.err:    at android.view.View.dispatchPointerEvent(View.java:10244)
01-11 10:22:23.548 28381 28381 W System.err:    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4444)
01-11 10:22:23.548 28381 28381 W System.err:    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4312)
01-11 10:22:23.548 28381 28381 W System.err:    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
01-11 10:22:23.548 28381 28381 W System.err:    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3912)
01-11 10:22:23.548 28381 28381 W System.err:    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3878)
01-11 10:22:23.548 28381 28381 W System.err:    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4005)
01-11 10:22:23.548 28381 28381 W System.err:    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3886)
01-11 10:22:23.548 28381 28381 W System.err:    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4062)
01-11 10:22:23.548 28381 28381 W System.err:    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
01-11 10:22:23.548 28381 28381 W System.err:    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3912)
01-11 10:22:23.548 28381 28381 W System.err:    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3878)
01-11 10:22:23.548 28381 28381 W System.err:    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3886)
01-11 10:22:23.548 28381 28381 W System.err:    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
01-11 10:22:23.548 28381 28381 W System.err:    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6253)
01-11 10:22:23.548 28381 28381 W System.err:    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6227)
01-11 10:22:23.548 28381 28381 W System.err:    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6188)
01-11 10:22:23.548 28381 28381 W System.err:    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6356)
01-11 10:22:23.549 28381 28381 W System.err:    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
01-11 10:22:23.549 28381 28381 W System.err:    at android.os.MessageQueue.nativePollOnce(Native Method)
01-11 10:22:23.549 28381 28381 W System.err:    at android.os.MessageQueue.next(MessageQueue.java:323)
01-11 10:22:23.549 28381 28381 W System.err:    at android.os.Looper.loop(Looper.java:136)
01-11 10:22:23.549 28381 28381 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6186)
01-11 10:22:23.549 28381 28381 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
01-11 10:22:23.549 28381 28381 W System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
01-11 10:22:23.549 28381 28381 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```
