### ISSUE TITLE
Sample Application is == null hence unable to create application

### ISSUE THREAD

**Issue by niiokai77** [osmandapp/Osmand#3675]
FATAL EXCEPTION: main
                                                                                         Process: net.osmand.core.samples.android.sample1, PID: 18297
                                                                                         java.lang.RuntimeException: Unable to create application net.osmand.core.samples.android.sample1.SampleApplication: java.lang.IllegalArgumentException: is == null
                                                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5278)
                                                                                             at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1580)
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                             at android.os.Looper.loop(Looper.java:227)
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:6100)
                                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:859)
                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)
                                                                                          Caused by: java.lang.IllegalArgumentException: is == null
                                                                                             at org.kxml2.io.KXmlParser.setInput(KXmlParser.java:1634)
                                                                                             at net.osmand.osm.MapPoiTypes.initFromInputStream(MapPoiTypes.java:312)
                                                                                             at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:289)
                                                                                             at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:274)
                                                                                             at net.osmand.core.samples.android.sample1.SampleApplication.initPoiTypes(SampleApplication.java:192)
                                                                                             at net.osmand.core.samples.android.sample1.SampleApplication.onCreate(SampleApplication.java:85)
                                                                                             at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1031)
                                                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5275)
                                                                                             at android.app.ActivityThread.-wrap1(ActivityThread.java) 
                                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1580) 
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                                             at android.os.Looper.loop(Looper.java:227) 
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:6100) 
                                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:859) 
                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)

**Comment by xmd5a2** [comment]
Do you have OsmAnd installed?

**Comment by niiokai77** [comment]
Yes, the play store version and the free one which uses intents to launch are already installed.

**Comment by niiokai77** [comment]
I've uninstalled the other versions and still it gives the same error.

**Comment by vshcherb** [comment]
In OsmAnd you should use Shared memory to store maps.

**Comment by niiokai77** [comment]
Could you explain this more? I'm using Windows 10 to deploy the application and not sure how to go about this.

**Comment by vshcherb** [comment]
You should use this app http://download.osmand.net/latest-night-build/OsmAnd-qt-sample-armv7.apk  and it should be fine.
