### ISSUE TITLE
RuntimeException when stopping the audio note

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#3698]
While traveling I could see some crashes in osmand.
This one seems to happens when clicking to record an audio note and quickly clicking to stop in the sequence:

```
Version  OsmAndF~ 2.7.0#17191D
23.04.2017 4:12:42
Apk Version : 2.7.0#17191D 240
Exception occured in thread Thread[main,5,main] : 
java.lang.RuntimeException: stop failed.
        at android.media.MediaRecorder.stop(Native Method)
        at net.osmand.plus.audionotes.AudioVideoNotesPlugin.stopCameraRecording(AudioVideoNotesPlugin.java:1081)
        at net.osmand.plus.audionotes.AudioVideoNotesPlugin.stopRecording(AudioVideoNotesPlugin.java:1531)
        at net.osmand.plus.audionotes.AudioVideoNotesPlugin$13.onClick(AudioVideoNotesPlugin.java:1518)
        at android.view.View.performClick(View.java:5201)
        at android.view.View$PerformClick.run(View.java:21163)
        at android.os.Handler.handleCallback(Handler.java:746)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5443)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

**Comment by vshcherb** [comment]
Currently not reproducible on our devices

**Comment by naoliv** [comment]
I still see this problem:

```
Version  OsmAnd Nightly 3.3.0#24338d
23.06.2019 3:18:53
Apk Version : 3.3.0#24338d 330
Exception occured in thread Thread[main,5,main] : 
java.lang.RuntimeException: stop failed.
        at android.media.MediaRecorder.stop(Native Method)
        at net.osmand.plus.audionotes.AudioVideoNotesPlugin.stopMediaRecording(AudioVideoNotesPlugin.java:1135)
        at net.osmand.plus.audionotes.AudioVideoNotesPlugin.stopRecording(AudioVideoNotesPlugin.java:1616)
        at net.osmand.plus.audionotes.AudioVideoNotesPlugin$13.onClick(AudioVideoNotesPlugin.java:1607)
        at android.view.View.performClick(View.java:6605)
        at android.view.View.performClickInternal(View.java:6582)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25897)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6694)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

```
Version  OsmAnd Nightly 3.4.0#24645d
28.07.2019 10:57:53
Apk Version : 3.4.0#24645d 340
Exception occured in thread Thread[main,5,main] : 
java.lang.RuntimeException: stop failed.
        at android.media.MediaRecorder.stop(Native Method)
        at net.osmand.plus.audionotes.AudioVideoNotesPlugin.stopMediaRecording(AudioVideoNotesPlugin.java:1135)
        at net.osmand.plus.audionotes.AudioVideoNotesPlugin.stopRecording(AudioVideoNotesPlugin.java:1616)
        at net.osmand.plus.audionotes.AudioVideoNotesPlugin$13.onClick(AudioVideoNotesPlugin.java:1607)
        at android.view.View.performClick(View.java:6605)
        at android.view.View.performClickInternal(View.java:6582)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25897)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6694)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
