### ISSUE TITLE
Dozends of crashes when sending device to StandBy

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#3837]
During a hiking tour of 10km I had much more than a dozend crashes.
I look at the map, then switch device to standBy. When I want to reopen osmand again, it is not active, I have to start it manually. Then app asks me whether I want to send a crash report. So you got a lot to read from email pebogufi21@...
I was never in navigation mode.
It does not matter whether recording is on/off.
It does not matter whether battery saving is on/off.
It does not matter whether gps is active/off.
- - -
Next problem:
In former times it was a easy workaround to install a older version if a new nightly build causes trouble.
This is not possible any more. The system refuses to install 2.7.0#21461 over current version. This is horrible !!!

Device : s5neolte
Brand : samsung
Model : SM-G903F
Product : s5neoltexx
Build : LMY47X.G903FXXU1APA2
Version : 5.1.1
App Version : OsmAnd~
Apk Version : 2.7.0 270

Version  OsmAnd~ 2.7.0
27.05.2017 6:19:05
Apk Version : 2.7.0 270
Exception occured in thread Thread[main,5,main] : 
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.SCREEN_OFF flg=0x50000010 (has extras) } in net.osmand.plus.activities.MapActivity$ScreenOffReceiver@3f9d65b7
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:996)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6873)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by: java.lang.NullPointerException: Null pointer exception during instruction 'invoke-static {v0}, net.osmand.plus.audionotes.AudioVideoNotesPlugin$AVActionType net.osmand.plus.audionotes.AudioVideoNotesPlugin$CurrentRecording.access$1200(net.osmand.plus.audionotes.AudioVideoNotesPlugin$CurrentRecording) // method@58096'
	at net.osmand.plus.audionotes.AudioVideoNotesPlugin.stopRecording(AudioVideoNotesPlugin.java:1561)
	at net.osmand.plus.audionotes.AudioVideoNotesPlugin.mapActivityScreenOff(AudioVideoNotesPlugin.java:819)
	at net.osmand.plus.OsmandPlugin.onMapActivityScreenOff(OsmandPlugin.java:390)
	at net.osmand.plus.activities.MapActivity$ScreenOffReceiver.onReceive(MapActivity.java:1445)
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:986)
	... 8 more

**Comment by jfburke3** [comment]
I've had some recent night builds crash a lot on me, too, under different circumstances.  I haven't sent any debug logs about it, but can the next time it happens.

**Comment by pebogufi** [comment]
... and reported here.
https://groups.google.com/forum/m/#!topic/osmand/LGmhddo5qFY
