### ISSUE TITLE
NPE in MapCreator

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#3935]
At least since June 8th I am seeing this with MapCreator:

```
jun 15, 2017 11:15:19 PM net.osmand.data.index.IndexBatchCreator generateIndex
ADVERTÊNCIA: ----------- Generate Brazil-AC.osm.pbf



XML configuration file could not be read from /home/naoliv/mapa/creator/lote.xml
java.lang.NullPointerException
	at net.osmand.data.index.IndexBatchCreator.generateIndex(IndexBatchCreator.java:507)
	at net.osmand.data.index.IndexBatchCreator.generatedIndexes(IndexBatchCreator.java:475)
	at net.osmand.data.index.IndexBatchCreator.runBatch(IndexBatchCreator.java:318)
	at net.osmand.data.index.IndexBatchCreator.main(IndexBatchCreator.java:168)
jun 15, 2017 11:15:19 PM net.osmand.data.index.IndexBatchCreator main
GRAVE: XML configuration file could not be read from /home/naoliv/mapa/creator/lote.xml
java.lang.NullPointerException
	at net.osmand.data.index.IndexBatchCreator.generateIndex(IndexBatchCreator.java:507)
	at net.osmand.data.index.IndexBatchCreator.generatedIndexes(IndexBatchCreator.java:475)
	at net.osmand.data.index.IndexBatchCreator.runBatch(IndexBatchCreator.java:318)
	at net.osmand.data.index.IndexBatchCreator.main(IndexBatchCreator.java:168)
```

`lote.xml` is my own `batch.xml`, wich wasn't modified in this time:

```xml
<?xml version="1.0" encoding="utf-8"?>
<batch_process>
	<process_attributes mapZooms="" renderingTypesFile="" zoomWaySmoothness=""
		osmDbDialect="sqlite" mapDbDialect="sqlite"/>

	<!-- There are 3 subprocess :
		 1. Download fresh osm files from servers to 'directory_for_osm_files' (override existings).
		 2. Generate index files from all files in 'directory_for_osm_files' and put all indexes into 'directory_for_index_files'
		 3. Upload index files from 'directory_for_index_files' to googlecode.
		 If directory directory_for_uploaded_files is specified all uploaded files will be moved to it
		 All these subprocess could be ran independently ! So you can create some files check them and after that try to upload on googlecode,
		 or you can upload any file you have to googlecode (just put into 'directory_for_index_files')
	 -->
	 <!-- zoomWaySmoothness - 1-4, typical mapZooms - 11;12;13-14;15-   -->
	 <process directory_for_osm_files="/home/naoliv/mapa/osm" directory_for_index_files="/home/naoliv/mapa/mapa" directory_for_generation="/arquivos/tmp"
		 skipExistingIndexesAt="/arquivos/tmp" directory_for_srtm_files="/arquivos/srtm-osmand" indexPOI="true" indexRouting="true" indexMap="true" indexTransport="true" indexAddress="true">
		<!-- Add wget="C:/Program Files/GNUWin32/bin/wget.exe" to process, to use wget for download.
			 On linux systems if wget is in your path it can be wget="wget" or you can make own script with wget command:
			 wget="/path/to/script/wget.sh"
			 Defaultly enabled parameter of wget is: &-&-read-timeout=5 that prevents hanging of download from  cloudmade/geofabrik server
		-->

	</process>
</batch_process>
```

Diff from vanilla `batch.xml` is minimal (only paths from what I can see):

```diff
--- batch.xml	2017-06-15 22:27:50.000000000 -0300
+++ lote.xml	2017-04-18 10:48:44.063739676 -0300
@@ -12,9 +12,8 @@
 		 or you can upload any file you have to googlecode (just put into 'directory_for_index_files')
 	 -->
 	 <!-- zoomWaySmoothness - 1-4, typical mapZooms - 11;12;13-14;15-   -->
-	<process directory_for_osm_files="/home/..." directory_for_index_files="/home/..." directory_for_generation="/home/..."
-		skipExistingIndexesAt="/home/..." directory_for_srtm_files="/home/..." indexPOI="true" indexRouting="true" indexMap="true"
-		indexTransport="true" indexAddress="true">
+	 <process directory_for_osm_files="/home/naoliv/mapa/osm" directory_for_index_files="/home/naoliv/mapa/mapa" directory_for_generation="/arquivos/tmp"
+		 skipExistingIndexesAt="/arquivos/tmp" directory_for_srtm_files="/arquivos/srtm-osmand" indexPOI="true" indexRouting="true" indexMap="true" indexTransport="true" indexAddress="true">
 		<!-- Add wget="C:/Program Files/GNUWin32/bin/wget.exe" to process, to use wget for download.
 			 On linux systems if wget is in your path it can be wget="wget" or you can make own script with wget command:
 			 wget="/path/to/script/wget.sh"
```

Did something get broken in the latest MapCreator versions?

**Comment by vshcherb** [comment]
Fixed
