### ISSUE TITLE
Osmand keeps on crashing on France Brittany map

### ISSUE THREAD

**Issue by DamienCassou** [osmandapp/Osmand#3952]
The app regularly crashes on the "France Brittany" map. I tried on 2 OsmAnd versions downloaded from 2 different locations with no data sharing between the two.

> What version of OsmAnd are you using, on what device and Android/iOS version?

- OsmAnd
  - OsmAnd~ (from fdroid) 2.6.3
  - [OsmAnd-default.apk](http://download.osmand.net/latest-night-build/OsmAnd-default.apk) downloaded today: OsmAndF~ 2.7.0#17715D
- Android: 7.1.2, LineageOS nightly June 19th, 14.1-20170619, rooted+twrp
- Phone: OnePlus One (bacon)

> Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

only offline maps

> If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.

I have 2 offline maps on my phone :
- Not crashing: "Sweden Stockholm län"  (June 1st)
- Crashing: "France Brittany" (June 1st)

I can very easily reproduce the application crash in France Brittany (around Brest city). I have *not* been able to reproduce in Stockholm.

Please tell me how to give you a log of the problem if you want one.

**Comment by vshcherb** [comment]
Programs like these could help to retrieve the logs https://play.google.com/store/search?q=logcat&c=apps&hl=en

**Comment by vshcherb** [comment]
exception.log in osmand folder is welcome too.

**Comment by DamienCassou** [comment]
```
09-04 12:13:17.548  5009  5030 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=net.osmand.plus/.activities.MapActivity bnds=[330,1466][540,1704] (has extras)} from uid 10032 on display 0
09-04 12:13:17.608  5009  5045 E Notification: setLatestEventInfo() is deprecated and you should feel deprecated.
09-04 12:13:17.608  5009  5045 E Notification: java.lang.Throwable
09-04 12:13:17.608  5009  5045 E Notification: 	at android.app.Notification.setLatestEventInfo(Notification.java:2083)
09-04 12:13:17.608  5009  5045 E Notification: 	at com.android.server.am.ActivityManagerService$MainHandler.handleMessage(ActivityManagerService.java:2363)
09-04 12:13:17.608  5009  5045 E Notification: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-04 12:13:17.608  5009  5045 E Notification: 	at android.os.Looper.loop(Looper.java:154)
09-04 12:13:17.608  5009  5045 E Notification: 	at android.os.HandlerThread.run(HandlerThread.java:61)
09-04 12:13:17.608  5009  5045 E Notification: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
09-04 12:13:17.652  5009  7137 E LocSvc_eng: E/void loc_eng_delete_aiding_data(loc_eng_data_s_type &, GpsAidingData): log_eng state error: instance not initialized
09-04 12:13:17.652  5009  5029 I GnssLocationProvider: WakeLock acquired by sendMessage(5, 0, null)
09-04 12:13:17.716  5009  5043 I GnssLocationProvider: WakeLock acquired by handleInjectNtpTime()
09-04 12:13:17.716  5009  5043 I GnssLocationProvider: WakeLock released by handleMessage(5, 0, null)
09-04 12:13:17.717  5009  1396 E LocSvc_eng: E/int loc_eng_inject_time(loc_eng_data_s_type &, GpsUtcTime, int64_t, int): log_eng state error: instance not initialized
09-04 12:13:17.718  5009  1396 I GnssLocationProvider: WakeLock acquired by sendMessage(10, 0, null)
09-04 12:13:17.718  5009  1396 I GnssLocationProvider: WakeLock released by handleInjectNtpTime()
09-04 12:13:17.718  5009  5043 I GnssLocationProvider: WakeLock released by handleMessage(10, 0, null)
09-04 12:13:19.898 16862 16889 I net.osmand: MapRenderRepositories RENDER MAP: update due zoom/map density
09-04 12:13:19.898 16862 16889 I net.osmand: MapRenderRepositories RENDER MAP: Interrupt rendering map
09-04 12:13:20.573 16862 16888 I net.osmand: MapRenderRepositories RENDER MAP: new request RotatedTileBox [lat=48.401546478271484, lon=-4.50404167175293, rotate=0.0, density=3.0, zoom=15, mapDensity=0.9900000095367432, zoomAnimation=0.0, zoomFloatPart=0.0, cx=900, cy=1386, pixWidth=1800, pixHeight=2772]
09-04 12:13:20.793 16862 16862 D net.osmand: OsmandMapTileView onDoubleTap getZoom()
09-04 12:13:21.655 16862 16889 I net.osmand: MapRenderRepositories RENDER MAP: update due zoom/map density
09-04 12:13:21.655 16862 16889 I net.osmand: MapRenderRepositories RENDER MAP: Interrupt rendering map
09-04 12:13:22.138 16862 16888 I net.osmand:native: Route objects 47761
09-04 12:13:22.140 16862 16888 I net.osmand:native: Islands 0, closed water 2, coastline touches screen 1
09-04 12:13:22.140 16862 16888 I net.osmand:native: Detailed coastlines = 19, basemap coastlines 1, ocean tile 0. Detailed added 1, basemap processed 0, basemap added 1.
09-04 12:13:22.194 16862 16888 I net.osmand:native: Search : tree - read( 4474), accept( 2304), objs - visit( 90765), accept(47823), in result(47765) 
09-04 12:13:22.336 16862 16888 I net.osmand: MapRenderRepositories RENDER MAP: new request RotatedTileBox [lat=48.39585793396463, lon=-4.4973071645112555, rotate=0.0, density=3.0, zoom=16, mapDensity=0.9900000095367432, zoomAnimation=0.0, zoomFloatPart=0.0, cx=900, cy=1386, pixWidth=1800, pixHeight=2772]
09-04 12:13:22.577 16862 16889 I net.osmand: MapRenderRepositories RENDER MAP: update due zoom/map density
09-04 12:13:22.577 16862 16889 I net.osmand: MapRenderRepositories RENDER MAP: Interrupt rendering map
09-04 12:13:23.154 16862 16888 I net.osmand:native: Route objects 33049
09-04 12:13:23.155 16862 16888 I net.osmand:native: Islands 0, closed water 1, coastline touches screen 1
09-04 12:13:23.155 16862 16888 I net.osmand:native: Detailed coastlines = 13, basemap coastlines 1, ocean tile 0. Detailed added 1, basemap processed 0, basemap added 1.
09-04 12:13:23.183 16862 16888 I net.osmand:native: Search : tree - read( 2954), accept( 1262), objs - visit( 50605), accept(33083), in result(33051) 
09-04 12:13:23.284 16862 16888 I net.osmand: MapRenderRepositories RENDER MAP: new request RotatedTileBox [lat=48.39454203206207, lon=-4.495611703438925, rotate=0.0, density=3.0, zoom=18, mapDensity=0.9900000095367432, zoomAnimation=0.0, zoomFloatPart=0.0, cx=900, cy=1386, pixWidth=1800, pixHeight=2772]
09-04 12:13:23.346 16862 16888 I net.osmand:native: Route objects 1895
09-04 12:13:23.346 16862 16888 I net.osmand:native: Islands 0, closed water 2, coastline touches screen 1
09-04 12:13:23.346 16862 16888 I net.osmand:native: Detailed coastlines = 2, basemap coastlines 1, ocean tile 0. Detailed added 1, basemap processed 0, basemap added 1.
09-04 12:13:23.348 16862 16888 I net.osmand:native: Search : tree - read( 1394), accept( 178), objs - visit( 8805), accept(1908), in result(1899) 
09-04 12:13:23.473 16862 16888 I net.osmand: MapRenderRepositories BLat=48.38905429840088, TLat=48.40002727508545, LLong=-4.500489234924316, RLong=-4.490736961364746, zoom=18
09-04 12:13:23.473 16862 16888 I net.osmand: MapRenderRepositories Native search: 189 ms 
09-04 12:13:23.484 16862 16888 I net.osmand:native: Creating SkBitmap in native w:1800 h:2772 s:3600 f:4!
09-04 12:13:23.484 16862 16888 I net.osmand:native: Row bytes for RGB_565 is 3600
09-04 12:13:23.484 16862 16888 I net.osmand:native: Locked 9979200 bytes at 0x560fb00c
09-04 12:13:23.484 16862 16888 I net.osmand:native: Initializing rendering
09-04 12:13:23.484 16862 16888 I net.osmand:native: Rendering image
09-04 12:13:25.237 16862 16888 I net.osmand: RenderingIcons Icon data length is 775
09-04 12:13:25.239 16862 16888 I net.osmand: RenderingIcons Icon data length is 903
09-04 12:13:25.243 16862 16888 I net.osmand: RenderingIcons Icon data length is 313
09-04 12:13:25.243 16862 16888 I net.osmand: RenderingIcons Icon data length is 630
09-04 12:13:25.244 16862 16888 I net.osmand: RenderingIcons Icon data length is 812
09-04 12:13:25.244 16862 16888 I net.osmand: RenderingIcons Icon data length is 760
09-04 12:13:25.245 16862 16888 I net.osmand: RenderingIcons Icon data length is 893
09-04 12:13:25.252 16862 16888 I net.osmand: RenderingIcons Icon data length is 428
09-04 12:13:25.252 16862 16888 I net.osmand: RenderingIcons Icon data length is 803
09-04 12:13:25.275 16862 16888 I net.osmand: RenderingIcons Icon data length is 421
09-04 12:13:25.276 16862 16888 I net.osmand: RenderingIcons Icon data length is 546
09-04 12:13:25.281 16862 16888 I net.osmand: RenderingIcons Icon data length is 477
09-04 12:13:25.281 16862 16888 I net.osmand: RenderingIcons Icon data length is 368
09-04 12:13:25.440 16862 16888 I net.osmand:native: Native ok (rendering 6175, text 4451 ms) 
09-04 12:13:25.440 16862 16888 I net.osmand:native:  (30591 points, 14982 points inside, 2962 of 3573 objects visible)
09-04 12:13:25.441 16862 16888 I net.osmand:native: End Rendering image
09-04 12:13:25.441 16862 16888 I net.osmand:native: Native ok (init 1900015, rendering 6175) 
09-04 12:13:25.442 16862 16888 I net.osmand: MapRenderRepositories true
09-04 12:13:26.860 16862 16889 I net.osmand: MapRenderRepositories RENDER MAP: update due zoom/map density
09-04 12:13:26.860 16862 16889 I net.osmand: MapRenderRepositories RENDER MAP: Interrupt rendering map
09-04 12:13:26.901 16862 16889 I net.osmand: MapRenderRepositories RENDER MAP: update due zoom/map density
09-04 12:13:26.901 16862 16889 I net.osmand: MapRenderRepositories RENDER MAP: Interrupt rendering map
09-04 12:13:26.943 16862 16888 I net.osmand: MapRenderRepositories RENDER MAP: new request RotatedTileBox [lat=48.39408178064456, lon=-4.495716844409941, rotate=0.0, density=3.0, zoom=20, mapDensity=0.9900000095367432, zoomAnimation=0.0, zoomFloatPart=0.0, cx=900, cy=1386, pixWidth=1800, pixHeight=2772]
09-04 12:13:26.975 16862 16888 I net.osmand:native: Route objects 146
09-04 12:13:26.975 16862 16888 I net.osmand:native: Detailed coastlines = 1, basemap coastlines 1, ocean tile 0. Detailed added 0, basemap processed 0, basemap added 0.
09-04 12:13:26.975 16862 16888 I net.osmand:native: Search : tree - read( 1154), accept( 80), objs - visit( 5125), accept(158), in result(146) 
09-04 12:13:26.982 16862 16888 I net.osmand: MapRenderRepositories BLat=48.39271278381348, TLat=48.395457077026364, LLong=-4.4969377517700195, RLong=-4.494502544403076, zoom=20
09-04 12:13:26.982 16862 16888 I net.osmand: MapRenderRepositories Native search: 39 ms 
09-04 12:13:26.989 16862 16888 I net.osmand:native: Creating SkBitmap in native w:1800 h:2772 s:3600 f:4!
09-04 12:13:26.989 16862 16888 I net.osmand:native: Row bytes for RGB_565 is 3600
09-04 12:13:26.989 16862 16888 I net.osmand:native: Locked 9979200 bytes at 0x57dbb00c
09-04 12:13:26.989 16862 16888 I net.osmand:native: Initializing rendering
09-04 12:13:26.990 16862 16888 I net.osmand:native: Rendering image
09-04 12:13:28.536 16862 16888 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 16888 (Loader map obje)
09-04 12:13:28.536   207   207 W         : debuggerd: handling request: pid=16862 uid=10077 gid=10077 tid=16888
09-04 12:13:28.577  1439  1439 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-04 12:13:28.577  1439  1439 F DEBUG   : LineageOS Version: '14.1-20170828-NIGHTLY-bacon'
09-04 12:13:28.577  1439  1439 F DEBUG   : Build fingerprint: 'oneplus/bacon/A0001:6.0.1/MHC19Q/ZNH2KAS1KN:user/release-keys'
09-04 12:13:28.577  1439  1439 F DEBUG   : Revision: '0'
09-04 12:13:28.577  1439  1439 F DEBUG   : ABI: 'arm'
09-04 12:13:28.577  1439  1439 F DEBUG   : pid: 16862, tid: 16888, name: Loader map obje  >>> net.osmand.plus <<<
09-04 12:13:28.578  1439  1439 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
09-04 12:13:28.581  1439  1439 F DEBUG   :     r0 00000000  r1 000041f8  r2 00000006  r3 00000008
09-04 12:13:28.581  1439  1439 F DEBUG   :     r4 8261f978  r5 00000006  r6 8261f920  r7 0000010c
09-04 12:13:28.581  1439  1439 F DEBUG   :     r8 8261dde8  r9 8261de7c  sl 8261da10  fp 8261da50
09-04 12:13:28.581  1439  1439 F DEBUG   :     ip 0000000c  sp 8261d960  lr b52a4107  pc b52a6970  cpsr 600f0010
09-04 12:13:28.599  1439  1439 F DEBUG   : 
09-04 12:13:28.599  1439  1439 F DEBUG   : backtrace:
09-04 12:13:28.599  1439  1439 F DEBUG   :     #00 pc 0004a970  /system/lib/libc.so (tgkill+12)
09-04 12:13:28.600  1439  1439 F DEBUG   :     #01 pc 00048103  /system/lib/libc.so (pthread_kill+34)
09-04 12:13:28.600  1439  1439 F DEBUG   :     #02 pc 0001d715  /system/lib/libc.so (raise+10)
09-04 12:13:28.600  1439  1439 F DEBUG   :     #03 pc 00019261  /system/lib/libc.so (__libc_android_abort+34)
09-04 12:13:28.600  1439  1439 F DEBUG   :     #04 pc 00017128  /system/lib/libc.so (abort+4)
09-04 12:13:28.600  1439  1439 F DEBUG   :     #05 pc 0020b91c  /data/app/net.osmand.plus-1/lib/arm/libosmand.so (_Z15sk_malloc_flagsjj+48)
09-04 12:13:28.600  1439  1439 F DEBUG   :     #06 pc 001278c8  /data/app/net.osmand.plus-1/lib/arm/libosmand.so (_ZN12SkChunkAlloc8newBlockEjNS_13AllocFailTypeE+40)
09-04 12:13:28.600  1439  1439 F DEBUG   :     #07 pc 00127940  /data/app/net.osmand.plus-1/lib/arm/libosmand.so (_ZN12SkChunkAlloc5allocEjNS_13AllocFailTypeE+56)
09-04 12:13:28.600  1439  1439 F DEBUG   :     #08 pc 0013742c  /data/app/net.osmand.plus-1/lib/arm/libosmand.so (_ZN13SkEdgeBuilder9buildPolyERK6SkPathPK7SkIRecti+128)
09-04 12:13:28.600  1439  1439 F DEBUG   :     #09 pc 00137aa8  /data/app/net.osmand.plus-1/lib/arm/libosmand.so (_ZN13SkEdgeBuilder5buildERK6SkPathPK7SkIRecti+756)
09-04 12:13:28.600  1439  1439 F DEBUG   :     #10 pc 00182ac0  /data/app/net.osmand.plus-1/lib/arm/libosmand.so (_Z12sk_fill_pathRK6SkPathPK7SkIRectP9SkBlitteriiiRK8SkRegion+92)
09-04 12:13:28.600  1439  1439 F DEBUG   :     #11 pc 001806b8  /data/app/net.osmand.plus-1/lib/arm/libosmand.so (_ZN6SkScan12AntiFillPathERK6SkPathRK8SkRegionP9SkBlitterb+1244)
09-04 12:13:28.600  1439  1439 F DEBUG   :     #12 pc 00180a68  /data/app/net.osmand.plus-1/lib/arm/libosmand.so (_ZN6SkScan12AntiFillPathERK6SkPathRK12SkRasterClipP9SkBlitter+244)
09-04 12:13:28.600  1439  1439 F DEBUG   :     #13 pc 001311a4  /data/app/net.osmand.plus-1/lib/arm/libosmand.so (_ZNK6SkDraw8drawPathERK6SkPathRK7SkPaintPK8SkMatrixbbP9SkBlitter+580)
09-04 12:13:28.600  1439  1439 F DEBUG   :     #14 pc 00103050  /data/app/net.osmand.plus-1/lib/arm/libosmand.so (_ZN14SkBitmapDevice8drawPathERK6SkDrawRK6SkPathRK7SkPaintPK8SkMatrixb+60)
09-04 12:13:28.600  1439  1439 F DEBUG   :     #15 pc 001240a0  /data/app/net.osmand.plus-1/lib/arm/libosmand.so (_ZN8SkCanvas10onDrawPathERK6SkPathRK7SkPaint+692)
09-04 12:13:28.600  1439  1439 F DEBUG   :     #16 pc 000d3c6d  /data/app/net.osmand.plus-1/lib/arm/libosmand.so (_Z12drawPolylineP13MapDataObjectP26RenderingRuleSearchRequestP8SkCanvasP7SkPaintP16RenderingContextSt4pairISsSsEii+1952)
09-04 12:13:28.600  1439  1439 F DEBUG   :     #17 pc 000d4541  /data/app/net.osmand.plus-1/lib/arm/libosmand.so (_Z10drawObjectP16RenderingContextP8SkCanvasP26RenderingRuleSearchRequestP7SkPaintRSt6vectorI22MapDataObjectPrimitiveSaIS8_EEi+200)
09-04 12:13:28.600  1439  1439 F DEBUG   :     #18 pc 000d5cf9  /data/app/net.osmand.plus-1/lib/arm/libosmand.so (_Z11doRenderingSt6vectorIP13MapDataObjectSaIS1_EEP8SkCanvasP26RenderingRuleSearchRequestP16RenderingContext+256)
09-04 12:13:28.600  1439  1439 F DEBUG   :     #19 pc 000f9a8f  /data/app/net.osmand.plus-1/lib/arm/libosmand.so (Java_net_osmand_plus_render_NativeOsmandLibrary_generateRenderingDirect+446)
09-04 12:13:28.600  1439  1439 F DEBUG   :     #20 pc 011a4e17  /data/app/net.osmand.plus-1/oat/arm/base.odex (offset 0x1020000)
09-04 12:13:29.091   207   207 W         : debuggerd: resuming target 16862
09-04 12:13:29.095  5009  5098 I BootReceiver: Copying /data/tombstones/tombstone_03 to DropBox (SYSTEM_TOMBSTONE)
09-04 12:13:29.102  5009  1445 W ActivityManager:   Force finishing activity net.osmand.plus/.activities.MapActivity
09-04 12:13:29.163  5009  8501 I OpenGLRenderer: Initialized EGL, version 1.4
09-04 12:13:29.163  5009  8501 D OpenGLRenderer: Swap behavior 1
09-04 12:13:29.212  5009  7094 D GnssStatusListenerHelper: Remote Listener died: android.location.IGnssStatusListener$Stub$Proxy@a32e346
09-04 12:13:29.212  5009  7094 I WindowManager: WIN DEATH: Window{69cf94e u0 SurfaceView - net.osmand.plus/net.osmand.plus.activities.MapActivity}
09-04 12:13:29.212  5009  7137 D GraphicsStats: Buffer count: 17
09-04 12:13:29.212  5009 15956 I ActivityManager: Process net.osmand.plus (pid 16862) has died
09-04 12:13:29.212  5009 15956 D ActivityManager: cleanUpApplicationRecord -- 16862
09-04 12:13:29.215  5009  7137 I WindowManager: WIN DEATH: Window{3c5537f u0 net.osmand.plus/net.osmand.plus.activities.MapActivity}
09-04 12:13:29.233  3686  3686 I Zygote  : Process 16862 exited due to signal (6)
09-04 12:13:29.812  7113  7247 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
09-04 12:13:30.138  5009  5043 I UsageStatsService: User[0] Flushing usage stats to disk
```

**Comment by DamienCassou** [comment]
@vshcherb: where can I find 'exception.log'? I've tried in '/sdcard/Android/data/net.osmand.plus'

**Comment by DamienCassou** [comment]
I was in Brest last week and I can confirm that osmand is completely unusable there. That is a shame because I can't live without it anymore :-).

**Comment by vshcherb** [comment]
It looks like it is C++ crash, sometimes reinstalls help to solve the issue.

**Comment by DamienCassou** [comment]
@vshcherb: as explained in my first message, the problem happens with 2 different versions of Osmand. Do you still think I should try reinstalling?

**Comment by vshcherb** [comment]
Just downloaded france brittany . If your issue across your devices it will be easy for us to reproduce. No crash so far

**Comment by DamienCassou** [comment]
I have been able to reproduce the problems several times on a OnePlus1 with LineageOS nightly and on a OnePlus3T with up-to-date official rom (OxygenOS 4.1.6).

However, I have *not* been able to reproduce on a Sony XPeria Tablet with up-to-date official rom (5.1.1).

To reproduce, go to maximum zoom level in the city center of Brest, Brittany. Then, move the map a lot in all directions, sometimes zooming out and zooming back to maximum. In less than a minute you should crash the application.

**Comment by vshcherb** [comment]
OnePlus2 tested for 5 minutes Brest couldn't reproduce. I believe it is a genuine bug if you could possible record a screen it could help to understand it faster. 

Unfortunately as I see a crash we may not be able to fix it cause it is 3rd party library crash. It is possible crash related to a certain position

**Comment by DamienCassou** [comment]
> record a screen

do you mean screen capture?

> we may not be able to fix it cause it is 3rd party library crash

if you need, I can build the application and its dependencies with debugging symbols and more logs. If you are interested, can you please guide me?

**Comment by DamienCassou** [comment]
I can still reproduce the issue with newest osmand. Can you please help me? I'm moving to this city in a few weeks and can't live without osmand.

**Comment by DamienCassou** [comment]
>  it is 3rd party library crash

which library?

**Comment by DamienCassou** [comment]
I now leave in Brest and can't use osmand anymore :-(.

**Comment by hvellyr** [comment]
I can see the crash; for me reliably reproducible whenever zooming in in the area of Crozon (south of Brest).

**Comment by SpcCw** [comment]
Similar crash in Prague :(

I don't think it was there about six months ago.

How to reproduce: find Praha by search, "show on map" so it centers on the city centre. Then start zooming in allowing the map to render between each zoom. Somewhere in the middle range of zoom it crashes. If zooming really fast to the maximum or minimum level before it can render the map - it seems stable unless you zoom in/out again... The problem is that when you search for something it usually shows the place in the problematic zoom range and crashes :( It is about 7 zoom level if counting from the maximum zoom and zooming out.

Tested on two devices (Note 4, Oukitel K10000Max), different Android versions (6 and 7), tried clearing cache, wiping app data, clean reinstall...

If it persists OSMAnd will be unusable in the area :(

**Comment by twitwi** [comment]
We have the same problem here, in many places, on different devices. Currently in Dublin, if we look for "Address > Dublin > Show on map" and then zoom, we get a crash. Devices include Lenovo K6 (android 7.0) and Samsung A5, both somewhat low-end decent phones.

**Workaround**: although not totally satisfactory visually, switching to "safe mode" prevents the crash for now. This can be done in "parameters > general parameter".

Here are the logs, of the crash that happens in the native library:

~~~
--------- beginning of crash
09-10 16:41:28.096 30151 30175 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x8b380000 in tid 30175 (Loader map obje)
09-10 16:41:28.098   387   387 W         : debuggerd: handling request: pid=30151 uid=10338 gid=10338 tid=30175
09-10 16:41:28.116 32068 32068 W debuggerd: type=1400 audit(0.0:33309): avc: denied { search } for name="expand" dev="tmpfs" ino=12322 scontext=u:r:debuggerd:s0 tcontext=u:object_r:mnt_expand_file:s0 tclass=dir permissive=0
09-10 16:41:28.126 32068 32068 W debuggerd: type=1400 audit(0.0:33310): avc: denied { search } for name="expand" dev="tmpfs" ino=12322 scontext=u:r:debuggerd:s0 tcontext=u:object_r:mnt_expand_file:s0 tclass=dir permissive=0
09-10 16:41:28.126 32068 32068 W debuggerd: type=1400 audit(0.0:33311): avc: denied { search } for name="expand" dev="tmpfs" ino=12322 scontext=u:r:debuggerd:s0 tcontext=u:object_r:mnt_expand_file:s0 tclass=dir permissive=0
09-10 16:41:28.291 32068 32068 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-10 16:41:28.292 32068 32068 F DEBUG   : Build fingerprint: 'Lenovo/karate/K33a48:7.0/NRD90N/K33_S223_170610_ROW:user/release-keys'
09-10 16:41:28.292 32068 32068 F DEBUG   : Revision: '0'
09-10 16:41:28.292 32068 32068 F DEBUG   : ABI: 'arm'
09-10 16:41:28.292 32068 32068 F DEBUG   : pid: 30151, tid: 30175, name: Loader map obje  >>> net.osmand.plus <<<
09-10 16:41:28.292 32068 32068 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8b380000
09-10 16:41:28.276 32068 32068 W debuggerd: type=1400 audit(0.0:33312): avc: denied { search } for name="expand" dev="tmpfs" ino=12322 scontext=u:r:debuggerd:s0 tcontext=u:object_r:mnt_expand_file:s0 tclass=dir permissive=0
09-10 16:41:28.292 32068 32068 F DEBUG   :     r0 8b178a00  r1 0000c49c  r2 0000c49c  r3 0002b47e
09-10 16:41:28.292 32068 32068 F DEBUG   :     r4 00000000  r5 00000020  r6 00000000  r7 8b37fffc
09-10 16:41:28.292 32068 32068 F DEBUG   :     r8 886f6de4  r9 00000000  sl 00000010  fp a7b2a330
09-10 16:41:28.292 32068 32068 F DEBUG   :     ip ff000000  sp 93cfe5bc  lr 9311d3cc  pc 93123f90  cpsr 80070010
09-10 16:41:28.326 32068 32068 F DEBUG   : 
09-10 16:41:28.326 32068 32068 F DEBUG   : backtrace:
09-10 16:41:28.326 32068 32068 F DEBUG   :     #00 pc 002f1f90  /mnt/expand/798da9e0-8cfd-4239-9706-f834eba19b43/app/net.osmand.plus-1/lib/arm/libosmand.so
09-10 16:41:28.326 32068 32068 F DEBUG   :     #01 pc 002eb3c8  /mnt/expand/798da9e0-8cfd-4239-9706-f834eba19b43/app/net.osmand.plus-1/lib/arm/libosmand.so
09-10 16:41:28.326 32068 32068 F DEBUG   :     #02 pc 002d948c  /mnt/expand/798da9e0-8cfd-4239-9706-f834eba19b43/app/net.osmand.plus-1/lib/arm/libosmand.so
09-10 16:41:28.326 32068 32068 F DEBUG   :     #03 pc 002ac8c4  /mnt/expand/798da9e0-8cfd-4239-9706-f834eba19b43/app/net.osmand.plus-1/lib/arm/libosmand.so
09-10 16:41:28.326 32068 32068 F DEBUG   :     #04 pc 002ac150  /mnt/expand/798da9e0-8cfd-4239-9706-f834eba19b43/app/net.osmand.plus-1/lib/arm/libosmand.so
09-10 16:41:28.316 32068 32068 W debuggerd: type=1400 audit(0.0:33313): avc: denied { search } for name="expand" dev="tmpfs" ino=12322 scontext=u:r:debuggerd:s0 tcontext=u:object_r:mnt_expand_file:s0 tclass=dir permissive=0
09-10 16:41:28.326 32068 32068 F DEBUG   :     #05 pc 001e2e38  /mnt/expand/798da9e0-8cfd-4239-9706-f834eba19b43/app/net.osmand.plus-1/lib/arm/libosmand.so
09-10 16:41:28.326 32068 32068 F DEBUG   :     #06 pc 0019fdc4  /mnt/expand/798da9e0-8cfd-4239-9706-f834eba19b43/app/net.osmand.plus-1/lib/arm/libosmand.so
09-10 16:41:28.326 32068 32068 F DEBUG   :     #07 pc 001b1058  /mnt/expand/798da9e0-8cfd-4239-9706-f834eba19b43/app/net.osmand.plus-1/lib/arm/libosmand.so
09-10 16:41:28.326 32068 32068 F DEBUG   :     #08 pc 001afc0c  /mnt/expand/798da9e0-8cfd-4239-9706-f834eba19b43/app/net.osmand.plus-1/lib/arm/libosmand.so
09-10 16:41:28.326 32068 32068 F DEBUG   :     #09 pc 001ae560  /mnt/expand/798da9e0-8cfd-4239-9706-f834eba19b43/app/net.osmand.plus-1/lib/arm/libosmand.so
09-10 16:41:28.326 32068 32068 F DEBUG   :     #10 pc 002b0d70  /mnt/expand/798da9e0-8cfd-4239-9706-f834eba19b43/app/net.osmand.plus-1/lib/arm/libosmand.so
09-10 16:41:28.326 32068 32068 F DEBUG   :     #11 pc 002afd14  /mnt/expand/798da9e0-8cfd-4239-9706-f834eba19b43/app/net.osmand.plus-1/lib/arm/libosmand.so
09-10 16:41:28.326 32068 32068 F DEBUG   :     #12 pc 000ff27f  /mnt/expand/798da9e0-8cfd-4239-9706-f834eba19b43/app/net.osmand.plus-1/lib/arm/libosmand.so
09-10 16:41:28.326 32068 32068 F DEBUG   :     #13 pc 00101b07  /mnt/expand/798da9e0-8cfd-4239-9706-f834eba19b43/app/net.osmand.plus-1/lib/arm/libosmand.so
09-10 16:41:28.326 32068 32068 F DEBUG   :     #14 pc 0010766d  /mnt/expand/798da9e0-8cfd-4239-9706-f834eba19b43/app/net.osmand.plus-1/lib/arm/libosmand.so
09-10 16:41:28.327 32068 32068 F DEBUG   :     #15 pc 0014f0a9  /mnt/expand/798da9e0-8cfd-4239-9706-f834eba19b43/app/net.osmand.plus-1/lib/arm/libosmand.so
09-10 16:41:28.327 32068 32068 F DEBUG   :     #16 pc 0013dc97  /mnt/expand/798da9e0-8cfd-4239-9706-f834eba19b43/app/net.osmand.plus-1/oat/arm/base.odex (offset 0x1524000)
~~~

**Comment by DamienCassou** [comment]
I can still reproduce on my One+ 1 (bacon), with LineageOS 16.0 (android v9) and OSMand 3.3.5 from fdroid.

**Comment by Bibi56** [comment]
@DamienCassou try 3.4.4 on fdroid. No problem in Brest or Crozon (but neither with older versions). Try changing the style, could be the issue. There you should use Nautical Maps ;-).

**Comment by DamienCassou** [comment]
Bibi56 <notifications@github.com> writes:
> @DamienCassou try 3.4.4 on fdroid. No problem in Brest or Crozon (but
> neither with older versions). Try changing the style, could be the
> issue. There you should use Nautical Maps ;-).

It seems that Osmand does not crash anymore! Awesome.

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by vshcherb** [comment]
Should be fixed with opengl

**Comment by DamienCassou** [comment]
@vshcherb Which release contains the fix? Do I have to setup anything? I reproduced the bug again yesterday.

**Comment by vshcherb** [comment]
4.5.9 should have the fix
