### ISSUE TITLE
Crash at net.osmand.search.core.CustomSearchPoiFilter.getName() on a null object reference

### ISSUE THREAD

**Issue by ShinIce** [osmandapp/Osmand#4024]
Hi,

I made for myself an obf file with custom geocache pois and added the category also to the poi_types.xml (attached). All is working fine with this kind of poi, but performing a search from the magnifying glass or even from the dashboard leads me to an instant crash (attached).

Does anyone has an idea how I can fix this?

 ```
<poi_category name="geocache" default_tag="geocache" top="true">
			<poi_type name="geocache" tag="geocache" value="found"/>
                 <poi_type name="geocache" tag="geocache" value=""/>
 </poi_category>


Version  OsmAnd+ 2.6.5
03.07.2017 5:12:29
Apk Version : 2.6.5 265
Exception occured in thread Thread[main,5,main] :
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String net.osmand.search.core.CustomSearchPoiFilter.getName()' on a null object reference
        at net.osmand.search.core.SearchCoreFactory$SearchAmenityTypesAPI.search(SearchCoreFactory.java:646)
        at net.osmand.search.SearchUICore.shallowSearch(SearchUICore.java:258)
        at net.osmand.plus.search.QuickSearchDialogFragment.reloadCategoriesInternal(QuickSearchDialogFragment.java:1097)
        at net.osmand.plus.search.QuickSearchDialogFragment.reloadCategories(QuickSearchDialogFragment.java:1090)
        at net.osmand.plus.search.QuickSearchDialogFragment.onSearchListFragmentResume(QuickSearchDialogFragment.java:1041)
        at net.osmand.plus.search.QuickSearchListFragment.onResume(QuickSearchListFragment.java:165)
        at android.support.v4.app.Fragment.performResume(Fragment.java:2020)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1107)
        at android.support.v4.app.FragmentManagerImpl.performPendingDeferredStart(FragmentManager.java:926)
        at android.support.v4.app.FragmentManagerImpl.startPendingDeferredFragments(FragmentManager.java:1276)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1634)
        at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
        at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1025)
        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1545)
        at android.view.View.measure(View.java:19861)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:911)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
        at android.view.View.measure(View.java:19861)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
        at android.view.View.measure(View.java:19861)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:19861)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:19861)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
        at android.view.View.measure(View.java:19861)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:689)
        at android.view.View.measure(View.java:19861)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2275)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1366)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1619)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6343)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
        at android.view.Choreographer.doFrame(Choreographer.java:621)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by AlexSyt** [comment]
Commit 5d5bb6c - is mistake. This commit does not relate to this issue.

**Comment by AlexSyt** [comment]
@ShinIce Hi,

Can you please send the full poi_types.xml that you modified?

**Comment by ShinIce** [comment]
@AlexSyt for sure :)

I only needed to rename it from xml to txt, looks like github don't like xml files :smile: 

[poi_types.txt](https://github.com/osmandapp/Osmand/files/1131573/poi_types.txt)

**Comment by AlexSyt** [comment]
@ShinIce good morning :)

Try to use this file, with it everything should work)

[poi_types.txt](https://github.com/osmandapp/Osmand/files/1134815/poi_types.txt)

**Comment by ShinIce** [comment]
@AlexSyt hi :)

Oh, well, awesome :D Works like a charm.
I can't diff the files right now, can you maybe explain what the problem was?

Thank you ;)

**Comment by AlexSyt** [comment]
@ShinIce,

You had the old version of poi_types.xml :)

**Comment by ShinIce** [comment]
@AlexSyt oh damn, this is bad :cry: 
It worked for long time with the same file and I didn't thought that this could be the problem.

Thank you for the hint :beers:  I think we can close it now, or is it still needed for 2.7.0?

**Comment by AlexSyt** [comment]
@ShinIce, you are welcome)

Yes, you can close it.
