### ISSUE TITLE
App crashes when tapping on menu items

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#4109]
App crashes when tapping on menu items:
Dashboard, My Places, 

No crashes on:
Map markers, Search, Legacy Search, Config Map

```
Version  OsmAnd~ 2.7.0#22051M
14.07.2017 12:23:52
Apk Version : 2.7.0#22051M 270
Exception occured in thread Thread[main,5,main] : 
android.database.sqlite.SQLiteException: no such column: splitType (code 1): , while compiling: SELECT fileName, fileDir,totalDistance, totalTracks, startTime, endTime, timeSpan, timeMoving, totalDistanceMoving, diffElevationUp, diffElevationDown, avgElevation, minElevation, maxElevation, maxSpeed, avgSpeed, points, wptPoints, color, fileLastModifiedTime, splitType, splitInterval FROM gpxTable
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
	at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1255)
	at net.osmand.plus.api.SQLiteAPIImpl$SQLiteDatabaseWrapper.rawQuery(SQLiteAPIImpl.java:48)
	at net.osmand.plus.GPXDatabase.getItems(GPXDatabase.java:444)
	at net.osmand.plus.myplaces.AvailableGPXFragment$ProcessGpxTask.<init>(AvailableGPXFragment.java:1538)
	at net.osmand.plus.myplaces.AvailableGPXFragment.onResume(AvailableGPXFragment.java:189)
	at android.support.v4.app.Fragment.performResume(Fragment.java:2294)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1387)
	at android.support.v4.app.FragmentManagerImpl.performPendingDeferredStart(FragmentManager.java:1168)
	at android.support.v4.app.FragmentManagerImpl.startPendingDeferredFragments(FragmentManager.java:1673)
	at android.support.v4.app.FragmentManagerImpl.doPendingDeferredStart(FragmentManager.java:2520)
	at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2040)
	at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626)
	at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:166)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
	at android.view.View.measure(View.java:18805)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:18805)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:901)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
	at android.view.View.measure(View.java:18805)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
	at android.view.View.measure(View.java:18805)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
	at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:393)
	at android.view.View.measure(View.java:18805)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:18805)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
	at android.view.View.measure(View.java:18805)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
	at android.view.View.measure(View.java:18805)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1216)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
	at android.view.Choreographer.doFrame(Choreographer.java:606)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by polarbearing** [comment]
OsmAnd-master-nb-2017-07-12.apk #22039M seems to work. 
2017-07-13, 2.7.0#22048M (midday) and 2.7.0#22051M (evening) crash.

**Comment by dmpr0** [comment]
Hi, thank you for crash log, we can't reproduce it, please try to download fresh nightly. Let's me now if something change.

**Comment by polarbearing** [comment]
Installing OsmAnd-master-nb-2017-07-14.apk 18:05 #22066M
No crash so far.
