### ISSUE TITLE
GPX track "Analyze on map" leads to crash

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#4168]
OsmAnd+ 2.7.0

Tapping on "Analyze on map" for any GPX track leads to an immediate crash:

```
Exception occured in thread Thread[main,5,main] : 
java.lang.RuntimeException: Unable to resume activity {net.osmand.plus/net.osmand.plus.activities.MapActivity}: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3137)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3168)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1407)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
	at java.util.ArrayList.get(ArrayList.java:308)
	at net.osmand.plus.helpers.GpxUiHelper.createGPXSlopeDataSet(GpxUiHelper.java:1441)
	at net.osmand.plus.mapcontextmenu.other.TrackDetailsMenu.updateView(TrackDetailsMenu.java:470)
	at net.osmand.plus.mapcontextmenu.other.TrackDetailsMenu.updateInfo(TrackDetailsMenu.java:155)
	at net.osmand.plus.mapcontextmenu.other.TrackDetailsMenuFragment.updateInfo(TrackDetailsMenuFragment.java:128)
	at net.osmand.plus.mapcontextmenu.other.TrackDetailsMenuFragment.onCreateView(TrackDetailsMenuFragment.java:72)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2248)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1340)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1569)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1636)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2415)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2201)
	at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2155)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2064)
	at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:379)
	at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:499)
	at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
	at android.app.Activity.performResume(Activity.java:6351)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3126)
	... 8 more
```

Seems to happen only in the "my tracks" activity when using the little menu right nex to a track. Doesn't happen when opening a track and tapping on the "Analyze on map" button in the lower right corner.

**Comment by scaidermern** [comment]
Please reopen. OsmAnd 2.7.1 still crashes, now with a different exception:

```
Version  OsmAnd+ 2.7.1
Apk Version : 2.7.1 271
Exception occured in thread Thread[main,5,main] : 
java.lang.RuntimeException: Unable to resume activity {net.osmand.plus/net.osmand.plus.activities.MapActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int net.osmand.plus.GPXUtilities$TrkSegment.getColor(int)' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3137)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3168)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1407)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int net.osmand.plus.GPXUtilities$TrkSegment.getColor(int)' on a null object reference
	at net.osmand.plus.mapcontextmenu.other.TrackDetailsMenu.refreshChart(TrackDetailsMenu.java:308)
	at net.osmand.plus.mapcontextmenu.other.TrackDetailsMenu.updateView(TrackDetailsMenu.java:595)
	at net.osmand.plus.mapcontextmenu.other.TrackDetailsMenu.updateInfo(TrackDetailsMenu.java:155)
	at net.osmand.plus.mapcontextmenu.other.TrackDetailsMenuFragment.updateInfo(TrackDetailsMenuFragment.java:128)
	at net.osmand.plus.mapcontextmenu.other.TrackDetailsMenuFragment.onCreateView(TrackDetailsMenuFragment.java:72)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2248)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1340)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1569)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1636)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2415)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2201)
	at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2155)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2064)
	at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:379)
	at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:499)
	at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
	at android.app.Activity.performResume(Activity.java:6351)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3126)
	... 8 more
```

**Comment by crimean** [comment]
@scaidermern please send us single gpx file where crash happens.

**Comment by scaidermern** [comment]
The failing gpx track: [fail.gpx.txt](https://github.com/osmandapp/Osmand/files/1175839/fail.gpx.txt)

The crash doesn't occur with this one: [good.gpx.txt](https://github.com/osmandapp/Osmand/files/1175845/good.gpx.txt)

The most notable difference between those two tracks is that the first one is significantly larger, thus taking longer to load.

**Comment by scaidermern** [comment]
Works now 👍
