### ISSUE TITLE
OsmAnd+ 2.8.2 crashes everytime in "places"

### ISSUE THREAD

**Issue by bumbaras** [osmandapp/Osmand#4758]
OsmAnd+ for android. Updated from previous version.
Menu\Places. Now, when I click "+" on bottom of screen the app is crashing. I have never used this "+" function before so I don't know if it worked before.
On next run the app is asking me to send crash report. I give Yes and i have to choose the folder to save exception.log. But after that I got error message: "Error of opening file: src".

**Comment by dmpr0** [comment]
Hi, thank you for feedback!
What version of Android do you have? I think it cause because OsmAnd doesn't have permission for memory.

**Comment by bumbaras** [comment]
Version of Android? The best one for me :). It is 4.1.2. And I pointed to save exception.log to sdcard0 (the builtin). In this version there are no restriction to save to sdcard.

**Comment by bumbaras** [comment]
Last entries from exception.log from data folder - device is rooted so there is no issue to get there:
15.11.2017 5:53:30
Apk Version : 2.8.2 282
Exception occured in thread Thread[main,5,main] : 
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT typ=*/* }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1545)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1416)
	at android.app.Activity.startActivityForResult(Activity.java:3351)
	at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:67)
	at android.app.Activity.startActivityForResult(Activity.java:3312)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:720)
	at net.osmand.plus.myplaces.FavoritesActivity.importFavourites(FavoritesActivity.java:97)
	at net.osmand.plus.activities.FavoritesTreeFragment.importFavourites(FavoritesTreeFragment.java:538)
	at net.osmand.plus.activities.FavoritesTreeFragment.onOptionsItemSelected(FavoritesTreeFragment.java:290)
	at net.osmand.plus.base.OsmandExpandableListFragment$1.onMenuItemClick(OsmandExpandableListFragment.java:92)
	at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:167)
	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:963)
	at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)
	at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:150)
	at android.view.View.performClick(View.java:4171)
	at android.view.View$PerformClick.run(View.java:17195)
	at android.os.Handler.handleCallback(Handler.java:643)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4803)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by bumbaras** [comment]
Is something new about fix for crashes?

**Comment by vshcherb** [comment]
+ is for Importing GPX file, as I see from stack trace it is Android issue. Though it needs to be investigated further possibly it doesn't have permission but in any case it should not crash.

**Comment by bumbaras** [comment]
I made a clean install (cleared data, cache, then uninstall).
That way I got a possibility to import places. Crash everytime when import button pressed.
I don't know if it worked before 2.8.2, never use any of them (nor plus nor import functions).
I can set any permission so which file should get 777?

**Comment by PavelRatushnyi** [comment]
This import feature is supported only on Android 4.4+, so "+" buttons shouldn't be visible for unsupported versions of Android.

**Comment by bumbaras** [comment]
What is so special in "import" function that it can't work under 4.1? Really?
I suspect I can just put .gpx file in proper place to make it work as sideload.
Is "plus" for import? I was thinking it is to add additional tags for saved places.

**Comment by PavelRatushnyi** [comment]
Yes, "plus" is for import from file storage.
You could try importing track or favourites via this button in our latest nightly, but maybe you will need to place gpx file to downloads folder or in file storage dialog select option "show another devices" (or something like that), it depens on device. Hope this will help you:)
