### ISSUE TITLE
import map Could not read input channel file descriptors from parcel.

### ISSUE THREAD

**Issue by sazearte** [osmandapp/Osmand#4782]
I try to import all map but osmand crash all the time
It's crash in random file, my all maps is not corrupt.

this is log :
```
Version  OsmAnd 2.8.2
19.11.2017 10:44:09
Apk Version : 2.8.2 282
Exception occured in thread Thread[main,5,main] : 
java.lang.RuntimeException: Could not read input channel file descriptors from parcel.
	at android.view.InputChannel.nativeReadFromParcel(Native Method)
	at android.view.InputChannel.readFromParcel(InputChannel.java:148)
	at android.view.InputChannel$1.createFromParcel(InputChannel.java:39)
	at android.view.InputChannel$1.createFromParcel(InputChannel.java:36)
	at com.android.internal.view.InputBindResult.<init>(InputBindResult.java:62)
	at com.android.internal.view.InputBindResult$1.createFromParcel(InputBindResult.java:102)
	at com.android.internal.view.InputBindResult$1.createFromParcel(InputBindResult.java:99)
	at com.android.internal.view.IInputMethodManager$Stub$Proxy.windowGainedFocus(IInputMethodManager.java:712)
	at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1169)
	at android.view.inputmethod.InputMethodManager.onWindowFocus(InputMethodManager.java:1370)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3172)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5019)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
	at dalvik.system.NativeStart.main(Native Method)
Version  OsmAnd 2.8.2
19.11.2017 10:44:09
Apk Version : 2.8.2 282
Exception occured in thread Thread[main,5,main] : 
java.lang.RuntimeException: Could not read input channel file descriptors from parcel.
	at android.view.InputChannel.nativeReadFromParcel(Native Method)
	at android.view.InputChannel.readFromParcel(InputChannel.java:148)
	at android.view.InputChannel$1.createFromParcel(InputChannel.java:39)
	at android.view.InputChannel$1.createFromParcel(InputChannel.java:36)
	at com.android.internal.view.InputBindResult.<init>(InputBindResult.java:62)
	at com.android.internal.view.InputBindResult$1.createFromParcel(InputBindResult.java:102)
	at com.android.internal.view.InputBindResult$1.createFromParcel(InputBindResult.java:99)
	at com.android.internal.view.IInputMethodManager$Stub$Proxy.windowGainedFocus(IInputMethodManager.java:712)
	at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1169)
	at android.view.inputmethod.InputMethodManager.onWindowFocus(InputMethodManager.java:1370)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3172)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5019)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
	at dalvik.system.NativeStart.main(Native Method)
Version  OsmAnd 2.8.2
19.11.2017 11:11:27
Apk Version : 2.8.2 282
Exception occured in thread Thread[main,5,main] : 
java.lang.RuntimeException: Could not read input channel file descriptors from parcel.
	at android.view.InputChannel.nativeReadFromParcel(Native Method)
	at android.view.InputChannel.readFromParcel(InputChannel.java:148)
	at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:690)
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:505)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:259)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
	at android.widget.Toast$TN.handleShow(Toast.java:405)
	at android.widget.Toast$TN$1.run(Toast.java:313)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5019)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
	at dalvik.system.NativeStart.main(Native Method)
Version  OsmAnd 2.8.2
19.11.2017 11:11:27
Apk Version : 2.8.2 282
Exception occured in thread Thread[main,5,main] : 
java.lang.RuntimeException: Could not read input channel file descriptors from parcel.
	at android.view.InputChannel.nativeReadFromParcel(Native Method)
	at android.view.InputChannel.readFromParcel(InputChannel.java:148)
	at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:690)
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:505)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:259)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
	at android.widget.Toast$TN.handleShow(Toast.java:405)
	at android.widget.Toast$TN$1.run(Toast.java:313)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5019)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
	at dalvik.system.NativeStart.main(Native Method)
Version  OsmAnd 2.8.2
19.11.2017 11:27:11
Apk Version : 2.8.2 282
Exception occured in thread Thread[main,5,main] : 
java.lang.RuntimeException: Could not read input channel file descriptors from parcel.
	at android.view.InputChannel.nativeReadFromParcel(Native Method)
	at android.view.InputChannel.readFromParcel(InputChannel.java:148)
	at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:690)
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:505)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:259)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
	at android.widget.Toast$TN.handleShow(Toast.java:405)
	at android.widget.Toast$TN$1.run(Toast.java:313)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5019)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
	at dalvik.system.NativeStart.main(Native Method)

```

**Comment by vshcherb** [comment]
You can't import maps today, you need to either download them from the app or copy to the proper folder.
