### ISSUE TITLE
OsmAndCore-sample launching issue

### ISSUE THREAD

**Issue by hamzabm** [osmandapp/Osmand#4815]
whene i try to run the application OsmAndCore-sample, l'application install but the app is craching after 2 second

this is the logcat : 

E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: net.osmand.core.samples.android.sample1, PID: 19821
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{net.osmand.core.samples.android.sample1/net.osmand.core.samples.android.sample1.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.drawable.Drawable.getIntrinsicWidth()' on a null object reference
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2434)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:157)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5551)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.drawable.Drawable.getIntrinsicWidth()' on a null object reference
                                                       at net.osmand.core.samples.android.sample1.MainActivity.initMapMarkers(MainActivity.java:356)
                                                       at net.osmand.core.samples.android.sample1.MainActivity.onCreate(MainActivity.java:300)
                                                       at android.app.Activity.performCreate(Activity.java:6272)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:157) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5551) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)

**Comment by hamzabm** [comment]
more logs : 

12-04 11:07:37.000 13710-13710/? E/net.osmand: MapRenderingTypes Unexpected error
                                               java.lang.IllegalArgumentException: is == null
                                                   at org.kxml2.io.KXmlParser.setInput(KXmlParser.java:1636)
                                                   at net.osmand.osm.MapPoiTypes.initFromInputStream(MapPoiTypes.java:312)
                                                   at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:289)
                                                   at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:275)
                                                   at net.osmand.osm.MapPoiTypes.getDefault(MapPoiTypes.java:75)
                                                   at net.osmand.binary.BinaryMapPoiReaderAdapter.<init>(BinaryMapPoiReaderAdapter.java:103)
                                                   at net.osmand.binary.BinaryMapIndexReader.<init>(BinaryMapIndexReader.java:128)
                                                   at net.osmand.map.OsmandRegions.prepareFile(OsmandRegions.java:97)
                                                   at net.osmand.core.samples.android.sample1.SampleApplication.indexRegionsBoundaries(SampleApplication.java:137)
                                                   at net.osmand.core.samples.android.sample1.SampleApplication.onCreate(SampleApplication.java:78)
                                                   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5885)
                                                   at android.app.ActivityThread.-wrap3(ActivityThread.java)
                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1703)
                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                   at android.os.Looper.loop(Looper.java:154)
                                                   at android.app.ActivityThread.main(ActivityThread.java:6692)
                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
12-04 11:07:37.001 13710-13710/? E/net.osmand: MapRenderingTypes Unexpected error
                                               java.lang.IllegalArgumentException: is == null
                                                   at org.kxml2.io.KXmlParser.setInput(KXmlParser.java:1636)
                                                   at net.osmand.osm.MapPoiTypes.initFromInputStream(MapPoiTypes.java:312)
                                                   at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:289)
                                                   at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:275)
                                                   at net.osmand.osm.MapPoiTypes.getDefault(MapPoiTypes.java:75)
                                                   at net.osmand.binary.BinaryMapPoiReaderAdapter.<init>(BinaryMapPoiReaderAdapter.java:103)
                                                   at net.osmand.binary.BinaryMapIndexReader.<init>(BinaryMapIndexReader.java:128)
                                                   at net.osmand.map.OsmandRegions.prepareFile(OsmandRegions.java:97)
                                                   at net.osmand.core.samples.android.sample1.SampleApplication.indexRegionsBoundaries(SampleApplication.java:137)
                                                   at net.osmand.core.samples.android.sample1.SampleApplication.onCreate(SampleApplication.java:78)
                                                   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5885)
                                                   at android.app.ActivityThread.-wrap3(ActivityThread.java)
                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1703)
                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                   at android.os.Looper.loop(Looper.java:154)
                                                   at android.app.ActivityThread.main(ActivityThread.java:6692)
                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
12-04 11:07:37.007 13710-13710/? E/net.osmand: MapRenderingTypes Unexpected error
                                               java.lang.IllegalArgumentException: is == null
                                                   at org.kxml2.io.KXmlParser.setInput(KXmlParser.java:1636)
                                                   at net.osmand.osm.MapPoiTypes.initFromInputStream(MapPoiTypes.java:312)
                                                   at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:289)
                                                   at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:275)
                                                   at net.osmand.core.samples.android.sample1.SampleApplication.initPoiTypes(SampleApplication.java:190)
                                                   at net.osmand.core.samples.android.sample1.SampleApplication.onCreate(SampleApplication.java:85)
                                                   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5885)
                                                   at android.app.ActivityThread.-wrap3(ActivityThread.java)
                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1703)
                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                   at android.os.Looper.loop(Looper.java:154)
                                                   at android.app.ActivityThread.main(ActivityThread.java:6692)
                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
12-04 11:07:37.007 13710-13710/? E/net.osmand: MapRenderingTypes Unexpected error
                                               java.lang.IllegalArgumentException: is == null
                                                   at org.kxml2.io.KXmlParser.setInput(KXmlParser.java:1636)
                                                   at net.osmand.osm.MapPoiTypes.initFromInputStream(MapPoiTypes.java:312)
                                                   at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:289)
                                                   at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:275)
                                                   at net.osmand.core.samples.android.sample1.SampleApplication.initPoiTypes(SampleApplication.java:190)
                                                   at net.osmand.core.samples.android.sample1.SampleApplication.onCreate(SampleApplication.java:85)
                                                   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5885)
                                                   at android.app.ActivityThread.-wrap3(ActivityThread.java)
                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1703)
                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                   at android.os.Looper.loop(Looper.java:154)
                                                   at android.app.ActivityThread.main(ActivityThread.java:6692)
                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
12-04 11:07:37.008 13710-13710/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: net.osmand.core.samples.android.sample1, PID: 13710
                                                   java.lang.RuntimeException: Unable to create application net.osmand.core.samples.android.sample1.SampleApplication: java.lang.IllegalArgumentException: is == null
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5888)
                                                       at android.app.ActivityThread.-wrap3(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1703)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6692)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
                                                    Caused by: java.lang.IllegalArgumentException: is == null
                                                       at org.kxml2.io.KXmlParser.setInput(KXmlParser.java:1636)
                                                       at net.osmand.osm.MapPoiTypes.initFromInputStream(MapPoiTypes.java:312)
                                                       at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:289)
                                                       at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:275)
                                                       at net.osmand.core.samples.android.sample1.SampleApplication.initPoiTypes(SampleApplication.java:190)
                                                       at net.osmand.core.samples.android.sample1.SampleApplication.onCreate(SampleApplication.java:85)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5885)
                                                       at android.app.ActivityThread.-wrap3(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1703) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6692) 
                                                       at java.lang.reflect.Method.invoke(Native Method)

**Comment by hamzabm** [comment]
any answer please ?

**Comment by AlexSyt** [comment]
Hello, I think now everything should work, try again, please :)

**Comment by hamzabm** [comment]
sorry but still have the same problem 

more logcat : 

`12-04 16:37:09.087 30847-30847/net.osmand.core.samples.android.sample1 E/net.osmand: MapRenderingTypes Unexpected error
                                                                                     java.lang.IllegalArgumentException: is == null
                                                                                         at org.kxml2.io.KXmlParser.setInput(KXmlParser.java:1634)
                                                                                         at net.osmand.osm.MapPoiTypes.initFromInputStream(MapPoiTypes.java:312)
                                                                                         at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:289)
                                                                                         at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:275)
                                                                                         at net.osmand.osm.MapPoiTypes.getDefault(MapPoiTypes.java:75)
                                                                                         at net.osmand.binary.BinaryMapPoiReaderAdapter.<init>(BinaryMapPoiReaderAdapter.java:103)
                                                                                         at net.osmand.binary.BinaryMapIndexReader.<init>(BinaryMapIndexReader.java:128)
                                                                                         at net.osmand.core.samples.android.sample1.CurrentPositionHelper.setRepositories(CurrentPositionHelper.java:55)
                                                                                         at net.osmand.core.samples.android.sample1.CurrentPositionHelper.<init>(CurrentPositionHelper.java:42)
                                                                                         at net.osmand.core.samples.android.sample1.SampleLocationProvider.<init>(SampleLocationProvider.java:94)
                                                                                         at net.osmand.core.samples.android.sample1.SampleApplication.onCreate(SampleApplication.java:72)
                                                                                         at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
                                                                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
                                                                                         at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
12-04 16:37:09.088 30847-30847/net.osmand.core.samples.android.sample1 E/net.osmand: MapRenderingTypes Unexpected error
                                                                                     java.lang.IllegalArgumentException: is == null
                                                                                         at org.kxml2.io.KXmlParser.setInput(KXmlParser.java:1634)
                                                                                         at net.osmand.osm.MapPoiTypes.initFromInputStream(MapPoiTypes.java:312)
                                                                                         at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:289)
                                                                                         at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:275)
                                                                                         at net.osmand.osm.MapPoiTypes.getDefault(MapPoiTypes.java:75)
                                                                                         at net.osmand.binary.BinaryMapPoiReaderAdapter.<init>(BinaryMapPoiReaderAdapter.java:103)
                                                                                         at net.osmand.binary.BinaryMapIndexReader.<init>(BinaryMapIndexReader.java:128)
                                                                                         at net.osmand.core.samples.android.sample1.CurrentPositionHelper.setRepositories(CurrentPositionHelper.java:55)
                                                                                         at net.osmand.core.samples.android.sample1.CurrentPositionHelper.<init>(CurrentPositionHelper.java:42)
                                                                                         at net.osmand.core.samples.android.sample1.SampleLocationProvider.<init>(SampleLocationProvider.java:94)
                                                                                         at net.osmand.core.samples.android.sample1.SampleApplication.onCreate(SampleApplication.java:72)
                                                                                         at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
                                                                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
                                                                                         at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
12-04 16:37:09.090 30847-30847/net.osmand.core.samples.android.sample1 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                         Process: net.osmand.core.samples.android.sample1, PID: 30847
                                                                                         java.lang.RuntimeException: Unable to create application net.osmand.core.samples.android.sample1.SampleApplication: java.lang.IllegalArgumentException: is == null
                                                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4710)
                                                                                             at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                          Caused by: java.lang.IllegalArgumentException: is == null
                                                                                             at org.kxml2.io.KXmlParser.setInput(KXmlParser.java:1634)
                                                                                             at net.osmand.osm.MapPoiTypes.initFromInputStream(MapPoiTypes.java:312)
                                                                                             at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:289)
                                                                                             at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:275)
                                                                                             at net.osmand.osm.MapPoiTypes.getDefault(MapPoiTypes.java:75)
                                                                                             at net.osmand.binary.BinaryMapPoiReaderAdapter.<init>(BinaryMapPoiReaderAdapter.java:103)
                                                                                             at net.osmand.binary.BinaryMapIndexReader.<init>(BinaryMapIndexReader.java:128)
                                                                                             at net.osmand.core.samples.android.sample1.CurrentPositionHelper.setRepositories(CurrentPositionHelper.java:55)
                                                                                             at net.osmand.core.samples.android.sample1.CurrentPositionHelper.<init>(CurrentPositionHelper.java:42)
                                                                                             at net.osmand.core.samples.android.sample1.SampleLocationProvider.<init>(SampleLocationProvider.java:94)
                                                                                             at net.osmand.core.samples.android.sample1.SampleApplication.onCreate(SampleApplication.java:72)
                                                                                             at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
                                                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
                                                                                             at android.app.ActivityThread.-wrap1(ActivityThread.java) 
                                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                             at android.os.Looper.loop(Looper.java:148) 
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                             at java.lang.reflect.Method.invoke(Native Method) `

**Comment by AlexSyt** [comment]
This is another problem, I'll take a look

**Comment by AlexSyt** [comment]
Can you describe the steps to repeat the problem, please?

**Comment by hamzabm** [comment]
i have downloded all the code (OsmAnd Master)  and then i have compiled it with Android studio, 
the app is building and installing perfectly, but it crach when lunching.

**Comment by AlexSyt** [comment]
It's strange, on my device everything starts without problems. I`ll take a look.

**Comment by hamzabm** [comment]
do you confirm that no steps needed before compiling and building project ?

**Comment by AlexSyt** [comment]
Did you have our main application installed during the launch of the core sample?

**Comment by hamzabm** [comment]
Yes I confirm OsmAnd is alleady installed.

**Comment by AlexSyt** [comment]
Check whether the application has access to the file system and the files of main application. 
Also check if the following files are present in the project:
1. OsmAnd/src/net.osmand/osm/poi_types.xml
2. OsmAndCore-sample/src/net.osmand/osm/poi_types.xml

**Comment by hamzabm** [comment]
for the first one : 
1- 
there is no directory  /osm/  on  path : OsmAnd/src/net.osmand/ 

for second one also there is no directory  /osm/  on path OsmAndCore-sample/src/net.osmand/

**Comment by AlexSyt** [comment]
If your project does not look like this, then you must re-download our project and rebuild main and sample apps.
![screenshot from 2017-12-04 20-42-19](https://user-images.githubusercontent.com/21020674/33569903-d20a3fb6-d933-11e7-9517-32f1de2484ad.png)

**Comment by vshcherb** [comment]
Looks like now it is more related issue to how to compile rather running prebuilt apk.

**Comment by hamzabm** [comment]
okey, but can you give some hint in the way to compile the project,
I have checked the github source code 
https://github.com/osmandapp/Osmand/tree/master/OsmAnd/src/net/osmand

i could'nt find the directory "/OSM/"

**Comment by AlexSyt** [comment]
This file is in the "OsmAnd-resources" repository.
You must download not only "Osmand" repository, but the entire project with:
repo init -u https://github.com/osmandapp/OsmAnd-manifest.git -m commit.xml
repo sync
Good luck :)

**Comment by hamzabm** [comment]
okey i will try it thanks ;) 

one last question : 
is it posssible to run the code simple without OSMAND installed ?

**Comment by AlexSyt** [comment]
I don`t think so)

**Comment by hamzabm** [comment]
perfect thanks ;) 
you were very helpful 👍

**Comment by hamzabm** [comment]
repo init -u https://github.com/osmandapp/OsmAnd-manifest.git -m commit.xml
repo sync

how can i run this command 
i'am using windows platform .

**Comment by AlexSyt** [comment]
I'm using Linux, so I don`t know. 
Read here about that "repo" tool: https://source.android.com/setup/developing

**Comment by hamzabm** [comment]
repo init -u https://github.com/osmandapp/OsmAnd-manifest.git -m commit.xml
repo sync
those two command are working fine. 
but still dont have the folder /OSM/
is there other comands nedded ?

**Comment by AlexSyt** [comment]
Try to build the project (files are copied during the build) and install, that should work. Otherwise i don't know what the problem is.

**Comment by goodibunakov** [comment]
Well, did somebody try to build OsmAndCore-sample on windows?
