### ISSUE TITLE
failed to connect to download.osmand.net/78.46.73.132 (port 80)

### ISSUE THREAD

**Issue by outsinre** [osmandapp/Osmand#4882]
Dunno why OsmAnd (2.8.2) can **not** download vector maps, raster maps, or any other online maps. Available vector maps list does **not** appear in *Download maps*.

I got *logcat*:

```
12-26 23:05:07.141   538   538 E SurfaceFlinger: net.osmand.plus/net.osmand.plus.activities.MapActivity b- nAvgNum= 14 avgtime=16689226.00 fps=59.92
12-26 23:05:07.141   538   538 E SurfaceFlinger: net.osmand.plus/net.osmand.plus.activities.MapActivity nAvgNum= 3 avgtime=16990642.00 fps=58.86
12-26 23:05:08.126 23425 23466 E net.osmand: TileSourceManager Exception while downloading tile sources
12-26 23:05:08.126 23425 23466 E net.osmand: java.net.ConnectException: failed to connect to download.osmand.net/78.46.73.132 (port 80): connect failed: ECONNREFUSED (Connection refused)
12-26 23:05:08.126 23425 23466 E net.osmand: 	at libcore.io.IoBridge.connect(IoBridge.java:124)
12-26 23:05:08.126 23425 23466 E net.osmand: 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
12-26 23:05:08.126 23425 23466 E net.osmand: 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
12-26 23:05:08.126 23425 23466 E net.osmand: 	at java.net.Socket.connect(Socket.java:884)
12-26 23:05:08.126 23425 23466 E net.osmand: 	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:117)
12-26 23:05:08.126 23425 23466 E net.osmand: 	at com.android.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160)
12-26 23:05:08.126 23425 23466 E net.osmand: 	at com.android.okhttp.internal.http.SocketConnector.connectCleartext(SocketConnector.java:67)
12-26 23:05:08.126 23425 23466 E net.osmand: 	at com.android.okhttp.Connection.connect(Connection.java:152)
12-26 23:05:08.126 23425 23466 E net.osmand: 	at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
12-26 23:05:08.126 23425 23466 E net.osmand: 	at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
12-26 23:05:08.126 23425 23466 E net.osmand: 	at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:342)
12-26 23:05:08.126 23425 23466 E net.osmand: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:331)
12-26 23:05:08.126 23425 23466 E net.osmand: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:249)
12-26 23:05:08.126 23425 23466 E net.osmand: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
12-26 23:05:08.126 23425 23466 E net.osmand: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
12-26 23:05:08.126 23425 23466 E net.osmand: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:231)
12-26 23:05:08.126 23425 23466 E net.osmand: 	at net.osmand.map.TileSourceManager.downloadTileSourceTemplates(TileSourceManager.java:465)
12-26 23:05:08.126 23425 23466 E net.osmand: 	at net.osmand.plus.rastermaps.OsmandRasterMapsPlugin$6.doInBackground(OsmandRasterMapsPlugin.java:387)
12-26 23:05:08.126 23425 23466 E net.osmand: 	at net.osmand.plus.rastermaps.OsmandRasterMapsPlugin$6.doInBackground(OsmandRasterMapsPlugin.java:384)
12-26 23:05:08.126 23425 23466 E net.osmand: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
12-26 23:05:08.126 23425 23466 E net.osmand: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-26 23:05:08.126 23425 23466 E net.osmand: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
12-26 23:05:08.126 23425 23466 E net.osmand: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
12-26 23:05:08.126 23425 23466 E net.osmand: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
12-26 23:05:08.126 23425 23466 E net.osmand: 	at java.lang.Thread.run(Thread.java:818)
12-26 23:05:08.126 23425 23466 E net.osmand: Caused by: android.system.ErrnoException: connect failed: ECONNREFUSED (Connection refused)
12-26 23:05:08.126 23425 23466 E net.osmand: 	at libcore.io.Posix.connect(Native Method)
12-26 23:05:08.126 23425 23466 E net.osmand: 	at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:111)
12-26 23:05:08.126 23425 23466 E net.osmand: 	at libcore.io.IoBridge.connectErrno(IoBridge.java:137)
12-26 23:05:08.126 23425 23466 E net.osmand: 	at libcore.io.IoBridge.connect(IoBridge.java:122)
12-26 23:05:08.126 23425 23466 E net.osmand: 	... 24 more
```

In order to download anything within the app, I have to set up Android proxy (i.e. socks5).

**Comment by vshcherb** [comment]
Is it possible the issue is fixed? Can't reproduce neither on mobile neither on PC.

**Comment by outsinre** [comment]
@vshcherb The issue disappeared after I rebooted device. Weird.
