### ISSUE TITLE
How  do  i  to  build this Osmand project with platforms windows in  android studio  ?

### ISSUE THREAD

**Issue by dykdykdyk** [osmandapp/Osmand#4891]
thanks you if  you know 
,please tell  me .

**Comment by dykdykdyk** [comment]
this(github)  and stackoverflow.com have nothing about this project to build The whole process, i'm in china and also have no helpful message to Reference,so please help  me   if  you  used this project  build - Success at  platform  windows with android studio 。。。

**Comment by Adamant36** [comment]
It appears that the app is written in Eclipse and not Android Studio with Java. Beyond that, I have no clue how you would it build it or anything. There doesn't seem to be a guide anywhere that I can find on how to build it or contribute to the project. I don't know if thats because they just haven't written one or if they are not looking for new people..Considering how many issues there are, you would at think there would be a good guide on how to contribute.

**Comment by dykdykdyk** [comment]
@Adamant36   ,then  i  have orther question，

E/net.osmand: NativeOsmandLibrary Failed to load native library
                                                        java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/net.osmand-1/base.apk", zip file "/data/app/net.osmand-1/split_lib_dependencies_apk.apk", zip file "/data/app/net.osmand-1/split_lib_slice_0_apk.apk", zip file "/data/app/net.osmand-1/split_lib_slice_1_apk.apk", zip file "/data/app/net.osmand-1/split_lib_slice_2_apk.apk", zip file "/data/app/net.osmand-1/split_lib_slice_3_apk.apk", zip file "/data/app/net.osmand-1/split_lib_slice_4_apk.apk", zip file "/data/app/net.osmand-1/split_lib_slice_5_apk.apk", zip file "/data/app/net.osmand-1/split_lib_slice_6_apk.apk", zip file "/data/app/net.osmand-1/split_lib_slice_7_apk.apk", zip file "/data/app/net.osmand-1/split_lib_slice_8_apk.apk", zip file "/data/app/net.osmand-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/net.osmand-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libgnustl_static.so"
                                                            at java.lang.Runtime.loadLibrary(Runtime.java:379)
                                                            at java.lang.System.loadLibrary(System.java:1086)
                                                            at net.osmand.plus.render.NativeOsmandLibrary.getLibrary(NativeOsmandLibrary.java:38)
                                                            at net.osmand.plus.AppInitializer.initNativeCore(AppInitializer.java:638)
                                                            at net.osmand.plus.AppInitializer.startApplicationBackground(AppInitializer.java:513)
                                                            at net.osmand.plus.AppInitializer.access$300(AppInitializer.java:74)
                                                            at net.osmand.plus.AppInitializer$9.run(AppInitializer.java:756)
                                                            at java.lang.Thread.run(Thread.java:833)

do  you know how can i slove it ?

**Comment by dykdykdyk** [comment]
@Adamant36  then i  have a question,
net.osmand: NativeOsmandLibrary Loading native gnustl_shared...
01-04 16:09:57.432 25616-25744/net.osmand E/net.osmand: NativeOsmandLibrary Failed to load native library
                                                        java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/net.osmand-2/base.apk", zip file "/data/app/net.osmand-2/split_lib_dependencies_apk.apk", zip file "/data/app/net.osmand-2/split_lib_slice_0_apk.apk", zip file "/data/app/net.osmand-2/split_lib_slice_1_apk.apk", zip file "/data/app/net.osmand-2/split_lib_slice_2_apk.apk", zip file "/data/app/net.osmand-2/split_lib_slice_3_apk.apk", zip file "/data/app/net.osmand-2/split_lib_slice_4_apk.apk", zip file "/data/app/net.osmand-2/split_lib_slice_5_apk.apk", zip file "/data/app/net.osmand-2/split_lib_slice_6_apk.apk", zip file "/data/app/net.osmand-2/split_lib_slice_7_apk.apk", zip file "/data/app/net.osmand-2/split_lib_slice_8_apk.apk", zip file "/data/app/net.osmand-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/net.osmand-2/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libgnustl_shared.so"
                                                            at java.lang.Runtime.loadLibrary(Runtime.java:379)
                                                            at java.lang.System.loadLibrary(System.java:1086)
                                                            at net.osmand.plus.render.NativeOsmandLibrary.getLibrary(NativeOsmandLibrary.java:37)
                                                            at net.osmand.plus.AppInitializer.initNativeCore(AppInitializer.java:638)
                                                            at net.osmand.plus.AppInitializer.startApplicationBackground(AppInitializer.java:513)
                                                            at net.osmand.plus.AppInitializer.access$300(AppInitializer.java:74)
                                                            at net.osmand.plus.AppInitializer$9.run(AppInitializer.java:756)
                                                            at java.lang.Thread.run(Thread.java:833)

do  you know how  can  i  solve it ?

**Comment by Adamant36** [comment]
Hhhhmmm I don't know. That's a little out of my expertise. If you do a google search the error code java.lang.UnsatisfiedLinkError there's a bunch of stuff about it. Also, if you do a google search for "java.lang.UnsatisfiedLinkError osmand" there's a bunch of pages specifically relating to this app. You might try looking through them.
