### ISSUE TITLE
Failed: remove geofences by PendingIntent

### ISSUE THREAD

**Issue by github11221** [osmandapp/Osmand#5023]
02-14 10:01:40.057 7060-26930/? E/GeofenceHelper: Failed: remove geofences by PendingIntent
02-14 10:01:50.138 27321-27327/? E/art: Failed sending reply to debugger: Broken pipe
02-14 10:01:50.287 27344-27344/? E/dex2oat: Failed to create oat file: /data/dalvik-cache/arm/data@app@net.osmand.core.samples.android.sample1-2@split_lib_dependencies_apk.apk@classes.dex: Permission denied
02-14 10:01:51.023 27354-27354/? E/dex2oat: Failed to create oat file: /data/dalvik-cache/arm/data@app@net.osmand.core.samples.android.sample1-2@split_lib_slice_0_apk.apk@classes.dex: Permission denied
02-14 10:01:51.179 27356-27356/? E/dex2oat: Failed to create oat file: /data/dalvik-cache/arm/data@app@net.osmand.core.samples.android.sample1-2@split_lib_slice_1_apk.apk@classes.dex: Permission denied
02-14 10:01:51.241 27359-27359/? E/dex2oat: Failed to create oat file: /data/dalvik-cache/arm/data@app@net.osmand.core.samples.android.sample1-2@split_lib_slice_2_apk.apk@classes.dex: Permission denied
02-14 10:01:51.302 27361-27361/? E/dex2oat: Failed to create oat file: /data/dalvik-cache/arm/data@app@net.osmand.core.samples.android.sample1-2@split_lib_slice_3_apk.apk@classes.dex: Permission denied
02-14 10:01:51.364 27363-27363/? E/dex2oat: Failed to create oat file: /data/dalvik-cache/arm/data@app@net.osmand.core.samples.android.sample1-2@split_lib_slice_4_apk.apk@classes.dex: Permission denied
02-14 10:01:51.431 27365-27365/? E/dex2oat: Failed to create oat file: /data/dalvik-cache/arm/data@app@net.osmand.core.samples.android.sample1-2@split_lib_slice_5_apk.apk@classes.dex: Permission denied
02-14 10:01:51.513 27367-27367/? E/dex2oat: Failed to create oat file: /data/dalvik-cache/arm/data@app@net.osmand.core.samples.android.sample1-2@split_lib_slice_6_apk.apk@classes.dex: Permission denied
02-14 10:01:51.570 27369-27369/? E/dex2oat: Failed to create oat file: /data/dalvik-cache/arm/data@app@net.osmand.core.samples.android.sample1-2@split_lib_slice_7_apk.apk@classes.dex: Permission denied
02-14 10:01:51.703 27371-27371/? E/dex2oat: Failed to create oat file: /data/dalvik-cache/arm/data@app@net.osmand.core.samples.android.sample1-2@split_lib_slice_8_apk.apk@classes.dex: Permission denied
02-14 10:01:51.763 27373-27373/? E/dex2oat: Failed to create oat file: /data/dalvik-cache/arm/data@app@net.osmand.core.samples.android.sample1-2@split_lib_slice_9_apk.apk@classes.dex: Permission denied
02-14 10:01:52.127 27321-27321/net.osmand.core.samples.android.sample1 E/net.osmand: MapRenderingTypes Unexpected error
                                                                                     java.lang.IllegalArgumentException: is == null
                                                                                         at org.kxml2.io.KXmlParser.setInput(KXmlParser.java:1634)
                                                                                         at net.osmand.osm.MapPoiTypes.initFromInputStream(MapPoiTypes.java:312)
                                                                                         at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:289)
                                                                                         at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:275)
                                                                                         at net.osmand.osm.MapPoiTypes.getDefault(MapPoiTypes.java:75)
                                                                                         at net.osmand.binary.BinaryMapPoiReaderAdapter.<init>(BinaryMapPoiReaderAdapter.java:103)
                                                                                         at net.osmand.binary.BinaryMapIndexReader.<init>(BinaryMapIndexReader.java:128)
                                                                                         at net.osmand.map.OsmandRegions.prepareFile(OsmandRegions.java:97)
                                                                                         at net.osmand.core.samples.android.sample1.SampleApplication.indexRegionsBoundaries(SampleApplication.java:137)
                                                                                         at net.osmand.core.samples.android.sample1.SampleApplication.onCreate(SampleApplication.java:78)
                                                                                         at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
                                                                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4806)
                                                                                         at android.app.ActivityThread.access$1600(ActivityThread.java:154)
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1452)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                         at android.os.Looper.loop(Looper.java:234)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5526)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-14 10:01:52.129 27321-27321/net.osmand.core.samples.android.sample1 E/net.osmand: MapRenderingTypes Unexpected error
                                                                                     java.lang.IllegalArgumentException: is == null
                                                                                         at org.kxml2.io.KXmlParser.setInput(KXmlParser.java:1634)
                                                                                         at net.osmand.osm.MapPoiTypes.initFromInputStream(MapPoiTypes.java:312)
                                                                                         at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:289)
                                                                                         at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:275)
                                                                                         at net.osmand.osm.MapPoiTypes.getDefault(MapPoiTypes.java:75)
                                                                                         at net.osmand.binary.BinaryMapPoiReaderAdapter.<init>(BinaryMapPoiReaderAdapter.java:103)
                                                                                         at net.osmand.binary.BinaryMapIndexReader.<init>(BinaryMapIndexReader.java:128)
                                                                                         at net.osmand.map.OsmandRegions.prepareFile(OsmandRegions.java:97)
                                                                                         at net.osmand.core.samples.android.sample1.SampleApplication.indexRegionsBoundaries(SampleApplication.java:137)
                                                                                         at net.osmand.core.samples.android.sample1.SampleApplication.onCreate(SampleApplication.java:78)
                                                                                         at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
                                                                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4806)
                                                                                         at android.app.ActivityThread.access$1600(ActivityThread.java:154)
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1452)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                         at android.os.Looper.loop(Looper.java:234)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5526)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-14 10:01:52.140 27321-27321/net.osmand.core.samples.android.sample1 E/net.osmand: MapRenderingTypes Unexpected error
                                                                                     java.lang.IllegalArgumentException: is == null
                                                                                         at org.kxml2.io.KXmlParser.setInput(KXmlParser.java:1634)
                                                                                         at net.osmand.osm.MapPoiTypes.initFromInputStream(MapPoiTypes.java:312)
                                                                                         at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:289)
                                                                                         at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:275)
                                                                                         at net.osmand.core.samples.android.sample1.SampleApplication.initPoiTypes(SampleApplication.java:190)
                                                                                         at net.osmand.core.samples.android.sample1.SampleApplication.onCreate(SampleApplication.java:85)
                                                                                         at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
                                                                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4806)
                                                                                         at android.app.ActivityThread.access$1600(ActivityThread.java:154)
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1452)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                         at android.os.Looper.loop(Looper.java:234)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5526)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-14 10:01:52.141 27321-27321/net.osmand.core.samples.android.sample1 E/net.osmand: MapRenderingTypes Unexpected error
                                                                                     java.lang.IllegalArgumentException: is == null
                                                                                         at org.kxml2.io.KXmlParser.setInput(KXmlParser.java:1634)
                                                                                         at net.osmand.osm.MapPoiTypes.initFromInputStream(MapPoiTypes.java:312)
                                                                                         at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:289)
                                                                                         at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:275)
                                                                                         at net.osmand.core.samples.android.sample1.SampleApplication.initPoiTypes(SampleApplication.java:190)
                                                                                         at net.osmand.core.samples.android.sample1.SampleApplication.onCreate(SampleApplication.java:85)
                                                                                         at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
                                                                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4806)
                                                                                         at android.app.ActivityThread.access$1600(ActivityThread.java:154)
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1452)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                         at android.os.Looper.loop(Looper.java:234)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5526)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-14 10:01:52.142 27321-27321/net.osmand.core.samples.android.sample1 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                         Process: net.osmand.core.samples.android.sample1, PID: 27321
                                                                                         java.lang.RuntimeException: Unable to create application net.osmand.core.samples.android.sample1.SampleApplication: java.lang.IllegalArgumentException: is == null
                                                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4809)
                                                                                             at android.app.ActivityThread.access$1600(ActivityThread.java:154)
                                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1452)
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                             at android.os.Looper.loop(Looper.java:234)
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:5526)
                                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                          Caused by: java.lang.IllegalArgumentException: is == null
                                                                                             at org.kxml2.io.KXmlParser.setInput(KXmlParser.java:1634)
                                                                                             at net.osmand.osm.MapPoiTypes.initFromInputStream(MapPoiTypes.java:312)
                                                                                             at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:289)
                                                                                             at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:275)
                                                                                             at net.osmand.core.samples.android.sample1.SampleApplication.initPoiTypes(SampleApplication.java:190)
                                                                                             at net.osmand.core.samples.android.sample1.SampleApplication.onCreate(SampleApplication.java:85)
                                                                                             at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
                                                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4806)
                                                                                             at android.app.ActivityThread.access$1600(ActivityThread.java:154) 
                                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1452) 
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                             at android.os.Looper.loop(Looper.java:234) 
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:5526) 
                                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
02-14 10:01:52.177 336-336/? E/lowmemorykiller: Error writing /proc/27321/oom_score_adj; errno=22
02-14 10:01:56.509 361-1005/? E/NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'TIME_NS' not found
02-14 10:01:56.510 361-1005/? E/NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'UID' not found
02-14 10:03:39.606 361-1005/? E/NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'TIME_NS' not found
02-14 10:03:39.606 361-1005/? E/NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'UID' not found
02-14 10:03:56.669 361-1005/? E/NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'TIME_NS' not found
02-14 10:03:56.670 361-1005/? E/NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'UID' not found
02-14 10:04:14.529 361-1005/? E/NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'TIME_NS' not found
02-14 10:04:14.529 361-1005/? E/NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'UID' not found
02-14 10:04:58.230 361-1005/? E/NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'TIME_NS' not found
02-14 10:04:58.231 361-1005/? E/NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'UID' not found
02-14 10:04:58.880 919-8622/? E/GooglePlayServicesUtil: The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.
02-14 10:07:21.115 361-1005/? E/NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'TIME_NS' not found
02-14 10:07:21.115 361-1005/? E/NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'UID' not found
02-14 10:07:57.469 361-1005/? E/NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'TIME_NS' not found
02-14 10:07:57.470 361-1005/? E/NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'UID' not found
02-14 10:08:21.308 361-1005/? E/NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'TIME_NS' not found
02-14 10:08:21.308 361-1005/? E/NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'UID' not found
02-14 10:08:36.350 361-1005/? E/NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'TIME_NS' not found
02-14 10:08:36.350 361-1005/? E/NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'UID' not found
02-14 10:09:38.123 361-1005/? E/NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'TIME_NS' not found
02-14 10:09:38.124 361-1005/? E/NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'UID' not found
02-14 10:09:53.907 22879-28068/? E/whr: Job(ItemMessageAttachmentsCacheEvictorJob#0.67) Enqueued job 'ItemMessageAttachmentsCacheEvictorJob' failed
                                        java.lang.IllegalArgumentException: Attachment cache cannot be null.
                                            at oqm.a(Unknown Source)
                                            at osa.a(Unknown Source)
                                            at xgr.a(SourceFile:2)
                                            at whd.b(SourceFile:2)
                                            at whe.a(Unknown Source)
                                            at xgr.a(SourceFile:2)
                                            at xfy.run(SourceFile:1)
                                            at vyf.run(Unknown Source)
                                            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
                                            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                            at java.lang.Thread.run(Thread.java:818)
02-14 10:09:57.390 361-1005/? E/NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'TIME_NS' not found
02-14 10:09:57.390 361-1005/? E/NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'UID' not found

**Comment by vshcherb** [comment]
>> Failed: remove geofences by PendingIntent #5023
Not clear description but I guess it is related to Storage Permission
Caused by: java.lang.IllegalArgumentException: is == null
at org.kxml2.io.KXmlParser.setInput(KXmlParser.java:1634)
at net.osmand.osm.MapPoiTypes.initFromInputStream(MapPoiTypes.java:312)
at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:289)
at net.osmand.osm.MapPoiTypes.init(MapPoiTypes.java:275)
at net.osmand.core.samples.android.sample1.SampleApplication.initPoiTypes(SampleApplication.java:190)
Or missing files
