### ISSUE TITLE
Crash uploading POI

### ISSUE THREAD

**Issue by hungrymonkey** [osmandapp/Osmand#5107]
I was trying to upload a poi

I cant replicate this crash

```
Version  OsmAnd~ 2.9.3
04.03.2018 4:28:12
Apk Version : 2.9.3 293
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v4.app.FragmentTransaction android.support.v4.app.FragmentManager.beginTransaction()' on a null object reference
	at android.support.v4.app.DialogFragment.dismissInternal(DialogFragment.java:200)
	at android.support.v4.app.DialogFragment.dismissAllowingStateLoss(DialogFragment.java:181)
	at net.osmand.plus.osmedit.UploadOpenstreetmapPointAsyncTask.onPostExecute(UploadOpenstreetmapPointAsyncTask.java:99)
	at net.osmand.plus.osmedit.UploadOpenstreetmapPointAsyncTask.onPostExecute(UploadOpenstreetmapPointAsyncTask.java:15)
	at android.os.AsyncTask.finish(AsyncTask.java:667)
	at android.os.AsyncTask.-wrap1(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by ADepic** [comment]
did it happen again? More specific? What POI
