### ISSUE TITLE
Can't create map from a specific region due to out of memory error

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#5211]
While trying to create a map from this area https://www.openstreetmap.org/relation/3360778 I am seeing this:

```
abr 04, 2018 1:29:27 AM net.osmand.data.index.IndexBatchCreator generateIndex
GRAVE: OutOfMemory
java.lang.OutOfMemoryError: Java heap space
        at java.desktop/java.awt.image.DataBufferShort.<init>(DataBufferShort.java:90)
        at java.desktop/java.awt.image.ComponentSampleModel.createDataBuffer(ComponentSampleModel.java:445)
        at java.desktop/java.awt.image.Raster.createWritableRaster(Raster.java:1005)
        at java.desktop/javax.imageio.ImageTypeSpecifier.createBufferedImage(ImageTypeSpecifier.java:1074)
        at com.twelvemonkeys.imageio.ImageReaderBase.getDestination(ImageReaderBase.java:316)
        at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:759)
        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1468)
        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1315)
        at net.osmand.data.preparation.IndexHeightData$TileData.loadData(IndexHeightData.java:65)
        at net.osmand.data.preparation.IndexHeightData.getPointHeight(IndexHeightData.java:362)
        at net.osmand.data.preparation.IndexHeightData.getPointHeight(IndexHeightData.java:338)
        at net.osmand.data.preparation.IndexHeightData.proccess(IndexHeightData.java:293)
        at net.osmand.data.preparation.IndexCreator.iterateMainEntity(IndexCreator.java:265)
        at net.osmand.data.preparation.IndexCreator.access$200(IndexCreator.java:56)
        at net.osmand.data.preparation.IndexCreator$6.iterateEntity(IndexCreator.java:805)
        at net.osmand.data.preparation.OsmDbAccessor.iterateOverEntities(OsmDbAccessor.java:253)
        at net.osmand.data.preparation.OsmDbAccessor.iterateOverEntities(OsmDbAccessor.java:207)
        at net.osmand.data.preparation.IndexCreator.iterateMainEntities(IndexCreator.java:802)
        at net.osmand.data.preparation.IndexCreator.generateIndexes(IndexCreator.java:660)
        at net.osmand.data.preparation.IndexCreator.generateIndexes(IndexCreator.java:586)
        at net.osmand.data.index.IndexBatchCreator.generateIndex(IndexBatchCreator.java:566)
        at net.osmand.data.index.IndexBatchCreator.generatedIndexes(IndexBatchCreator.java:475)
        at net.osmand.data.index.IndexBatchCreator.runBatch(IndexBatchCreator.java:318)
        at net.osmand.data.index.IndexBatchCreator.main(IndexBatchCreator.java:168)
```

With every other region in Brazil (including the one with most of the objects https://www.openstreetmap.org/relation/3073228) I can properly create an `obf` with `-Xmx6g`, while with this specific area it fails even with `-Xmx10g`.

It seems to fail here since Aug 8 2017 at least.

It seems to be strange to have to allocate much more memory for just this area.
Is there something that maybe could be fixed/optimized/refactored in OsmAndMapCreator for this, please?

**Comment by vshcherb** [comment]
It uses by default in_memory sqlite so there should be an option to chnage it .
https://github.com/osmandapp/OsmAnd-tools/blob/master/obf-generation/indexes-batch-generate-inmem.xml#L4

**Comment by naoliv** [comment]
I have `osmDbDialect="sqlite" mapDbDialect="sqlite"` in my config (which I guess should use the disk instead the memory)
Which other options can I try, please?

**Comment by vshcherb** [comment]
Sorry, now I realized... 
Unfortunately you can't do it cause you have SRTM data for preparation... unfortunately it requires to load in memory so it could be built faster and today there is no other option to reduce memory footprint except removing srtm tiles or building by small subareas.

**Comment by naoliv** [comment]
Right, thanks
