### ISSUE TITLE
OsmAnd crashes when tapping on overlapping POIs

### ISSUE THREAD

**Issue by MAlfare** [osmandapp/Osmand#5228]
This happens since at least:

Version  OsmAnd~ 2.9.0#24133m
26.03.2018 11:30:46
Apk Version : 2.9.0#24133m 300
 
on one of my devices:

Device : ME302C
Brand : asus
Model : ME302C
Product : WW_epad
Build : JSS15Q.WW_epad-V5.0.21-20140701
Version : 4.3
App Version : OsmAnd~
Apk Version : 3.0.0#24335m 300 

It does not happen on:

Lenovo A3500F tablet with
Android Version 4.4.2
and
Lenovo Moto G4 Plus smart phone with
Android-Version 7.0

When tapping on POIs overlapping each other, OsmAnd does not present a list named "What's here:" to select which POIs details to show, but crashes immediately.
If zoomed in, so that the POIs are separated from each other, either one can be tapped to show its details without problems.

As stated above, this only happens on the asus device (maybe, because it has an intel processor?)

Exception log shows the following:

```
Version  OsmAnd~ 3.0.0#24359m
12.04.2018 1:43:04
Apk Version : 3.0.0#24359m 300
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalStateException: Cannot add header view to list -- setAdapter has already been called.
	at android.widget.ListView.addHeaderView(ListView.java:258)
	at android.widget.ListView.addHeaderView(ListView.java:287)
	at net.osmand.plus.mapcontextmenu.other.MapMultiSelectionMenuFragment.onCreateView(MapMultiSelectionMenuFragment.java:149)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2343)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1421)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1752)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1821)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2595)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2382)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2337)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2244)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:702)
	at android.os.Handler.handleCallback(Handler.java:730)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5162)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:744)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by CJTmmr** [comment]
related issue #5149

on my device it was fixed two weeks ago

**Comment by MAlfare** [comment]
Glad to hear, that this problem is solved for your device.
So it it should be possible to solve it for mine.

BTW, your log is exactly the same as mine, except the numbers behind the "java:" and the OsmAnd and Apk version numbers.

Do you know, what the "m" and "d" following the OsmAnd version numbers do mean?

**Comment by MAlfare** [comment]
Seems to be repaired in version OsmAnd~3.0.0#24625m, nightly from 2018-05-01 23:03

**Comment by Chumva** [comment]
fixed with https://github.com/osmandapp/Osmand/commit/012d19e79fb734ed4518418e551e97bc718ea3f1#diff-f82579d6785a79c21c9079ebd3d323b7R149
