### ISSUE TITLE
NPE: Attempt to invoke virtual method 'double net.osmand.Location.getLatitude()' on a null object reference

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#5396]
While planning a route OsmAnd 7.1.2 suddenly stopped rendering. The map became completely white. OsmAnd itself did still respond.

The log says:
```
05-11 09:33:22.501 I/chatty  (29890): uid=10097(net.osmand.plus) Loader map obje expire 66 lines
05-11 09:33:22.856 I/chatty  (29890): uid=10097(net.osmand.plus) RenderingBaseIm expire 155 lines
05-11 09:33:27.839 I/chatty  (29890): uid=10097(net.osmand.plus) Loader map obje expire 34 lines
05-11 09:33:29.690 I/chatty  (29890): uid=10097(net.osmand.plus) RenderingBaseIm expire 69 lines
05-11 09:33:31.970 I/ActivityManager(1533): START u0 {flg=0x20000 cmp=net.osmand.plus/.activities.PluginsActivity} from uid 10097 on display 0
05-11 09:33:32.009 I/chatty  (29890): uid=10097(net.osmand.plus) expire 19 lines
05-11 09:33:32.349 I/ActivityManager(1533): Displayed net.osmand.plus/.activities.PluginsActivity: +339ms
05-11 09:33:32.438 I/chatty  (29890): uid=10097(net.osmand.plus) RenderThread expire 1 line
05-11 09:33:39.226 E/ActivityThread(29890): Activity net.osmand.plus.activities.MapActivity has leaked IntentReceiver net.osmand.aidl.OsmandAidlApi$8@dbbf39d that was originally registered here. Are you missing a call to unregisterReceiver()?
05-11 09:33:39.226 E/ActivityThread(29890): android.app.IntentReceiverLeaked: Activity net.osmand.plus.activities.MapActivity has leaked IntentReceiver net.osmand.aidl.OsmandAidlApi$8@dbbf39d that was originally registered here. Are you missing a call to unregisterReceiver()?
05-11 09:33:39.226 E/ActivityThread(29890): 	at net.osmand.aidl.OsmandAidlApi.registerStartVideoRecordingReceiver(OsmandAidlApi.java:428)
05-11 09:33:39.226 E/ActivityThread(29890): 	at net.osmand.aidl.OsmandAidlApi.onCreateMapActivity(OsmandAidlApi.java:142)
05-11 09:33:39.226 E/ActivityThread(29890): 	at net.osmand.plus.activities.MapActivity.onCreate(MapActivity.java:327)
05-11 09:33:40.351 I/ActivityManager(1533): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=net.osmand.plus/.activities.MapActivity bnds=[0,835][180,1032] (has extras)} from uid 10079 on display 0
05-11 09:33:40.566 I/chatty  (29890): uid=10097(net.osmand.plus) AsyncTask #2 expire 2 lines
05-11 09:33:41.120 I/chatty  (29890): uid=10097(net.osmand.plus) HeapTaskDaemon expire 1 line
05-11 09:33:41.160 I/ActivityManager(1533): Displayed net.osmand.plus/.activities.MapActivity: +782ms
05-11 09:33:41.161 I/chatty  (29890): uid=10097(net.osmand.plus) RenderingBaseIm expire 1 line
05-11 09:33:41.208 E/net.osmand(29890): OsmandMapTileView Attempt to invoke virtual method 'double net.osmand.Location.getLatitude()' on a null object reference
05-11 09:33:41.208 E/net.osmand(29890): java.lang.NullPointerException: Attempt to invoke virtual method 'double net.osmand.Location.getLatitude()' on a null object reference
05-11 09:33:41.208 E/net.osmand(29890): 	at net.osmand.plus.views.RouteLayer$RouteSimplificationGeometry.addLocation(RouteLayer.java:500)
05-11 09:33:41.208 E/net.osmand(29890): 	at net.osmand.plus.views.RouteLayer$RouteSimplificationGeometry.drawSegments(RouteLayer.java:472)
05-11 09:33:41.208 E/net.osmand(29890): 	at net.osmand.plus.views.RouteLayer$RouteSimplificationGeometry.access$200(RouteLayer.java:402)
05-11 09:33:41.208 E/net.osmand(29890): 	at net.osmand.plus.views.RouteLayer.drawLocations(RouteLayer.java:548)
05-11 09:33:41.208 E/net.osmand(29890): 	at net.osmand.plus.views.RouteLayer.onPrepareBufferImage(RouteLayer.java:158)
05-11 09:33:41.208 E/net.osmand(29890): 	at net.osmand.plus.views.OsmandMapTileView.refreshBaseMapInternal(OsmandMapTileView.java:584)
05-11 09:33:41.208 E/net.osmand(29890): 	at net.osmand.plus.views.OsmandMapTileView.access$900(OsmandMapTileView.java:62)
05-11 09:33:41.208 E/net.osmand(29890): 	at net.osmand.plus.views.OsmandMapTileView$2.run(OsmandMapTileView.java:781)
05-11 09:33:41.208 E/net.osmand(29890): 	at android.os.Handler.handleCallback(Handler.java:751)
05-11 09:33:41.208 E/net.osmand(29890): 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-11 09:33:41.208 E/net.osmand(29890): 	at android.os.Looper.loop(Looper.java:154)
05-11 09:33:41.208 E/net.osmand(29890): 	at android.os.HandlerThread.run(HandlerThread.java:61)
05-11 09:33:41.253 E/net.osmand(29890): OsmandMapTileView Attempt to invoke virtual method 'double net.osmand.Location.getLatitude()' on a null object reference
05-11 09:33:41.253 E/net.osmand(29890): java.lang.NullPointerException: Attempt to invoke virtual method 'double net.osmand.Location.getLatitude()' on a null object reference
05-11 09:33:41.253 E/net.osmand(29890): 	at net.osmand.plus.views.RouteLayer$RouteSimplificationGeometry.addLocation(RouteLayer.java:500)
05-11 09:33:41.253 E/net.osmand(29890): 	at net.osmand.plus.views.RouteLayer$RouteSimplificationGeometry.drawSegments(RouteLayer.java:472)
05-11 09:33:41.253 E/net.osmand(29890): 	at net.osmand.plus.views.RouteLayer$RouteSimplificationGeometry.access$200(RouteLayer.java:402)
05-11 09:33:41.253 E/net.osmand(29890): 	at net.osmand.plus.views.RouteLayer.drawLocations(RouteLayer.java:548)
05-11 09:33:41.253 E/net.osmand(29890): 	at net.osmand.plus.views.RouteLayer.onPrepareBufferImage(RouteLayer.java:158)
05-11 09:33:41.253 E/net.osmand(29890): 	at net.osmand.plus.views.OsmandMapTileView.refreshBaseMapInternal(OsmandMapTileView.java:584)
05-11 09:33:41.253 E/net.osmand(29890): 	at net.osmand.plus.views.OsmandMapTileView.access$900(OsmandMapTileView.java:62)
05-11 09:33:41.253 E/net.osmand(29890): 	at net.osmand.plus.views.OsmandMapTileView$2.run(OsmandMapTileView.java:781)
05-11 09:33:41.253 E/net.osmand(29890): 	at android.os.Handler.handleCallback(Handler.java:751)
05-11 09:33:41.253 E/net.osmand(29890): 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-11 09:33:41.253 E/net.osmand(29890): 	at android.os.Looper.loop(Looper.java:154)
05-11 09:33:41.253 E/net.osmand(29890): 	at android.os.HandlerThread.run(HandlerThread.java:61)
05-11 09:33:41.812 W/SQLiteConnectionPool(29890): A SQLiteConnection object for database '/storage/9F08-1C0C/Android/data/net.osmand.plus/files/tiles/Hillshade Austria europe.sqlitedb' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
05-11 09:33:41.813 W/SQLiteConnectionPool(29890): A SQLiteConnection object for database '/storage/9F08-1C0C/Android/data/net.osmand.plus/files/tiles/Hillshade Austria europe.sqlitedb' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
05-11 09:33:42.373 E/net.osmand(29890): OsmandMapTileView Attempt to invoke virtual method 'double net.osmand.Location.getLatitude()' on a null object reference
05-11 09:33:42.373 E/net.osmand(29890): java.lang.NullPointerException: Attempt to invoke virtual method 'double net.osmand.Location.getLatitude()' on a null object reference
05-11 09:33:42.373 E/net.osmand(29890): 	at net.osmand.plus.views.RouteLayer$RouteSimplificationGeometry.addLocation(RouteLayer.java:500)
05-11 09:33:42.373 E/net.osmand(29890): 	at net.osmand.plus.views.RouteLayer$RouteSimplificationGeometry.drawSegments(RouteLayer.java:472)
05-11 09:33:42.373 E/net.osmand(29890): 	at net.osmand.plus.views.RouteLayer$RouteSimplificationGeometry.access$200(RouteLayer.java:402)
05-11 09:33:42.373 E/net.osmand(29890): 	at net.osmand.plus.views.RouteLayer.drawLocations(RouteLayer.java:548)
05-11 09:33:42.373 E/net.osmand(29890): 	at net.osmand.plus.views.RouteLayer.onPrepareBufferImage(RouteLayer.java:158)
05-11 09:33:42.373 E/net.osmand(29890): 	at net.osmand.plus.views.OsmandMapTileView.refreshBaseMapInternal(OsmandMapTileView.java:584)
05-11 09:33:42.373 E/net.osmand(29890): 	at net.osmand.plus.views.OsmandMapTileView.access$900(OsmandMapTileView.java:62)
05-11 09:33:42.373 E/net.osmand(29890): 	at net.osmand.plus.views.OsmandMapTileView$2.run(OsmandMapTileView.java:781)
05-11 09:33:42.373 E/net.osmand(29890): 	at android.os.Handler.handleCallback(Handler.java:751)
05-11 09:33:42.373 E/net.osmand(29890): 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-11 09:33:42.373 E/net.osmand(29890): 	at android.os.Looper.loop(Looper.java:154)
05-11 09:33:42.373 E/net.osmand(29890): 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

Restarting OsmAnd resolved the problem. Just occurred once, no idea how to reproduce.

**Comment by vshcherb** [comment]
According to the codebase it should not happen at all in a properly functioning Android VM.
