### ISSUE TITLE
Travel section crash OsmAnd

### ISSUE THREAD

**Issue by dmromanov** [osmandapp/Osmand#5431]
Version  OsmAnd+ 3.0.0
18.05.2018 1:24:52
Apk Version : 3.0.0 300
Android 8.0.0 OPR1.170623.027
Mi6 with MIUI9 Global Stable ROM 9.5.6.0

I've downloaded travel database at a newly created section "Travel" of OsmAnd.
After clicking at "Travel (beta)" menu item OsmAnd crash.
Restart does not help.

c0fdd22b acde094101ae3a936ae350bfdff5715b World_wikivoyage.sqlite 

```
Exception occured in thread Thread[AsyncTask #6,5,main] : 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:353)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: android.database.sqlite.SQLiteException: no such column: article_id (code 1): , while compiling: SELECT article_id, title, content_gz, is_part_of, lat, lon, image_title, gpx_gz, trip_id, original_id, lang, contents_json, aggregated_part_of FROM travel_articles WHERE lang = 'en' and trip_id IN (33068, 9436, 2116, 1280, 1602, 10247, 43348, 1044, 8849, 1977, 10421, 1492, 2483, 1599, 4422, 391, 14831, 2789, 3246, 38596, 8680, 2644, 32983, 13183, 2387)
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1318)
	at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1257)
	at net.osmand.plus.api.SQLiteAPIImpl$SQLiteDatabaseWrapper.rawQuery(SQLiteAPIImpl.java:52)
	at net.osmand.plus.wikivoyage.data.TravelDbHelper.readTravelArticles(TravelDbHelper.java:329)
	at net.osmand.plus.wikivoyage.data.TravelDbHelper.loadPopularArticles(TravelDbHelper.java:311)
	at net.osmand.plus.wikivoyage.data.TravelDbHelper.loadDataForSelectedTravelBook(TravelDbHelper.java:157)
	at net.osmand.plus.wikivoyage.explore.WikivoyageExploreDialogFragment$LoadWikivoyageData.doInBackground(WikivoyageExploreDialogFragment.java:253)
	at net.osmand.plus.wikivoyage.explore.WikivoyageExploreDialogFragment$LoadWikivoyageData.doInBackground(WikivoyageExploreDialogFragment.java:241)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more
```

**Comment by jfburke3** [comment]
@dmromanov Did it actually complete the download?  I think I had the same thing happen in #5425 .  If you delete the relevant .sqlite file, does it "fix" the crash?

**Comment by dmromanov** [comment]
I will try.

**Comment by dmromanov** [comment]
@jfburke3 After re-downloading I got the same error. Hash sums of the new file match hash sums of the old file.

```
crc32b: c0fdd22b
md5: acde094101ae3a936ae350bfdff5715b
World_wikivoyage.sqlite
```

**Comment by Norbert80** [comment]
Same bug on my device.

**Comment by vshcherb** [comment]
On the moment of beta release it was fine but few hours later db format has changed without backward compatibility (last change before release)
 new beta on Monday will fix with this.

**Comment by vshcherb** [comment]
Beta release delayed till Tuesday.

**Comment by dmromanov** [comment]
OsmAnd+ 3.0.0 2018-05-22
Works good.
