### ISSUE TITLE
Crash on publishing exception.log

### ISSUE THREAD

**Issue by dmromanov** [osmandapp/Osmand#5432]
Version  OsmAnd+ 3.0.0
18.05.2018 1:24:55
Apk Version : 3.0.0 300
Android 8.0.0 OPR1.170623.027
Mi6 with MIUI9 Global Stable ROM 9.5.6.0

Crash reporting was successfully working in a previos beta version.

Related to #5431. After experiencing a crash, on the next launch of OsmAnd it suggests to send the crash log to developers. If clicked on "Send" button - OsmAnd crash.

Exception occured in thread Thread[main,5,main] : 
android.os.FileUriExposedException: file:///storage/emulated/0/osmand/exception.log exposed beyond app through ClipData.Item.getUri()
	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1958)
	at android.net.Uri.checkFileUriExposed(Uri.java:2348)
	at android.content.ClipData.prepareToLeaveProcess(ClipData.java:941)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:9747)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:9753)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:9732)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1611)
	at android.app.Activity.startActivityForResult(Activity.java:4540)
	at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68)
	at android.support.v4.app.ActivityCompat.startActivityForResult(ActivityCompat.java:233)
	at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:825)
	at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:939)
	at android.support.v4.app.Fragment.startActivity(Fragment.java:1000)
	at android.support.v4.app.Fragment.startActivity(Fragment.java:989)
	at net.osmand.plus.dialogs.ErrorBottomSheetDialog$1.onClick(ErrorBottomSheetDialog.java:72)
	at android.view.View.performClick(View.java:6266)
	at android.view.View$PerformClick.run(View.java:24730)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6665)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

**Comment by Chumva** [comment]
Fixed with https://github.com/osmandapp/Osmand/commit/84852b393f0b0bc0ea8ea52a70789b2890949cdd
