### ISSUE TITLE
IllegalStateException: Animator has already started, cannot change it now!

### ISSUE THREAD

**Issue by justinjhendrick** [osmandapp/Osmand#5485]
Repro Steps:
1) Pixel with Android 8.1
2) Install Osmand+ 2.9.3
3) enable battery saving mode
4) tap on "Configure map"

Then this exception occurs and crashes the application

```
05-24 19:24:29.302 16584 16584 E AndroidRuntime: FATAL EXCEPTION: main
05-24 19:24:29.302 16584 16584 E AndroidRuntime: Process: net.osmand.plus, PID: 16584
05-24 19:24:29.302 16584 16584 E AndroidRuntime: java.lang.IllegalStateException: Animator has already started, cannot change it now!
05-24 19:24:29.302 16584 16584 E AndroidRuntime: 	at android.view.RenderNodeAnimator.checkMutable(RenderNodeAnimator.java:149)
05-24 19:24:29.302 16584 16584 E AndroidRuntime: 	at android.view.RenderNodeAnimator.setDuration(RenderNodeAnimator.java:324)
05-24 19:24:29.302 16584 16584 E AndroidRuntime: 	at android.view.RenderNodeAnimator.setDuration(RenderNodeAnimator.java:322)
05-24 19:24:29.302 16584 16584 E AndroidRuntime: 	at android.animation.AnimatorSet.updateAnimatorsDuration(AnimatorSet.java:774)
05-24 19:24:29.302 16584 16584 E AndroidRuntime: 	at android.animation.AnimatorSet.getTotalDuration(AnimatorSet.java:1737)
05-24 19:24:29.302 16584 16584 E AndroidRuntime: 	at android.animation.AnimatorSet.forceToEnd(AnimatorSet.java:446)
05-24 19:24:29.302 16584 16584 E AndroidRuntime: 	at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:995)
05-24 19:24:29.302 16584 16584 E AndroidRuntime: 	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
05-24 19:24:29.302 16584 16584 E AndroidRuntime: 	at android.animation.AnimationHandler.-wrap2(Unknown Source:0)
05-24 19:24:29.302 16584 16584 E AndroidRuntime: 	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
05-24 19:24:29.302 16584 16584 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
05-24 19:24:29.302 16584 16584 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
05-24 19:24:29.302 16584 16584 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:655)
05-24 19:24:29.302 16584 16584 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
05-24 19:24:29.302 16584 16584 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
05-24 19:24:29.302 16584 16584 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-24 19:24:29.302 16584 16584 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
05-24 19:24:29.302 16584 16584 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
05-24 19:24:29.302 16584 16584 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-24 19:24:29.302 16584 16584 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
05-24 19:24:29.302 16584 16584 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by justinjhendrick** [comment]
Closing. I just realized this is a duplicate of #5220
