### ISSUE TITLE
app often crashing on Android 8

### ISSUE THREAD

**Issue by WebFreak001** [osmandapp/OsmAnd#5655]
Using OsmAnd on my car radio, but today it has been crashing a lot (last week it didn't happen)

```
Device : px5
Brand : Android
Model : px5
Product : px5
Build : px5-userdebug 8.0.0 OPR5.170623.007 eng.hct.20180409.174155 test-keys
Version : 8.0.0
App Version : OsmAnd
Apk Version : 3.0.4 304
```

```
Version  OsmAnd 3.0.4
08.07.2018 10:35:19
Apk Version : 3.0.4 304
Exception occured in thread Thread[main,5,main] : 
android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:734)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1679)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1658)
	at net.osmand.plus.activities.SavingTrackHelper.execWithClose(SavingTrackHelper.java:585)
	at net.osmand.plus.activities.SavingTrackHelper.insertData(SavingTrackHelper.java:416)
	at net.osmand.plus.activities.SavingTrackHelper.updateLocation(SavingTrackHelper.java:406)
	at net.osmand.plus.OsmAndLocationProvider.setLocation(OsmAndLocationProvider.java:799)
	at net.osmand.plus.OsmAndLocationProvider.access$700(OsmAndLocationProvider.java:47)
	at net.osmand.plus.OsmAndLocationProvider$2.onLocationChanged(OsmAndLocationProvider.java:596)
	at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:291)
	at android.location.LocationManager$ListenerTransport.-wrap0(Unknown Source:0)
	at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:236)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Version  OsmAnd 3.0.4
08.07.2018 1:31:24
Apk Version : 3.0.4 304
Exception occured in thread Thread[main,5,main] : 
android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:734)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1679)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1658)
	at net.osmand.plus.activities.SavingTrackHelper.execWithClose(SavingTrackHelper.java:585)
	at net.osmand.plus.activities.SavingTrackHelper.insertData(SavingTrackHelper.java:416)
	at net.osmand.plus.activities.SavingTrackHelper.updateLocation(SavingTrackHelper.java:406)
	at net.osmand.plus.OsmAndLocationProvider.setLocationFromService(OsmAndLocationProvider.java:767)
	at net.osmand.plus.NavigationService.onLocationChanged(NavigationService.java:240)
	at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:291)
	at android.location.LocationManager$ListenerTransport.-wrap0(Unknown Source:0)
	at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:236)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

not sure if this is the Exception reporter from OsmAnd or from the device, but I think this is definitely helpful.

What I have noticed is that it might be because of wifi being enabled. (it wasn't enabled last week) It had crashed about 3 times (but I couldn't save the stacktrace because I was in the middle of the Autobahn) but after disabling wifi it ran fine. Maybe this could also be caused by the GPX tracking extension in there because I enabled it to save a track and live upload it via an HTTP address.

What I also noticed was that after crashing, restarting & recalculating the route it tried to send me the wrong direction through a "one-way street" (it tried to make me do a 150 degree turn on the Autobahn into the Auffahrt in the other direction), but when I checked the osm data where I believed it happened, everything was a one-way (though I can't really say that for sure, but maybe if there is some different logic in the re-routing algorithm it might be worth investigating there)

**Comment by AlexSyt** [comment]
App crashes because of SQLite database which needed for GPX-track recording. I think the problem is on the device side.

**Comment by WebFreak001** [comment]
it seems that the device is running a custom android rom with disabled settings. For example I can't use proper bluetooth and even if I enable the developer settings I cannot access them.

However I don't see a reason why the app would crash because of that. Any reason not to just put it in a try/catch block so navigation doesn't crash because of GPX-track recording?

**Comment by AlexSyt** [comment]
I have already added a catch block for this exception.

**Comment by WebFreak001** [comment]
uh ok guess it's the OS/Device then (the system UI crashes occasionally too)

**Comment by WebFreak001** [comment]
didn't happen anymore for a year now so closing
