### ISSUE TITLE
Why black screen show on map view ?

### ISSUE THREAD

**Issue by code4rox** [osmandapp/Osmand#5738]
I have build Osmand successfully but in osmand app I have downloaded the offline map after download the map not show correctly the black screen showed on map view.

![screenshot_osmand_nightly_20180727-093523](https://user-images.githubusercontent.com/34452490/43302173-68269c5e-9182-11e8-9172-0a422db9ddba.png)
   
In the Logcat I received the following errors 

```
`2018-07-27 09:52:24.766 21509-21544/net.osmand E/net.osmand: NativeOsmandLibrary Failed to load native library
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/net.osmand-jlsDBfbIUwRHokiox1klLQ==/base.apk"],nativeLibraryDirectories=[/data/app/net.osmand-jlsDBfbIUwRHokiox1klLQ==/lib/arm, /system/lib, /system/vendor/lib]]] couldn't find "libgnustl_shared.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at net.osmand.plus.render.NativeOsmandLibrary.getLibrary(NativeOsmandLibrary.java:37)
        at net.osmand.plus.AppInitializer.initNativeCore(AppInitializer.java:751)
        at net.osmand.plus.AppInitializer.startApplicationBackground(AppInitializer.java:625)
        at net.osmand.plus.AppInitializer.access$300(AppInitializer.java:80)
        at net.osmand.plus.AppInitializer$9.run(AppInitializer.java:869)
        at java.lang.Thread.run(Thread.java:764)`
```

```
2018-07-27 09:52:24.694 21509-21544/net.osmand E/net.osmand: ResourceManager voice/de/ttsconfig.p
    java.io.FileNotFoundException: voice/de/ttsconfig.p
        at android.content.res.AssetManager.openAsset(Native Method)
        at android.content.res.AssetManager.open(AssetManager.java:388)
        at net.osmand.plus.resources.ResourceManager.copyAssets(ResourceManager.java:538)
        at net.osmand.plus.resources.ResourceManager.unpackBundledAssets(ResourceManager.java:526)
        at net.osmand.plus.resources.ResourceManager.checkAssets(ResourceManager.java:429)
        at net.osmand.plus.resources.ResourceManager.reloadIndexesOnStart(ResourceManager.java:355)
        at net.osmand.plus.AppInitializer.startApplicationBackground(AppInitializer.java:620)
        at net.osmand.plus.AppInitializer.access$300(AppInitializer.java:80)
        at net.osmand.plus.AppInitializer$9.run(AppInitializer.java:869)
```

**Comment by code4rox** [comment]
Successfully, I have build project using these commands 

```
repo init -u https://github.com/osmandapp/OsmAnd-manifest.git -m android_build.xml
repo sync -d
```

```
cd android/OsmAnd
../gradlew --refresh-dependencies clean assembleFullLegacyFatDebug
```

**Comment by jfburke3** [comment]
I've had something similar happen with the official release version.  Is there something I can do to capture the issue that might help find the problem?

**Comment by vshcherb** [comment]
not aware of that issue on the standard build probably you should configure ndk build properly

**Comment by duven87** [comment]
I have this problem today on my S5 mini with lineage 16.

**Comment by mmoser18** [comment]
Same here with the official release version (v4.4.7). On my Samsung S23 (Android 13) when running Osmand and switching the phone off and back on, the screen often is totally black  (or to be precise: the part, where the application content should appear is black, only the notification area on top is visible. In contrast to the screenshot above not even any buttons or other navigation elements are visible). Only the lit top bar indicates that your phone is actually switched on. Otherwise it looks and behaves as if it were still switched off, i.e. it does not react to any screen input. Only pressing the power button for a few seconds brings back the map view.

**Comment by sonora** [comment]
@mmoser18 , @jfburke3 Does falling back to using the render engine v1 fix this?

**Comment by mmoser18** [comment]
No - unfortunately it did not. The effect appears reproducibly, when I have Android open as top application and then turn off the device. Then I need to wait for at least 30 seconds or so and when I then switch it on again then I see only the top area lit, the bottom part of the screen remains black. I then need to press Power for 2-3 seconds and then the display re-appears (i.e. the lock screen). 
If Osmand is NOT the top application (i.e. it was running in the back and an other application was on top) or if it is not running at all, then I immediately get the "lock-screen" where I need to log in or press the fingerprint, when powering on.

**Comment by sonora** [comment]
Cannot currently find a device reproducing this. Believe it is device dependent, hence I thought it may be GPU (remderer v2) related  but apparently not.
