### ISSUE TITLE
OsmAnd+ crashed while taking audio notes

### ISSUE THREAD

**Issue by jmsbert** [osmandapp/Osmand#5784]
Dear developers of OSMAnd,
for the second time the current version of OSMAnd+ crashed in the same situation: While taking audio notes and recording the track the mobile phone stated that OSMAnd+ did not respond. I hope that you can fix this issue.

Device : a5y17lte
Brand : samsung
Model : SM-A520F
Product : a5y17ltexx
Build : R16NW.A520FXXU4CRF1
Version : 8.0.0
App Version : OsmAnd+
Apk Version : 3.0.4 304

exception.log:
Version  OsmAnd+ 3.0.4
29.07.2018 1:16:31
Apk Version : 3.0.4 304
Exception occured in thread Thread[main,5,main] : 
java.lang.RuntimeException: stop failed.
	at android.media.MediaRecorder._stop(Native Method)
	at android.media.MediaRecorder.stop(MediaRecorder.java:1339)
	at net.osmand.plus.audionotes.AudioVideoNotesPlugin.stopMediaRecording(AudioVideoNotesPlugin.java:1133)
	at net.osmand.plus.audionotes.AudioVideoNotesPlugin.stopRecording(AudioVideoNotesPlugin.java:1614)
	at net.osmand.plus.audionotes.AudioVideoNotesPlugin$13.onClick(AudioVideoNotesPlugin.java:1605)
	at android.view.View.performClick(View.java:6897)
	at android.view.View$PerformClick.run(View.java:26101)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Version  OsmAnd+ 3.0.4
03.08.2018 8:55:29
Apk Version : 3.0.4 304
Exception occured in thread Thread[main,5,main] : 
java.lang.RuntimeException: stop failed.
	at android.media.MediaRecorder._stop(Native Method)
	at android.media.MediaRecorder.stop(MediaRecorder.java:1339)
	at net.osmand.plus.audionotes.AudioVideoNotesPlugin.stopMediaRecording(AudioVideoNotesPlugin.java:1133)
	at net.osmand.plus.audionotes.AudioVideoNotesPlugin.stopRecording(AudioVideoNotesPlugin.java:1614)
	at net.osmand.plus.audionotes.AudioVideoNotesPlugin$13.onClick(AudioVideoNotesPlugin.java:1605)
	at android.view.View.performClick(View.java:6897)
	at android.view.View$PerformClick.run(View.java:26101)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by Rpnpif** [comment]
I can confirm for photo.
I have the same issue here with Android 7 and OsmAnd 3.0.4 to take a photo note.

I noted that the issue occurred when a quick not needed double touch is done on the icon on the OsmAnd screen..

**Comment by naoliv** [comment]
Maybe the same problem from #3698

**Comment by Rpnpif** [comment]
I am sorry but I am wrong.
My issue concerns also audio note not observed for photo note.

**Comment by vshcherb** [comment]
Same as #3698
