### ISSUE TITLE
CRASH immediately after navigation was startet

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#5969]
First I calulate the route, the I press GO, then the app immediately crashes. It restartes, calculates, crash again, and so on, util I stop navigation.
Map is current germany baden-wuerttemberg, route length 700m, wellknown without problems.
Crash happens on a lot of different test routes, without exception.

See also
https://github.com/osmandapp/Osmand/issues/5968
Regards Peter
---
Version  OsmAnd~ 3.2.0#25787m
02.09.2018 7:20:05
Apk Version : 3.2.0#25787m 320
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Map net.osmand.plus.routing.data.StreetName.toMap()' on a null object reference
	at net.osmand.plus.voice.JSCommandBuilder.convertStreetName(JSCommandBuilder.java:45)
	at net.osmand.plus.voice.JSCommandBuilder.goAhead(JSCommandBuilder.java:78)
	at net.osmand.plus.voice.JSCommandBuilder.goAhead(JSCommandBuilder.java:25)
	at net.osmand.plus.routing.VoiceRouter.approachFavorite(VoiceRouter.java:274)
	at net.osmand.plus.helpers.WaypointHelper.announceVisibleLocations(WaypointHelper.java:432)
	at net.osmand.plus.helpers.WaypointHelper.locationChanged(WaypointHelper.java:102)
	at net.osmand.plus.OsmAndLocationProvider.setLocation(OsmAndLocationProvider.java:808)
	at net.osmand.plus.OsmAndLocationProvider.access$700(OsmAndLocationProvider.java:47)
	at net.osmand.plus.OsmAndLocationProvider$2.onLocationChanged(OsmAndLocationProvider.java:589)
	at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:297)
	at android.location.LocationManager$ListenerTransport.-wrap0(LocationManager.java)
	at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:242)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6776)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
Version  OsmAnd~ 3.2.0#25787m
02.09.2018 7:20:21
Apk Version : 3.2.0#25787m 320
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Map net.osmand.plus.routing.data.StreetName.toMap()' on a null object reference
	at net.osmand.plus.voice.JSCommandBuilder.convertStreetName(JSCommandBuilder.java:45)
	at net.osmand.plus.voice.JSCommandBuilder.goAhead(JSCommandBuilder.java:78)
	at net.osmand.plus.voice.JSCommandBuilder.goAhead(JSCommandBuilder.java:25)
	at net.osmand.plus.routing.VoiceRouter.approachFavorite(VoiceRouter.java:274)
	at net.osmand.plus.helpers.WaypointHelper.announceVisibleLocations(WaypointHelper.java:432)
	at net.osmand.plus.helpers.WaypointHelper.locationChanged(WaypointHelper.java:102)
	at net.osmand.plus.OsmAndLocationProvider.setLocation(OsmAndLocationProvider.java:808)
	at net.osmand.plus.OsmAndLocationProvider.access$700(OsmAndLocationProvider.java:47)
	at net.osmand.plus.OsmAndLocationProvider$2.onLocationChanged(OsmAndLocationProvider.java:589)
	at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:297)
	at android.location.LocationManager$ListenerTransport.-wrap0(LocationManager.java)
	at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:242)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6776)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
Version  OsmAnd~ 3.2.0#25787m
02.09.2018 7:20:36
Apk Version : 3.2.0#25787m 320
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Map net.osmand.plus.routing.data.StreetName.toMap()' on a null object reference
	at net.osmand.plus.voice.JSCommandBuilder.convertStreetName(JSCommandBuilder.java:45)
	at net.osmand.plus.voice.JSCommandBuilder.goAhead(JSCommandBuilder.java:78)
	at net.osmand.plus.voice.JSCommandBuilder.goAhead(JSCommandBuilder.java:25)
	at net.osmand.plus.routing.VoiceRouter.approachFavorite(VoiceRouter.java:274)
	at net.osmand.plus.helpers.WaypointHelper.announceVisibleLocations(WaypointHelper.java:432)
	at net.osmand.plus.helpers.WaypointHelper.locationChanged(WaypointHelper.java:102)
	at net.osmand.plus.OsmAndLocationProvider.setLocation(OsmAndLocationProvider.java:808)
	at net.osmand.plus.OsmAndLocationProvider.access$700(OsmAndLocationProvider.java:47)
	at net.osmand.plus.OsmAndLocationProvider$2.onLocationChanged(OsmAndLocationProvider.java:589)
	at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:297)
	at android.location.LocationManager$ListenerTransport.-wrap0(LocationManager.java)
	at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:242)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6776)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)

**Comment by jfburke3** [comment]
@pebogufi Are you by chance using an external (e.g., Bluetooth) GPS receiver?

**Comment by pebogufi** [comment]
No, never

**Comment by jfburke3** [comment]
What device & Android version are you using?

**Comment by pebogufi** [comment]
Device : gtaxllte
Brand : samsung
Model : SM-T585, Tablet 10,1"
Product : gtaxlltexx
Build : NRD90M.T585XXU3BRF1
Version : 7.0
App Version : OsmAnd~
Apk Version : 3.2.0#25824m 320.       -> bug in this version still present

**Comment by pebogufi** [comment]
Confirm fixed, thanks a lot
Peter
