### ISSUE TITLE
OsmAnd crashes when rendering hiking routes at medium zoomlevels

### ISSUE THREAD

**Issue by pietervdvn** [osmandapp/Osmand#6009]
Hello,

While hiking north of Pécs in Hungary, OsmAnd crashes when trying to render the map at medium zoom levels with hiking routes enabled (color by both osmc and network affiliati on).

This happens with both OsmAnd+ 3.1.5 (beta) and the free 3.1.5, both on my device.

Both use the September maps of Hungary and have the live update of yesterday.

Logs have been submitted via my email address, which is the same as my username on github, followed by @gmail.com

**Comment by PaulStets** [comment]
Here's the log:
```
Version  OsmAnd+ 3.1.5
10.09.2018 10:08:52
Apk Version : 3.1.5 315
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2053)
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2079)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:678)
	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:632)
	at android.support.v4.app.DialogFragment.show(DialogFragment.java:143)
	at net.osmand.plus.osmedit.EditPoiDialogFragment.show(EditPoiDialogFragment.java:392)
	at net.osmand.plus.osmedit.EditPoiDialogFragment$19.onPostExecute(EditPoiDialogFragment.java:707)
	at net.osmand.plus.osmedit.EditPoiDialogFragment$19.onPostExecute(EditPoiDialogFragment.java:697)
	at android.os.AsyncTask.finish(AsyncTask.java:667)
	at android.os.AsyncTask.-wrap1(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```
