### ISSUE TITLE
NPE: Attempt to invoke virtual method 'java.util.Map net.osmand.plus.routing.data.StreetName.toMap()' on a null object reference

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#6025]
With OsmAnd+ 3.2.0 the app crashes very often during navigation. Looks like it is related to the new JS TTS thing. Happens both during real navigation and with simulated positions.

```
Version  OsmAnd+ 3.2.0
11.09.2018 8:05:24
Apk Version : 3.2.0 320
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Map net.osmand.plus.routing.data.StreetName.toMap()' on a null object reference
	at net.osmand.plus.voice.JSCommandBuilder.convertStreetName(JSCommandBuilder.java:45)
	at net.osmand.plus.voice.JSCommandBuilder.goAhead(JSCommandBuilder.java:78)
	at net.osmand.plus.voice.JSCommandBuilder.goAhead(JSCommandBuilder.java:25)
	at net.osmand.plus.routing.VoiceRouter.approachFavorite(VoiceRouter.java:274)
	at net.osmand.plus.helpers.WaypointHelper.announceVisibleLocations(WaypointHelper.java:432)
	at net.osmand.plus.helpers.WaypointHelper.locationChanged(WaypointHelper.java:102)
	at net.osmand.plus.OsmAndLocationProvider.setLocationFromService(OsmAndLocationProvider.java:763)
	at net.osmand.plus.NavigationService.onLocationChanged(NavigationService.java:240)
	at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:297)
	at android.location.LocationManager$ListenerTransport.-wrap0(LocationManager.java)
	at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:242)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by PaulStets** [comment]
Duplicate #5969
