### ISSUE TITLE
Search: crash on jumping to location 

### ISSUE THREAD

**Issue by bugzillus** [osmandapp/Osmand#6171]
Osmand 3.2/3.22 on Lineage 14, offline maps:

Sometimes, when picking a suggested location, Osmand crashes when trying to jump to that location and draw the map on the screen. In v3.22 it seems like a catch routine is added and provides an exception.log (see below). On the last instance, the crash could not be reproduced, it worked at the second try. Before, a crash referring to another location point could be reproduced. Before v3.2, this kind of crashes was not observed.

---

Version  OsmAnd~ 3.2.2
Apk Version : 3.2.2 322
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalStateException: InputStream#read(byte[]) returned invalid result: 0
The InputStream implementation is buggy.
	at com.google.protobuf.CodedInputStream.refillBuffer(CodedInputStream.java:768)
	at com.google.protobuf.CodedInputStream.readRawByte(CodedInputStream.java:798)
	at com.google.protobuf.CodedInputStream.readRawVarint32(CodedInputStream.java:379)
	at net.osmand.binary.BinaryMapIndexReader.preloadStreets(BinaryMapIndexReader.java:651)
	at net.osmand.plus.search.QuickSearchListFragment.isCityEmpty(QuickSearchListFragment.java:138)
	at
net.osmand.plus.search.QuickSearchListFragment.onListItemClick(QuickSearchListFragment.java:106)
	at android.support.v4.app.ListFragment$2.onItemClick(ListFragment.java:62)
	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1164)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3139)
	at android.widget.AbsListView$3.run(AbsListView.java:4054)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by dmpr0** [comment]
I have this too.
Open Route Preparation > Select Destination > Address > Select city.
[exception (19).log](https://github.com/osmandapp/Osmand/files/3018088/exception.19.log)
