### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6332]
OsmAnd frequently keeps crashing on start-up. When it does not crash it shows a relief map but no content with an error message: unable to draw selected area.
[exception[1] (1).log](https://github.com/osmandapp/Osmand/files/2640272/exception.1.1.log)

**Comment by scaidermern** [comment]
Just in case anyone else is experiencing the same issue, looks like it has something to do with the rendering of GPX tracks:

```
Version  OsmAnd+ 3.2.6
19.11.2018 5:57:32
Apk Version : 3.2.6 326
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'net.osmand.render.RenderingRule net.osmand.render.RenderingRulesStorage.getRenderingAttributeRule(java.lang.String)' on a null object reference
	at net.osmand.plus.dialogs.ConfigureMapMenu$GpxAppearanceAdapter.parseTrackColor(ConfigureMapMenu.java:1362)
	at net.osmand.plus.myplaces.TrackActivityFragmentAdapter.updateColorView(TrackActivityFragmentAdapter.java:678)
	at net.osmand.plus.myplaces.TrackActivityFragmentAdapter.updateHeader(TrackActivityFragmentAdapter.java:350)
	at net.osmand.plus.myplaces.TrackActivityFragmentAdapter.onCreateView(TrackActivityFragmentAdapter.java:189)
	at net.osmand.plus.myplaces.TrackSegmentFragment.onCreateView(TrackSegmentFragment.java:123)
```

**Comment by alyonapinchuk** [comment]
The same issue has been reported. At startup, the app gives the message:  "Error occurred during map generation of the selected area"  and  "Native library is not supported". Also, the app crashes when opening a gpx file. 
[exception.log](https://github.com/osmandapp/Osmand/files/2645998/exception.log)

**Comment by jfburke3** [comment]
I haven't encountered this in a long time.  Does deleting ind.cache or regions.ocbf help?

**Comment by MadWasp79** [comment]
closed with https://github.com/osmandapp/Osmand/commit/dd58cac8315c6d1cb90c0b59b53bd7ef8f97b1db
