### ISSUE TITLE
Crash when opening menu

### ISSUE THREAD

**Issue by orvly** [osmandapp/Osmand#6382]
**Description:**
OsmAnd crashes when tapping on the menu (hamburger menu)
Before doing that, panning in all direction and zooming in/out works fine.
Location tracking based on current location also works fine, and so does navigation.
The crash occurs even if tapping on the menu right after application start.

I've copied and pasted the crash file below.

**What version of OsmAnd are you using, on what device and Android/iOS version?**

OsmAnd 3.2.7
Samsung A5 2017
Android 8.0.0
Device language is Hebrew, a right-to-left language, maybe it's relevant.

**Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?**
Offline maps

**If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.**
Not relevant.

---

Exception stack trace:

```
Version  OsmAnd 3.2.7
12.12.2018 7:07:13
Apk Version : 3.2.7 327
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalArgumentException: No drawer view found with gravity LEFT
	at android.support.v4.widget.DrawerLayout.openDrawer(DrawerLayout.java:1639)
	at net.osmand.plus.activities.MapActivity.openDrawer(MapActivity.java:1577)
	at net.osmand.plus.views.MapControlsLayer$9.onClick(MapControlsLayer.java:435)
	at android.view.View.performClick(View.java:6897)
	at android.view.View$PerformClick.run(View.java:26101)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

```

**Comment by MadWasp79** [comment]
fixed with https://github.com/osmandapp/Osmand/pull/6443/commits/e1e5250470ad5c8760db33354664f44b5da3c144

**Comment by dosshra** [comment]
Still, have this issue with tapping on the menu (hamburger menu) when I Use Hebrew as the language of the device. Switching to English menus solves the problem.
