### ISSUE TITLE
OsmAnd freezes (ANR) when I select a bus stop in Minsk, Belarus

### ISSUE THREAD

**Issue by vi** [osmandapp/Osmand#6408]
Snippet from adb logcat:

```
12-30 02:36:52.527 I/net.osmand(18947): BinaryMapAddressReaderAdapter Searched address structure in 328ms. Found 1 subtress
12-30 02:36:52.531 I/net.osmand(18947): BinaryMapAddressReaderAdapter Whole address search by name is done in 332ms. Found 1
12-30 02:36:52.532 I/net.osmand(18947): GeocodingUtilities Preload buildings улица Багратиона Минск 1837
12-30 02:36:52.532 I/net.osmand(18947): GeocodingUtilities Search street by name Запорожская площадь [запорожская]
12-30 02:36:52.532 I/net.osmand(18947): Postcode Not matches Belarus's postcode regex: ЗАПОРОЖСКАЯ
12-30 02:36:52.843 I/net.osmand(18947): BinaryMapAddressReaderAdapter Searched address structure in 310ms. Found 1 subtress
12-30 02:36:52.847 I/net.osmand(18947): BinaryMapAddressReaderAdapter Whole address search by name is done in 314ms. Found 2
12-30 02:36:52.847 I/net.osmand(18947): GeocodingUtilities Preload buildings Запорожская площадь Минск 1846
12-30 02:36:52.848 I/net.osmand(18947): GeocodingUtilities Preload buildings Запорожская улица Минск 1840
12-30 02:36:52.848 I/net.osmand(18947): GeocodingUtilities Search street by name 2-й переулок Багратиона [2-й, багратиона]
12-30 02:36:52.848 I/net.osmand(18947): Postcode Not matches Belarus's postcode regex: БАГРАТИОНА
12-30 02:36:53.159 I/net.osmand(18947): BinaryMapAddressReaderAdapter Searched address structure in 310ms. Found 1 subtress
12-30 02:36:53.163 I/net.osmand(18947): BinaryMapAddressReaderAdapter Whole address search by name is done in 314ms. Found 2
12-30 02:36:53.164 I/net.osmand(18947): GeocodingUtilities Preload buildings 2-й переулок Багратиона Минск 1845
12-30 02:36:53.164 I/net.osmand(18947): GeocodingUtilities Preload buildings 2-й переулок Багратиона Слепянка 547
12-30 02:36:53.164 I/net.osmand(18947): GeocodingUtilities Search street by name Авангардная улица [авангардная]
12-30 02:36:53.165 I/net.osmand(18947): Postcode Not matches Belarus's postcode regex: АВАНГАРДНАЯ
12-30 02:36:53.476 I/net.osmand(18947): BinaryMapAddressReaderAdapter Searched address structure in 311ms. Found 1 subtress
12-30 02:36:53.478 I/net.osmand(18947): BinaryMapAddressReaderAdapter Whole address search by name is done in 313ms. Found 1
12-30 02:36:53.479 I/net.osmand(18947): GeocodingUtilities Preload buildings Авангардная улица Минск 1847
12-30 02:36:53.479 I/net.osmand(18947): GeocodingUtilities Search street by name 1-й Запорожский переулок [1-й, запорожский]
12-30 02:36:53.479 I/net.osmand(18947): Postcode Not matches Belarus's postcode regex: ЗАПОРОЖСКИЙ
12-30 02:36:53.820 I/net.osmand(18947): BinaryMapAddressReaderAdapter Searched address structure in 341ms. Found 1 subtress
12-30 02:36:53.823 I/net.osmand(18947): BinaryMapAddressReaderAdapter Whole address search by name is done in 344ms. Found 1
12-30 02:36:53.824 I/net.osmand(18947): GeocodingUtilities Preload buildings 1-й Запорожский переулок Минск 1839
12-30 02:36:53.824 I/net.osmand(18947): GeocodingUtilities Search street by name проезд Металлистов [металлистов]
12-30 02:36:53.824 I/net.osmand(18947): Postcode Not matches Belarus's postcode regex: МЕТАЛЛИСТОВ
12-30 02:36:54.162 I/net.osmand(18947): BinaryMapAddressReaderAdapter Searched address structure in 338ms. Found 1 subtress
12-30 02:36:54.165 I/net.osmand(18947): BinaryMapAddressReaderAdapter Whole address search by name is done in 341ms. Found 1
12-30 02:36:54.165 I/net.osmand(18947): GeocodingUtilities Preload buildings проезд Металлистов Минск 4213
12-30 02:36:58.222 D/WifiConfigStore(  779): Retrieve network priorities after PNO.
12-30 02:36:58.717 D/net.osmand(18947): OsmandMapTileView On click event 469.0 1129.0
12-30 02:36:58.766 I/net.osmand(18947): BinaryMapPoiReaderAdapter Searched poi structure in 39 ms. Found 0 subtrees
12-30 02:36:58.767 I/net.osmand(18947): BinaryMapIndexReader Read 932 subtrees. Go through 6 subtrees.
12-30 02:36:58.767 I/net.osmand(18947): BinaryMapIndexReader Search poi is done. Visit 0 objects. Read 0 objects.
12-30 02:36:58.767 D/net.osmand(18947): AmenityIndexRepositoryBinary Search for 53.90911635844845 27.63108730316162 done in 40 ms found 0.
12-30 02:36:58.771 I/net.osmand(18947): BinaryMapPoiReaderAdapter Searched poi structure in 4 ms. Found 4 subtrees
12-30 02:36:58.777 I/net.osmand(18947): BinaryMapIndexReader Read 46 subtrees. Go through 10 subtrees.
12-30 02:36:58.778 I/net.osmand(18947): BinaryMapIndexReader Search poi is done. Visit 100 objects. Read 8 objects.
12-30 02:36:58.778 D/net.osmand(18947): AmenityIndexRepositoryBinary Search for 53.90911635844845 27.63108730316162 done in 11 ms found 8.
```

Snippet from `/data/anr/traces.txt` (also [attached](https://github.com/osmandapp/Osmand/files/2716791/traces.txt)):

```
"main" prio=5 tid=1 Suspended
  | group="main" sCount=1 dsCount=0 obj=0x733db2a0 self=0xb4d36500
  | sysTid=18947 nice=0 cgrp=default sched=0/0 handle=0xb6f30b34
  | state=S schedstat=( 25832681788 5924356317 33867 ) utm=2463 stm=120 core=1 HZ=100
  | stack=0xbe21a000-0xbe21c000 stackSize=8MB
  | held mutexes=
  at com.google.protobuf.CodedInputStream.refillBuffer(CodedInputStream.java:-1)
  at com.google.protobuf.CodedInputStream.isAtEnd(CodedInputStream.java:718)
  at com.google.protobuf.CodedInputStream.readTag(CodedInputStream.java:105)
  at net.osmand.binary.BinaryMapTransportReaderAdapter.initializeStringTable(BinaryMapTransportReaderAdapter.java:398)
  at net.osmand.binary.BinaryMapIndexReader.searchTransportIndex(BinaryMapIndexReader.java:570)
  at net.osmand.plus.resources.TransportIndexRepositoryBinary.searchTransportStops(TransportIndexRepositoryBinary.java:48)
  - locked <0x0342ea7b> (a net.osmand.plus.resources.TransportIndexRepositoryBinary)
  at net.osmand.plus.views.ContextMenuLayer.findTransportStopsAt(ContextMenuLayer.java:912)
  at net.osmand.plus.views.ContextMenuLayer.processTransportStops(ContextMenuLayer.java:857)
  at net.osmand.plus.views.ContextMenuLayer.showContextMenu(ContextMenuLayer.java:749)
  at net.osmand.plus.views.ContextMenuLayer.onSingleTap(ContextMenuLayer.java:999)
  at net.osmand.plus.views.OsmandMapTileView$MapTileViewOnGestureListener.onSingleTapConfirmed(OsmandMapTileView.java:1356)
  at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:300)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:148)
  at android.app.ActivityThread.main(ActivityThread.java:5417)
  at java.lang.reflect.Method.invoke!(Native method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

OsmAnd~ 3.2.7 from F-Droid repo.
Device has Android 6.0.1, issue also reproducible on another device with Android 4.4. Issue also reproducible with a bit older OsmAnd~ version.

**Comment by vi** [comment]
Verified that a bus stop in Zürich, Switzerland is selectable, on a map by "Jan 1, 2018" and by "Dec 1, 2018". Bus info is present.

Verified that a bus stop in Astana, Kazahkstan by "Mar 5, 2016" or by "Dec 1, 2018" is selectable (no bus info although).

**Comment by MadWasp79** [comment]
fixed with https://github.com/osmandapp/Osmand/pull/6443/commits/f7d3e72fb113f346e11e420bb591fbcb752bbc30
