### ISSUE TITLE
Crash while navigation, if map screen returns from background

### ISSUE THREAD

**Issue by Zahnstocher** [osmandapp/Osmand#6570]
Latest nightly.
Start OsmAnd.
Wait for GPS fix.
Start Navigation.
Send map activity to background (for example open OsmAnd settings or open another app).
Try to go back to OsmAnd map screen.
Crash:
```
AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'net.osmand.data.LatLon net.osmand.plus.TargetPointsHelper$TargetPoint.point' on a null object reference
AndroidRuntime:        at net.osmand.plus.TargetPointsHelper.lookupAddressForMyLocationPoint(TargetPointsHelper.java:316)
AndroidRuntime:        at net.osmand.plus.TargetPointsHelper.lookupAddessAll(TargetPointsHelper.java:163)
AndroidRuntime:        at net.osmand.plus.activities.MapActivity$3.onProgress(MapActivity.java:393)
AndroidRuntime:        at net.osmand.plus.AppInitializer$8.run(AppInitializer.java:832)
AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6981)
AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```
After this, OsmAnd crashes on every OsmAnd start.

**Comment by Zahnstocher** [comment]
Fixed:
https://github.com/osmandapp/Osmand/commit/47538b845258b2e3c513056e3a6ff59dbc164621#diff-528ca3bdb63dbb288a9c851c64480658
