### ISSUE TITLE
Crash quick action Map Layer

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#6884]
Воспроизводится проблема так:
Активируем "Быстрое действие"
Добавляем туда "Изменить стиль карты"
Жмем на него и  крашимся

Version  OsmAnd~ 3.3.7
01.05.2019 12:31:54
Apk Version : 3.3.7 337
Exception occured in thread Thread[main,5,main] : 
java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
  at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:260)
  at java.util.ArrayList.get(ArrayList.java:313)
  at net.osmand.plus.quickaction.actions.MapStyleAction.execute(MapStyleAction.java:54)
  at net.osmand.plus.views.MapQuickActionLayer.onActionSelected(MapQuickActionLayer.java:429)
  at net.osmand.plus.quickaction.QuickActionsWidget$4.onClick(QuickActionsWidget.java:244)
  at android.view.View.performClick(View.java:5265)
  at android.view.View$PerformClick.run(View.java:21534)
  at android.os.Handler.handleCallback(Handler.java:815)
  at android.os.Handler.dispatchMessage(Handler.java:104)
  at android.os.Looper.loop(Looper.java:207)
  at android.app.ActivityThread.main(ActivityThread.java:5728)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
  at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

**Comment by MadWasp79** [comment]
closed with https://github.com/osmandapp/Osmand/commit/c6a1f997baec3cda11bde6c9c0080bb904cfacca
