### ISSUE TITLE
Crashes every use

### ISSUE THREAD

**Issue by captlightfoot** [osmandapp/Osmand#6919]
I have no idea what it going on, hope I can find some help here. Here is the log I received in my last crash.

> Version  OsmAnd+ 3.3.6
03.04.2019 4:25:31
Apk Version : 3.3.6 336
Exception occured in thread Thread[main,5,main] : 
java.lang.OutOfMemoryError: Failed to allocate a 36112 byte allocation with 28220 free bytes and 27KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:917)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:837)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:762)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:742)
	at android.app.Notification.cloneInto(Notification.java:1743)
	at android.app.Notification.clone(Notification.java:1711)
	at android.app.NotificationManager.notify(NotificationManager.java:182)
	at android.support.v4.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:210)
	at android.support.v4.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:194)
	at net.osmand.plus.notifications.OsmandNotification.refreshNotification(OsmandNotification.java:142)
	at net.osmand.plus.NotificationHelper.refreshNotification(NotificationHelper.java:102)
	at net.osmand.plus.routing.RoutingHelper.updateCurrentRouteStatus(RoutingHelper.java:500)
	at net.osmand.plus.routing.RoutingHelper.setCurrentLocation(RoutingHelper.java:332)
	at net.osmand.plus.routing.RoutingHelper.setCurrentLocation(RoutingHelper.java:293)
	at net.osmand.plus.OsmAndLocationProvider.setLocation(OsmAndLocationProvider.java:802)
	at net.osmand.plus.OsmAndLocationProvider.access$700(OsmAndLocationProvider.java:47)
	at net.osmand.plus.OsmAndLocationProvider$2.onLocationChanged(OsmAndLocationProvider.java:590)
	at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:286)
	at android.location.LocationManager$ListenerTransport.access$000(LocationManager.java:215)
	at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:231)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6939)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Version  OsmAnd+ 3.3.6
04.04.2019 11:14:25
Apk Version : 3.3.6 336
Exception occured in thread Thread[RenderingBaseImage,5,main] : 
java.lang.OutOfMemoryError: Failed to allocate a 377008 byte allocation with 126740 free bytes and 123KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:917)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:848)
	at net.osmand.plus.views.MapTileLayer.drawTileMap(MapTileLayer.java:242)
	at net.osmand.plus.views.MapTileLayer.onPrepareBufferImage(MapTileLayer.java:124)
	at net.osmand.plus.srtmplugin.HillshadeLayer.onPrepareBufferImage(HillshadeLayer.java:59)
	at net.osmand.plus.views.OsmandMapTileView.refreshBaseMapInternal(OsmandMapTileView.java:590)
	at net.osmand.plus.views.OsmandMapTileView.access$900(OsmandMapTileView.java:62)
	at net.osmand.plus.views.OsmandMapTileView$2.run(OsmandMapTileView.java:791)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Version  OsmAnd+ 3.3.6
06.04.2019 4:40:41
Apk Version : 3.3.6 336
Exception occured in thread Thread[RenderingBaseImage,5,main] : 
java.lang.OutOfMemoryError: Failed to allocate a 377008 byte allocation with 135944 free bytes and 132KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:917)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:848)
	at net.osmand.plus.views.MapTileLayer.drawTileMap(MapTileLayer.java:242)
	at net.osmand.plus.views.MapTileLayer.onPrepareBufferImage(MapTileLayer.java:124)
	at net.osmand.plus.srtmplugin.HillshadeLayer.onPrepareBufferImage(HillshadeLayer.java:59)
	at net.osmand.plus.views.OsmandMapTileView.refreshBaseMapInternal(OsmandMapTileView.java:590)
	at net.osmand.plus.views.OsmandMapTileView.access$900(OsmandMapTileView.java:62)
	at net.osmand.plus.views.OsmandMapTileView$2.run(OsmandMapTileView.java:791)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Version  OsmAnd+ 3.3.6
07.04.2019 10:45:12
Apk Version : 3.3.6 336
Exception occured in thread Thread[RenderingBaseImage,5,main] : 
java.lang.OutOfMemoryError: Failed to allocate a 377008 byte allocation with 355504 free bytes and 347KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:917)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:848)
	at net.osmand.plus.views.MapTileLayer.drawTileMap(MapTileLayer.java:242)
	at net.osmand.plus.views.MapTileLayer.onPrepareBufferImage(MapTileLayer.java:124)
	at net.osmand.plus.srtmplugin.HillshadeLayer.onPrepareBufferImage(HillshadeLayer.java:59)
	at net.osmand.plus.views.OsmandMapTileView.refreshBaseMapInternal(OsmandMapTileView.java:590)
	at net.osmand.plus.views.OsmandMapTileView.access$900(OsmandMapTileView.java:62)
	at net.osmand.plus.views.OsmandMapTileView$2.run(OsmandMapTileView.java:791)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Version  OsmAnd+ 3.3.6
13.04.2019 4:00:59
Apk Version : 3.3.6 336
Exception occured in thread Thread[RenderingBaseImage,5,main] : 
java.lang.OutOfMemoryError: Failed to allocate a 377008 byte allocation with 145736 free bytes and 142KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:917)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:848)
	at net.osmand.plus.views.MapTileLayer.drawTileMap(MapTileLayer.java:242)
	at net.osmand.plus.views.MapTileLayer.onPrepareBufferImage(MapTileLayer.java:124)
	at net.osmand.plus.srtmplugin.HillshadeLayer.onPrepareBufferImage(HillshadeLayer.java:59)
	at net.osmand.plus.views.OsmandMapTileView.refreshBaseMapInternal(OsmandMapTileView.java:590)
	at net.osmand.plus.views.OsmandMapTileView.access$900(OsmandMapTileView.java:62)
	at net.osmand.plus.views.OsmandMapTileView$2.run(OsmandMapTileView.java:791)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Version  OsmAnd+ 3.3.6
13.04.2019 4:43:51
Apk Version : 3.3.6 336
Exception occured in thread Thread[RenderingBaseImage,5,main] : 
java.lang.OutOfMemoryError: Failed to allocate a 377008 byte allocation with 276020 free bytes and 269KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:917)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:848)
	at net.osmand.plus.views.MapTileLayer.drawTileMap(MapTileLayer.java:242)
	at net.osmand.plus.views.MapTileLayer.onPrepareBufferImage(MapTileLayer.java:124)
	at net.osmand.plus.srtmplugin.HillshadeLayer.onPrepareBufferImage(HillshadeLayer.java:59)
	at net.osmand.plus.views.OsmandMapTileView.refreshBaseMapInternal(OsmandMapTileView.java:590)
	at net.osmand.plus.views.OsmandMapTileView.access$900(OsmandMapTileView.java:62)
	at net.osmand.plus.views.OsmandMapTileView$2.run(OsmandMapTileView.java:791)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Version  OsmAnd+ 3.3.6
14.04.2019 1:20:03
Apk Version : 3.3.6 336
Exception occured in thread Thread[RenderingBaseImage,5,main] : 
java.lang.OutOfMemoryError: Failed to allocate a 377008 byte allocation with 130412 free bytes and 127KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:917)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:848)
	at net.osmand.plus.views.MapTileLayer.drawTileMap(MapTileLayer.java:242)
	at net.osmand.plus.views.MapTileLayer.onPrepareBufferImage(MapTileLayer.java:124)
	at net.osmand.plus.srtmplugin.HillshadeLayer.onPrepareBufferImage(HillshadeLayer.java:59)
	at net.osmand.plus.views.OsmandMapTileView.refreshBaseMapInternal(OsmandMapTileView.java:590)
	at net.osmand.plus.views.OsmandMapTileView.access$900(OsmandMapTileView.java:62)
	at net.osmand.plus.views.OsmandMapTileView$2.run(OsmandMapTileView.java:791)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Version  OsmAnd+ 3.3.6
14.04.2019 2:36:39
Apk Version : 3.3.6 336
Exception occured in thread Thread[RenderingBaseImage,5,main] : 
java.lang.OutOfMemoryError: Failed to allocate a 377008 byte allocation with 359696 free bytes and 351KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:917)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:848)
	at net.osmand.plus.views.MapTileLayer.drawTileMap(MapTileLayer.java:242)
	at net.osmand.plus.views.MapTileLayer.onPrepareBufferImage(MapTileLayer.java:124)
	at net.osmand.plus.srtmplugin.HillshadeLayer.onPrepareBufferImage(HillshadeLayer.java:59)
	at net.osmand.plus.views.OsmandMapTileView.refreshBaseMapInternal(OsmandMapTileView.java:590)
	at net.osmand.plus.views.OsmandMapTileView.access$900(OsmandMapTileView.java:62)
	at net.osmand.plus.views.OsmandMapTileView$2.run(OsmandMapTileView.java:791)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Version  OsmAnd+ 3.3.6
25.04.2019 3:44:41
Apk Version : 3.3.6 336
Exception occured in thread Thread[RenderingBaseImage,5,main] : 
java.lang.OutOfMemoryError: Failed to allocate a 377008 byte allocation with 317260 free bytes and 309KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:917)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:848)
	at net.osmand.plus.views.MapTileLayer.drawTileMap(MapTileLayer.java:242)
	at net.osmand.plus.views.MapTileLayer.onPrepareBufferImage(MapTileLayer.java:124)
	at net.osmand.plus.srtmplugin.HillshadeLayer.onPrepareBufferImage(HillshadeLayer.java:59)
	at net.osmand.plus.views.OsmandMapTileView.refreshBaseMapInternal(OsmandMapTileView.java:590)
	at net.osmand.plus.views.OsmandMapTileView.access$900(OsmandMapTileView.java:62)
	at net.osmand.plus.views.OsmandMapTileView$2.run(OsmandMapTileView.java:791)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Version  OsmAnd+ 3.3.6
28.04.2019 12:10:29
Apk Version : 3.3.6 336
Exception occured in thread Thread[RenderingBaseImage,5,main] : 
java.lang.OutOfMemoryError: Failed to allocate a 377008 byte allocation with 180104 free bytes and 175KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:917)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:848)
	at net.osmand.plus.views.MapTileLayer.drawTileMap(MapTileLayer.java:242)
	at net.osmand.plus.views.MapTileLayer.onPrepareBufferImage(MapTileLayer.java:124)
	at net.osmand.plus.srtmplugin.HillshadeLayer.onPrepareBufferImage(HillshadeLayer.java:59)
	at net.osmand.plus.views.OsmandMapTileView.refreshBaseMapInternal(OsmandMapTileView.java:590)
	at net.osmand.plus.views.OsmandMapTileView.access$900(OsmandMapTileView.java:62)
	at net.osmand.plus.views.OsmandMapTileView$2.run(OsmandMapTileView.java:791)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Version  OsmAnd+ 3.3.6
29.04.2019 8:38:41
Apk Version : 3.3.6 336
Exception occured in thread Thread[RenderingBaseImage,5,main] : 
java.lang.OutOfMemoryError: Failed to allocate a 377008 byte allocation with 49348 free bytes and 48KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:917)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:848)
	at net.osmand.plus.views.MapTileLayer.drawTileMap(MapTileLayer.java:242)
	at net.osmand.plus.views.MapTileLayer.onPrepareBufferImage(MapTileLayer.java:124)
	at net.osmand.plus.srtmplugin.HillshadeLayer.onPrepareBufferImage(HillshadeLayer.java:59)
	at net.osmand.plus.views.OsmandMapTileView.refreshBaseMapInternal(OsmandMapTileView.java:590)
	at net.osmand.plus.views.OsmandMapTileView.access$900(OsmandMapTileView.java:62)
	at net.osmand.plus.views.OsmandMapTileView$2.run(OsmandMapTileView.java:791)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Version  OsmAnd+ 3.3.6
08.05.2019 7:21:47
Apk Version : 3.3.6 336
Exception occured in thread Thread[RenderingBaseImage,5,main] : 
java.lang.OutOfMemoryError: Failed to allocate a 377008 byte allocation with 208300 free bytes and 203KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:917)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:848)
	at net.osmand.plus.views.MapTileLayer.drawTileMap(MapTileLayer.java:242)
	at net.osmand.plus.views.MapTileLayer.onPrepareBufferImage(MapTileLayer.java:124)
	at net.osmand.plus.srtmplugin.HillshadeLayer.onPrepareBufferImage(HillshadeLayer.java:59)
	at net.osmand.plus.views.OsmandMapTileView.refreshBaseMapInternal(OsmandMapTileView.java:590)
	at net.osmand.plus.views.OsmandMapTileView.access$900(OsmandMapTileView.java:62)
	at net.osmand.plus.views.OsmandMapTileView$2.run(OsmandMapTileView.java:791)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by vshcherb** [comment]
Not enough memory Java memory, not sure what can help. Probably reducing number of layers and using vector map (c++ memory)
