### ISSUE TITLE
Crash on zooming in/out

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#6958]
The app closes every time while zooming in and out. 
Xiaomi Redmi Note 4.
[exception.log](https://github.com/osmandapp/Osmand/files/3198287/exception.log)

**Comment by scaidermern** [comment]
```
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/system/app/Chrome/Chrome.apk!/lib/armeabi-v7a/libmonochrome.so" is 32-bit instead of 64-bit
	at java.lang.Runtime.loadLibrary0(Runtime.java:977)
	at java.lang.System.loadLibrary(System.java:1530)
	at org.chromium.base.library_loader.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:89)
	... 37 more
```

**Comment by vshcherb** [comment]
Either chrome should be updated or only 32bit OsmAnd version should be used.
