### ISSUE TITLE
crash with new version / new profile handling

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#7001]
New version 3.3.0#27421 does not use routing.xml, neither in dir files not in subdir files/routing.
I made some specific changes example
		< parameter id="height" name="Height" description="Maximum vehicle height to be permitted on the route" type="numeric" values="0,1.49,1.99,**2.79**,2.99,3.49,3.99,4.49,4.99,5.49,5.99,6.49,6.99,7.49" valueDescriptions="-,1.5m,2m,**2.8m**,3m,3.5m,4m,4.5m,5m,5.5m,6m,6.5m,7m,7.5m"/>	

and more, but they are not visble.

**Comment by dmpr0** [comment]
Hello @pebogufi, now you need to create an app profile to use your routing file, you can do it in Settings > App Profiles > Add > Select base profile > Navigation type > Selecting an item from your custom file.

**Comment by pebogufi** [comment]
ok.
When using new profile:
When I am in map markers  and click
Appearance on the map
I get a crash.

Version  OsmAnd~ 3.3.0#27421m
31.05.2019 6:03:17
Apk Version : 3.3.0#27421m 330
Exception occured in thread Thread[main,5,main] : 
android.content.res.Resources$NotFoundException: String resource ID #0xffffffff
	at android.content.res.Resources.getText(Resources.java:354)
	at android.widget.TextView.setText(TextView.java:6135)
	at net.osmand.plus.mapmarkers.DirectionIndicationDialogFragment.onCreateView(DirectionIndicationDialogFragment.java:78)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:7000)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by MadWasp79** [comment]
closed with #7001
