### ISSUE TITLE
NPE crash & Crash upon sending the error report

### ISSUE THREAD

**Issue by Famlam** [osmandapp/Osmand#7012]
I got the following NPE exception. I don't remember exactly what I was doing unfortunately (I recall I was looking at the route details and tried to go back to the map), so hopefully this is still helpful.

Also, while trying to send the report after the app restarted, I got another crash.
Please find below the exception log.
(Android 5.1)

```
Version  OsmAnd 3.3.8
05.06.2019 10:49:12
Apk Version : 3.3.8 338
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.github.mikephil.charting.data.LineData.getDataSets()' on a null object reference
	at net.osmand.plus.mapcontextmenu.other.TrackDetailsMenu.getTrackSegment(TrackDetailsMenu.java:219)
	at net.osmand.plus.mapcontextmenu.other.TrackDetailsMenu.refreshChart(TrackDetailsMenu.java:413)
	at net.osmand.plus.routepreparationmenu.RouteDetailsFragment.refreshChart(RouteDetailsFragment.java:1675)
	at net.osmand.plus.routepreparationmenu.RouteDetailsFragment.calculateLayout(RouteDetailsFragment.java:411)
	at net.osmand.plus.base.ContextMenuFragment$4.onGlobalLayout(ContextMenuFragment.java:881)
	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:912)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1954)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1117)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6184)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:773)
	at android.view.Choreographer.doCallbacks(Choreographer.java:586)
	at android.view.Choreographer.doFrame(Choreographer.java:556)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:759)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5421)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
Version  OsmAnd 3.3.8
05.06.2019 10:49:29
Apk Version : 3.3.8 338
Exception occured in thread Thread[main,5,main] : 
android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
	at android.app.ContextImpl.startActivity(ContextImpl.java:1420)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1407)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:323)
	at net.osmand.plus.OsmandApplication.sendCrashLog(OsmandApplication.java:1065)
	at net.osmand.plus.dialogs.ErrorBottomSheetDialog$1.onClick(ErrorBottomSheetDialog.java:46)
	at android.view.View.performClick(View.java:4802)
	at android.view.View$PerformClick.run(View.java:20058)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5421)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
Version  OsmAnd 3.3.8
05.06.2019 10:49:50
Apk Version : 3.3.8 338
Exception occured in thread Thread[main,5,main] : 
android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
	at android.app.ContextImpl.startActivity(ContextImpl.java:1420)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1407)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:323)
	at net.osmand.plus.OsmandApplication.sendCrashLog(OsmandApplication.java:1065)
	at net.osmand.plus.dialogs.ErrorBottomSheetDialog$1.onClick(ErrorBottomSheetDialog.java:46)
	at android.view.View.performClick(View.java:4802)
	at android.view.View$PerformClick.run(View.java:20058)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5421)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
```

**Comment by Chumva** [comment]
NPE was fixed here https://github.com/osmandapp/Osmand/commit/3d0d79136a10080b05514d133f21118e1a8ce8cf and error with sending logs also has been fixed https://github.com/osmandapp/Osmand/commit/874bb9f08d5a9dee1e1d01bb72e11cb246c751d6
