### ISSUE TITLE
Crash while opening OsmAnd + untranslated message in Russian

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#7062]
I've got a new phone, installed the latest nightly version and just opened OsmAnd:

```
Version  OsmAnd Nightly 3.3.0#24338d
19.06.2019 5:15:10
Apk Version : 3.3.0#24338d 330
Exception occured in thread Thread[main,5,main] : 
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{80d7a90 u0 net.osmand.dev/net.osmand.plus.download.DownloadService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1740)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6694)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

And I guess that the error message should be, at least, in English:

![](https://user-images.githubusercontent.com/982338/59800227-66efa880-92bc-11e9-994b-db0a664a8b2f.png)

**Comment by Zahnstocher** [comment]
I got the same crash after downloading a map.
Android 9
latest OsmAnd nightly build
```
Exception occured in thread Thread[main,5,main] : 
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{d5762b5 u0 net.osmand.plus/.download.DownloadService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1855)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:6986)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```
