### ISSUE TITLE
Crash while uploading OSM edit

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#7069]
```
Version  OsmAnd+ 3.3.8
06.06.2019 4:12:18
Apk Version : 3.3.8 338
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2053)
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2079)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:678)
	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:632)
	at android.support.v4.app.DialogFragment.show(DialogFragment.java:143)
	at net.osmand.plus.osmedit.OsmEditsUploadListenerHelper.uploadEnded(OsmEditsUploadListenerHelper.java:83)
	at net.osmand.plus.osmedit.dialogs.SendPoiDialogFragment$SimpleProgressDialogPoiUploader$1.uploadEnded(SendPoiDialogFragment.java:264)
	at net.osmand.plus.osmedit.UploadOpenstreetmapPointAsyncTask.onPostExecute(UploadOpenstreetmapPointAsyncTask.java:103)
	at net.osmand.plus.osmedit.UploadOpenstreetmapPointAsyncTask.onPostExecute(UploadOpenstreetmapPointAsyncTask.java:16)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.-wrap1(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

I think this was caused by disabling data connection during upload (because it took too long due to low signal quality). So not a big deal since it occurs only rarely.

**Comment by vshcherb** [comment]
Looks like this https://stackoverflow.com/questions/7575921/illegalstateexception-can-not-perform-this-action-after-onsaveinstancestate-wit
