### ISSUE TITLE
Increasing Out of Memory crashes lately?

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#7774]
I occasiobaly see OoM crashes with nighlies in the last few weeks while driving with a calculated route (but without follow mode). Never used to see that before, but also not sure we can do much about it?

They all look like this:

```
Version  OsmAnd~ 3.4.0#3711des
28.10.2019 6:11:59
Apk Version : 3.4.0#3711des 340
Exception occured in thread Thread[RenderingBaseImage,5,main] : 
java.lang.OutOfMemoryError
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:928)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:901)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:833)
	at net.osmand.plus.views.MapTileLayer.drawTileMap(MapTileLayer.java:242)
	at net.osmand.plus.views.MapTileLayer.onPrepareBufferImage(MapTileLayer.java:124)
	at net.osmand.plus.srtmplugin.HillshadeLayer.onPrepareBufferImage(HillshadeLayer.java:59)
	at net.osmand.plus.views.OsmandMapTileView.refreshBaseMapInternal(OsmandMapTileView.java:590)
	at net.osmand.plus.views.OsmandMapTileView.access$900(OsmandMapTileView.java:62)
	at net.osmand.plus.views.OsmandMapTileView$2.run(OsmandMapTileView.java:791)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:146)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by vshcherb** [comment]
That's possible though we need to take the dump cause bitmaps are always taking the most space and mostly visible in crashes but problem should be somewhere else

**Comment by sonora** [comment]
So maybe let us implement method 3 of that article into our code?
