### ISSUE TITLE
App crashes when trying to enter a destination

### ISSUE THREAD

**Issue by bigtreiber** [osmandapp/Osmand#7945]
I've just updated OsmAnd to 3.5.2 on Android (LOS 16) and have an issue when trying to enter a destination for routing. The app always crashes. This didn't happen in 3.4.8.
I'm using offline maps.

Crash log shows:
    
    Version  OsmAnd~ 3.5.2
    16.11.2019 9:30:38
    Apk Version : 3.5.2 352
    Exception occured in thread Thread[main,5,main] : 
    java.util.UnknownFormatConversionException: Conversion = ' '
	at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2781)
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2811)
	at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2624)
	at java.util.Formatter.parse(Formatter.java:2557)
	at java.util.Formatter.format(Formatter.java:2504)
	at java.util.Formatter.format(Formatter.java:2458)
	at java.lang.String.format(String.java:2883)
	at android.content.res.Resources.getString(Resources.java:466)
	at android.support.v4.app.Fragment.getString(Fragment.java:713)
	at net.osmand.plus.routepreparationmenu.AddPointBottomSheetDialog.createSwitchStartAndEndItem(AddPointBottomSheetDialog.java:324)
	at net.osmand.plus.routepreparationmenu.AddPointBottomSheetDialog.createMenuItems(AddPointBottomSheetDialog.java:130)
	at net.osmand.plus.base.MenuBottomSheetDialogFragment.onCreateView(MenuBottomSheetDialogFragment.java:72)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
    
can anybody help?

**Comment by Chumva** [comment]
There was an error with some translations which caused this crash, it should be fixed in 3.5.3.
