### ISSUE TITLE
 *.kmb bookmarks not supported (Maps.Me)

### ISSUE THREAD

**Issue by R3gi** [osmandapp/Osmand#8060]
OsmAnd crashes right after I select a bookmarks *.kmb file to import from [Maps.Me](https://play.google.com/store/apps/details?id=com.mapswithme.maps.pro).

Steps to reproduce:
1. Go to Main menu > My Places > Favorites
2. Tap "Import" button
3. Select file (from the /MapsWithMe/bookmarks/)
4. Observe: OsmAnd crashes

Expected behavior:
- OsmAnd doesn't crash on bookmarks file import.
- OsmAnd can import *.kmb files from Maps.Me app.

From my observations the app crashes when it is set to use default system language (in my case Czech), otherwise it displays modal that the file doesn't contain any bookmarks. In both cases it's impossible to import bookmarks file from Maps.Me.

Maps.Me 9.4.7-Google (191019)

Device : daisy_sprout
Brand : xiaomi
Model : Mi A2 Lite
Product : daisy
Build : PKQ1.180917.001.V10.0.16.0.PDLMIXM
Version : 9
App Version : OsmAnd~
Apk Version : 3.5.5 355

Crash log recorded by OsmAnd:
```
Version  OsmAnd~ 3.5.5
09.12.2019 10:21:30
Apk Version : 3.5.5 355
Exception occured in thread Thread[main,5,main] : 
java.util.UnknownFormatConversionException: Conversion = '$'
	at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2781)
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2811)
	at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2624)
	at java.util.Formatter.parse(Formatter.java:2557)
	at java.util.Formatter.format(Formatter.java:2504)
	at java.util.Formatter.format(Formatter.java:2458)
	at java.lang.String.format(String.java:2883)
	at android.content.res.Resources.getString(Resources.java:466)
	at android.content.Context.getString(Context.java:594)
	at net.osmand.plus.helpers.ImportHelper.importFavourites(ImportHelper.java:808)
	at net.osmand.plus.helpers.ImportHelper.access$400(ImportHelper.java:78)
	at net.osmand.plus.helpers.ImportHelper$2.onPostExecute(ImportHelper.java:261)
	at net.osmand.plus.helpers.ImportHelper$2.onPostExecute(ImportHelper.java:227)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.access$600(AsyncTask.java:180)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6694)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```

**Comment by vshcherb** [comment]
*.kmb file is not supported by OsmAnd and crash is fixed in the latest build.

**Comment by vshcherb** [comment]
KMB is a proprieatary format we're not going to support it.

**Comment by R3gi** [comment]
Thanks for information. Luckily, it seems [Maps.Me allows bookmarks export](https://support.maps.me/hc/en-us/articles/207894989-How-to-share-export-bookmarks-) in *.kml format too. Unfortunately OsmAnd crashes even on import of those standard *kml files. Hopefully this will be resolved by the fix you mentioned :-) Thanks again.

**Comment by vshcherb** [comment]
KML should be supported, so please test with English language and share example-kml if it doesn't work

**Comment by R3gi** [comment]
Import from KLM file (exported from Maps.Me) doesn't work either. Created separated #8097.
