### ISSUE TITLE
Exception when editing POI

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#8150]
The following exception occurs when trying to edit a POI but switching to another App _before_ OsmAnd finished downloading the POI from OSM:

```
Version  OsmAnd+ 3.5.5
25.12.2019 4:52:50
Apk Version : 3.5.5 355
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2053)
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2079)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:678)
	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:632)
	at android.support.v4.app.DialogFragment.show(DialogFragment.java:143)
	at net.osmand.plus.osmedit.EditPoiDialogFragment.show(EditPoiDialogFragment.java:397)
	at net.osmand.plus.osmedit.EditPoiDialogFragment$19.onPostExecute(EditPoiDialogFragment.java:729)
	at net.osmand.plus.osmedit.EditPoiDialogFragment$19.onPostExecute(EditPoiDialogFragment.java:719)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.-wrap1(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by vshcherb** [comment]
This activity is not supposed to work in the background
