### ISSUE TITLE
crash on 3.5.6#28852m 356 by start of navigation

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#8351]
Version  OsmAnd~ 3.5.6#28852m
29.01.2020 10:05:38
Apk Version : 3.5.6#28852m 356
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'double net.osmand.data.LatLon.getLatitude()' on a null object reference
	at net.osmand.util.MapUtils.getDistance(MapUtils.java:119)
	at net.osmand.plus.routing.RoutingHelper.checkAndUpdateStartLocation(RoutingHelper.java:270)
	at net.osmand.plus.TargetPointsHelper.updateMyLocationToStart(TargetPointsHelper.java:448)
	at net.osmand.plus.TargetPointsHelper.removeAllWayPoints(TargetPointsHelper.java:383)
	at net.osmand.plus.OsmandApplication.stopNavigation(OsmandApplication.java:562)
	at net.osmand.plus.activities.MapActivityActions.stopNavigationWithoutConfirm(MapActivityActions.java:1042)
	at net.osmand.plus.routepreparationmenu.MapRouteInfoMenu.onDismiss(MapRouteInfoMenu.java:2138)
	at net.osmand.plus.routepreparationmenu.MapRouteInfoMenuFragment.onDestroyView(MapRouteInfoMenuFragment.java:178)
	at android.support.v4.app.Fragment.performDestroyView(Fragment.java:2565)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1512)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
	at android.support.v4.app.BackStackRecord.executePopOps(BackStackRecord.java:851)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2593)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:7000)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
Version  OsmAnd~ 3.5.6#28852m
29.01.2020 10:06:32
Apk Version : 3.5.6#28852m 356
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'double net.osmand.Location.getLatitude()' on a null object reference
	at net.osmand.plus.routing.RoutingHelper.checkAndUpdateStartLocation(RoutingHelper.java:265)
	at net.osmand.plus.routing.RoutingHelper.setFinalAndCurrentLocation(RoutingHelper.java:177)
	at net.osmand.plus.TargetPointsHelper.updateRoutingHelper(TargetPointsHelper.java:459)
	at net.osmand.plus.TargetPointsHelper.updateRouteAndRefresh(TargetPointsHelper.java:438)
	at net.osmand.plus.activities.MapActivityActions.enterRoutePlanningModeGivenGpx(MapActivityActions.java:507)
	at net.osmand.plus.views.MapControlsLayer.startRoutePlanningWithDestination(MapControlsLayer.java:489)
	at net.osmand.plus.views.MapControlsLayer.navigateButton(MapControlsLayer.java:448)
	at net.osmand.plus.mapcontextmenu.MapContextMenu.navigateButtonPressed(MapContextMenu.java:956)
	at net.osmand.plus.mapcontextmenu.MapContextMenuFragment$17.onClick(MapContextMenuFragment.java:635)
	at android.view.View.performClick(View.java:6935)
	at android.widget.TextView.performClick(TextView.java:12752)
	at android.view.View$PerformClick.run(View.java:26214)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:7000)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
Version  OsmAnd~ 3.5.6#28852m
29.01.2020 10:07:13
Apk Version : 3.5.6#28852m 356
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'double net.osmand.Location.getLatitude()' on a null object reference
	at net.osmand.plus.routing.RoutingHelper.checkAndUpdateStartLocation(RoutingHelper.java:265)
	at net.osmand.plus.routing.RoutingHelper.setFinalAndCurrentLocation(RoutingHelper.java:177)
	at net.osmand.plus.TargetPointsHelper.updateRoutingHelper(TargetPointsHelper.java:459)
	at net.osmand.plus.TargetPointsHelper.updateRouteAndRefresh(TargetPointsHelper.java:438)
	at net.osmand.plus.activities.MapActivityActions.enterRoutePlanningModeGivenGpx(MapActivityActions.java:507)
	at net.osmand.plus.activities.MapActivityActions.enterRoutePlanningModeGivenGpx(MapActivityActions.java:485)
	at net.osmand.plus.activities.MapActivityActions.enterRoutePlanningMode(MapActivityActions.java:480)
	at net.osmand.plus.views.MapControlsLayer.onNavigationClick(MapControlsLayer.java:424)
	at net.osmand.plus.views.MapControlsLayer.doRoute(MapControlsLayer.java:404)
	at net.osmand.plus.views.MapControlsLayer$6.onClick(MapControlsLayer.java:397)
	at android.view.View.performClick(View.java:6935)
	at android.view.View$PerformClick.run(View.java:26214)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:7000)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
Version  OsmAnd~ 3.5.6#28852m
29.01.2020 10:07:54
Apk Version : 3.5.6#28852m 356
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'double net.osmand.Location.getLatitude()' on a null object reference
	at net.osmand.plus.routing.RoutingHelper.checkAndUpdateStartLocation(RoutingHelper.java:265)
	at net.osmand.plus.routing.RoutingHelper.setFinalAndCurrentLocation(RoutingHelper.java:177)
	at net.osmand.plus.TargetPointsHelper.updateRoutingHelper(TargetPointsHelper.java:459)
	at net.osmand.plus.TargetPointsHelper.updateRouteAndRefresh(TargetPointsHelper.java:438)
	at net.osmand.plus.activities.MapActivityActions.enterRoutePlanningModeGivenGpx(MapActivityActions.java:507)
	at net.osmand.plus.views.MapControlsLayer.startRoutePlanningWithDestination(MapControlsLayer.java:489)
	at net.osmand.plus.views.MapControlsLayer.navigateButton(MapControlsLayer.java:448)
	at net.osmand.plus.mapcontextmenu.MapContextMenu.navigateButtonPressed(MapContextMenu.java:956)
	at net.osmand.plus.mapcontextmenu.MapContextMenuFragment$17.onClick(MapContextMenuFragment.java:635)
	at android.view.View.performClick(View.java:6935)
	at android.widget.TextView.performClick(TextView.java:12752)
	at android.view.View$PerformClick.run(View.java:26214)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:7000)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
Version  OsmAnd~ 3.5.6#28852m
29.01.2020 10:08:36
Apk Version : 3.5.6#28852m 356
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'double net.osmand.Location.getLatitude()' on a null object reference
	at net.osmand.plus.routing.RoutingHelper.checkAndUpdateStartLocation(RoutingHelper.java:265)
	at net.osmand.plus.routing.RoutingHelper.setFinalAndCurrentLocation(RoutingHelper.java:177)
	at net.osmand.plus.TargetPointsHelper.updateRoutingHelper(TargetPointsHelper.java:459)
	at net.osmand.plus.TargetPointsHelper.updateRouteAndRefresh(TargetPointsHelper.java:438)
	at net.osmand.plus.activities.MapActivityActions.enterRoutePlanningModeGivenGpx(MapActivityActions.java:507)
	at net.osmand.plus.views.MapControlsLayer.startRoutePlanningWithDestination(MapControlsLayer.java:489)
	at net.osmand.plus.views.MapControlsLayer.navigateButton(MapControlsLayer.java:448)
	at net.osmand.plus.mapcontextmenu.MapContextMenu.navigateButtonPressed(MapContextMenu.java:956)
	at net.osmand.plus.mapcontextmenu.MapContextMenuFragment$17.onClick(MapContextMenuFragment.java:635)
	at android.view.View.performClick(View.java:6935)
	at android.widget.TextView.performClick(TextView.java:12752)
	at android.view.View$PerformClick.run(View.java:26214)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:7000)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
Version  OsmAnd~ 3.5.6#28852m
29.01.2020 10:09:58
Apk Version : 3.5.6#28852m 356
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'double net.osmand.Location.getLatitude()' on a null object reference
	at net.osmand.plus.routing.RoutingHelper.checkAndUpdateStartLocation(RoutingHelper.java:265)
	at net.osmand.plus.routing.RoutingHelper.setFinalAndCurrentLocation(RoutingHelper.java:177)
	at net.osmand.plus.TargetPointsHelper.updateRoutingHelper(TargetPointsHelper.java:459)
	at net.osmand.plus.TargetPointsHelper.updateRouteAndRefresh(TargetPointsHelper.java:438)
	at net.osmand.plus.activities.MapActivityActions.enterRoutePlanningModeGivenGpx(MapActivityActions.java:507)
	at net.osmand.plus.activities.MapActivityActions.enterRoutePlanningModeGivenGpx(MapActivityActions.java:485)
	at net.osmand.plus.activities.MapActivityActions.enterRoutePlanningMode(MapActivityActions.java:480)
	at net.osmand.plus.views.MapControlsLayer.onNavigationClick(MapControlsLayer.java:424)
	at net.osmand.plus.views.MapControlsLayer.doRoute(MapControlsLayer.java:404)
	at net.osmand.plus.views.MapControlsLayer$6.onClick(MapControlsLayer.java:397)
	at android.view.View.performClick(View.java:6935)
	at android.view.View$PerformClick.run(View.java:26214)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:7000)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
Version  OsmAnd~ 3.5.6#28852m
29.01.2020 10:11:40
Apk Version : 3.5.6#28852m 356
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'double net.osmand.Location.getLatitude()' on a null object reference
	at net.osmand.plus.routing.RoutingHelper.checkAndUpdateStartLocation(RoutingHelper.java:265)
	at net.osmand.plus.routing.RoutingHelper.setFinalAndCurrentLocation(RoutingHelper.java:177)
	at net.osmand.plus.TargetPointsHelper.updateRoutingHelper(TargetPointsHelper.java:459)
	at net.osmand.plus.TargetPointsHelper.updateRouteAndRefresh(TargetPointsHelper.java:438)
	at net.osmand.plus.activities.MapActivityActions.enterRoutePlanningModeGivenGpx(MapActivityActions.java:507)
	at net.osmand.plus.views.MapControlsLayer.startRoutePlanningWithDestination(MapControlsLayer.java:489)
	at net.osmand.plus.views.MapControlsLayer.navigateButton(MapControlsLayer.java:448)
	at net.osmand.plus.mapcontextmenu.MapContextMenu.navigateButtonPressed(MapContextMenu.java:956)
	at net.osmand.plus.mapcontextmenu.MapContextMenuFragment$17.onClick(MapContextMenuFragment.java:635)
	at android.view.View.performClick(View.java:6935)
	at android.widget.TextView.performClick(TextView.java:12752)
	at android.view.View$PerformClick.run(View.java:26214)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:7000)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by MadWasp79** [comment]
fixed with https://github.com/osmandapp/Osmand/pull/8348
