### ISSUE TITLE
Exception when adding favorite

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#8490]
I got the following exception while trying to add a favorite:

```
Version  OsmAnd+ 3.5.5
Apk Version : 3.5.5 355
Exception occured in thread Thread[main,5,main] : 
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.osmand.plus/net.osmand.plus.activities.MapActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String net.osmand.data.FavouritePoint.getCategory()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String net.osmand.data.FavouritePoint.getCategory()' on a null object reference
	at net.osmand.plus.FavouritesDbHelper.getGroup(FavouritesDbHelper.java:519)
	at net.osmand.plus.mapcontextmenu.editors.FavoritePointEditorFragment.onCreate(FavoritePointEditorFragment.java:64)
	at android.support.v4.app.Fragment.performCreate(Fragment.java:2331)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1386)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
	at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:3194)
	at android.support.v4.app.FragmentController.dispatchCreate(FragmentController.java:184)
	at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:355)
	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:84)
	at net.osmand.plus.activities.OsmandInAppPurchaseActivity.onCreate(OsmandInAppPurchaseActivity.java:39)
	at net.osmand.plus.activities.MapActivity.onCreate(MapActivity.java:269)
	at android.app.Activity.performCreate(Activity.java:7009)
	at android.app.Activity.performCreate(Activity.java:7000)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
	... 9 more
```

A map download was running for the current area. So I guess this was caused by trying to read from the map that was just reinitialized.

**Comment by vshcherb** [comment]
Fixed
