### ISSUE TITLE
Crashes when opening app in android.os.Parcel.readList

### ISSUE THREAD

**Issue by jmakovicka** [osmandapp/Osmand#8920]
Hi,

I started getting frequent crashes with latest master, possibly related to the switch to material components sliders, guessing from this very similar report: https://github.com/material-components/material-components-android/issues/793

Stack trace:

Version  OsmAnd~ 3.7.0
07.05.2020 8:17:54
Apk Version : 3.7.0 370
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.add(java.lang.Object)' on a null object reference
	at android.os.Parcel.readListInternal(Parcel.java:3309)
	at android.os.Parcel.readList(Parcel.java:2238)
	at com.google.android.material.slider.Slider$SliderState.<init>(Slider.java:2085)
	at com.google.android.material.slider.Slider$SliderState.<init>(Slider.java:2053)
	at com.google.android.material.slider.Slider$SliderState$1.createFromParcel(Slider.java:2067)
	at com.google.android.material.slider.Slider$SliderState$1.createFromParcel(Slider.java:2062)
	at android.os.Parcel.readParcelable(Parcel.java:2973)
	at android.os.Parcel.readValue(Parcel.java:2866)
	at android.os.Parcel.readSparseArrayInternal(Parcel.java:3327)
	at android.os.Parcel.readSparseArray(Parcel.java:2484)
	at android.os.Parcel.readValue(Parcel.java:2923)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:3244)
	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
	at android.os.BaseBundle.unparcel(BaseBundle.java:236)
	at android.os.Bundle.getSparseParcelableArray(Bundle.java:1029)
	at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2156)
	at android.app.Activity.onRestoreInstanceState(Activity.java:1563)
	at android.app.Activity.performRestoreInstanceState(Activity.java:1518)
	at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1347)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3311)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by jmakovicka** [comment]
I updated material to com.google.android.material:material:1.2.0-alpha06 which should contain a fix, seen no crashes so far.

**Comment by vshcherb** [comment]
Yes , we saw crashes though didn't understand where it comes from. Was it specific to one screen or on all with sliders

**Comment by vshcherb** [comment]
Yes , we saw crashes though didn't understand where it comes from. Was it specific to one screen or on all with sliders

**Comment by jmakovicka** [comment]
I always encountered this when reopening the app, not when using it. And the stacktrace is not very helpful.
