### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#8927]
```
Version  OsmAnd+ 3.7.0
09.05.2020 8:44:03
Apk Version : 3.7.0 370
Exception occured in thread Thread[main,5,main] : 
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.osmand.plus/net.osmand.plus.activities.MapActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.add(java.lang.Object)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.add(java.lang.Object)' on a null object reference
	at android.os.Parcel.readListInternal(Parcel.java:3186)
	at android.os.Parcel.readList(Parcel.java:2187)
	at com.google.android.material.slider.Slider$SliderState.<init>(Slider.java:2085)
	at com.google.android.material.slider.Slider$SliderState.<init>(Slider.java:2053)
	at com.google.android.material.slider.Slider$SliderState$1.createFromParcel(Slider.java:2067)
	at com.google.android.material.slider.Slider$SliderState$1.createFromParcel(Slider.java:2062)
	at android.os.Parcel.readParcelable(Parcel.java:2860)
	at android.os.Parcel.readValue(Parcel.java:2754)
	at android.os.Parcel.readSparseArrayInternal(Parcel.java:3204)
	at android.os.Parcel.readSparseArray(Parcel.java:2416)
	at android.os.Parcel.readValue(Parcel.java:2811)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:3123)
	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:273)
	at android.os.BaseBundle.unparcel(BaseBundle.java:226)
	at android.os.Bundle.getSparseParcelableArray(Bundle.java:1009)
	at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2129)
	at android.app.Activity.onRestoreInstanceState(Activity.java:1102)
	at android.app.Activity.performRestoreInstanceState(Activity.java:1057)
	at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1260)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2751)
	... 9 more
Version  OsmAnd+ 3.7.0
09.05.2020 12:45:23
Apk Version : 3.7.0 370
Exception occured in thread Thread[main,5,main] : 
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.osmand.plus/net.osmand.plus.activities.MapActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.add(java.lang.Object)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.add(java.lang.Object)' on a null object reference
	at android.os.Parcel.readListInternal(Parcel.java:3186)
	at android.os.Parcel.readList(Parcel.java:2187)
	at com.google.android.material.slider.Slider$SliderState.<init>(Slider.java:2085)
	at com.google.android.material.slider.Slider$SliderState.<init>(Slider.java:2053)
	at com.google.android.material.slider.Slider$SliderState$1.createFromParcel(Slider.java:2067)
	at com.google.android.material.slider.Slider$SliderState$1.createFromParcel(Slider.java:2062)
	at android.os.Parcel.readParcelable(Parcel.java:2860)
	at android.os.Parcel.readValue(Parcel.java:2754)
	at android.os.Parcel.readSparseArrayInternal(Parcel.java:3204)
	at android.os.Parcel.readSparseArray(Parcel.java:2416)
	at android.os.Parcel.readValue(Parcel.java:2811)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:3123)
	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:273)
	at android.os.BaseBundle.unparcel(BaseBundle.java:226)
	at android.os.Bundle.getSparseParcelableArray(Bundle.java:1009)
	at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2129)
	at android.app.Activity.onRestoreInstanceState(Activity.java:1102)
	at android.app.Activity.performRestoreInstanceState(Activity.java:1057)
	at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1260)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2751)
	... 9 more
```

**Comment by scaidermern** [comment]
Sorry, duplicate of  #8920.
