### ISSUE TITLE
Osmand always crashes on startup

### ISSUE THREAD

**Issue by devdan** [osmandapp/Osmand#9216]
Device: Samsung Galaxy S5 (klte) running LineageOS 16.0

When starting Osmand, it always crashes. I currently tested with Version 3.7.3, but I think it happened with older versions as well. 
It seems there are issues accessing files in /data/user/0/
It crashes before asking for any permissions. I tried to give it storage permission manually, but it didn't help.
The SD card is adopted, if this information helps.

This is the output from logcat:

```
2020-06-11 23:32:48.192 596-1134/? I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=net.osmand.plus/.activities.MapActivity bnds=[36,590][204,837]} from uid 10137
2020-06-11 23:32:48.257 596-655/? I/ActivityManager: Start proc 9356:net.osmand.plus/u0a220 for activity net.osmand.plus/.activities.MapActivity
    
    --------- beginning of main
2020-06-11 23:32:48.268 9356-9356/? W/main: type=1400 audit(0.0:29704): avc: denied { read } for name="u:object_r:alarm_boot_prop:s0" dev="tmpfs" ino=6992 scontext=u:r:untrusted_app:s0:c220,c256,c512,c768 tcontext=u:object_r:alarm_boot_prop:s0 tclass=file permissive=0
2020-06-11 23:32:48.314 9356-9356/? E/net.osmand.plu: Not starting debugger since process cannot load the jdwp agent.
2020-06-11 23:32:48.354 596-1274/? W/ActivityManager: Request to remove task ignored for non-existent task 14258
2020-06-11 23:32:48.476 9356-9356/? W/net.osmand.plu: JIT profile information will not be recorded: profile file does not exits.
2020-06-11 23:32:48.488 9356-9356/? W/ContextImpl: Failed to ensure /data/user/0/net.osmand.plus/cache: mkdir failed: ENOENT (No such file or directory)
2020-06-11 23:32:48.489 9356-9356/? W/ContextImpl: Failed to update user.inode_cache: stat failed: ENOENT (No such file or directory)
2020-06-11 23:32:48.490 9356-9356/? W/ContextImpl: Failed to ensure /data/user_de/0/net.osmand.plus/code_cache: mkdir failed: ENOENT (No such file or directory)
2020-06-11 23:32:48.490 9356-9356/? W/ContextImpl: Failed to update user.inode_code_cache: stat failed: ENOENT (No such file or directory)
2020-06-11 23:32:48.536 9356-9356/? I/MultiDex: VM with version 2.1.0 has multidex support
2020-06-11 23:32:48.536 9356-9356/? I/MultiDex: Installing application
2020-06-11 23:32:48.536 9356-9356/? I/MultiDex: VM has multidex support, MultiDex support library is disabled.
2020-06-11 23:32:48.536 9356-9356/? I/MultiDex: Installing application
2020-06-11 23:32:48.536 9356-9356/? I/MultiDex: VM has multidex support, MultiDex support library is disabled.
2020-06-11 23:32:48.552 9356-9356/? W/ContextImpl: Failed to ensure /data/user/0/net.osmand.plus/cache: mkdir failed: ENOENT (No such file or directory)
2020-06-11 23:32:48.552 9356-9356/? W/ContextImpl: Failed to update user.inode_cache: stat failed: ENOENT (No such file or directory)
2020-06-11 23:32:48.573 9356-9356/? W/ContextImpl: Failed to ensure /data/user/0/net.osmand.plus/files: mkdir failed: ENOENT (No such file or directory)
2020-06-11 23:32:48.641 9356-9356/? W/ContextImpl: Failed to ensure /data/user/0/net.osmand.plus/shared_prefs: mkdir failed: ENOENT (No such file or directory)
2020-06-11 23:32:48.686 9356-9356/? I/chatty: uid=10220(net.osmand.plus) identical 7 lines
2020-06-11 23:32:48.689 9356-9356/? W/ContextImpl: Failed to ensure /data/user/0/net.osmand.plus/shared_prefs: mkdir failed: ENOENT (No such file or directory)
2020-06-11 23:32:48.703 9356-9356/? E/SharedPreferencesImpl: Couldn't create directory for SharedPreferences file /data/user/0/net.osmand.plus/shared_prefs/net.osmand.settings.default.xml
2020-06-11 23:32:48.704 9356-9356/? E/SharedPreferencesImpl: Couldn't create directory for SharedPreferences file /data/user/0/net.osmand.plus/shared_prefs/net.osmand.settings.car.xml
2020-06-11 23:32:48.704 9356-9356/? E/SharedPreferencesImpl: Couldn't create directory for SharedPreferences file /data/user/0/net.osmand.plus/shared_prefs/net.osmand.settings.bicycle.xml
2020-06-11 23:32:48.705 9356-9356/? E/SharedPreferencesImpl: Couldn't create directory for SharedPreferences file /data/user/0/net.osmand.plus/shared_prefs/net.osmand.settings.pedestrian.xml
2020-06-11 23:32:48.705 9356-9356/? E/SharedPreferencesImpl: Couldn't create directory for SharedPreferences file /data/user/0/net.osmand.plus/shared_prefs/net.osmand.settings.public_transport.xml
2020-06-11 23:32:48.705 9356-9356/? E/SharedPreferencesImpl: Couldn't create directory for SharedPreferences file /data/user/0/net.osmand.plus/shared_prefs/net.osmand.settings.boat.xml
2020-06-11 23:32:48.706 9356-9356/? E/SharedPreferencesImpl: Couldn't create directory for SharedPreferences file /data/user/0/net.osmand.plus/shared_prefs/net.osmand.settings.aircraft.xml
2020-06-11 23:32:48.706 9356-9356/? E/SharedPreferencesImpl: Couldn't create directory for SharedPreferences file /data/user/0/net.osmand.plus/shared_prefs/net.osmand.settings.ski.xml
2020-06-11 23:32:48.714 9356-9356/? W/ContextImpl: Failed to ensure /data/user/0/net.osmand.plus/shared_prefs: mkdir failed: ENOENT (No such file or directory)
2020-06-11 23:32:48.718 9356-9356/? E/SharedPreferencesImpl: Couldn't create directory for SharedPreferences file /data/user/0/net.osmand.plus/shared_prefs/activities.MapActivity.xml
2020-06-11 23:32:48.720 9356-9356/? I/chatty: uid=10220(net.osmand.plus) identical 3 lines
2020-06-11 23:32:48.720 9356-9356/? E/SharedPreferencesImpl: Couldn't create directory for SharedPreferences file /data/user/0/net.osmand.plus/shared_prefs/activities.MapActivity.xml
2020-06-11 23:32:48.729 9356-9356/? E/SharedPreferencesImpl: Couldn't create directory for SharedPreferences file /data/user/0/net.osmand.plus/shared_prefs/net.osmand.settings.xml
2020-06-11 23:32:48.736 596-615/? W/ActivityManager: Unable to start service Intent { cmp=btools.routingapp/.BRouterService } U=0: not found
2020-06-11 23:32:48.732 9356-9356/? E/SharedPreferencesImpl: Couldn't create directory for SharedPreferences file /data/user/0/net.osmand.plus/shared_prefs/net.osmand.settings.xml
2020-06-11 23:32:48.764 9356-9356/? W/System.err: Startup service net.osmand.plus.inapp.InAppPurchaseHelper took too long 28 ms
2020-06-11 23:32:48.785 9356-9356/? I/net.osmand: ResourceManager Bitmap tiles to load in memory : 162.0
2020-06-11 23:32:48.789 9356-9356/? W/System.err: Startup service net.osmand.plus.resources.ResourceManager took too long 22 ms
2020-06-11 23:32:48.802 9356-9356/? W/ContextImpl: Failed to ensure /data/user/0/net.osmand.plus/databases: mkdir failed: ENOENT (No such file or directory)
2020-06-11 23:32:48.806 9356-9356/? E/SQLiteLog: (14) cannot open file at line 36667 of [68b898381a]
2020-06-11 23:32:48.807 9356-9356/? E/SQLiteLog: (14) os_unix.c:36667: (2) open(/data/user/0/net.osmand.plus/databases/analytics) - 
2020-06-11 23:32:48.820 9356-9356/? E/SQLiteDatabase: Failed to open database '/data/user/0/net.osmand.plus/databases/analytics'.
    android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14 SQLITE_CANTOPEN): Could not open database
        at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:212)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:196)
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:503)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:204)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:196)
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:880)
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:865)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:739)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:729)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:355)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:298)
        at net.osmand.plus.AnalyticsHelper.getCollectedRowsCount(AnalyticsHelper.java:102)
        at net.osmand.plus.AnalyticsHelper.submitCollectedDataAsync(AnalyticsHelper.java:129)
        at net.osmand.plus.AnalyticsHelper.<init>(AnalyticsHelper.java:83)
        at net.osmand.plus.AppInitializer.onCreateApplication(AppInitializer.java:440)
        at net.osmand.plus.OsmandApplication.onCreate(OsmandApplication.java:208)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5920)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2020-06-11 23:32:48.820 9356-9356/? W/System.err: Startup service net.osmand.plus.AnalyticsHelper took too long 23 ms
2020-06-11 23:32:48.831 9356-9356/? W/System.err: Startup service net.osmand.plus.NotificationHelper took too long 11 ms
2020-06-11 23:32:48.833 9356-9356/? W/ContextImpl: Failed to ensure /data/user/0/net.osmand.plus/databases: mkdir failed: ENOENT (No such file or directory)
2020-06-11 23:32:48.833 9356-9356/? E/SQLiteLog: (14) cannot open file at line 36667 of [68b898381a]
2020-06-11 23:32:48.833 9356-9356/? E/SQLiteLog: (14) os_unix.c:36667: (2) open(/data/user/0/net.osmand.plus/databases/gpx_database) - 
2020-06-11 23:32:48.834 9356-9356/? E/SQLiteDatabase: Failed to open database '/data/user/0/net.osmand.plus/databases/gpx_database'.
    android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14 SQLITE_CANTOPEN): Could not open database
        at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:212)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:196)
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:503)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:204)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:196)
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:880)
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:865)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:766)
        at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:772)
        at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:757)
        at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:306)
        at net.osmand.plus.api.SQLiteAPIImpl.getOrCreateDatabase(SQLiteAPIImpl.java:27)
        at net.osmand.plus.GPXDatabase.openConnection(GPXDatabase.java:244)
        at net.osmand.plus.GPXDatabase.<init>(GPXDatabase.java:237)
        at net.osmand.plus.GpxDbHelper.<init>(GpxDbHelper.java:43)
        at net.osmand.plus.AppInitializer.onCreateApplication(AppInitializer.java:444)
        at net.osmand.plus.OsmandApplication.onCreate(OsmandApplication.java:208)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5920)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2020-06-11 23:32:48.834 9356-9356/? E/net.osmand: SQLiteAPIImpl unknown error (code 14 SQLITE_CANTOPEN): Could not open database
    android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14 SQLITE_CANTOPEN): Could not open database
        at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:212)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:196)
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:503)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:204)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:196)
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:880)
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:865)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:766)
        at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:772)
        at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:757)
        at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:306)
        at net.osmand.plus.api.SQLiteAPIImpl.getOrCreateDatabase(SQLiteAPIImpl.java:27)
        at net.osmand.plus.GPXDatabase.openConnection(GPXDatabase.java:244)
        at net.osmand.plus.GPXDatabase.<init>(GPXDatabase.java:237)
        at net.osmand.plus.GpxDbHelper.<init>(GpxDbHelper.java:43)
        at net.osmand.plus.AppInitializer.onCreateApplication(AppInitializer.java:444)
        at net.osmand.plus.OsmandApplication.onCreate(OsmandApplication.java:208)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5920)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2020-06-11 23:32:48.843 9356-9356/? W/ContextImpl: Failed to ensure /data/user/0/net.osmand.plus/databases: mkdir failed: ENOENT (No such file or directory)
2020-06-11 23:32:48.843 9356-9356/? E/SQLiteLog: (14) cannot open file at line 36667 of [68b898381a]
2020-06-11 23:32:48.843 9356-9356/? E/SQLiteLog: (14) os_unix.c:36667: (2) open(/data/user/0/net.osmand.plus/databases/poi_filters) - 
2020-06-11 23:32:48.844 9356-9356/? E/SQLiteDatabase: Failed to open database '/data/user/0/net.osmand.plus/databases/poi_filters'.
    android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14 SQLITE_CANTOPEN): Could not open database
        at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:212)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:196)
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:503)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:204)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:196)
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:880)
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:865)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:766)
        at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:772)
        at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:757)
        at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:306)
        at net.osmand.plus.api.SQLiteAPIImpl.getOrCreateDatabase(SQLiteAPIImpl.java:27)
        at net.osmand.plus.poi.PoiFiltersHelper$PoiFilterDbHelper.openConnection(PoiFiltersHelper.java:714)
        at net.osmand.plus.poi.PoiFiltersHelper$PoiFilterDbHelper.getWritableDatabase(PoiFiltersHelper.java:699)
        at net.osmand.plus.poi.PoiFiltersHelper$PoiFilterDbHelper.doDeletion(PoiFiltersHelper.java:760)
        at net.osmand.plus.poi.PoiFiltersHelper.<init>(PoiFiltersHelper.java:81)
        at net.osmand.plus.AppInitializer.onCreateApplication(AppInitializer.java:452)
        at net.osmand.plus.OsmandApplication.onCreate(OsmandApplication.java:208)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5920)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2020-06-11 23:32:48.844 9356-9356/? E/net.osmand: SQLiteAPIImpl unknown error (code 14 SQLITE_CANTOPEN): Could not open database
    android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14 SQLITE_CANTOPEN): Could not open database
        at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:212)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:196)
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:503)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:204)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:196)
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:880)
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:865)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:766)
        at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:772)
        at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:757)
        at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:306)
        at net.osmand.plus.api.SQLiteAPIImpl.getOrCreateDatabase(SQLiteAPIImpl.java:27)
        at net.osmand.plus.poi.PoiFiltersHelper$PoiFilterDbHelper.openConnection(PoiFiltersHelper.java:714)
        at net.osmand.plus.poi.PoiFiltersHelper$PoiFilterDbHelper.getWritableDatabase(PoiFiltersHelper.java:699)
        at net.osmand.plus.poi.PoiFiltersHelper$PoiFilterDbHelper.doDeletion(PoiFiltersHelper.java:760)
        at net.osmand.plus.poi.PoiFiltersHelper.<init>(PoiFiltersHelper.java:81)
        at net.osmand.plus.AppInitializer.onCreateApplication(AppInitializer.java:452)
        at net.osmand.plus.OsmandApplication.onCreate(OsmandApplication.java:208)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5920)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2020-06-11 23:32:48.854 9356-9356/? D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2020-06-11 23:32:48.856 9356-9356/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.osmand.plus, PID: 9356
    java.lang.RuntimeException: Unable to create application net.osmand.plus.OsmandApplication: java.lang.NullPointerException: Attempt to invoke interface method 'int net.osmand.plus.api.SQLiteAPI$SQLiteConnection.getVersion()' on a null object reference
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5925)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int net.osmand.plus.api.SQLiteAPI$SQLiteConnection.getVersion()' on a null object reference
        at net.osmand.plus.poi.PoiFiltersHelper$PoiFilterDbHelper.openConnection(PoiFiltersHelper.java:715)
        at net.osmand.plus.poi.PoiFiltersHelper$PoiFilterDbHelper.getWritableDatabase(PoiFiltersHelper.java:699)
        at net.osmand.plus.poi.PoiFiltersHelper$PoiFilterDbHelper.doDeletion(PoiFiltersHelper.java:760)
        at net.osmand.plus.poi.PoiFiltersHelper.<init>(PoiFiltersHelper.java:81)
        at net.osmand.plus.AppInitializer.onCreateApplication(AppInitializer.java:452)
        at net.osmand.plus.OsmandApplication.onCreate(OsmandApplication.java:208)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5920)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6718) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2020-06-11 23:32:48.888 596-9391/? W/DropBoxManagerService: Dropping: data_app_crash (1895 > 0 bytes)
2020-06-11 23:32:48.898 596-2005/? W/ActivityManager:   Force finishing activity net.osmand.plus/.activities.MapActivity
2020-06-11 23:32:48.934 9356-9356/? I/Process: Sending signal. PID: 9356 SIG: 9
2020-06-11 23:32:48.950 596-617/? I/ActivityManager: Process net.osmand.plus (pid 9356) has died: fore TOP 
2020-06-11 23:32:48.950 596-656/? W/libprocessgroup: kill(-9356, 9) failed: No such process
2020-06-11 23:32:48.950 596-656/? I/libprocessgroup: Successfully killed process cgroup uid 10220 pid 9356 in 0ms
2020-06-11 23:32:48.955 435-1339/? W/SurfaceFlinger: Attempting to set client state on removed layer: Splash Screen net.osmand.plus#0
2020-06-11 23:32:48.956 435-1339/? W/SurfaceFlinger: Attempting to destroy on removed layer: Splash Screen net.osmand.plus#0
2020-06-11 23:32:48.962 405-405/? I/Zygote: Process 9356 exited due to signal (9)
2020-06-11 23:32:48.965 596-802/? W/WindowManager: Failed looking up window callers=com.android.server.wm.WindowManagerService.windowForClientLocked:5525 com.android.server.wm.WindowManagerService.removeWindow:1641 com.android.server.wm.Session.remove:226 
2020-06-11 23:32:49.004 1539-1700/? W/Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
2020-06-11 23:32:49.005 1539-1700/? D/vndksupport: Loading /vendor/lib/hw/gralloc.msm8974.so from current namespace instead of sphal namespace.
```

**Comment by vshcherb** [comment]
It looks like data was corrupted inside, make data backup from sdcard (maps, favorites, gpx) and please reinstall.

**Comment by devdan** [comment]
I reinstalled several times and also deleted all the files from sd card related to Osmand but it still crashed on startup.

**Comment by devdan** [comment]
I just tried the free version and it works! However, Osmand+ crashes, no matter if I install it from f-droid or Play Store.

**Comment by sonora** [comment]
It looks like the internal app data became corrupted, not necessarily that on SD card.

Hence after you have  backed up your files .please uninstall before reinstalling. Alternatively, in Android's app manager, delete all app data.

**Comment by devdan** [comment]
I did that several times: Delete data, uninstall app, install again. The result is always the same.

For some reasons, the free version does not crash.

**Comment by sonora** [comment]
@vshcherb  Do we still have Firebase in the plus version? I have seen issues in other apps where certain combinations of outdated Firebase version but newer Play Services caused issies like Not starting debugger since process cannot load the jdwp agent'.

I also noted that there are some occurrences of 'net.osmand.plu' (without the trailing 's') in the logcat provided, that also seems odd?

**Comment by vshcherb** [comment]
Nope no firebase

**Comment by devdan** [comment]
I just compiled Osmand+ from source as a debug build to be able to debug the issue, but to my surprise, it didn't crash at all and worked fine. 

Is the only difference debug vs. release here or do you build it in a special way before releasing it to the store?
