### ISSUE TITLE
OsmAnd~ 3.7.4 crashs 2-3 times during normal daily hiking tour

### ISSUE THREAD

**Issue by ironspock** [osmandapp/Osmand#9521]
I'm using 
 OsmAnd~ 3.7.4 with offline maps on a CATS30 with Android 5.1

During a normal daily hiking tour (4-6 hours) with normal usage of OsmAnd~ 3.7.4 (zooming in/out, switching maps layout (global <-> hiking), following track, collecting track information etc.) the App is crashing approx 2-3 times.

Similar behavior I was already facing in previous versions.
Refer to part of the exception.log file below (it's always similar with different size of byte allocation)

Version  OsmAnd~ 3.7.4
26.07.2020 12:25:39
Apk Version : 3.7.4 374
Exception occured in thread Thread[RenderingBaseImage,5,main] : 
java.lang.OutOfMemoryError: Failed to allocate a 465136 byte allocation with 211544 free bytes and 206KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:812)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:720)
	at net.osmand.plus.views.MapTileLayer.drawTileMap(MapTileLayer.java:249)
	at net.osmand.plus.views.MapTileLayer.onPrepareBufferImage(MapTileLayer.java:128)
	at net.osmand.plus.srtmplugin.TerrainLayer.onPrepareBufferImage(TerrainLayer.java:68)
	at net.osmand.plus.views.OsmandMapTileView.refreshBaseMapInternal(OsmandMapTileView.java:601)
	at net.osmand.plus.views.OsmandMapTileView.access$900(OsmandMapTileView.java:64)
	at net.osmand.plus.views.OsmandMapTileView$2.run(OsmandMapTileView.java:803)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by vshcherb** [comment]
it is quite strange cause it could be an older problem which is related to lack of free memory. We will need to investigate what's causing such type of memory leak after 1-2 hour usage.
