### ISSUE TITLE
Track matching: Exception when trying to match GPX track to road

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#9772]
The new GPX track to road matching feature (#3908) leads to the following exception after pressing the finish/done button:

```
Version  OsmAnd Nightly 3.7.0#27564d
09.09.2020 7:39:27
Apk Version : 3.7.0#27564d 370
Exception occured in thread Thread[AsyncTask #11,5,main] : 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
	at java.util.ArrayList.remove(ArrayList.java:506)
	at net.osmand.plus.measurementtool.MeasurementEditingContext.exportRouteAsGpx(MeasurementEditingContext.java:745)
	at net.osmand.plus.measurementtool.MeasurementToolFragment$26.doInBackground(MeasurementToolFragment.java:1663)
	at net.osmand.plus.measurementtool.MeasurementToolFragment$26.doInBackground(MeasurementToolFragment.java:1582)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
```

**Comment by scaidermern** [comment]
Example GPX file for which this exception occurs: [foo.gpx.txt](https://github.com/osmandapp/OsmAnd/files/5199432/foo.gpx.txt)

**Comment by scaidermern** [comment]
Fixed, thanks!
