### ISSUE TITLE
NullPointerException at net.osmand.plus.myplaces.AvailableGPXFragment$GpxIndexesAdapter$2.compare

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#9874]
After recording and saving a track, opening My Places -> Tracks leads to the following exception:

```
Version  OsmAnd+ 3.8.1
22.09.2020 5:12:49
Apk Version : 3.8.1 381
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to invoke virtual method 'long java.io.File.lastModified()' on a null object reference
	at net.osmand.plus.myplaces.AvailableGPXFragment$GpxIndexesAdapter$2.compare(AvailableGPXFragment.java:1084)
	at net.osmand.plus.myplaces.AvailableGPXFragment$GpxIndexesAdapter$2.compare(AvailableGPXFragment.java:1078)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1492)
	at java.util.ArrayList.sort(ArrayList.java:1470)
	at java.util.Collections.sort(Collections.java:206)
	at net.osmand.plus.myplaces.AvailableGPXFragment$GpxIndexesAdapter.refreshSelected(AvailableGPXFragment.java:1078)
	at net.osmand.plus.myplaces.AvailableGPXFragment$LoadGpxTask.onPostExecute(AvailableGPXFragment.java:957)
	at net.osmand.plus.myplaces.AvailableGPXFragment$LoadGpxTask.onPostExecute(AvailableGPXFragment.java:907)
	at android.os.AsyncTask.finish(AsyncTask.java:755)
	at android.os.AsyncTask.access$900(AsyncTask.java:192)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

This exception persists. The only option is to disable the newly recorded track via Configure Map -> Tracks.

**Comment by max-klaus** [comment]
Fixed by https://github.com/osmandapp/Osmand/commit/525ce78e003b8e62b860ceb0b067f80f4194fe0f
